### ISSUE TITLE
with firebase authentication cannot find module '@firebase/app' after npm install

### ISSUE THREAD

**Issue by waldothedeveloper** [zeit/next.js#10025]
# bug report

## Describe the bug

After having an issue  with ```npm install```  I read that with npm install firebase@latest as well as firebase-admin the issues should go away. Here's the package.json:

// package.json
```
{
  "name": "with-firebase",
  "version": "1.0.0",
  "scripts": {
    "dev": "node server.js",
    "build": "next build",
    "start": "NODE_ENV=production node server.js"
  },
  "dependencies": {
    "body-parser": "^1.17.1",
    "express": "^4.14.0",
    "express-session": "^1.15.2",
    "firebase": "^7.6.2",
    "firebase-admin": "^8.9.0",
    "isomorphic-unfetch": "^3.0.0",
    "next": "latest",
    "react": "^16.7.0",
    "react-dom": "^16.7.0",
    "session-file-store": "^1.0.0"
  }
}
```

Following with a successful npm install I run ```npm run dev``` and I also tried ```node server.js``` 
but I'm getting: 

```
Module not found: Can't resolve '@firebase/app' in '/Users/waldolavautnazario/Downloads/with-firebase-authentication/node_modules/@firebase/firestore/dist'
Error: Cannot find module '@firebase/app'
```

I tried changing the import of firebase like this: 
```
import * as firebase from "firebase/app";
```

and also on ```ComponentDidMount``` I added this:

```
 if (!firebase.apps.length) {
      firebase.initializeApp(clientCredentials);
    }
```

But I'm still getting the same error. I tried using ```canary``` as well as ```master``` branches but the error still persist.
Here are the full logs of the console: 

```
node server.js
[ ready ] compiled successfully
> Ready on http://localhost:3000
[ event ] build page: /next/dist/pages/_error
[ wait ]  compiling ...
[ ready ] compiled successfully
[ event ] build page: /
[ wait ]  compiling ...
[ error ] ./node_modules/@firebase/firestore/dist/index.cjs.js
Module not found: Can't resolve '@firebase/app' in '/Users/waldolavautnazario/Downloads/with-firebase-authentication/node_modules/@firebase/firestore/dist'
Error: Cannot find module '@firebase/app'
Require stack:
- /Users/waldolavautnazario/Downloads/with-firebase-authentication/node_modules/@firebase/firestore/dist/index.node.cjs.js
- /Users/waldolavautnazario/Downloads/with-firebase-authentication/node_modules/firebase/firestore/dist/index.cjs.js
- /Users/waldolavautnazario/Downloads/with-firebase-authentication/.next/server/static/development/pages/index.js
- /Users/waldolavautnazario/Downloads/with-firebase-authentication/node_modules/next/dist/next-server/server/require.js
- /Users/waldolavautnazario/Downloads/with-firebase-authentication/node_modules/next/dist/next-server/server/load-components.js
- /Users/waldolavautnazario/Downloads/with-firebase-authentication/node_modules/next/dist/next-server/server/api-utils.js
- /Users/waldolavautnazario/Downloads/with-firebase-authentication/node_modules/next/dist/next-server/server/next-server.js
- /Users/waldolavautnazario/Downloads/with-firebase-authentication/node_modules/next/dist/server/next.js
- /Users/waldolavautnazario/Downloads/with-firebase-authentication/server.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:973:15)
    at Function.Module._load (internal/modules/cjs/loader.js:855:27)
    at Module.require (internal/modules/cjs/loader.js:1033:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/Users/waldolavautnazario/Downloads/with-firebase-authentication/node_modules/@firebase/firestore/dist/index.node.cjs.js:7:32)
    at Module._compile (internal/modules/cjs/loader.js:1144:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1164:10)
    at Module.load (internal/modules/cjs/loader.js:993:32)
    at Function.Module._load (internal/modules/cjs/loader.js:892:14)
    at Module.require (internal/modules/cjs/loader.js:1033:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/Users/waldolavautnazario/Downloads/with-firebase-authentication/node_modules/firebase/firestore/dist/index.cjs.js:3:1)
    at Module._compile (internal/modules/cjs/loader.js:1144:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1164:10)
    at Module.load (internal/modules/cjs/loader.js:993:32)
    at Function.Module._load (internal/modules/cjs/loader.js:892:14) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/waldolavautnazario/Downloads/with-firebase-authentication/node_modules/@firebase/firestore/dist/index.node.cjs.js',
    '/Users/waldolavautnazario/Downloads/with-firebase-authentication/node_modules/firebase/firestore/dist/index.cjs.js',
    '/Users/waldolavautnazario/Downloads/with-firebase-authentication/.next/server/static/development/pages/index.js',
    '/Users/waldolavautnazario/Downloads/with-firebase-authentication/node_modules/next/dist/next-server/server/require.js',
    '/Users/waldolavautnazario/Downloads/with-firebase-authentication/node_modules/next/dist/next-server/server/load-components.js',
    '/Users/waldolavautnazario/Downloads/with-firebase-authentication/node_modules/next/dist/next-server/server/api-utils.js',
    '/Users/waldolavautnazario/Downloads/with-firebase-authentication/node_modules/next/dist/next-server/server/next-server.js',
    '/Users/waldolavautnazario/Downloads/with-firebase-authentication/node_modules/next/dist/server/next.js',
    '/Users/waldolavautnazario/Downloads/with-firebase-authentication/server.js'
  ]
}
ModuleNotFoundError: Module not found: Error: Can't resolve '@firebase/app' in '/Users/waldolavautnazario/Downloads/with-firebase-authentication/node_modules/@firebase/firestore/dist'
    at /Users/waldolavautnazario/Downloads/with-firebase-authentication/node_modules/webpack/lib/Compilation.js:925:10
    at /Users/waldolavautnazario/Downloads/with-firebase-authentication/node_modules/webpack/lib/NormalModuleFactory.js:401:22
    at /Users/waldolavautnazario/Downloads/with-firebase-authentication/node_modules/webpack/lib/NormalModuleFactory.js:130:21
    at /Users/waldolavautnazario/Downloads/with-firebase-authentication/node_modules/webpack/lib/NormalModuleFactory.js:224:22
    at /Users/waldolavautnazario/Downloads/with-firebase-authentication/node_modules/neo-async/async.js:2830:7
    at /Users/waldolavautnazario/Downloads/with-firebase-authentication/node_modules/neo-async/async.js:6877:13
    at /Users/waldolavautnazario/Downloads/with-firebase-authentication/node_modules/webpack/lib/NormalModuleFactory.js:214:25
    at /Users/waldolavautnazario/Downloads/with-firebase-authentication/node_modules/enhanced-resolve/lib/Resolver.js:213:14
    at /Users/waldolavautnazario/Downloads/with-firebase-authentication/node_modules/enhanced-resolve/lib/Resolver.js:285:5
    at eval (eval at create (/Users/waldolavautnazario/Downloads/with-firebase-authentication/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:13:1)
    at /Users/waldolavautnazario/Downloads/with-firebase-authentication/node_modules/enhanced-resolve/lib/UnsafeCachePlugin.js:44:7
    at /Users/waldolavautnazario/Downloads/with-firebase-authentication/node_modules/enhanced-resolve/lib/Resolver.js:285:5
    at eval (eval at create (/Users/waldolavautnazario/Downloads/with-firebase-authentication/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:13:1)
    at /Users/waldolavautnazario/Downloads/with-firebase-authentication/node_modules/enhanced-resolve/lib/Resolver.js:285:5
    at eval (eval at create (/Users/waldolavautnazario/Downloads/with-firebase-authentication/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:25:1)
    at /Users/waldolavautnazario/Downloads/with-firebase-authentication/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:67:43
```
## To Reproduce
You can use your own example: 
[with-firebase-authentication](https://github.com/zeit/next.js/tree/canary/examples/with-firebase-authentication) with or without updating to the lastest firebase and firebase-admin dependencies.

## Expected behavior
expected to work?

expected to work?

## Screenshots
![image](https://user-images.githubusercontent.com/16472274/72122890-879d4f80-332d-11ea-8aa2-a719d5a87fe4.png)

## System information
![image](https://user-images.githubusercontent.com/16472274/72123138-57a27c00-332e-11ea-90db-689a2b25a20a.png)

- OS: [macOS]
- Browser [chrome, safari, anything]
- Version of Next.js: [@latest]

## Additional context
Please help. I'm new to NextJS. I'm new to using JWT to protect routes on SSR. I'm not a senior dev.

I appreciate so much any help with to see how can I put together a working example to protect routes using Firebase authentication.

Best to all on this 2020!

**Comment by waldothedeveloper** [comment]
And maybe this is not directly related to NextJS (or not related at all) but to Firebase.
But folks I really need to put a working example of protecting routes in NextJS (SSR) with JWT unless there's a new way to do it that I haven't heard of.

**Comment by ssong** [comment]
@waldothedeveloper I can't seem to replicate this using the latest canary branch.

What I'd recommend you try is keep the `package.json` as you showed above,

delete `package-lock.json` and `node_modules` and try reinstalling the npm packages. I've had other issues where the `package.json` changes weren't being reflected in the `package-lock.json` before so maybe give that a shot.

**Comment by waldothedeveloper** [comment]
@ssong Let me give a quick try, I'm going to clone the repo again to start clean and follow the steps on the example docs...will come back to you if it works

**Comment by waldothedeveloper** [comment]
@ssong  Confirmed. I was able to do it. Thank you so much for your support. 
Amazing product and amazing team. Thank you guys!

**Comment by balazsorban44** [comment]
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
