### ISSUE TITLE
Pages with utf-8 name don't work properly under SSR

### ISSUE THREAD

**Issue by frei-0xff** [zeit/next.js#10084]
# Bug report

Pages with utf-8 non-ASCII characters in their name don't work properly under SSR

## Describe the bug

Pages with utf-8 non-ASCII characters in their name work just fine with client-side navigation,
but when rendered on server side return "404 This page could not be found."

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Create page 'pages/тест.js'
2. Navigate to http://localhost:3000/тест
4. See error "404 This page could not be found."

## Expected behavior

I'm expecting to see page 'pages/тест.js' rendered

## System information

- OS: Windows
- Version of Next.js: 9.1.7

## Additional context

Minimal repository to reproduce bug: https://github.com/frei-0xff/nextjs-utf8-pagename

**Comment by StarpTech** [comment]
What's the purpose of using none-ASCII chars if your page name should be displayed as a valid URL?

`http://localhost:3000/тест` is converted to `http://localhost:3000/%D1%82%D0%B5%D1%81%D1%82` and can't be found.

**Comment by kachkaev** [comment]
@StarpTech you might want to have a link like `http://яндекс.рф/тест`. These display as Cyrillic URLs modern browser tabs. From my experience, `тест` turns into `%D1%82%D0%B5%D1%81%D1%82` only when you copy the URL into buffer.

**Comment by frei-0xff** [comment]
@StarpTech none-ASCII URL's displayed propertly in all modern browsers and used by popular sites. For example by wikipedia.org

**Comment by StarpTech** [comment]
Thanks for the examples. I have never used it.

**Comment by Itzik7** [comment]
As a workaround you can use dynamic page `[page` and switch case on pages names in utf8 pages name.

**Comment by frei-0xff** [comment]
In version 9.2 client-side routing for pages with non-ASCII characters worked just fine. The issue was only with the server-side routing, that could be worked around with custom server.js with decodeURI(parsedUrl.pathname).

After updating to version 9.5.1 client-side routing for pages with non-ASCII characters stopped working at all. In development mode, after clicking on the link with such a page name, no navigation happens without any error messages. After routeChangeStart event neither routeChangeComplete nor routeChangeError events are fired, and only after clicking on another link routeChangeError with "Error: Route Cancelled" is fired.

**Comment by jonrh** [comment]
Tested v9.5.0, v9.5.5, and v10.0.1 and none of them support statically generated pages with non-ascii names like `/тест` and `/hæ`. It worked as expected in a few versions I [tested](https://github.com/frei-0xff/nextjs-utf8-pagename) between v9.0.0 and v9.4.4. I would classify this is a bug or an undocumented breaking change in v9.5.

Not being able to have utf-8 routes in Next.js is blocking a migration from Gatsby where it works as expected.

**Comment by fillon** [comment]
I am experiencing the same issue with route in thai language

Is there a workaround?

next-10.0.3

**Comment by jonrh** [comment]
Tested again and found something really peculiar. It works as expected when deployed on Vercel. It does not work locally when running `next dev` nor `next build && next start`, returns 404 error.

Sample code: [https://github.com/jonrh/next-unicode-bugs](https://github.com/jonrh/next-unicode-bugs)
Sample live website: [https://next-unicode-bugs.vercel.app/](https://next-unicode-bugs.vercel.app/)

Video showing it working on Vercel:
https://user-images.githubusercontent.com/58344/103299546-b4da8600-49f4-11eb-8dd9-92ffd8536407.mov

I would also like to clarify that this is only testing static routes, not server side rendering (SSR/SSG) as the title of this issue states.

**Comment by tyteen4a03** [comment]
Can trigger this issue with 9.5+. Any ETA on this as I really want to upgrade to React 17 and webpack 5?

**Comment by andreyshedko** [comment]
If this will help someone, I had fixed this issue the following way:
```
const res = await fetch(`${process.env.HOST}/api/tags/read`, headers);
  const data = await res.json();
  let paths: { params: ParsedUrlQuery }[] = [];
  if (Array.isArray(data)) {
    paths = data.map((tag: Tag) => ({
      params: { tag: encodeURI(tag.tagName) },
    }));
  }

  return {
    paths,
    fallback: false,
  };
```

**Comment by aynik** [comment]
As a workaround I used rewrites on `next.config.js`:

```javascript
  async rewrites() {
    return [
      {
        source: `/${encodeURIComponent('カート')}`,
        destination: '/cart',
      },
      {
        source: `/${encodeURIComponent('アカウント')}`,
        destination: '/account',
      },
    ]
  }
```

**Comment by JanDez** [comment]
> Tested v9.5.0, v9.5.5, and v10.0.1 and none of them support statically generated pages with non-ascii names like `/тест` and `/hæ`. It worked as expected in a few versions I [tested](https://github.com/frei-0xff/nextjs-utf8-pagename) between v9.0.0 and v9.4.4. I would classify this is a bug or an undocumented breaking change in v9.5.

That happend to my with ñ's ans ´'s words

**Comment by ShahriarKh** [comment]
for me, `decodeURI` is the answer:
```js
export async function getStaticPaths() {
   const { posts } = await request(CMS, POSTS);

   const paths = posts.nodes.map((post) => ({
      params: { slug: decodeURI(post.slug) },
   }));

   return { paths, fallback: false };
}
```

**Comment by nbouvrette** [comment]
We just released a new package that overcomes this issue (and many others): https://github.com/Avansai/next-multilingual-example

Looking forward to hearing feedback on our approach.

**Comment by Tobeyforce** [comment]
> 

While this package shows some promise, shouldn't international urls be supported by default? Internationalization is the concept of supporting multiple languages, which has nothing to do (maybe a little) with UTF-8-based urls.

It looks like this package e.g enforces every url to use a language prefix, e.g /fr/myurlehre
I think it's quite simple - international urls should be supported by default. 

For example:
I want to use the swedish characters å,ä, ö and have a url called /påsk

This doesn't work. However, if I name my page p%C3%A5sk it works.... until I use getStaticPaths, then it breaks.
This really causes a ton of confusion.

**Comment by Tobeyforce** [comment]
While this package shows some promise, shouldn't international urls be supported by default? Internationalization is the concept of supporting multiple languages, which has nothing to do (maybe a little) with UTF-8-based urls.

It looks like this package e.g enforces every url to use a language prefix, e.g /fr/myurlehre
I think it's quite simple - international urls should be supported by default.

For example:
I want to use the swedish characters å,ä, ö and have a url called /påsk

This doesn't work. However, if I name my page p%C3%A5sk it works.... until I use getStaticPaths, then it breaks.
This really causes a ton of confusion.

> We just released a new package that overcomes this issue (and many others): https://github.com/Avansai/next-multilingual
> 
> Looking forward to hearing feedback on our approach.

**Comment by rnarkk** [comment]
I keep getting this error when I go to non-ascii path in the local dev mode (`npm run dev`), trying to use Dynamic Routes with App Router:

```
TypeError: Cannot convert argument to a ByteString because the character at index 8 has a value of <value> which is greater than 255.
    at Object.fetch (node:internal/deps/undici/undici:16287:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async invokeRequest (/path/to/node_modules/next/dist/server/lib/server-ipc/invoke-request.js:21:12)
    at async invokeRender (/path/to/node_modules/next/dist/server/lib/router-server.js:229:29)
    at async handleRequest (/path/to/node_modules/next/dist/server/lib/router-server.js:422:24)
    at async requestHandler (/path/to/node_modules/next/dist/server/lib/router-server.js:439:13)
```

**Comment by rnarkk** [comment]
Any updates?

**Comment by ViktorYermak** [comment]
Nextjs v14.0.4 and app router, the problem with **utf-8** is still here, at least partially (with **Static Rendering** at build time).
And it’s a big problem, according to url structure best practices for **non-English** url.
Yes, `decodeURIComponent()` in `generateStaticParams` is a workaround, but it’s only a workaround.
(With **Dynamic Rendering** at request time everything works properly).

**Comment by coffeecupjapan** [comment]
I just take a quick look at this problem only , but it seems like `nextjs` at build runtime replace any `non-word characters` to blank and therefore you cannot use non-ascii words, I assume.

https://github.com/vercel/next.js/blob/7dbb66f390ab54e4b5c4c632a626cbcd6fd8f271/packages/next/src/shared/lib/router/utils/route-regex.ts#L114-L116

Are any one eagerly want to do add ascii words at least here ( and supposely more, I cannot pick every dependencies.. sorry) ?

https://github.com/vercel/next.js/blob/7dbb66f390ab54e4b5c4c632a626cbcd6fd8f271/packages/next/src/shared/lib/router/utils/route-regex.ts#L81-L97

**Comment by coffeecupjapan** [comment]
I have investigated this issue for a while and find in dev mode UTF-8 words can be included in routing regex .
https://github.com/vercel/next.js/blob/39589ff35003ba73f92b7f7b349b3fdd3458819f/packages/next/src/server/lib/router-utils/setup-dev-bundler.ts#L2338-L2342

But non-ascii UTF-8 pathName passed from URL is somehow encoded.

<img width="663" alt="image" src="https://github.com/vercel/next.js/assets/136598145/4537a287-e420-47c2-bb74-2b3218de149e">

In dev mode, the quick solution is to decode non-ascii UTF-8 words (not sure for production and above comment is about production) .
But I think I need more testing.

**Comment by abdessamadely** [comment]
In my case, I encountered this issue with Arabic pathnames, After debugging a little I noticed that we have a misalignment between dev, and export (on validation I think), as a workaround, I did the following:

```ts
process.env.NODE_ENV === 'development' ? encodeURI(page) : page
// or
process.env.NODE_ENV === 'development' ? encodeURI(page) : decodeURI(page)
```

On dev, I encoded the pathname. So, it would match what the Next server has, but on `export/build`, I give it the value I want for the generated filename.

#### Full example:

```tsx
const pages = ['من-نحن', 'سياسة-الخصوصية', 'الشروط-والأحكام']
export async function generateStaticParams() {
  return pages.map((page) => ({
    pathname: process.env.NODE_ENV === 'development' ? encodeURI(page) : page 
  }))
}
```

**Comment by Arctomachine** [comment]
What exactly is main source of this problem? We could come up with solution together and fix it by v15 stable release perhaps

**Comment by vncafecode** [comment]
It's been 4 years and no one else at Next showing interest of fixing it

**Comment by Arctomachine** [comment]
I tried to decode url and it works for non-ascii symbols. 
```js
const propsSlug = (await props.params)?.slug
const slug = decodeURIComponent(propsSlug) || '/'
```
 But as workaround it only works in dynamic segments like `app/[slug]/page`.
Static segments like `/app/привет` still have to be declared under url encoded names `/app/

With this in mind I suspect solution to this problem should be very simple: add `decodeURIComponent` somewhere into next router

**Comment by codenomnom** [comment]
@Arctomachine for static pages I'm using redirects, defined in the next config. It's extremely tedious and prone to errors, and also diminishes a lot of the "file based routing" idea, but I didn't find any better option as of now.

**Comment by Arctomachine** [comment]
Found that revalidatePath is not working for unicode paths (dynamic segment). Or it does, but randomly and rarely, have not been able to notice any pattern.
And encodeURIComponent helps here, revalidate return of this function instead of raw unicode path.

**Comment by tyteen4a03** [comment]
I sent a little card to Malte Ubl, here's hoping 🤞 

https://x.com/tyteen4a03/status/2069481553478967688
