### ISSUE TITLE
`next export` touches file in `.next`

### ISSUE THREAD

**Issue by dbo** [zeit/next.js#10137]
# Bug report

## Describe the bug

Running `next export` on a build server installation touches files in the `.next` directory. This is especially causing trouble if the server package has been installed globally, since rights are missing in this case, e.g.

```
next export
> using build directory: /usr/local/share/.config/yarn/global/node_modules/myserver/.next
Error: EACCES: permission denied, open '/usr/local/share/.config/yarn/global/node_modules/myserver/.next/export-detail.json'
    at Object.openSync (fs.js:440:3)
    at writeFileSync (fs.js:1265:35)
    at _default (/usr/local/share/.config/yarn/global/node_modules/next/dist/export/index.js:9:379) {
  errno: -13,
  syscall: 'open',
  code: 'EACCES',
  path: '/usr/local/share/.config/yarn/global/node_modules/myserver/.next/export-detail.json'
}
```

## To Reproduce

`next build && next export` will reveal that `.next/export-detail.json` has been written.

## Expected behavior

Don't write on export, just read from `.next`.

**Comment by Timer** [comment]
`next export` isn't a pure command, it needs to persist state for re-exports! This is the expected behavior.

**Comment by dbo** [comment]
@Timer Could you please point me to the description of the expected behaviour, especially why an export requires to persist state in the built .next folder? If it is about caching/performance on follow-up exports, is the .next folder really the right place for that kind of data?

It would help if you could give some guidance how to work with published server artefacts/NPMs then for export purposes.

**Comment by dbo** [comment]
Anybody else could step in here? I really like to understand the reasoning behind this, because it seems strange to me. Thanks in advance!

@timneutkens or @rauchg ?

**Comment by dbo** [comment]
Is this the way this open source project is run? Quite disappointing, @Timer @timneutkens

**Comment by esamattis** [comment]
I too find this behaviour weird. We run next.js in a read-only container where the `.next` is created during the container build and `next export` would export to a writable volume mount but since next.js tries to write to `.next` dir during export export we must add write permissions to container itself.

**Comment by balazsorban44** [comment]
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
