### ISSUE TITLE
error build with-zones

### ISSUE THREAD

**Issue by DamienA24** [zeit/next.js#10415]
Hello, I tried :

https://github.com/zeit/next.js/tree/canary/examples/with-zones

I follow the instructions and I got this :

```
@MacBook-Pro  ~/Documents/nextjs  cd with-zones 
 @MacBook-Pro  ~/Documents/nextjs/with-zones  now dev
> Now CLI 16.7.3 dev (beta) — https://zeit.co/feedback
┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│ WARN! You defined 1 build that did not match any source files (please ensure they are NOT defined in .nowignore): │
└───────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
- {"src":"home/next.config.js","use":"@now/next"}
> Creating initial build
Exiting builder due to build error:
Error: Cannot find module 'next'
Require stack:
- /Users/d_/Documents/nextjs/with-zones/blog/noop.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:793:17)
    at resolveFileName (/Users/d_/Library/Caches/co.zeit.now/dev/builders/node_modules/@now/next/dist/dev-server.js:142:39)
    at resolveFrom (/Users/d_/Library/Caches/co.zeit.now/dev/builders/node_modules/@now/next/dist/dev-server.js:156:9)
    at Object.module.exports.101.module.exports [as default] (/Users/d_/Library/Caches/co.zeit.now/dev/builders/node_modules/@now/next/dist/dev-server.js:159:47)
    at process.<anonymous> (/Users/d_/Library/Caches/co.zeit.now/dev/builders/node_modules/@now/next/dist/dev-server.js:4472:48)
    at Object.onceWrapper (events.js:313:26)
    at process.emit (events.js:223:5)
    at emit (internal/child_process.js:876:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:21) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/Users/d_/Documents/nextjs/with-zones/blog/noop.js' ]
```

What is the problem, I don't understand... thank you

**Comment by DamienA24** [comment]
I saw a new commit 14 hours ago, but now the problem is different and it's not working again...

**Comment by Timer** [comment]
`now dev` usage has been undocumented per #10426. Please use the standard `next dev` command!

**Comment by balazsorban44** [comment]
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
