### ISSUE TITLE
[with-react-intl] - FormattedMessage HTML

### ISSUE THREAD

**Issue by BramDecuypere** [zeit/next.js#10533]
# Examples bug report

[EDIT: 18/03/2020] - Although the API is changing, it still persists on `FormattedMessage` & `formatMessage()`

## Example name

`with-react-intl`

## Describe the bug

Handling formatting of messages for html.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Download the example and install
2. Change value to something containing basic html (like the example below)
3. Implement FormattedMessage (with rich text)
4. Start the server ad refresh
5. See error

## Expected behavior

To be able to handle the key - value like this:
```
<FormattedHTMLMessage id="main.title" defaultMessage="Home" />
```

```
{
  "main.title": "I want this amazing<strong>deal</strong>",
}
```

## Screenshots

```
[React Intl] Error formatting message: "nav.home" for locale: "en", using default message as fallback.
Error: Cannot format XML message without DOMParser
    at new FormatError (/Users/bramdecuypere/git/with-react-intl-app/node_modules/intl-messageformat/dist/formatters.js:27:28)
    at Object.formatHTMLMessage (/Users/bramdecuypere/git/with-react-intl-app/node_modules/intl-messageformat/dist/formatters.js:283:15)
    at IntlMessageFormat.formatHTMLMessage (/Users/bramdecuypere/git/with-react-intl-app/node_modules/intl-messageformat/dist/core.js:70:33)
    at formatMessage (/Users/bramdecuypere/git/with-react-intl-app/node_modules/react-intl/dist/formatters/message.js:67:47)
    at formatHTMLMessage (/Users/bramdecuypere/git/with-react-intl-app/node_modules/react-intl/dist/formatters/message.js:119:12)
    at Object.children (/Users/bramdecuypere/git/with-react-intl-app/node_modules/react-intl/dist/components/html-message.js:55:40)
    at ReactDOMServerRenderer.render (/Users/bramdecuypere/git/with-react-intl-app/node_modules/react-dom/cjs/react-dom-server.node.development.js:3855:55)
    at ReactDOMServerRenderer.read (/Users/bramdecuypere/git/with-react-intl-app/node_modules/react-dom/cjs/react-dom-server.node.development.js:3536:29)
    at renderToString (/Users/bramdecuypere/git/with-react-intl-app/node_modules/react-dom/cjs/react-dom-server.node.development.js:4245:27)
    at render (/Users/bramdecuypere/git/with-react-intl-app/node_modules/next/dist/next-server/server/render.js:80:16)
    at Object.renderPage (/Users/bramdecuypere/git/with-react-intl-app/node_modules/next/dist/next-server/server/render.js:291:16)
    at Function.getInitialProps (/Users/bramdecuypere/git/with-react-intl-app/.next/server/static/development/pages/_document.js:485:19)
    at Function.getInitialProps (/Users/bramdecuypere/git/with-react-intl-app/.next/server/static/development/pages/_document.js:1084:31)
    at Object.loadGetInitialProps (/Users/bramdecuypere/git/with-react-intl-app/node_modules/next/dist/next-server/lib/utils.js:59:29)
    at Object.renderToHTML (/Users/bramdecuypere/git/with-react-intl-app/node_modules/next/dist/next-server/server/render.js:295:36)
    at processTicksAndRejections (internal/process/task_queues.js:86:5)
```

## System information

- OS: macOS, Windows
- Node: v11.13.0
- Version of Next.js: latest / 9.2.1

## Additional context

Any suggestion to fix this would be great. I've checked myself (implementing jsdom), but haven't really got an idea on how to implement it in next.js.

**Comment by honia19** [comment]
@BramDecuypere I think you just incorrect use react-intl

**Comment by BramDecuypere** [comment]
@honia19 Thanks for commenting! Although I do believe I'm using a capability of react-intl. Although I just found out it is legacy (and not the recommended way) 

So I tried to make sure we have the latest way of working. So I found this:
[Rich text formatting in react-intl](https://github.com/formatjs/react-intl/blob/master/docs/Components.md#rich-text-formatting)

```
<FormattedMessage
  id="app.greeting"
  description="Greeting to welcome the user to the app"
  defaultMessage="Hello, <b>Eric</b> {icon}"
  values={{
    b: (...chunks) => <b>{chunks}</b>,
    icon: <svg />,
  }}
/>
```

But even then still having the error in place.

**Comment by fabianishere** [comment]
You need to polyfill DOMParser in Node environments (as explained [here](https://github.com/formatjs/formatjs/tree/master/packages/intl-messageformat#caveats)).

To do this  in Next.js, you can for example [xmldom](https://github.com/xmldom/xmldom) and add the following piece of code to the entrypoint of your server (e.g. `server.js`):
```js
// Polyfill for DOMParser required by formatjs
const { DOMParser } = require('xmldom');
global.DOMParser = DOMParser;

...
// Imports
```

**Comment by fabianishere** [comment]
If you want to see it in action, I have implemented the example on my [react-intl-domparser](https://github.com/fabianishere/next.js/tree/example/react-intl-domparser) branch.

**Comment by BramDecuypere** [comment]
@fabianishere Yeah, that is what i did to solve it now after some searching. But it would be nice to have Next.js deal with this, no?

**Comment by fabianishere** [comment]
I see your point, but `DOMParser` is a heavy dependency if you are not using the functionality. Maybe a better idea is to document this behavior in the example, with instructions on how to apply the polyfill.

**Comment by danilofuchs** [comment]
As of [react-intl 4.0](https://github.com/formatjs/react-intl/releases/tag/v4.0.0), `FormattedHTMLMessage` and `intl.formatHTMLMessage` have been removed and polyfilling is not necessary.
I think this issue and #10782 should be closed as they do not reflect the latest library api.

**Comment by BramDecuypere** [comment]
> As of [react-intl 4.0](https://github.com/formatjs/react-intl/releases/tag/v4.0.0), `FormattedHTMLMessage` and `intl.formatHTMLMessage` have been removed and polyfilling is not necessary.
> I think this issue and #10782 should be closed as they do not reflect the latest library api.

Because they are now included in the regular `FormattedMessage` and `formatMessage()`.

But still this issue will persist, since we are trying to handle... What I will do is updating the pr to make sure it reflects the latest api.

**Comment by fabianishere** [comment]
@BramDecuypere Actually, react-intl 4.0 removes the dependency on `DOMParser`, so this issue shouldn't occur with that version. However, react-intl 4.0 has only been out for about two weeks now, so I would prefer at least mentioning this issue in the Next.js example since many people might still be using react-intl 3.

**Comment by BramDecuypere** [comment]
@fabianishere indeed that solves this issue as well, thanks for the update and the hard work everyone is doing on the Next.js project!

Summary:
1. You can just handle basic html formatting in `react-intl@4`
2. If you can't upgrade at this point, you can use a custom server like this:

```
import { createServer } from "http";
import { parse } from "url";
import next from "next";
import { DOMParser } from "xmldom";

global.DOMParser = DOMParser;

const port = parseInt(process.env.PORT, 10) || 3001;
const dev = process.env.NODE_ENV !== "production";
const app = next({ dev });
const handle = app.getRequestHandler();

app.prepare().then(() => {
  createServer((req: any, res: any) => {
    handle(req, res, parsedUrl);
  }).listen(port, () => {
    console.log(`> Ready on http://localhost:${port}`);
  });
});

```

**Comment by biels** [comment]
What is the recommended way of handling formatted HTML messages in 2021 (next 11.x.x)?

**Comment by balazsorban44** [comment]
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
