### ISSUE TITLE
next export + styled-jsx fails with template variables

### ISSUE THREAD

**Issue by igl** [zeit/next.js#10576]
# Bug report

Compilation fails when using variables in styled-jsx css strings.

`next export` output:

```
ReferenceError: DECO_GREEN is not defined
     at SectionTitle (/opt/plancraft/pkgs/webpage/.next/serverless/pages/index.js:10268:495)
     at d (/opt/plancraft/pkgs/webpage/.next/serverless/pages/index.js:44774:498)
     at Za (/opt/plancraft/pkgs/webpage/.next/serverless/pages/index.js:44777:16)
```

## Screenshots

Snippet from `.next/serverless/pages/index.js`:
![image](https://user-images.githubusercontent.com/293519/74764366-dc63ac80-5281-11ea-8627-607747ecfdef.png)

The module prefix "_styles." is missing from the variables injected into the css string

## System information

- OS: macOS & linux
- Node: v10
- Next.js: 9.2.2

**Comment by timneutkens** [comment]
Please add a minimal reproduction.

**Comment by igl** [comment]
Currently working out of a monorepo. This will take some time to extract a lean example.

Suspecting our custom babel config at the moment.

**Comment by igl** [comment]
ok got it.

It was my fault for tweaking `next/babel` the wrong way:

![image](https://user-images.githubusercontent.com/293519/74770540-b98ac580-528c-11ea-9eb5-b20d39db9c6b.png)

kthxbye!

**Comment by balazsorban44** [comment]
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
