### ISSUE TITLE
GraphQL relay-compiler vs. next build: pages/__generated__/... is not a React component

### ISSUE THREAD

**Issue by messa** [zeit/next.js#10646]
Tool `react-compiler` extracts GraphQL fragments and queries from pages and components and creates files like `pages/__generated__/pages_indexQuery.graphql`. But `next build` fails to process these pages because they are not proper pages - they don't have React component as a default export.

Is there any way how to exclude `pages/__generated__` when running `next build`?

One or more examples are broken because of this. For example **with-relay-modern-server-express**:

```shell
$ docker run --rm -it node:12 /bin/bash
$ curl https://codeload.github.com/zeit/next.js/tar.gz/canary | tar -xz --strip=2 next.js-canary/examples/with-relay-modern-server-express
$ cd with-relay-modern-server-express
$ npm install
$ npm install relay-compiler@latest # the older versions of relay-compiler work the same but require watchman
$ npm run relay
Created:
 - pages_indexQuery.graphql.js
 - BlogPosts_viewer.graphql.js
 - BlogPostPreview_post.graphql.js
$ npm run build 
...

> Using external babel configuration
> Location: "/with-relay-modern-server-express/.babelrc"
Creating an optimized production build

Compiled successfully.

> Build error occurred
Error: Build optimization failed: found page without a React Component as default export in
pages/__generated__/pages_indexQuery.graphql

See https://err.sh/zeit/next.js/page-without-valid-component for more info.

    at build (/with-relay-modern-server-express/node_modules/next/dist/build/index.js:18:143)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

**Comment by messa** [comment]
I've been looking into https://github.com/zeit/next.js/blob/91a473244051efe62dfdfdb88b49c97f30578333/packages/next/build/index.ts#L193-L198

Right now I don't see a way how to configure the collect page process. Would probably have to add a new option to `next.config.js`.

But maybe the solution should be to use `relay-compiler --artifactDirectory`?
From `relay-compiler --help`:

```
  --artifactDirectory   A specific directory to output all artifacts to. When
                        enabling this the babel plugin needs `artifactDirectory`
                        set as well.                    [string] [default: null]
```

**Comment by lfades** [comment]
`/pages` should contain nothing but valid pages, so if you can move the `__generated__` files outside of it, that would be the best solution, and `--artifactDirectory` seems to be the way 😌 .

**Comment by TrySound** [comment]
It's not easy to migrate to artifactDirectory when almost each module imports types from such folders.

**Comment by balazsorban44** [comment]
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
