### ISSUE TITLE
Serverless: switching from getInitialProps to getServerSideProps causes "res.hasHeader is not a function" error

### ISSUE THREAD

**Issue by zorzysty** [zeit/next.js#11223]
# Bug report

## Describe the bug

Component using SSR works flawlessly on **localhost** both using `getInitialProps` and `getServerSideProps` . 
It also works on **serverless** when using `getInitialProps`, but causes a **500 error on serverless** when using `getServerSideProps`.

Here are the error logs:
```
ERROR	TypeError: res.hasHeader is not a function
    at sendPayload (/var/task/pages/[id].js:13625:41)
    at renderReqToHTML (/var/task/pages/[id].js:25515:13)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

Here's the code for `getInitialProps`:
```javascript
Id.getInitialProps = async ({ query: { id } }) => {
  const url = `/${id}`

  const getData = async () => {
    try {
      const { status, user_id: userId, username } = await API.get(url)

      const user = { id: userId, name: username }

      return { status, user }
    } catch (err) {
      return { status: 'error' }
    }
  }

  const { status, user } = await getData()

  return {
    status,
    user,
  }
}
```

Here's the code for `getServerSideProps`:
```javascript
export const getServerSideProps = async ({ query: { id } }) => {
  const url = `/${id}`

  const getData = async () => {
    try {
      const { status, user_id: userId, username } = await API.get(url)

      const user = { id: userId, name: username }

      return { status, user }
    } catch (err) {
      return { status: 'error' }
    }
  }

  const { status, user } = await getData()

  return {
    props: {
      status,
      user,
    },
  }
}
```

## Screenshots

Here's what's actually being rendered
![obraz](https://user-images.githubusercontent.com/5398733/77167181-6c795980-6aad-11ea-9816-a9acc194bc68.png)

## System information

- AWS CloudFront
- Node v 12.x
- Nextjs v 9.3.1
- serverless v 1.67.0
- serverless-next.js v 1.67.0

**Comment by a14m** [comment]
@zorzysty I had the same issue and digging deep I found the culprit to be `next-aws-lambda` not having the method (with the lambda wrapper)... I think this can be closed in favor of the other PR

**Comment by zorzysty** [comment]
Thanks @a14m. This indeed looks like an issue with serverless-next.js and not next.js itself.
I'm closing the ticket.

**Comment by damiangene** [comment]
Apologies, I know this issue is closed but I've run into the same problem.

```
ERROR	TypeError: res.hasHeader is not a function
    at sendPayload (/var/task/pages/earn.js:2120:231)
    at renderReqToHTML (/var/task/pages/earn.js:6235:13)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

code to fetch
```
export const getServerSideProps : GetServerSideProps = async () => {
  const API = 'http://myAPIEndpoint'
  const res = await fetch(API, {
                headers: {
                  'Id': '1234'
                }
              });
 
  const posts = await res.json()
 
  return{
    props: {
      posts
    }
  };
}
```

**Comment by balazsorban44** [comment]
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
