### ISSUE TITLE
Ubuntu 18.04 next install fails

### ISSUE THREAD

**Issue by ReTWi** [zeit/next.js#11283]
# Bug report

## Describe the bug

When installing next.js on ubuntu 18.04  `npm i next` , there is an error:

```
npm ERR! code 1
npm ERR! Command failed: git checkout next
npm ERR! error: pathspec 'next' did not match any file(s) known to git.
npm ERR!

npm ERR! A complete log of this run can be found in:
```

Error log las lines:
```
20509 warn optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.2.7 (node_modules/webpack/node_modules/chokidar/node_modules/fsevents):
20510 warn notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.12: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
20511 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid OS:    darwin
20511 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid Arch:  any
20511 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual OS:   linux
20511 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual Arch: x64
20512 verbose stack Error: Command failed: git checkout next
20512 verbose stack error: pathspec 'next' did not match any file(s) known to git.
20512 verbose stack
20512 verbose stack     at ChildProcess.exithandler (child_process.js:303:12)
20512 verbose stack     at ChildProcess.emit (events.js:315:20)
20512 verbose stack     at maybeClose (internal/child_process.js:1026:16)
20512 verbose stack     at Socket.<anonymous> (internal/child_process.js:441:11)
20512 verbose stack     at Socket.emit (events.js:315:20)
20512 verbose stack     at Pipe.<anonymous> (net.js:674:12)
20513 verbose cwd /home/me/app
20514 verbose Linux 4.15.0-55-generic
20515 verbose argv "/usr/bin/node" "/usr/bin/npm" "i" "next"
20516 verbose node v13.11.0
20517 verbose npm  v6.13.7
20518 error code 1
20519 error Command failed: git checkout next
20519 error error: pathspec 'next' did not match any file(s) known to git.
20520 verbose exit [ 1, true ]
```

## Expected behavior

No error

## System information

OS: Ubuntu 18.04
Version of Next.js: v9.3.1

**Comment by ReTWi** [comment]
Problem was with prettier#next package (#next part gives error).

**Comment by balazsorban44** [comment]
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
