### ISSUE TITLE
Issue with getStaticPaths and `firebase/firestore`

### ISSUE THREAD

**Issue by hangindev** [zeit/next.js#11339]
# Bug report

## Describe the bug

This bug only happens in `next dev`, not `next build` and `next start`.

With `firebase/firestore` imported, error appears when using `getStaticPaths` with fallback during development. When the page is visited the first time, there is no error. However, when the page is refreshed, the pre-rendered page throw error:
```
Error: Failed to load D:\Sandbox\node_modules\grpc\src\node\extension_binary\node-v72-win32-x64-unknown\grpc_node.node. Module did not self-register: '\\?\D:\Sandbox\3ehxw\node_modules\grpc\src\node\extension_binary\node-v72-win32-x64-unknown\grpc_node.node'.
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1207:18)
    at Module.load (internal/modules/cjs/loader.js:1001:32)
    at Function.Module._load (internal/modules/cjs/loader.js:900:14)
    at Module.require (internal/modules/cjs/loader.js:1043:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (D:\Sandbox\3ehxw\node_modules\grpc\src\grpc_extension.js:32:13)
    at Module._compile (internal/modules/cjs/loader.js:1157:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1177:10)
    at Module.load (internal/modules/cjs/loader.js:1001:32)
    at Function.Module._load (internal/modules/cjs/loader.js:900:14) {
  type: 'Error'
}
```

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. clone [https://github.com/hangindev/issue-nextjs-firestore-reproduce](https://github.com/hangindev/issue-nextjs-firestore-reproduce)
2. `npm i` and `npm run dev`
3. visit http://localhost:3000/123
4. refresh the page to see error in terminal

## Expected behavior

Without error.

## System information

- Windows 10
- Chrome
- next: 9.3.1

## Additional context

It might be related to [issue #7894](https://github.com/zeit/next.js/issues/7894). But that issue happened on `next build`.

**Comment by balazsorban44** [comment]
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
