### ISSUE TITLE
Yarn install on fork errors on WIndows 10

### ISSUE THREAD

**Issue by filipesmedeiros** [zeit/next.js#11357]
# Bug report

## Describe the bug

The Yarn installation of the repository seems to fail with error

## To Reproduce

1. Fork repo
2. Clone it to local Windows 10 machine
3. Create new branch
4. Run `yarn` (on the correct dir)

## Expected behavior

The installation would go well

## Screenshots

```
yarn
yarn install v1.22.4
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
info fsevents@1.2.11: The platform "win32" is incompatible with this module.
info "fsevents@1.2.11" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@2.1.2: The platform "win32" is incompatible with this module.
info "fsevents@2.1.2" is an optional dependency and failed compatibility check. Excluding it from installation.
[4/5] Linking dependencies...
warning " > @babel/plugin-proposal-object-rest-spread@7.6.2" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@babel/plugin-proposal-object-rest-spread > @babel/plugin-syntax-object-rest-spread@7.7.4" has unmet peer dependency "@babel/core@^7.0.0-0".
warning " > @babel/preset-flow@7.0.0" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@babel/preset-flow > @babel/plugin-transform-flow-strip-types@7.7.4" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@babel/preset-flow > @babel/plugin-transform-flow-strip-types > @babel/plugin-syntax-flow@7.7.4" has unmet peer dependency "@babel/core@^7.0.0-0".
warning " > @babel/preset-react@7.7.0" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@babel/preset-react > @babel/plugin-transform-react-display-name@7.7.4" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@babel/preset-react > @babel/plugin-transform-react-jsx@7.7.7" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@babel/preset-react > @babel/plugin-transform-react-jsx-self@7.7.4" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@babel/preset-react > @babel/plugin-transform-react-jsx-source@7.7.4" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@babel/preset-react > @babel/plugin-transform-react-jsx > @babel/plugin-syntax-jsx@7.7.4" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@mdx-js/loader > @mdx-js/mdx > @babel/plugin-proposal-object-rest-spread@7.7.7" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@zeit/next-css > css-loader@1.0.0" has unmet peer dependency "webpack@^4.0.0".
warning "@zeit/next-css > extract-css-chunks-webpack-plugin@3.3.3" has unmet peer dependency "webpack@^4.4.0".
warning "@zeit/next-css > optimize-css-assets-webpack-plugin@5.0.3" has unmet peer dependency "webpack@^4.0.0".
warning "@zeit/next-sass > sass-loader@6.0.6" has unmet peer dependency "webpack@^2.0.0 || >= 3.0.0-rc.0 || ^3.0.0".
warning "@zeit/next-typescript > @babel/preset-typescript@7.7.7" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@zeit/next-typescript > @babel/preset-typescript > @babel/plugin-transform-typescript@7.7.4" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@zeit/next-typescript > @babel/preset-typescript > @babel/plugin-transform-typescript > @babel/helper-create-class-features-plugin@7.7.4" has unmet peer dependency "@babel/core@^7.0.0".
warning "@zeit/next-typescript > @babel/preset-typescript > @babel/plugin-transform-typescript > @babel/plugin-syntax-typescript@7.7.4" has unmet peer dependency "@babel/core@^7.0.0-0".
warning " > babel-core@7.0.0-bridge.0" has unmet peer dependency "@babel/core@^7.0.0-0".
warning " > babel-jest@24.9.0" has unmet peer dependency "@babel/core@^7.0.0".
warning "babel-jest > babel-preset-jest@24.9.0" has unmet peer dependency "@babel/core@^7.0.0".
warning " > react-ssr-prepass@1.0.8" has unmet peer dependency "react-is@^16.8.0".
warning " > request-promise-core@1.1.2" has unmet peer dependency "request@^2.34".
warning " > @next/plugin-material-ui@9.3.2-canary.1" has unmet peer dependency "@material-ui/styles@*".
warning "workspace-aggregator-ccd5b6ae-ce36-4b23-b57b-16971d0dfdbb > @next/polyfill-nomodule > microbundle > rollup-plugin-typescript2@0.19.3" has incorrect peer dependency "rollup@>=0.68.0".
[5/5] Building fresh packages...
[1/10] ⠠ node-sass
[-/10] ⠠ waiting...
[3/10] ⠠ grpc
[-/10] ⠠ waiting...
error D:\Better\next.js\node_modules\grpc: Command failed.
Exit code: 1
Command: node-pre-gyp install --fallback-to-build --library=static_library
Arguments:
Directory: D:\Better\next.js\node_modules\grpc
Output:
node-pre-gyp info it worked if it ends with ok
node-pre-gyp info using node-pre-gyp@0.13.0
node-pre-gyp info using node@13.11.0 | win32 | x64
node-pre-gyp WARN Using request for node-pre-gyp https download
node-pre-gyp info check checked for "D:\Better\next.js\node_modules\grpc\src\node\extension_binary\node-v79-win32-x64-unknown\grpc_node.node" (not found)
node-pre-gyp http GET https://node-precompiled-binaries.grpc.io/grpc/v1.22.2/node-v79-win32-x64-unknown.tar.gz
node-pre-gyp http 404 https://node-precompiled-binaries.grpc.io/grpc/v1.22.2/node-v79-win32-x64-unknown.tar.gz
node-pre-gyp WARN Tried to download(404): https://node-precompiled-binaries.grpc.io/grpc/v1.22.2/node-v79-win32-x64-unknown.tar.gz
node-pre-gyp WARN Pre-built binaries not found for grpc@1.22.2 and node@13.11.0 (node-v79 ABI, unknown) (falling back to source compile with node-gyp)
node-pre-gyp http 404 status code downloading tarball https://node-precompiled-binaries.grpc.io/grpc/v1.22.2/node-v79-win32-x64-unknown.tar.gz
gyp info it worked if it ends with ok
gyp info using node-gyp@3.8.0
gyp info using node@13.11.0 | win32 | x64
gyp info ok
gyp info it worked if it ends with ok
gyp info using node-gyp@3.8.0
gyp info using node@13.11.0 | win32 | x64
gyp ERR! configure error
gyp ERR! stack Error: Command failed: C:\Python38\python.EXE -c import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack   File "<string>", line 1
gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack                       ^
gyp ERR! stack SyntaxError: invalid syntax
gyp ERR! stack
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:303:12)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at maybeClose (internal/child_process.js:1026:16)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
gyp ERR! System Windows_NT 10.0.17763
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "D:\\Better\\next.js\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "--fallback-to-build" "--library=static_library" "--module=D:\\Better\\next.js\\node_modules\\grpc\\src\\node\\extension_binary\\node-v79-win32-x64-unknown\\grpc_node.node" "--module_name=grpc_node" "--module_path=D:\\Better\\next.js\\node_modules\\grpc\\src\\node\\extension_binary\\node-v79-win32-x64-unknown" "--napi_version=6" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v79"
gyp ERR! cwd D:\Better\next.js\node_modules\grpc
gyp ERR! node -v v13.11.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'C:\Program Files\nodejs\node.exe D:\Better\next.js\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --library=static_library --module=D:\Better\next.js\node_modules\grpc\src\node\extension_binary\node-v79-win32-x64-unknown\grpc_node.node --module_name=grpc_node --module_path=D:\Better\next.js\node_modules\grpc\src\node\extension_binary\node-v79-win32-x64-unknown --napi_version=6 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v79' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (D:\Better\next.js\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1026:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
node-pre-gyp ERR! System Windows_NT 10.0.17763
node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "D:\\Better\\next.js\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build" "--library=static_library"
node-pre-gyp ERR! cwd D:\Better\next.js\node_modules\grpc
node-pre-gyp ERR! node -v v13.11.0
node-pre-gyp ERR! node-pre-gyp -v v0.13.0
node-pre-gyp ERR! not ok
```

## System information

- OS: Windows 10 64-bit Version 10.0.17763

**Comment by filipesmedeiros** [comment]
Ok after changing Python to version 2, the installation proceeds further, but then errors even worsely(?) , the error doesn't fit in the terminal, so I'm assuming Windows support is not there yet? Or did I do something wrong?

**Comment by timneutkens** [comment]
You'll probably want to use a lower version of Node.js, eg v12.14.1

**Comment by filipesmedeiros** [comment]
Yup, that was it! Thanks. Btw, not that I need it for anything, but is there out-of-the box Node 13 support coming? Maybe once it's LTS right?

**Comment by timneutkens** [comment]
It's already supported by Next.js, Node 13 has node-gyp related bugs, but it's only relevant to some devdeps

**Comment by balazsorban44** [comment]
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
