### ISSUE TITLE
issue with webpack-analyzer + HMR

### ISSUE THREAD

**Issue by sedubois** [zeit/next.js#1143]
I get the error below when developing with the webpack analyzer (configured as instructed in @timneutkens' example).

Code: https://github.com/relatenow/relate

```
$ nodemon -w server -w universal 
[nodemon] 1.11.0
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: /Users/sdubois/Documents/relate/server/**/* /Users/sdubois/Documents/relate/universal/**/*
[nodemon] starting `node ./server`
> Using external babel configuration
> location: "/Users/sdubois/Documents/relate/package.json"
> Using "webpack" config function defined in next.config.js.
c DONE  Compiled successfully in 15491ms

> Ready on http://localhost:3000
Webpack Bundle Analyzer is started at http://127.0.0.1:8888
Use Ctrl+C to close it
c WAIT  Compiling...

c DONE  Compiled successfully in 2941ms

Couldn't parse bundle asset "/Users/sdubois/Documents/relate/.next/4.e69f6923a6bd656a9415.hot-update.js".
Analyzer will use module sizes from stats file.

events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE 127.0.0.1:8888
    at Object.exports._errnoException (util.js:1022:11)
    at exports._exceptionWithHostPort (util.js:1045:20)
    at Server._listen2 (net.js:1262:14)
    at listen (net.js:1298:10)
    at doListening (net.js:1397:7)
    at _combinedTickCallback (internal/process/next_tick.js:77:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
[nodemon] app crashed - waiting for file changes before starting...
```

**Comment by eezing** [comment]
Looks like watch mode is a no-go: https://github.com/th0r/webpack-bundle-analyzer/issues/37

**Comment by timneutkens** [comment]
Right, we should update the example to use stats.json instead of the server.
