### ISSUE TITLE
Internal Server Error - TypeError: lowPriorityScripts is not iterable

### ISSUE THREAD

**Issue by shubhamkushwahsk** [zeit/next.js#11463]
# Bug report

## Describe the bug

I have a very basic Next.js App setup, and everything works just perfectly on development. But as soon as I build the app and deploy to the server, it doesn't render the default 404 page, but instead shows:
> Internal server error

## To Reproduce

1. Build the next app, using "next build"
2. Deploy it to ubuntu server (Nginx)
3. Run the app using "next start -p 8000"
4. Go to a random route that doesn't exist (e.g. /xyz)

## What is working

The development and even production build if served via "next start" on my mac.

## Expected behavior

The default 404 page should be rendered, instead of the error "Internal server error".

## Error Log

```
TypeError: lowPriorityScripts is not iterable
at NextScript.getScripts (/home/ubuntu/app/.next/server/static/-w_wsy_dLbzAUuf_h5xwp/pages/_document.js:824:34)
at NextScript.render (/home/ubuntu/app/.next/server/static/-w_wsy_dLbzAUuf_h5xwp/pages/_document.js:948:182)
at processChild (/home/ubuntu/app/node_modules/react-dom/cjs/react-dom-server.node.development.js:3293:18)
at resolve (/home/ubuntu/app/node_modules/react-dom/cjs/react-dom-server.node.development.js:3124:5)
at ReactDOMServerRenderer.render (/home/ubuntu/app/node_modules/react-dom/cjs/react-dom-server.node.development.js:3598:22)
at ReactDOMServerRenderer.read (/home/ubuntu/app/node_modules/react-dom/cjs/react-dom-server.node.development.js:3536:29)
at Object.renderToStaticMarkup (/home/ubuntu/app/node_modules/react-dom/cjs/react-dom-server.node.development.js:4261:27)
at renderDocument (/home/ubuntu/app/node_modules/next/dist/next-server/server/render.js:91:18)
at Object.renderToHTML (/home/ubuntu/app/node_modules/next/dist/next-server/server/render.js:369:16)
at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

## Server information

- OS: Ubuntu
- Browser: Chrome
- Version of Next.js: [e.g. 9.1.7]

## Additional Information

I have a customized `_document.js` if that can cause some issue.

**Comment by shubhamkushwahsk** [comment]
I have also tried custom `_error.js`, and `404.js`, but I still see: Internal server error after deployment.

**Comment by amancp** [comment]
Hi @shubhamkushwahsk, Have you rectified this issue. I am facing the same issue while deployment. 

TypeError: lowPriorityScripts is not iterable

This build is working fine in local environment but when making it live I found this error.

Could you help me in this?

**Comment by timneutkens** [comment]
Please provide a complete reproduction so that we can investigate

**Comment by amancp** [comment]
> Please provide a complete reproduction so that we can investigate

Hi @shubhamkushwahsk, Have you rectified this issue. I am facing the same issue while deployment. 

This build is working fine in local environment but when making it live I found this error.

Could you help me in this? 

### To Reproduce

- Build the next app, using "next run build"
- Deploy it to ubuntu server (Nginx)
- Run the app using "PORT=3000 next start"
- Go to home page

### PM2 Log 

TypeError: lowPriorityScripts is not iterable
at NextScript.getScripts (/data/ccreact/build/reactcc/server/static/xwlk8nuqm/pages/_document.js:892:34)
at NextScript.render (/data/ccreact/build/reactcc/server/static/xwlk8nuqm/pages/_document.js:1016:182)
at d (/data/ccreact/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:38:231)
at $a (/data/ccreact/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:39:16)
at a.b.render (/data/ccreact/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:44:476)
at a.b.read (/data/ccreact/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:44:18)
at Object.renderToStaticMarkup (/data/ccreact/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:54:462)
at renderDocument (/data/ccreact/node_modules/next/dist/next-server/server/render.js:90:18)
at Object.renderToHTML (/data/ccreact/node_modules/next/dist/next-server/server/render.js:375:16)
at process._tickCallback (internal/process/next_tick.js:68:7)

### Server Information
- OS: Ubuntu
- Browser: Chrome
- Version of Next.js: ^9.2.2
- Version of Node: v10.16.0

This is getting undefined on server http://prnt.sc/rpaxa3 but working fine on local system.

**Comment by Timer** [comment]
You're likely not copying your `package-lock.json` or `yarn.lock` to your production server before dependency install, causing a Next.js version mismatch.

**Comment by jkjustjoshing** [comment]
When I was on Next.js v9.1, I was able to do the equivalent of the following:
```
npm ci
next build
rm -rf node_modules
npm ci --only=production
next start
```
to reduce the size of my production Docker image. Upgrading to Next.js >= 9.2, I'm getting the above error.

Is there a solution to this that doesn't involve including all my dev dependencies on production? I really don't want to pay for storage space to hold my storybook, unit testing, and linting dependencies that aren't used in production.

**Comment by Timer** [comment]
@jkjustjoshing I'm not sure how those steps are relevant to this issue. Please provide a full demo and check my above comment.

**Comment by amancp** [comment]
> You're likely not copying your `package-lock.json` or `yarn.lock` to your production server before dependency install, causing a Next.js version mismatch.

Thanks @Timer, it is definitely related with `package-lock.json` or `yarn.lock` file which was not updating due to some reason.

I have updated it on server and re-installed the dependencies again.

**Comment by amancp** [comment]
Hi @shubhamkushwahsk , 

Try the same and mark is fixed if above solution is working for you as well.

**Comment by shubhamkushwahsk** [comment]
Thanks @Timer @amancp
Running `npm install` on the server solved it!

**Comment by malimccalla** [comment]
I was having the same issue running my application in a Docker container. Turns out I was not copying the `yarn.lock` file in the image

**Comment by balazsorban44** [comment]
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
