### ISSUE TITLE
I receive the following errors when trying to build

### ISSUE THREAD

**Issue by MacHooper** [zeit/next.js#11659]
# Bug report

## Describe the bug
Upon running yarn build, I  receive errors.

`Automatically optimizing pages ...
Error occurred prerendering page "/art/a". Read more: https://err.sh/next.js/prerender-error:
Error: Cannot find module './a.md'

Error occurred prerendering page "/blog/po". Read more: https://err.sh/next.js/prerender-error:
Error: Cannot find module './po.md'

Error occurred prerendering page "/photo/pho". Read more: https://err.sh/next.js/prerender-error:
Error: Cannot find module './pho.md'

Error occurred prerendering page "/design/des". Read more: https://err.sh/next.js/prerender-error:
Error: Cannot find module './des.md'

> Build error occurred
Error: Export encountered errors
    at _default (/home/mac/Documents/lucy-portfolio/node_modules/next/dist/export/index.js:19:1086)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async build (/home/mac/Documents/lucy-portfolio/node_modules/next/dist/build/index.js:36:218)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
`
## To Reproduce

Run Yarn Build on this particular site.

## Expected behavior

The site should build without errors

## System information

- OS: Linux
- Browser (if applies) [e.g. chrome, safari]
- Version of Next.js: 9.3.4

## Additional context

In regards to the page rendering errors, those files do not exist and they are not called upon anywhere in my code.

As for the build errors I am unsure.

**Comment by c0b41** [comment]
dups. #11583

**Comment by timneutkens** [comment]
> In regards to the page rendering errors, those files do not exist and they are not called upon anywhere in my code.

You must have some markdown loading code somewhere in your application as Next.js does not have any markdown handling.

@c0b41 I doubt this is the same issue. This is just a case of an error being thrown somewhere in the application code.

@MacHooper can you provide a complete reproduction as asked for in the issue template.

Just to illustrate the way that someone would currently look at the issue:

```
To Reproduce

Run Yarn Build on this particular site.
```

Which particular site? There is no site nor repository included in your issue.

**Comment by balazsorban44** [comment]
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
