### ISSUE TITLE
Setting maxAge in setPreviewData throws an error

### ISSUE THREAD

**Issue by mrgnou** [zeit/next.js#11712]
# Bug report

## Describe the bug

I'm playing around with the new preview mode released in 9.3, and setting maxAge property on setPreviewData results in the following server error:

```
Error: invalid expiresIn option for string payload
    at Object.e.exports [as sign] (/private/var/www/node_modules/next/dist/compiled/jsonwebtoken/index.js:1:37404)
    at setPreviewData (/private/var/www/node_modules/next/dist/next-server/server/api-utils.js:293:34)
    at ServerResponse.apiRes.setPreviewData (/private/var/www/node_modules/next/dist/next-server/server/api-utils.js:37:57)
```

## To Reproduce

Create an /api/preview.js page module:

```js
export const Preview = async (req, res) => {
	res.setPreviewData({}, {maxAge: 60 * 60})
	// res.writeHead(307, { Location: my_slug })
	res.end()
}
export default Preview
```

And access /api/preview

## Expected behavior

 [maxAge](https://nextjs.org/docs/advanced-features/preview-mode#specify-the-preview-mode-duration) should properly set preview cookies expiry.

## System information

- OS macOS
- Browser chrome
- Version of Next.js: 9.3.4

**Comment by Akhr0** [comment]
Same problem =/

**Comment by balazsorban44** [comment]
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
