### ISSUE TITLE
Build Error - Upgrading from Next 9.2 to Next 9.3.3

### ISSUE THREAD

**Issue by rtm619** [zeit/next.js#11748]
# Bug report

## Describe the bug

After upgrading from Next 9.2 to 9.3, I am facing a build error whenever I try to build my project.

## To Reproduce

Upgrade Next 9.2 to 9.3.3. Try next build.

## Expected behavior

Build should be successful.

## System information

- OS: Windows
- Version of Next.js: 9.3.3

## Additional context

Following is the error stack trace: 
```

> Location: "D:\Workspace\.babelrc"
Creating an optimized production build ..fs.js:885
  return binding.mkdir(pathModule._makeLong(path),
                 ^

Error: EEXIST: file already exists, mkdir 'D:\Workspace\.next\cache\next-minifier'
    at fs.mkdirSync (fs.js:885:18)
    at new TaskRunner (D:\Workspace\node_modules\next\dist\build\webpack\plugins\terser-webpack-plugin\src\TaskRunner.js:1:634)    
    at TerserPlugin.optimizeFn (D:\Workspace\node_modules\next\dist\build\webpack\plugins\terser-webpack-plugin\src\index.js:6:1316)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (D:\Workspace\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:21:1)
    at AsyncSeriesHook.lazyCompileHook (D:\Workspace\node_modules\tapable\lib\Hook.js:154:20)
    at hooks.additionalAssets.callAsync.err (D:\Workspace\node_modules\webpack\lib\Compilation.js:1409:36)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (D:\Workspace\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (D:\Workspace\node_modules\tapable\lib\Hook.js:154:20)
    at hooks.optimizeTree.callAsync.err (D:\Workspace\node_modules\webpack\lib\Compilation.js:1405:32)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (D:\Workspace\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:6:1)
```

My .babelrc:

```
{
  "presets": [
    [
      "next/babel",
      {
        "transform-runtime": { "useESModules": false },
        "preset-env": {
          "targets": {
            "browsers": [">0.03%"]
          },
          "useBuiltIns": "usage",
          "corejs": 3
        }
      }
    ]
  ],
  "plugins": [
    "@babel/plugin-proposal-optional-chaining",
    ["@babel/plugin-proposal-decorators", { "legacy": true }],
    ["@babel/plugin-proposal-class-properties", { "loose": true }]
  ]
}

```

My Dependencies:

```
"dependencies": {
    "apollo-cache-inmemory": "^1.6.3",
    "apollo-client": "^2.6.4",
    "apollo-link-http": "^1.5.16",
    "axios": "^0.19.0",
    "classnames": "^2.2.6",
    "graphql": "^14.5.8",
    "graphql-tag": "^2.10.1",
    "isomorphic-unfetch": "^3.0.0",
    "lodash.isempty": "^4.4.0",
    "mobx": "^4.15.0",
    "mobx-react": "^6.1.4",
    "next": "^9.3.3",
    "picturefill": "^3.0.3",
    "prop-types": "^15.7.2",
    "qs-stringify": "^1.2.0",
    "react": "^16.8.6",
    "react-dom": "^16.8.6",
    "react-lazyload": "^2.6.5",
    "react-markdown": "^4.2.2",
    "react-reveal": "^1.2.2",
    "react-slick": "^0.25.2",
    "validatorjs": "^3.18.1"
  },
  "devDependencies": {
    "@babel/core": "^7.8.4",
    "@babel/plugin-proposal-decorators": "^7.4.4",
    "@babel/plugin-proposal-optional-chaining": "^7.2.0",
    "@elastic/site-search-node": "^1.0.1",
    "@fullhuman/postcss-purgecss": "^1.3.0",
    "@storybook/addon-actions": "^5.3.13",
    "@storybook/addon-knobs": "^5.3.14",
    "@storybook/addon-links": "^5.3.13",
    "@storybook/addons": "^5.3.13",
    "@storybook/react": "^5.3.13",
    "autoprefixer": "^9.7.1",
    "babel-eslint": "^10.0.2",
    "babel-loader": "^8.0.6",
    "cssnano": "^4.1.10",
    "dotenv": "^8.1.0",
    "enzyme": "^3.10.0",
    "enzyme-adapter-react-16": "^1.15.1",
    "eslint": "^6.1.0",
    "eslint-config-airbnb": "^18.0.1",
    "eslint-plugin-import": "^2.18.2",
    "eslint-plugin-jsx-a11y": "^6.2.3",
    "eslint-plugin-react": "^7.14.3",
    "eslint-plugin-react-hooks": "^1.7.0",
    "googleapis": "^48.0.0",
    "husky": "^3.0.2",
    "jest": "^25.1.0",
    "jest-enzyme": "^7.1.2",
    "jest-mock-axios": "^3.1.2",
    "jest-next-dynamic": "^1.0.1",
    "postcss-import": "^12.0.1",
    "postcss-url": "^8.0.0",
    "prettier": "^1.18.2",
    "stylelint": "9.10.1",
    "stylelint-config-recommended": "2.1.0",
    "tailwindcss": "^1.1.3"
  },
```

Please advise the next course of action to resolve this issue.

**Comment by timneutkens** [comment]
You're potentially on an old version of Node.js that is not supported (eg below 10.13). Another potential solution is trying `next@canary` (a few fixes were landed recently).

**Comment by rtm619** [comment]
Hi Tim,

Thanks for the quick solution. I was indeed running Node 10.x. After upgrading to 12.x, the issue was resolved.

**Comment by balazsorban44** [comment]
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
