### ISSUE TITLE
when custom generateBuildId and webpack output.filename, Cannot find module

### ISSUE THREAD

**Issue by okyping** [zeit/next.js#11941]
# Bug report

## Describe the bug
Each rebuild will generate a new buildId， the buildid is a directory, most files' path will be changed when rebuilt.
![image](https://user-images.githubusercontent.com/2967319/79441757-38d91300-800a-11ea-9416-35e7914aa000.png)

not conducive to using browser cache

and if i use generateBuildId to custom buildid
```
generateBuildId: async () => {
    // For example get the latest git commit hash here
    return 'my-build-id'
  }
```
i must custom webpack config to refresh file name

```
webpack(config, {buildId, dev, isServer, defaultLoaders}) {
        ...
        config.output.filename = '[name].[hash:8].js';
        ...
}
```
![image](https://user-images.githubusercontent.com/2967319/79443456-6d4dce80-800c-11ea-9bc1-ef4832dc8075.png)

but then,
![image](https://user-images.githubusercontent.com/2967319/79443890-054bb800-800d-11ea-81e4-995ba5a34499.png)
```
Cannot find module 'somepath/ssr/server/static/xxx/pages/_app.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at hasCustomAppGetInitialProps (somepath/node_modules/next/dist/build/utils.js:25:1002)
```
because the output filename is _app.js.d80047c4.js

**Comment by timneutkens** [comment]
You shouldn't change these webpack settings when using Next.js. As asked in the other thread why are you trying to do this in the first place?

**Comment by juneeighteen** [comment]
To answer the "why" for me: I use bootstrap, and import the .css files in _app.js.  I serve my application under the /releases/buildId/ folder of an S3 bucket in AWS. This makes it super easy to test my new code.  The CSS for bootstrap is attempting to load from domain.dev/_next/static/... this is not what I want.  I want to control the output of this _next/static folder.  What other ways can I do this?

**Comment by 7iomka** [comment]
@juneeighteen you found a solution?

**Comment by juneeighteen** [comment]
@7iomka , Not really. I used shell scripts after the build process to fix this bug.

**Comment by balazsorban44** [comment]
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
