### ISSUE TITLE
Error installing boilerplate from react-intl example

### ISSUE THREAD

**Issue by juanda99** [zeit/next.js#11978]
# Error installint react-intl example

First time using next so I apologize if it's my fault

Current node version: 

lts/* -> lts/erbium (-> v12.16.2)

OS: MacOS

Command executed:

```
➜   npm init next-app --example with-react-intl with-react-intl-app
npx: installed 1 in 1.776s
Creating a new Next.js app in /Users/juandaniel/Code/kkk/with-react-intl-app.

Downloading files for example with-react-intl. This might take a moment.

Installing packages. This might take a couple of minutes.

yarn install v1.3.2
(node:24684) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
info No lockfile found.
[1/4] 🔍  Resolving packages...
warning next > mkdirp@0.5.3: Legacy versions of mkdirp are no longer supported. Please update to mkdirp 1.x. (Note that the API surface has changed to use Promises in 1.x.)
warning next > resolve-url-loader > rework > css > urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
warning next > resolve-url-loader > rework > css > source-map-resolve > resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning "@formatjs/cli > @babel/plugin-proposal-class-properties@7.8.3" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@formatjs/cli > babel-plugin-const-enum@0.0.2" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@formatjs/cli > babel-plugin-const-enum@0.0.2" has unmet peer dependency "@babel/generator@^7.0.0-0".
warning "@formatjs/cli > @babel/preset-env@7.9.5" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@formatjs/cli > @babel/preset-typescript@7.9.0" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@formatjs/cli > @babel/plugin-proposal-class-properties > @babel/helper-create-class-features-plugin@7.9.5" has unmet peer dependency "@babel/core@^7.0.0".
warning "@formatjs/cli > @babel/preset-env > @babel/helper-compilation-targets@7.8.7" has unmet peer dependency "@babel/core@^7.0.0".
warning "@formatjs/cli > @babel/preset-env > @babel/plugin-proposal-json-strings@7.8.3" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@formatjs/cli > babel-plugin-const-enum > @babel/plugin-syntax-typescript@7.8.3" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@formatjs/cli > @babel/preset-env > @babel/plugin-proposal-async-generator-functions@7.8.3" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@formatjs/cli > @babel/preset-env > @babel/plugin-proposal-dynamic-import@7.8.3" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@formatjs/cli > @babel/preset-env > @babel/plugin-proposal-nullish-coalescing-operator@7.8.3" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@formatjs/cli > @babel/preset-env > @babel/plugin-proposal-object-rest-spread@7.9.5" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@formatjs/cli > @babel/preset-env > @babel/plugin-proposal-optional-chaining@7.9.0" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@formatjs/cli > @babel/preset-env > @babel/plugin-proposal-unicode-property-regex@7.8.8" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@formatjs/cli > @babel/preset-env > @babel/plugin-syntax-async-generators@7.8.4" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@formatjs/cli > @babel/preset-env > @babel/plugin-proposal-optional-catch-binding@7.8.3" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@formatjs/cli > @babel/preset-env > @babel/plugin-syntax-dynamic-import@7.8.3" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@formatjs/cli > @babel/preset-env > @babel/plugin-syntax-nullish-coalescing-operator@7.8.3" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@formatjs/cli > @babel/preset-env > @babel/plugin-syntax-json-strings@7.8.3" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@formatjs/cli > @babel/preset-env > @babel/plugin-syntax-object-rest-spread@7.8.3" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@formatjs/cli > @babel/preset-env > @babel/plugin-syntax-optional-chaining@7.8.3" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@formatjs/cli > @babel/preset-env > @babel/plugin-syntax-optional-catch-binding@7.8.3" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@formatjs/cli > @babel/preset-env > @babel/plugin-syntax-top-level-await@7.8.3" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@formatjs/cli > @babel/preset-env > @babel/plugin-syntax-numeric-separator@7.8.3" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@formatjs/cli > @babel/preset-env > @babel/plugin-transform-arrow-functions@7.8.3" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@formatjs/cli > @babel/preset-env > @babel/plugin-transform-block-scoped-functions@7.8.3" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@formatjs/cli > @babel/preset-env > @babel/plugin-transform-classes@7.9.5" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@formatjs/cli > @babel/preset-env > @babel/plugin-transform-computed-properties@7.8.3" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@formatjs/cli > @babel/preset-env > @babel/plugin-transform-async-to-generator@7.8.3" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@formatjs/cli > @babel/preset-env > @babel/plugin-transform-block-scoping@7.8.3" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@formatjs/cli > @babel/preset-env > @babel/plugin-transform-destructuring@7.9.5" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@formatjs/cli > @babel/preset-env > @babel/plugin-transform-dotall-regex@7.8.3" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@formatjs/cli > @babel/preset-env > @babel/plugin-transform-exponentiation-operator@7.8.3" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@formatjs/cli > @babel/preset-env > @babel/plugin-transform-duplicate-keys@7.8.3" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@formatjs/cli > @babel/preset-env > @babel/plugin-transform-for-of@7.9.0" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@formatjs/cli > @babel/preset-env > @babel/plugin-transform-literals@7.8.3" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@formatjs/cli > @babel/preset-env > @babel/plugin-transform-function-name@7.8.3" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@formatjs/cli > @babel/preset-env > @babel/plugin-transform-member-expression-literals@7.8.3" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@formatjs/cli > @babel/preset-env > @babel/plugin-transform-modules-systemjs@7.9.0" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@formatjs/cli > @babel/preset-env > @babel/plugin-transform-named-capturing-groups-regex@7.8.3" has unmet peer dependency "@babel/core@^7.0.0".
warning "@formatjs/cli > @babel/preset-env > @babel/plugin-transform-modules-commonjs@7.9.0" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@formatjs/cli > @babel/preset-env > @babel/plugin-transform-modules-umd@7.9.0" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@formatjs/cli > @babel/preset-env > @babel/plugin-transform-new-target@7.8.3" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@formatjs/cli > @babel/preset-env > @babel/plugin-transform-object-super@7.8.3" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@formatjs/cli > @babel/preset-env > @babel/plugin-transform-modules-amd@7.9.0" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@formatjs/cli > @babel/preset-env > @babel/plugin-transform-parameters@7.9.5" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@formatjs/cli > @babel/preset-env > @babel/plugin-transform-property-literals@7.8.3" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@formatjs/cli > @babel/preset-env > @babel/plugin-transform-reserved-words@7.8.3" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@formatjs/cli > @babel/preset-env > @babel/plugin-transform-shorthand-properties@7.8.3" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@formatjs/cli > @babel/preset-env > @babel/plugin-transform-template-literals@7.8.3" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@formatjs/cli > @babel/preset-env > @babel/plugin-transform-spread@7.8.3" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@formatjs/cli > @babel/preset-env > @babel/plugin-transform-typeof-symbol@7.8.4" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@formatjs/cli > @babel/preset-env > @babel/plugin-transform-sticky-regex@7.8.3" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@formatjs/cli > @babel/preset-env > @babel/plugin-transform-regenerator@7.8.7" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@formatjs/cli > @babel/preset-env > @babel/plugin-transform-unicode-regex@7.8.3" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@formatjs/cli > @babel/preset-env > @babel/preset-modules@0.1.3" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@formatjs/cli > @babel/preset-typescript > @babel/plugin-transform-typescript@7.9.4" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@formatjs/cli > @babel/preset-env > @babel/plugin-proposal-unicode-property-regex > @babel/helper-create-regexp-features-plugin@7.8.8" has unmet peer dependency "@babel/core@^7.0.0".
warning "next > sass-loader@8.0.2" has unmet peer dependency "node-sass@^4.0.0".
warning "next > sass-loader@8.0.2" has unmet peer dependency "sass@^1.3.0".
warning "next > sass-loader@8.0.2" has unmet peer dependency "fibers@>= 3.1.0".
[4/4] 📃  Building fresh packages...
[1/2] ⠄ full-icu: }
[2/2] ⠄ fsevents
[-/2] ⠄ waiting...
[-/2] ⠄ waiting...
error /Users/juandaniel/Code/kkk/with-react-intl-app/node_modules/full-icu: Command failed.
Exit code: 1
Command: node postinstall.js
Arguments:
Directory: /Users/juandaniel/Code/kkk/with-react-intl-app/node_modules/full-icu
Output:
internal/validators.js:117
    throw new ERR_INVALID_ARG_TYPE(name, 'string', value);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at validateString (internal/validators.js:117:11)
    at Object.resolve (path.js:980:7)
    at Object.<anonymous> (/Users/juandaniel/Code/kkk/with-react-intl-app/node_modules/full-icu/install-spawn.js:11:22)
    at Module._compile (internal/modules/cjs/loader.js:1156:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Module.require (internal/modules/cjs/loader.js:1042:19)
    at require (internal/modules/cjs/helpers.js:77:18)



Aborting installation.
  yarnpkg install --cwd /Users/juandaniel/Code/kkk/with-react-intl-app has failed.
```

**Comment by timneutkens** [comment]
Seems like an issue with the particular version of Node.js wrt native packages 🤔 The example has a dependency on `full-icu` which might have issues.

**Comment by juanda99** [comment]
Executing npm install after npm init next-app --example with-react-intl with-react-intl-app fix the issue

**Comment by timneutkens** [comment]
It was probably a fluke in npm's installing, feel free to close this issue.

**Comment by juanda99** [comment]
Not really a fluke. It always fails first time. It seems it needs to run  npm install twice!

**Comment by juanda99** [comment]
Uppps, just falling on my mac. Testing on Linux is ok, so I close the issue and will have a look at my local conf. Thanks!

**Comment by balazsorban44** [comment]
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
