### ISSUE TITLE
Cannot read property 'pageLoader' of null 

### ISSUE THREAD

**Issue by sorokinvj** [zeit/next.js#11999]
# Bug report
Hey guys, I saw this issue #9951 being resolved, but I am having the same error with react-testing library

## Describe the bug
I am trying to test a component, but have "Cannot read property 'pageLoader' of null" all over my tests (actually as many of them as many Links I have on a tested page) 

I am using NextJs with Redux example and test it with react-testing-library. 

the error:

```
[Error: Uncaught [TypeError: Cannot read property 'pageLoader' of null]
at reportException (/Users/vladislavsorokin/webprojects/rqc/node_modules/jsdom/lib/jsdom/living/helpers/runtime-script-errors.js:62:24)[39m
at innerInvokeEventListeners (/Users/vladislavsorokin/webprojects/rqc/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:332:9)[39m
at invokeEventListeners (/Users/vladislavsorokin/webprojects/rqc/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:267:3)[39m
at HTMLUnknownElementImpl._dispatch (/Users/vladislavsorokin/webprojects/rqc/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:214:9)[39m
at HTMLUnknownElementImpl.dispatchEvent (/Users/vladislavsorokin/webprojects/rqc/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:87:17)[39m
at HTMLUnknownElement.dispatchEvent (/Users/vladislavsorokin/webprojects/rqc/node_modules/jsdom/lib/jsdom/living/generated/EventTarget.js:144:23)[39m
at Object.invokeGuardedCallbackDev (/Users/vladislavsorokin/webprojects/rqc/node_modules/react-dom/cjs/react-dom.development.js:385:16)[39m
at invokeGuardedCallback (/Users/vladislavsorokin/webprojects/rqc/node_modules/react-dom/cjs/react-dom.development.js:440:31)[39m
at commitRootImpl (/Users/vladislavsorokin/webprojects/rqc/node_modules/react-dom/cjs/react-dom.development.js:25082:9)[39m
at unstable_runWithPriority (/Users/vladislavsorokin/webprojects/rqc/node_modules/scheduler/cjs/scheduler.development.js:697:12) TypeError: Cannot read property 'pageLoader' of null[39m
at Link.handleRef (/Users/vladislavsorokin/webprojects/rqc/node_modules/next/dist/client/link.js:8:710)[39m
at ref (/Users/vladislavsorokin/webprojects/rqc/node_modules/next/dist/client/link.js:13:67)[39m
at commitAttachRef (/Users/vladislavsorokin/webprojects/rqc/node_modules/react-dom/cjs/react-dom.development.js:22310:7)[39m
at commitLayoutEffects (/Users/vladislavsorokin/webprojects/rqc/node_modules/react-dom/cjs/react-dom.development.js:25349:7)[39m
at HTMLUnknownElement.callCallback (/Users/vladislavsorokin/webprojects/rqc/node_modules/react-dom/cjs/react-dom.development.js:336:14)[39m
at innerInvokeEventListeners (/Users/vladislavsorokin/webprojects/rqc/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:316:27)[39m
at invokeEventListeners (/Users/vladislavsorokin/webprojects/rqc/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:267:3)[39m
at HTMLUnknownElementImpl._dispatch (/Users/vladislavsorokin/webprojects/rqc/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:214:9)[39m
at HTMLUnknownElementImpl.dispatchEvent (/Users/vladislavsorokin/webprojects/rqc/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:87:17)[39m
at HTMLUnknownElement.dispatchEvent (/Users/vladislavsorokin/webprojects/rqc/node_modules/jsdom/lib/jsdom/living/generated/EventTarget.js:144:23)[39m
at Object.invokeGuardedCallbackDev (/Users/vladislavsorokin/webprojects/rqc/node_modules/react-dom/cjs/react-dom.development.js:385:16)[39m
at invokeGuardedCallback (/Users/vladislavsorokin/webprojects/rqc/node_modules/react-dom/cjs/react-dom.development.js:440:31)[39m
at commitRootImpl (/Users/vladislavsorokin/webprojects/rqc/node_modules/react-dom/cjs/react-dom.development.js:25082:9)[39m
at unstable_runWithPriority (/Users/vladislavsorokin/webprojects/rqc/node_modules/scheduler/cjs/scheduler.development.js:697:12)[39m
at runWithPriority$2 (/Users/vladislavsorokin/webprojects/rqc/node_modules/react-dom/cjs/react-dom.development.js:12149:10)[39m
at commitRoot (/Users/vladislavsorokin/webprojects/rqc/node_modules/react-dom/cjs/react-dom.development.js:24922:3)[39m
at finishSyncRender (/Users/vladislavsorokin/webprojects/rqc/node_modules/react-dom/cjs/react-dom.development.js:24329:3)[39m

at performSyncWorkOnRoot (/Users/vladislavsorokin/webprojects/rqc/node_modules/react-dom/cjs/react-dom.development.js:24307:9)[39m
at scheduleUpdateOnFiber (/Users/vladislavsorokin/webprojects/rqc/node_modules/react-dom/cjs/react-dom.development.js:23698:7)[39m
at updateContainer (/Users/vladislavsorokin/webprojects/rqc/node_modules/react-dom/cjs/react-dom.development.js:27103:3)[39m
at /Users/vladislavsorokin/webprojects/rqc/node_modules/react-dom/cjs/react-dom.development.js:27528:7[39m
at unbatchedUpdates (/Users/vladislavsorokin/webprojects/rqc/node_modules/react-dom/cjs/react-dom.development.js:24433:12)[39m
at legacyRenderSubtreeIntoContainer (/Users/vladislavsorokin/webprojects/rqc/node_modules/react-dom/cjs/react-dom.development.js:27527:5)[39m
at Object.render (/Users/vladislavsorokin/webprojects/rqc/node_modules/react-dom/cjs/react-dom.development.js:27608:10)[39m
at /Users/vladislavsorokin/webprojects/rqc/node_modules/@testing-library/react/dist/pure.js:86:25[39m
at batchedUpdates$1 (/Users/vladislavsorokin/webprojects/rqc/node_modules/react-dom/cjs/react-dom.development.js:24386:12)[39m
at act (/Users/vladislavsorokin/webprojects/rqc/node_modules/react-dom/cjs/react-dom-test-utils.development.js:1092:14)[39m
at render (/Users/vladislavsorokin/webprojects/rqc/node_modules/@testing-library/react/dist/pure.js:82:26)[39m
at render (/Users/vladislavsorokin/webprojects/rqc/utils/test-utils.js:28:10)[39m
at Object.<anonymous> (/Users/vladislavsorokin/webprojects/rqc/__tests__/index.test.js:12:25)[39m
at Object.asyncJestTest (/Users/vladislavsorokin/webprojects/rqc/node_modules/jest-jasmine2/build/jasmineAsyncInstall.js:100:37)[39m
at /Users/vladislavsorokin/webprojects/rqc/node_modules/jest-jasmine2/build/queueRunner.js:45:12[39m
at new Promise (<anonymous>)[39m
at mapper (/Users/vladislavsorokin/webprojects/rqc/node_modules/jest-jasmine2/build/queueRunner.js:28:19)[39m
at /Users/vladislavsorokin/webprojects/rqc/node_modules/jest-jasmine2/build/queueRunner.js:75:41[39m
at processTicksAndRejections (internal/process/task_queues.js:85:5)[39m

```

## System information

- OS:macOS 10.14.6
- Version of Next.js: 9.3.5
- Version of Node.js: 12.6.0

**Comment by doniyor2109** [comment]
@timneutkens Can I work on it?

**Comment by timneutkens** [comment]
Sure!

**Comment by doniyor2109** [comment]
@sorokinvj Could provide some snippet to reproduce? I could not to reproduce it.

**Comment by sorokinvj** [comment]
> @sorokinvj Could provide some snippet to reproduce? I could not to reproduce it.

@doniyor2109 I will do a snippet in a weekends, sorry can't make sooner than that. I mean I could open the whole project for access on github, but I am afraid this a lot of files!

**Comment by sorokinvj** [comment]
@doniyor2109 this is the repo https://github.com/sorokinvj/rqc-next-tests, basically its just three news cards that fetched from prismic.io (cms) and showed in ui

**Comment by doniyor2109** [comment]
@sorokinvj It seems the project has old version of Next. I upgraded to latest and it is working for me.
Here are changes https://github.com/sorokinvj/rqc-next-tests/pull/3

**Comment by sorokinvj** [comment]
@doniyor2109 worked, thanks! Strangely, why 'latest' in package.json didn't work?

**Comment by doniyor2109** [comment]
@sorokinvj `yarn upgrade` worked for me.

**Comment by timneutkens** [comment]
Can this issue be closed?

**Comment by sorokinvj** [comment]
@timneutkens sorry, forgot. Yes, thanks for the support!

**Comment by balazsorban44** [comment]
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
