### ISSUE TITLE
Error occurred prerendering page. Cannot read property of undefined.

### ISSUE THREAD

**Issue by raychuah** [zeit/next.js#12017]
# Bug report

## Describe the bug
Build error occured when run next build with dynamic path routing. 
Error code as below:
```
Automatically optimizing pages .
Error occurred prerendering page "/posts/[id]". Read more: https://err.sh/next.js/prerender-error:
TypeError: Cannot read property 'map' of undefined

> Build error occurred
Error: Export encountered errors
    at _default (D:\Workspace\nextJsTest\node_modules\next\dist\export\index.js:19:1086)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async build (D:\Workspace\nextJsTest\node_modules\next\dist\build\index.js:36:218)
Automatically optimizing pages .npm ERR! code ELIFECYCLE
```

## To Reproduce
Github repo [here](https://github.com/raychuah/nextjstest.git)

1. Clone or download github repo.
2. Run npm install
3. Run npm run build

## Expected behavior
No issue when execute npm run dev. It only happen when execute npm run build.
Expected no error occur.

## System information
- OS: Windows
- Browser Firefox
- Version of Next.js: 9.3.5
- Version of Node.js: 12.16.2

## Additional context
$ npm run build

> nextjstest@1.0.0 build D:\Workspace\nextJsTest
> next build

Creating an optimized production build

Compiled successfully.
```
Automatically optimizing pages .
Error occurred prerendering page "/posts/[id]". Read more: https://err.sh/next.js/prerender-error:
TypeError: Cannot read property 'map' of undefined

> Build error occurred
Error: Export encountered errors
    at _default (D:\Workspace\nextJsTest\node_modules\next\dist\export\index.js:19:1086)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async build (D:\Workspace\nextJsTest\node_modules\next\dist\build\index.js:36:218)
Automatically optimizing pages .npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! nextjstest@1.0.0 build: `next build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the nextjstest@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\User\AppData\Roaming\npm-cache\_logs\2020-04-19T05_52_20_084Z-debug.log
```

**Comment by ijjk** [comment]
Hi, it looks like you aren't handling the fallback behavior which you enabled by setting `fallback: true` [here](https://github.com/raychuah/nextjstest/blob/c5b43ba1a2a5a58bea19049576b225bdee0f4896/pages/posts/%5Bid%5D.jsx#L42). In your page component you need to check for `useRouter().isFallback` and render a loading state when using `fallback: true`.

An example of handling the fallback behavior in your page component can be seen here https://github.com/zeit/next.js/blob/4619996d4e854126e63a59bf501c14b3298dafff/examples/cms-prismic/pages/posts/%5Bslug%5D.js#L25-L27

**Comment by raychuah** [comment]
@ijjk Thanks a lot! It works after I add `router.isFallback`. Took me many hours of debugging.

I couldn't find any documentation regarding isLoading state though. Do you have any reference link?

**Comment by ijjk** [comment]
@raychuah here's a link to the related documentation: https://nextjs.org/docs/basic-features/data-fetching#fallback-pages

**Comment by raychuah** [comment]
Thanks!

**Comment by balazsorban44** [comment]
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
