### ISSUE TITLE
9.3.6-canary.9 "TypeError: Expected a string" on build

### ISSUE THREAD

**Issue by nodabladam** [zeit/next.js#12160]
# Bug report

When I update from 9.3.6-canary.8 to canary.9, I get this error in my build:

```
[ info ]  bundled successfully, waiting for typecheck results...
Promise {
  <rejected> TypeError: Expected a string
      at module.exports (C:\Users\enalm\code\nodabl\nodabl-app\packages\frontend-v2\node_modules\glob-to-regexp\index.js:3:11)
      at stringToRegexp (C:\Users\enalm\code\nodabl\nodabl-app\packages\frontend-v2\node_modules\watchpack\lib\watchpack.js:26:17)
      at C:\Users\enalm\code\nodabl\nodabl-app\packages\frontend-v2\node_modules\watchpack\lib\watchpack.js:34:38
      at Array.map (<anonymous>)
      at ignoredToRegexp (C:\Users\enalm\code\nodabl\nodabl-app\packages\frontend-v2\node_modules\watchpack\lib\watchpack.js:34:29)
      at normalizeOptions (C:\Users\enalm\code\nodabl\nodabl-app\packages\frontend-v2\node_modules\watchpack\lib\watchpack.js:49:12)
      at cachedNormalizeOptions (C:\Users\enalm\code\nodabl\nodabl-app\packages\frontend-v2\node_modules\watchpack\lib\watchpack.js:58:21)
      at new Watchpack (C:\Users\enalm\code\nodabl\nodabl-app\packages\frontend-v2\node_modules\watchpack\lib\watchpack.js:71:25)
      at NodeWatchFileSystem.watch (C:\Users\enalm\code\nodabl\nodabl-app\packages\frontend-v2\node_modules\next\node_modules\webpack\lib\node\NodeWatchFi
leSystem.js:42:18)
      at Watching.watch (C:\Users\enalm\code\nodabl\nodabl-app\packages\frontend-v2\node_modules\next\node_modules\webpack\lib\Watching.js:114:48)
      at C:\Users\enalm\code\nodabl\nodabl-app\packages\frontend-v2\node_modules\next\node_modules\webpack\lib\Watching.js:101:10
      at AsyncSeriesHook.eval [as callAsync] (eval at create (C:\Users\enalm\code\nodabl\nodabl-app\packages\frontend-v2\node_modules\tapable\lib\HookCode
Factory.js:33:10), <anonymous>:58:1)
      at Watching._done (C:\Users\enalm\code\nodabl\nodabl-app\packages\frontend-v2\node_modules\next\node_modules\webpack\lib\Watching.js:98:28)
      at C:\Users\enalm\code\nodabl\nodabl-app\packages\frontend-v2\node_modules\next\node_modules\webpack\lib\Watching.js:73:19
      at Compiler.emitRecords (C:\Users\enalm\code\nodabl\nodabl-app\packages\frontend-v2\node_modules\next\node_modules\webpack\lib\Compiler.js:499:39)
      at C:\Users\enalm\code\nodabl\nodabl-app\packages\frontend-v2\node_modules\next\node_modules\webpack\lib\Watching.js:54:20
      at C:\Users\enalm\code\nodabl\nodabl-app\packages\frontend-v2\node_modules\next\node_modules\webpack\lib\Compiler.js:485:14
      at _next2 (eval at create (C:\Users\enalm\code\nodabl\nodabl-app\packages\frontend-v2\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous
>:14:1)
      at eval (eval at create (C:\Users\enalm\code\nodabl\nodabl-app\packages\frontend-v2\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:
23:1)
      at C:\Users\enalm\code\nodabl\nodabl-app\packages\frontend-v2\node_modules\copy-webpack-plugin\dist\index.js:114:7
      at _next1 (eval at create (C:\Users\enalm\code\nodabl\nodabl-app\packages\frontend-v2\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous
>:19:1)
      at eval (eval at create (C:\Users\enalm\code\nodabl\nodabl-app\packages\frontend-v2\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:
33:1)
}
This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
```

## To Reproduce

Happens to me when navigating pages for the first time.  Seems like everything is still working, just much slower.

## System information

- OS: Windows
- Browser (if applies) [e.g. chrome, safari]
- Version of Next.js: 9.3.6-canary.9 (canary.8 works)
- Version of Node.js: 13.11.0

I don't know if this is something bad in my code exposed by the latest version or if there is an issue with next.  Hopefully this helps!

**Comment by Timer** [comment]
Could you please provide a full reproduction?

**Comment by nodabladam** [comment]
Sorry about the lack of reproduction, I didn't want to go too nuts if this was a known issue.  It looks like v9.3.6-canary.10 fixes the issue in my app.  Closing.

**Comment by balazsorban44** [comment]
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
