### ISSUE TITLE
'dev' script doesn't compile component with changed name in next@2.0.0-beta.32

### ISSUE THREAD

**Issue by Lyonsclay** [zeit/next.js#1260]
I am working on this repo, https://github.com/Lyonsclay/Blogus, from two different machines. I pulled some changes into my second machine, ran `npm run dev`, and got this error in the console.

```
These dependencies were not found in node_modules:

../components/Layout
../components/Layout
../components/Layout
```

I have a Layout.js component in a components folder I created. I changed the name from layout.js to Layout.js on the other machine before pushing. 

The error message I got in the browser is quite different;

```
Module not found: Error: [CaseSensitivePathsPlugin] `/Users/clay/Developer/Blogus/components/Layout.js` does not match the corresponding path on disk `layout.js`.
ModuleNotFoundError: Module not found: Error: [CaseSensitivePathsPlugin] `/Users/clay/Developer/Blogus/components/Layout.js` does not match the corresponding path on disk `layout.js`.
    at factoryCallback (/Users/clay/Developer/Blogus/node_modules/webpack/lib/Compilation.js:259:39)
    at /Users/clay/Developer/Blogus/node_modules/webpack/lib/NormalModuleFactory.js:234:19
    at /Users/clay/Developer/Blogus/node_modules/webpack/lib/NormalModuleFactory.js:69:21
    at /Users/clay/Developer/Blogus/node_modules/tapable/lib/Tapable.js:201:18
    at NormalModuleFactory.<anonymous> (/Users/clay/Developer/Blogus/node_modules/case-sensitive-paths-webpack-plugin/index.js:128:17)
    at NormalModuleFactory.applyPluginsAsyncWaterfall (/Users/clay/Developer/Blogus/node_modules/tapable/lib/Tapable.js:208:13)
    at onDoneResolving (/Users/clay/Developer/Blogus/node_modules/webpack/lib/NormalModuleFactory.js:68:11)
    at onDoneResolving (/Users/clay/Developer/Blogus/node_modules/webpack/lib/NormalModuleFactory.js:189:6)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```
Following issue #1042 I tried installing next@2.0.0-beta.21 locally, but the behaviour was the same.

My work around was to install next@2.0.0-beta.32 globally and run `next`.

**Comment by arunoda** [comment]
This is an issue because, you've `layout.js` in the disk but not `Layout.js`. You can require components with the correct case.

Git has some issue with detecting the filename case changes.
See: http://stackoverflow.com/questions/10523849/changing-capitalization-of-filenames-in-git

**Comment by arunoda** [comment]
Reopen with more info if that didn't help you.

**Comment by Lyonsclay** [comment]
That was definitely it, thanks for your help!
