### ISSUE TITLE
Cannot find module babel/find-config when deploying to Heroku 

### ISSUE THREAD

**Issue by baboons** [zeit/next.js#1268]
Everything works fine when running locally but it won't build on Heroku.
I have reached an end and tried everything. Cant figure it out nor can I find any Issue for it (might be an undiscovered bug or just me doing it wrong).

```
2017-02-24T19:18:12.748920+00:00 app[web.1]: > next build
2017-02-24T19:18:12.748921+00:00 app[web.1]:
2017-02-24T19:18:14.938728+00:00 heroku[web.1]: State changed from starting to crashed
2017-02-24T19:18:14.913606+00:00 heroku[web.1]: Process exited with status 1
2017-02-24T19:18:14.750137+00:00 app[web.1]: module.js:471
2017-02-24T19:18:14.750151+00:00 app[web.1]:     throw err;
2017-02-24T19:18:14.750151+00:00 app[web.1]:     ^
2017-02-24T19:18:14.750152+00:00 app[web.1]:
2017-02-24T19:18:14.750153+00:00 app[web.1]: Error: Cannot find module './babel/find-config'
2017-02-24T19:18:14.750154+00:00 app[web.1]:     at Function.Module._resolveFilename (module.js:469:15)
2017-02-24T19:18:14.750155+00:00 app[web.1]:     at Function.Module._load (module.js:417:25)
2017-02-24T19:18:14.750155+00:00 app[web.1]:     at Module.require (module.js:497:17)
2017-02-24T19:18:14.750156+00:00 app[web.1]:     at require (internal/module.js:20:19)
2017-02-24T19:18:14.750157+00:00 app[web.1]:     at Object.<anonymous> (/app/node_modules/next/dist/server/build/webpack.js:75:19)
2017-02-24T19:18:14.750158+00:00 app[web.1]:     at Module._compile (module.js:570:32)
2017-02-24T19:18:14.750159+00:00 app[web.1]:     at Object.Module._extensions..js (module.js:579:10)
2017-02-24T19:18:14.750160+00:00 app[web.1]:     at Function.Module._load (module.js:438:3)
2017-02-24T19:18:14.750159+00:00 app[web.1]:     at Module.load (module.js:487:32)
2017-02-24T19:18:14.750160+00:00 app[web.1]:     at tryModuleLoad (module.js:446:12)
2017-02-24T19:18:14.773753+00:00 app[web.1]:
2017-02-24T19:18:14.785477+00:00 app[web.1]: npm ERR! Linux 3.13.0-105-generic
2017-02-24T19:18:14.785961+00:00 app[web.1]: npm ERR! argv "/app/.heroku/node/bin/node" "/app/.heroku/node/bin/npm" "start"
2017-02-24T19:18:14.786218+00:00 app[web.1]: npm ERR! node v6.9.5
2017-02-24T19:18:14.786445+00:00 app[web.1]: npm ERR! npm  v3.10.10
2017-02-24T19:18:14.786673+00:00 app[web.1]: npm ERR! code ELIFECYCLE
```

```
{
  "name": "scrape-wizard",
  "version": "0.0.1",
  "scripts": {
    "dev": "next",
    "build": "next build",
    "prestart": "next build",
    "start": "next start -p $PORT",
    "heroku-postbuild": "heroku-nextjs-build"
  },
  "engines": {
    "node": "6.9.x"
  },
  "cacheDirectories": [
    "nextjs/node_modules"
  ],
  "dependencies": {
    "@mars/heroku-nextjs-build": "^1.1.0",
    "next": "^2.0.0-beta",
    "next-route": "^1.0.2",
    "path-match": "1.2.4",
    "postcss-cssnext": "^2.9.0",
    "react": "^15.4.2",
    "react-dom": "^15.4.2",
    "react-edit-inline": "^1.0.8",
    "react-google-login": "^2.8.2",
    "styled-jsx-postcss": "^0.1.5"
  },
  "routes": {
    "/view/:id": "/view",
    "/edit/:id": "/edit"
  },
  "devDependencies": {
    "babel-preset-stage-0": "^6.16.0"
  }
}
```

**Comment by impronunciable** [comment]
Hi @baboons thanks for reporting

We have a similar issue https://github.com/zeit/next.js/issues/198 and seemed to be fixed some days ago https://github.com/zeit/next.js/pull/1164

can you make sure you are using a version >= `2.0.0-beta.28` just to make sure is not the same issue?

Thanks in advance

**Comment by baboons** [comment]
Hi @impronunciable I'm running the latest beta (beta32) but I still get this issue. 

Ps. I discovered Now and fell in love (ditching Heroku).

**Comment by impronunciable** [comment]
@baboons I think @rauchg will be happy with your move to now :P 🔼  I'll try to take a look at this anyway. Thanks for reporting
