### ISSUE TITLE
Cannot set Headers for 'OPTIONS' API requests on dev server

### ISSUE THREAD

**Issue by fromi** [zeit/next.js#12790]
# Bug report

## Describe the bug

I am using micro-cors to allow cors on my next.js project. It works fine on my production environment.
I am trying to setup a complete development environment on my laptop. So I started my Next.js application at localhost:8080, and my React app that consumes the API on localhost:3000.
The OPTIONS request produces this error:
```
Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at ServerResponse.setHeader (_http_outgoing.js:470:11)
    at C:\Users\romai\IdeaProjects\Interlude\node_modules\micro-cors\lib\index.js:31:11
    at corsHandler (C:\Users\romai\IdeaProjects\Interlude\.next\server\static\development\pages\api\graphql.js:1898:79)
    at Object.apiResolver (C:\Users\romai\IdeaProjects\Interlude\node_modules\next\dist\next-server\server\api-utils.js:47:15)
    at DevServer.handleApiRequest (C:\Users\romai\IdeaProjects\Interlude\node_modules\next\dist\next-server\server\next-server.js:475:27)
```
I added so logs to my application to see what is happening:
```
async function corsHandler(req: NextApiRequest, res: NextApiResponse) {
  console.log(res.headersSent)
  console.log(res.getHeaders())
  cors((req, res) => req.method === 'OPTIONS' ? res.end() : handler(req, res))(req, res)
}
export default corsHandler
```
It appears that some headers are already send in the response, but only for OPTIONS request in development environments:
```
'access-control-allow-origin': 'http://localhost:3000',
'access-control-allow-methods': 'OPTIONS, GET',
'access-control-allow-headers': 'content-type'
```
I don't know where those headers comes from, however it is send before my handler is executed (and before micro-cors is called).

## Expected behavior

No headers send before my handler gets called, or some workaround.

## Additional context

I found that issue that might be related: https://github.com/zeit/next.js/issues/11752
However, I tried to setup the experimental feature described in that issue but my handler is no longer called, and the headers are not impacted either.

**Comment by eric-burel** [comment]
I seem to hit the same issue, when running a static build of Next as the frontend + the same application in development mode that serves as the backend (only using API routes).

**Comment by grubxy** [comment]
just the same error as yours.

**Comment by timneutkens** [comment]
I think I fixed this last sunday, can you try next@canary?

PR: https://github.com/zeit/next.js/pull/12978

**Comment by fromi** [comment]
I tried it, and it works indeed!
Thanks

**Comment by balazsorban44** [comment]
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
