### ISSUE TITLE
Cannot find module '@babel/code-frame'

### ISSUE THREAD

**Issue by kyleballard** [zeit/next.js#12905]
# Bug report

## Describe the bug

`npm run dev` creates an error indicating `Error: Cannot find module '@babel/code-frame'`

## To Reproduce

Following the basic step of running `npm init next-app sample-app` and then trying to execute `npm run dev` produces the error below.  I have cleared my global `AppData\Roaming\npm` folder on windows to attempt to isolate the application to just the current folder yet the issue persists.

## Expected behavior

I would expect to be able to execute the app without error, and view on localhost:3000

## System information

- OS: Windows
- Browser (if applies) [e.g. chrome, safari]: n/a
- Version of Next.js: 9.4.0
- Version of Node.js: 14.2.0

## Additional context

Full error message:
ready - started server on http://localhost:3000
Error: Cannot find module '@babel/code-frame'
Require stack:
- C:\Users\username\Documents\Projects\sample-app\node_modules\@next\react-dev-overlay\lib\middleware.js
- C:\Users\username\Documents\Projects\sample-app\node_modules\next\dist\server\hot-reloader.js
- C:\Users\username\Documents\Projects\sample-app\node_modules\next\dist\server\next-dev-server.js
- C:\Users\username\Documents\Projects\sample-app\node_modules\next\dist\server\next.js
- C:\Users\username\Documents\Projects\sample-app\node_modules\next\dist\server\lib\start-server.js
- C:\Users\username\Documents\Projects\sample-app\node_modules\next\dist\cli\next-dev.js
- C:\Users\username\Documents\Projects\sample-app\node_modules\next\dist\bin\next
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1020:15)
    at Function.Module._load (internal/modules/cjs/loader.js:890:27)
    at Module.require (internal/modules/cjs/loader.js:1080:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (C:\Users\username\Documents\Projects\sample-app\node_modules\@next\react-dev-overlay\lib\middleware.js:42:20)
    at Module._compile (internal/modules/cjs/loader.js:1176:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1196:10)
    at Module.load (internal/modules/cjs/loader.js:1040:32)
    at Function.Module._load (internal/modules/cjs/loader.js:929:14)
    at Module.require (internal/modules/cjs/loader.js:1080:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\username\\Documents\\Projects\\sample-app\\node_modules\\@next\\react-dev-overlay\\lib\\middleware.js',
    'C:\\Users\\username\\Documents\\Projects\\sample-app\\node_modules\\next\\dist\\server\\hot-reloader.js',
    'C:\\Users\\username\\Documents\\Projects\\sample-app\\node_modules\\next\\dist\\server\\next-dev-server.js',
    'C:\\Users\\username\\Documents\\Projects\\sample-app\\node_modules\\next\\dist\\server\\next.js',
    'C:\\Users\\username\\Documents\\Projects\\sample-app\\node_modules\\next\\dist\\server\\lib\\start-server.js',
    'C:\\Users\\username\\Documents\\Projects\\sample-app\\node_modules\\next\\dist\\cli\\next-dev.js',
    'C:\\Users\\username\\Documents\\Projects\\sample-app\\node_modules\\next\\dist\\bin\\next'
  ]
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sample-app@0.1.0 dev: `next dev`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sample-app@0.1.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\username\AppData\Roaming\npm-cache\_logs\2020-05-15T02_49_19_096Z-debug.log

**Comment by Timer** [comment]
Please try deleting your `package-lock.json` and re-running `npm i`.

**Comment by kyleballard** [comment]
I removed `package-lock.json` and re-ran `npm i`.   I get the same error.   The following output was provided after `npm i` if this helps:

npm WARN deprecated fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.2.7 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.1.2 (node_modules\fork-ts-checker-webpack-plugin\node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN Invalid name: "@ampproject/toolbox-core"
npm WARN Invalid name: "@ampproject/toolbox-runtime-version"
npm WARN Invalid name: "@ampproject/toolbox-script-csp"
npm WARN Invalid name: "@ampproject/toolbox-validator-rules"
npm WARN Invalid name: "@babel/code-frame"
npm WARN Invalid name: "@babel/compat-data"
npm WARN Invalid name: "@babel/generator"
npm WARN Invalid name: "@babel/helper-annotate-as-pure"
npm WARN Invalid name: "@babel/helper-builder-binary-assignment-operator-visitor"
npm WARN Invalid name: "@babel/helper-builder-react-jsx"
npm WARN Invalid name: "@babel/helper-builder-react-jsx-experimental"
npm WARN Invalid name: "@babel/helper-compilation-targets"
npm WARN Invalid name: "@babel/helper-create-class-features-plugin"
npm WARN Invalid name: "@babel/helper-create-regexp-features-plugin"
npm WARN Invalid name: "@babel/helper-define-map"
npm WARN Invalid name: "@babel/helper-explode-assignable-expression"
npm WARN Invalid name: "@babel/helper-function-name"
npm WARN Invalid name: "@babel/helper-get-function-arity"
npm WARN Invalid name: "@babel/helper-hoist-variables"
npm WARN Invalid name: "@babel/helper-member-expression-to-functions"
npm WARN Invalid name: "@babel/helper-module-imports"
npm WARN Invalid name: "@babel/helper-module-transforms"
npm WARN Invalid name: "@babel/helper-optimise-call-expression"
npm WARN Invalid name: "@babel/helper-plugin-utils"
npm WARN Invalid name: "@babel/helper-regex"
npm WARN Invalid name: "@babel/helper-remap-async-to-generator"
npm WARN Invalid name: "@babel/helper-replace-supers"
npm WARN Invalid name: "@babel/helper-simple-access"
npm WARN Invalid name: "@babel/helper-split-export-declaration"
npm WARN Invalid name: "@babel/helper-validator-identifier"
npm WARN Invalid name: "@babel/helper-wrap-function"
npm WARN Invalid name: "@babel/helpers"
npm WARN Invalid name: "@babel/highlight"
npm WARN Invalid name: "@babel/parser"
npm WARN Invalid name: "@babel/plugin-proposal-async-generator-functions"
npm WARN Invalid name: "@babel/plugin-proposal-dynamic-import"
npm WARN Invalid name: "@babel/plugin-proposal-json-strings"
npm WARN Invalid name: "@babel/plugin-proposal-optional-catch-binding"
npm WARN Invalid name: "@babel/plugin-proposal-unicode-property-regex"
npm WARN Invalid name: "@babel/plugin-syntax-async-generators"
npm WARN Invalid name: "@babel/plugin-syntax-json-strings"
npm WARN Invalid name: "@babel/plugin-syntax-jsx"
npm WARN Invalid name: "@babel/plugin-syntax-nullish-coalescing-operator"
npm WARN Invalid name: "@babel/plugin-syntax-numeric-separator"
npm WARN Invalid name: "@babel/plugin-syntax-object-rest-spread"
npm WARN Invalid name: "@babel/plugin-syntax-optional-catch-binding"
npm WARN Invalid name: "@babel/plugin-syntax-optional-chaining"
npm WARN Invalid name: "@babel/plugin-syntax-top-level-await"
npm WARN Invalid name: "@babel/plugin-syntax-typescript"
npm WARN Invalid name: "@babel/plugin-transform-arrow-functions"
npm WARN Invalid name: "@babel/plugin-transform-async-to-generator"
npm WARN Invalid name: "@babel/plugin-transform-block-scoped-functions"
npm WARN Invalid name: "@babel/plugin-transform-block-scoping"
npm WARN Invalid name: "@babel/plugin-transform-classes"
npm WARN Invalid name: "@babel/plugin-transform-computed-properties"
npm WARN Invalid name: "@babel/plugin-transform-destructuring"
npm WARN Invalid name: "@babel/plugin-transform-dotall-regex"
npm WARN Invalid name: "@babel/plugin-transform-duplicate-keys"
npm WARN Invalid name: "@babel/plugin-transform-exponentiation-operator"
npm WARN Invalid name: "@babel/plugin-transform-for-of"
npm WARN Invalid name: "@babel/plugin-transform-function-name"
npm WARN Invalid name: "@babel/plugin-transform-literals"
npm WARN Invalid name: "@babel/plugin-transform-member-expression-literals"
npm WARN Invalid name: "@babel/plugin-transform-modules-amd"
npm WARN Invalid name: "@babel/plugin-transform-modules-systemjs"
npm WARN Invalid name: "@babel/plugin-transform-modules-umd"
npm WARN Invalid name: "@babel/plugin-transform-named-capturing-groups-regex"
npm WARN Invalid name: "@babel/plugin-transform-new-target"
npm WARN Invalid name: "@babel/plugin-transform-object-super"
npm WARN Invalid name: "@babel/plugin-transform-parameters"
npm WARN Invalid name: "@babel/plugin-transform-property-literals"
npm WARN Invalid name: "@babel/plugin-transform-react-display-name"
npm WARN Invalid name: "@babel/plugin-transform-react-jsx"
npm WARN Invalid name: "@babel/plugin-transform-react-jsx-self"
npm WARN Invalid name: "@babel/plugin-transform-react-jsx-development"
npm WARN Invalid name: "@babel/plugin-transform-react-jsx-source"
npm WARN Invalid name: "@babel/plugin-transform-reserved-words"
npm WARN Invalid name: "@babel/plugin-transform-regenerator"
npm WARN Invalid name: "@babel/plugin-transform-shorthand-properties"
npm WARN Invalid name: "@babel/plugin-transform-spread"
npm WARN Invalid name: "@babel/plugin-transform-sticky-regex"
npm WARN Invalid name: "@babel/plugin-transform-template-literals"
npm WARN Invalid name: "@babel/plugin-transform-typeof-symbol"
npm WARN Invalid name: "@babel/plugin-transform-typescript"
npm WARN Invalid name: "@babel/plugin-transform-unicode-regex"
npm WARN Invalid name: "@babel/template"
npm WARN Invalid name: "@babel/traverse"
npm WARN Invalid name: "@types/color-name"
npm WARN Invalid name: "@webassemblyjs/floating-point-hex-parser"
npm WARN Invalid name: "@webassemblyjs/helper-api-error"
npm WARN Invalid name: "@webassemblyjs/helper-buffer"
npm WARN Invalid name: "@webassemblyjs/helper-code-frame"
npm WARN Invalid name: "@webassemblyjs/helper-fsm"
npm WARN Invalid name: "@webassemblyjs/helper-wasm-bytecode"
npm WARN Invalid name: "@webassemblyjs/helper-wasm-section"
npm WARN Invalid name: "@webassemblyjs/ieee754"
npm WARN Invalid name: "@webassemblyjs/leb128"
npm WARN Invalid name: "@webassemblyjs/utf8"
npm WARN Invalid name: "@webassemblyjs/wasm-gen"
npm WARN Invalid name: "@webassemblyjs/wasm-opt"
npm WARN Invalid name: "@webassemblyjs/wast-parser"
npm WARN Invalid name: "@webassemblyjs/wast-printer"
npm WARN Invalid name: "@xtuc/ieee754"
npm WARN Invalid name: "@xtuc/long"

added 221 packages from 3 contributors, removed 117 packages, updated 7 packages, moved 3 packages and audited 907 packages in 12.163s

33 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

**Comment by kyleballard** [comment]
This appears to be a general issue with my environment/machine in that npm scoped modules are not loaded.  I am unsure why this would be.  Same issue occurs with @angular/cli or any other scoped module.

**Comment by balazsorban44** [comment]
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
