### ISSUE TITLE
ReferenceError: $RefreshReg$ is not defined in 9.4

### ISSUE THREAD

**Issue by derekr** [zeit/next.js#12910]
# Bug report

## Describe the bug

Using latest Next.js version which enables Fast Refresh by default compilation seems to break with the error:

```
ReferenceError: $RefreshReg$ is not defined
```

Not urgent since you can disable FastRefresh, but wanted to start investigating and get pointed in the right direction if this seems like the wrong place to seek help.

I've traced it down to most likely something being dropped/lost in transpilation of the glaze module and glaze code being eval'd in the treat webpack plugin (where the error is thrown).

<details>
<summary>Full trace</summary>

```
ReferenceError: $RefreshReg$ is not defined
    at eval (webpack-internal:///./node_modules/next/dist/build/webpack/loaders/next-babel-loader.js?!./node_modules/glaze/dist-web/useStyling.treat.js:30:1)
    at Module../node_modules/next/dist/build/webpack/loaders/next-babel-loader.js?!./node_modules/glaze/dist-web/useStyling.treat.js (/Users/drk/dev/derekr/blergh.com/node_modules/glaze/dist-web/useStyling.treat.js:201:1)
    at __webpack_require__ (/Users/drk/dev/derekr/blergh.com/node_modules/glaze/dist-web/useStyling.treat.js:31:31)
    at /Users/drk/dev/derekr/blergh.com/node_modules/glaze/dist-web/useStyling.treat.js:104:18
    at /Users/drk/dev/derekr/blergh.com/node_modules/glaze/dist-web/useStyling.treat.js:107:10
    at Script.runInContext (vm.js:131:20)
    at Script.runInNewContext (vm.js:137:17)
    at module.exports (/Users/drk/dev/derekr/blergh.com/node_modules/eval/eval.js:73:12)
    at produce (/Users/drk/dev/derekr/blergh.com/node_modules/treat/webpack-plugin/loader.js:152:14)
ReferenceError: $RefreshReg$ is not defined
    at eval (webpack-internal:///./node_modules/next/dist/build/webpack/loaders/next-babel-loader.js?!./node_modules/glaze/dist-web/useStyling.treat.js:30:1)
    at Module../node_modules/next/dist/build/webpack/loaders/next-babel-loader.js?!./node_modules/glaze/dist-web/useStyling.treat.js (/Users/drk/dev/derekr/blergh.com/node_modules/glaze/dist-web/useStyling.treat.js:201:1)
    at __webpack_require__ (/Users/drk/dev/derekr/blergh.com/node_modules/glaze/dist-web/useStyling.treat.js:31:31)
    at /Users/drk/dev/derekr/blergh.com/node_modules/glaze/dist-web/useStyling.treat.js:104:18
    at /Users/drk/dev/derekr/blergh.com/node_modules/glaze/dist-web/useStyling.treat.js:107:10
    at Script.runInContext (vm.js:131:20)
    at Script.runInNewContext (vm.js:137:17)
    at module.exports (/Users/drk/dev/derekr/blergh.com/node_modules/eval/eval.js:73:12)
    at produce (/Users/drk/dev/derekr/blergh.com/node_modules/treat/webpack-plugin/loader.js:152:14)
```
</details>

## To Reproduce

Using:

Using the nextjs example app in [the glaze repo](https://github.com/kripod/glaze/tree/master/packages/example-nextjs), upgrade to latest `next` or `next@canary` and try running `yarn dev`. Should see the above error in the next server output. 

## Expected behavior

yarn dev works fine, no errors AND Fast Refresh works.

## Screenshots

<img width="1020" alt="Screen Shot 2020-05-14 at 10 00 12 PM" src="https://user-images.githubusercontent.com/22249/82013143-67a8d000-962e-11ea-8df3-c37bb822a175.png">

## System:
 - OS: macOS 10.15.4
 - CPU: (8) x64 Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz
 - Memory: 2.06 GB / 16.00 GB
 - Shell: 3.0.2 - /usr/local/bin/fish
## Binaries:
 - Node: 12.16.3 - ~/.fnm/current/bin/node
 - Yarn: 1.22.0 - /usr/local/bin/yarn
 - npm: 6.14.4 - ~/.fnm/current/bin/npm
## Browsers:
 - Chrome Canary: 84.0.4146.4
 - Firefox Developer Edition: 75.0
 - Safari: 13.1
## npmPackages:
 - glaze: ^0.5.1 => 0.5.1 
 - next: ^9.4.1-canary.4 => 9.4.1-canary.4 
 - next-treat: ^1.3.0 => 1.3.0 
 - react: ^16.13.1 => 16.13.1 
 - treat: ^1.4.1 => 1.4.1
## Additional context

Cross posting this in [the glaze repo](https://github.com/kripod/glaze/issues/36) (this is all p bleeding edge/early code) since that's where I'm seeing the error, but wondering if there is something to look for regarding how babel plays in to Fast Refresh and the potential pitfalls with other modules (next.js "plugins" in next.config.js) using babel transpilation that might get canceled/mangled in the next compilation process.

**Comment by timneutkens** [comment]
It's probably an issue with that plugin 🤔 Note that it's accidental that you can disable fast refresh and the old code will be removed very soon.

**Comment by derekr** [comment]
Yeah def think it's the plugin issue. Was curious if during implementation of Fast Refresh an error like this had come up and if there was a take away from nextjs extension authors. I think the eval is trying to mimic mini-css-extract-plugin or something without using it explicitly. Thanks for the heads up about removing that fast refresh toggle!

**Comment by balazsorban44** [comment]
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
