### ISSUE TITLE
Error using transform-define

### ISSUE THREAD

**Issue by sedubois** [zeit/next.js#1292]
An example of using transform-define for universal configuration is provided, but I have a weird error, which I narrowed down below (run it with babel-node): 

```json
// package.json
{
  "dependencies": {
    "babel-plugin-transform-define": "^1.2.0"
  },
  "babel": {
    "plugins": [
      [
        "transform-define",
        "./config.js"
      ]
    ]
  }
}
```
```js
// config.js
module.exports = { KEY: 'value' };
```
```js
// index.js
const config = require('./config');
console.log(config.KEY);
```

Somehow next manages to load my [app](https://github.com/relatenow/relate) based on the above principle just fine, but the `console.log` throws when I run the server myself (I'm trying to add integration tests):
```
TypeError: /Users/sdubois/Documents/relate-debug/index.js: Property property of MemberExpression expected node to be of a type ["Identifier"] but instead got "StringLiteral"
    at validate (/usr/local/lib/node_modules/babel-cli/node_modules/babel-types/lib/definitions/index.js:109:13)
    at Object.validate (/usr/local/lib/node_modules/babel-cli/node_modules/babel-types/lib/definitions/core.js:412:50)
    at Object.validate (/usr/local/lib/node_modules/babel-cli/node_modules/babel-types/lib/index.js:505:9)
    at NodePath._replaceWith (/usr/local/lib/node_modules/babel-cli/node_modules/babel-traverse/lib/path/replacement.js:176:7)
    at NodePath.replaceWith (/usr/local/lib/node_modules/babel-cli/node_modules/babel-traverse/lib/path/replacement.js:160:8)
    at replaceAndEvaluateNode (/Users/sdubois/Documents/relate-debug/node_modules/babel-plugin-transform-define/lib/index.js:111:12)
    at processNode (/Users/sdubois/Documents/relate-debug/node_modules/babel-plugin-transform-define/lib/index.js:148:5)
    at PluginPass.Identifier (/Users/sdubois/Documents/relate-debug/node_modules/babel-plugin-transform-define/lib/index.js:23:9)
    at newFn (/usr/local/lib/node_modules/babel-cli/node_modules/babel-traverse/lib/visitors.js:276:21)
    at NodePath._call (/usr/local/lib/node_modules/babel-cli/node_modules/babel-traverse/lib/path/context.js:76:18)
```

**Comment by sedubois** [comment]
Strangely enough, it works when I change to `console.log(config['KEY']))`.

**Comment by timneutkens** [comment]
`// index.js` = your custom server?
If you run it with babel-node it will transpile all occurences of `KEY` which might cause what you're seeing?

**Comment by sedubois** [comment]
OK it's because my custom server is normally simply started with `node server`, which doesn't do any babel stuff, but in my jest tests, the `require('../../server')` I'm using there is transformed by babel.

I'll try to adapt the babel config not to load that plugin in `test` env.

It's not trivial to get all the universal config right...

**Comment by sedubois** [comment]
@tim how can I set up my babel config, so that it doesn't transpile a certain folder (server/)?
