### ISSUE TITLE
with-redux-saga example crash

### ISSUE THREAD

**Issue by yxwu** [zeit/next.js#13187]
# Bug report

## Describe the bug

When using the latest version of next-redux-saga and next-redux-wrapper in package.json
```
    "next": "^9.4.2",
    "next-redux-saga": "^4.1.2",
    "next-redux-wrapper": "^6.0.0"
```
The app crashes:
```
event - compiled successfully
/!\ You are using legacy implementaion. Please update your code: use createWrapper() and wrapper.withRedux().
Error: Circular structure in "getInitialProps" result of page "/_error". https://err.sh/zeit/next.js/circular-structure
    at Function.getInlineScriptSource (webpack-internal:///./node_modules/next/dist/pages/_document.js:575:15)
    at NextScript.render (webpack-internal:///./node_modules/next/dist/pages/_document.js:655:28)
    at processChild (/Volumes/ramdisk/tmp/with-redux-saga-app/node_modules/react-dom/cjs/react-dom-server.node.development.js:3134:18)
    at resolve (/Volumes/ramdisk/tmp/with-redux-saga-app/node_modules/react-dom/cjs/react-dom-server.node.development.js:2960:5)
    at ReactDOMServerRenderer.render (/Volumes/ramdisk/tmp/with-redux-saga-app/node_modules/react-dom/cjs/react-dom-server.node.development.js:3435:22)
    at ReactDOMServerRenderer.read (/Volumes/ramdisk/tmp/with-redux-saga-app/node_modules/react-dom/cjs/react-dom-server.node.development.js:3373:29)
    at renderToStaticMarkup (/Volumes/ramdisk/tmp/with-redux-saga-app/node_modules/react-dom/cjs/react-dom-server.node.development.js:4004:27)
    at renderDocument (/Volumes/ramdisk/tmp/with-redux-saga-app/node_modules/next/dist/next-server/server/render.js:3:876)
    at renderToHTML (/Volumes/ramdisk/tmp/with-redux-saga-app/node_modules/next/dist/next-server/server/render.js:48:72)
    at async DevServer.renderToHTMLWithComponents (/Volumes/ramdisk/tmp/with-redux-saga-app/node_modules/next/dist/next-server/server/next-server.js:63:38)
    at async DevServer.renderErrorToHTML (/Volumes/ramdisk/tmp/with-redux-saga-app/node_modules/next/dist/next-server/server/next-server.js:99:321)
    at async DevServer.renderErrorToHTML (/Volumes/ramdisk/tmp/with-redux-saga-app/node_modules/next/dist/server/next-dev-server.js:22:1143)
    at async DevServer.renderToHTML (/Volumes/ramdisk/tmp/with-redux-saga-app/node_modules/next/dist/next-server/server/next-server.js:98:850)
    at async DevServer.renderToHTML (/Volumes/ramdisk/tmp/with-redux-saga-app/node_modules/next/dist/server/next-dev-server.js:22:539)
    at async DevServer.render (/Volumes/ramdisk/tmp/with-redux-saga-app/node_modules/next/dist/next-server/server/next-server.js:48:236)
    at async Object.fn (/Volumes/ramdisk/tmp/with-redux-saga-app/node_modules/next/dist/next-server/server/next-server.js:35:852)
```

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to 'http://localhost:3000'
2. crash

## Expected behavior

no crash

**Comment by VuongVu** [comment]
It not a bug, create a wrapper like the demo: [https://github.com/kirill-konshin/next-redux-wrapper/blob/master/packages/demo/src/components/store.tsx](url) and implement it in _app.js.
