### ISSUE TITLE
Cannot destructure property 'finished' of '(intermediate value)' as it is undefined.

### ISSUE THREAD

**Issue by muhaimincs** [zeit/next.js#13298]
# Bug report
```bash
TypeError: Cannot destructure property 'finished' of '(intermediate value)' as it is undefined.
    at HotReloader.run (/Users/user/Documents/project/node_modules/next/dist/server/hot-reloader.js:15:387)
    at async DevServer.run (/Users/user/Documents/project/node_modules/next/dist/server/next-dev-server.js:15:644)
    at async DevServer.handleRequest (/Users/user/Documents/project/node_modules/next/dist/next-server/server/next-server.js:13:133)
```
## Describe the bug
I just upgrade to next 9.4.2 and stumble upon this error

## To Reproduce
switch to next 9.4.2

**Comment by nero2009** [comment]
Hi I am getting the error and my hot reloading stops working after seeing this error. I can only fix this back restart my dev server but the problem comes back when I make any kind of change to my code

**Comment by balazsorban44** [comment]
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
