### ISSUE TITLE
next build fails on Heroku and Now but locally is fine ¯\_(ツ)_/¯

### ISSUE THREAD

**Issue by voronianski** [zeit/next.js#133]
```bash
 > utopiaframework.org@1.0.0 build /tmp/build_813464eed46e698e2cb2f1dbbf192448/luvitrocks-utopiaframework.org-c670071
       > next build
       
       { Error: ./components/header.js
       Module not found: Error: Cannot resolve 'file' or 'directory' ./Logo in /tmp/build_813464eed46e698e2cb2f1dbbf192448/luvitrocks-utopiaframework.org-c670071/components
       resolve file
       /tmp/build_813464eed46e698e2cb2f1dbbf192448/luvitrocks-utopiaframework.org-c670071/components/Logo doesn't exist
       /tmp/build_813464eed46e698e2cb2f1dbbf192448/luvitrocks-utopiaframework.org-c670071/components/Logo.webpack.js doesn't exist
       /tmp/build_813464eed46e698e2cb2f1dbbf192448/luvitrocks-utopiaframework.org-c670071/components/Logo.web.js doesn't exist
       /tmp/build_813464eed46e698e2cb2f1dbbf192448/luvitrocks-utopiaframework.org-c670071/components/Logo.js doesn't exist
       /tmp/build_813464eed46e698e2cb2f1dbbf192448/luvitrocks-utopiaframework.org-c670071/components/Logo.json doesn't exist
       resolve directory
       /tmp/build_813464eed46e698e2cb2f1dbbf192448/luvitrocks-utopiaframework.org-c670071/components/Logo doesn't exist (directory default file)
       /tmp/build_813464eed46e698e2cb2f1dbbf192448/luvitrocks-utopiaframework.org-c670071/components/Logo/package.json doesn't exist (directory description file)
       [/tmp/build_813464eed46e698e2cb2f1dbbf192448/luvitrocks-utopiaframework.org-c670071/components/Logo]
       [/tmp/build_813464eed46e698e2cb2f1dbbf192448/luvitrocks-utopiaframework.org-c670071/components/Logo.webpack.js]
       [/tmp/build_813464eed46e698e2cb2f1dbbf192448/luvitrocks-utopiaframework.org-c670071/components/Logo.web.js]
       [/tmp/build_813464eed46e698e2cb2f1dbbf192448/luvitrocks-utopiaframework.org-c670071/components/Logo.js]
       [/tmp/build_813464eed46e698e2cb2f1dbbf192448/luvitrocks-utopiaframework.org-c670071/components/Logo.json]
       @ ./components/header.js 15:12-29
       at /tmp/build_813464eed46e698e2cb2f1dbbf192448/luvitrocks-utopiaframework.org-c670071/node_modules/next/dist/server/build/index.js:54:31
       at Compiler.<anonymous> (/tmp/build_813464eed46e698e2cb2f1dbbf192448/luvitrocks-utopiaframework.org-c670071/node_modules/webpack/lib/Compiler.js:194:14)
       at Compiler.emitRecords (/tmp/build_813464eed46e698e2cb2f1dbbf192448/luvitrocks-utopiaframework.org-c670071/node_modules/webpack/lib/Compiler.js:282:37)
       at Compiler.<anonymous> (/tmp/build_813464eed46e698e2cb2f1dbbf192448/luvitrocks-utopiaframework.org-c670071/node_modules/webpack/lib/Compiler.js:187:11)
       at /tmp/build_813464eed46e698e2cb2f1dbbf192448/luvitrocks-utopiaframework.org-c670071/node_modules/webpack/lib/Compiler.js:275:11
       at Compiler.applyPluginsAsync (/tmp/build_813464eed46e698e2cb2f1dbbf192448/luvitrocks-utopiaframework.org-c670071/node_modules/tapable/lib/Tapable.js:60:69)
       at Compiler.afterEmit (/tmp/build_813464eed46e698e2cb2f1dbbf192448/luvitrocks-utopiaframework.org-c670071/node_modules/webpack/lib/Compiler.js:272:8)
       at Compiler.<anonymous> (/tmp/build_813464eed46e698e2cb2f1dbbf192448/luvitrocks-utopiaframework.org-c670071/node_modules/webpack/lib/Compiler.js:267:14)
       at /tmp/build_813464eed46e698e2cb2f1dbbf192448/luvitrocks-utopiaframework.org-c670071/node_modules/async/lib/async.js:52:16
       at done (/tmp/build_813464eed46e698e2cb2f1dbbf192448/luvitrocks-utopiaframework.org-c670071/node_modules/async/lib/async.js:246:17)
       errors: [ './components/header.jsnModule not found: Error: Cannot resolve 'file' or 'directory' ./Logo in /tmp/build_813464eed46e698e2cb2f1dbbf192448/luvitrocks-utopiaframework.org-c670071/componentsnresolve filen  /tmp/build_813464eed46e698e2cb2f1dbbf192448/luvitrocks-utopiaframework.org-c670071/components/Logo doesn't existn  /tmp/build_813464eed46e698e2cb2f1dbbf192448/luvitrocks-utopiaframework.org-c670071/components/Logo.webpack.js doesn't existn  /tmp/build_813464eed46e698e2cb2f1dbbf192448/luvitrocks-utopiaframework.org-c670071/components/Logo.web.js doesn't existn  /tmp/build_813464eed46e698e2cb2f1dbbf192448/luvitrocks-utopiaframework.org-c670071/components/Logo.js doesn't existn  /tmp/build_813464eed46e698e2cb2f1dbbf192448/luvitrocks-utopiaframework.org-c670071/components/Logo.json doesn't existnresolve directoryn  /tmp/build_813464eed46e698e2cb2f1dbbf192448/luvitrocks-utopiaframework.org-c670071/components/Logo doesn't exist (directory default file)n  /tmp/build_813464eed46e698e2cb2f1dbbf192448/luvitrocks-utopiaframework.org-c670071/components/Logo/package.json doesn't exist (directory description file)n[/tmp/build_813464eed46e698e2cb2f1dbbf192448/luvitrocks-utopiaframework.org-c670071/components/Logo]n[/tmp/build_813464eed46e698e2cb2f1dbbf192448/luvitrocks-utopiaframework.org-c670071/components/Logo.webpack.js]n[/tmp/build_813464eed46e698e2cb2f1dbbf192448/luvitrocks-utopiaframework.org-c670071/components/Logo.web.js]n[/tmp/build_813464eed46e698e2cb2f1dbbf192448/luvitrocks-utopiaframework.org-c670071/components/Logo.js]n[/tmp/build_813464eed46e698e2cb2f1dbbf192448/luvitrocks-utopiaframework.org-c670071/components/Logo.json]n @ ./components/header.js 15:12-29' ],
       warnings: [] }
       
       npm ERR! Linux 3.13.0-100-generic
       npm ERR! argv "/tmp/build_813464eed46e698e2cb2f1dbbf192448/luvitrocks-utopiaframework.org-c670071/.heroku/node/bin/node" "/tmp/build_813464eed46e698e2cb2f1dbbf192448/luvitrocks-utopiaframework.org-c670071/.heroku/node/bin/npm" "run" "build"
       npm ERR! node v7.0.0
       npm ERR! npm  v3.10.8
       npm ERR! code ELIFECYCLE
       npm ERR! utopiaframework.org@1.0.0 build: `next build`
       npm ERR! Exit status 1
       npm ERR!
       npm ERR! Failed at the utopiaframework.org@1.0.0 build script 'next build'.
       npm ERR! Make sure you have the latest version of node.js and npm installed.
       npm ERR! If you do, this is most likely a problem with the utopiaframework.org package,
       npm ERR! not with npm itself.
       npm ERR! Tell the author that this fails on your system:
       npm ERR!     next build
       npm ERR! You can get information on how to open an issue for this project with:
       npm ERR!     npm bugs utopiaframework.org
       npm ERR! Or if that isn't available, you can get their info via:
       npm ERR!     npm owner ls utopiaframework.org
       npm ERR! There is likely additional logging output above.
       
       npm ERR! Please include the following file with any support request:
       npm ERR!     /tmp/build_813464eed46e698e2cb2f1dbbf192448/luvitrocks-utopiaframework.org-c670071/npm-debug.log
       
       npm ERR! Linux 3.13.0-100-generic
       npm ERR! argv "/tmp/build_813464eed46e698e2cb2f1dbbf192448/luvitrocks-utopiaframework.org-c670071/.heroku/node/bin/node" "/tmp/build_813464eed46e698e2cb2f1dbbf192448/luvitrocks-utopiaframework.org-c670071/.heroku/node/bin/npm" "install" "--unsafe-perm" "--userconfig" "/tmp/build_813464eed46e698e2cb2f1dbbf192448/luvitrocks-utopiaframework.org-c670071/.npmrc"
       npm ERR! node v7.0.0
       npm ERR! npm  v3.10.8
       npm ERR! code ELIFECYCLE
       npm ERR! utopiaframework.org@1.0.0 postinstall: `npm run build`
       npm ERR! Exit status 1
       npm ERR!
       npm ERR! Failed at the utopiaframework.org@1.0.0 postinstall script 'npm run build'.
       npm ERR! Make sure you have the latest version of node.js and npm installed.
       npm ERR! If you do, this is most likely a problem with the utopiaframework.org package,
       npm ERR! not with npm itself.
       npm ERR! Tell the author that this fails on your system:
       npm ERR!     npm run build
       npm ERR! You can get information on how to open an issue for this project with:
       npm ERR!     npm bugs utopiaframework.org
       npm ERR! Or if that isn't available, you can get their info via:
       npm ERR!     npm owner ls utopiaframework.org
       npm ERR! There is likely additional logging output above.
       
       npm ERR! Please include the following file with any support request:
       npm ERR!     /tmp/build_813464eed46e698e2cb2f1dbbf192448/luvitrocks-utopiaframework.org-c670071/npm-debug.log
-----> Build failed
       
       We're sorry this build is failing! You can troubleshoot common issues here:
       https://devcenter.heroku.com/articles/troubleshooting-node-deploys
       
       Some possible problems:
       
       - Dangerous semver range (>) in engines.node
       https://devcenter.heroku.com/articles/nodejs-support#specifying-a-node-js-version
       
       Love,
       Heroku
```

**Comment by voronianski** [comment]
The same error is on `now .` deployment:

```bash
now .
> Deploying ~/github/utopiaframework.org
> Warning! Skipping file /Users/dmitri/github/utopiaframework.org/static/bg-pattern.png (size exceeded 1MB)
> Warning! 1 of the files exceeded the limit for your plan.
> See https://zeit.co/account to upgrade.
> Using Node.js 6.9.0 (requested: `>=6.0.0`)
> Ready! https://utopiaframeworkorg-ounymypstg.now.sh (copied to clipboard) [2s]
> Upload [====================] 100% 0.0s
> Sync complete (922B) [2s]
> Initializing…
> Building
> ▲ npm install
> Installing package highlight.js@^9.7.0
> Installing package next@^1.0.0
> Installing package react-highlight@^0.9.0
> (node:50) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: ENOENT: no such file or directory, readlink '/home/nowuser/src/node_modules/.tmp/11b1537c-3281-4106-a9ad-dcf5a7b0cdb9/node_modules/node-pre-gyp'
> node-pre-gyp info it worked if it ends with ok
> node-pre-gyp info using node-pre-gyp@0.6.29
> node-pre-gyp info using node@6.9.0 | linux | x64
> node-pre-gyp info check checked for "/home/nowuser/src/node_modules/09ad3fb161afd3f4b10cb78f85ad7a42d2a25d1f/lib/binding/Release/node-v48-linux-x64/fse.node" (not found)
> node-pre-gyp http GET https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.0.14/fse-v1.0.14-node-v48-linux-x64.tar.gz
> node-pre-gyp http 404 https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.0.14/fse-v1.0.14-node-v48-linux-x64.tar.gz
> node-pre-gyp ERR! Tried to download: https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.0.14/fse-v1.0.14-node-v48-linux-x64.tar.gz
> node-pre-gyp ERR! Pre-built binaries not found for fsevents@1.0.14 and node@6.9.0 (node-v48 ABI) (falling back to source compile with node-gyp)
> node-pre-gyp http Pre-built binary not available for your system, looked for https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.0.14/fse-v1.0.14-node-v48-linux-x64.tar.gz
> gyp info it worked if it ends with ok
> gyp info using node-gyp@3.3.1
> gyp info using node@6.9.0 | linux | x64
> gyp info ok
> gyp info it worked if it ends with ok
> gyp info using node-gyp@3.3.1
> gyp info using node@6.9.0 | linux | x64
> gyp http GET https://nodejs.org/download/release/v6.9.0/node-v6.9.0-headers.tar.gz
> gyp http 200 https://nodejs.org/download/release/v6.9.0/node-v6.9.0-headers.tar.gz
> gyp http GET https://nodejs.org/download/release/v6.9.0/SHASUMS256.txt
> gyp http 200 https://nodejs.org/download/release/v6.9.0/SHASUMS256.txt
> gyp info spawn /usr/bin/python2
> gyp info spawn args [ '/usr/lib/node_modules/node-gyp/gyp/gyp_main.py',
> gyp info spawn args   'binding.gyp',
> gyp info spawn args   'make',
> gyp info spawn args   '-f',
> gyp info spawn args   '-I',
> gyp info spawn args   '-I',
> gyp info spawn args   '/home/nowuser/src/node_modules/09ad3fb161afd3f4b10cb78f85ad7a42d2a25d1f/build/config.gypi',
> gyp info spawn args   '-Dnode_root_dir=/home/nowuser/.node-gyp/6.9.0',
> gyp info spawn args   '/usr/lib/node_modules/node-gyp/addon.gypi',
> gyp info spawn args   '-I',
> gyp info spawn args   '/home/nowuser/.node-gyp/6.9.0/include/node/common.gypi',
> gyp info spawn args   '-Dlibrary=shared_library',
> gyp info spawn args   '-Dvisibility=default',
> gyp info spawn args   '-Dnode_gyp_dir=/usr/lib/node_modules/node-gyp',
> gyp info spawn args   '--no-parallel',
> gyp info spawn args   '-Dnode_lib_file=node.lib',
> gyp info spawn args   '-Dmodule_root_dir=/home/nowuser/src/node_modules/09ad3fb161afd3f4b10cb78f85ad7a42d2a25d1f',
> gyp info spawn args   '--depth=.',
> gyp info spawn args   '-Goutput_dir=.' ]
> gyp info spawn args   '--generator-output',
> gyp info spawn args   'build',
> gyp info ok
> gyp info it worked if it ends with ok
> gyp info using node-gyp@3.3.1
> gyp info using node@6.9.0 | linux | x64
> gyp info spawn make
> gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
> make: Entering directory '/home/nowuser/src/node_modules/09ad3fb161afd3f4b10cb78f85ad7a42d2a25d1f/build'
>   SOLINK_MODULE(target) Release/obj.target/.node
>   COPY Release/.node
> make: Leaving directory '/home/nowuser/src/node_modules/09ad3fb161afd3f4b10cb78f85ad7a42d2a25d1f/build'
> gyp info ok
> node-pre-gyp info ok
> ▲ npm run build
> { Error: ./components/header.js
> Module not found: Error: Cannot resolve 'file' or 'directory' ./Logo in /home/nowuser/src/components
> resolve file
>   /home/nowuser/src/components/Logo doesn't exist
>   /home/nowuser/src/components/Logo.webpack.js doesn't exist
>   /home/nowuser/src/components/Logo.web.js doesn't exist
>   /home/nowuser/src/components/Logo.js doesn't exist
>   /home/nowuser/src/components/Logo.json doesn't exist
> resolve directory
>   /home/nowuser/src/components/Logo doesn't exist (directory default file)
>   /home/nowuser/src/components/Logo/package.json doesn't exist (directory description file)
> [/home/nowuser/src/components/Logo]
> [/home/nowuser/src/components/Logo.webpack.js]
> [/home/nowuser/src/components/Logo.web.js]
> [/home/nowuser/src/components/Logo.js]
> [/home/nowuser/src/components/Logo.json]
>  @ ./components/header.js 15:12-29
>     at /home/nowuser/src/node_modules/15744f4aba6ecb7d0a1750d7a4a2660d6efc0d6e/dist/server/build/index.js:54:31
>     at Compiler.<anonymous> (/home/nowuser/src/node_modules/0a79c0ca287eb47d24f1da61b5f91b43ad6b29d8/lib/Compiler.js:194:14)
>     at Compiler.emitRecords (/home/nowuser/src/node_modules/0a79c0ca287eb47d24f1da61b5f91b43ad6b29d8/lib/Compiler.js:282:37)
>     at Compiler.<anonymous> (/home/nowuser/src/node_modules/0a79c0ca287eb47d24f1da61b5f91b43ad6b29d8/lib/Compiler.js:187:11)
>     at /home/nowuser/src/node_modules/0a79c0ca287eb47d24f1da61b5f91b43ad6b29d8/lib/Compiler.js:275:11
>     at Compiler.applyPluginsAsync (/home/nowuser/src/node_modules/83d7d57e3d1ba8fe04c1aff2eddd6e9eb2c9743c/lib/Tapable.js:60:69)
>     at Compiler.afterEmit (/home/nowuser/src/node_modules/0a79c0ca287eb47d24f1da61b5f91b43ad6b29d8/lib/Compiler.js:272:8)
>     at Compiler.<anonymous> (/home/nowuser/src/node_modules/0a79c0ca287eb47d24f1da61b5f91b43ad6b29d8/lib/Compiler.js:267:14)
>     at /home/nowuser/src/node_modules/2d6754e3763495a3e047fe6496ce31deeef478dd/lib/async.js:52:16
>     at done (/home/nowuser/src/node_modules/2d6754e3763495a3e047fe6496ce31deeef478dd/lib/async.js:246:17)
>   errors: [ './components/header.js\nModule not found: Error: Cannot resolve \'file\' or \'directory\' ./Logo in /home/nowuser/src/components\nresolve file\n  /home/nowuser/src/components/Logo doesn\'t exist\n  /home/nowuser/src/components/Logo.webpack.js doesn\'t exist\n  /home/nowuser/src/components/Logo.web.js doesn\'t exist\n  /home/nowuser/src/components/Logo.js doesn\'t exist\n  /home/nowuser/src/components/Logo.json doesn\'t exist\nresolve directory\n  /home/nowuser/src/components/Logo doesn\'t exist (directory default file)\n  /home/nowuser/src/components/Logo/package.json doesn\'t exist (directory description file)\n[/home/nowuser/src/components/Logo]\n[/home/nowuser/src/components/Logo.webpack.js]\n[/home/nowuser/src/components/Logo.web.js]\n[/home/nowuser/src/components/Logo.js]\n[/home/nowuser/src/components/Logo.json]\n @ ./components/header.js 15:12-29' ],
>   warnings: [] }
> Error Error: Command next build ended with code 1
>     at ChildProcess.<anonymous> (/usr/lib/node_modules/@zeit/ace/build/lib/run.js:1:599)
>     at emitTwo (events.js:106:13)
>     at ChildProcess.emit (events.js:191:7)
>     at maybeClose (internal/child_process.js:877:16)
>     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
> (node:137) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Command next build ended with code 1
> ▲ npm start
> > Ready on http://localhost:80
> Deployment complete!
```

The app somehow is deployed https://utopiaframeworkorg-ounymypstg.now.sh/ but links that are using components which were errored are not working, e.g. https://utopiaframeworkorg-ounymypstg.now.sh/guides

**Comment by voronianski** [comment]
Ok, I've found an issue. The problem was in typo - https://github.com/luvitrocks/utopiaframework.org/commit/847bee7a85ea2a8eaae2ec795b66af047964f028
