### ISSUE TITLE
Compile error in Fast Refresh js when using getServerSideProps

### ISSUE THREAD

**Issue by cfraz89** [zeit/next.js#13312]
# Bug report
On Next 9.4, I have a page which hits a compile error within `react-refresh/cjs/react-refresh-babel.development.js` for a page using getServerSideProps. If getServerSideProps is removed, it compiles fine.

## Describe the bug
This is the error log:
```
event - build page: /rateable/[key]
wait  - compiling...
error - ./pages/rateable/[key].tsx
TypeError: /home/chris/Projects/otterate-ui-web/pages/rateable/[key].tsx: Cannot read property 'type' of null
Could not find files for /rateable/[key] in .next/build-manifest.json
ModuleBuildError: Module build failed (from ./node_modules/next/dist/build/webpack/loaders/next-babel-loader.js):
TypeError: /home/chris/Projects/otterate-ui-web/pages/rateable/[key].tsx: Cannot read property 'type' of null
    at findInnerComponents (/home/chris/Projects/otterate-ui-web/node_modules/react-refresh/cjs/react-refresh-babel.development.js:210:26)
    at PluginPass.VariableDeclaration (/home/chris/Projects/otterate-ui-web/node_modules/react-refresh/cjs/react-refresh-babel.development.js:694:9)
    at newFn (/home/chris/Projects/otterate-ui-web/node_modules/@babel/traverse/lib/visitors.js:179:21)
    at NodePath._call (/home/chris/Projects/otterate-ui-web/node_modules/@babel/traverse/lib/path/context.js:55:20)
    at NodePath.call (/home/chris/Projects/otterate-ui-web/node_modules/@babel/traverse/lib/path/context.js:42:17)
    at NodePath.visit (/home/chris/Projects/otterate-ui-web/node_modules/@babel/traverse/lib/path/context.js:90:31)
    at TraversalContext.visitQueue (/home/chris/Projects/otterate-ui-web/node_modules/@babel/traverse/lib/context.js:112:16)
    at TraversalContext.visitSingle (/home/chris/Projects/otterate-ui-web/node_modules/@babel/traverse/lib/context.js:84:19)
    at TraversalContext.visit (/home/chris/Projects/otterate-ui-web/node_modules/@babel/traverse/lib/context.js:140:19)
    at Function.traverse.node (/home/chris/Projects/otterate-ui-web/node_modules/@babel/traverse/lib/index.js:84:17)
    at NodePath.visit (/home/chris/Projects/otterate-ui-web/node_modules/@babel/traverse/lib/path/context.js:97:18)
    at TraversalContext.visitQueue (/home/chris/Projects/otterate-ui-web/node_modules/@babel/traverse/lib/context.js:112:16)
    at TraversalContext.visitMultiple (/home/chris/Projects/otterate-ui-web/node_modules/@babel/traverse/lib/context.js:79:17)
    at TraversalContext.visit (/home/chris/Projects/otterate-ui-web/node_modules/@babel/traverse/lib/context.js:138:19)
    at Function.traverse.node (/home/chris/Projects/otterate-ui-web/node_modules/@babel/traverse/lib/index.js:84:17)
    at NodePath.visit (/home/chris/Projects/otterate-ui-web/node_modules/@babel/traverse/lib/path/context.js:97:18)
    at /home/chris/Projects/otterate-ui-web/node_modules/webpack/lib/NormalModule.js:316:20
    at /home/chris/Projects/otterate-ui-web/node_modules/loader-runner/lib/LoaderRunner.js:367:11
    at /home/chris/Projects/otterate-ui-web/node_modules/loader-runner/lib/LoaderRunner.js:233:18
    at context.callback (/home/chris/Projects/otterate-ui-web/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at /home/chris/Projects/otterate-ui-web/node_modules/next/dist/compiled/babel-loader/index.js:1:3616
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
ModuleBuildError: Module build failed (from ./node_modules/next/dist/build/webpack/loaders/next-babel-loader.js):
TypeError: /home/chris/Projects/otterate-ui-web/pages/rateable/[key].tsx: Cannot read property 'type' of null
    at findInnerComponents (/home/chris/Projects/otterate-ui-web/node_modules/react-refresh/cjs/react-refresh-babel.development.js:210:26)
    at PluginPass.VariableDeclaration (/home/chris/Projects/otterate-ui-web/node_modules/react-refresh/cjs/react-refresh-babel.development.js:694:9)
    at newFn (/home/chris/Projects/otterate-ui-web/node_modules/@babel/traverse/lib/visitors.js:179:21)
    at NodePath._call (/home/chris/Projects/otterate-ui-web/node_modules/@babel/traverse/lib/path/context.js:55:20)
    at NodePath.call (/home/chris/Projects/otterate-ui-web/node_modules/@babel/traverse/lib/path/context.js:42:17)
    at NodePath.visit (/home/chris/Projects/otterate-ui-web/node_modules/@babel/traverse/lib/path/context.js:90:31)
    at TraversalContext.visitQueue (/home/chris/Projects/otterate-ui-web/node_modules/@babel/traverse/lib/context.js:112:16)
    at TraversalContext.visitSingle (/home/chris/Projects/otterate-ui-web/node_modules/@babel/traverse/lib/context.js:84:19)
    at TraversalContext.visit (/home/chris/Projects/otterate-ui-web/node_modules/@babel/traverse/lib/context.js:140:19)
    at Function.traverse.node (/home/chris/Projects/otterate-ui-web/node_modules/@babel/traverse/lib/index.js:84:17)
    at NodePath.visit (/home/chris/Projects/otterate-ui-web/node_modules/@babel/traverse/lib/path/context.js:97:18)
    at TraversalContext.visitQueue (/home/chris/Projects/otterate-ui-web/node_modules/@babel/traverse/lib/context.js:112:16)
    at TraversalContext.visitMultiple (/home/chris/Projects/otterate-ui-web/node_modules/@babel/traverse/lib/context.js:79:17)
    at TraversalContext.visit (/home/chris/Projects/otterate-ui-web/node_modules/@babel/traverse/lib/context.js:138:19)
    at Function.traverse.node (/home/chris/Projects/otterate-ui-web/node_modules/@babel/traverse/lib/index.js:84:17)
    at NodePath.visit (/home/chris/Projects/otterate-ui-web/node_modules/@babel/traverse/lib/path/context.js:97:18)
    at /home/chris/Projects/otterate-ui-web/node_modules/webpack/lib/NormalModule.js:316:20
    at /home/chris/Projects/otterate-ui-web/node_modules/loader-runner/lib/LoaderRunner.js:367:11
    at /home/chris/Projects/otterate-ui-web/node_modules/loader-runner/lib/LoaderRunner.js:233:18
    at context.callback (/home/chris/Projects/otterate-ui-web/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at /home/chris/Projects/otterate-ui-web/node_modules/next/dist/compiled/babel-loader/index.js:1:3616
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

Doing a little inspection - `ref.node` is `null`

## To Reproduce

For me, attempt to visit any page in the project. The compile error will be thrown.

## Expected behavior

Page compiles successfully

## System information

- OS: Arch Linux
- Version of Next.js: 9.4.2
- Version of Node.js: 14.3.0

**Comment by Timer** [comment]
Please upgrade to `next@canary`.

**Comment by balazsorban44** [comment]
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
