### ISSUE TITLE
yarn build -(ExperimentalWarning: The fs.promises API is experimental)

### ISSUE THREAD

**Issue by sai1139** [zeit/next.js#13337]
# Bug report
1)yarn build error-> (node:14380) ExperimentalWarning: The fs.promises API is experimental
2) At production error
{ Error: Cannot find module 'dotenv'
at Function.Module._resolveFilename (internal/modules/cjs/loader.js:580:15)
    at Module.Hook._require.Module.require (/usr/lib/node_modules/pm2/node_modules/require-in-the-middle/index.js:51:29)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/home/covalense/selfcare/server.js:1:63)
     at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
     at Module.load (internal/modules/cjs/loader.js:598:32)
     at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
   at Function.Module._load (internal/modules/cjs/loader.js:529:3)
     at Object.<anonymous> (/usr/lib/node_modules/pm2/lib/ProcessContainerFork.js:27:21) code: 'MODULE_NOT_FOUND' }
 (node:14380) ExperimentalWarning: The fs.promises API is experimental

node:10.4.1
next:9.4.2

**Comment by sai1139** [comment]
@timneutkens  can you explain what is the issue?

**Comment by timneutkens** [comment]
The issue template was completely ignored (again) so I've closed the issue as it's not actionable.

**Comment by sai1139** [comment]
what is solution?

**Comment by timneutkens** [comment]
I'm not sure what you're running / how you're seeing it. It looks unrelated to Next.js but it's impossible to say as the issue template was ignored (as said).

**Comment by cmsbased** [comment]
I resolved the "The fs.promises API is experimental" error message by updating Node.js to latest LTS build (12.17.0) on Windows computer.

**Comment by balazsorban44** [comment]
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
