### ISSUE TITLE
Error using babel plugins for CSS (ie. babel-plugin-styled-components)

### ISSUE THREAD

**Issue by acanimal** [zeit/next.js#1373]
Hi,
I'm trying to use styled-components to manage my CSS. I need SSR take into account CSS too and because of this I have created a `.babelrc` file with:

```
{
  "plugins": [
    "styled-components"
  ]
}
```

My page `index.js` is as simple as:

```
const App = ({ children, title = '' }) => (
  <div>
    <Head>
      <title>{ title }</title>
      <meta charSet='utf-8' />
      <meta name='viewport' content='initial-scale=1.0, width=device-width' />
      <link href='https://fonts.googleapis.com/css?family=Roboto:300,400,500' rel='stylesheet' />
    </Head>
    <header>
      <nav>
        <Link href='/'><a>Home</a></Link> |
        <Link href='/about'><a>About</a></Link> |
        <Link href='/contact'><a>Contact</a></Link>
      </nav>
    </header>

    <Zone>
      { children }
    </Zone>

    <footer>
      Footer
    </footer>
  </div>
)

export default () => (
  <App>
    Nothing to show
  </App>
)
```

But I'm getting next error when the page is compiled

```
 ERROR  Failed to compile with 1 errors                                                                                                                                          6:55:53 PM

 error  in ./pages?entry

Syntax Error: Unexpected token (11:2)

   9 |
  10 | const App = ({ children, title = '' }) => (
> 11 |   <div>
     |   ^
  12 |     <Head>
  13 |       <title>{ title }</title>
  14 |       <meta charSet='utf-8' />
```

In addition, as an alternative, I have tried to use css-modules with `babel-plugin-react-css-modules` but same error in the same place is thrown.

**Comment by sorin-davidoi** [comment]
You need to add

```json
"presets": [
    "next/babel"
  ]
```

to `.babelrc` (see [this](https://github.com/zeit/next.js/blob/master/examples/with-custom-babel-config/.babelrc)).

**Comment by arunoda** [comment]
Thanks @sorin-davidoi .

**Comment by acanimal** [comment]
@sorin-davidoi @arunoda Done, but now I get next error:

```
TypeError: _styledComponents2.default.div.withConfig is not a function
TypeError: _styledComponents2.default.div.withConfig is not a function
    at Object.<anonymous> (/Users/antonio/Projects/nextjs-test/.next/dist/pages/index.js:25:43)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at _callee$ (/Users/antonio/Projects/nextjs-test/node_modules/next/dist/server/require.js:33:46)
    at tryCatch (/Users/antonio/Projects/nextjs-test/node_modules/regenerator-runtime/runtime.js:64:40)
```

Any ideas?
Thanks in advance

**Comment by sedubois** [comment]
@acanimal it's easier to debug if you share a repo to reproduce

**Comment by acanimal** [comment]
Sorry, here is a repo `https://github.com/acanimal/nextjs-test`. Thanks

**Comment by coliverav89** [comment]
I have the same error too

_styledcomponents2.default.div.withconfig

**Comment by cjthedizzy** [comment]
Im having the same error as well

`_styledComponents2.default.div.withConfig is not a function`

**Comment by cjthedizzy** [comment]
If youre seeing:
Uncaught TypeError: _styledComponents2.default.div.withConfig is not a function

Make sure your using v2 of styled-components. Refer to this github issue:
https://github.com/styled-components/babel-plugin-styled-components/issues/43#issuecomment-293350554
