### ISSUE TITLE
simplest example on readme is breaking

### ISSUE THREAD

**Issue by pulkitnandan** [zeit/next.js#1425]
I have tried the steps as mentioned on readme which is indeed the one the stable release but it just doesn't works out of the box and gave the following errors

` ERROR  Failed to compile with 3 errors

 error  in ./~/next/dist/pages/_error.js

Module build failed: Error: Couldn't find preset "es2015" relative to directory "/home/rohitn"
    at /home/rohitn/c/node_modules/babel-core/lib/transformation/file/options/option-manager.js:299:19
    at Array.map (native)
    at OptionManager.resolvePresets (/home/rohitn/c/node_modules/babel-core/lib/transformation/file/options/option-manager.js:270:20)
    at OptionManager.mergePresets (/home/rohitn/c/node_modules/babel-core/lib/transformation/file/options/option-manager.js:259:10)
    at OptionManager.mergeOptions (/home/rohitn/c/node_modules/babel-core/lib/transformation/file/options/option-manager.js:244:14)
    at OptionManager.init (/home/rohitn/c/node_modules/babel-core/lib/transformation/file/options/option-manager.js:374:12)
    at File.initOptions (/home/rohitn/c/node_modules/babel-core/lib/transformation/file/index.js:216:65)
    at new File (/home/rohitn/c/node_modules/babel-core/lib/transformation/file/index.js:139:24)
    at Pipeline.transform (/home/rohitn/c/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at transpile (/home/rohitn/c/node_modules/babel-loader/lib/index.js:41:20)

 @ multi bundles/pages/_error.js

 error  in ./pages/index.js

Module build failed: Error: Couldn't find preset "es2015" relative to directory "/home/rohitn"
    at /home/rohitn/c/node_modules/babel-core/lib/transformation/file/options/option-manager.js:299:19
    at Array.map (native)
    at OptionManager.resolvePresets (/home/rohitn/c/node_modules/babel-core/lib/transformation/file/options/option-manager.js:270:20)
    at OptionManager.mergePresets (/home/rohitn/c/node_modules/babel-core/lib/transformation/file/options/option-manager.js:259:10)
    at OptionManager.mergeOptions (/home/rohitn/c/node_modules/babel-core/lib/transformation/file/options/option-manager.js:244:14)
    at OptionManager.init (/home/rohitn/c/node_modules/babel-core/lib/transformation/file/options/option-manager.js:374:12)
    at File.initOptions (/home/rohitn/c/node_modules/babel-core/lib/transformation/file/index.js:216:65)
    at new File (/home/rohitn/c/node_modules/babel-core/lib/transformation/file/index.js:139:24)
    at Pipeline.transform (/home/rohitn/c/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at transpile (/home/rohitn/c/node_modules/babel-loader/lib/index.js:41:20)

 @ multi bundles/pages/index.js

 error  in ./~/next/dist/pages/_error-debug.js

Module build failed: Error: Couldn't find preset "es2015" relative to directory "/home/rohitn"
    at /home/rohitn/c/node_modules/babel-core/lib/transformation/file/options/option-manager.js:299:19
    at Array.map (native)
    at OptionManager.resolvePresets (/home/rohitn/c/node_modules/babel-core/lib/transformation/file/options/option-manager.js:270:20)
    at OptionManager.mergePresets (/home/rohitn/c/node_modules/babel-core/lib/transformation/file/options/option-manager.js:259:10)
    at OptionManager.mergeOptions (/home/rohitn/c/node_modules/babel-core/lib/transformation/file/options/option-manager.js:244:14)
    at OptionManager.init (/home/rohitn/c/node_modules/babel-core/lib/transformation/file/options/option-manager.js:374:12)
    at File.initOptions (/home/rohitn/c/node_modules/babel-core/lib/transformation/file/index.js:216:65)
    at new File (/home/rohitn/c/node_modules/babel-core/lib/transformation/file/index.js:139:24)
    at Pipeline.transform (/home/rohitn/c/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at transpile (/home/rohitn/c/node_modules/babel-loader/lib/index.js:41:20)

> Ready on http://localhost:3000
`

**Comment by pulkitnandan** [comment]
I'm using version 6.9.4 of node and npm's is 3.10.10.

FIXED using https://github.com/zeit/next.js/issues/178

i.e. add this in package.json 
"babel": {
    "presets": [
      "es2015",
      "react"
    ]
  }
 
and install babel-preset-es2015 & babel-preset-react
