### ISSUE TITLE
Error during page navigation

### ISSUE THREAD

**Issue by nealalpert** [zeit/next.js#1429]
Our error log is registering the following error seemingly randomly during page navigation:

> Error: Invalid Build File Hash(18adc7a43c926cbfd1fb) for chunk: commons.js
    at Server.handleBuildHash (/var/app/current/node_modules/next/dist/server/index.js:930:15)
    at Server._callee5$ (/var/app/current/node_modules/next/dist/server/index.js:275:28)
    at tryCatch (/var/app/current/node_modules/regenerator-runtime/runtime.js:64:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/var/app/current/node_modules/regenerator-runtime/runtime.js:299:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/var/app/current/node_modules/regenerator-runtime/runtime.js:116:21)
    at step (/var/app/current/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at /var/app/current/node_modules/babel-runtime/helpers/asyncToGenerator.js:35:14
    at Promise.F (/var/app/current/node_modules/core-js/library/modules/_export.js:35:28)
    at Object.<anonymous> (/var/app/current/node_modules/babel-runtime/helpers/asyncToGenerator.js:14:12)
    at Object._nextHashCommonsJs [as fn] (/var/app/current/node_modules/next/dist/server/index.js:289:26)

Seems to be originating from the following code:
https://github.com/zeit/next.js/search?utf8=%E2%9C%93&q=Invalid+Build+File+Hash

**Comment by khrome83** [comment]
This was produced with version `"next": "^2.0.0-beta.32",`

Do we know what the server.js code is doing that it is generating this error?

We can not reproduce this locally.

**Comment by arunoda** [comment]
@nealalpert this is happening because there are two version of your Next.js is deployed and routed via the same domian name.

If you are doing so, make sure to use sticky sessions.

**Comment by khrome83** [comment]
@arunoda thank you that makes perfect sense!

**Comment by arunoda** [comment]
For the future reference, I've updated the wiki with more info: https://github.com/zeit/next.js/wiki/Deployment

**Comment by alanshutko** [comment]
So, by design, the application will **break** if it is updated while users are online?

**Comment by arunoda** [comment]
@alanshutko no it's not.
See: https://github.com/zeit/next.js/wiki/Deployment#why
