### ISSUE TITLE
Weird behavior with custom routes

### ISSUE THREAD

**Issue by kirill-konshin** [zeit/next.js#1438]
In order to support previous URL schema I have a custom server with following routes handler:

```js
const pathMatch = require('path-match');
const route = pathMatch();
const routes = {
    '/page': route('/pages/:slug.html'),
    '/post': route('/news/:slug.html'),
    '/tracks': route('/music.html')
};
app.prepare().then(() => {
    createServer((req, res) => {
        const parsedUrl = parse(req.url, true);
        const {pathname} = parsedUrl;
        const handled = Object.keys(routes).some((page) => {
            const match = routes[page];
            const params = match(pathname);
            if (params) {
                app.render(req, res, page, Object.assign({}, query, params));
                return true;
            }
            return false;
        });
        if (!handled) handle(req, res, parsedUrl);
    }).listen(3000, (err) => {
        if (err) throw err;
        console.log('> Ready on http://localhost:3000');
    });
});
```

When I visit page like `/pages/contacts.html` everything is just fine while it's server-rendered, but when I click any link on a page like `<Link href="/page?slug=about" as="/pages/about.html" activeClassName="active"><a>About</a></Link>` I get a weird error:

```
Error: Failed to execute 'open' on 'XMLHttpRequest': Invalid URL
    at eval (eval at evalScript (http://localhost:3000/_next/-/main.js:4853:3), <anonymous>:33027:17)
    at self.fetch (eval at evalScript (http://localhost:3000/_next/-/main.js:4853:3), <anonymous>:33004:18)
    at Object._callee3$ (eval at evalScript (http://localhost:3000/_next/-/main.js:4853:3), <anonymous>:32441:32)
    at tryCatch (eval at evalScript (http://localhost:3000/_next/-/main.js:4853:3), <anonymous>:33013:40)
    at Generator.invoke [as _invoke] (eval at evalScript (http://localhost:3000/_next/-/main.js:4853:3), <anonymous>:33248:22)
    at Generator.prototype.(anonymous function) [as next] (eval at evalScript (http://localhost:3000/_next/-/main.js:4853:3), <anonymous>:33065:21)
    at step (eval at evalScript (http://localhost:3000/_next/-/main.js:4853:3), <anonymous>:32522:40)
    at eval (eval at evalScript (http://localhost:3000/_next/-/main.js:4853:3), <anonymous>:32534:21)
    at Object.eval (eval at evalScript (http://localhost:3000/_next/-/main.js:4853:3), <anonymous>:32519:52)
    at Object.fetch (eval at evalScript (http://localhost:3000/_next/-/main.js:4853:3), <anonymous>:32486:22)
```

The text is injected right into the page, no styles. Server console is pristine.

**Comment by arunoda** [comment]
Could you wrap this into a sample repo?
So, we can have a look quick look at this.

**Comment by kirill-konshin** [comment]
I figured that is actually some weird error in client which was making an XHR request to malformed URL. I am closing the ticket.

As a side request, could you improve error reporting? Now it's misleading and does not show what code is eval'ed...

**Comment by arunoda** [comment]
Yeah! We are going to get rid of eval in the first place. See: https://github.com/zeit/next.js/issues/1301

**Comment by kirill-konshin** [comment]
Awesome! Looking forward to use it.
