### ISSUE TITLE
Question: How write ES6 code in server.js?

### ISSUE THREAD

**Issue by tashburn** [zeit/next.js#1472]
I know of a few methods for this (`babel-register`, `babel-cli`), but what's your recommended solution that's most compatible with Next in both dev and prod?

**Comment by sergiodxa** [comment]
Node v6 and v7 let use write ES2015, except for `import` and `export`. I think the recommendation is to use `require` and `module.exports` for that and use ES2015 without Babel.

**Comment by tashburn** [comment]
K thank you.

**Comment by nndung179** [comment]
I made it work as follow:

instead of using server.js directly you could require it in index.js file. Then update script at **package.json**

index.js
```js
require("babel-register")();
require("./server.js");
```

package.json
```js
"start": "npm run sass && nodemon -w index.js index.js",
```

**Comment by vjpr** [comment]
I am getting this error when I try that.

```
/Users/Vaughan/dev-live/vwp/index.js:1
(function (exports, require, module, __filename, __dirname) { import _regeneratorRuntime from 'next/node_modules/babel-runtime/regenerator';
                                                              ^^^^^^

SyntaxError: Unexpected token import
    at createScript (vm.js:74:10)
    at Object.runInThisContext (vm.js:116:10)
    at Module._compile (module.js:533:28)
    at loader (/Users/Vaughan/dev-live/vwp/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/Vaughan/dev-live/vwp/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
```
