### ISSUE TITLE
example with-external-scoped-css is broken

### ISSUE THREAD

**Issue by pulkitnandan** [zeit/next.js#1517]
Hi,

The very recent pull of next example with-external-scoped-css is failing with following error.

```
rohitn@rohitn ~/next.js/examples/with-external-scoped-css $ npm run start

> with-external-scoped-css@1.0.0 start /home/rohitn/next.js/examples/with-external-scoped-css
> next

> Using external babel configuration
> location: "/home/rohitn/next.js/examples/with-external-scoped-css/.babelrc"
(node:23080) DeprecationWarning: loaderUtils.parseQuery() received a non-string value which can be problematic, see https://github.com/webpack/loader-utils/issues/56
parseQuery() will be replaced with getOptions() in the next major version of loader-utils.


 ERROR  Failed to compile with 1 errors                                                                                                                      3:44:17 PM

 error  in ./pages/_document.js?entry

Module build failed: Error: Cannot find module './pre-processor.js'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at requireLocalFileOrNodeModule (/home/rohitn/next.js/examples/with-external-scoped-css/node_modules/babel-plugin-css-modules-transform/build/utils/requireLocalFileOrNodeModule.js:24:16)
    at Object.preprocessCss (/home/rohitn/next.js/examples/with-external-scoped-css/node_modules/babel-plugin-css-modules-transform/build/options_resolvers/preprocessCss.js:19:70)
    at /home/rohitn/next.js/examples/with-external-scoped-css/node_modules/babel-plugin-css-modules-transform/build/index.js:143:62
    at Array.forEach (native)
    at Plugin.manipulateOptions (/home/rohitn/next.js/examples/with-external-scoped-css/node_modules/babel-plugin-css-modules-transform/build/index.js:136:46)
    at File.buildPluginsForOptions (/home/rohitn/next.js/examples/with-external-scoped-css/node_modules/babel-core/lib/transformation/file/index.js:280:16)

 @ multi ./pages/_document.js?entry

> Ready on http://localhost:3000
```

**Comment by pulkitnandan** [comment]
While it seems to be fixed after I created a new npm package containing the functionality or pre-processor.js but now it fails with following error.

```
 ERROR  Failed to compile with 1 errors                                                                                                                      4:48:57 PM

 error  in ./pages/_document.js?entry

Module build failed: Error: ENOENT: no such file or directory, scandir '/home/rohitn/tul-mp-desktop/node_modules/node-sass/vendor'
    at Error (native)
    at Object.fs.readdirSync (fs.js:951:18)
    at Object.getInstalledBinaries (/home/rohitn/tul-mp-desktop/node_modules/node-sass/lib/extensions.js:123:13)
    at foundBinariesList (/home/rohitn/tul-mp-desktop/node_modules/node-sass/lib/errors.js:20:15)
    at foundBinaries (/home/rohitn/tul-mp-desktop/node_modules/node-sass/lib/errors.js:15:5)
    at Object.module.exports.missingBinary (/home/rohitn/tul-mp-desktop/node_modules/node-sass/lib/errors.js:45:5)
    at module.exports (/home/rohitn/tul-mp-desktop/node_modules/node-sass/lib/binding.js:15:30)
    at Object.<anonymous> (/home/rohitn/tul-mp-desktop/node_modules/node-sass/lib/index.js:14:35)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)

 @ multi ./pages/_document.js?entry

> Ready on http://localhost:3000

```

**Comment by aranajhonny** [comment]
I just run this example and it works fine.

![screenshot_2](https://cloud.githubusercontent.com/assets/9091881/24361883/05172814-12c0-11e7-844c-e5e4c6002fdf.png)

**Comment by pulkitnandan** [comment]
its this for linux @ current master.

```
cation: "/home/rohitn/next.js/examples/with-external-scoped-css/.babelrc"
(node:7758) DeprecationWarning: loaderUtils.parseQuery() received a non-string value which can be problematic, see https://github.com/webpack/loader-utils/issues/56
parseQuery() will be replaced with getOptions() in the next major version of loader-utils.


 ERROR  Failed to compile with 1 errors                                                                                                                      9:44:26 PM

 error  in ./pages/_document.js?entry

Module build failed: Error: Cannot find module './pre-processor.js'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at requireLocalFileOrNodeModule (/home/rohitn/next.js/examples/with-external-scoped-css/node_modules/babel-plugin-css-modules-transform/build/utils/requireLocalFileOrNodeModule.js:24:16)
    at Object.preprocessCss (/home/rohitn/next.js/examples/with-external-scoped-css/node_modules/babel-plugin-css-modules-transform/build/options_resolvers/preprocessCss.js:19:70)
    at /home/rohitn/next.js/examples/with-external-scoped-css/node_modules/babel-plugin-css-modules-transform/build/index.js:143:62
    at Array.forEach (native)
    at Plugin.manipulateOptions (/home/rohitn/next.js/examples/with-external-scoped-css/node_modules/babel-plugin-css-modules-transform/build/index.js:136:46)
    at File.buildPluginsForOptions (/home/rohitn/next.js/examples/with-external-scoped-css/node_modules/babel-core/lib/transformation/file/index.js:280:16)

 @ multi ./pages/_document.js?entry

> Ready on http://localhost:3000

```

**Comment by pulkitnandan** [comment]
Even after writing the whole preprocessCss function in babel-plugin-css-modules-transform, it's not working.

**Comment by lsentkiewicz** [comment]
Hot-reloading is not working for sass code. Is this expected?

**Comment by pulkitnandan** [comment]
Not expected in my use case.

It do have started working now with no change to sources anywhere, seems node-sass was giving issues when they had their version updated to 4.5.2.
