### ISSUE TITLE
next/babel preset breaks babel-register

### ISSUE THREAD

**Issue by obibring** [zeit/next.js#1573]
I'm using a custom `.babelrc` file, with the `next/babel` preset as described in the docs. In my `server.js` file (a custom express server similar to that in the custom-server example), I use `babel-register` to enable runtime transpilation of ES2015+ code that resides in my `node-modules` directory. Attempting to run my server with the `next/babel` preset produces the error:

```
Cannot read property 'find' of undefined
    at getRealPathFromRegExpConfig (<my-repo>/node_modules/babel-plugin-module-resolver/lib/getRealPath.js:94:10)
    at getRealPath (<my-repo>/node_modules/babel-plugin-module-resolver/lib/getRealPath.js:139:30)
    at mapModule (<my-repo>/node_modules/babel-plugin-module-resolver/lib/index.js:52:36)
    at transformRequireCall (<my-repo>/node_modules/babel-plugin-module-resolver/lib/transformers/require.js:20:22)
    at PluginPass.CallExpression (<my-repo>/node_modules/babel-plugin-module-resolver/lib/index.js:111:29)
    at NodePath._call
```

However, when I remove `next/babel`, it works. For reference, here's the `.babelrc` without `next/babel`:

```
{
  "presets": [
    "react",
    "stage-0",
    "env"
  ]
}
```

**Comment by arunoda** [comment]
Currently this is an issue.
In your `babel-register` try to set [bablerc option to false](https://babeljs.io/docs/usage/babel-register/).
Then provide plugin manually.

**Comment by obibring** [comment]
Thanks for the quick reply. I don't see documentation on setting the babelrc option to false. Can you show an example of what you mean?

**Comment by obibring** [comment]
Found it. It works. For future reference:
```javascript
const path = require('path');
const _ = require('lodash');
const babelrc = JSON.parse(fs.readFileSync(path.resolve(__dirname + '/.babelrc'));

require('babel-register')({
  babelrc: false, // Tell babel-register to ignore the .babelrc file
  presets: _.without(babelrc.presets, 'next/babel')
});
```
