### ISSUE TITLE
Custom server, filesystem-defined routes: TypeError: Cannot read property 'replace' of undefined

### ISSUE THREAD

**Issue by arnaudrenaud** [zeit/next.js#1616]
I use the following as `index.js` (a simpler version of the example at https://zeit.co/blog/next2#programmatic-api):
```
const express = require('express')
const next = require('next')

const dev = process.env.NODE_ENV !== 'production'
const app = next({ dev })
const handle = app.getRequestHandler()

app.prepare().then(() => {
  const server = express()

  server.get('/r', (req, res) => {
    return app.render(req, res, '/b', req.query)
  })

  server.get('*', handle)
  server.listen(3000)
})
```

I also a have a dumb component page as `pages/b.js`:
```
export default () => (
  <div>Welcome to b.js!</div>
)
```

After starting the server (`node index.js`), **route `/r` responds correctly (with page `b`) but route `/b` responds with an internal server error**.
(Also note route `/b` responds correctly with page `b` when running the standard Next server `yarn dev`.)

Stack trace:
```
TypeError: Cannot read property 'replace' of undefined
    at toRoute (/Users/arnaudrenaud/nvh4/node_modules/next/dist/lib/router/router.js:821:14)
    at new Router (/Users/arnaudrenaud/nvh4/node_modules/next/dist/lib/router/router.js:128:18)
    at renderPage (/Users/arnaudrenaud/nvh4/node_modules/next/dist/server/render.js:150:25)
    at Function.getInitialProps (/Users/arnaudrenaud/nvh4/node_modules/next/dist/server/document.js:79:25)
    at _callee$ (/Users/arnaudrenaud/nvh4/node_modules/next/dist/lib/utils.js:36:30)
    at tryCatch (/Users/arnaudrenaud/nvh4/node_modules/regenerator-runtime/runtime.js:64:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Users/arnaudrenaud/nvh4/node_modules/regenerator-runtime/runtime.js:299:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Users/arnaudrenaud/nvh4/node_modules/regenerator-runtime/runtime.js:116:21)
    at step (/Users/arnaudrenaud/nvh4/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at /Users/arnaudrenaud/nvh4/node_modules/babel-runtime/helpers/asyncToGenerator.js:35:14
```

`package.json`:
```
{
  ...
  "dependencies": {
    "express": "^4.15.2",
    "next": "^2.0.1",
    "react": "^15.4.2",
    "react-dom": "^15.4.2"
  },
  "scripts": {
    "dev": "next",
    "build": "next build",
    "start": "next start"
  }
}
```
I use node v6.9.2.

**Comment by aranajhonny** [comment]
try https://github.com/zeit/next.js/blob/master/examples/custom-server-express/server.js#L20

**Comment by arunoda** [comment]
If this doesn't fix your issue, you may need to provide a sample repo for us.

**Comment by arnaudrenaud** [comment]
The solution provided by @aranajhonny solved the issue.

**Comment by arunoda** [comment]
Okay. Gonne close this then.
