### ISSUE TITLE
Does not work with babel-plugin-add-module-exports

### ISSUE THREAD

**Issue by mizchi** [zeit/next.js#1685]
next with this plugin is broken on client side. SSR is passed without error.

https://github.com/59naga/babel-plugin-add-module-exports

```
Cannot read property 'Component' of undefined
TypeError: Cannot read property 'Component' of undefined
    at _callee3$ (http://localhost:4000/_next/-/commons.js:22000:50)
    at tryCatch (http://localhost:4000/_next/-/commons.js:37879:40)
    at Generator.invoke [as _invoke] (http://localhost:4000/_next/-/commons.js:38114:22)
    at Generator.prototype.(anonymous function) [as next] (http://localhost:4000/_next/-/commons.js:37931:21)
    at step (http://localhost:4000/_next/-/commons.js:4125:30)
    at http://localhost:4000/_next/-/commons.js:4143:14
    at Promise (<anonymous>)
    at F (http://localhost:4000/_next/-/commons.js:964:28)
    at http://localhost:4000/_next/-/commons.js:4122:12
    at doRender (http://localhost:4000/_next/-/commons.js:22025:18)
```

It may occur by implicit React reference.

I do not think next have to resolve this issue, but I see some project uses this plugin. I just reported.
Close this if you do not need.

**Comment by arunoda** [comment]
I think this plugin might scramble the normal export system in someway. I think this is not a direct Next.js issue.
