### ISSUE TITLE
Error: Next in dev yields "cannot read property call of undefined", in production throws an error

### ISSUE THREAD

**Issue by ithinco** [zeit/next.js#1717]
macOS 10.12.4
node v7.7.1
npm  v4.1.2
yarn v0.21.3

I'm using "with-react-md" example, and didn't change anything, just yarn install, npm run dev/start.

The error in dev mode is the same as issue [1510](https://github.com/zeit/next.js/issues/1510)

And in production mode, the error is

```
> next start

Warning: Accessing PropTypes via the main React package is deprecated. Use the prop-types package from npm instead.
module.js:472
    throw err;
    ^
Error: Cannot find module '/Users/ce/Documents/production/alljs/.next/build-stats.json'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at new Server (/Users/ce/Documents/production/alljs/node_modules/next/dist/server/index.js:104:30)
    at Object.<anonymous> (/Users/ce/Documents/production/alljs/node_modules/next/dist/bin/next-start:48:11)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
```

**Comment by ithinco** [comment]
@rauchg @arunoda

**Comment by reezon** [comment]
run "next build" before  "next start"

**Comment by ithinco** [comment]
@reezon Yeah, thank you. npm run build solves the production error, but the dev error still exists.

**Comment by arunoda** [comment]
In dev, just use `next`

**Comment by arunoda** [comment]
Please follow the tutorial: https://learnnextjs.com/basics/getting-started
