### ISSUE TITLE
FS Error whether running Next Dev or Next Prod

### ISSUE THREAD

**Issue by akadop** [zeit/next.js#1725]
Everything was working fine last night, but today I am coming across these errors (both Mac and Windows).

Reinstalled all my node_modules, did not help.

ERROR  Failed to compile with 39 errors                                                                                                             6:32:32 PM

These modules were not found:

* fs in ./~/next/dist/server/index.js, ./~/next/dist/server/config.js and 33 others
* module in (webpack)/lib/NormalModule.js, ./~/babel-core/lib/helpers/resolve.js
* readline in ./~/friendly-errors-webpack-plugin/src/output.js
* net in ./~/debug/src/node.js

To install them, you can run: npm install --save fs module readline net
Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined.
 You likely forgot to export your component from the file it's defined in. Check your code at index.js?entry:16.
{ Error: Cannot find module '~/exampaths-next/.next/build-stats.json'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at new Server (~/exampaths-next/node_modules/next/dist/server/index.js:104:30)
    at module.exports (~/exampaths-next/node_modules/next/dist/server/next.js:10:10)
    at walkTree (~/exampaths-next/node_modules/react-apollo/src/server.ts:76:15)
    at /mnt/c/Users/akaga/Documents/Github/exampaths-next/node_modules/react-apollo/src/server.ts:90:11
    at forEachSingleChild (~/exampaths-next/node_modules/react/lib/ReactChildren.js:51:8)
    at traverseAllChildrenImpl (~/exampaths-next/node_modules/react/lib/traverseAllChildren.js:77:5) code: 'MODULE_NOT_FOUND'
, queryErrors: [ [Circular] ] }

 WAIT  Compiling...                                                                                                                                  6:34:16 PM

 ERROR  Failed to compile with 39 errors                                                                                                             6:34:21 PM

These modules were not found:

* fs in ./~/is-windows-bash/index.js, ./~/mz/fs.js and 33 others
* module in (webpack)/lib/NormalModule.js, ./~/babel-core/lib/helpers/resolve.js
* readline in ./~/friendly-errors-webpack-plugin/src/output.js
* net in ./~/debug/src/node.js

To install them, you can run: npm install --save fs module readline net

**Comment by akadop** [comment]
This is the error appearing on localhost.

Cannot find module '/mnt/c/Users/akaga/Documents/Github/exampaths-next/.next/build-stats.json'
Error: Cannot find module '/mnt/c/Users/akaga/Documents/Github/exampaths-next/.next/build-stats.json'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at new Server (/mnt/c/Users/akaga/Documents/Github/exampaths-next/node_modules/next/dist/server/index.js:104:30)
    at module.exports (/mnt/c/Users/akaga/Documents/Github/exampaths-next/node_modules/next/dist/server/next.js:10:10)
    at walkTree (/mnt/c/Users/akaga/Documents/Github/exampaths-next/node_modules/react-apollo/src/server.ts:76:15)
    at /mnt/c/Users/akaga/Documents/Github/exampaths-next/node_modules/react-apollo/src/server.ts:90:11
    at forEachSingleChild (/mnt/c/Users/akaga/Documents/Github/exampaths-next/node_modules/react/lib/ReactChildren.js:51:8)
    at traverseAllChildrenImpl (/mnt/c/Users/akaga/Documents/Github/exampaths-next/node_modules/react/lib/traverseAllChildren.js:77:5)

**Comment by markthethomas** [comment]
Getting the same thing w/ v.7.9.0 & next @ 2.1.1 even in tiny examples (just pages/index.js and the deps, nothing else); any ideas why this would be happening? Also worth nothing: on OS X

**Comment by timneutkens** [comment]
Can you provide the exact steps to reproduce, and an example repository? It's really hard to debug otherwise 👍

**Comment by markthethomas** [comment]
*facepalm* — was importing a nonexistent preset "next" in my babelrc; hard error to track down, but def. my own doing lol

**Comment by alexnewmannn** [comment]
@akadop Hey, @dizlexik was reporting a similar issue where it happened when he had his server using distDir and was essentially running 2 versions of the app. Can you post an example simple project of this issue occuring?

**Comment by akadop** [comment]
Sorry for the late response. Turns out it was infact running 2 different versions of the app, although I do not know how that happened. There was no error indicating port 3000 was in use. 

In any case, Thanks for all the help.

**Comment by ApprenticeGC** [comment]
Not sure if I should reopen the issue since it may not be related to Next.js. The case is that when using Next.js with [Minio.js](https://github.com/minio/minio-js), the following errors shown:

```
These modules were not found:

* fs in ./node_modules/mkdirp/index.js, ./node_modules/minio/dist/main/minio.js

To install it, you can run: npm install --save fs
```

I have made a very simple [project](https://github.com/ApprenticeGC/report-with-minio-error) to show how to reproduce this error.

If this issue isn't the concern of Next.js but Minio.js, I would be happy to just post the issue there. Thanks.
