### ISSUE TITLE
zeit.co/oss broken on client-side navigation on IE11

### ISSUE THREAD

**Issue by khankuan** [zeit/next.js#1754]
Hi, I've noticed that https://zeit.co/oss received an unexpected error when navigating from client side. On a related note, I would like to know if there are any specs on browser supports for next.js yet.

```
TypeError: Object doesn't support property or method 'includes'
   {
      [functions]: ,
      __proto__: { },
      description: "Object doesn't support property or method 'includes'",
      message: "Object doesn't support property or method 'includes'",
      name: "TypeError",
      number: -2146827850,
      stack: "TypeError: Object doesn't support property or method 'includes'
   at getProjects (eval code:169:7)
   at Anonymous function (eval code:345:11)
   at tryCatch (https://cdnjs.cloudflare.com/ajax/libs/es6-promise/4.0.5/es6-promise.auto.js:414:5)
   at invokeCallback (https://cdnjs.cloudflare.com/ajax/libs/es6-promise/4.0.5/es6-promise.auto.js:429:5)
   at publish (https://cdnjs.cloudflare.com/ajax/libs/es6-promise/4.0.5/es6-promise.auto.js:397:7)
   at flush (https://cdnjs.cloudflare.com/ajax/libs/es6-promise/4.0.5/es6-promise.auto.js:125:5)"
   }

Object doesn't support property or method 'includes'
TypeError: Object doesn't support property or method 'includes'
   at getProjects (eval code:169:7)
   at Anonymous function (eval code:345:11)
   at tryCatch (https://cdnjs.cloudflare.com/ajax/libs/es6-promise/4.0.5/es6-promise.auto.js:414:5)
   at invokeCallback (https://cdnjs.cloudflare.com/ajax/libs/es6-promise/4.0.5/es6-promise.auto.js:429:5)
   at publish (https://cdnjs.cloudflare.com/ajax/libs/es6-promise/4.0.5/es6-promise.auto.js:397:7)
   at flush (https://cdnjs.cloudflare.com/ajax/libs/es6-promise/4.0.5/es6-promise.auto.js:125:5)
```

Cheers!

**Comment by arunoda** [comment]
Thanks @khankuan a lot.
We fixed the issue and we'll deploy it soon.
