### ISSUE TITLE
Unable to find element with ID XX

### ISSUE THREAD

**Issue by FangzfHtml** [zeit/next.js#1789]
#### error logs:
    Invariant Violation: Unable to find element with ID 7.
    at invariant (http://localhost:3000/_next/-/commons.js:49:15)
    at precacheChildNodes (http://localhost:3000/_next/-/commons.js:382:21)
    at Object.getNodeFromInstance (http://localhost:3000/_next/-/commons.js:458:5)
    at ReactDOMTextComponent.getHostNode (http://localhost:3000/_next/-/commons.js:29591:50)
    at Object.getHostNode (http://localhost:3000/_next/-/commons.js:2236:29)
    at ReactDOMComponent._updateChildren (http://localhost:3000/_next/-/commons.js:31316:42)
    at ReactDOMComponent.updateChildren (http://localhost:3000/_next/-/commons.js:31269:12)
    at ReactDOMComponent._updateDOMChildren (http://localhost:3000/_next/-/commons.js:28435:12)
    at ReactDOMComponent.updateComponent (http://localhost:3000/_next/-/commons.js:28253:10)
    at ReactDOMComponent.receiveComponent (http://localhost:3000/_next/-/commons.js:28215:10)

#### my codes:
```
constructor(props){
     super(props)
     this.state = {
            data : {}
     };
     this.topData = this.topData.bind(this);
}
componentDidMount(){
     var dataTop = {'a':'a'};
     this.setState({
          data : dataTop
     });
}
```
> When I execute ` this.setState({
     data : dataTop
      })`, appear the error

**Comment by arunoda** [comment]
Please provide a sample repo where we can easily debug this locally.
Reopen when you have it.
