### ISSUE TITLE
Styled-components shows 'cssRules' of undefined error randomly

### ISSUE THREAD

**Issue by sfarthin** [zeit/next.js#1804]
Steps to reproduce

$> cd ./examples/with-styled-components
$> npm run dev
Then visit http://localhost:3000/page-not-exist . Should show a 404 page.
Stop the process with Ctrl-C. Restart it (e.g. `npm run dev`).
Now visit http://localhost:3000/page-not-exist again and you should see this error in the server process:

```
TypeError: Cannot read property 'cssRules' of undefined
    at StyleSheet.rules (/Users/stevefar/next.js/examples/with-styled-components/node_modules/styled-components/lib/vendor/glamor/sheet.js:196:26)
    at StyleSheet.rules (/Users/stevefar/next.js/examples/with-styled-components/node_modules/styled-components/lib/models/StyleSheet.js:54:36)
    at Function._callee$ (/Users/stevefar/next.js/examples/with-styled-components/.next/dist/pages/_document.js:111:123)
    at tryCatch (/Users/stevefar/next.js/examples/with-styled-components/node_modules/regenerator-runtime/runtime.js:64:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Users/stevefar/next.js/examples/with-styled-components/node_modules/regenerator-runtime/runtime.js:299:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Users/stevefar/next.js/examples/with-styled-components/node_modules/regenerator-runtime/runtime.js:116:21)
    at step (/Users/stevefar/next.js/examples/with-styled-components/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at /Users/stevefar/next.js/examples/with-styled-components/node_modules/babel-runtime/helpers/asyncToGenerator.js:35:14
    at Promise.F (/Users/stevefar/next.js/examples/with-styled-components/node_modules/core-js/library/modules/_export.js:35:28)
    at Function.<anonymous> (/Users/stevefar/next.js/examples/with-styled-components/node_modules/babel-runtime/helpers/asyncToGenerator.js:14:12)
```

I see this pop up inconsistently on a small project I am working on. This includes pages that do exist and that have styled-components. All my pages have at least one styled-component. This is just the simplest example I was able to reproduce with some certainty.

**Comment by esseb** [comment]
See the comment at the bottom of https://github.com/zeit/next.js/tree/master/examples/with-styled-components

Should be fixed in styled-components v2 according to the linked issue, although that is not released yet.

**Comment by timneutkens** [comment]
Thanks!
