### ISSUE TITLE
Error: Cannot find module '../utils/colorManipulator'

### ISSUE THREAD

**Issue by uu-fish** [zeit/next.js#1849]
↓ Such an error occurred.

```
Error: Cannot find module '../utils/colorManipulator'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/takata/GitHub/sample/.next/dist/node_modules/material-ui/styles/getMuiTheme.js:17:25)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
```

I tried to use material-ui(0.18.0), It did not work.

`material-ui` is in `.next/dist/node_modules/` , but `material-ui/utils/colorManipulator.js` is not in `.next/dist/node_modules/`

Is this due to the relative path?

```js:colorManipulator.js
Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.convertColorToString = convertColorToString;
exports.convertHexToRGB = convertHexToRGB;
exports.decomposeColor = decomposeColor;
exports.getContrastRatio = getContrastRatio;
exports.getLuminance = getLuminance;
exports.emphasize = emphasize;
exports.fade = fade;
exports.darken = darken;
exports.lighten = lighten;
```

**Comment by arunoda** [comment]
You should add `material-ui` into your `package.json`.
It should not be in the `.next/dist` in anyway.

If the error still exists, create a sample repo and send us. (And of course re-open this issue)
