### ISSUE TITLE
Create external LESS/Stylus stylesheet

### ISSUE THREAD

**Issue by DavidSvetlik** [zeit/next.js#1863]
Hi, I haven't found it, therefore this issue. Is it possible to create some global (but also external) stylesheet from LESS/Stylus files? And how?

All I found was this example
https://github.com/zeit/next.js/tree/master/examples/with-external-scoped-css

But apparently that is not enough:
1. example is for Sass only, not sure if it can actually work with Less node module
2. css is scoped which I don't need

It would be also nice to have "watch" function (even though I would need to save js file in order for it to work).

---

In classic webpack I would have no trouble to set this up, but you in README you write:

"Adding loaders to support new file types (css, less, svg, etc.) is not recommended because only the client code gets bundled via webpack and thus it won't work on the initial server rendering."

So I would really appreciate some working alternative, thank you. :-)

**Comment by sergiodxa** [comment]
The example work with LESS and Stylus, just change it to use them instead of SASS.

To build don't scoped CSS you need to set your own build process for less/stylus/sass manually.

**Comment by DavidSvetlik** [comment]
@sergiodxa :

I am not sure if less works the same way:

http://lesscss.org/usage/#programmatic-usage (not clear what "less.render" function actually returns)

But I actually tried to set it up and it just generated empty file.


About not scoped - so you mean something like completelly separated webpack/whatever instance? Probably gonna be best choice though.

**Comment by timneutkens** [comment]
@DavidSvetlik please see https://github.com/zeit/next.js/tree/master/examples/with-global-stylesheet, it can be modified to support less / stylus etc

**Comment by flexlee** [comment]
Hi @DavidSvetlik, are you able to get LESS to work? Do you mind posting a `pre-processor.js` example? Thanks.

**Comment by Lonelind** [comment]
Tried this out with stylus. Implemented everything from `with-global-stylesheet` example, but still, my app throws an exception.

```
{ Error: Cannot find module '../assets/styles/base.styl'
    at Function.Module._resolveFilename (module.js:489:15)
    at Function.Module._load (module.js:439:25)
    at Module.require (module.js:517:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/<project_path>/pages/_document.js:5:1)
    at Module._compile (module.js:573:30)
    at Module._compile (/<project_path>/node_modules/source-map-support/source-map-support.js:483:25)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)
    at Module.require (module.js:517:17)
    at require (internal/module.js:11:18)
    at _callee$ (/<project_path>/node_modules/next/dist/server/require.js:33:46)
    at tryCatch (/<project_path>/node_modules/next/node_modules/regenerator-runtime/runtime.js:65:40)
    at Generator.invoke [as _invoke] (/<project_path>/node_modules/next/node_modules/regenerator-runtime/runtime.js:303:22)
    at Generator.prototype.(anonymous function) [as next] (/<project_path>/node_modules/next/node_modules/regenerator-runtime/runtime.js:117:21)
    at step (/<project_path>/node_modules/next/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at /<project_path>/node_modules/next/node_modules/babel-runtime/helpers/asyncToGenerator.js:28:13
    at <anonymous> code: 'MODULE_NOT_FOUND' }
```

I am importing this in `_document.js`, trying to `console.log` the imported module.

```es6
import styles from '../assets/styles/base.styl';
```

The file is on its place, it's not empty and it's valid.

```styl
body
    font-family: Helvetica, sans-serif
```

Plugin config is written to `.babelrc`, `postcss.config.js` was created too. Just like in example. Why doesn't this work?

**Comment by DavidSvetlik** [comment]
@flexlee Sorry for late answer. No, I wasn't able to make it work, I moved to SASS instead.

**Comment by luanwulin** [comment]
most less compiler is async but pre-processor.js  require a sync function. is there any solutions?
