### ISSUE TITLE
Example with micro as custom server

### ISSUE THREAD

**Issue by sbehrends** [zeit/next.js#1922]
I am trying to combine three awesome Zeit projects (next.js + micro + now).
While putting next on top of micro I keep getting errors. Did anyone make it work?

This is my example code

```
const next = require('next')
const { parse } = require('url')
const dispatch = require('micro-route/dispatch')

const dev = process.env.NODE_ENV !== 'production'
const app = next({ dev })
const handle = app.getRequestHandler()

const defaultRoute = async function (req, res) {
  return { say: 'Hello' }
}

module.exports = dispatch()
  .dispatch('/api', '*', defaultRoute )
  .otherwise((req, res) => {
    const parsedUrl = parse(req.url, true)
    handle(req, res, parsedUrl)
  })

```

Error after running `npm start` and requesting http://localhost:3000/

```
TypeError: Cannot read property 'hasErrors' of null
    at HotReloader.getCompilationErrors (/projects/node_modules/next/dist/server/hot-reloader.js:525:23)
    at Server.getCompilationError (/projects/node_modules/next/dist/server/index.js:1012:37)
    at Server._callee16$ (/projects/node_modules/next/dist/server/index.js:742:39)
    at tryCatch (/projects/node_modules/regenerator-runtime/runtime.js:65:40)
    at Generator.invoke [as _invoke] (/projects/node_modules/regenerator-runtime/runtime.js:303:22)
    at Generator.prototype.(anonymous function) [as next] (/projects/node_modules/regenerator-runtime/runtime.js:117:21)
    at step (/projects/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at /projects/node_modules/babel-runtime/helpers/asyncToGenerator.js:35:14
    at F (/projects/node_modules/core-js/library/modules/_export.js:35:28)
    at Server.<anonymous> (/projects/node_modules/babel-runtime/helpers/asyncToGenerator.js:14:12)
    at Server.renderToHTML (/projects/node_modules/next/dist/server/index.js:786:23)
    at Server._callee15$ (/projects/node_modules/next/dist/server/index.js:708:29)
    at tryCatch (/projects/node_modules/regenerator-runtime/runtime.js:65:40)
    at Generator.invoke [as _invoke] (/projects/node_modules/regenerator-runtime/runtime.js:303:22)
    at Generator.prototype.(anonymous function) [as next] (/projects/node_modules/regenerator-runtime/runtime.js:117:21)
    at step (/projects/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
```

**Comment by impronunciable** [comment]
Hi,
I guess your `start` script is not setting `NODE_ENV=production` so `hmr` is breaking. Try adding `NODE_ENV=production` to the start script :)

**Comment by sbehrends** [comment]
I can confirm that production ENV works. Any way to make it work on development as well?

**Comment by arunoda** [comment]
@sbehrends for dev, it should be pretty simple.
Just run:

```js
npm start
````

**Comment by sbehrends** [comment]
But fails with above error :(

**Comment by sergiodxa** [comment]
Are you running `app.prepare()`? I don't see it in your code.

**Comment by arunoda** [comment]
@sergiodxa is correct. You need to run it.
Check the express example for more info.

**Comment by sbehrends** [comment]
Whoops.... I guess that was it!

I will take a look into it and come back

**Comment by sbehrends** [comment]
Can confirm that adding app.prepare made it work.
Just wondering where to put it, since micro needs to export

**Comment by sbehrends** [comment]
Got it!
Thanks all :)

**Comment by fabien88** [comment]
Having same issue, where did you put the app.prepare @sbehrends ?

**Comment by sergiodxa** [comment]
@fabien88 you can (maybe) export a custom async function that run `await app.prepare()` and return `dispatch()`

**Comment by ssured** [comment]
@sergiodxa you can have a look at how I did it in https://github.com/ssured/nownextmicro, see https://github.com/ssured/nownextmicro/blob/a30212d779d82dca5893a250f5f596246bf6bc46/server.js#L21

**Comment by fabien88** [comment]
Nice one, thanks :)
