### ISSUE TITLE
build wxample with-react-md  error

### ISSUE THREAD

**Issue by foxundermoon** [zeit/next.js#1951]
local and now both failure

```
> Upload [====================] 100% 0.0s
> Sync complete (4.86MB) [10s]
> Initializing…
> Building
> ▲ npm install
> ✓ Using "yarn.lock"
> ⧗ Installing:
>  ‣ next@latest
>  ‣ react@^15.4.2
>  ‣ react-addons-css-transition-group@^15.4.2
>  ‣ react-addons-transition-group@^15.4.2
>  ‣ react-dom@^15.4.2
>  ‣ react-md@^1.0.1
> ✓ Installed 593 modules [51s]
> ▲ npm run build
> > with-react-md@1.0.0 build /home/nowuser/src
> > next build

> > Failed to build on /tmp/61256877-79a9-4608-a38d-509b098a46de
> { Error: ./~/react-addons-css-transition-group/index.js
> Module not found: Error: Can't resolve 'react/lib/ReactCSSTransitionGroup' in '/home/nowuser/src/node_modules/react-addons-css-transition-group'
> resolve 'react/lib/ReactCSSTransitionGroup' in '/home/nowuser/src/node_modules/react-addons-css-transition-group'
>   Parsed request is a module
>   using description file: /home/nowuser/src/node_modules/react-addons-css-transition-group/package.json (relative path: .)
>     Field 'browser' doesn't contain a valid alias configuration
>     aliased with mapping 'react': '/home/nowuser/src/node_modules/react/dist/react.min.js' to '/home/nowuser/src/node_modules/react/dist/react.min.js/lib/ReactCSSTransitionGroup'
>       using description file: /home/nowuser/src/node_modules/react-addons-css-transition-group/package.json (relative path: .)
>         Field 'browser' doesn't contain a valid alias configuration
>       after using description file: /home/nowuser/src/node_modules/react-addons-css-transition-group/package.json (relative path: .)
>         using description file: /home/nowuser/src/node_modules/react/package.json (relative path: ./dist/react.min.js/lib/ReactCSSTransitionGroup)
>           as directory
>             /home/nowuser/src/node_modules/react/dist/react.min.js/lib/ReactCSSTransitionGroup doesn't exist
>           no extension
>             Field 'browser' doesn't contain a valid alias configuration
>             /home/nowuser/src/node_modules/react/dist/react.min.js/lib/ReactCSSTransitionGroup doesn't exist
>           .js
>             Field 'browser' doesn't contain a valid alias configuration
>             /home/nowuser/src/node_modules/react/dist/react.min.js/lib/ReactCSSTransitionGroup.js doesn't exist
>           .json
>             Field 'browser' doesn't contain a valid alias configuration
>             /home/nowuser/src/node_modules/react/dist/react.min.js/lib/ReactCSSTransitionGroup.json doesn't exist
> [/home/nowuser/src/node_modules/react/dist/react.min.js/lib/ReactCSSTransitionGroup]
> [/home/nowuser/src/node_modules/react/dist/react.min.js/lib/ReactCSSTransitionGroup]
> [/home/nowuser/src/node_modules/react/dist/react.min.js/lib/ReactCSSTransitionGroup.js]
> [/home/nowuser/src/node_modules/react/dist/react.min.js/lib/ReactCSSTransitionGroup.json]
>  @ ./~/react-addons-css-transition-group/index.js 1:17-61
>  @ ./~/react-md/lib/NavigationDrawers/NavigationDrawer.js
>  @ ./~/react-md/lib/NavigationDrawers/index.js
>  @ ./pages?entry
>  @ multi ./pages?entry
>     at /home/nowuser/src/node_modules/next/dist/server/build/index.js:181:21
>     at /home/nowuser/src/node_modules/webpack/lib/Compiler.js:267:15
>     at Compiler.emitRecords (/home/nowuser/src/node_modules/webpack/lib/Compiler.js:362:37)
>     at /home/nowuser/src/node_modules/webpack/lib/Compiler.js:260:12
>     at /home/nowuser/src/node_modules/webpack/lib/Compiler.js:355:11
>     at next (/home/nowuser/src/node_modules/tapable/lib/Tapable.js:154:11)
>     at Compiler.compiler.plugin (/home/nowuser/src/node_modules/webpack/lib/performance/SizeLimitsPlugin.js:99:4)
>     at Compiler.applyPluginsAsyncSeries1 (/home/nowuser/src/node_modules/tapable/lib/Tapable.js:158:13)
>     at Compiler.afterEmit (/home/nowuser/src/node_modules/webpack/lib/Compiler.js:352:8)
>     at Compiler.<anonymous> (/home/nowuser/src/node_modules/webpack/lib/Compiler.js:347:14)
>   errors:
>    [ './~/react-addons-css-transition-group/index.js\nModule not found: Error: Can\'t resolve \'react/lib/ReactCSSTransitionGroup\' in \'/home/nowuser/src/node_modules/react-addons-css-transition-group\'\nresolve \'react/lib/ReactCSSTransitionGroup\' in \'/home/nowuser/src/node_modules/react-addons-css-transition-group\'\n  Parsed request is a module\n  using description file: /home/nowuser/src/node_modules/react-addons-css-transition-group/package.json (relative path: .)\n    Field \'browser\' doesn\'t contain a valid alias configuration\n    aliased with mapping \'react\': \'/home/nowuser/src/node_modules/react/dist/react.min.js\' to \'/home/nowuser/src/node_modules/react/dist/react.min.js/lib/ReactCSSTransitionGroup\'\n      using description file: /home/nowuser/src/node_modules/react-addons-css-transition-group/package.json (relative path: .)\n        Field \'browser\' doesn\'t contain a valid alias configuration\n      after using description file: /home/nowuser/src/node_modules/react-addons-css-transition-group/package.json (relative path: .)\n        using description file: /home/nowuser/src/node_modules/react/package.json (relative path: ./dist/react.min.js/lib/ReactCSSTransitionGroup)\n          as directory\n            /home/nowuser/src/node_modules/react/dist/react.min.js/lib/ReactCSSTransitionGroup doesn\'t exist\n          no extension\n            Field \'browser\' doesn\'t contain a valid alias configuration\n            /home/nowuser/src/node_modules/react/dist/react.min.js/lib/ReactCSSTransitionGroup doesn\'t exist\n          .js\n            Field \'browser\' doesn\'t contain a valid alias configuration\n            /home/nowuser/src/node_modules/react/dist/react.min.js/lib/ReactCSSTransitionGroup.js doesn\'t exist\n          .json\n            Field \'browser\' doesn\'t contain a valid alias configuration\n            /home/nowuser/src/node_modules/react/dist/react.min.js/lib/ReactCSSTransitionGroup.json doesn\'t exist\n[/home/nowuser/src/node_modules/react/dist/react.min.js/lib/ReactCSSTransitionGroup]\n[/home/nowuser/src/node_modules/react/dist/react.min.js/lib/ReactCSSTransitionGroup]\n[/home/nowuser/src/node_modules/react/dist/react.min.js/lib/ReactCSSTransitionGroup.js]\n[/home/nowuser/src/node_modules/react/dist/react.min.js/lib/ReactCSSTransitionGroup.json]\n @ ./~/react-addons-css-transition-group/index.js 1:17-61\n @ ./~/react-md/lib/NavigationDrawers/NavigationDrawer.js\n @ ./~/react-md/lib/NavigationDrawers/index.js\n @ ./pages?entry\n @ multi ./pages?entry',
>      './~/react-addons-transition-group/index.js\nModule not found: Error: Can\'t resolve \'react/lib/ReactTransitionGroup\' in \'/home/nowuser/src/node_modules/react-addons-transition-group\'\nresolve \'react/lib/ReactTransitionGroup\' in \'/home/nowuser/src/node_modules/react-addons-transition-group\'\n  Parsed request is a module\n  using description file: /home/nowuser/src/node_modules/react-addons-transition-group/package.json (relative path: .)\n    Field \'browser\' doesn\'t contain a valid alias configuration\n    aliased with mapping \'react\': \'/home/nowuser/src/node_modules/react/dist/react.min.js\' to \'/home/nowuser/src/node_modules/react/dist/react.min.js/lib/ReactTransitionGroup\'\n      using description file: /home/nowuser/src/node_modules/react-addons-transition-group/package.json (relative path: .)\n        Field \'browser\' doesn\'t contain a valid alias configuration\n      after using description file: /home/nowuser/src/node_modules/react-addons-transition-group/package.json (relative path: .)\n        using description file: /home/nowuser/src/node_modules/react/package.json (relative path: ./dist/react.min.js/lib/ReactTransitionGroup)\n          as directory\n            /home/nowuser/src/node_modules/react/dist/react.min.js/lib/ReactTransitionGroup doesn\'t exist\n          no extension\n            Field \'browser\' doesn\'t contain a valid alias configuration\n            /home/nowuser/src/node_modules/react/dist/react.min.js/lib/ReactTransitionGroup doesn\'t exist\n          .js\n            Field \'browser\' doesn\'t contain a valid alias configuration\n            /home/nowuser/src/node_modules/react/dist/react.min.js/lib/ReactTransitionGroup.js doesn\'t exist\n          .json\n            Field \'browser\' doesn\'t contain a valid alias configuration\n            /home/nowuser/src/node_modules/react/dist/react.min.js/lib/ReactTransitionGroup.json doesn\'t exist\n[/home/nowuser/src/node_modules/react/dist/react.min.js/lib/ReactTransitionGroup]\n[/home/nowuser/src/node_modules/react/dist/react.min.js/lib/ReactTransitionGroup]\n[/home/nowuser/src/node_modules/react/dist/react.min.js/lib/ReactTransitionGroup.js]\n[/home/nowuser/src/node_modules/react/dist/react.min.js/lib/ReactTransitionGroup.json]\n @ ./~/react-addons-transition-group/index.js 1:17-58\n @ ./~/react-md/lib/Inks/InkContainer.js\n @ ./~/react-md/lib/Inks/injectInk.js\n @ ./~/react-md/lib/Buttons/Button.js\n @ ./pages?entry\n @ multi ./pages?entry' ],
>   warnings: [] }
> npm ERR! Linux 4.7.0-coreos
> npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "run" "build"
> npm ERR! node v7.10.0
> npm ERR! npm  v4.2.0
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! with-react-md@1.0.0 build: `next build`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the with-react-md@1.0.0 build script 'next build'.
> npm ERR! Make sure you have the latest version of node.js and npm installed.
> npm ERR! If you do, this is most likely a problem with the with-react-md package,
> npm ERR! not with npm itself.
> npm ERR! Tell the author that this fails on your system:
> npm ERR!     next build
> npm ERR! You can get information on how to open an issue for this project with:
> npm ERR!     npm bugs with-react-md
> npm ERR! Or if that isn't available, you can get their info via:
> npm ERR!     npm owner ls with-react-md
> npm ERR! There is likely additional logging output above.
> npm ERR! Please include the following file with any support request:
> npm ERR!     /home/nowuser/.npm/_logs/2017-05-12T10_33_35_711Z-debug.log

```

**Comment by c0b41** [comment]
#1877

**Comment by timneutkens** [comment]
I added the recommended fix to the example.
