### ISSUE TITLE
v3-beta Error: Cannot find module 'walk'

### ISSUE THREAD

**Issue by johhansantana** [zeit/next.js#1971]
when I do `next build && next export` I get an error:

```
➜  with-dynamic-import git:(v3-beta) ✗ yarn build
yarn build v0.21.3
$ next build && next export 
> Using external babel configuration
> location: "/Users/jsantana/Downloads/next.js/examples/.babelrc"
module.js:472
    throw err;
    ^

Error: Cannot find module 'walk'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/jsantana/Downloads/next.js/examples/with-dynamic-import/node_modules/next/dist/server/export.js:39:13)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
error Command failed with exit code 1.
```

**Comment by arunoda** [comment]
Thanks.
Try the latest beta. We just fixed it.

**Comment by johhansantana** [comment]
@arunoda the blog post with the example `next.config.js` has invalid syntax

```javascript
exports.exportPathMap = () => {
  "/": { page: "/" },
  "/about": { page: "/about" },
  "/p/hello-nextjs": { page: "/post", query: { title: "hello-nextjs" } },
  "/p/learn-nextjs": { page: "/post", query: { title: "learn-nextjs" } },
  "/p/deploy-nextjs": { page: "/post", query: { title: "deploy-nextjs" } }
}
```

if I try to change it to
```javascript
exports.exportPathMap = {
  "/": { page: "/" },
  "/about": { page: "/about" },
  "/p/hello-nextjs": { page: "/post", query: { title: "hello-nextjs" } },
  "/p/learn-nextjs": { page: "/post", query: { title: "learn-nextjs" } },
  "/p/deploy-nextjs": { page: "/post", query: { title: "deploy-nextjs" } }
}
```

The `next export` gives me error:
```
$ next export 
  Exporting to: /Users/jsantana/Downloads/next.js/examples/with-dynamic-import/out

  copying dynamic import chunks
> Could not found "exportPathMap" function inside "next.config.js"
> "next export" uses that function build html pages.
error Command failed with exit code 1.
```

**Comment by johhansantana** [comment]
fixed:
```
exports.exportPathMap = () => {
  return {
    "/": { page: "/" },
    "/about": { page: "/about" }
  }
}
```

**Comment by arunoda** [comment]
Thanks. Will fix it.

**Comment by mrwullah** [comment]
Is it fixed? I still can see the same issue.

**Comment by VitaliiKotliar** [comment]
+1

**Comment by tianhuil** [comment]
@mrwullah, this issue has been fixed.  You have to fill in `next.config.js` as per @johhansantana's comment and the error goes away.
