### ISSUE TITLE
[2.3.1] Runtime error in prod build. Dev runs clean.

### ISSUE THREAD

**Issue by jcheroske** [zeit/next.js#2009]
I'm getting an error when running the production build. I do a:
```
yarn run build
yarn run start
```
and the server comes up fine. But when I hit it, I get this:
```
TypeError: store.getState is not a function
    at ApolloClient.setStore (/Users/jay/code/freightslayer-next/node_modules/apollo-client/apollo.umd.js:3473:44)
    at /Users/jay/code/freightslayer-next/node_modules/apollo-client/apollo.umd.js:3308:23
    at /Users/jay/code/freightslayer-next/node_modules/redux/lib/applyMiddleware.js:49:16
    at Array.map (native)
    at /Users/jay/code/freightslayer-next/node_modules/redux/lib/applyMiddleware.js:48:27
    at createStore (/Users/jay/code/freightslayer-next/node_modules/redux/lib/createStore.js:65:33)
    at createReduxStore (/Users/jay/code/freightslayer-next/build/dist/config/modules/apollo-redux.js:154:45)
    at Function._callee$ (/Users/jay/code/freightslayer-next/build/dist/config/modules/apollo-redux.js:179:34)
    at tryCatch (/Users/jay/code/freightslayer-next/node_modules/regenerator-runtime/runtime.js:65:40)
    at Generator.invoke [as _invoke] (/Users/jay/code/freightslayer-next/node_modules/regenerator-runtime/runtime.js:303:22)
```
If I view the `store` object at the point of the exception, it looks like this:
```
{ 
  getState: undefined, 
  dispatch: [Function: dispatch]
}
```
When the code is run in the `dev` server, the same object looks like:
```
{ 
  getState: [Function: getState],
  dispatch: [Function: dispatch] 
}
```
Anyone have any insight into this?

**Comment by arunoda** [comment]
We can't tell anything without looking at code.
Could you give us any sample code to test with?

**Comment by arunoda** [comment]
Please re-open this issue after that.
