### ISSUE TITLE
Async functions defined on module throw TypeError

### ISSUE THREAD

**Issue by amccloud** [zeit/next.js#202]
Looks like the [`babel-runtime` alias in the webpack config](https://github.com/zeit/next.js/blob/master/server/build/webpack.js#L100) is causing babel to transpile incorrectly. Any async function defined on the module fails because `_regenerator2` is `undefined`. If the aysnc function is defined within a class, like with `getInitialProps`, everything works. Without the alias everything appears to work. I'm using `next@1.1.0`.

##### pages/index.js
```js
async function test() {
  
}
```

##### throws:
```node
TypeError: Cannot read property 'default' of undefined
    at /Users/amccloud/Labs/Auth0/next-auth0/.next/dist/pages/index.js:4:36
    at Object.<anonymous> (/Users/amccloud/Labs/Auth0/next-auth0/.next/dist/pages/index.js:19:2)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at _callee$ (/Users/amccloud/Labs/Auth0/next-auth0/node_modules/next/dist/server/require.js:33:46)
```

##### with `babel-runtime` alias
```js
"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.test = undefined;

var test = exports.test = function () {
  var _ref = (0, _asyncToGenerator3.default)(_regenerator2.default.mark(function _callee() { // _regenerator2 undefined
    return _regenerator2.default.wrap(function _callee$(_context) {
      while (1) {
        switch (_context.prev = _context.next) {
          case 0:
          case "end":
            return _context.stop();
        }
      }
    }, _callee, this);
  }));

  return function test() {
    return _ref.apply(this, arguments);
  };
}();

var _regenerator = require("/Users/amccloud/Labs/Auth0/next-auth0/node_modules/babel-runtime/regenerator");

var _regenerator2 = _interopRequireDefault(_regenerator);

var _asyncToGenerator2 = require("/Users/amccloud/Labs/Auth0/next-auth0/node_modules/babel-runtime/helpers/asyncToGenerator");

var _asyncToGenerator3 = _interopRequireDefault(_asyncToGenerator2);

function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }
```

##### without `babel-runtime` alias
```
"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.test = undefined;

var _regenerator = require("babel-runtime/regenerator");

var _regenerator2 = _interopRequireDefault(_regenerator);

var _asyncToGenerator2 = require("babel-runtime/helpers/asyncToGenerator");

var _asyncToGenerator3 = _interopRequireDefault(_asyncToGenerator2);

var test = exports.test = function () {
  var _ref = (0, _asyncToGenerator3.default)(_regenerator2.default.mark(function _callee() {
    return _regenerator2.default.wrap(function _callee$(_context) {
      while (1) {
        switch (_context.prev = _context.next) {
          case 0:
          case "end":
            return _context.stop();
        }
      }
    }, _callee, this);
  }));

  return function test() {
    return _ref.apply(this, arguments);
  };
}();

function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }
```

##### possibly related issues
- https://github.com/zeit/next.js/issues/168

**Comment by sedubois** [comment]
Looks like this and #168 are duplicates

**Comment by amccloud** [comment]
@sedubois possibly. I linked to it at the bottom of my issue. @bs1180 mentioned he thinks his problem might be different.

**Comment by bs1180** [comment]
@amccloud I think this is likely the root cause of both the problems with template literals and async functions (and no doubt other ES6 functionality that no-one has stumbled over yet). I'll test it against the template literals later, fingers crossed.

**Comment by nkzawa** [comment]
It seems this is the problem of `babel` or `babel-plugin-module-resolver`. I reported it to their repo:

https://github.com/tleunen/babel-plugin-module-resolver

**Comment by tleunen** [comment]
Thank you @nkzawa for reporting the issue. I've fixed the issue and released a v2.3.0. Let me know if you have any other problems.

**Comment by amccloud** [comment]
Thanks @tleunen!

@nkzawa `2.3.0` fixes the issue I reported. Fix in PR: https://github.com/zeit/next.js/pull/218

**Comment by nkzawa** [comment]
@tleunen @amccloud 😍  thanks for your quick response !
