### ISSUE TITLE
Run well when dev, but i get a 404 after build.

### ISSUE THREAD

**Issue by DarkPage** [zeit/next.js#2038]
I fllow the lesson: 7.Fetching Data for Pages, i make a simple api like this:
```js
// server.js
const express = require('express');
const bodyParser = require('body-parser');
const next = require('next');

const dev = process.env.NODE_ENV !== 'production';
const app = next({ dev });
const handle = app.getRequestHandler();
const cors = require('cors');

var user = require('./controller/user.controller.js');  // orm sequelize

app.prepare().then(() => {

    const server = express();

    server.use(bodyParser.json());                              // for parsing application/json
    server.use(bodyParser.urlencoded({ extended: true }));      // for parsing application/x-www-form-urlencoded
    server.use(cors());

    server.get('/api/v1/user', (req, res) => {
        user.findAll(req, res);
    });

    server.get('*', (req, res) => {
        return handle(req, res)
    });

    server.listen(3000, (err) => {
        if (err) throw err
        console.log('> Ready on http://localhost:3000')
    });
}).catch((ex) => {
    console.error(ex.stack)
    process.exit(1)
});
```
```js
// pages/index.js
import Header from '../components/Header';
import axios from 'axios';
import React, { Component } from 'react';
import ReactDOM from 'react-dom';

// class style
export default class Index extends Component {

	static async getInitialProps() {
		try {
			const res = await axios.get('http://localhost:3000/api/v1/user');
			const { data } = res;
			console.log(`User data fetched.`)
			return {
				users: data || []
			}
		} catch (error) {
			console.log(error)
			return {
				users: []
			}
		}
	}

	render() {
		let html = this.props.users.map(user=>{
			return (
				<div className="user">
					<h5>{user.id}</h5>
					<p>{user.firstName}</p>
					<div>{user.lastName}</div>
				</div>
			)
		});
		return (
			<div>
				<Header />
				<p>Hello Next.js</p>
				<div>{html}</div>
				<style jsx global>{`
				p{
					font-size: 14px;
				}
				.user{
					border-bottom: 1px solid black;
					background: url('./static/kitty.png') no-repeat;
				}
				`}</style>
			</div>
		)
	}
}
```
```js
// deploy
$npm run build
$PORT=3000 npm run start // script next start -p $PORT

// http://localhost:3000/ refresh i got 404
{ Error: Request failed with status code 404
    at createError (/Users/wangxin/Desktop/next-k12/node_modules/axios/lib/core/createError.js:15:15)
    at settle (/Users/wangxin/Desktop/next-k12/node_modules/axios/lib/core/settle.js:18:12)
    at IncomingMessage.handleStreamEnd (/Users/wangxin/Desktop/next-k12/node_modules/axios/lib/adapters/http.js:191:11)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:188:7)
    at endReadableNT (_stream_readable.js:975:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
  config:
   { adapter: [Function: httpAdapter],
     transformRequest: { '0': [Function: transformRequest] },
     transformResponse: { '0': [Function: transformResponse] },
     timeout: 0,
     xsrfCookieName: 'XSRF-TOKEN',
     xsrfHeaderName: 'X-XSRF-TOKEN',
     maxContentLength: -1,
     validateStatus: [Function: validateStatus],
     headers:
...
```
why error ?

**Comment by arunoda** [comment]
It's hard to answer like this.
Feel send us a sample repo.

**Comment by arunoda** [comment]
Please re-open once you have it.

**Comment by kunokdev** [comment]
Just started getting this error on my stage project:

> Error: Request failed with status code 404
>     at e.exports (http://hoteli.tmc-solutions.xyz/_next/64a5f7aebc1b5bff0baa1baeaf94b8c8/app.js:7:253428)
>     at e.exports (http://hoteli.tmc-solutions.xyz/_next/64a5f7aebc1b5bff0baa1baeaf94b8c8/app.js:12:176441)
>     at XMLHttpRequest.p.(anonymous function) (http://hoteli.tmc-solutions.xyz/_next/64a5f7aebc1b5bff0baa1baeaf94b8c8/app.js:7:252181)

I can't provide static repository because project has many points with hardcoded credentials but built demo is available at http://hoteli.tmc-solutions.xyz  (I'll edit this post once I update page with new versiomn w/o this issue)

It is late atm and my work time is finished but I will continue working on finding what caused this error in the morning and will update this post.

**Comment by miladmeidanshahi** [comment]
same issue :\
