### ISSUE TITLE
Unexpected token import in node_modules

### ISSUE THREAD

**Issue by achtan** [zeit/next.js#2080]
hi, here is my repo: https://github.com/achtan/nextjs-unexpected-token-import

when i run `npm run dev` i see this error:
```
/Users/admin/sites/.../email-wizard/node_modules/react-iframe/index.js:1
(function (exports, require, module, __filename, __dirname) { import React, {PureComponent} from "react"

SyntaxError: Unexpected token import
    at Object.exports.runInThisContext (vm.js:78:16)
    at Module._compile (module.js:543:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/admin/sites/.../email-wizard/.next/dist/components/Preview.js:15:20)
    at Module._compile (module.js:571:32)
```

as you can see my package.json is a bit messy :) I tried a few presetes but with no luck...

**Comment by timneutkens** [comment]
@achtan This is an unfortunate issue on `react-iframe`. As you can see it tries to load `index.js` (https://github.com/svenanders/react-iframe/blob/master/index.js) which has es6 code in it. It should load `index.min.js` because of this line: https://github.com/svenanders/react-iframe/blob/master/package.json#L5. I believe the author forgot to run `gulp` before `npm publish`ing it 😅 

As far as Next.js goes. We ignore the `node_modules` directory from being compiled by babel.

**Comment by achtan** [comment]
thx for help!
one more question: why can i write `import ... from... ` in my server.js file? i am forced to use ` const ... = require(..)`

**Comment by timneutkens** [comment]
We don't transpile server.js so you're bound to your version of node.js.
