### ISSUE TITLE
_next/on-demand-entries-ping - Cannot read property 'replace' of undefined

### ISSUE THREAD

**Issue by rpellerin** [zeit/next.js#2109]
I built an app with Next.js and Express. When doing`NODE_ENV=production node server` and then accessing `http://localhost:3000/_next/on-demand-entries-ping`, I get 

```
0|server   | TypeError: Cannot read property 'replace' of undefined
0|server   |     at normalizePage (node_modules/next/dist/server/on-demand-entry-ha
ndler.js:264:14)
0|server   |     at node_modules/next/dist/server/on-demand-entry-handler.js:193:20
0|server   |     at node_modules/next/dist/server/hot-reloader.js:129:29
0|server   |     at F (node_modules/core-js/library/modules/_export.js:35:28)
0|server   |     at HotReloader._loop$ (node_modules/next/dist/server/hot-reloader.
js:128:34)
0|server   |     at tryCatch (node_modules/regenerator-runtime/runtime.js:65:40)
0|server   |     at Generator.invoke [as _invoke] (node_modules/regenerator-runtime
/runtime.js:303:22)
0|server   |     at Generator.prototype.(anonymous function) [as next] (node_module
s/regenerator-runtime/runtime.js:117:21)
0|server   |     at tryCatch (node_modules/regenerator-runtime/runtime.js:65:40)
0|server   |     at maybeInvokeDelegate (node_modules/regenerator-runtime/runtime.j
s:365:18)
```

How can I fix that? Thank you.

**Comment by sergiodxa** [comment]
`on-demand-entries-ping` it's only for development, are you sending `{ dev: false }` to `next` in your custom server?

**Comment by arunoda** [comment]
Thanks @sergiodxa .
Check you are using the NODE_ENV correct to get decide the dev or not.
Check our example apps for more info.

**Comment by rpellerin** [comment]
Yes I am @sergiodxa. And yet I am getting `Internal Server Error` with the stacktrace I copy pasted above.
