### ISSUE TITLE
firebaseui can't import

### ISSUE THREAD

**Issue by polo13999** [zeit/next.js#2167]
ReferenceError: window is not defined
    at /Users/user/Sites/demo/firebaseNext/node_modules/firebaseui/dist/npm.js:30:129
    at Object.<anonymous> (/Users/user/Sites/demo/firebaseNext/node_modules/firebaseui/dist/npm.js:327:16)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/user/Sites/demo/firebaseNext/.next/dist/pages/index.js:15:19)

**Comment by sedubois** [comment]
https://github.com/zeit/next.js/wiki/FAQ#i-use-a-library-which-throws-window-is-undefined
