### ISSUE TITLE
Very strange `CDC` structure error, unexpectedly

### ISSUE THREAD

**Issue by micahbrich** [zeit/next.js#2203]
In the last few days, since from 2.0 to the latest 2.x, then @latest, I've been getting this super strange error that I cannot, for the life of me, figure out:

```js
Module build failed: Error: Wrong value in `CDC` structure definition (While processing preset: "/sites/x/node_modules/next/babel.js")
    at processStructure (/sites/x/node_modules/css-tree/lib/syntax/index.js:144:23)
    at createSyntax (/sites/x/node_modules/css-tree/lib/syntax/index.js:219:33)
    at Object.exports.create (/sites/x/node_modules/css-tree/lib/syntax/index.js:294:12)
    at Object.<anonymous> (/sites/x/node_modules/css-tree/lib/syntax/default.js:3:40)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
```

It's happened a handful of times, though I can't quite pin down when it'll pop up — just now I was literally just adding `window.thingy = thingy` to a `componentDidMount()` method. 

After removing the line I added, the error persisted, though. The only way I've found to get past it is to `rm -rf node_modules` and then `yarn install` all over again.

Does anyone have any idea what the heck this is all about? :boom:

**Comment by arunoda** [comment]
May be it's related to a babel plugin you use. Could you have a look at the `css-tree` module if you are using it directly.

Try to remove it and use.

**Comment by micahbrich** [comment]
It's happened so intermittently I can't even debug it at this point, but thank you @arunoda 🙌

**Comment by AndreAntunesVieira** [comment]
I had the same problem. My problem was a Array.prototype... css-tree dependence use some method that break with array extends.
