### ISSUE TITLE
Hard to determine within generated code where next is failing

### ISSUE THREAD

**Issue by JulianKnodt** [zeit/next.js#2229]
Essentially, I have a bunch of markdown files which I'm parsing with Github's Markup Ruby library, and piping them all one level deep inside the pages directory. Everything works fine when I run `next dev` but when I run `next build` it throws this error. I can't determine if it's my own parsing code that throws this error, or if it's next. a generated file is fairly simple:

```
//Generated on 10/06/2017 12:05

import React from 'react';
import Page from './components/page.js';
const template = {__html: `Long String With Generated HTML from MD with inline HTML`}

export default () => <Page><div dangerouslySetInnerHTML={template}/></Page>;
```

I think the issue I want to highlight is that I can't tell where the error is coming from. Because it's generated HTML, there's a ton of > operators, and it doesn't provide a line or file. I think just displaying where in my code it came up would be nice

```{ Error: commons.js from UglifyJs
Unexpected token: operator (>) [commons.js:6747,25]
    at /Users/julianknodt/Desktop/programming/projects/codechrysalis-prep/node_modules/next/dist/server/build/index.js:181:21
    at /Users/julianknodt/Desktop/programming/projects/codechrysalis-prep/node_modules/next/node_modules/webpack/lib/Compiler.js:267:15
    at Compiler.emitRecords (/Users/julianknodt/Desktop/programming/projects/codechrysalis-prep/node_modules/next/node_modules/webpack/lib/Compiler.js:362:37)
    at /Users/julianknodt/Desktop/programming/projects/codechrysalis-prep/node_modules/next/node_modules/webpack/lib/Compiler.js:260:12
    at /Users/julianknodt/Desktop/programming/projects/codechrysalis-prep/node_modules/next/node_modules/webpack/lib/Compiler.js:355:11
    at next (/Users/julianknodt/Desktop/programming/projects/codechrysalis-prep/node_modules/tapable/lib/Tapable.js:154:11)
    at Compiler.compiler.plugin (/Users/julianknodt/Desktop/programming/projects/codechrysalis-prep/node_modules/next/node_modules/webpack/lib/performance/SizeLimitsPlugin.js:99:4)
    at Compiler.applyPluginsAsyncSeries1 (/Users/julianknodt/Desktop/programming/projects/codechrysalis-prep/node_modules/tapable/lib/Tapable.js:158:13)
    at Compiler.afterEmit (/Users/julianknodt/Desktop/programming/projects/codechrysalis-prep/node_modules/next/node_modules/webpack/lib/Compiler.js:352:8)
    at Compiler.<anonymous> (/Users/julianknodt/Desktop/programming/projects/codechrysalis-prep/node_modules/next/node_modules/webpack/lib/Compiler.js:347:14)
  errors: [ 'commons.js from UglifyJs\nUnexpected token: operator (>) [commons.js:6747,25]' ],
  warnings: [] }

```

**Comment by JulianKnodt** [comment]
Fixed when I deleted `node_modules/`. I didn't try turning it on and off again.
