### ISSUE TITLE
Unable to add custom resolve dir

### ISSUE THREAD

**Issue by chaffeqa** [zeit/next.js#2232]
Our existing app has `./src` as the original entry point.  Throughout our code we have `import Component from 'something/in/scr'`.

To solve this, in our root (where we are building the `next.config.js`) we have defined:

```js
const path = require('path')
const ourSrcDir = path.resolve(__dirname, 'src')
module.exports = {
  webpack: (config, { dev }) => {
    config.resolve.modules.push(ourSrcDir)
    // Important: return the modified config
    return config
  }
}
```

This works fine with `npm build`, however the dev server fails (on opening in browser) with:

```
{ Error: Cannot find module 'components/c2'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/next-resolve-bug/.next/dist/src/components/c1.js:11:10)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3) code: 'MODULE_NOT_FOUND' }
```

I made an [reproduction repo](https://github.com/chaffeqa/next-resolve-bug).

```
npm install && npm run clean && npm run build
```

Then open `http://localhost:3000`

**Comment by chaffeqa** [comment]
I actually just [solved this using a custom .babelrc rule](https://github.com/chaffeqa/next-resolve-bug/commit/e913d6037bffa1b2e82c4241c8090f26c41a71fd)

Hope this helps anyone else
