### ISSUE TITLE
Bluebird is generating a promise warning

### ISSUE THREAD

**Issue by jcheroske** [zeit/next.js#2251]
I've replace the default Promise implementation with Bluebird's with the following startup code:
```
const globalObject = process.browser ? window : global
globalObject.Promise = Promise
require('babel-runtime/core-js/promise').default = Promise
```
When next.js starts up, I'm seeing a Bluebird warning in the browser console:
```
bluebird.js?922a52e:1542 Warning: a promise was created in a handler but was not returned from it, see http://goo.gl/rRqMUw
    at new Promise (http://localhost:3000/_next/1497375358980/commons.js:124054:10)
    at http://localhost:3000/_next/1497375358980/commons.js:3296:12
    at runPinger (http://localhost:3000/_next/1497375358980/commons.js:9498:20)
    at exports.default (http://localhost:3000/_next/1497375358980/commons.js:9506:3)
    at http://localhost:3000/_next/1497375358980/commons.js:15211:39
    at <anonymous>
From previous event:
    at Object.<anonymous> (http://localhost:3000/_next/1497375358980/commons.js:15210:16)
    at __webpack_require__ (http://localhost:3000/_next/1497375358980/manifest.js:698:31)
    at fn (http://localhost:3000/_next/1497375358980/manifest.js:115:20)
    at Object.590 (http://localhost:3000/_next/1497375358980/main.js:9:18)
    at __webpack_require__ (http://localhost:3000/_next/1497375358980/manifest.js:698:31)
    at webpackJsonpCallback (http://localhost:3000/_next/1497375358980/manifest.js:26:23)
    at http://localhost:3000/_next/1497375358980/main.js:2:1
```
Everything is working correctly.

**Comment by arunoda** [comment]
I think you can't do this way. That's because babel's Promise polyfil is loaded even before you do this.
