### ISSUE TITLE
[Async/await] ReferenceError: regeneratorRuntime is not defined 

### ISSUE THREAD

**Issue by jackmatrix** [zeit/next.js#2313]
I have the following error when i am trying to use the async await function getInitialProps.
`error: ReferenceError: regeneratorRuntime is not defined
    at /.next/dist/pages/index.js:73:34
    at /.next/dist/pages/index.js:102:4
    at Object.<anonymous> (/.next/dist/pages/index.js:109:2)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)`

So any idea to help me to make this working ?

Thanks

**Comment by arunoda** [comment]
I assume something is wrong with your babel setup. When you start your app, see what's the location of the babelrc file.
Have a look at it and act accordingly.
Basically, your babel config need to have `next/babel` preset.
