### ISSUE TITLE
`TypeError: Cannot read property 'split' of undefined` on export

### ISSUE THREAD

**Issue by frol** [zeit/next.js#2315]
Using non-`<a>` tags inside `<Link>` cause `TypeError: Cannot read property 'split' of undefined` on export (Next.js `3.0.0-beta16`):

```
$ next build
$ next export
  using build directory: /tmp/qq/.next
  exporting path: /
TypeError: Cannot read property 'split' of undefined
    at _rewriteUrlForNextExport (/tmp/qq/node_modules/next/dist/lib/router/index.js:120:23)
    at Link.render (/tmp/qq/node_modules/next/dist/lib/link.js:187:59)
    at ReactCompositeComponentWrapper._renderValidatedComponentWithoutOwnerOrContext (/tmp/qq/node_modules/react-dom/lib/ReactCompositeComponent.js:798:30)
    at ReactCompositeComponentWrapper._renderValidatedComponent (/tmp/qq/node_modules/react-dom/lib/ReactCompositeComponent.js:821:32)
    at ReactCompositeComponentWrapper.performInitialMount (/tmp/qq/node_modules/react-dom/lib/ReactCompositeComponent.js:361:30)
    at ReactCompositeComponentWrapper.mountComponent (/tmp/qq/node_modules/react-dom/lib/ReactCompositeComponent.js:257:21)
    at Object.mountComponent (/tmp/qq/node_modules/react-dom/lib/ReactReconciler.js:45:35)
    at ReactCompositeComponentWrapper.performInitialMount (/tmp/qq/node_modules/react-dom/lib/ReactCompositeComponent.js:370:34)
    at ReactCompositeComponentWrapper.mountComponent (/tmp/qq/node_modules/react-dom/lib/ReactCompositeComponent.js:257:21)
    at Object.mountComponent (/tmp/qq/node_modules/react-dom/lib/ReactReconciler.js:45:35)
```

```javascript
/* pages/index.js */

import Link from 'next/link'

export default () => {
    return <Link href="/"><button>Test</button></Link>
}
```

```javascript
/* next.config.js */

module.exports = {
  exportPathMap: function() {
    return {
      '/': { page: '/' },
    }
  }
}
```

NOTE: Both development (`next`) and release (`next start`) modes work fine while static exporting fails.

**Comment by arunoda** [comment]
Thanks. This is a bug.

**Comment by saulflores95** [comment]
Hi I just downloaded the Next 3.0 and i am getting the same error! 
`
module.exports = {
  exportPathMap: function () {
    return {
      "/": { page: "/" },
      "/quienes-somos": { page: "/quienes-somos" },
      "/servicios": { page: "/servicios", query: { title: "Nuestro Servicio" } },
      "/contacto": { page: "/contacto", query: { title: "Contacto" } }
    }
  },
}

`
yarn export v0.21.3
$ next build && next export
                                                                                                                                                                                                                    using build directory: C:\Users\Saul\Documents\GitHub\toroco\.next
  exporting path: /
  exporting path: /quienes-somos
  exporting path: /servicios
  exporting path: /contacto
TypeError: Cannot read property 'split' of undefined
    at _rewriteUrlForNextExport (C:\Users\Saul\Documents\GitHub\toroco\node_modules\next\dist\lib\router\index.js:120:23)
    at Link.render (C:\Users\Saul\Documents\GitHub\toroco\node_modules\next\dist\lib\link.js:187:59)
    at ReactCompositeComponentWrapper._renderValidatedComponentWithoutOwnerOrContext (C:\Users\Saul\Documents\GitHub\toroco\node_modules\react-dom\lib\ReactCompositeComponent.js:799:30)
    at ReactCompositeComponentWrapper._renderValidatedComponent (C:\Users\Saul\Documents\GitHub\toroco\node_modules\react-dom\lib\ReactCompositeComponent.js:822:32)
    at ReactCompositeComponentWrapper.performInitialMount (C:\Users\Saul\Documents\GitHub\toroco\node_modules\react-dom\lib\ReactCompositeComponent.js:362:30)
    at ReactCompositeComponentWrapper.mountComponent (C:\Users\Saul\Documents\GitHub\toroco\node_modules\react-dom\lib\ReactCompositeComponent.js:258:21)
    at Object.mountComponent (C:\Users\Saul\Documents\GitHub\toroco\node_modules\react-dom\lib\ReactReconciler.js:46:35)
    at ReactDOMComponent.mountChildren (C:\Users\Saul\Documents\GitHub\toroco\node_modules\react-dom\lib\ReactMultiChild.js:238:44)
    at ReactDOMComponent._createContentMarkup (C:\Users\Saul\Documents\GitHub\toroco\node_modules\react-dom\lib\ReactDOMComponent.js:653:32)
    at ReactDOMComponent.mountComponent (C:\Users\Saul\Documents\GitHub\toroco\node_modules\react-dom\lib\ReactDOMComponent.js:520:29)
error Command failed with exit code 1.

`


`

**Comment by bossbossk20** [comment]
this issue saved me  👍
