### ISSUE TITLE
Dynamic import : Unexpected token import 

### ISSUE THREAD

**Issue by jackmatrix** [zeit/next.js#2424]
I am unable to dynamically import my components. I have the following error 

`Module build failed: SyntaxError: Unexpected token (import)`

I am just trying to do this 

`const DynamicComponent5 = dynamic(import('./home.js'))`

i've yet imported dynamic from next

So what i've missed ?

Thanks for helping

**Comment by timneutkens** [comment]
@jackmatrix, what version of next.js are you using?

**Comment by jackmatrix** [comment]
I am using 2.4.4

**Comment by timneutkens** [comment]
@jackmatrix please update to `next@beta`, dynamic imports are a feature of the upcoming v3 version 👍

**Comment by jackmatrix** [comment]
YEah thanks i just figured it out now. So i updated and the issue was fixed. Thanks a lot.

**Comment by timneutkens** [comment]
👌

**Comment by donedgardo** [comment]
Hi tim! I'm having this same issue with `next@beta`.
I have a custom webpack in my next.config.js:
```javascript
module.exports = {
  webpack: (config, { dev }) => {
    // Perform customizations to webpack config
    // MapboxDraw error https://github.com/webpack-contrib/css-loader/issues/447
    config.node = {};
    config.node.fs = 'empty';
    // Important: return the modified config
    return config
  },
  webpackDevMiddleware: (config) => {
    // Perform customizations to webpack dev middleware config
    config.node = {};
    config.node.fs = 'empty';
    // Important: return the modified config
    return config
  }
}
```
I tried `next build` locally with the following error output: 
```bash
> next build

> Using "webpack" config function defined in next.config.js.
> Failed to build on /var/folders/48/ldn9nnlx7bnbg6m8ss2b84hr0000gn/T/ffd50826-7451-4851-81ee-0d5a6b87da8b
{ Error: chunks/---LocationMap-bce28a43-2313-497a-ab2e-fa90cb18fc27.js from UglifyJs
Unexpected token: operator (>) [chunks/---LocationMap-bce28a43-2313-497a-ab2e-fa90cb18fc27.js:253,73]
    at /Users/donedgardo/skyrocket/migoIQ/connectIQ/node_modules/next/dist/server/build/index.js:182:21
    at emitRecords.err (/Users/donedgardo/skyrocket/migoIQ/connectIQ/node_modules/webpack/lib/Compiler.js:269:13)
    at Compiler.emitRecords (/Users/donedgardo/skyrocket/migoIQ/connectIQ/node_modules/webpack/lib/Compiler.js:375:38)
    at emitAssets.err (/Users/donedgardo/skyrocket/migoIQ/connectIQ/node_modules/webpack/lib/Compiler.js:262:10)
    at applyPluginsAsyncSeries1.err (/Users/donedgardo/skyrocket/migoIQ/connectIQ/node_modules/webpack/lib/Compiler.js:368:12)
    at next (/Users/donedgardo/skyrocket/migoIQ/connectIQ/node_modules/tapable/lib/Tapable.js:200:11)
    at Compiler.compiler.plugin (/Users/donedgardo/skyrocket/migoIQ/connectIQ/node_modules/webpack/lib/performance/SizeLimitsPlugin.js:99:4)
    at Compiler.applyPluginsAsyncSeries1 (/Users/donedgardo/skyrocket/migoIQ/connectIQ/node_modules/tapable/lib/Tapable.js:204:13)
    at Compiler.afterEmit (/Users/donedgardo/skyrocket/migoIQ/connectIQ/node_modules/webpack/lib/Compiler.js:365:9)
    at require.forEach.err (/Users/donedgardo/skyrocket/migoIQ/connectIQ/node_modules/webpack/lib/Compiler.js:360:15)
  errors: [ 'chunks/---LocationMap-bce28a43-2313-497a-ab2e-fa90cb18fc27.js from UglifyJs\nUnexpected token: operator (>) [chunks/---LocationMap-bce28a43-2313-497a-ab2e-fa90cb18fc27.js:253,73]' ],
  warnings: 
   [ './node_modules/es6-promise/dist/es6-promise.js\nModule not found: Error: Can\'t resolve \'vertx\' in \'/Users/donedgardo/skyrocket/migoIQ/connectIQ/node_modules/es6-promise/dist\'\nresolve \'vertx\' in \'/Users/donedgardo/skyrocket/migoIQ/connectIQ/node_modules/es6-promise/dist\'\n  Parsed request is a module\n  using description file: /Users/donedgardo/skyrocket/migoIQ/connectIQ/node_modules/es6-promise/package.json (relative path: ./dist)\n  after using description file: /Users/donedgardo/skyrocket/migoIQ/connectIQ/node_modules/es6-promise/package.json (relative path: ./dist)\n    resolve as module\n      looking for modules in /Users/donedgardo/skyrocket/migoIQ/connectIQ/node_modules/next/node_modules\n        using description file: /Users/donedgardo/skyrocket/migoIQ/connectIQ/node_modules/next/package.json (relative path: ./node_modules)\n      
```

Now log from build: 
```
> Failed to build on /tmp/fa0d35b1-8b22-4777-b73f-34cd049c9752
> { Error: ./components/LocationForm/LocationForm.js
> Module build failed: SyntaxError: Unexpected token (17:2)
>   15 | 
>   16 | const LocationMap = dynamic(
> > 17 |   import('../LocationMap'),
>      |   ^
>   18 |   { ssr: false },
>   19 | );
>   20 | const FTP_SERVER = 'https://migoiq.ftp.server.com/';
> Error
>     at transpile (/home/nowuser/src/node_modules/babel-loader/lib/index.js:63:13)
>     at /home/nowuser/src/node_modules/babel-loader/lib/fs-cache.js:118:18
>     at ReadFileContext.callback (/home/nowuser/src/node_modules/babel-loader/lib/fs-cache.js:31:21)
>     at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:359:13)
>  @ ./pages/locations.js?entry 75:21-71
```
