### ISSUE TITLE
_document.js from Next 2 incompatible with Next 3

### ISSUE THREAD

**Issue by mherodev** [zeit/next.js#2435]
When upgrading to `@next` I'm seeing this error when building:

```
TypeError: Cannot read property 'map' of undefined
    at Head.getPreloadDynamicChunks (/Users/mherold/git/next-web/node_modules/next/dist/server/document.js:146:20)
    at Head.render (/Users/mherold/git/next-web/node_modules/next/dist/server/document.js:174:14)
    at /Users/mherold/git/next-web/node_modules/react-dom/lib/ReactCompositeComponent.js:795:21
    at measureLifeCyclePerf (/Users/mherold/git/next-web/node_modules/react-dom/lib/ReactCompositeComponent.js:75:12)
    at ReactCompositeComponentWrapper._renderValidatedComponentWithoutOwnerOrContext (/Users/mherold/git/next-web/node_modules/react-dom/lib/ReactCompositeComponent.js:794:25)
    at ReactCompositeComponentWrapper._renderValidatedComponent (/Users/mherold/git/next-web/node_modules/react-dom/lib/ReactCompositeComponent.js:821:32)
    at ReactCompositeComponentWrapper.performInitialMount (/Users/mherold/git/next-web/node_modules/react-dom/lib/ReactCompositeComponent.js:361:30)
    at ReactCompositeComponentWrapper.mountComponent (/Users/mherold/git/next-web/node_modules/react-dom/lib/ReactCompositeComponent.js:257:21)
    at Object.mountComponent (/Users/mherold/git/next-web/node_modules/react-dom/lib/ReactReconciler.js:45:35)
    at ReactDOMComponent.mountChildren (/Users/mherold/git/next-web/node_modules/react-dom/lib/ReactMultiChild.js:236:44)
```

I assume I need to pass something regarding `getPreloadDynamicChunks` correctly through `getInitialProps` in my custom `_document.js`? Should this have a default value in Next's `document.js` to maintain backward compatibility?

Thanks in advance!

Best
Michael

Oh! And here's my custom `_document.js` for reference:

```jsx
import React from 'react';
import Document, { Head, Main, NextScript } from 'next/document';
import flush from 'styled-jsx/server';

/* eslint-disable react/no-danger */

export default class MyDocument extends Document {
  static getInitialProps({ renderPage }) {
    const { html, head } = renderPage();
    const styles = flush();
    return { html, head, styles };
  }

  render() {
    const script = `window.ENV = '${process.env.ENV || 'dev'}';`;
    return (
      <html lang="en">
        <Head>
          <script dangerouslySetInnerHTML={{ __html: script }} />
        </Head>
        <body>
          <Main />
          <NextScript />
        </body>
      </html>
    );
  }
}
```

**Comment by arunoda** [comment]
v3's `getInitialProps` is kind a different. See: https://github.com/zeit/next.js#custom-document

**Comment by mherodev** [comment]
Ah, makes sense! I feel a little mislead by the "fully backward compatible" language in a preview doc, but it also wouldn't be a big version switch without breaking changes.
