### ISSUE TITLE
using-preact example throws an error - react is not installed

### ISSUE THREAD

**Issue by iamsoorena** [zeit/next.js#2442]
I've downloaded using preact example and the I runned "npm install" and then "npm run dev"
this is the error that I've git:
`Error: Cannot find module 'react'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._resolveFilename (C:\PROJECTS\torob\with-preact\using-preact\node_modules\module-alias\index.js:33:29)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\PROJECTS\torob\with-preact\using-preact\node_modules\next\dist\server\render.js:365:14)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)`

**Comment by timneutkens** [comment]
Unfortunately currently react is still included in the bundle. So you'll have to install it. We're tracking this here https://github.com/zeit/next.js/issues/1334

**Comment by vinaypuppal** [comment]
@iamsoorena I think we still need react for dev side because
> Preact doesn't work well with react-hot-loader. And we don't really need preact in the dev mode. 
Arunoda's mentioned [this here](https://github.com/zeit/next.js/pull/767#issue-200807529)

**Comment by timneutkens** [comment]
@vinaypuppal that was actually fixed by Jason.
