### ISSUE TITLE
Heroku build fails, says it can’t find a component that shouldn’t be there

### ISSUE THREAD

**Issue by tomsoderlund** [zeit/next.js#2446]
I've been using Next.js with Heroku for some time, but then I ran into a problem when I deleted a component (`ElementStyleHelper`) that I didn't need anymore. On the next build:

	remote:        Running heroku-postbuild
	remote:        
	remote:        > APPNAME-REDACTED@0.1.0 heroku-postbuild /tmp/build_dac4e00b3ed5a2493d369cdc0a56e5b5
	remote:        > next build
	remote:        
	remote: > Failed to build on /tmp/a13a02a8-a03f-4535-887c-81e215a4cd83
	remote: { Error: ./components/Element.js
	remote: Module not found: Error: Can't resolve './ElementStyleHelper' in '/tmp/build_dac4e00b3ed5a2493d369cdc0a56e5b5/components'
	remote: resolve './ElementStyleHelper' in '/tmp/build_dac4e00b3ed5a2493d369cdc0a56e5b5/components'
	remote:   using description file: /tmp/build_dac4e00b3ed5a2493d369cdc0a56e5b5/package.json (relative path: ./components)
	remote:     Field 'browser' doesn't contain a valid alias configuration
	remote:   after using description file: /tmp/build_dac4e00b3ed5a2493d369cdc0a56e5b5/package.json (relative path: ./components)
	remote:     using description file: /tmp/build_dac4e00b3ed5a2493d369cdc0a56e5b5/package.json (relative path: ./components/ElementStyleHelper)
	remote:       as directory
	remote:         /tmp/build_dac4e00b3ed5a2493d369cdc0a56e5b5/components/ElementStyleHelper doesn't exist
	remote:       no extension
	remote:         Field 'browser' doesn't contain a valid alias configuration
	remote:         /tmp/build_dac4e00b3ed5a2493d369cdc0a56e5b5/components/ElementStyleHelper doesn't exist
	remote:       .js
	remote:         Field 'browser' doesn't contain a valid alias configuration
	remote:         /tmp/build_dac4e00b3ed5a2493d369cdc0a56e5b5/components/ElementStyleHelper.js doesn't exist
	remote:       .json
	remote:         Field 'browser' doesn't contain a valid alias configuration
	remote:         /tmp/build_dac4e00b3ed5a2493d369cdc0a56e5b5/components/ElementStyleHelper.json doesn't exist
	remote: [/tmp/build_dac4e00b3ed5a2493d369cdc0a56e5b5/components/ElementStyleHelper]
	remote: [/tmp/build_dac4e00b3ed5a2493d369cdc0a56e5b5/components/ElementStyleHelper]
	remote: [/tmp/build_dac4e00b3ed5a2493d369cdc0a56e5b5/components/ElementStyleHelper.js]
	remote: [/tmp/build_dac4e00b3ed5a2493d369cdc0a56e5b5/components/ElementStyleHelper.json]
	remote:  @ ./components/Element.js 35:26-57
	remote:  @ ./components/Screen.js
	remote:  @ ./components/Project.js
	remote:  @ ./pages?entry
	remote:  @ multi ./pages?entry
	remote:     at /tmp/build_dac4e00b3ed5a2493d369cdc0a56e5b5/node_modules/next/dist/server/build/index.js:182:21
	remote:     at /tmp/build_dac4e00b3ed5a2493d369cdc0a56e5b5/node_modules/webpack/lib/Compiler.js:272:15
	remote:     at Compiler.emitRecords (/tmp/build_dac4e00b3ed5a2493d369cdc0a56e5b5/node_modules/webpack/lib/Compiler.js:367:37)
	remote:     at /tmp/build_dac4e00b3ed5a2493d369cdc0a56e5b5/node_modules/webpack/lib/Compiler.js:265:12
	remote:     at /tmp/build_dac4e00b3ed5a2493d369cdc0a56e5b5/node_modules/webpack/lib/Compiler.js:360:11
	remote:     at next (/tmp/build_dac4e00b3ed5a2493d369cdc0a56e5b5/node_modules/tapable/lib/Tapable.js:154:11)
	remote:     at Compiler.compiler.plugin (/tmp/build_dac4e00b3ed5a2493d369cdc0a56e5b5/node_modules/webpack/lib/performance/SizeLimitsPlugin.js:99:4)
	remote:     at Compiler.applyPluginsAsyncSeries1 (/tmp/build_dac4e00b3ed5a2493d369cdc0a56e5b5/node_modules/tapable/lib/Tapable.js:158:13)
	remote:     at Compiler.afterEmit (/tmp/build_dac4e00b3ed5a2493d369cdc0a56e5b5/node_modules/webpack/lib/Compiler.js:357:8)
	remote:     at Compiler.<anonymous> (/tmp/build_dac4e00b3ed5a2493d369cdc0a56e5b5/node_modules/webpack/lib/Compiler.js:352:14)
	remote:   errors: [ './components/Element.js\nModule not found: Error: Can\'t resolve \'./ElementStyleHelper\' in \'/tmp/build_dac4e00b3ed5a2493d369cdc0a56e5b5/components\'\nresolve \'./ElementStyleHelper\' in \'/tmp/build_dac4e00b3ed5a2493d369cdc0a56e5b5/components\'\n  using description file: /tmp/build_dac4e00b3ed5a2493d369cdc0a56e5b5/package.json (relative path: ./components)\n    Field \'browser\' doesn\'t contain a valid alias configuration\n  after using description file: /tmp/build_dac4e00b3ed5a2493d369cdc0a56e5b5/package.json (relative path: ./components)\n    using description file: /tmp/build_dac4e00b3ed5a2493d369cdc0a56e5b5/package.json (relative path: ./components/ElementStyleHelper)\n      as directory\n        /tmp/build_dac4e00b3ed5a2493d369cdc0a56e5b5/components/ElementStyleHelper doesn\'t exist\n      no extension\n        Field \'browser\' doesn\'t contain a valid alias configuration\n        /tmp/build_dac4e00b3ed5a2493d369cdc0a56e5b5/components/ElementStyleHelper doesn\'t exist\n      .js\n        Field \'browser\' doesn\'t contain a valid alias configuration\n        /tmp/build_dac4e00b3ed5a2493d369cdc0a56e5b5/components/ElementStyleHelper.js doesn\'t exist\n      .json\n        Field \'browser\' doesn\'t contain a valid alias configuration\n        /tmp/build_dac4e00b3ed5a2493d369cdc0a56e5b5/components/ElementStyleHelper.json doesn\'t exist\n[/tmp/build_dac4e00b3ed5a2493d369cdc0a56e5b5/components/ElementStyleHelper]\n[/tmp/build_dac4e00b3ed5a2493d369cdc0a56e5b5/components/ElementStyleHelper]\n[/tmp/build_dac4e00b3ed5a2493d369cdc0a56e5b5/components/ElementStyleHelper.js]\n[/tmp/build_dac4e00b3ed5a2493d369cdc0a56e5b5/components/ElementStyleHelper.json]\n @ ./components/Element.js 35:26-57\n @ ./components/Screen.js\n @ ./components/Project.js\n @ ./pages?entry\n @ multi ./pages?entry' ],
	remote:   warnings: [] }
	remote: npm ERR! code ELIFECYCLE
	remote: npm ERR! errno 1
	remote: npm ERR! APPNAME-REDACTED@0.1.0 heroku-postbuild: `next build`
	remote: npm ERR! Exit status 1
	remote: npm ERR! 
	remote: npm ERR! Failed at the APPNAME-REDACTED@0.1.0 heroku-postbuild script.
	remote: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
	remote: 
	remote: npm ERR! A complete log of this run can be found in:
	remote: npm ERR!     /app/.npm/_logs/2017-07-02T21_35_43_095Z-debug.log
	remote: 
	remote: -----> Build failed

Why is it complaining over `ElementStyleHelper`? It's not referenced in my code anywhere.

Running `npm run heroku-postbuild` locally works fine.

**Comment by tomsoderlund** [comment]
Should the `.next` folder be in `.gitignore`, or pushed to Heroku?

**Comment by tomsoderlund** [comment]
Sorry, think I solved it - was an incomplete commit with a reference still to `ElementStyleHelper`.
