### ISSUE TITLE
Unable to use scss in my project

### ISSUE THREAD

**Issue by jackmatrix** [zeit/next.js#2496]
I am unable to load my scss stylesheets. 

Yet i configured my custom webpack js file in order to take in account these loaders.

```javascript
var path = require('path');
module.exports = {
  webpack: function (config) {
    var loaders = [
      {test: /\.scss$/, loader: "style-loader!raw-loader!sass-loader?includePaths[]=" + path.resolve(__dirname, "./node_modules/compass-mixins/lib")},
      { test: /\.css$/, loader: "style-loader!css-loader" }
    ]
    config.module.rules.concat(loaders)
    return config
  }
}
```

Then in my browser i get that error 

```
ModuleParseError: Module parse failed: /style.scss Unexpected character '@' (2:0)
You may need an appropriate loader to handle this file type.
| 
| @import 'compass';
| @import "~susy/sass/susy";
| $star : #FF6D00;
    at doBuild.e (/node_modules/next/node_modules/webpack/lib/NormalModule.js:301:19)
    at runLoaders (/node_modules/next/node_modules/webpack/lib/NormalModule.js:207:11)
    at /node_modules/loader-runner/lib/LoaderRunner.js:370:3
    at iterateNormalLoaders (/node_modules/loader-runner/lib/LoaderRunner.js:211:10)
    at /node_modules/loader-runner/lib/LoaderRunner.js:202:4
    at /node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:62:14
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

I've also tried to do this in this way 

```javascript
var path = require('path');
module.exports = {
  webpack: function (config) {
    
    config.module.rules.push({
        test: /\.scss$/,
        loaders: ["style-loader", "css-loader", "sass-loader"],
        include: path.resolve(__dirname,'./node_modules')
      })
    return config
  }
}
```

But that doesn't improve anything

Someone has a idea about what I am doing wrong ?

Thanks

**Comment by timneutkens** [comment]
Please see https://github.com/zeit/next.js/tree/v3-beta/examples/with-global-stylesheet. This outlines how to use scss / any preprocessor.

**Comment by infacq** [comment]
I also have same problem. Try to migrate and still looking this solution

**Comment by jaqua** [comment]
@timneutkens Link is broken

**Comment by timneutkens** [comment]
@jaqua fixed
