### ISSUE TITLE
TypeError: renderPage is not a function

### ISSUE THREAD

**Issue by tangdada** [zeit/next.js#2632]
TypeError: renderPage is not a function
    at Function.getInitialProps (http://localhost:4000/_next/1500888985100/commons.js:23805:25)
    at _callee$ (http://localhost:4000/_next/1500888985100/commons.js:6792:30)
    at tryCatch (http://localhost:4000/_next/1500888985100/commons.js:37520:40)
    at Generator.invoke [as _invoke] (http://localhost:4000/_next/1500888985100/commons.js:37758:22)
    at Generator.prototype.(anonymous function) [as next] (http://localhost:4000/_next/1500888985100/commons.js:37572:21)
    at step (http://localhost:4000/_next/1500888985100/commons.js:4170:30)
    at http://localhost:4000/_next/1500888985100/commons.js:4188:14
    at Promise (<anonymous>)
    at F (http://localhost:4000/_next/1500888985100/commons.js:970:28)
    at http://localhost:4000/_next/1500888985100/commons.js:4167:12

**Comment by arunoda** [comment]
Please provide a proper reproduction.

**Comment by D1no** [comment]
@arunoda  I have the same issue `renderPage is not a function` from `dist/server/document.js:83:25`.

I am using styled components and implemented the server side rendering as per the [example-with-styled-components](https://github.com/zeit/next.js/blob/master/examples/with-styled-components/pages/_document.js) for the static generation of a github page, but neither as build or as dev does it render.

```js
// pages/index.js

import React from "react";
import App from "./components/app";

import { Provider } from "rebass";
import { injectGlobal, ServerStyleSheet } from "styled-components";

import Document, { Head, Main, NextScript } from 'next/document';

// Resetting browser defaults
injectGlobal`
  * { box-sizing: border-box; }
  body { margin: 0 }
`;

// Composing app with theme
export default class LandingPage extends Document {
  render() {
    // Getting CSS Classes & Styles for in-lining as static render.
    const sheet = new ServerStyleSheet();
    const main = sheet.collectStyles(<Main />);
    const styleTags = sheet.getStyleElement();

    return (
      <html>
        <Head>
          <title>Title</title>
          <meta name="viewport" content="initial-scale=1.0, width=device-width" />
          {styleTags}
        </Head>
        <body>
          <div className="root">
            {main}
          </div>
          <NextScript />
        </body>
      </html>
    );
  }
}

```

Error Stack:
```bash
[1]  WAIT  Compiling...13:46:23
[1] 
[1] TypeError: renderPage is not a function
[1]     at Function.getInitialProps (/Users/worker/development/gitmoji/node_modules/next/dist/server/document.js:83:25)
[1]     at _callee$ (/Users/worker/development/gitmoji/node_modules/next/dist/lib/utils.js:36:30)
[1]     at tryCatch (/Users/worker/development/gitmoji/node_modules/regenerator-runtime/runtime.js:65:40)
[1]     at Generator.invoke [as _invoke] (/Users/worker/development/gitmoji/node_modules/regenerator-runtime/runtime.js:303:22)
[1]     at Generator.prototype.(anonymous function) [as next] (/Users/worker/development/gitmoji/node_modules/regenerator-runtime/runtime.js:117:21)
[1]     at step (/Users/worker/development/gitmoji/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
[1]     at /Users/worker/development/gitmoji/node_modules/babel-runtime/helpers/asyncToGenerator.js:35:14
[1]     at Promise (<anonymous>)
[1]     at F (/Users/worker/development/gitmoji/node_modules/core-js/library/modules/_export.js:35:28)
[1]     at /Users/worker/development/gitmoji/node_modules/babel-runtime/helpers/asyncToGenerator.js:14:12
```

```js
// Package.json
  "dependencies": {
    "next": "beta",
    "react": "^15.6.1",
    "react-dom": "^15.6.1",
    "styled-components": "^2.1.0"
  }

```

**Comment by D1no** [comment]
Added a PR... since I spend quite some time to find my problem. Not seeing it was related to the file naming `_document.js` instead of `index.js`. Which absolutely makes sense.
