### ISSUE TITLE
Maximum call stack size exceeded on server-side

### ISSUE THREAD

**Issue by stevefan1999** [zeit/next.js#2666]
```js
RangeError: Maximum call stack size exceeded
    at tryCatch (<REDACTED>/node_modules/regenerator-runtime/runtime.js:63:20)
    at Generator.invoke [as _invoke] (<REDACTED>/node_modules/regenerator-runtime/runtime.js:303:22)
    at Generator.prototype.(anonymous function) [as next] (<REDACTED>/node_modules/regenerator-runtime/runtime.js:117:21)
    at step (<REDACTED>/node_modules/next/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at <REDACTED>/node_modules/next/node_modules/babel-runtime/helpers/asyncToGenerator.js:35:14
    at Promise (<anonymous>)
    at F (<REDACTED>/node_modules/core-js/library/modules/_export.js:35:28)
    at Server.<anonymous> (<REDACTED>/node_modules/next/node_modules/babel-runtime/helpers/asyncToGenerator.js:14:12)
    at Server.render (<REDACTED>/node_modules/next/dist/server/index.js:765:23)
    at Server._callee12$ (<REDACTED>/node_modules/next/dist/server/index.js:583:35)
```
What just happened...
package.json
```json
{
  "dependencies": {
    "next": "latest",
    "prop-types": "^15.5.10",
    "react": "^15.6.1",
    "react-dom": "^15.6.1"
  },
  "scripts": {
    "build": "next build",
    "clean": "rm -rf .next",
    "dev": "node server.js",
    "dev-mon": "nodemon server.js",
    "start": "NODE_ENV=production node server.js"
  },
  "standard": {
    "ignore": [
      "/static/**"
    ],
    "parser": "babel-eslint"
  }
}
```
Production server started with `yarn run build && yarn run start` and when I navigate to the index page the call stack is smashed on server-side

**Comment by stevefan1999** [comment]
Reverted to beta build and I have to remove `add-module-exports` from `.babelrc`, now everything is back to normal
