### ISSUE TITLE
Material UI Next: Changing styles in subcomponents breaks HMR

### ISSUE THREAD

**Issue by sbking** [zeit/next.js#2705]
In the `material-ui-next` example, if you add a subcomponent to the page which uses the `withStyles` HOC, changing any of the style properties breaks HMR.

- [x] I have searched the [issues](https://github.com/zeit/next.js/issues) of this repository and believe that this is not a duplicate.

## Expected Behavior

When changing stylesheet properties in a subcomponent that uses the `withStyles` HOC from Material UI (beta), HMR should work properly.

## Current Behavior

When the page hot reloads due to a style change, this error occurs:

    Cannot read property 'get' of undefined
    TypeError: Cannot read property 'get' of undefined
        at http://localhost:3000/_next/1501726171018/commons.js:49907:49
        at Array.forEach (<anonymous>)
        at ProxyComponent.detach (http://localhost:3000/_next/1501726171018/commons.js:49905:23)
        at ProxyComponent.detach (http://localhost:3000/_next/1501726171018/commons.js:41945:30)
        at ProxyComponent.componentWillUnmount (http://localhost:3000/_next/1501726171018/commons.js:49843:16)
        at ProxyComponent.proxiedComponentWillUnmount (http://localhost:3000/_next/1501726171018/commons.js:41982:43)
        at http://localhost:3000/_next/1501726171018/commons.js:33428:25
        at measureLifeCyclePerf (http://localhost:3000/_next/1501726171018/commons.js:33095:12)
        at ReactCompositeComponentWrapper.unmountComponent (http://localhost:3000/_next/1501726171018/commons.js:33427:11)
        at Object.unmountComponent (http://localhost:3000/_next/1501726171018/commons.js:2501:22)`

This is happening at this line: https://github.com/callemall/material-ui/blob/v1-beta/src/styles/withStyles.js#L173 (`sheetManager` is undefined)

## Steps to Reproduce (for bugs)

1. Download https://github.com/sbking/next.js/tree/material-ui-next-hmr-issue/examples/with-material-ui-next
2. `npm install && npm run dev`
3. Open in browser, see that text is red.
4. Change the color to `blue` in `components/StyledText.js`
5. HMR fails

## Context

Trying to adjust component styles with hot style updates.

## Your Environment

| Tech    | Version |
|---------|---------|
| next    | both latest and 3.0.1-beta.20        |
| node    | 8.2.1        |
| OS      |  OS X (both El Capitan and Sierra)       |
| browser |  Chrome, Firefox, Safari       |

**Comment by sbking** [comment]
Interestingly, if the component is defined within the page file rather than its own module, HMR works as expected.

**Comment by sbking** [comment]
It looks like this issue may have already been addressed in Material UI but hasn't yet been added to a tagged beta release: https://github.com/callemall/material-ui/pull/7601
