### ISSUE TITLE
Development mode with cloud functions

### ISSUE THREAD

**Issue by sarovin** [zeit/next.js#2736]
Hi,
i want use the development mode with the firebase `serve` but i receive an error...
This is a problem with hot reloading??? Any suggestion?

index.js
```javascript

import * as functions from 'firebase-functions';
import cors from 'cors';
import express from 'express';
import next from 'next';

const dev = process.env.NODE_ENV !== 'production';
const nextApp = next({ dev, conf: { distDir: 'next' } });
const handle = nextApp.getRequestHandler();

export let app = functions.https.onRequest(async (req, res) => {
  console.log('DEBUG 1');
  await nextApp.prepare();
  console.log('DEBUG 2');
  return handle(req, res);
});
```

ERROR:

```
i  functions: Preparing to emulate HTTPS functions. Support for other event types coming soon.
Warning: You're using Node.js v7.4.0 but Google Cloud Functions only supports v6.11.1.
Server#addProtoService is deprecated. Use addService instead
i  hosting: Serving hosting files from: build/public
✔  hosting: Local server: http://localhost:3000

✔  functions: app: http://localhost:3001/next-firebase-functions-497a5/us-central1/app
info: User function triggered, starting execution
info: DEBUG 1
info: Execution took 467 ms, finished with status: 'crash'
info: Execution took 60005 ms, finished with status: 'timeout'
Error: Can't set headers after they are sent.
    at ServerResponse.setHeader (_http_outgoing.js:367:11)
    at ServerResponse.header (/Users/pi/.config/yarn/global/node_modules/express/lib/response.js:730:10)
    at ServerResponse.send (/Users/pi/.config/yarn/global/node_modules/express/lib/response.js:170:12)
    at ServerResponse.json (/Users/pi/.config/yarn/global/node_modules/express/lib/response.js:256:15)
    at Timeout.req.functionTimeout.setTimeout [as _onTimeout] (/Users/pi/.config/yarn/global/node_modules/@google-cloud/functions-emulator/src/supervisor/supervisor.js:192:14)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
    at Timer.listOnTimeout (timers.js:207:5)
```

## Your Environment
| Tech    | Version |
|---------|---------|
| next    |    3.0.3     |
| node    |   7.4.0      |

**Comment by timneutkens** [comment]
Every single request would trigger a rebuild, developing on serverless won't work.

**Comment by jackmatrix** [comment]
same problem. How to fix it ?

**Comment by sarovin** [comment]
@jackmatrix see my project => https://github.com/Bolket/next-firebase-functions
