### ISSUE TITLE
example with-amp + with-react-md; npm run build ; npm start ; will get error

### ISSUE THREAD

**Issue by Wolke** [zeit/next.js#2757]
[https://github.com/Wolke/with-react-md-amp](https://github.com/Wolke/with-react-md-amp)
 npm run build ;
 npm start ; 
will get error
Internal Server Error

TypeError: Cannot read property 'map' of undefined
    at Head.getPreloadDynamicChunks (/Users/chienhunglin/Dropbox/demo/next.js/examples/with-react-md-amp/node_modules/next/dist/server/document.js:146:20)
    at Head.render (/Users/chienhunglin/Dropbox/demo/next.js/examples/with-react-md-amp/node_modules/next/dist/server/document.js:174:14)
    at ReactCompositeComponentWrapper._renderValidatedComponentWithoutOwnerOrContext (/Users/chienhunglin/Dropbox/demo/next.js/examples/with-react-md-amp/node_modules/react-dom/lib/ReactCompositeComponent.js:798:30)
    at ReactCompositeComponentWrapper._renderValidatedComponent (/Users/chienhunglin/Dropbox/demo/next.js/examples/with-react-md-amp/node_modules/react-dom/lib/ReactCompositeComponent.js:821:32)
    at ReactCompositeComponentWrapper.performInitialMount (/Users/chienhunglin/Dropbox/demo/next.js/examples/with-react-md-amp/node_modules/react-dom/lib/ReactCompositeComponent.js:361:30)
    at ReactCompositeComponentWrapper.mountComponent (/Users/chienhunglin/Dropbox/demo/next.js/examples/with-react-md-amp/node_modules/react-dom/lib/ReactCompositeComponent.js:257:21)
    at Object.mountComponent (/Users/chienhunglin/Dropbox/demo/next.js/examples/with-react-md-amp/node_modules/react-dom/lib/ReactReconciler.js:45:35)
    at ReactDOMComponent.mountChildren (/Users/chienhunglin/Dropbox/demo/next.js/examples/with-react-md-amp/node_modules/react-dom/lib/ReactMultiChild.js:236:44)
    at ReactDOMComponent._createContentMarkup (/Users/chienhunglin/Dropbox/demo/next.js/examples/with-react-md-amp/node_modules/react-dom/lib/ReactDOMComponent.js:659:32)
    at ReactDOMComponent.mountComponent (/Users/chienhunglin/Dropbox/demo/next.js/examples/with-react-md-amp/node_modules/react-dom/lib/ReactDOMComponent.js:526:29)

**Comment by rickyrauch** [comment]
Same issue here with next 3

**Comment by oleole90** [comment]
Getting same error with **antd** lib.
