### ISSUE TITLE
nextjs/socket.io ::TypeError: Path must be a string. Received IncomingMessage

### ISSUE THREAD

**Issue by vaheqelyan** [zeit/next.js#2765]
Hi guys.I'm working with socket.io, but I got this error message for the route of /about

> TypeError: Path must be a string. Received IncomingMessage
 at assertPath (path.js:7:11)
    at extname (path.js:887:5)
    at new View (C:\Users\Admin\Desktop\rinterest\node_modules\express\lib\view.js:57:14)
    at Function.render (C:\Users\Admin\Desktop\rinterest\node_modules\express\lib\application.js:570:12)
    at app.get (C:\Users\Admin\Desktop\rinterest\server.js:47:20)
    at Layer.handle [as handle_request] (C:\Users\Admin\Desktop\rinterest\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\Users\Admin\Desktop\rinterest\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (C:\Users\Admin\Desktop\rinterest\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (C:\Users\Admin\Desktop\rinterest\node_modules\express\lib\router\layer.js:95:5)
    at C:\Users\Admin\Desktop\rinterest\node_modules\express\lib\router\index.js:281:22

Here is my file server

```javascript
const path = require("path");
const app = require("express")();
const bodyParser = require("body-parser");
const session = require("express-session");

app.use(
     bodyParser.urlencoded({
          extended: true
     })
);

app.use(bodyParser.json());

app.use(
     session({
          secret: "change-me",
          resave: false,
          rolling: true,
          saveUninitialized: true,
          httpOnly: true,
          cookie: {
               maxAge: 60000 * 60 * 24 * 7 * 4
          }
     })
);

const server = require("http").Server(app);
const io = require("socket.io")(server);
const next = require("next");

const dev = process.env.NODE_ENV !== "production";
const nextApp = next({ dev });
const nextHandler = nextApp.getRequestHandler();

nextApp.prepare().then(() => {
     app.get("/about", (req, res) => {
          return app.render(req, res, "/about", req.params);
     });
     app.get("*", (req, res) => {
          return nextHandler(req, res);
     });

     server.listen(80, err => {
          if (err) throw err;
          console.log("> Ready on http://localhost");
     });
});

```

And here is my page pages/about.js

```javascript
import React from "react";

export default class About extends React.Component {
     render() {
          return <div>/about</div>;
     }
}
```
very simple isn't it.i guess it is not a big problem and the issue will be closed quickly.thanks in advance!

**Comment by timneutkens** [comment]
Are you using https://github.com/zeit/next.js/tree/master/examples/with-socket.io?

**Comment by vaheqelyan** [comment]
@timneutkens yes

**Comment by timneutkens** [comment]
`return app.render(req, res, "/about", req.params);` should be `return nextApp.render(req, res, "/about", req.params);`
