### ISSUE TITLE
[next.config.js] Build fails if the distDir is outside of the next.js project (../).

### ISSUE THREAD

**Issue by D1no** [zeit/next.js#2769]
- [x] I have searched the [issues](https://github.com/zeit/next.js/issues) of this repository and believe that this is not a duplicate.

## Expected Behavior
Should build.

## Current Behavior
Build fails.
```bash
DONE  Compiled successfully in 97ms22:04:14
[1]
[1] { Error: Cannot find module 'rebass'
[1]     at Function.Module._resolveFilename (module.js:485:15)
[1]     at Function.Module._load (module.js:437:25)
[1]     at Module.require (module.js:513:17)
[1]     at require (internal/module.js:11:18)
[1]     at Object.<anonymous> (/Users/worker/development/project/_system/__build__/next/dist/pages/index.js:4:806)
[1]     at Module._compile (module.js:569:30)
[1]     at Object.Module._extensions..js (module.js:580:10)
[1]     at Module.load (module.js:503:32)
[1]     at tryModuleLoad (module.js:466:12)
[1]     at Function.Module._load (module.js:458:3) code: 'MODULE_NOT_FOUND' }
[1] { Error: Cannot find module 'styled-components'
[1]     at Function.Module._resolveFilename (module.js:485:15)
[1]     at Function.Module._load (module.js:437:25)
[1]     at Module.require (module.js:513:17)
[1]     at require (internal/module.js:11:18)
[1]     at Object.<anonymous> (/Users/worker/development/project/_system/__build__/next/dist/pages/_document.js:11:275)
[1]     at Module._compile (module.js:569:30)
[1]     at Object.Module._extensions..js (module.js:580:10)
[1]     at Module.load (module.js:503:32)
[1]     at tryModuleLoad (module.js:466:12)
[1]     at Function.Module._load (module.js:458:3) code: 'MODULE_NOT_FOUND' }
[1] { Error: Cannot find module 'styled-components'
[1]     at Function.Module._resolveFilename (module.js:485:15)
[1]     at Function.Module._load (module.js:437:25)
[1]     at Module.require (module.js:513:17)
[1]     at require (internal/module.js:11:18)
[1]     at Object.<anonymous> (/Users/worker/development/project/_system/__build__/next/dist/pages/_document.js:11:275)
[1]     at Module._compile (module.js:569:30)
[1]     at Object.Module._extensions..js (module.js:580:10)
[1]     at Module.load (module.js:503:32)
[1]     at tryModuleLoad (module.js:466:12)
[1]     at Function.Module._load (module.js:458:3) code: 'MODULE_NOT_FOUND' }
[1] { Error: Cannot find module 'styled-components'
[1]     at Function.Module._resolveFilename (module.js:485:15)
[1]     at Function.Module._load (module.js:437:25)
[1]     at Module.require (module.js:513:17)
[1]     at require (internal/module.js:11:18)
[1]     at Object.<anonymous> (/Users/worker/development/project/_system/__build__/next/dist/pages/_document.js:11:275)
[1]     at Module._compile (module.js:569:30)
[1]     at Object.Module._extensions..js (module.js:580:10)
[1]     at Module.load (module.js:503:32)
[1]     at tryModuleLoad (module.js:466:12)
[1]     at Function.Module._load (module.js:458:3) code: 'MODULE_NOT_FOUND' }
[1] { Error: Cannot find module 'styled-components'
[1]     at Function.Module._resolveFilename (module.js:485:15)
[1]     at Function.Module._load (module.js:437:25)
[1]     at Module.require (module.js:513:17)
[1]     at require (internal/module.js:11:18)
[1]     at Object.<anonymous> (/Users/worker/development/project/_system/__build__/next/dist/pages/_document.js:11:275)
[1]     at Module._compile (module.js:569:30)
[1]     at Object.Module._extensions..js (module.js:580:10)
[1]     at Module.load (module.js:503:32)
[1]     at tryModuleLoad (module.js:466:12)
[1]     at Function.Module._load (module.js:458:3) code: 'MODULE_NOT_FOUND' }
[1] { Error: Cannot find module 'rebass'
[1]     at Function.Module._resolveFilename (module.js:485:15)
[1]     at Function.Module._load (module.js:437:25)
[1]     at Module.require (module.js:513:17)
[1]     at require (internal/module.js:11:18)
[1]     at Object.<anonymous> (/Users/worker/development/project/_system/__build__/next/dist/pages/index.js:4:806)
[1]     at Module._compile (module.js:569:30)
[1]     at Object.Module._extensions..js (module.js:580:10)
[1]     at Module.load (module.js:503:32)
[1]     at tryModuleLoad (module.js:466:12)
[1]     at Function.Module._load (module.js:458:3) code: 'MODULE_NOT_FOUND' }
[1] { Error: Cannot find module 'styled-components'
[1]     at Function.Module._resolveFilename (module.js:485:15)
[1]     at Function.Module._load (module.js:437:25)
[1]     at Module.require (module.js:513:17)
[1]     at require (internal/module.js:11:18)
[1]     at Object.<anonymous> (/Users/worker/development/project/_system/__build__/next/dist/pages/_document.js:11:275)
[1]     at Module._compile (module.js:569:30)
[1]     at Object.Module._extensions..js (module.js:580:10)
[1]     at Module.load (module.js:503:32)
[1]     at tryModuleLoad (module.js:466:12)
[1]     at Function.Module._load (module.js:458:3) code: 'MODULE_NOT_FOUND' }
[1] { Error: Cannot find module 'styled-components'
[1]     at Function.Module._resolveFilename (module.js:485:15)
[1]     at Function.Module._load (module.js:437:25)
[1]     at Module.require (module.js:513:17)
[1]     at require (internal/module.js:11:18)
[1]     at Object.<anonymous> (/Users/worker/development/project/_system/__build__/next/dist/pages/_document.js:11:275)
[1]     at Module._compile (module.js:569:30)
[1]     at Object.Module._extensions..js (module.js:580:10)
[1]     at Module.load (module.js:503:32)
[1]     at tryModuleLoad (module.js:466:12)
[1]     at Function.Module._load (module.js:458:3) code: 'MODULE_NOT_FOUND' }
[1] { Error: Cannot find module 'styled-components'
[1]     at Function.Module._resolveFilename (module.js:485:15)
[1]     at Function.Module._load (module.js:437:25)
[1]     at Module.require (module.js:513:17)
[1]     at require (internal/module.js:11:18)
[1]     at Object.<anonymous> (/Users/worker/development/project/_system/__build__/next/dist/pages/_document.js:11:275)
[1]     at Module._compile (module.js:569:30)
[1]     at Object.Module._extensions..js (module.js:580:10)
[1]     at Module.load (module.js:503:32)
[1]     at tryModuleLoad (module.js:466:12)
[1]     at Function.Module._load (module.js:458:3) code: 'MODULE_NOT_FOUND' }
[1] { Error: Cannot find module 'styled-components'
[1]     at Function.Module._resolveFilename (module.js:485:15)
[1]     at Function.Module._load (module.js:437:25)
[1]     at Module.require (module.js:513:17)
[1]     at require (internal/module.js:11:18)
[1]     at Object.<anonymous> (/Users/worker/development/project/_system/__build__/next/dist/pages/_document.js:11:275)
[1]     at Module._compile (module.js:569:30)
[1]     at Object.Module._extensions..js (module.js:580:10)
[1]     at Module.load (module.js:503:32)
[1]     at tryModuleLoad (module.js:466:12)
[1]     at Function.Module._load (module.js:458:3) code: 'MODULE_NOT_FOUND' }
```

## Steps to Reproduce (for bugs)
Set the outDir to a folder outside of the next.js project. 
```js
module.exports = {
  // the next.js project lives in _web. All deploys go into _system. So we go one folder up.
  distDir: '../_system/__build__/next'
}
```

## Context
Quite typical for a mono repository where all the resources are gathered in one public folder for deploy.

## Your Environment
| Tech    | Version |
|---------|---------|
| next    | beta |
| node    | 8.2.1 |
| OS      |  Mac Sierra |

**Comment by arunoda** [comment]
This is a kind of a requirement.

**Comment by D1no** [comment]
I am not sure why that is, but maybe it should go into the docs/code (in case I just missed it).
