### ISSUE TITLE
Use node-sass (SCSS) in NEXT.JS

### ISSUE THREAD

**Issue by thinnakrit** [zeit/next.js#2772]
**# How to use SCSS in NEXT.js**

Today i want to use scss for creating new my website

1. Install dependencies below
```
npm i -s css-loader extract-text-webpack-plugin node-sass sass-loader style-loader url-loader webpack
```
Yes ! i use webpack for generate file.

2. Open / Create file name ```next.config.js``` and wraite code below
```javascript
const webpack = require('webpack')
const ExtractTextPlugin = require('extract-text-webpack-plugin')
module.exports = {
  distDir: 'build',
  webpack: (config, { dev }) => {
    config.module.rules.push({
      test: /\.css$/,
      loader: 'emit-file-loader',
      options: {
        name: 'dist/[path][name].[ext]'
      }
    });
    if (!dev) {
      config.module.rules.push({
        test: /\.css$/,
        use: ExtractTextPlugin.extract({
          use: [
            {
              loader: 'css-loader',
              options: {
                importLoaders: 2,
                modules: false,
                url: true,
                sourceMap: false,
                minimize: true,
                localIdentName: false
                  ? '[name]-[local]-[hash:base64:5]'
                  : '[hash:base64:5]'
              }
            },
            { loader: 'postcss-loader' }
          ]
        })
      });

      config.module.rules.push({
        test: /\.scss$/,
        use: ExtractTextPlugin.extract({
            fallback: 'style-loader',
            use: [
                {
                    loader: 'css-loader'
                },
                {
                    loader: 'sass-loader',
                    options: {
                        sourceMap: true
                    }
                }
            ]
        })
      });

      config.plugins.push(new ExtractTextPlugin('app.css'));
    } else {
      config.module.rules.push({
        test: /\.css$/,
        use: [{ loader: 'raw-loader' }, { loader: 'postcss-loader' }]
      });
    }
    return config;
  }
}
```
3. Create folder and file for using, now i create ```./static/css/style.scss```
4. Open ```./pages/_document.js``` and add code below
```javascript
import '../static/css/style.scss'
```

I have a bug this on my production
```
{ Error: Cannot find module '../static/css/style.scss'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
```

| Tech    | Version |
|---------|---------|
| next    |     3    |
| node    |     8    |
| OS      |     MacOS Sierra    |
| browser |   Chrome      |
| etc     |         |

**Comment by timneutkens** [comment]
Please see https://github.com/zeit/next.js#faq there are multiple ways to use scss 👍

**Comment by thinnakrit** [comment]
thank you <3
