### ISSUE TITLE
styles.createStyleSheet is not a function

### ISSUE THREAD

**Issue by psyrotix** [zeit/next.js#2796]
Getting this error after running npm install then npm run dev. 
node v 7.9 
next v 3.0.6
mac OS Sierra 10.12.6

This is a with material-ui-next from the examples folder.

```
TypeError: (0 , _styles.createStyleSheet) is not a function
    at Object.<anonymous> (/Users/Parth/Documents/with-material-ui-next/.next/dist/components/withRoot.js:47:47)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/Parth/Documents/with-material-ui-next/.next/dist/pages/index.js:43:17)
    at Module._compile (module.js:571:32)
```

**Comment by michaelfriedman** [comment]
Was there a solution to this? I'm encountering the same.

**Comment by psyrotix** [comment]
Yes the solution was to change the function that starts at line 6 in withRoot.js to this function 

`// Apply some reset
const styleSheet = theme => ({
  '@global': {
    html: {
      background: theme.palette.background.default,
      WebkitFontSmoothing: 'antialiased', // Antialiasing.
      MozOsxFontSmoothing: 'grayscale' // Antialiasing.
    },
    body: {
      margin: 0
    }
  }
})`

And also remove the import for createStyleSheet
