### ISSUE TITLE
Error running in Windows 10 - You may need an appropriate loader to handle this file type.

### ISSUE THREAD

**Issue by cellanda** [zeit/next.js#2822]
I have encountered a pretty basic bug in next.js on Windows 10. It may well be an issue in one of the dependencies.

versions:
next: 3.0.6
node: 6.11.2
npm: 5.3.0
react: 15.6.1
react-dom: 15.6.1
OS; Windows 10 pro v1511 build 10586.1045

Steps
1. On Windows 10
2. with a clean clone of the repo.
3. follow the setup notes in the readme
4. npm run dev

This produced the following output on the web page:

Error in Z:\terry\Stuff\Development\Software\GitHub\cellanda\quiz\pages\index.js?entry
Module parse failed: y:\terry\Stuff\Development\Software\GitHub\cellanda\quiz\node_modules\react-hot-loader\webpack.js!y:\terry\Stuff\Development\Software\GitHub\cellanda\quiz\pages\index.js?entry Unexpected token (2:2) You may need an appropriate loader to handle this file type. | export default () => ( | <div>Welcome to next.js!</div> | ) |
ModuleParseError: Module parse failed: y:\terry\Stuff\Development\Software\GitHub\cellanda\quiz\node_modules\react-hot-loader\webpack.js!y:\terry\Stuff\Development\Software\GitHub\cellanda\quiz\pages\index.js?entry Unexpected token (2:2)
You may need an appropriate loader to handle this file type.
| export default () => (
|   <div>Welcome to next.js!</div>
| )
| 
    at doBuild.e (y:\terry\Stuff\Development\Software\GitHub\cellanda\quiz\node_modules\webpack\lib\NormalModule.js:302:19)
    at runLoaders (y:\terry\Stuff\Development\Software\GitHub\cellanda\quiz\node_modules\webpack\lib\NormalModule.js:208:11)
    at y:\terry\Stuff\Development\Software\GitHub\cellanda\quiz\node_modules\loader-runner\lib\LoaderRunner.js:370:3
    at iterateNormalLoaders (y:\terry\Stuff\Development\Software\GitHub\cellanda\quiz\node_modules\loader-runner\lib\LoaderRunner.js:211:10)
    at iterateNormalLoaders (y:\terry\Stuff\Development\Software\GitHub\cellanda\quiz\node_modules\loader-runner\lib\LoaderRunner.js:218:10)
    at y:\terry\Stuff\Development\Software\GitHub\cellanda\quiz\node_modules\loader-runner\lib\LoaderRunner.js:233:3
    at Object.context.callback (y:\terry\Stuff\Development\Software\GitHub\cellanda\quiz\node_modules\loader-runner\lib\LoaderRunner.js:111:13)
    at Object.transform (y:\terry\Stuff\Development\Software\GitHub\cellanda\quiz\node_modules\react-hot-loader\lib\webpack\index.js:48:15)
    at LOADER_EXECUTION (y:\terry\Stuff\Development\Software\GitHub\cellanda\quiz\node_modules\loader-runner\lib\LoaderRunner.js:119:14)
    at runSyncOrAsync (y:\terry\Stuff\Development\Software\GitHub\cellanda\quiz\node_modules\loader-runner\lib\LoaderRunner.js:120:4)

**Comment by eezing** [comment]
@cellanda Can you clarify what repo in "2. with a clean clone of the repo."?
