### ISSUE TITLE
Get error for newbie with nextjs?

### ISSUE THREAD

**Issue by thearabbit** [zeit/next.js#284]
I base on `Meteor JS`, but now I want to try `Next`.
Get error for the first
```js
Error in ./pages/index.js
Module build failed: Error: Couldn't find preset "es2015" relative to directory "/Users/theara/Desktop/nextjs/pages"
    at /Users/theara/Desktop/nextjs/node_modules/next/node_modules/babel-core/lib/transformation/file/options/option-manager.js:298:19
    at Array.map (native)
    at OptionManager.resolvePresets (/Users/theara/Desktop/nextjs/node_modules/next/node_modules/babel-core/lib/transformation/file/options/option-manager.js:269:20)
    at OptionManager.mergePresets (/Users/theara/Desktop/nextjs/node_modules/next/node_modules/babel-core/lib/transformation/file/options/option-manager.js:258:10)
    at OptionManager.mergeOptions (/Users/theara/Desktop/nextjs/node_modules/next/node_modules/babel-core/lib/transformation/file/options/option-manager.js:243:14)
    at OptionManager.init (/Users/theara/Desktop/nextjs/node_modules/next/node_modules/babel-core/lib/transformation/file/options/option-manager.js:373:12)
    at File.initOptions (/Users/theara/Desktop/nextjs/node_modules/next/node_modules/babel-core/lib/transformation/file/index.js:221:65)
    at new File (/Users/theara/Desktop/nextjs/node_modules/next/node_modules/babel-core/lib/transformation/file/index.js:141:24)
    at Pipeline.transform (/Users/theara/Desktop/nextjs/node_modules/next/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at transpile (/Users/theara/Desktop/nextjs/node_modules/next/node_modules/babel-loader/index.js:38:20)
```

**Comment by fdidron** [comment]
@thearabbit Can you commit your project somewhere ? Seems like ou have a conflicting babel setting.

**Comment by thearabbit** [comment]
Thanks for your reply, this my testing repo https://github.com/thearabbit/nextjs

**Comment by fdidron** [comment]
@thearabbit Looking at your package.json file, it seems nextjs is not added as a dependency, you should run `npm install next --save`.
Also can you confirm which node version you are running ?

**Comment by thearabbit** [comment]
I do this through `readme`
```js
// create pro folder and then
$ npm install next --save
// and add a script to your package.json like this:
{
  "scripts": {
    "dev": "next"
  }
}
```
not clear `how to install`.
Now I tried to install `next`, but still don't work.
Please help me.

**Comment by thearabbit** [comment]
I base on node `v4.5.0`.

**Comment by jonaswindey** [comment]
Try upgrading to latest node, v4 is still using npm version 2, which I'm not sure is supported.

**Comment by arunoda** [comment]
Yep. That's an issue with NPM2.
For an quick fix, try upgrading into latest node or install npm@3 or use Yarn.

**Comment by thearabbit** [comment]
Work fine after upgrade to `node lastest`.
Thanks @arunoda, you are my idol.
I try `next js` after your post [Arunoda: Leaving the Meteor Community](https://forums.meteor.com/t/arunoda-leaving-the-meteor-community/31568)
Miss you on `Meteor`.
but now I don't clear that `next js` is full and easy like `meteor`?
