### ISSUE TITLE
Unexpected token function at getInitialProps

### ISSUE THREAD

**Issue by huxinmin** [zeit/next.js#2934]
- [x] I have searched the [issues](https://github.com/zeit/next.js/issues) of this repository and believe that this is not a duplicate.

## Current Behavior

`Unexpected token function
G:\huxinmin.github.io\nextJs\.next\dist\pages\index.js:65
    value: async function getInitialProps() {
                 ^^^^^^^^
SyntaxError: Unexpected token function
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:542:28)
    at Module._compile (G:\huxinmin.github.io\nextJs\node_modules\_source-map-support@0.4.15@source-map-support\source-map-support.js:483:25)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at _callee$ (G:\huxinmin.github.io\nextJs\node_modules\_next@3.2.2@next\dist\server\require.js:33:46)`

## Steps to Reproduce (for bugs)

1. clone data-fetch example and npm install and npm run dev
2. see 127.0.0.1:3000 in browser 
3. the package.json is `{
  "name": "nextJs",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "dev": "next",
    "build": "next build",
    "start": "next start"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "isomorphic-fetch": "^2.2.1",
    "next": "latest",
    "react": "^15.4.2",
    "react-dom": "^15.4.2"
  }
}
`
4.

## Context

I did all same as the example told but can not successful , I was very sad and ask for help

## Your Environment

| Tech    | Version |
|---------|---------|
| next    |      3.2.2   |
| node    |    6.10. 0    |
| OS      |    windows     |
| browser |    chrome    |
| etc     |         |

**Comment by timneutkens** [comment]
I guess you have created a `.babelrc` and forgot to include `next/babel` preset 👍
