### ISSUE TITLE
JSON files can't be imported on server

### ISSUE THREAD

**Issue by nkzawa** [zeit/next.js#296]
```js
import data from '../data.json'
console.log(data)
```

This doesn't work on server. It seems we have to copy `.json` files to `.next/dist` directory.

**Comment by elsigh** [comment]
Something related to this - I am trying to do the same thing with a `secrets.json` file (on the latest version of nextjs `"next": "^5.1.0"`.

It works fine on my local server, and running `yarn build` succeeds locally.

When I deploy with `now` I get:

```
> next build
> Failed to build
> { Error: (client) ./components/Page.js
> Module not found: Error: Can't resolve './secrets.json' in '/home/nowuser/src/components'
> resolve './secrets.json' in '/home/nowuser/src/components'
>   using description file: /home/nowuser/src/package.json (relative path: ./components)
>     Field 'browser' doesn't contain a valid alias configuration
>   after using description file: /home/nowuser/src/package.json (relative path: ./components)
>     using description file: /home/nowuser/src/package.json (relative path: ./components/secrets.json)
>       no extension
>         Field 'browser' doesn't contain a valid alias configuration
>         /home/nowuser/src/components/secrets.json doesn't exist
>       .js
>         Field 'browser' doesn't contain a valid alias configuration
>         /home/nowuser/src/components/secrets.json.js doesn't exist
>       .jsx
>         Field 'browser' doesn't contain a valid alias configuration
>         /home/nowuser/src/components/secrets.json.jsx doesn't exist
>       .json
>         Field 'browser' doesn't contain a valid alias configuration
>         /home/nowuser/src/components/secrets.json.json doesn't exist
>       as directory
>         /home/nowuser/src/components/secrets.json doesn't exist
> [/home/nowuser/src/components/secrets.json]
> [/home/nowuser/src/components/secrets.json.js]
> [/home/nowuser/src/components/secrets.json.jsx]
> [/home/nowuser/src/components/secrets.json.json]
> [/home/nowuser/src/components/secrets.json]
>  @ ./components/Page.js 2:0-37
>  @ ./pages/authreceiver.js
>  @ multi ./pages/authreceiver.js
>     at /home/nowuser/src/node_modules/next/dist/server/build/index.js:207:31
>     at runWithDependencies (/home/nowuser/src/node_modules/webpack/lib/MultiCompiler.js:154:4)
>     at /home/nowuser/src/node_modules/async/dist/async.js:1126:9
>     at /home/nowuser/src/node_modules/async/dist/async.js:473:16
>     at iteratorCallback (/home/nowuser/src/node_modules/async/dist/async.js:1050:13)
>     at /home/nowuser/src/node_modules/async/dist/async.js:958:16
>     at /home/nowuser/src/node_modules/async/dist/async.js:1123:13
>     at runCompilers (/home/nowuser/src/node_modules/webpack/lib/MultiCompiler.js:96:47)
>     at fn (/home/nowuser/src/node_modules/webpack/lib/MultiCompiler.js:101:6)
>     at compiler.run (/home/nowuser/src/node_modules/webpack/lib/MultiCompiler.js:150:5)
>     at emitRecords.err (/home/nowuser/src/node_modules/webpack/lib/Compiler.js:265:13)
>     at Compiler.emitRecords (/home/nowuser/src/node_modules/webpack/lib/Compiler.js:371:38)
>     at emitAssets.err (/home/nowuser/src/node_modules/webpack/lib/Compiler.js:258:10)
>     at applyPluginsAsyncSeries1.err (/home/nowuser/src/node_modules/webpack/lib/Compiler.js:364:12)
>     at next (/home/nowuser/src/node_modules/tapable/lib/Tapable.js:218:11)
>     at Compiler.compiler.plugin (/home/nowuser/src/node_modules/webpack/lib/performance/SizeLimitsPlugin.js:99:4)
>   errors:
>    [ '(client) ./components/Page.js\nModule not found: Error: Can\'t resolve \'./secrets.json\' in \'/home/nowuser/src/components\'\nresolve \'./secrets.json\' in \'/home/nowuser/src/components\'\n  using description file: /home/nowuser/src/package.json (relative path: ./components)\n    Field \'browser\' doesn\'t contain a valid alias configuration\n  after using description file: /home/nowuser/src/package.json (relative path: ./components)\n    using description file: /home/nowuser/src/package.json (relative path: ./components/secrets.json)\n      no extension\n        Field \'browser\' doesn\'t contain a valid alias configuration\n        /home/nowuser/src/components/secrets.json doesn\'t exist\n      .js\n        Field \'browser\' doesn\'t contain a valid alias configuration\n        /home/nowuser/src/components/secrets.json.js doesn\'t exist\n      .jsx\n        Field \'browser\' doesn\'t contain a valid alias configuration\n        /home/nowuser/src/components/secrets.json.jsx doesn\'t exist\n      .json\n        Field \'browser\' doesn\'t contain a valid alias configuration\n        /home/nowuser/src/components/secrets.json.json doesn\'t exist\n      as directory\n        /home/nowuser/src/components/secrets.json doesn\'t exist\n[/home/nowuser/src/components/secrets.json]\n[/home/nowuser/src/components/secrets.json.js]\n[/home/nowuser/src/components/secrets.json.jsx]\n[/home/nowuser/src/components/secrets.json.json]\n[/home/nowuser/src/components/secrets.json]\n @ ./components/Page.js 2:0-37\n @ ./pages/authreceiver.js\n @ multi ./pages/authreceiver.js',
>      '(server) ./components/Page.js\nModule not found: Error: Can\'t resolve \'./secrets.json\' in \'/home/nowuser/src/components\'\nresolve \'./secrets.json\' in \'/home/nowuser/src/components\'\n  using description file: /home/nowuser/src/package.json (relative path: ./components)\n  after using description file: /home/nowuser/src/package.json (relative path: ./components)\n    using description file: /home/nowuser/src/package.json (relative path: ./components/secrets.json)\n      no extension\n        /home/nowuser/src/components/secrets.json doesn\'t exist\n      .js\n        /home/nowuser/src/components/secrets.json.js doesn\'t exist\n      .jsx\n        /home/nowuser/src/components/secrets.json.jsx doesn\'t exist\n      .json\n        /home/nowuser/src/components/secrets.json.json doesn\'t exist\n      as directory\n        /home/nowuser/src/components/secrets.json doesn\'t exist\n[/home/nowuser/src/components/secrets.json]\n[/home/nowuser/src/components/secrets.json.js]\n[/home/nowuser/src/components/secrets.json.jsx]\n[/home/nowuser/src/components/secrets.json.json]\n[/home/nowuser/src/components/secrets.json]\n @ ./components/Page.js 2:0-37\n @ ./pages/authreceiver.js\n @ multi ./pages/authreceiver.js' ],
>   warnings: [] }
```

**Comment by elsigh** [comment]
I tried a variety of changes like moving my json file into the components dir and importing it via `./secrets.json` and no dice. 

Seems like a webpack thing?

**Comment by elsigh** [comment]
I also tried `const secrets = require("./../secrets.json");` which works locally, but fails when running `now` in the same way.

**Comment by csantiago132** [comment]
@elsigh how are you importing the file? im using webpack 4 and this became an issue, my workaround is  
 - use a `file-loader` 
 - rename the json extension to something else, `myfile.notajson` 
 - In the file-loader, change the `[ext]` to `.json.` tied together, this would look like

```js
import '!file-loader?name=[name].json!./myfile.notajson';
```

**Comment by elsigh** [comment]
@csantiago132 what do you mean by "how are you importing the file"? I think I listed trying both `import` and `require`

I'm also going to try turning my file into a simple js file that exports an object.

**Comment by csantiago132** [comment]
@elsigh sorry I didnt write it the right way, what I meant is in what context/how are you using the file? By itself?  as part of a module? anyways, what I posted above worked for me, just trying to help

**Comment by elsigh** [comment]
zomg, it looks like it's not working because I have `secrets.json` in my `.gitignore`. I think I'll open a new issue for this.

**Comment by csantiago132** [comment]
ok hope it gets fixed @elsigh
