### ISSUE TITLE
React-i18n in Production

### ISSUE THREAD

**Issue by PMiraLopes** [zeit/next.js#2965]
React-i18n in Production

## Expected Behavior

I'm struggling with a very strange bug on running the react-i18next with nextJS, it works perfectly on dev, but when I run it on production mode it crashes. The strange thing is that I created the configs based on the examples that are provided here, but it doesn't work on production mode, as doesn't find react under the i18n options object.

## Current Behavior

On production I get this error the front-end

app.js:78 Cannot read property 'react' of undefined
TypeError: Cannot read property 'react' of undefined
    at new l (http://localhost:3000/_next/65dbc4ba-ad42-4d43-b7bc-3bc411c9d184/page/:3:1740)
    at d._constructComponentWithoutOwner (http://localhost:3000/_next/2ff3a5285f98c6920205133b0780e5fc/app.js:35:341292)
    at d._constructComponent (http://localhost:3000/_next/2ff3a5285f98c6920205133b0780e5fc/app.js:35:341159)
    at d.mountComponent (http://localhost:3000/_next/2ff3a5285f98c6920205133b0780e5fc/app.js:35:340341)
    at Object.mountComponent (http://localhost:3000/_next/2ff3a5285f98c6920205133b0780e5fc/app.js:7:67596)
    at d.performInitialMount (http://localhost:3000/_next/2ff3a5285f98c6920205133b0780e5fc/app.js:35:342114)
    at d.mountComponent (http://localhost:3000/_next/2ff3a5285f98c6920205133b0780e5fc/app.js:35:341000)
    at Object.mountComponent (http://localhost:3000/_next/2ff3a5285f98c6920205133b0780e5fc/app.js:7:67596)
    at mountChildren (http://localhost:3000/_next/2ff3a5285f98c6920205133b0780e5fc/app.js:35:336860)
    at m._createContentMarkup (http://localhost:3000/_next/2ff3a5285f98c6920205133b0780e5fc/app.js:35:325835)

## Steps to Reproduce (for bugs)

1.next build
2.npm start

## Your Environment

| Tech    | Version |
|---------|---------|
| next    |^3.0.1-beta.18|
| OS      | MAC OS |
| browser | Chrome |

**Comment by malikimprowised** [comment]
I am also getting the same issue. 
Version
next.js =>  3.2.2
react =>  15.6.1

**Comment by pedrovagner** [comment]
I thought my app is crashing because of `react-i18n`, but a just find out my error is in `moment.js`.
