### ISSUE TITLE
Cannot push to heroku 

### ISSUE THREAD

**Issue by esharmony** [zeit/next.js#3002]
Everything built fine locally and on Now, but I have sensitive information I want to remain private and at this point I don't need a pro plan so I tried to push to Heroku. I have search on here for the answer it seems as if it cannot resolve the components paths, I have tried many of the solutions that looked similar to my issue but nothing has worked - error and package.json below and any help most appreciated. 

```
$ git push heroku master
Counting objects: 86, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (85/85), done.
Writing objects: 100% (86/86), 8.55 KiB | 1.42 MiB/s, done.
Total 86 (delta 52), reused 1 (delta 0)
remote: Compressing source files... done.
remote: Building source:
remote: 
remote: -----> Node.js app detected
remote: 
remote: -----> Creating runtime environment
remote:        
remote:        NPM_CONFIG_LOGLEVEL=error
remote:        NPM_CONFIG_PRODUCTION=true
remote:        NODE_VERBOSE=false
remote:        NODE_ENV=production
remote:        NODE_MODULES_CACHE=true
remote: 
remote: -----> Installing binaries
remote:        engines.node (package.json):  unspecified
remote:        engines.npm (package.json):   unspecified (use default)
remote:        
remote:        Resolving node version 6.x...
remote:        Downloading and installing node 6.11.3...
remote:        Detected package-lock.json: defaulting npm to version 5.x.x
remote:        Bootstrapping npm 5.x.x (replacing 3.10.10)...
remote:        npm 5.4.2 installed
remote: 
remote: -----> Restoring cache
remote:        Loading 2 from cacheDirectories (default):
remote:        - node_modules
remote:        - bower_components (not cached - skipping)
remote: 
remote: -----> Building dependencies
remote:        Installing node modules (package.json + package-lock)
remote:        added 116 packages and removed 1 package in 11.622s
remote:        Running heroku-postbuild
remote:        
remote:        > next-authenticate@1.0.0 heroku-postbuild /tmp/build_30fc7bd58001466be08fc9fc142a91ed
remote:        > npm run build
remote:        
remote:        
remote:        > next-authenticate@1.0.0 build /tmp/build_30fc7bd58001466be08fc9fc142a91ed
remote:        > next build
remote:        
remote: > Failed to build on /tmp/057b6abc-1779-476a-95ae-d6c4e832c9ef
remote: { Error: ./components/layout.js
remote: Module not found: Error: Can't resolve '../components/head' in '/tmp/build_30fc7bd58001466be08fc9fc142a91ed/components'
remote: resolve '../components/head' in '/tmp/build_30fc7bd58001466be08fc9fc142a91ed/components'
remote:   using description file: /tmp/build_30fc7bd58001466be08fc9fc142a91ed/package.json (relative path: ./components)
remote:     Field 'browser' doesn't contain a valid alias configuration
remote:   after using description file: /tmp/build_30fc7bd58001466be08fc9fc142a91ed/package.json (relative path: ./components)
remote:     using description file: /tmp/build_30fc7bd58001466be08fc9fc142a91ed/package.json (relative path: ./components/head)
remote:       no extension
remote:         Field 'browser' doesn't contain a valid alias configuration
remote:         /tmp/build_30fc7bd58001466be08fc9fc142a91ed/components/head doesn't exist
remote:       .js
remote:         Field 'browser' doesn't contain a valid alias configuration
remote:         /tmp/build_30fc7bd58001466be08fc9fc142a91ed/components/head.js doesn't exist
remote:       .json
remote:         Field 'browser' doesn't contain a valid alias configuration
remote:         /tmp/build_30fc7bd58001466be08fc9fc142a91ed/components/head.json doesn't exist
remote:       as directory
remote:         /tmp/build_30fc7bd58001466be08fc9fc142a91ed/components/head doesn't exist
remote: [/tmp/build_30fc7bd58001466be08fc9fc142a91ed/components/head]
remote: [/tmp/build_30fc7bd58001466be08fc9fc142a91ed/components/head.js]
remote: [/tmp/build_30fc7bd58001466be08fc9fc142a91ed/components/head.json]
remote: [/tmp/build_30fc7bd58001466be08fc9fc142a91ed/components/head]
remote:  @ ./components/layout.js 15:12-41
remote:  @ ./pages/error.js?entry
remote:  @ multi ./pages/error.js?entry
remote:     at /tmp/build_30fc7bd58001466be08fc9fc142a91ed/node_modules/next/dist/server/build/index.js:182:21
remote:     at emitRecords.err (/tmp/build_30fc7bd58001466be08fc9fc142a91ed/node_modules/webpack/lib/Compiler.js:269:13)
remote:     at Compiler.emitRecords (/tmp/build_30fc7bd58001466be08fc9fc142a91ed/node_modules/webpack/lib/Compiler.js:375:38)
remote:     at emitAssets.err (/tmp/build_30fc7bd58001466be08fc9fc142a91ed/node_modules/webpack/lib/Compiler.js:262:10)
remote:     at applyPluginsAsyncSeries1.err (/tmp/build_30fc7bd58001466be08fc9fc142a91ed/node_modules/webpack/lib/Compiler.js:368:12)
remote:     at next (/tmp/build_30fc7bd58001466be08fc9fc142a91ed/node_modules/tapable/lib/Tapable.js:218:11)
remote:     at Compiler.compiler.plugin (/tmp/build_30fc7bd58001466be08fc9fc142a91ed/node_modules/webpack/lib/performance/SizeLimitsPlugin.js:99:4)
remote:     at Compiler.applyPluginsAsyncSeries1 (/tmp/build_30fc7bd58001466be08fc9fc142a91ed/node_modules/tapable/lib/Tapable.js:222:13)
remote:     at Compiler.afterEmit (/tmp/build_30fc7bd58001466be08fc9fc142a91ed/node_modules/webpack/lib/Compiler.js:365:9)
remote:     at require.forEach.err (/tmp/build_30fc7bd58001466be08fc9fc142a91ed/node_modules/webpack/lib/Compiler.js:360:15)
remote:   errors: 
remote:    [ './components/layout.js\nModule not found: Error: Can\'t resolve \'../components/head\' in \'/tmp/build_30fc7bd58001466be08fc9fc142a91ed/components\'\nresolve \'../components/head\' in \'/tmp/build_30fc7bd58001466be08fc9fc142a91ed/components\'\n  using description file: /tmp/build_30fc7bd58001466be08fc9fc142a91ed/package.json (relative path: ./components)\n    Field \'browser\' doesn\'t contain a valid alias configuration\n  after using description file: /tmp/build_30fc7bd58001466be08fc9fc142a91ed/package.json (relative path: ./components)\n    using description file: /tmp/build_30fc7bd58001466be08fc9fc142a91ed/package.json (relative path: ./components/head)\n      no extension\n        Field \'browser\' doesn\'t contain a valid alias configuration\n        /tmp/build_30fc7bd58001466be08fc9fc142a91ed/components/head doesn\'t exist\n      .js\n        Field \'browser\' doesn\'t contain a valid alias configuration\n        /tmp/build_30fc7bd58001466be08fc9fc142a91ed/components/head.js doesn\'t exist\n      .json\n        Field \'browser\' doesn\'t contain a valid alias configuration\n        /tmp/build_30fc7bd58001466be08fc9fc142a91ed/components/head.json doesn\'t exist\n      as directory\n        /tmp/build_30fc7bd58001466be08fc9fc142a91ed/components/head doesn\'t exist\n[/tmp/build_30fc7bd58001466be08fc9fc142a91ed/components/head]\n[/tmp/build_30fc7bd58001466be08fc9fc142a91ed/components/head.js]\n[/tmp/build_30fc7bd58001466be08fc9fc142a91ed/components/head.json]\n[/tmp/build_30fc7bd58001466be08fc9fc142a91ed/components/head]\n @ ./components/layout.js 15:12-41\n @ ./pages/error.js?entry\n @ multi ./pages/error.js?entry',
remote:      './components/layout.js\nModule not found: Error: Can\'t resolve \'../components/header\' in \'/tmp/build_30fc7bd58001466be08fc9fc142a91ed/components\'\nresolve \'../components/header\' in \'/tmp/build_30fc7bd58001466be08fc9fc142a91ed/components\'\n  using description file: /tmp/build_30fc7bd58001466be08fc9fc142a91ed/package.json (relative path: ./components)\n    Field \'browser\' doesn\'t contain a valid alias configuration\n  after using description file: /tmp/build_30fc7bd58001466be08fc9fc142a91ed/package.json (relative path: ./components)\n    using description file: /tmp/build_30fc7bd58001466be08fc9fc142a91ed/package.json (relative path: ./components/header)\n      no extension\n        Field \'browser\' doesn\'t contain a valid alias configuration\n        /tmp/build_30fc7bd58001466be08fc9fc142a91ed/components/header doesn\'t exist\n      .js\n        Field \'browser\' doesn\'t contain a valid alias configuration\n        /tmp/build_30fc7bd58001466be08fc9fc142a91ed/components/header.js doesn\'t exist\n      .json\n        Field \'browser\' doesn\'t contain a valid alias configuration\n        /tmp/build_30fc7bd58001466be08fc9fc142a91ed/components/header.json doesn\'t exist\n      as directory\n        /tmp/build_30fc7bd58001466be08fc9fc142a91ed/components/header doesn\'t exist\n[/tmp/build_30fc7bd58001466be08fc9fc142a91ed/components/header]\n[/tmp/build_30fc7bd58001466be08fc9fc142a91ed/components/header.js]\n[/tmp/build_30fc7bd58001466be08fc9fc142a91ed/components/header.json]\n[/tmp/build_30fc7bd58001466be08fc9fc142a91ed/components/header]\n @ ./components/layout.js 19:14-45\n @ ./pages/error.js?entry\n @ multi ./pages/error.js?entry',
remote:      './components/layout.js\nModule not found: Error: Can\'t resolve \'../components/navBar\' in \'/tmp/build_30fc7bd58001466be08fc9fc142a91ed/components\'\nresolve \'../components/navBar\' in \'/tmp/build_30fc7bd58001466be08fc9fc142a91ed/components\'\n  using description file: /tmp/build_30fc7bd58001466be08fc9fc142a91ed/package.json (relative path: ./components)\n    Field \'browser\' doesn\'t contain a valid alias configuration\n  after using description file: /tmp/build_30fc7bd58001466be08fc9fc142a91ed/package.json (relative path: ./components)\n    using description file: /tmp/build_30fc7bd58001466be08fc9fc142a91ed/package.json (relative path: ./components/navBar)\n      no extension\n        Field \'browser\' doesn\'t contain a valid alias configuration\n        /tmp/build_30fc7bd58001466be08fc9fc142a91ed/components/navBar doesn\'t exist\n      .js\n        Field \'browser\' doesn\'t contain a valid alias configuration\n        /tmp/build_30fc7bd58001466be08fc9fc142a91ed/components/navBar.js doesn\'t exist\n      .json\n        Field \'browser\' doesn\'t contain a valid alias configuration\n        /tmp/build_30fc7bd58001466be08fc9fc142a91ed/components/navBar.json doesn\'t exist\n      as directory\n        /tmp/build_30fc7bd58001466be08fc9fc142a91ed/components/navBar doesn\'t exist\n[/tmp/build_30fc7bd58001466be08fc9fc142a91ed/components/navBar]\n[/tmp/build_30fc7bd58001466be08fc9fc142a91ed/components/navBar.js]\n[/tmp/build_30fc7bd58001466be08fc9fc142a91ed/components/navBar.json]\n[/tmp/build_30fc7bd58001466be08fc9fc142a91ed/components/navBar]\n @ ./components/layout.js 23:14-45\n @ ./pages/error.js?entry\n @ multi ./pages/error.js?entry' ],
remote:   warnings: [] }
remote: npm ERR! code ELIFECYCLE
remote: npm ERR! errno 1
remote: npm ERR! next-authenticate@1.0.0 build: `next build`
remote: npm ERR! Exit status 1
remote: npm ERR! 
remote: npm ERR! Failed at the next-authenticate@1.0.0 build script.
remote: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
remote: 
remote: npm ERR! A complete log of this run can be found in:
remote: npm ERR!     /app/.npm/_logs/2017-09-27T07_32_42_439Z-debug.log
remote: npm ERR! code ELIFECYCLE
remote: npm ERR! errno 1
remote: npm ERR! next-authenticate@1.0.0 heroku-postbuild: `npm run build`
remote: npm ERR! Exit status 1
remote: npm ERR! 
remote: npm ERR! Failed at the next-authenticate@1.0.0 heroku-postbuild script.
remote: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
remote: 
remote: npm ERR! A complete log of this run can be found in:
remote: npm ERR!     /app/.npm/_logs/2017-09-27T07_32_42_463Z-debug.log
remote: 
remote: -----> Build failed
remote:        
remote:        We're sorry this build is failing! You can troubleshoot common issues here:
remote:        https://devcenter.heroku.com/articles/troubleshooting-node-deploys
remote:        
remote:        Some possible problems:
remote:        
remote:        - Node version not specified in package.json
remote:        https://devcenter.heroku.com/articles/nodejs-support#specifying-a-node-js-version
remote:        
remote:        Love,
remote:        Heroku
remote:
```

package.json

{
  "name": "next-authenticate",
  "version": "1.0.0",
  "description": "",
  "scripts": {
    "dev": "next",
    "build": "next build",
    "start": "next start -p $PORT",
    "heroku-postbuild": "npm run build"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "es6-promise": "^4.1.1",
    "isomorphic-fetch": "^2.2.1",
    "next": "^3.2.2",
    "nprogress": "^0.2.0",
    "react": "^15.6.1",
    "react-dom": "^15.6.1",
    "universal-cookie": "^2.1.0"
  },
  "devDependencies": {}
}

**Comment by mattytb** [comment]
My issue was stupid of me, it was a case sensitivity issue, I had changed the capitalisation of a couple of my components and Git will not change them unless you rename to something different then rename again with the change of caps. This meant all looked fine but was actually looking for the Capped version.

**Comment by timneutkens** [comment]
👍
