### ISSUE TITLE
i am try to add graphql pubSub by apollo ,but failure

### ISSUE THREAD

**Issue by foxundermoon** [zeit/next.js#3036]
error with  no  implementation for WebSocket. so i install server WebSocket and try Polyfill it .
but still failure .

```
import { createNetworkInterface } from "react-apollo";
import { ApolloClient } from "apollo-client";
import fetch from "isomorphic-fetch";
import WebSocket from "ws";

import { ApolloLink, HttpLink, WebSocketLink } from "apollo-link";

let apolloClient = null;

// Polyfill fetch() on the server (used by apollo-client)
if (!process.browser) {
  global.fetch = fetch;
  global.WebSocket = WebSocket;
}

function create(initialState) {
  return new ApolloClient({
    initialState,
    ssrMode: !process.browser, // Disables forceFetch on the server (so queries are only run once)
    link: createLink()
    // networkInterface: createNetworkInterface({
    //   // uri: 'https://api.graph.cool/simple/v1/cixmkt2ul01q00122mksg82pn', // Server URL (must be absolute)
    //   uri: "http://localhost:6000/graphql", // Server URL (must be absolute)
    //   opts: {
    //     // Additional fetch() options like `credentials` or `headers`
    //     credentials: "same-origin"
    //   }
    // })
  });
}

function createLink() {
  const uri = "http://localhost:6000/graphql";
  const wsUri = "ws://localhost:6000/subscriptions";
  return ApolloLink.from([
    new HttpLink({ uri }),
    new WebSocketLink({ uri: wsUri })
  ]);
}

export default function initApollo(initialState) {
  // Make sure to create a new client for every server-side request so that data
  // isn't shared between connections (which would be bad)
  if (!process.browser) {
    return create(initialState);
  }

  // Reuse client on the client-side
  if (!apolloClient) {
    apolloClient = create(initialState);
  }

  return apolloClient;
}


```

```
500
Internal Server Error.
Unable to find native implementation, or alternative implementation for WebSocket!
Error: Unable to find native implementation, or alternative implementation for WebSocket!
    at new SubscriptionClient (/Users/fox/workspace/web/7xiu.fun/node_modules/apollo-link-ws/node_modules/subscriptions-transport-ws/src/client.ts:109:13)
    at new WebSocketLink (/Users/fox/workspace/web/7xiu.fun/node_modules/src/webSocketLink.ts:25:33)
    at createLink (/Users/fox/workspace/web/7xiu.fun/lib/initApollo.js:37:5)
    at create (/Users/fox/workspace/web/7xiu.fun/lib/initApollo.js:20:11)
    at initApollo (/Users/fox/workspace/web/7xiu.fun/lib/initApollo.js:45:12)
    at Function._callee$ (/Users/fox/workspace/web/7xiu.fun/lib/withData.js:13:3)
    at tryCatch (/Users/fox/workspace/web/7xiu.fun/node_modules/next/node_modules/regenerator-runtime/runtime.js:65:40)
    at Generator.invoke [as _invoke] (/Users/fox/workspace/web/7xiu.fun/node_modules/next/node_modules/regenerator-runtime/runtime.js:303:22)
    at Generator.prototype.forEach.prototype.(anonymous function) [as next] (/Users/fox/workspace/web/7xiu.fun/node_modules/next/node_modules/regenerator-runtime/runtime.js:117:21)
    at step (/Users/fox/workspace/web/7xiu.fun/node_modules/next/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at /Users/fox/workspace/web/7xiu.fun/node_modules/next/node_modules/babel-runtime/helpers/asyncToGenerator.js:28:13
    at <anonymous>
```

**Comment by bs1180** [comment]
I don't think you want to be creating a subscription on the server, because the Apollo client is only being created for SSR (and so disposed of on each request). Instead, something like this should work:

```
 function createLink() {
  const uri = "http://localhost:6000/graphql";
  
  const transports = [new HttpLink({ uri })]

  if (process.browser) {
    const wsUri = "ws://localhost:6000/subscriptions";
    transports.push(new WebSocketLink({ uri: wsUri }))
  }
  
  return ApolloLink.from(transports);
}
```

**Comment by foxundermoon** [comment]
@bs1180   yes, i just want  it run   well .i not want creating a subscription on the server
