### ISSUE TITLE
npm run build failed

### ISSUE THREAD

**Issue by psycura** [zeit/next.js#3199]
- [x ] I have searched the [issues](https://github.com/zeit/next.js/issues) of this repository and believe that this is not a duplicate.

## Expected Behavior
npm run build - expect to build for deploy

## Current Behavior
receive an error:

> > Failed to build on C:\Users\psycu\AppData\Local\Temp\6d75aadf-8045-42b3-9a00-69e315dbec1c
{ Error: commons.js from UglifyJs
Unexpected token: name (onClickOutside) [commons.js:94268,33]
    at D:\Sites\training\boilerplates\with-mobx\node_modules\next\dist\server\build\index.js:182:21
    at emitRecords.err (D:\Sites\training\boilerplates\with-mobx\node_modules\webpack\lib\Compiler.js:269:13)
    at Compiler.emitRecords (D:\Sites\training\boilerplates\with-mobx\node_modules\webpack\lib\Compiler.js:375:38)
    at emitAssets.err (D:\Sites\training\boilerplates\with-mobx\node_modules\webpack\lib\Compiler.js:262:10)
    at applyPluginsAsyncSeries1.err (D:\Sites\training\boilerplates\with-mobx\node_modules\webpack\lib\Compiler.js:368:12)
    at next (D:\Sites\training\boilerplates\with-mobx\node_modules\tapable\lib\Tapable.js:218:11)
    at Compiler.compiler.plugin (D:\Sites\training\boilerplates\with-mobx\node_modules\webpack\lib\performance\SizeLimitsPlugin.js:99:4)
    at Compiler.applyPluginsAsyncSeries1 (D:\Sites\training\boilerplates\with-mobx\node_modules\tapable\lib\Tapable.js:222:13)
    at Compiler.afterEmit (D:\Sites\training\boilerplates\with-mobx\node_modules\webpack\lib\Compiler.js:365:9)
    at require.forEach.err (D:\Sites\training\boilerplates\with-mobx\node_modules\webpack\lib\Compiler.js:354:15)
  errors: [ 'commons.js from UglifyJs\nUnexpected token: name (onClickOutside) [commons.js:94268,33]' ],
  warnings: [] }
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! with-mobx@1.0.0 build: `next build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the with-mobx@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\psycu\AppData\Roaming\npm-cache\_logs\2017-10-28T13_26_00_550Z-debug.log

## Steps to Reproduce (for bugs)
im using firebase,mobx,emotion libraries.
on dev mode everything for fine, but buil cannot be completed.

I think it maybe some connection to my .babelrc file that include:

`
{
    "presets": [
        "next/babel"
    ],
    "plugins": [
        "transform-decorators-legacy",
        [
            "transform-assets-import-to-string",
            {
                "baseDir": "static",
                "baseUri": "/"
            }
        ],
        [
            "emotion",
            {
                "inline": true
            }
        ]
    ]
}
`

## Your Environment

| Tech    | Version |
|---------|---------|
| next    |    latest     |
| node    |     8.5.0    |
| OS      |   windows 10 64bit      |
| browser |    chrome     |
| etc     |         |

**Comment by mrmartineau** [comment]
@psycura I also have a similar issue to you, on [this repo](https://github.com/mrmartineau/xkcd-app). 

### Here is the error:
```
yarn build v0.27.5
$ next build
> Using external babel configuration
> Location: "/Users/zandermartineau/code/xkcd-app/.babelrc"
> Failed to build on /var/folders/07/c7wr7hw51zg81_k6r8l8v47w0000gq/T/98ab0b65-359c-4901-bce3-679346d3ba54
{ Error: ./pages/_document.js?entry
Module build failed: TypeError: unknown: Duplicate declaration "React"
   6 | import _inherits from 'babel-runtime/helpers/inherits';
   7 | import React from 'react';
>  8 | import React from 'react';
     |        ^
   9 | import React from 'react';
  10 | import Document, { Head, Main, NextScript } from 'next/dist/server/document.js';
  11 | import { extractCritical } from 'emotion-server';
    at File.buildCodeFrameError (/Users/zandermartineau/code/xkcd-app/node_modules/babel-core/lib/transformation/file/index.js:427:15)
    at Scope.checkBlockScopedCollisions (/Users/zandermartineau/code/xkcd-app/node_modules/babel-traverse/lib/scope/index.js:398:27)
    at Scope.registerBinding (/Users/zandermartineau/code/xkcd-app/node_modules/babel-traverse/lib/scope/index.js:592:16)
    at Scope.registerDeclaration (/Users/zandermartineau/code/xkcd-app/node_modules/babel-traverse/lib/scope/index.js:516:14)
    at Object.Declaration (/Users/zandermartineau/code/xkcd-app/node_modules/babel-traverse/lib/scope/index.js:176:36)
    at NodePath._call (/Users/zandermartineau/code/xkcd-app/node_modules/babel-traverse/lib/path/context.js:76:18)
    at NodePath.call (/Users/zandermartineau/code/xkcd-app/node_modules/babel-traverse/lib/path/context.js:48:17)
    at NodePath.visit (/Users/zandermartineau/code/xkcd-app/node_modules/babel-traverse/lib/path/context.js:105:12)
    at TraversalContext.visitQueue (/Users/zandermartineau/code/xkcd-app/node_modules/babel-traverse/lib/context.js:150:16)
    at TraversalContext.visitMultiple (/Users/zandermartineau/code/xkcd-app/node_modules/babel-traverse/lib/context.js:103:17)
 @ multi ./pages/_document.js?entry
    at /Users/zandermartineau/code/xkcd-app/node_modules/next/dist/server/build/index.js:182:21
    at emitRecords.err (/Users/zandermartineau/code/xkcd-app/node_modules/webpack/lib/Compiler.js:269:13)
    at Compiler.emitRecords (/Users/zandermartineau/code/xkcd-app/node_modules/webpack/lib/Compiler.js:375:38)
    at emitAssets.err (/Users/zandermartineau/code/xkcd-app/node_modules/webpack/lib/Compiler.js:262:10)
    at applyPluginsAsyncSeries1.err (/Users/zandermartineau/code/xkcd-app/node_modules/webpack/lib/Compiler.js:368:12)
    at next (/Users/zandermartineau/code/xkcd-app/node_modules/tapable/lib/Tapable.js:218:11)
    at Compiler.compiler.plugin (/Users/zandermartineau/code/xkcd-app/node_modules/webpack/lib/performance/SizeLimitsPlugin.js:99:4)
    at Compiler.applyPluginsAsyncSeries1 (/Users/zandermartineau/code/xkcd-app/node_modules/tapable/lib/Tapable.js:222:13)
    at Compiler.afterEmit (/Users/zandermartineau/code/xkcd-app/node_modules/webpack/lib/Compiler.js:365:9)
    at require.forEach.err (/Users/zandermartineau/code/xkcd-app/node_modules/webpack/lib/Compiler.js:354:15)
  errors:
   [ './pages/_document.js?entry\nModule build failed: TypeError: unknown: Duplicate declaration "React"\n\u001b[0m \u001b[90m  6 | \u001b[39m\u001b[36mimport\u001b[39m _inherits from \u001b[32m\'babel-runtime/helpers/inherits\'\u001b[39m\u001b[33m;\u001b[39m\n \u001b[90m  7 | \u001b[39m\u001b[36mimport\u001b[39m \u001b[33mReact\u001b[39m from \u001b[32m\'react\'\u001b[39m\u001b[33m;\u001b[39m\n\u001b[31m\u001b[1m>\u001b[22m\u001b[39m\u001b[90m  8 | \u001b[39m\u001b[36mimport\u001b[39m \u001b[33mReact\u001b[39m from \u001b[32m\'react\'\u001b[39m\u001b[33m;\u001b[39m\n \u001b[90m    | \u001b[39m       \u001b[31m\u001b[1m^\u001b[22m\u001b[39m\n \u001b[90m  9 | \u001b[39m\u001b[36mimport\u001b[39m \u001b[33mReact\u001b[39m from \u001b[32m\'react\'\u001b[39m\u001b[33m;\u001b[39m\n \u001b[90m 10 | \u001b[39m\u001b[36mimport\u001b[39m \u001b[33mDocument\u001b[39m\u001b[33m,\u001b[39m { \u001b[33mHead\u001b[39m\u001b[33m,\u001b[39m \u001b[33mMain\u001b[39m\u001b[33m,\u001b[39m \u001b[33mNextScript\u001b[39m } from \u001b[32m\'next/dist/server/document.js\'\u001b[39m\u001b[33m;\u001b[39m\n \u001b[90m 11 | \u001b[39m\u001b[36mimport\u001b[39m { extractCritical } from \u001b[32m\'emotion-server\'\u001b[39m\u001b[33m;\u001b[39m\u001b[0m\n    at File.buildCodeFrameError (/Users/zandermartineau/code/xkcd-app/node_modules/babel-core/lib/transformation/file/index.js:427:15)\n    at Scope.checkBlockScopedCollisions (/Users/zandermartineau/code/xkcd-app/node_modules/babel-traverse/lib/scope/index.js:398:27)\n    at Scope.registerBinding (/Users/zandermartineau/code/xkcd-app/node_modules/babel-traverse/lib/scope/index.js:592:16)\n    at Scope.registerDeclaration (/Users/zandermartineau/code/xkcd-app/node_modules/babel-traverse/lib/scope/index.js:516:14)\n    at Object.Declaration (/Users/zandermartineau/code/xkcd-app/node_modules/babel-traverse/lib/scope/index.js:176:36)\n    at NodePath._call (/Users/zandermartineau/code/xkcd-app/node_modules/babel-traverse/lib/path/context.js:76:18)\n    at NodePath.call (/Users/zandermartineau/code/xkcd-app/node_modules/babel-traverse/lib/path/context.js:48:17)\n    at NodePath.visit (/Users/zandermartineau/code/xkcd-app/node_modules/babel-traverse/lib/path/context.js:105:12)\n    at TraversalContext.visitQueue (/Users/zandermartineau/code/xkcd-app/node_modules/babel-traverse/lib/context.js:150:16)\n    at TraversalContext.visitMultiple (/Users/zandermartineau/code/xkcd-app/node_modules/babel-traverse/lib/context.js:103:17)\n @ multi ./pages/_document.js?entry',
     './pages?entry\nModule build failed: TypeError: unknown: Duplicate declaration "React"\n\u001b[0m \u001b[90m 1 | \u001b[39m\u001b[36mimport\u001b[39m \u001b[33mReact\u001b[39m from \u001b[32m\'react\'\u001b[39m\u001b[33m;\u001b[39m\n\u001b[31m\u001b[1m>\u001b[22m\u001b[39m\u001b[90m 2 | \u001b[39m\u001b[36mimport\u001b[39m \u001b[33mReact\u001b[39m from \u001b[32m\'react\'\u001b[39m\u001b[33m;\u001b[39m\n \u001b[90m   | \u001b[39m       \u001b[31m\u001b[1m^\u001b[22m\u001b[39m\n \u001b[90m 3 | \u001b[39m\u001b[36mimport\u001b[39m \u001b[33mReact\u001b[39m from \u001b[32m\'react\'\u001b[39m\u001b[33m;\u001b[39m\n \u001b[90m 4 | \u001b[39m\u001b[36mimport\u001b[39m \u001b[33mMasterLayout\u001b[39m from \u001b[32m\'../layouts/master\'\u001b[39m\u001b[33m;\u001b[39m\n \u001b[90m 5 | \u001b[39m\u001b[36mimport\u001b[39m styled from \u001b[32m\'react-emotion\'\u001b[39m\u001b[33m;\u001b[39m\u001b[0m\n    at File.buildCodeFrameError (/Users/zandermartineau/code/xkcd-app/node_modules/babel-core/lib/transformation/file/index.js:427:15)\n    at Scope.checkBlockScopedCollisions (/Users/zandermartineau/code/xkcd-app/node_modules/babel-traverse/lib/scope/index.js:398:27)\n    at Scope.registerBinding (/Users/zandermartineau/code/xkcd-app/node_modules/babel-traverse/lib/scope/index.js:592:16)\n    at Scope.registerDeclaration (/Users/zandermartineau/code/xkcd-app/node_modules/babel-traverse/lib/scope/index.js:516:14)\n    at Object.Declaration (/Users/zandermartineau/code/xkcd-app/node_modules/babel-traverse/lib/scope/index.js:176:36)\n    at NodePath._call (/Users/zandermartineau/code/xkcd-app/node_modules/babel-traverse/lib/path/context.js:76:18)\n    at NodePath.call (/Users/zandermartineau/code/xkcd-app/node_modules/babel-traverse/lib/path/context.js:48:17)\n    at NodePath.visit (/Users/zandermartineau/code/xkcd-app/node_modules/babel-traverse/lib/path/context.js:105:12)\n    at TraversalContext.visitQueue (/Users/zandermartineau/code/xkcd-app/node_modules/babel-traverse/lib/context.js:150:16)\n    at TraversalContext.visitMultiple (/Users/zandermartineau/code/xkcd-app/node_modules/babel-traverse/lib/context.js:103:17)\n @ multi ./pages?entry' ],
  warnings: [] }
error Command failed with exit code 1.
```
The error mentions duplicate declarations for React, which is so strange.. I am also having the same issue on https://github.com/nimbletank/nimbletank-nextjs-start

#### With this .babelrc:
```json
{
  "env": {
    "development": {
      "presets": "next/babel",
      "plugins": [
        ["emotion", { "sourceMap": true }],
        "inline-react-svg"
      ]
    },
    "production": {
      "presets": "next/babel",
      "plugins": [
        ["emotion", { "sourceMap": false }],
        "inline-react-svg"
      ]
    },
    "test": {
      "presets": [
        "env",
        "next/babel"
      ],
      "plugins": [
        ["emotion", { "sourceMap": true }],
        "inline-react-svg"
      ]
    }
  },
  "plugins": [
    ["emotion", { "sourceMap": true }],
    "inline-react-svg"
  ]
}
```

### Here is my error when I remove the babelrc:

```
yarn build v0.27.5
$ next build
> Failed to build on /var/folders/07/c7wr7hw51zg81_k6r8l8v47w0000gq/T/9b739ae6-6ceb-45cb-b59b-e466885a6e19
{ Error: bundles/pages/index.js from UglifyJs
Invalid assignment [bundles/pages/index.js:2335,31]
    at /Users/zandermartineau/code/xkcd-app/node_modules/next/dist/server/build/index.js:182:21
    at emitRecords.err (/Users/zandermartineau/code/xkcd-app/node_modules/webpack/lib/Compiler.js:269:13)
    at Compiler.emitRecords (/Users/zandermartineau/code/xkcd-app/node_modules/webpack/lib/Compiler.js:375:38)
    at emitAssets.err (/Users/zandermartineau/code/xkcd-app/node_modules/webpack/lib/Compiler.js:262:10)
    at applyPluginsAsyncSeries1.err (/Users/zandermartineau/code/xkcd-app/node_modules/webpack/lib/Compiler.js:368:12)
    at next (/Users/zandermartineau/code/xkcd-app/node_modules/tapable/lib/Tapable.js:218:11)
    at Compiler.compiler.plugin (/Users/zandermartineau/code/xkcd-app/node_modules/webpack/lib/performance/SizeLimitsPlugin.js:99:4)
    at Compiler.applyPluginsAsyncSeries1 (/Users/zandermartineau/code/xkcd-app/node_modules/tapable/lib/Tapable.js:222:13)
    at Compiler.afterEmit (/Users/zandermartineau/code/xkcd-app/node_modules/webpack/lib/Compiler.js:365:9)
    at require.forEach.err (/Users/zandermartineau/code/xkcd-app/node_modules/webpack/lib/Compiler.js:354:15)
  errors: [ 'bundles/pages/index.js from UglifyJs\nInvalid assignment [bundles/pages/index.js:2335,31]' ],
  warnings: [] }
error Command failed with exit code 1.
```

@arunoda do you know what this might be related to?

**Comment by thierryc** [comment]
remove "inline-react-svg"
