### ISSUE TITLE
custome webpack failed: TypeError: arguments[i].apply is not a function

### ISSUE THREAD

**Issue by guotie** [zeit/next.js#3275]
When i merge my own webpack config to the next.config.js and run next, the following error:

```
TypeError: arguments[i].apply is not a function
    at Compiler.apply (F:\Users\tie\gopath\src\ktarget\workspace\node_modules\tapable\lib\Tapable.js:375:16)
    at webpack (F:\Users\tie\gopath\src\ktarget\workspace\node_modules\next\node_modules\webpack\lib\webpack.js:33:19)
    at _callee2$ (F:\Users\tie\gopath\src\ktarget\workspace\node_modules\next\dist\server\build\webpack.js:571:69)
    at tryCatch (F:\Users\tie\gopath\src\ktarget\workspace\node_modules\regenerator-runtime\runtime.js:65:40)
    at Generator.invoke [as _invoke] (F:\Users\tie\gopath\src\ktarget\workspace\node_modules\regenerator-runtime\runtime.js:299:22)
    at Generator.prototype.(anonymous function) [as next] (F:\Users\tie\gopath\src\ktarget\workspace\node_modules\regenerator-runtime\runtime.js:117:21)
    at step (F:\Users\tie\gopath\src\ktarget\workspace\node_modules\babel-runtime\helpers\asyncToGenerator.js:17:30)
    at F:\Users\tie\gopath\src\ktarget\workspace\node_modules\babel-runtime\helpers\asyncToGenerator.js:28:13
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:169:7)
    at Function.Module.runMain (module.js:607:11)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:575:3
```

**Comment by timneutkens** [comment]
Sounds like an error in your config. Please follow the issue template so that we have more information to go on 👍
