### ISSUE TITLE
Error on reload or direct enter url to the browser on Production

### ISSUE THREAD

**Issue by pthphap** [zeit/next.js#3308]
I'm trying out nextjs for a couple of weeks, and I have build a small web using Nextjs
Everything works fine on Dev environment, 
However when it comes to Prod, I'm facing a lot of troubles 
I read Nextjs docs and know that I have to run "next build" so I did and then I deploy my app to my droplet (512 MB, 1 core)

Live demo is here: http://tangerine.vn

On Dev env when I open "http://localhost:8080/collections/skincare" (by typing url to browser or navigate on main menu), the page works as I expected, it shows some products

But on Prod env, It's working only if I open the page by navigate on main menu, and when I open devtool (Chrome) to debug I got some weird message what I have no idea where is the root of the problem

![image](https://user-images.githubusercontent.com/11292667/32991969-a20c54c4-cd77-11e7-8c80-386c463ca3c0.png)

Here is my server.js
```
// LIBRARIES
const express = require('express')
const next = require('next')

const dev = process.env.NODE_ENV !== 'production'
const app = next({ dev })
const handle = app.getRequestHandler()

// CONFIG
app.prepare().then(() => {
  // Start Express
  const server = express()
  /*
   * Search
   */
  server.get('/search/:code', (req, res) => {
    const actual = '/search'
    const params = {
      code: req.params.code
    }
    app.render(req, res, actual, params)
  })

  /*
   * Products by category
   */
  server.get('/collections/:category$', (req, res) => {
    const actual = '/collections'
    const params = {
      category: req.params.category
    }
    app.render(req, res, actual, params)
  })

  /*
   * Product Detail
   */
  server.get('/collections/:category/:productCode$', (req, res) => {
    const actual = '/detail'
    const params = {
      category: req.params.category,
      productCode: req.params.productCode,
    }
    app.render(req, res, actual, params)
  })

  /*
   * Home 
   */
  server.get('/', (req, res) => {
    var ip = req.headers['x-real-ip'] || req.connection.remoteAddress;
    res.redirect('/home')
  })
  server.get('*', (req, res) => {
    return handle(req, res)
  })

  /*
   * Run app
   */
  server.listen(3000, (err) => {
    if (err) throw err
    console.log('>> Ready on http://localhost:3000')
  })

})
.catch((ex) => {
  console.error(">> EXCEPTION", ex.stack)
  process.exit(1)
})
```

##  Environment
| Tech    | Version |
|---------|---------|
"express": "^4.16.0",
"next": "^3.2.2",
"react": "^15.6.2",
"webpack": "^3.8.1"

Can someone help me out. Thank you

**Comment by ShangguanMr** [comment]
I have the same problem

**Comment by ShangguanMr** [comment]
I hope the official gives a solution

**Comment by liweinan0423** [comment]
```
app.js:36 I.default.find is not a function
TypeError: I.default.find is not a function
    at e.value (http://tangerine.vn/_next/3061f79a-93de-4935-b858-5805099db6f8/page/collections:9:597076)
    at E (http://tangerine.vn/_next/bf6ccc76a8084294eedca63be540d34c/app.js:2:23619)
    at e.r (http://tangerine.vn/_next/bf6ccc76a8084294eedca63be540d34c/app.js:2:26528)
    at e.value (http://tangerine.vn/_next/3061f79a-93de-4935-b858-5805099db6f8/page/collections:9:597407)
    at E (http://tangerine.vn/_next/bf6ccc76a8084294eedca63be540d34c/app.js:2:23619)
    at e.r (http://tangerine.vn/_next/bf6ccc76a8084294eedca63be540d34c/app.js:2:26528)
    at e.value (http://tangerine.vn/_next/3061f79a-93de-4935-b858-5805099db6f8/page/collections:9:597359)
    at E (http://tangerine.vn/_next/bf6ccc76a8084294eedca63be540d34c/app.js:2:23619)
    at e.r (http://tangerine.vn/_next/bf6ccc76a8084294eedca63be540d34c/app.js:2:26528)
    at t.value (http://tangerine.vn/_next/3061f79a-93de-4935-b858-5805099db6f8/page/collections:9:590672)
```

I think it should be an error in your application code. Could you share your code so we can help investigation? If for confidential reason you cannot share your code, could you make a sample repo that can reproduce your error?

**Comment by pthphap** [comment]
I works perfectly fine if I use the dev config for it on production, but all pages will be loaded really slow due to browser has to download large file (~14M) :(
