### ISSUE TITLE
A compile error occurred

### ISSUE THREAD

**Issue by zhipenglin** [zeit/next.js#3349]
- [ ] I have searched the [issues](https://github.com/zeit/next.js/issues) of this repository and believe that this is not a duplicate.

## Steps to Reproduce (for bugs)

1. npm install --save next react react-dom
2. Populate ./pages/index.js inside your project:
export default () => <div>Welcome to next.js!</div>
3. npm run dev
4. internal/child_process.js:325
    throw errnoException(err, 'spawn');
    ^

Error: spawn EACCES
    at _errnoException (util.js:1022:11)
    at ChildProcess.spawn (internal/child_process.js:325:11)
    at Object.exports.spawn (child_process.js:493:9)
    at spawn (/Users/mac/Documents/lantts/node_modules/cross-spawn/index.js:17:18)
    at startProcess (/Users/mac/Documents/lantts/node_modules/next/dist/bin/next:72:36)
    at Object.<anonymous> (/Users/mac/Documents/lantts/node_modules/next/dist/bin/next:93:12)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)

## Your Environment

| Tech    | Version |
|---------|---------|
| next    |      4.1.4   |
| node    |    v8.3.0     |
| OS      |     macOS High Sierra v10.13.1    |
| browser |      chrome   |
| etc     |         |

**Comment by liweinan0423** [comment]
It looks like some sort of file permission issue. Try run it under `root` user. Or delete the whole project and re-create and run with the same user

**Comment by zhipenglin** [comment]
thank you
