### ISSUE TITLE
Using url methods on the server causes an unhandled promise rejection

### ISSUE THREAD

**Issue by MarcoThePoro** [zeit/next.js#339]
So I'm not sure if you're supposed to be able to make redirects within the server render but here it goes.

On my site, I'm trying to redirect away from a page if the user isn't authenticated. My authentication happens within my getInitialProps, and if the user is not authenticated then I call url.pushTo from within componentWillMount of the page.

When I navigate to the protected page from the client (using a url.pushTo or `<Link>`), everything works as normal. getInitialProps is fired, returning props indicating no authorization, then componentWillMount checks that and then redirects back.

However, when it renders on the server (if I visit the protected page directly by entering the url into the browser) the call to url.pushTo rejects and it sends the protected page to the client. When the client scripts run, the componentWillMount is called again on the client and then the url.pushTo runs as normal. This results in the protected page flashing up quickly before being replaced by the redirected page.

Here is an example consisting of two pages, `private` and `public`.

```js
// pages/private.js
import React from 'react';

export default class Private extends React.Component {
  static async getInitialProps() {
    await delay(1000); // simulate an auth check
    return {
      authorized: false,
    };
  }

  componentWillMount() {
    if (!this.props.authorized) {
      this.props.url.replaceTo('/public');
    }
  }

  render() {
    return (
      <div>You are not authorized for this page!!!</div>
    );
  }
}

function delay(time) {
  return new Promise(resolve => setTimeout(resolve, time))
}
```

```js
// pages/public.js
import React from 'react';
import Link from 'next/link';

export default class Public extends React.Component {
  static async getInitialProps() {
    return {
      message: 'This is a public page!'
    };
  }

  render() {
    return (
      <div>
        <p>
          {this.props.message}
        </p>
        <p>
          <Link href="/private">Go to a private page you arent authorized for</Link>
        </p>
      </div>
    );
  }
}
```
Obviously you wouldn't link to a page that would immediately redirect you back, it was just for demonstration.

If you visit  `/private` by typing `localhost:3000/private` in the browser, you get an unhandled promise rejection in the server console, and it renders the private page and sends it to the client, only for it to flash up on the client and then immediately be redirected.
```
(node:14224) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 27): TypeError: Cannot read property 'getInitialProps' of undefined
```
Here is a trace of the error I got from adding `.catch(err => console.log(err)` to the call to replaceTo.
```
TypeError: Cannot read property 'getInitialProps' of undefined
    at Router._callee7$ (D:\BitTorrentSync\common\projects\next-test\node_modules\next\dist\lib\router.js:7299:33)
    at tryCatch (D:\BitTorrentSync\common\projects\next-test\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (D:\BitTorrentSync\common\projects\next-test\node_modules\regenerator-runtime\ru
ntime.js:337:22)
    at Generator.prototype.(anonymous function) [as next] (D:\BitTorrentSync\common\projects\next-test\node_modules\r
egenerator-runtime\runtime.js:96:21)
    at step (D:\BitTorrentSync\common\projects\next-test\node_modules\babel-runtime\helpers\asyncToGenerator.js:17:30
)
    at D:\BitTorrentSync\common\projects\next-test\node_modules\babel-runtime\helpers\asyncToGenerator.js:35:14
    at F (D:\BitTorrentSync\common\projects\next-test\node_modules\core-js\library\modules\_export.js:35:28)
    at Router.<anonymous> (D:\BitTorrentSync\common\projects\next-test\node_modules\babel-runtime\helpers\asyncToGene
rator.js:14:12)
    at Router.getInitialProps (D:\BitTorrentSync\common\projects\next-test\node_modules\next\dist\lib\router.js:7356:
23)
    at Router._callee4$ (D:\BitTorrentSync\common\projects\next-test\node_modules\next\dist\lib\router.js:7018:29)
TypeError: Cannot read property 'getInitialProps' of undefined
    at Router._callee7$ (D:\BitTorrentSync\common\projects\next-test\node_modules\next\dist\lib\router.js:7299:33)
    at tryCatch (D:\BitTorrentSync\common\projects\next-test\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (D:\BitTorrentSync\common\projects\next-test\node_modules\regenerator-runtime\ru
ntime.js:337:22)
    at Generator.prototype.(anonymous function) [as next] (D:\BitTorrentSync\common\projects\next-test\node_modules\r
egenerator-runtime\runtime.js:96:21)
    at step (D:\BitTorrentSync\common\projects\next-test\node_modules\babel-runtime\helpers\asyncToGenerator.js:17:30
)
    at D:\BitTorrentSync\common\projects\next-test\node_modules\babel-runtime\helpers\asyncToGenerator.js:35:14
    at F (D:\BitTorrentSync\common\projects\next-test\node_modules\core-js\library\modules\_export.js:35:28)
    at Router.<anonymous> (D:\BitTorrentSync\common\projects\next-test\node_modules\babel-runtime\helpers\asyncToGene
rator.js:14:12)
    at Router.getInitialProps (D:\BitTorrentSync\common\projects\next-test\node_modules\next\dist\lib\router.js:7356:
23)
    at Router._callee4$ (D:\BitTorrentSync\common\projects\next-test\node_modules\next\dist\lib\router.js:7018:29)
```
(Edit: example was run on a fresh install of next 1.2.3)

**Comment by nkzawa** [comment]
`url` prop is only for client, so instead, please use `res` to redirect requests.

```js
static getInitialProps ({ res }) {
  if (res) {
    res.writeHead(302, { Location: ''/somewhere' } )
    res.end()
    return
  }
}
```

**Comment by MarcoThePoro** [comment]
Oh okay that makes sense. I'll close this.
