### ISSUE TITLE
Support React Handsontable

### ISSUE THREAD

**Issue by nvqchau** [zeit/next.js#3535]
I try to use [react handsontable](https://github.com/handsontable/react-handsontable) but there is an error

> document is not defined
ReferenceError: document is not defined
    at Object.<anonymous> (/Users/chaunguyen/Projects/next-example/node_modules/react-handsontable/node_modules/handsontable/commonjs/helpers/browser.js:10:14)
    at Module._compile (module.js:635:30)
    at Module._compile (/Users/chaunguyen/Projects/next-example/node_modules/source-map-support/source-map-support.js:492:25)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/chaunguyen/Projects/next-example/node_modules/react-handsontable/node_modules/handsontable/commonjs/helpers/dom/element.js:50:16)

Anybody help me by an example?
Or do you have any plan for support it?

**Comment by timneutkens** [comment]
This means that it does not support server side rendering. You could require the module in `componentDidMount` and render it conditionally.
