### ISSUE TITLE
Token input component for Next.js?

### ISSUE THREAD

**Issue by tomsoderlund** [zeit/next.js#3539]
Anyone managed to use an existing token input component with Next.js?

I’ve tried [react-tokeninput](https://github.com/instructure-react/react-tokeninput) and [react-token-autocomplete](https://github.com/peterKaleta/react-token-autocomplete), both makes Next.js crash.

**Comment by sergiodxa** [comment]
What's the exact error you're having?

**Comment by tomsoderlund** [comment]
This basic example for `react-token-autocomplete`:

	import TokenAutocomplete from 'react-token-autocomplete'

	// in render:

	<TokenAutocomplete
		placeholder="type to limit suggestions"
		defaultValues={['apple']}
		options={['apple', 'banana', 'carrot', 'watermelon']}
		/>

Gives me:

	Cannot call a class as a function
	TypeError: Cannot call a class as a function
		at _classCallCheck (webpack:///./~/radium/lib/enhancer.js?:7:99)
		at RadiumEnhancer (webpack:///./~/radium/lib/enhancer.js?:19:7)
		at resolve (/Users/tomsoderlund/Documents/Projects/Weld.io/Development/weld-extensions/cabal/node_modules/react-dom/cjs/react-dom-server.node.development.js:2102:14)
		at ReactDOMServerRenderer.render (/Users/tomsoderlund/Documents/Projects/Weld.io/Development/weld-extensions/cabal/node_modules/react-dom/cjs/react-dom-server.node.development.js:2260:22)
		at ReactDOMServerRenderer.read (/Users/tomsoderlund/Documents/Projects/Weld.io/Development/weld-extensions/cabal/node_modules/react-dom/cjs/react-dom-server.node.development.js:2234:19)
		at renderToString (/Users/tomsoderlund/Documents/Projects/Weld.io/Development/weld-extensions/cabal/node_modules/react-dom/cjs/react-dom-server.node.development.js:2501:25)
		at renderPage (/Users/tomsoderlund/Documents/Projects/Weld.io/Development/weld-extensions/cabal/node_modules/next/dist/server/render.js:174:26)
		at Function.getInitialProps (/Users/tomsoderlund/Documents/Projects/Weld.io/Development/weld-extensions/cabal/node_modules/next/dist/server/document.js:83:25)
		at _callee$ (/Users/tomsoderlund/Documents/Projects/Weld.io/Development/weld-extensions/cabal/node_modules/next/dist/lib/utils.js:36:30)
		at tryCatch (/Users/tomsoderlund/Documents/Projects/Weld.io/Development/weld-extensions/cabal/node_modules/regenerator-runtime/runtime.js:62:40)
		at Generator.invoke [as _invoke] (/Users/tomsoderlund/Documents/Projects/Weld.io/Development/weld-extensions/cabal/node_modules/regenerator-runtime/runtime.js:296:22)
		at Generator.prototype.(anonymous function) [as next] (/Users/tomsoderlund/Documents/Projects/Weld.io/Development/weld-extensions/cabal/node_modules/regenerator-runtime/runtime.js:114:21)
		at step (/Users/tomsoderlund/Documents/Projects/Weld.io/Development/weld-extensions/cabal/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
		at /Users/tomsoderlund/Documents/Projects/Weld.io/Development/weld-extensions/cabal/node_modules/babel-runtime/helpers/asyncToGenerator.js:35:14
		at Promise (<anonymous>)
		at F (/Users/tomsoderlund/Documents/Projects/Weld.io/Development/weld-extensions/cabal/node_modules/babel-runtime/node_modules/core-js/library/modules/_export.js:35:28)

**Comment by timneutkens** [comment]
I guess these libraries have to be changed to support server-side rendering.
