### ISSUE TITLE
hot-reloader with stylelint-webpack-plugin causes unhandled exception

### ISSUE THREAD

**Issue by bryan** [zeit/next.js#3560]
- [x] I have searched the [issues](https://github.com/zeit/next.js/issues) of this repository and believe that this is not a duplicate.

```
(node:30515) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'reasons' of undefined
    at /Users/project/node_modules/next/dist/server/hot-reloader.js:445:37
    at Array.map (<anonymous>)
    at Compiler.<anonymous> (/Users/project/node_modules/next/dist/server/hot-reloader.js:444:79)
    at Compiler.applyPlugins (/Users/project/node_modules/tapable/lib/Tapable.js:61:14)
    at Watching._done (/Users/project/node_modules/next/node_modules/webpack/lib/Compiler.js:104:17)
    at compiler.emitRecords.err (/Users/project/node_modules/next/node_modules/webpack/lib/Compiler.js:78:19)
    at Compiler.emitRecords (/Users/project/node_modules/next/node_modules/webpack/lib/Compiler.js:375:38)
    at compiler.emitAssets.err (/Users/project/node_modules/next/node_modules/webpack/lib/Compiler.js:61:20)
    at applyPluginsAsyncSeries1.err (/Users/project/node_modules/next/node_modules/webpack/lib/Compiler.js:368:12)
    at next (/Users/project/node_modules/tapable/lib/Tapable.js:218:11)
    at Compiler.afterEmit (/Users/project/node_modules/stylelint-webpack-plugin/lib/run-compilation.js:52:5)
    at next (/Users/project/node_modules/tapable/lib/Tapable.js:220:14)
    at Compiler.<anonymous> (/Users/project/node_modules/next/dist/server/hot-reloader.js:432:19)
    at next (/Users/project/node_modules/tapable/lib/Tapable.js:220:14)
    at Compiler.compiler.plugin (/Users/project/node_modules/next/node_modules/webpack/lib/performance/SizeLimitsPlugin.js:99:4)
    at next (/Users/project/node_modules/tapable/lib/Tapable.js:220:14)
    at /Users/project/node_modules/next/dist/server/build/plugins/unlink-file-plugin.js:98:18
    at <anonymous>
(node:30515) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:30515) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
## Expected Behavior
stylelint-webpack-plugin should work with webpack config defined in next.config.js

## Current Behavior
The stylelint-webpack-plugin complains about an uncaught property 'reasons' and displays the initial linting warnings/errors. Not working for subsequent reloads as a result

## Steps to Reproduce (for bugs)
1. Install stylelint, stylelint-webpack-plugin
2. Configure StyleLintPlugin in next.config.js
3. Run program and observe error after webpack config is loaded in

## Context
Linting usage for dev purposes

## Your Environment

| Tech    | Version |
|---------|---------|
| next    | 4.2.2 |
| node    | 3.10.10 |
| OS      | macos  |

**Comment by lededje** [comment]
Can you post your next.config.js so we can reproduce?

**Comment by bryan** [comment]
Here you go.

```
const webpack = require('webpack');
const fs = require('fs');
const path = require('path');
const glob = require('glob');
var StyleLintPlugin = require('stylelint-webpack-plugin');

module.exports = {
  poweredByHeader: false,
  webpack: (config, {dev}) => {
    config.plugins.push(
      new webpack.DefinePlugin({
        'process.env.NODE_ENV': JSON.stringify(process.env.NODE_ENV),
      }),
      new StyleLintPlugin({
        configFile: path.resolve(__dirname, './.stylelintrc'),
        files: '**/*.css',
      }),
    );

    config.plugins = config.plugins.filter(
      (plugin) => (plugin.constructor.name !== 'UglifyJsPlugin')
    )

    config.module.rules.push(
      {
        test: /\.(css|scss)/,
        loader: 'emit-file-loader',
        options: {
          name: 'dist/[path][name].[ext]'
        }
      },
      {
        test: /\.css$/,
        use: ['babel-loader', 'raw-loader', 'postcss-loader']
      },
      {
        test: /\.s(a|c)ss$/,
        use: ['babel-loader', 'raw-loader', 'postcss-loader',
          { loader: 'sass-loader',
            options: {
              includePaths: ['styles', 'node_modules']
                .map((d) => path.join(__dirname, d))
                .map((g) => glob.sync(g))
                .reduce((a, c) => a.concat(c), [])
            }
          }
        ]
      },
      {
        test: /\.(eot|woff|woff2|svg|ttf)([\?]?.*)$/,
        loader: "file-loader"
      },
      {
        test: /\.(eot|woff|woff2|svg|ttf|jpg|png)$/,
        loader: 'url-loader',
        options: {
          limit: 25000,
        }
      },
      {
        test: /\.jsx$|\.js$/,
        enforce: 'pre',
        exclude: /node_modules/,
        loader: 'eslint-loader',
        options: {
          emitWarning: dev,
        },
      }
    )

    return config;
  },
};

```

**Comment by bryan** [comment]
@timneutkens Still running into the hot-reloader error after upgrade to v5.0, any idea?

https://github.com/zeit/next.js/blob/7a1d9c18a39860f5711446595543468bfbdef04e/server/hot-reloader.js#L148-L153
