### ISSUE TITLE
Running next globally > `The module 'react' was not found.`

### ISSUE THREAD

**Issue by vjpr** [zeit/next.js#3585]
```
npm i -g next

mkdir test

cd test

npm i -S react react-dom

next

The module 'react' was not found. Next.js requires that you include it in 'dependencies' of your 'package.json'. To add it, run 'npm install --save react'
The module 'react-dom' was not found. Next.js requires that you include it in 'dependencies' of your 'package.json'. To add it, run 'npm install --save react-dom'
Error: Cannot find module 'react'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/Vaughan/nvm/versions/node/v8.9.0/lib/node_modules/next/dist/server/render.js:383:14)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
```

The check is here:

https://github.com/zeit/next.js/blob/29c4035eb5ef093e415e3723e0f3e9b883864953/bin/next#L6-L15

Just checked the readme, and it seems you need to run from your npm-scripts. 

Maybe it is worth while that this error tells the user that they need to run it from their npm-scripts...

## Your Environment

| Tech    | Version |
|---------|---------|
| next    |   4.2.3      |
| node    |  8.9       |
| OS      |   macOS      |
| browser |         |
| etc     |         |

**Comment by Fallion** [comment]
Next should be run locally, not from a global script https://github.com/zeit/next.js/#setup
