### ISSUE TITLE
How to debug heap out of memory while building my app ?

### ISSUE THREAD

**Issue by jackmatrix** [zeit/next.js#3613]
Can't build my app. I am using Next 4.2.3. it throws

```
852459 ms: Mark-sweep 1206.0 (1434.3) -> 1203.5 (1434.3) MB, 1045.1 / 0.0 ms [allocation failure] [GC in old space requested].
  853443 ms: Mark-sweep 1203.5 (1434.3) -> 1203.5 (1434.3) MB, 984.0 / 0.0 ms [allocation failure] [GC in old space requested].
  854465 ms: Mark-sweep 1203.5 (1434.3) -> 1213.2 (1405.3) MB, 1022.4 / 0.0 ms [last resort gc].
  855426 ms: Mark-sweep 1213.2 (1405.3) -> 1223.0 (1405.3) MB, 960.5 / 0.0 ms [last resort gc].


<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x2f42f9fcfb51 <JS Object>
    1: visit [0x2f42f9f04381 <undefined>:5616] [pc=0x1b1ba4152345] (this=0x1ef03be1edc1 <a TreeWalker with map 0x38d60ce7feb1>,node=0x3d1af43180a1 <an AST_VarDef with map 0x3ef8ba838d91>,descend=0x1ef03bed3df1 <JS Function (SharedFunctionInfo 0x1e326cd40ff1)>)
    2: _visit [0x2f42f9f04381 <undefined>:~1337] [pc=0x1b1ba4131e0a] (this=0x1ef03be1edc1 <a TreeWalker with map 0x38d60ce7feb1>,node=0x...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
 1: node::Abort() [/usr/local/bin/node]
 2: node::FatalException(v8::Isolate*, v8::Local<v8::Value>, v8::Local<v8::Message>) [/usr/local/bin/node]
 3: v8::internal::V8::FatalProcessOutOfMemory(char const*, bool) [/usr/local/bin/node]
 4: v8::internal::Handle<v8::internal::JSFunction> v8::internal::Factory::New<v8::internal::JSFunction>(v8::internal::Handle<v8::internal::Map>, v8::internal::AllocationSpace) [/usr/local/bin/node]
 5: v8::internal::Factory::NewFunction(v8::internal::Handle<v8::internal::Map>, v8::internal::Handle<v8::internal::SharedFunctionInfo>, v8::internal::Handle<v8::internal::Context>, v8::internal::PretenureFlag) [/usr/local/bin/node]
 6: v8::internal::Factory::NewFunctionFromSharedFunctionInfo(v8::internal::Handle<v8::internal::SharedFunctionInfo>, v8::internal::Handle<v8::internal::Context>, v8::internal::PretenureFlag) [/usr/local/bin/node]
 7: v8::internal::Runtime_NewClosure_Tenured(int, v8::internal::Object**, v8::internal::Isolate*) [/usr/local/bin/node]
 8: 0x1b1ba01092a7
got signal SIGABRT, exiting
error Command failed with exit code 1.
```

this is the log generated by npm 

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'run', 'build' ]
2 info using npm@5.4.0
3 info using node@v6.9.1
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle myproject@1.0.0~prebuild: myproject@1.0.0
6 info lifecycle myproject@1.0.0~build: myproject@1.0.0
7 verbose lifecycle myproject@1.0.0~build: unsafe-perm in lifecycle true
8 verbose lifecycle myproject@1.0.0~build: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/Users/MyName/Desktop/local/app/node_modules/.bin:/Users/MyName/.rvm/gems/jruby-1.7.19/bin:/Users/MyName/.rvm/gems/jruby-1.7.19@global/bin:/Users/MyName/.rvm/rubies/jruby-1.7.19/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/git/bin:/Users/MyName/.rvm/bin
9 verbose lifecycle myproject@1.0.0~build: CWD: /Users/MyName/Desktop/local/app
10 silly lifecycle myproject@1.0.0~build: Args: [ '-c', 'next build' ]
11 silly lifecycle myproject@1.0.0~build: Returned: code: 1  signal: null
12 info lifecycle myproject@1.0.0~build: Failed to exec build script
13 verbose stack Error: myproject@1.0.0 build: `next build`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:280:16)
13 verbose stack     at emitTwo (events.js:106:13)
13 verbose stack     at EventEmitter.emit (events.js:191:7)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:106:13)
13 verbose stack     at ChildProcess.emit (events.js:191:7)
13 verbose stack     at maybeClose (internal/child_process.js:877:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
14 verbose pkgid myproject@1.0.0
15 verbose cwd /Users/MyName/Desktop/local/app
16 verbose Darwin 17.3.0
17 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "build"
18 verbose node v6.9.1
19 verbose npm  v5.4.0
20 error code ELIFECYCLE
21 error errno 1
22 error myproject@1.0.0 build: `next build`
22 error Exit status 1
23 error Failed at the myproject@1.0.0 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

i also have some dependencies issues since i've upgraded to react 16 (but still couldn't build when i was in react 15)

```
warning " > draft-convert@1.4.10" has incorrect peer dependency "react@^15.0.2".
warning " > draft-convert@1.4.10" has incorrect peer dependency "react-dom@^15.0.2".
warning " > react-no-ssr@1.1.0" has incorrect peer dependency "react@^0.14.0 || ^15.0.0".
warning " > react-sticky@6.0.1" has incorrect peer dependency "react@^15.3.0".
warning " > react-sticky@6.0.1" has incorrect peer dependency "react-dom@^15.3.0".
warning " > react-tag-input@4.7.2" has incorrect peer dependency "react@^0.14.0 || ^15.0.0-rc".
warning " > react-tag-input@4.7.2" has incorrect peer dependency "react-dom@^0.14.0 || ^15.0.0-rc".
warning " > sass-loader@6.0.6" has unmet peer dependency "webpack@^2.0.0 || >= 3.0.0-rc.0 || ^3.0.0".
warning " > semantic-ui-react@0.70.0" has incorrect peer dependency "react@>=0.14.0 <= 15".
warning " > semantic-ui-react@0.70.0" has incorrect peer dependency "react-dom@>=0.14.0 <= 15".
```

Impossible to find exactly what's causing this error. Very painful to debug.

Are there some people who already struggled with this issue ?

**Comment by lookapanda** [comment]
@jackmatrix Since you closed this issue again, may I asked what solved this for you?

**Comment by jackmatrix** [comment]
@lookapanda  I've already explained in a previous post. It was caused by some pages that i left blank (No code inside). So it's generating a kind of timeout error while building because next expecting js code inside each page file.

**Comment by lookapanda** [comment]
Your previous post was the original post of this issue, no explanation there ;)

Thanks for ellaborating!
