### ISSUE TITLE
Adding jest in .babelrc prevents next app from running

### ISSUE THREAD

**Issue by valnub** [zeit/next.js#3744]
I tried to add jest to my nextjs app. To do this, I simply added a babelrc file to my project root (see content below). The tests run now but my app won't start anymore.

- [x] I have searched the [issues](https://github.com/zeit/next.js/issues) of this repository and believe that this is not a duplicate.

## Expected Behavior
- `npm run dev` should start the app
- `npm test` should start jest testing

## Current Behavior
When the following babelrc file is added to project root...

```json
{
  "env" : {
    "test": {
      "presets": ["env", "react", "stage-2"],
      "plugins": ["transform-export-extensions"],
      "only": [
        "./**/*.js",
        "node_modules/jest-runtime"
      ]
    }
  }
}
```

... `npm test` runs fine but `npm run dev` fails giving this error:

```shell
ERROR  Failed to compile with 1 errors                                                                                                                                 12:28:08

error  in ./pages/_document.js?entry

Syntax Error: Unexpected token (29:6)

  27 |   render() {
  28 |     return (
> 29 |       <html lang={this.props.local.lang_short_value}>
     |       ^
  30 |         <Head />
  31 |         <body>
  32 |           <Main />

 @ multi ./pages/_document.js?entry

{ Error: Cannot find module /web/.next/dist/pages/_document
    at _callee$ (/web/node_modules/next/dist/server/resolve.js:220:19)
    at tryCatch (/web/node_modules/regenerator-runtime/runtime.js:62:40)
    at Generator.invoke [as _invoke] (/web/node_modules/regenerator-runtime/runtime.js:296:22)
    at Generator.prototype.(anonymous function) [as next] (/web/node_modules/regenerator-runtime/runtime.js:114:21)
    at step (/web/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at /web/node_modules/babel-runtime/helpers/asyncToGenerator.js:28:13
    at <anonymous> code: 'ENOENT' }
```

[Reading the docs](https://github.com/zeit/next.js/#customizing-babel-config), I found out that the babelrc file needs `"presets": ["next/babel", "env"]`. So I changed the babelrc file to this:

```json
{
  "env" : {
    "dev": {
      "presets": ["next/babel", "env"]
    },
    "test": {
      "presets": ["env", "react", "stage-2"],
      "plugins": ["transform-export-extensions"],
      "only": [
        "./**/*.js",
        "node_modules/jest-runtime"
      ]
    }
  }
}
```

But this still doesn't work. Did I miss something?

## Steps to Reproduce (for bugs)
- Use the babelrc and package.json provided
- run `npm run dev`

### package.json

```json
{
  "scripts": {
    "dev": "next",
    "build": "next build",
    "start": "next start",
    "test": "jest"
  },
  "jest": {
    "transform": {
      "^.+\\.js?$": "babel-jest"
    },
    "transformIgnorePatterns": [
      "!node_modules/react-runtime"
    ]
  },
  "devDependencies": {
    "babel-jest": "^22.1.0",
    "babel-plugin-transform-export-extensions": "^6.22.0",
    "babel-preset-env": "^1.6.1",
    "babel-preset-react": "^6.24.1",
    "babel-preset-stage-2": "^6.24.1",
    "enzyme": "^3.3.0",
    "enzyme-adapter-react-16": "^1.1.1",
    "eslint": "^4.17.0",
    "eslint-config-airbnb": "^16.1.0",
    "eslint-plugin-import": "^2.8.0",
    "eslint-plugin-jsx-a11y": "^6.0.3",
    "eslint-plugin-react": "^7.5.1",
    "jest": "^22.1.4",
    "react-test-renderer": "^16.2.0"
  },
  "dependencies": {
    "apollo-cache-inmemory": "^1.1.7",
    "apollo-client": "^2.2.3",
    "apollo-client-preset": "^1.0.8",
    "apollo-link": "^1.1.0",
    "apollo-link-error": "^1.0.5",
    "apollo-link-http": "^1.3.3",
    "bcryptjs": "^2.4.3",
    "graphql": "^0.12.3",
    "graphql-tag": "^2.7.3",
    "moment": "^2.20.1",
    "next": "^4.2.3",
    "node-fetch": "^1.7.3",
    "prop-types": "^15.6.0",
    "radium": "^0.19.6",
    "react": "^16.2.0",
    "react-apollo": "^2.0.4",
    "react-autosuggest": "^9.3.3",
    "react-dom": "^16.2.0",
    "react-id-swiper": "^1.5.8",
    "react-touch-events": "^2.1.0",
    "styled-jsx": "^2.2.4"
  }
}
```

## Your Environment

| Tech    | Version |
|---------|---------|
| next    |   ^4.2.3      |
| node    |    9.3.0     |
| OS      |     macOS 10.13.3    |
| browser |    Chrome     |
| etc     |   See package.json      |

What's wrong? :-(

**Comment by Fallion** [comment]
You need to set the NODE_ENV to be 'dev'.

**Comment by valnub** [comment]
@Fallion Ahhhh, thanks!! :-)

For any follow-ups: I changed the dev script in package.json to this:

```
"dev": "export NODE_ENV=dev && next",
```

**Comment by Fallion** [comment]
@valnub Watch out. Your babelrc might break on Production as well.

**Comment by valnub** [comment]
@Fallion Thanks, I already fixed that as well :-)
