### ISSUE TITLE
Can next.js (v5) works with OnsenUI?

### ISSUE THREAD

**Issue by CrisLi** [zeit/next.js#3772]
- [ ] I have searched the [issues](https://github.com/zeit/next.js/issues) of this repository and believe that this is not a duplicate.

## Expected Behavior
Want to use Next.js in a mobile webapp, OnsenUI component is very rich. Want to use it with Next.js.

## Current Behavior
OnsenUI can't SSR. `window is not defined` error.

```
ReferenceError: window is not defined
    at window (/Users/chris/Projects/my-projects/home_seek/frontend/node_modules/core/src/ons/styler.js:27:18)
    at /Users/chris/Projects/my-projects/home_seek/frontend/node_modules/core/src/ons/styler.js:26:16
    at onsElements (/Users/chris/Projects/my-projects/home_seek/frontend/node_modules/onsenui/js/onsenui.js:4:82)
    at Object.<anonymous> (/Users/chris/Projects/my-projects/home_seek/frontend/node_modules/onsenui/js/onsenui.js:7:2)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at /Users/chris/Projects/my-projects/home_seek/frontend/node_modules/react-onsenui/dist/react-onsenui.js:4:145
    at Object.<anonymous> (/Users/chris/Projects/my-projects/home_seek/frontend/node_modules/react-onsenui/dist/react-onsenui.js:7:2)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
```

## Steps to Reproduce (for bugs)
```
import * as Ons from 'react-onsenui';
export default ({ handleClick }) => (
  <div>
    <Ons.Page>
      <Ons.Button onClick={handleClick}>Tap me!</Ons.Button>
    </Ons.Page>
  </div>
);
```

**Comment by timneutkens** [comment]
Components that depend on window can't be rendered on the server. So you can file an issue on OnsenUI's repository. Unfortunately there's nothing we can do on our side to aid compatibility like this.

**Comment by CrisLi** [comment]
@timneutkens  thanks timneutkens

**Comment by flieks** [comment]
@CrisLi @timneutkens  what about using `next export` to get the static pages.
I'm also interested in reusing my existing nextjs website together with onsen

**Comment by kissk01** [comment]
In componentDidMount add something like: 
`const reactOns = require('react-onsenui')`
And then similarly in componentDidMount you can have onsen components like: 
`Page = reactOns.Page //etc`

And then you can use onsen component in render:
```
<Page>...
</Page>
```
