### ISSUE TITLE
Cannot run next -- module missing

### ISSUE THREAD

**Issue by EmptyCrown** [zeit/next.js#3833]
Hello, I'm trying to get a simple next app to work, and somehow I started getting the follow error, even though `extract-text-webpack-plugin` is installed. I *believe* this started happening after I ran `npm install -g next`. 

```
Error: Cannot find module 'extract-text-webpack-plugin'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/jesse/Documents/next.config.js:3:27)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at loadConfig (/Users/jesse/Documents/next-with-antd/node_modules/next/dist/server/config.js:57:28)
    at getConfig (/Users/jesse/Documents/next-with-antd/node_modules/next/dist/server/config.js:40:20)
    at new HotReloader (/Users/jesse/Documents/next-with-antd/node_modules/next/dist/server/hot-reloader.js:119:40)
    at Server.getHotReloader (/Users/jesse/Documents/next-with-antd/node_modules/next/dist/server/index.js:157:14)
```

Here is my `.babelrc`:
```
{
  "plugins": [
    [
      "inline-import",
      {
        "extensions": [".css"]
      }
    ]
  ],
  "presets": ["next/babel"],
  "ignore": []
}
```

And my `package.json`:
```
{
  "name": "next-with-antd",
  "version": "1.0.0",
  "repository": "https://github.com/hanpama/next-with-antd",
  "description": "",
  "keywords": [],
  "author": "Max Choi",
  "scripts": {
    "dev": "next",
    "build": "next build",
    "start": "next start"
  },
  "license": "ISC",
  "dependencies": {
    "antd": "^3.0.0",
    "babel-plugin-inline-import": "^2.0.6",
    "extract-text-webpack-plugin": "^3.0.2",
    "next": "latest",
    "react": "^16.2.0",
    "react-dom": "^16.2.0"
  }
}
```

**Comment by saitonakamura** [comment]
What's the version of the npm you're using?

**Comment by timneutkens** [comment]
It's recommended to use next locally instead of installing it global.
