### ISSUE TITLE
Next.js Unable to Resolve Linked Module

### ISSUE THREAD

**Issue by dcalhoun** [zeit/next.js#3841]
Next.js fails to compile whenever a module is linked locally using [`yarn link`](https://yarnpkg.com/en/docs/cli/link). This is a reissue of #1244.

- [x] I have searched the [issues](https://github.com/zeit/next.js/issues) of this repository and believe that this is not a duplicate.

## Expected Behavior
Next.js successfully imports dependencies that are linked via yarn/npm.

## Current Behavior
Next.js fails to import linked dependencies and fails to compile.

```
yarn run v1.3.2
$ next
Error: Cannot find module 'lodash'
    at Function.Module._resolveFilename (module.js:538:15)
    at Function.Module._load (module.js:468:25)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/username/Sites/oss/nextjs-linked-module/node_modules/write-file-webpack-plugin/src/index.js:6:1)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/username/Sites/oss/nextjs-linked-module/node_modules/next/dist/server/build/webpack.js:55:31)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

## Steps to Reproduce (for bugs)
1. Clone [`lodash`](https://github.com/lodash/lodash).
1. Link `lodash` via `cd path/to/lodash && yarn link`.
1. Clone [linked module test case](https://github.com/dcalhoun/nextjs-linked-module) in a separate location.
1. Link `lodash` for the test case via `cd path/to/nextjs-linked-module && yarn install && yarn link lodash`.
1. `yarn start`

## Context
I need to have a local module linked so that I may actively develop it and have a Next.js project utilize the local module.

## Your Environment

| Tech    | Version |
|---------|---------|
| next    | 5.0.1-canary.2        |
| node    |    8.9.4     |
| OS      |  macOS 10.13.1       |
| browser |  Chrome 64.0.3282.167       |

**Comment by dcalhoun** [comment]
@timneutkens unfortunately, this issue has become a major blocker for me to share code between projects. Any thoughts on what might be causing this issue? Is there a particular place in the Next.js source where I might investigate this myself? Thanks in advance.

**Comment by timneutkens** [comment]
`"main": "lodash.js"` there is no lodash.js without building lodash, hence it breaks saying lodash doesn't exist.

**Comment by dcalhoun** [comment]
😞 You are correct. My issues likely spawn from mistakes outside of Next.js. I'll close this issue while I investigate my problem further.

Sorry for wasting your time. I appreciate your help!
