### ISSUE TITLE
example using-nerv not working

### ISSUE THREAD

**Issue by lipp** [zeit/next.js#3868]
The using-nerv example is not working

- [x] I have searched the [issues](https://github.com/zeit/next.js/issues) of this repository and believe that this is not a duplicate.

## Expected Behavior

can start the example server

## Current Behavior

Getting error: 

```
> using-nerv@1.0.0 start /Users/preuss/next.js/examples/using-nerv
> NODE_ENV=production node server.js

module.js:557
    throw err;
    ^

Error: Cannot find module 'nervjs/server'
    at Function.Module._resolveFilename (module.js:555:15)
    at Function.Module._resolveFilename (/Users/preuss/next.js/examples/using-nerv/node_modules/module-alias/index.js:43:29)
    at Function.Module._load (module.js:482:25)
    at Module.require (module.js:604:17)
```

## Steps to Reproduce (for bugs)

1. cd examples/using-nerv
2. npm i
3. npm run build && npm run start

## Your Environment

| Tech    | Version |
|---------|---------|
| next    |    latest (5.0.0)     |
| node    |     9.4.0    |
| OS      |     osx    |

**Comment by timneutkens** [comment]
Looks like nerv/server was moved into a package called `nerv-server`: https://github.com/NervJS/nerv/tree/master/packages/nerv-server

**Comment by lipp** [comment]
I added the react-dom/server alias accordingly:
https://github.com/lipp/next.js/commit/a2aec2caf37bddccdd8f02e4b7ec5ad953b312a5

however, nerv seems to not set `.isReactComponent` properly. I created an issue at nerv repo https://github.com/NervJS/nerv/issues/43

(When removing the `.isReactComponent` check, the example seems to work)

**Comment by etiennemtl** [comment]
Any news on this? We really need nevjs with nextjs as we need to support IE8 😓

**Comment by timneutkens** [comment]
Feel free to figure it out and contribute back to the example.

**Comment by etiennemtl** [comment]
Well right now, I've came back to the same issue as @gpolyn got where next complain about _document.js not having the `. isReactComponent ` property set.
