### ISSUE TITLE
Error when run production build use custom server with express. 

### ISSUE THREAD

**Issue by naijab** [zeit/next.js#3875]
- [x] I have searched the [issues](https://github.com/zeit/next.js/issues) of this repository and believe that this is not a duplicate.

## Expected Behavior
I try to do
* Run production build use custom server with express 
* Jest Test

## Current Behavior
* I can run next in development mode with `node server.js`
* Jest Test ( Jest is ok, run normally)

After next build, I try to start custom server with express with
 `NODE_ENV=production node server.js`

This is log
```
TypeError: Cannot read property 'toLowerCase' of undefined
    at a.renderDOM (/home/naijab/freelance/neogamer/frontend/gamerui/src/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:36:391)
    at a.render (/home/naijab/freelance/neogamer/frontend/gamerui/src/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:36:228)
    at a.read (/home/naijab/freelance/neogamer/frontend/gamerui/src/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:35:250)
    at renderToStaticMarkup (/home/naijab/freelance/neogamer/frontend/gamerui/src/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:44:75)
    at _callee3$ (/home/naijab/freelance/neogamer/frontend/gamerui/src/node_modules/next/dist/server/render.js:223:100)
    at tryCatch (/home/naijab/freelance/neogamer/frontend/gamerui/src/node_modules/regenerator-runtime/runtime.js:62:40)
    at Generator.invoke [as _invoke] (/home/naijab/freelance/neogamer/frontend/gamerui/src/node_modules/regenerator-runtime/runtime.js:296:22)
    at Generator.prototype.(anonymous function) [as next] (/home/naijab/freelance/neogamer/frontend/gamerui/src/node_modules/regenerator-runtime/runtime.js:114:21)
    at step (/home/naijab/freelance/neogamer/frontend/gamerui/src/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at /home/naijab/freelance/neogamer/frontend/gamerui/src/node_modules/babel-runtime/helpers/asyncToGenerator.js:28:13
    at <anonymous>
```
## Steps to Reproduce (for bugs)
1. `yarn build` --> `next build`
2. `yarn start` --> `NODE_ENV=production node server.js`
3.  Point a browser to http://localhost:3000
4. Show 500 errors flash An unexpected error has occurred.

## Context
When start production build, internal server errors cause an unwanted flash of content.

## Your Environment

| Tech    | Version |
|---------|---------|
| next    |     5.0 |
| node    |    8.9|
| OS      | Ubuntu|
| browser |   Chrome 64 |
| etc     |         |

**Comment by timneutkens** [comment]
This error is usually because you tried to render a component the is actually `undefined`. this can be because you tried to import a component that doesn't exists. Please check that out, it's impossible to reproduce without seeing your code.

**Comment by JasonJJFS** [comment]
I am having this issue too now, just can't see what is causing this, AFAIK I have no missing components.
