### ISSUE TITLE
'Module not found' for next/config in typescript next project

### ISSUE THREAD

**Issue by brandonmp** [zeit/next.js#3931]
- [x] I have searched the [issues](https://github.com/zeit/next.js/issues?q=is%3Aissue) of this repository and believe that this is not a duplicate.

## Expected Behavior
`import getConfig from 'next/config'` should work in accordance w/ readme 

## Current Behavior
Running `now` (and `next build`) produces the following build error
```
> Failed to build
> { Error: (client) ./config/env.ts
> Module not found: Error: Can't resolve 'node_modules/next/config.js' in '/home/nowuser/src/config'
> resolve 'node_modules/next/config.js' in '/home/nowuser/src/config'
>   Parsed request is a module
>   using description file: /home/nowuser/src/package.json (relative path: ./config)
>     Field 'browser' doesn't contain a valid alias configuration
>   after using description file: /home/nowuser/src/package.json (relative path: ./config)
>     resolve as module
>       looking for modules in /home/nowuser/src/node_modules/next/node_modules
>         using description file: /home/nowuser/src/node_modules/next/package.json (relative path: ./node_modules)
>           Field 'browser' doesn't contain a valid alias configuration
>         after using description file: /home/nowuser/src/node_modules/next/package.json (relative path: ./node_modules)
>           using description file: /home/nowuser/src/node_modules/next/package.json (relative path: ./node_modules/node_modules/next/config.js)
>             no extension
>               Field 'browser' doesn't contain a valid alias configuration
>               /home/nowuser/src/node_modules/next/node_modules/node_modules/next/config.js doesn't exist
>             .js
>               Field 'browser' doesn't contain a valid alias configuration
>               /home/nowuser/src/node_modules/next/node_modules/node_modules/next/config.js.js doesn't exist
>             .jsx
>               Field 'browser' doesn't contain a valid alias configuration
>               /home/nowuser/src/node_modules/next/node_modules/node_modules/next/config.js.jsx doesn't exist
>             .json
>               Field 'browser' doesn't contain a valid alias configuration
>               /home/nowuser/src/node_modules/next/node_modules/node_modules/next/config.js.json doesn't exist
>             .ts
>               Field 'browser' doesn't contain a valid alias configuration
>               /home/nowuser/src/node_modules/next/node_modules/node_modules/next/config.js.ts doesn't exist
>             .tsx
>               Field 'browser' doesn't contain a valid alias configuration
>               /home/nowuser/src/node_modules/next/node_modules/node_modules/next/config.js.tsx doesn't exist
>             as directory
>               /home/nowuser/src/node_modules/next/node_modules/node_modules/next/config.js doesn't exist
>       /home/nowuser/src/config/node_modules doesn't exist or is not a directory
>       /home/nowuser/node_modules doesn't exist or is not a directory
>       /home/node_modules doesn't exist or is not a directory
>       /node_modules doesn't exist or is not a directory
>       looking for modules in /home/nowuser/src/node_modules
>         using description file: /home/nowuser/src/package.json (relative path: ./node_modules)
>           Field 'browser' doesn't contain a valid alias configuration
>         after using description file: /home/nowuser/src/package.json (relative path: ./node_modules)
>           using description file: /home/nowuser/src/package.json (relative path: ./node_modules/node_modules/next/config.js)
>             no extension
>               Field 'browser' doesn't contain a valid alias configuration
>               /home/nowuser/src/node_modules/node_modules/next/config.js doesn't exist
>             .js
>               Field 'browser' doesn't contain a valid alias configuration
>               /home/nowuser/src/node_modules/node_modules/next/config.js.js doesn't exist
>             .jsx
>               Field 'browser' doesn't contain a valid alias configuration
>               /home/nowuser/src/node_modules/node_modules/next/config.js.jsx doesn't exist
>             .json
>               Field 'browser' doesn't contain a valid alias configuration
>               /home/nowuser/src/node_modules/node_modules/next/config.js.json doesn't exist
>             .ts
>               Field 'browser' doesn't contain a valid alias configuration
>               /home/nowuser/src/node_modules/node_modules/next/config.js.ts doesn't exist
>             .tsx
>               Field 'browser' doesn't contain a valid alias configuration
>               /home/nowuser/src/node_modules/node_modules/next/config.js.tsx doesn't exist
>             as directory
>               /home/nowuser/src/node_modules/node_modules/next/config.js doesn't exist
> [/home/nowuser/src/node_modules/next/node_modules/node_modules/next/config.js]
> [/home/nowuser/src/node_modules/next/node_modules/node_modules/next/config.js.js]
> [/home/nowuser/src/node_modules/next/node_modules/node_modules/next/config.js.jsx]
> [/home/nowuser/src/node_modules/next/node_modules/node_modules/next/config.js.json]
> [/home/nowuser/src/node_modules/next/node_modules/node_modules/next/config.js.ts]
> [/home/nowuser/src/node_modules/next/node_modules/node_modules/next/config.js.tsx]
> [/home/nowuser/src/node_modules/next/node_modules/node_modules/next/config.js]
> [/home/nowuser/src/config/node_modules]
> [/home/nowuser/node_modules]
> [/home/node_modules]
> [/node_modules]
> [/home/nowuser/src/node_modules/node_modules/next/config.js]
> [/home/nowuser/src/node_modules/node_modules/next/config.js.js]
> [/home/nowuser/src/node_modules/node_modules/next/config.js.jsx]
> [/home/nowuser/src/node_modules/node_modules/next/config.js.json]
> [/home/nowuser/src/node_modules/node_modules/next/config.js.ts]
> [/home/nowuser/src/node_modules/node_modules/next/config.js.tsx]
> [/home/nowuser/src/node_modules/node_modules/next/config.js]
>  @ ./config/env.ts 4:16-54
>  @ ./config/index.ts
>  @ ./pages-code/login/make-linkedin-url.ts
>  @ ./pages/login.js
>  @ multi ./pages/login.js
>     at /home/nowuser/src/node_modules/next/dist/server/build/index.js:207:31
>     at runWithDependencies (/home/nowuser/src/node_modules/webpack/lib/MultiCompiler.js:154:4)
>     at /home/nowuser/src/node_modules/webpack/node_modules/async/dist/async.js:1126:9
>     at /home/nowuser/src/node_modules/webpack/node_modules/async/dist/async.js:473:16
>     at iteratorCallback (/home/nowuser/src/node_modules/webpack/node_modules/async/dist/async.js:1050:13)
>     at /home/nowuser/src/node_modules/webpack/node_modules/async/dist/async.js:958:16
>     at /home/nowuser/src/node_modules/webpack/node_modules/async/dist/async.js:1123:13
>     at runCompilers (/home/nowuser/src/node_modules/webpack/lib/MultiCompiler.js:96:47)
>     at fn (/home/nowuser/src/node_modules/webpack/lib/MultiCompiler.js:101:6)
>     at compiler.run (/home/nowuser/src/node_modules/webpack/lib/MultiCompiler.js:150:5)
>     at emitRecords.err (/home/nowuser/src/node_modules/webpack/lib/Compiler.js:265:13)
>     at Compiler.emitRecords (/home/nowuser/src/node_modules/webpack/lib/Compiler.js:371:38)
>     at emitAssets.err (/home/nowuser/src/node_modules/webpack/lib/Compiler.js:258:10)
>     at applyPluginsAsyncSeries1.err (/home/nowuser/src/node_modules/webpack/lib/Compiler.js:364:12)
>     at next (/home/nowuser/src/node_modules/tapable/lib/Tapable.js:218:11)
>     at Compiler.compiler.plugin (/home/nowuser/src/node_modules/webpack/lib/performance/SizeLimitsPlugin.js:99:4)
```
## Steps to Reproduce (for bugs)
1. add `import getConfig from 'next/config'` in a project using `@zeit/next-typescript`
2. `next build`

the error doesn't present in development

## Context
I'm fairly new to typescript. a google shows this sort of error in different contexts, but the most common solution is to add `ts` to the webpack loader resolver. This is already done in `next`, though, so the solution is N/A.

I've also tried the following:
- change file importing from `next/config` to a `.js`
- `import * as getConfig from 'next/config'`
- `const getConfig = require('next/config')`
- `import getConfig from '../node_modules/next/dist/lib/runtime-config.js'`

Could this be b/c `@types/next` doesn't seem to have a `config` export?

## Your Environment

| Tech    | Version |
|---------|---------|
| next    |     5.0.1-canary.10   |
| node    |    on `now`, 8.9.4     |
| OS      |     `now`    |
| browser |      na   |
| @zeit/next-typescript |   0.0.10      |

**Comment by brandonmp** [comment]
np i'm fine to close it as i've worked around it in my project. i assume it'll resolve once @types/next is updated anyway

**Comment by intermund** [comment]
Hello guys,

I am getting an error when trying to import from 'next/config' --- Module not found: Error: Can't resolve 'next/config'

Where to look to solve this? 

Thank you for your help.

**Comment by brandonmp** [comment]
@intermund  are you using typescript?

**Comment by timneutkens** [comment]
Upgrade to next@canary. It's not released on the stable channel yet 👍

**Comment by djskinner** [comment]
@brandonmp how did you resolve it?

**Comment by djskinner** [comment]
I've tried various different variants of:

```
declare function getConfig(): void;

declare module "next/config" {
    export default getConfig;
}
```

Combined numerous different ways to write the import statement but I always end up with either `TS1192: Module '"next/config"' has no default export.` or `TypeError: __WEBPACK_IMPORTED_MODULE_0_next_config__ is not a function`

**Comment by timneutkens** [comment]
My earlier message:

> Not sure what to do about this, the types aren't maintained by us.

The types are maintained in definitely typed. They are maintained by the community and we didn't create them.

**Comment by AlexanderRichey** [comment]
I'm also having this problem, but I'm not using typescript.

**Comment by timneutkens** [comment]
@AlexanderRichey most likely you're not running next@canary. It's not released on master yet.

**Comment by elsigh** [comment]
I have this problem too.

Things work fine for me locally, but fails when I try to deploy with `now`. 

```
lsimon@lsimon-ltm:~/src/chartcomposer (elsigh) $ yarn install next@canary
yarn install v1.5.1
error An unexpected error occurred: "`install` has been replaced with `add` to add new dependencies. Run \"yarn add next@canary\" instead.".
info If you think this is a bug, please open a bug report with the information provided in "/Users/lsimon/src/chartcomposer/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
lsimon@lsimon-ltm:~/src/chartcomposer (elsigh) $ yarn add next@canary
yarn add v1.5.1
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 📃  Building fresh packages...
success Saved 1 new dependency.
info Direct dependencies
└─ next@5.1.0
info All dependencies
└─ next@5.1.0
✨  Done in 2.23s.
lsimon@lsimon-ltm:~/src/chartcomposer (elsigh) $ ./deploy.sh
> Deploying ~/src/chartcomposer under chartcomposer
> Using Node.js 8.10.0 (default)
> Ready! https://chartcomposer-hqrvsowraq.now.sh (copied to clipboard) [4s]
> Synced 1 file (150.59KB) [4s]
> Initializing…
> Building
> ▲ npm install
> ✓ Using "package-lock.json"
> ⧗ Installing 10 main dependencies…
> ▲ npm run build
> chartcomposer@0.0.1 build /home/nowuser/src
> next build
> Failed to build
> { Error: (client) ./components/Page.js
> Module not found: Error: Can't resolve 'next/config' in '/home/nowuser/src/components'
```

**Comment by elsigh** [comment]
I have `"next": "^5.1.0",` in `package.json` 

Locally, I have the file `node_modules/next/config.js`

I'm not using typescript either

**Comment by elsigh** [comment]
I think I'll open a new issue and nuke these comments as this doesn't seem typescript related.

**Comment by brandonmp** [comment]
my bad for checking-out on this one all. i ended up kicking `next/config` in favor of using `webpack.DefinePlugin`, which was trivial once universal webpack landed in next.

Basically, I have a file called `env.js` that runs during build server-side:

```
// env.js
const _ = require('lodash');

const envSpecificOverrides = {
    production: {
        SOME_KEY: 'BLAHBLAH'
    },
    development: {
        SOME_KEY: 'BLAHBLAH'
    }
};

// pull current env from environment, since that'll be defined by now.
const envParams = envSpecificOverrides[process.env.NODE_ENV];

const common = {
    linkedInClientId: LINKED_IN_CLIENT_ID,
    STRIPE_KEY: STRIPE_KEY_TEST
};
const env = { ...common, ...envParams };

module.exports = _.chain(env)
    .toPairs()
    .map(([k, v]) => [`process.env.${k}`, JSON.stringify(v)])
    .fromPairs()
    .value();
```

the result is a map of `{ "process.env.SomeVar": someValue }`. note that `process.env.` has to be in the key name b/c webpack needs that i guess?

anyway, in `next.config.js`, i then just push that to webpack plugins:

```
// next.config.js
const webpack = require('webpack');
const myEnv = require('./env.js')

// ...

config.plugins.push(new webpack.DefinePlugin(myEnv))
```
