### ISSUE TITLE
ReferenceError: document is not defined

### ISSUE THREAD

**Issue by lightninglu10** [zeit/next.js#3942]
I'm trying to use Next.js to render part of my app, but I keep getting 

```
ReferenceError: document is not defined
    at Object.<anonymous> (/Users/patricklu/Q5/lunyr/Lunyr-Frontend/node_modules/domkit/builtinStyle.js:3:18)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/patricklu/Q5/lunyr/Lunyr-Frontend/node_modules/domkit/getVendorPropertyName.js:3:20)
    at Module._compile (module.js:569:30)
```

There's no instance in my app where I reference domkit, but somehow it keeps showing up. I only have one page in my app, and I've gone so far as to change my render method to this:

```
render() {
    return (
      <div>
      </div>
    );
  }
}
```

But it's still not rendering properly.

- [x] I have searched the [issues](https://github.com/zeit/next.js/issues?q=is%3Aissue) of this repository and believe that this is not a duplicate.

## Expected Behavior

Renders fine.

## Current Behavior

Render error

## Your Environment

| Tech    | Version |
|---------|---------|
| next    |    5     |
| node    |    8.1.2     |
| OS      |    macOs     |
| browser |     Chrome    |
| etc     |         |

**Comment by timneutkens** [comment]
You're importing something that uses `document`, or referencing it somewhere. It's unrelated to Next.js.
