### ISSUE TITLE
With Apollo: server side error for queries using the url prop as variable

### ISSUE THREAD

**Issue by f2net** [zeit/next.js#4030]
- [ x] I have searched the [issues](https://github.com/zeit/next.js/issues?q=is%3Aissue) of this repository and believe that this is not a duplicate.

## Expected Behavior
Have the url prop on the server too, so that the "withData" hoc (as per the withApollo example) can use it to execute the query server-side

## Current Behavior
this.props.url is undefined on the server, so that SSR is done without data and I see the query done client-side (SSR HTML has just the app scheleton).

## Steps to Reproduce (for bugs)
```javascript
graphql(singleProduct, {
    options: ({ url }) => ({ 
      variables: {
        seoName: url.query.productSeoName,
        crossSellingLimit: 12
      } 
    }),
    props: ({ data: { loading, error, product } }) => ({
      loading,
      error,
      product
    })
  })(MyComponent)
```

## Error
error: TypeError: Cannot read property 'query' of undefined at options [...]

## Your Environment
Next 5.0.0
Apollo client 2.2.7
React 16.2

**Comment by f2net** [comment]
If it helps, I am using custom routes

**Comment by f2net** [comment]
If I log the URL in the getInitialProps I get the url correctly.

```javascript
    static async getInitialProps(ctx) {
      // Initial serverState with apollo (empty)
      let serverState

      // Evaluate the composed component's getInitialProps()
      let composedInitialProps = {}
      if (ComposedComponent.getInitialProps) {
        composedInitialProps = await ComposedComponent.getInitialProps(ctx)
      }

      const url = {
        pathname: ctx.pathname,
        query: ctx.query,
      } 

      // Run all GraphQL queries in the component tree
      // and extract the resulting data
      const apollo = initApollo()
      try {
        console.log('get Data from tree', url)
        // Run all GraphQL queries
        await getDataFromTree(<ComposedComponent ctx={ctx} {...url} {...composedInitialProps} />, {
          router: {
            asPath: ctx.asPath,
            pathname: ctx.pathname,
            query: ctx.query,
          },
          client: apollo,
        })
      } catch (error) {
        console.log('error:', error)
        // Prevent Apollo Client GraphQL errors from crashing SSR.
        // Handle them in components via the data.error prop:
        // http://dev.apollodata.com/react/api-queries.html#graphql-query-data-error
      }

      console.log('done')
      if (!process.browser) {
        // getDataFromTree does not call componentWillUnmount
        // head side effect therefore need to be cleared manually
        Head.rewind()
      }

      // Extract query data from the Apollo store
      serverState = {
        apollo: {
          data: apollo.cache.extract(),
        },
      }

      return {
        serverState,
        ...composedInitialProps,
      }
    }

```

When I log the URL on the options function ({ url } => options) of the graphql HOC, I see that on the server the url is undefined during the getDataFromTree and then it gets populated:

Here you see the logget URL:
```
get Data from tree { pathname: '/dettaglio-prodotto',
  query: 
   { categorySeoName: 'cellulite',
     productSeoName: 'somatoline-0-1--0-3-emulsione-cutanea-30-bustine' } }
```

Then I see (logged from the options function:
```
URL undefined
error: TypeError: Cannot read property 'query' of undefined
    at options (/Users/matteo/Documents/Development/greenfarmacia-website/.next/dist/bundles/pages/dettaglio-prodotto.js:5101:21)
    at GraphQL.shouldSkip (/Users/matteo/Documents/Development/greenfarmacia-website/node_modules/react-apollo/graphql.js:313:50)
    at GraphQL.componentWillMount (/Users/matteo/Documents/Development/greenfarmacia-website/node_modules/react-apollo/graphql.js:69:27)
    at walkTree (/Users/matteo/Documents/Development/greenfarmacia-website/node_modules/react-apollo/getDataFromTree.js:28:28)
    at walkTree (/Users/matteo/Documents/Development/greenfarmacia-website/node_modules/react-apollo/getDataFromTree.js:50:17)
    at walkTree (/Users/matteo/Documents/Development/greenfarmacia-website/node_modules/react-apollo/getDataFromTree.js:50:17)
    at walkTree (/Users/matteo/Documents/Development/greenfarmacia-website/node_modules/react-apollo/getDataFromTree.js:50:17)
    at getQueriesFromTree (/Users/matteo/Documents/Development/greenfarmacia-website/node_modules/react-apollo/getDataFromTree.js:71:5)
    at getDataFromTree (/Users/matteo/Documents/Development/greenfarmacia-website/node_modules/react-apollo/getDataFromTree.js:86:19)
    at Function._callee$ (/Users/matteo/Documents/Development/greenfarmacia-website/.next/dist/bundles/pages/dettaglio-prodotto.js:1134:76)
done
```

And then I have the URL:
```
URL { query: 
   { categorySeoName: 'cellulite',
     productSeoName: 'somatoline-0-1--0-3-emulsione-cutanea-30-bustine' },
  pathname: '/dettaglio-prodotto',
  asPath: '/prodotto/cellulite/somatoline-0-1--0-3-emulsione-cutanea-30-bustine',
  back: [Function: back],
  push: [Function: push],
  pushTo: [Function: pushTo],
  replace: [Function: replace],
  replaceTo: [Function: replaceTo] }
```

**Comment by Zn4rK** [comment]
The issue here is that your `getInitialProps` does not include your url object in the return of the function. 

The initial `getDataFromTree` works because you are spreading the url object onto the ComposedComponent. 

When React then tries to render your Component, it doesn't have the expected props.

If you change your above code to:
```js
[...]
        await getDataFromTree(<ComposedComponent ctx={ctx} url={url} {...composedInitialProps} />
[...]
```
and
```js
[...]
return {
  serverState,
  url,
  ...composedInitialProps,
}
```

It should work as you expect :)

It's explained [here](https://github.com/zeit/next.js#fetching-data-and-component-lifecycle) pretty well.

**Comment by f2net** [comment]
Thank you very much, @Zn4rK ! 👍

The not returning the value is a last-minute error. 
Before I added the url to the composedInitialProps, but again **spreaded** and that's why I didn't find the url object.

I ended up doing this

```javascript
// Evaluate the composed component's getInitialProps()
let composedInitialProps = {}
if (ComposedComponent.getInitialProps) {
  composedInitialProps = await ComposedComponent.getInitialProps(ctx)
}

const url = {
  pathname: ctx.pathname,
  query: ctx.query,
}

composedInitialProps = {
  ...composedInitialProps,
  url,
}

```

I think this could be added to the "withApollo" example code, as often the Apollo queries depend on URL params. What do you think? I may post a PR...

Thank you again

**Comment by julmot** [comment]
@f2net I've requested a documentation about this in #4491. Thanks for your code example, it helped me a lot.
