### ISSUE TITLE
Issue with `next export` with React Toolbox integration

### ISSUE THREAD

**Issue by fchengpc** [zeit/next.js#4062]
- [x] I have searched the [issues](https://github.com/zeit/next.js/issues?q=is%3Aissue) of this repository and believe that this is not a duplicate.

Been trying to figure out if this is possible. I following try this repo setup >> https://github.com/ooade/next-react-toolbox. Seem okay until i try the `next export` then I run into following error >>>
```
(function (exports, require, module, __filename, __dirname) { :root {
                                                                                                       ^
SyntaxError: Unexpected token :
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (../../../../../../index.js:20:14)```

Tried `[next-css](https://github.com/zeit/next-plugins/tree/master/packages/next-css)` 

## Your Environment
|---------|---------|
| next    |  5.1    |
| node    |   v8.10.0      |

any helper is helpful.

**Comment by timneutkens** [comment]
It's a community plugin, unrelated to Next.js.

There's also:
https://github.com/hanford/next-offline
https://github.com/ragingwind/next-workbox
