### ISSUE TITLE
Issue of  '' css is not defined ''

### ISSUE THREAD

**Issue by haha54carol** [zeit/next.js#4063]
Please help! It happened after I install next@5.1.0...

but work at previously version

```javascript
ReferenceError: css is not defined
    at Selection.render (D:\Git\Aquamarine\.next\dist\bundles\pages\webpack:\pages\home.js?ffe1:9:14)
    at resolve (D:\Git\Aquamarine\node_modules\react-dom\cjs\react-dom-server.node.development.js:2149:18)
    at ReactDOMServerRenderer.render (D:\Git\Aquamarine\node_modules\react-dom\cjs\react-dom-server.node.development.js:2260:22)
    at ReactDOMServerRenderer.read (D:\Git\Aquamarine\node_modules\react-dom\cjs\react-dom-server.node.development.js:2234:19)
    at renderToString (D:\Git\Aquamarine\node_modules\react-dom\cjs\react-dom-server.node.development.js:2501:25)
    at renderPage (D:\Git\Aquamarine\node_modules\next\dist\server\render.js:180:26)
    at Function.getInitialProps (D:\Git\Aquamarine\.next\dist\bundles\pages\_document.js:206:39)
    at _callee$ (D:\Git\Aquamarine\node_modules\next\dist\lib\utils.js:36:30)
    at tryCatch (D:\Git\Aquamarine\node_modules\babel-runtime\node_modules\regenerator-runtime\runtime.js:62:40)
    at Generator.invoke [as _invoke] (D:\Git\Aquamarine\node_modules\babel-runtime\node_modules\regenerator-runtime\runtime.js:296:22)
    at Generator.prototype.(anonymous function) [as next] (D:\Git\Aquamarine\node_modules\babel-runtime\node_modules\regenerator-runtime\runtime.js:114:21)
    at step (D:\Git\Aquamarine\node_modules\babel-runtime\helpers\asyncToGenerator.js:17:30)
    at D:\Git\Aquamarine\node_modules\babel-runtime\helpers\asyncToGenerator.js:35:14
    at new Promise (<anonymous>)
    at new F (D:\Git\Aquamarine\node_modules\core-js\library\modules\_export.js:35:28)
    at D:\Git\Aquamarine\node_modules\babel-runtime\helpers\asyncToGenerator.js:14:12
```
and my 
@zeit/next-less is v0.1.1
@zeit/next-css is v0.1.4

## Your Environment

| Tech    | Version |
|---------|---------|
| next    |      5.1.0   |
| node    |      v8.9.4   |

**Comment by haha54carol** [comment]
sorry, it's not about the version.
