### ISSUE TITLE
Problem with Migration from Next.js 4 to Next.js 5 - Cannot read property 'array' of undefined

### ISSUE THREAD

**Issue by janbaer** [zeit/next.js#4093]
I just wanted to migrate our project from Next.js 4 to Next.js 5.

But after the migration I get the following error.

Cannot read property 'array' of undefined

```
TypeError: Cannot read property 'array' of undefined
    at Object../node_modules/react-shortcut/src/Component.js (http://localhost:3000/_next/-/page/index.js:51275:27)
    at __webpack_require__ (http://localhost:3000/_next/-/manifest.js:715:31)
    at fn (http://localhost:3000/_next/-/manifest.js:118:20)
    at Object.<anonymous> (http://localhost:3000/_next/-/page/index.js:1943:73)
    at Object../components/page.js (http://localhost:3000/_next/-/page/index.js:2350:30)
    at __webpack_require__ (http://localhost:3000/_next/-/manifest.js:715:31)
    at fn (http://localhost:3000/_next/-/manifest.js:118:20)
    at Object.<anonymous> (http://localhost:3000/_next/-/page/index.js:56938:78)
    at Object../pages/index.js (http://localhost:3000/_next/-/page/index.js:57082:30)
    at __webpack_require__ (http://localhost:3000/_next/-/manifest.js:715:31)
```
So the website is no longer working.  When I switch back to the version 4, the error is gone.

We're using Next.js from a Koa-Webserver amd we're also using Mobx for the state management. For tests we're using Jest. That's why we need a custom **.babelrc**

```
{
  "env": {
    "development": {
      "presets": "next/babel",
      "plugins": [ "transform-decorators-legacy" ]
    },
    "production": {
      "presets": "next/babel",
      "plugins": [ "transform-decorators-legacy" ]
    },
    "test": {
      "presets": [
        ["env", { "modules": "commonjs" }],
        "next/babel"
      ],
      "plugins": [ "transform-decorators-legacy" ]
    }
  }
}
```

We had the problem with Next.js 5.0 and now also with 5.1
## Your Environment
I've here Node 9.3.0 installed together with the latest version of Koa.js but I assume that there error could have something todo with webpack. The version 4.2.3 from Next.js was working without any problems

Are there any known breaking changes between 4 and 5?

**Comment by timneutkens** [comment]
In the future please provide a way to reproduce. This is not an issue with Next.js. It's an issue with the library you're using, it's using the old `React.PropTypes`
https://github.com/devlato/react-hotkeys/blob/master/src/Component.js#L10
