### ISSUE TITLE
next run build failed

### ISSUE THREAD

**Issue by tujiaw** [zeit/next.js#4112]
window build is ok!

CentOS Linux release 7.3.1611 (Core)
node v9.11.0
npm 5.6.0

```
9 verbose lifecycle ningto@1.0.0~dev: CWD: /root/ningto
10 silly lifecycle ningto@1.0.0~dev: Args: [ '-c', 'next "-p" "3344"' ]
11 silly lifecycle ningto@1.0.0~dev: Returned: code: 137  signal: null
12 info lifecycle ningto@1.0.0~dev: Failed to exec dev script
13 verbose stack Error: ningto@1.0.0 dev: `next "-p" "3344"`
13 verbose stack Exit status 137
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:285:16)
13 verbose stack     at EventEmitter.emit (events.js:180:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:180:13)
13 verbose stack     at maybeClose (internal/child_process.js:936:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)
14 verbose pkgid ningto@1.0.0
15 verbose cwd /root/ningto
16 verbose Linux 3.10.0-514.21.1.el7.x86_64
17 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "dev" "--" "-p" "3344"
18 verbose node v9.11.0
19 verbose npm  v5.6.0
20 error code ELIFECYCLE
21 error errno 137
22 error ningto@1.0.0 dev: `next "-p" "3344"`
22 error Exit status 137
23 error Failed at the ningto@1.0.0 dev script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 137, true ]

```

**Comment by Njunge11** [comment]
Hey @timneutkens  , what exactly rans out of memory?
