### ISSUE TITLE
Peer dependency not correctly resolved in linked module

### ISSUE THREAD

**Issue by rovansteen** [zeit/next.js#4143]
I have a monorepo, containing a `create-react-app` application, a `next.js` application and a separate library. This library is linked (with `yarn link`) to the two applications and has `styled-components` as a peer dependency, which is installed in both the applications.

The linking works fine in the `create-react-app` application but in `next.js` it breaks resulting in the following error:

```
Error in @scrnhq/eurovision-elements
Module not found: Error: Can't resolve 'styled-components' in '/Users/robert/sites/eurovision/elements/dist'
ModuleNotFoundError: Module not found: Error: Can't resolve 'styled-components' in '/Users/robert/sites/eurovision/elements/dist'
    at factoryCallback (/Users/robert/sites/eurovision/pulse/node_modules/webpack/lib/Compilation.js:276:40)
    at factory (/Users/robert/sites/eurovision/pulse/node_modules/webpack/lib/NormalModuleFactory.js:235:20)
    at resolver (/Users/robert/sites/eurovision/pulse/node_modules/webpack/lib/NormalModuleFactory.js:60:20)
    at asyncLib.parallel (/Users/robert/sites/eurovision/pulse/node_modules/webpack/lib/NormalModuleFactory.js:127:20)
    at /Users/robert/sites/eurovision/pulse/node_modules/async/dist/async.js:3874:9
    at /Users/robert/sites/eurovision/pulse/node_modules/async/dist/async.js:473:16
    at iteratorCallback (/Users/robert/sites/eurovision/pulse/node_modules/async/dist/async.js:1048:13)
    at /Users/robert/sites/eurovision/pulse/node_modules/async/dist/async.js:958:16
    at /Users/robert/sites/eurovision/pulse/node_modules/async/dist/async.js:3871:13
    at resolvers.normal.resolve (/Users/robert/sites/eurovision/pulse/node_modules/webpack/lib/NormalModuleFactory.js:119:22)
    at onError (/Users/robert/sites/eurovision/pulse/node_modules/enhanced-resolve/lib/Resolver.js:65:10)
    at loggingCallbackWrapper (/Users/robert/sites/eurovision/pulse/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at runAfter (/Users/robert/sites/eurovision/pulse/node_modules/enhanced-resolve/lib/Resolver.js:158:4)
    at innerCallback (/Users/robert/sites/eurovision/pulse/node_modules/enhanced-resolve/lib/Resolver.js:146:3)
    at loggingCallbackWrapper (/Users/robert/sites/eurovision/pulse/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at next (/Users/robert/sites/eurovision/pulse/node_modules/tapable/lib/Tapable.js:252:11)
```

Installing `styled-components` inside this library is not possible as it has to be a peer dependency, see: https://www.styled-components.com/docs/faqs#i-am-a-library-author-should-i-bundle-styledcomponents-with-my-library

- [X] I have searched the [issues](https://github.com/zeit/next.js/issues?q=is%3Aissue) of this repository and believe that this is not a duplicate.

## Expected Behavior
`next.js` should resolve peer dependencies of linked modules in the correct way, meaning from the project's `node_modules` folder.

## Current Behavior
It looks like peer dependencies currently are not resolved from the correct place, as it looks like it's only looking at the folder (and parents) of the linked module itself.

## Steps to Reproduce (for bugs)
As this is a closed source project I can't share the source code or set up, but if necessary I can add a similar reproducible example later. 

## Your Environment

| Tech    | Version |
|---------|---------|
| next    | 5.1.0 |
| node    | 9.6.1 |
| OS      | 10.13.2 |

**Comment by timneutkens** [comment]
> As this is a closed source project I can't share the source code or set up, but if necessary I can add a similar reproducible example later.

Please do 🙏

**Comment by timneutkens** [comment]
This is probably because we don't compile the module into the server bundle but instead mark it as external, there's not much we can do for this in the short-term, long term we're planning to bundle node_modules in the server bundle for specific use cases.

**Comment by patwritescode** [comment]
@rovansteen did you ever find a workaround of any sort?
