### ISSUE TITLE
Working with SASS modules and SASS imports for components 

### ISSUE THREAD

**Issue by eugeneross** [zeit/next.js#4148]
After reading some different methods of utilizing CSS modules within Nextjs pages, I'm wanting to know if the same concept can be applied to components but with SASS. This is one of the examples I'm referencing to:

https://github.com/zeit/next.js/tree/canary/examples/with-next-sass

What I'm trying to achieve is something like this with the following file structure:

Reusable components are in a folder structure so both `.js` and `.sass` files are in the same area.
```
├── pages
│   ├── index.js
├── components
│   ├── Button
│   │   ├── index.js
│   │   ├── index.sass
```

Import components as usual...

```
// pages/index.js

import Button from 'components/Button'

...

<Button 
  className='book'
  text="I'm a button"
  href='/about'
/>

```

Import styles from the component's `sass` file, then pass the styles as properties with `styles.btn`

```
// components/Button/index.js

// Libraries
import React, { Component } from 'react'
import Link from 'next/link'

// Styles
import styles from './index.sass'

export default class Button extends Component {
    constructor(props) {
        super(props)
    }

    componentDidMount() {

    }

    render() {
        return (
            this.props.href
                ? (
                    <a className={styles.btn + this.props.className} target='_blank' href={this.props.href}>
                        {this.props.text}
                    </a>
                ) : (
                    <Link href={this.props.link}>
                        <a className={styles.btn + this.props.className}>
                            {this.props.text}
                        </a>
                    </Link>
                )
        )
    }
}




```
Button's styling.

```
// components/Button/index.sass

.btn
  color: red

```

My `next.config.js` setup:

```
const path = require('path')
const glob = require('glob')
const withSASS = require('@zeit/next-sass')

module.exports = withSASS({
  cssModules: true,
  distDir: 'public',

  exportPathMap: function () {
    return {
      "/": { page: "/" },
      "/about": { page: "/about" },
    }
  }, 

  webpack: (config, { dev }) => {
    return config
  }
})

```

The markup for the page renders, but styles aren't being applied and the class name has a weird string with it (book is the class passed in the Button properties):

```
<a class="EGxqjOug9lYuZ5fOMdFUbbook" target="_blank" href="/about">I'm a button</a>
```

With all of this, I have a couple of questions concerning this setup:

1. Is what I'm trying to achieve even possible to do at the moment?
2. Is this issue depending on how my `next.config.js` file is setup?
3. How would I be able to import other `sass` files from different directories into the `index.sass` of my component? For example, if I want to import breakpoint mixins into my button component, will that cause any issues with modules? 

- [x] I have searched the [issues](https://github.com/zeit/next.js/issues?q=is%3Aissue) of this repository and believe that this is not a duplicate.

**Comment by mgiraldo** [comment]
the garbled string is just the package doing a custom/unique name for that object. you can customize it like so:

```js
  withSass({
    cssModules: true,
    cssLoaderOptions: {
      localIdentName: "[name]__[local]___[hash:base64:5]"
    },
    webpack: (config, options) => { ... 
```

where the resulting class name will be something like `Button__btn___3xknZ`

also notice how you are adding (as in arithmetic addition) instead of concatenating the unique name to `this.props.className` and this might also explain the style not being applied. 

try:

```jsx
className={`${styles.btn} ${this.props.className}`}
```

**Comment by mgiraldo** [comment]
you need a [`_document.js`](https://github.com/zeit/next-plugins/tree/master/packages/next-sass#usage)

**Comment by timneutkens** [comment]
@mgiraldo thanks for solving the issue 😌

**Comment by mgiraldo** [comment]
@timneutkens the `_document.js` part bit me too. Maybe add a heading to that part saying **With or without CSS modules** or something? The reader's eyes gravitate to headings. Or maybe under each subheading (eg: right under “With CSS modules”) mention “Create your `_document.js`. Then...” because yo _do_ repeat the “Create a config/index” files parts.

**Comment by eugeneross** [comment]
@mgiraldo @timneutkens I got it to work with your recommendation for using the `_document.js` file. 

I get the follow error when trying to use a global stylesheet ([similar to this example](https://github.com/davibe/next.js-example-with-global-stylesheet)) and modules.

```
(node:7930) UnhandledPromiseRejectionWarning: Error: Module build failed: 
.btn 
^
      Invalid CSS after ";": expected 1 selector or at-rule, was "{}"
      in /Users/eugeneross/Sites/tortuga/components/Button/index.sass (line 1, column 2)
    at Object../components/Button/index.sass (/Users/eugeneross/Sites/tortuga/public/dist/bundles/pages/index.js:157:7)
    at __webpack_require__ (/Users/eugeneross/Sites/tortuga/public/dist/bundles/pages/webpack:/webpack/bootstrap d890c6fe2fb73bcb2826?0165:21:1)
    at Object../components/Button/index.js (/Users/eugeneross/Sites/tortuga/public/dist/bundles/pages/index.js:83:70)
    at __webpack_require__ (/Users/eugeneross/Sites/tortuga/public/dist/bundles/pages/webpack:/webpack/bootstrap d890c6fe2fb73bcb2826?0165:21:1)
    at Object../pages/index.js (/Users/eugeneross/Sites/tortuga/public/dist/bundles/pages/index.js:170:77)
    at __webpack_require__ (/Users/eugeneross/Sites/tortuga/public/dist/bundles/pages/webpack:/webpack/bootstrap d890c6fe2fb73bcb2826?0165:21:1)
    at Object.0 (/Users/eugeneross/Sites/tortuga/public/dist/bundles/pages/index.js:275:18)
    at __webpack_require__ (/Users/eugeneross/Sites/tortuga/public/dist/bundles/pages/webpack:/webpack/bootstrap d890c6fe2fb73bcb2826?0165:21:1)
    at /Users/eugeneross/Sites/tortuga/public/dist/bundles/pages/webpack:/webpack/bootstrap d890c6fe2fb73bcb2826?0165:68:1
    at Object.<anonymous> (/Users/eugeneross/Sites/tortuga/public/dist/bundles/pages/index.js:73:10)
    at Module._compile (module.js:649:30)
    at Object.Module._extensions..js (module.js:660:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:501:12)
    at Function.Module._load (module.js:493:3)
    at Module.require (module.js:593:17)
(node:7930) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 6)
```

When I comment out the [webpack config rules](https://github.com/numieco/tortuga/blob/2.0/next.config.js#L22) from that example mentioned before I'm able to get the project working, but within `<head>` I'm receiving this for the inline stylesheet:

```
<style>[object Object]</style>
```

This is probably becuase I commented out the loaders within the config. 

My main question is, how would I be able to handle imports for a componenet's sass file? Say I have the following sass file for a button:

```
.btn
  position: relative
  display: inline-block
  vertical-align: middle
  zoom: 1
  text-align: center
  padding: 1rem 1.3rem
  line-height: 1em
  font-size: .7rem
  font-weight: 700
  letter-spacing: 1px
  border-radius: 100px
  outline: none
  border: none
  text-transform: uppercase
  box-shadow: 0 1px 1px 0 rgba(0, 0, 0, 0.06)
  transition: all 0.25s cubic-bezier(0.25, 0.46, 0.45, 0.94)
  +medium-phone
    padding: 1rem 1.3rem
    font-size: .9rem
  ```
With my setup, this would error out due to that mixin not being imported into the file:

```
ModuleBuildError: Module build failed: ModuleBuildError: Module build failed: 
  +medium-phone
          ^
      No mixin named medium-phone
      in /Users/eugeneross/Sites/tortuga/components/Button/index.sass
```

If I were to import the file where that mixin exists I get this:
```
Module build failed: ModuleBuildError: Module build failed: 
@import 'utilities/breakpoints'
^
      Invalid CSS after ";": expected 1 selector or at-rule, was "{}"
      in /Users/eugeneross/Sites/tortuga/components/Button/index.sass
```

Now, thinking about how modules would work, there would be no point in importing that breakpoint file to every single component becuase that sass file would get compiled for everytime it's called within another file, right? Becuase of that, my approach is to have sass modules that only deal with the components style, then i can import the mixin rules to a global stylesheet. 

Ultimately, what I'm trying to accomplish is being able to use mixins from other files I've defined with components that I'll be styling.

[Updated repo](https://github.com/numieco/tortuga/blob/2.0/)

**Comment by sveggiani** [comment]
@eugeneross Hi! did you find a way to overcome this issue?

**Comment by richardblondet** [comment]
@eugeneross Hello! How did you end up solving this issue?

**Comment by MIRAMAXED** [comment]
@eugeneross Hi! Answer the questions above, please ^^^

**Comment by VaniaFed** [comment]
Hey! I still have this problem.

**Comment by balazsorban44** [comment]
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
