### ISSUE TITLE
Can not execute `with-relay-modern` according to README by error

### ISSUE THREAD

**Issue by andoromeda** [zeit/next.js#4251]
## Expected Behavior
works without problem.

## Current Behavior
An error occurs when `yarn relay` command is executed

I want to run with-relay-modern.
https://github.com/zeit/next.js/tree/canary/examples/with-relay-modern

So, I ran the command according to the steps of the README.
However, the following error occurs.

## Steps to Reproduce (for bugs)
```
$ yarn create next-app --example with-relay-modern with-relay-modern-app
$ cd with-relay-modern-app
$ yarn
$ yarn schema
$ yarn relay

yarn run v1.6.0
(node:4330) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
$ relay-compiler --src ./ --exclude '**/.next/**' '**/node_modules/**' '**/test/**'  '**/__generated__/**' --exclude './schema/**' --schema ./schema/schema.graphql
Error: Error loading schema. Expected the schema to be a .graphql or a .json
file, describing your GraphQL server's API. Error detail:

GraphQLError: Syntax Error GraphQL request (16:1) Unexpected String

15:
16: """A connection to a list of items."""
    ^
17: type BlogPostConnection {

    at syntaxError (/~/with-relay-modern/node_modules/graphql/error/syntaxError.js:30:15)
    at unexpected (/~/with-relay-modern/node_modules/graphql/language/parser.js:995:33)
    at parseDefinition (/~/with-relay-modern/node_modules/graphql/language/parser.js:154:9)
    at parseDocument (/~/with-relay-modern/node_modules/graphql/language/parser.js:108:22)
    at parse (/~/with-relay-modern/node_modules/graphql/language/parser.js:45:10)
    at getSchema (/~/with-relay-modern/node_modules/relay-compiler/bin/relay-compiler:259:28)
    at /~/with-relay-modern/node_modules/relay-compiler/bin/relay-compiler:102:19
    at Generator.next (<anonymous>)
    at step (/~/with-relay-modern/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at /~/with-relay-modern/node_modules/babel-runtime/helpers/asyncToGenerator.js:28:13
    at getSchema (/~/with-relay-modern/node_modules/relay-compiler/bin/relay-compiler:261:12)
    at /~/with-relay-modern/node_modules/relay-compiler/bin/relay-compiler:102:19
    at Generator.next (<anonymous>)
    at step (/~/with-relay-modern/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at /~/with-relay-modern/node_modules/babel-runtime/helpers/asyncToGenerator.js:28:13
    at process._tickCallback (internal/process/next_tick.js:178:7)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

```

## Your Environment

| Tech    | Version |
|---------|---------|
| next    | 6.0.0 |
| node    | v10.0.0 |
| OS      | MacOS 10.13.4 |
| browser |         |
| etc     |         |

**Comment by ohjeyong** [comment]
I fixed this by command "yarn upgrade --latest".

**Comment by maxbeatty** [comment]
I tried reproducing this with node 8 and 10 just now but everything worked great 🤷‍♂️

**Comment by timneutkens** [comment]
Let's close this then.
