### ISSUE TITLE
Cannot find module 'webpack/lib/Chunk'.  does not work on linux but does works locally

### ISSUE THREAD

**Issue by theskillwithin** [zeit/next.js#4266]
After upgrading to next6 from next3 everything locally was working.

on my server I pulled the new code deleted node_modules and npm i and restarted the server

the server should run on port 3000

however It does not run and I am getting a strange error if I run it manually

```node server.js
module.js:549
    throw err;
    ^

Error: Cannot find module 'webpack/lib/Chunk'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/mojoteam/knowledgebase/SSR/node_modules/extract-text-webpack-plugin/dist/index.js:17:14)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)```

## Your Environment
<!--- Include as many relevant details about the environment you experienced the bug in -->
| Tech    | Version |
|---------|---------|
| next    |     6    |
| node    |    8.11.1     |
| OS      |    Fedora     |
| browser |     Chrome    |
| etc     |         |

**Comment by aaldrich** [comment]
@theskillwithin Did you figure this out? I'm having the same issue.

**Comment by akmil** [comment]
Are you using webpack in your project?

**Comment by theskillwithin** [comment]
@aaldrich I had to run npm run build I think

**Comment by mtrabelsi** [comment]
one solution that works:
- rm -rf node_modules
- install node v6.14.3 
- npm i

**Comment by quinnliu** [comment]
@mtrabelsi tried it & didn't work 4 me. but thanks 4 suggestion

**Comment by quinnliu** [comment]
@aaldrich @akmil anyone solve this problem? 

I'm using 
```
"node": "8.9.3",
"npm": "5.6.0"
```
& it's only showing me this error on Heroku but is working fine locally

**Comment by mtrabelsi** [comment]
@quinnliu  sorry for the late reply, you should also remove your **package-lock.json**
