### ISSUE TITLE
custom-server-typescript example is not working with Next 6

### ISSUE THREAD

**Issue by tashburn** [zeit/next.js#4303]
[x] I have searched the [issues](https://github.com/zeit/next.js/issues?q=is%3Aissue) of this repository and believe that this is not a duplicate.

## Expected Behavior

`yarn install` then `yarn dev` should result in a running program.

## Current Behavior

Get this error

```
(node:79838) UnhandledPromiseRejectionWarning: Error: Cannot find module './dist/server/build/babel/preset'
    at Function.Module._resolveFilename (module.js:543:15)
    at Function.Module._load (module.js:470:25)
    at Module.require (module.js:593:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/trent/home/projects/Grok/tmp/next.js/babel.js:1:18)
    at Module._compile (module.js:649:30)
    at Module.m._compile (/Users/trent/home/projects/Grok/tmp/next.js/examples/custom-server-typescript/node_modules/ts-node/src/index.ts:422:23)
    at Module._extensions..js (module.js:660:10)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/trent/home/projects/Grok/tmp/next.js/examples/custom-server-typescript/node_modules/ts-node/src/index.ts:425:12)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:501:12)
    at Function.Module._load (module.js:493:3)
    at Module.require (module.js:593:17)
    at require (internal/module.js:11:18)
    at requireModule (/Users/trent/home/projects/Grok/tmp/next.js/examples/custom-server-typescript/node_modules/@babel/core/lib/config/files/plugins.js:142:12)
    at loadPreset (/Users/trent/home/projects/Grok/tmp/next.js/examples/custom-server-typescript/node_modules/@babel/core/lib/config/files/plugins.js:56:15)
(node:79838) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
(node:79838) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[nodemon] clean exit - waiting for changes before restart

```
## Your Environment

| Tech    | Version |
|---------|---------|
| next    |   6.0.0      |
| node    |    9.8.0     |
| OS      |     macOS 10.13.4   |

**Comment by franxois** [comment]
Actually it works if you follow instructions to clone only this example to separate path. 
You can't clone all the repo and try to run only this example, it look like next read babel configuration in parent dir. 

Otherwise, you can add a .babelrc files containing

```
{
    "presets": [
        "next/babel"
    ]
}
```

**Comment by timneutkens** [comment]
Works fine for me `yarn create next-app --example custom-server-typescript custom-server-typescript-app`.

@tashburn when creating issues please provide a clear and concise steps to reproduce.

Like @franxois said if you clone the repository you have to build the code, but there's multiple ways to install examples that are faster than cloning the whole codebase + examples 👍
