### ISSUE TITLE
ErEror: Module parse fail  Unexpected character '@' (2:0) You may need an appropriate loader to handle this file type.

### ISSUE THREAD

**Issue by aqeeldilmir** [zeit/next.js#4325]
i am facing issue in importing the typeface-roboto font Types in the next.js file.
Error: Module parse failed: Unexpected character '@' (2:0)
You may need an appropriate loader to handle this file type.
| /* roboto-100normal - latin */
| @font-face {
|   font-family: 'Roboto';
|   font-style: normal;
    at Object.<anonymous> (/home/muhammad/be-projects/bluerain-app-dukaan-admin/.next/dist/bundles/pages/index.js:6649:7)
    at __webpack_require__ (/home/muhammad/be-projects/bluerain-app-dukaan-admin/.next/dist/bundles/pages/index.js:23:31)
    at Object.<anonymous> (/home/muhammad/be-projects/bluerain-app-dukaan-admin/.next/dist/bundles/pages/index.js:6552:23)
    at __webpack_require__ (/home/muhammad/be-projects/bluerain-app-dukaan-admin/.next/dist/bundles/pages/index.js:23:31)
    at Object.module.exports.Object.defineProperty.value (/home/muhammad/be-projects/bluerain-app-dukaan-admin/.next/dist/bundles/pages/index.js:161:18)
    at __webpack_require__ (/home/muhammad/be-projects/bluerain-app-dukaan-admin/.next/dist/bundles/pages/index.js:23:31)
    at /home/muhammad/be-projects/bluerain-app-dukaan-admin/.next/dist/bundles/pages/index.js:70:18
    at Object.<anonymous> (/home/muhammad/be-projects/bluerain-app-dukaan-admin/.next/dist/bundles/pages/index.js:73:10)
    at Module._compile (internal/modules/cjs/loader.js:654:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:665:10)
=============================================================================
This is my next.config.js

module.exports = {
  webpack: (config, options) => {
    config.module.rules.push({ test: /\.scss$/, loader: ['style-loader', 'css-loader', 'sass-loader'] });
    config.module.rules.push({
      test: /\.+(ts|tsx)$/,
      use: [
        //	defaultLoaders.babel,
        { loader: 'ts-loader', options: { transpileOnly: true } }
      ],
      exclude: /node_modules/,
      }, );
    return config;
  }
}

**Comment by kv9991** [comment]
try to update your next.js config like in this snippet (dont forget to install url-loader via npm)

```
config.module.rules.push({
      test: /\.(png|svg|eot|otf|ttf|woff|woff2)$/,
      use: {
        loader: "url-loader",
        options: {
          limit: 100000,
          publicPath: "./",
          outputPath: "static/",
          name: "[name].[ext]"
        }
      }
    });
```

**Comment by aqeeldilmir** [comment]
@kv9991  i am using typescript also?? in next.config.js

**Comment by aqeeldilmir** [comment]
@kv9991 facing same issue

**Comment by timneutkens** [comment]
Please follow the issue template.

**Comment by aqeeldilmir** [comment]
@timneutkens i am newbie please explain the issue template.
