### ISSUE TITLE
Styled-JSX HMR failed in Next 6.0.0

### ISSUE THREAD

**Issue by williamli** [zeit/next.js#4335]
setup a new project with 

```
mkdir hello-next
cd hello-next
npm init -y
npm install --save react react-dom next
mkdir pages
```

add a new index.js page

```
export default () =>
  <div>
    Hello world
    <p>scoped!</p>
    <style jsx>{`
      p {
        color: blue;
      }
      div {
        background: red;
      }
      @media (max-width: 600px) {
        div {
          background: blue;
        }
      }
    `}</style>
    <style global jsx>{`
      body {
        background: black;
      }
    `}</style>
  </div>
```

change the style and save.

you will then be greeted by style remove / update errors

```
StyleSheetRegistry: styleId: `jsx-803111306` not found.
Error: StyleSheetRegistry: styleId: `jsx-803111306` not found.
    at invariant (node_modules/styled-jsx/dist/stylesheet-registry.js:267:0)
    at StyleSheetRegistry.remove (node_modules/styled-jsx/dist/stylesheet-registry.js:118:0)
    at StyleSheetRegistry.update (node_modules/styled-jsx/dist/stylesheet-registry.js:139:0)

```

**Comment by williamli** [comment]
should be a duplicate of https://github.com/zeit/next.js/issues/4273

**Comment by williamli** [comment]
is there any way to patch this problem without running my project in next@canary?

**Comment by timneutkens** [comment]
6.0.1 will be out soon, until then use `next@canary`
