### ISSUE TITLE
No page context

### ISSUE THREAD

**Issue by liumin1128** [zeit/next.js#4351]
- [ ] I have searched the [issues](https://github.com/zeit/next.js/issues?q=is%3Aissue) of this repository and believe that this is not a duplicate.

## Current Behavior

{ Error: No page context
    at Function._callee$ (/Users/liumin/Desktop/next/with-redux-saga/node_modules/next-redux-wrapper/lib/index.js:169:25)
    at tryCatch (/Users/liumin/Desktop/next/with-redux-saga/node_modules/regenerator-runtime/runtime.js:62:40)
    at Generator.invoke [as _invoke] (/Users/liumin/Desktop/next/with-redux-saga/node_modules/regenerator-runtime/runtime.js:296:22)
    at Generator.prototype.(anonymous function) [as next] (/Users/liumin/Desktop/next/with-redux-saga/node_modules/regenerator-runtime/r
untime.js:114:21)
    at step (/Users/liumin/Desktop/next/with-redux-saga/node_modules/next-redux-wrapper/node_modules/@babel/runtime/helpers/asyncToGener
ator.js:12:30)
    at _next (/Users/liumin/Desktop/next/with-redux-saga/node_modules/next-redux-wrapper/node_modules/@babel/runtime/helpers/asyncToGene
rator.js:27:9)
    at /Users/liumin/Desktop/next/with-redux-saga/node_modules/next-redux-wrapper/node_modules/@babel/runtime/helpers/asyncToGenerator.js:34:7
    at new Promise (/Users/liumin/Desktop/next/with-redux-saga/node_modules/core-js/library/modules/es6.promise.js:177:7)
    at Function.<anonymous> (/Users/liumin/Desktop/next/with-redux-saga/node_modules/next-redux-wrapper/node_modules/@babel/runtime/helpers/asyncToGenerator.js:7:12)
    at Function.value [as getInitialProps] (/Users/liumin/Desktop/next/with-redux-saga/node_modules/next-redux-wrapper/lib/index.js:211:25)
    at _callee$ (/Users/liumin/Desktop/next/with-redux-saga/node_modules/next/dist/lib/utils.js:111:30)
    at tryCatch (/Users/liumin/Desktop/next/with-redux-saga/node_modules/regenerator-runtime/runtime.js:62:40)
    at Generator.invoke [as _invoke] (/Users/liumin/Desktop/next/with-redux-saga/node_modules/regenerator-runtime/runtime.js:296:22)
    at Generator.prototype.(anonymous function) [as next] (/Users/liumin/Desktop/next/with-redux-saga/node_modules/regenerator-runtime/runtime.js:114:21)
    at step (/Users/liumin/Desktop/next/with-redux-saga/node_modules/@babel/runtime/helpers/asyncToGenerator.js:12:30)
    at _next (/Users/liumin/Desktop/next/with-redux-saga/node_modules/@babel/runtime/helpers/asyncToGenerator.js:27:9) sourceMapsApplied: true }

## Steps to Reproduce (for bugs)

1. curl https://codeload.github.com/zeit/next.js/tar.gz/canary | tar -xz --strip=2 next.js-canary/examples/with-redux-saga
2. cd with-redux-saga
3. yarn
4. yarn add next next-redux-saga next-redux-wrapper
5. yarn dev

## Your Environment

| Tech    | Version |
|---------|---------|
| next    |     6.0.1    |
| node    |     v10.0.0    |
| OS      |    macOS 10.13.4     |
| browser |    chrome     |
| etc     |         |

package.json
{
  "name": "with-redux-saga",
  "version": "1.0.0",
  "license": "MIT",
  "scripts": {
    "dev": "next",
    "build": "next build",
    "start": "next start"
  },
  "dependencies": {
    "es6-promise": "4.1.1",
    "isomorphic-unfetch": "2.0.0",
    "next": "^6.0.1",
    "next-redux-saga": "^3.0.0-beta.1",
    "next-redux-wrapper": "^2.0.0-beta.6",
    "react": "^16.0.0",
    "react-dom": "^16.0.0",
    "react-redux": "5.0.5",
    "redux": "3.7.2",
    "redux-saga": "0.15.4"
  },
  "devDependencies": {
    "redux-devtools-extension": "2.13.2"
  }
}

**Comment by gastonfartek** [comment]
Not sure I get the full context of what you are trying to accomplish, however I think the issue might be because you ran ```yarn add next-redux-wrapper``` on step **4** and upgraded to the 2.0 version. In which case you'll need to create a ```/pages/_app.js```. Here is an example of your code with the new version (I haven't tested it)

**/pages/_app.js**

```javascript
import App, { Container } from 'next/app';
import React from 'react';
import { Provider } from 'react-redux';
import { withReduxSaga } from '../store';

class MyApp extends App {
  static async getInitialProps({ Component, router, ctx }) {
    let pageProps = {};

    if (Component.getInitialProps) {
      pageProps = await Component.getInitialProps(ctx);
    }

    return { pageProps };
  }

  render() {
    const { Component, pageProps, store } = this.props;
    return (
      <Container>
        <Provider store={store}>
          <Component {...pageProps} />
        </Provider>
      </Container>
    );
  }
}

export default withReduxSaga(MyApp);
```

**/pages/index.js**

```javascript
import React from 'react';
import { connect } from 'react-redux';
import { increment, loadData, startClock, tickClock } from '../actions';

import Page from '../components/page';

class Counter extends React.Component {
  static async getInitialProps({ store, isServer }) {
    store.dispatch(tickClock(isServer));
    store.dispatch(increment());
    if (!store.getState().placeholderData) {
      store.dispatch(loadData());
    }
  }

  componentDidMount() {
    this.props.dispatch(startClock());
  }

  render() {
    return <Page title="Index Page" linkTo="/other" />;
  }
}

export default connect()(Counter);
```

**Comment by timneutkens** [comment]
@gastonfartek feel free to upgrade/PR the example updates.

**Comment by timneutkens** [comment]
Thanks @gastonfartek 🙏 🙌

**Comment by PaulRBerg** [comment]
@liumin1128 This might also be helpful https://github.com/kirill-konshin/next-redux-wrapper/issues/89
