### ISSUE TITLE
Cannot read property 'showMore' of undefined in Example app with dynamic-imports

### ISSUE THREAD

**Issue by qskane** [zeit/next.js#4370]
I am following [Example app with dynamic-imports](https://github.com/zeit/next.js/tree/canary/examples/with-dynamic-import) 

when I visite `localhost:3000`, I got the error 

```
TypeError: Cannot read property 'showMore' of undefined
    at Function.getInitialProps (pages/index.js:49:0)
    at _callee$ (D:\workspace\node\with-dynamic-import-app\node_modules\next\dist\lib\utils.js:111:30)
    at tryCatch (D:\workspace\node\with-dynamic-import-app\node_modules\regenerator-runtime\runtime.js:62:40)
    at Generator.invoke [as _invoke] (D:\workspace\node\with-dynamic-import-app\node_modules\regenerator-runtime\runtime.js:296:22)
    at Generator.prototype.(anonymous function) [as next] (D:\workspace\node\with-dynamic-import-app\node_modules\regenerator-runtime\runtime.js:114:21)
    at step (D:\workspace\node\with-dynamic-import-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:12:30)
    at _next (D:\workspace\node\with-dynamic-import-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:27:9)
    at D:\workspace\node\with-dynamic-import-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:34:7
    at new Promise (<anonymous>)
    at new F (D:\workspace\node\with-dynamic-import-app\node_modules\core-js\library\modules\_export.js:36:28)
    at D:\workspace\node\with-dynamic-import-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:7:12
    at loadGetInitialProps (D:\workspace\node\with-dynamic-import-app\node_modules\next\dist\lib\utils.js:90:31)
    at Function._callee$ (D:\workspace\node\with-dynamic-import-app\node_modules\next\dist\lib\app.js:103:55)
    at tryCatch (D:\workspace\node\with-dynamic-import-app\node_modules\regenerator-runtime\runtime.js:62:40)
    at Generator.invoke [as _invoke] (D:\workspace\node\with-dynamic-import-app\node_modules\regenerator-runtime\runtime.js:296:22)
    at Generator.prototype.(anonymous function) [as next] (D:\workspace\node\with-dynamic-import-app\node_modules\regenerator-runtime\runtime.js:114:21)
```
I tried add following code 
```
  static getInitialProps({query}) {
    //stuiped added
    if(typeof query === "undefined"){
      query = {}
    }

    return {showMore: Boolean(query.showMore)}
  }
```

then I can visit `localhost:3000`, but when I click `Toggle Show More` button, another error display in the console

```
es6.promise.js:110 Unhandled promise rejection TypeError: Cannot read property 'showMore' of undefined
    at shallowEquals (shallow-equals.js:10)
    at Router.urlIsNew (router.js:571)
    at Router._callee3$ (router.js:303)
    at tryCatch (runtime.js:62)
    at Generator.invoke [as _invoke] (runtime.js:296)
    at Generator.prototype.(:3000/anonymous function) [as next] (http://localhost:3000/_next/static/commons/main.js:30863:21)
    at step (asyncToGenerator.js:12)
    at _next (asyncToGenerator.js:27)
    at asyncToGenerator.js:34
    at new Promise (es6.promise.js:177)
```

**How can I fix this ?**

```
$ node -v
v8.10.0
$ yarn -v
1.3.2

**Comment by w01fgang** [comment]
I have the same error. @qskane have you solved this issue?
