### ISSUE TITLE
Example "with-i18next" error hot reloading when adding styles in version `next@6.0.2`

### ISSUE THREAD

**Issue by jlobos** [zeit/next.js#4380]
**Describe the bug**
Example "with-i18next" error hot reloading when adding styles in `next@6.0.2` version , in `next@5.1.0` version this error does not appear

**To Reproduce**
Steps to reproduce the behavior, please provide code snippets or a repository:
1. Go to https://github.com/zeit/next.js/tree/canary/examples/with-i18next
2. Download and `npm run dev` wait for hot reloading
3. Edit `components/Post.js` and add styles
```js
      <style jsx>{`
        div {
          color: red;
        }
        `}</style>
      </div>
```

**Comment by yhirano55** [comment]
As far as it read error logs, it seems contains react-hot-reloader's problems.

```
_extends is not defined
ReferenceError: _extends is not defined
    at ProxyComponent.fixedT [as t] (eval at __reactstandin__regenerateByEval (http://localhost:3000/_next/webpack/4.407ef376c938fbdece6e.hot-update.js:77:19), <anonymous>:10:21)
    at ProxyComponent.render (components/Post.js:13:0)
    at ProxyComponent.hotComponentRender (node_modules/react-hot-loader/dist/react-hot-loader.development.js:579:0)
    at ProxyComponent.proxiedRender (node_modules/react-hot-loader/dist/react-hot-loader.development.js:587:0)
    at finishClassComponent (node_modules/react-dom/cjs/react-dom.development.js:8389:0)
    at updateClassComponent (node_modules/react-dom/cjs/react-dom.development.js:8357:0)
    at beginWork (node_modules/react-dom/cjs/react-dom.development.js:8982:0)
    at performUnitOfWork (node_modules/react-dom/cjs/react-dom.development.js:11814:0)
    at workLoop (node_modules/react-dom/cjs/react-dom.development.js:11843:0)
    at renderRoot (node_modules/react-dom/cjs/react-dom.development.js:11874:0)

    in Post (created by I18n)
    in I18n (created by Translate(Post))
    in Translate(Post) (at index.js:33)
    in div (created by Homepage)
    in I18nextProvider (at index.js:30)
    in Homepage (created by App)
    in Container (created by App)
    in App
    in AppContainer
```
