### ISSUE TITLE
(node:58300) UnhandledPromiseRejectionWarning: Error: Cannot find module 'babel-plugin-transform-runtime'

### ISSUE THREAD

**Issue by Hancoson** [zeit/next.js#4382]
**Describe the bug**
I use [custom-server-express](https://github.com/zeit/next.js/tree/canary/examples/custom-server-express) to creat my app, when I run `npm run dev`, there are some error:

```
(node:58300) UnhandledPromiseRejectionWarning: Error: Cannot find module 'babel-plugin-transform-runtime' from '/Users/**/Documents/code/github'
    at Function.module.exports [as sync] (/Users/**/Documents/code/github/node-blog-app/node_modules/resolve/lib/sync.js:40:15)
    at resolveStandardizedName (/Users/**/Documents/code/github/node-blog-app/node_modules/@babel/core/lib/config/files/plugins.js:78:29)
    at resolvePlugin (/Users/**/Documents/code/github/node-blog-app/node_modules/@babel/core/lib/config/files/plugins.js:27:10)
    at loadPlugin (/Users/**/Documents/code/github/node-blog-app/node_modules/@babel/core/lib/config/files/plugins.js:35:18)
    at createDescriptor (/Users/**/Documents/code/github/node-blog-app/node_modules/@babel/core/lib/config/config-descriptors.js:152:21)
    at /Users/**/Documents/code/github/node-blog-app/node_modules/@babel/core/lib/config/config-descriptors.js:104:12
    at Array.map (<anonymous>)
    at createDescriptors (/Users/**/Documents/code/github/node-blog-app/node_modules/@babel/core/lib/config/config-descriptors.js:103:27)
    at createPluginDescriptors (/Users/**/Documents/code/github/node-blog-app/node_modules/@babel/core/lib/config/config-descriptors.js:99:10)
    at /Users/**/Documents/code/github/node-blog-app/node_modules/@babel/core/lib/config/config-descriptors.js:50:19
    at plugins (/Users/**/Documents/code/github/node-blog-app/node_modules/@babel/core/lib/config/config-descriptors.js:40:25)
    at mergeChainOpts (/Users/**/Documents/code/github/node-blog-app/node_modules/@babel/core/lib/config/config-chain.js:296:68)
    at /Users/**/Documents/code/github/node-blog-app/node_modules/@babel/core/lib/config/config-chain.js:251:7
    at buildRootChain (/Users/**/Documents/code/github/node-blog-app/node_modules/@babel/core/lib/config/config-chain.js:85:20)
    at loadPrivatePartialConfig (/Users/**/Documents/code/github/node-blog-app/node_modules/@babel/core/lib/config/partial.js:41:53)
    at loadPartialConfig (/Users/**/Documents/code/github/node-blog-app/node_modules/@babel/core/lib/config/partial.js:66:16)
(node:58300) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
(node:58300) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**System information**
 - OS: macOS
 - Version of Next.js:  6.0.2
 - Version of node.js:  8.10.0
 - Version of npm:  5.6.0

**Comment by timneutkens** [comment]
I can't reproduce based on your description. `babel-plugin-transform-runtime` is not used in Next.js, since it's the babel 6 version of this plugin: `@babel/plugin-transform-runtime` which we do use. I'm guessing you have a outdated `.babelrc` somewhere.

**Comment by Hancoson** [comment]
Ok, I add `.babelrc` , can solve this problem. THX
```
{
  "plugins": [
    "@babel/plugin-transform-runtime"
  ]
}
```

**Comment by timneutkens** [comment]
You can just remove the `.babelrc`, or use:

```
{
  "presets": ["next/babel"]
}
```
