### ISSUE TITLE
with-mobx example broken in version 6

### ISSUE THREAD

**Issue by willopez** [zeit/next.js#4390]
The `with-mobx` example compiles, however, when loading in browser an error is displayed.

**To Reproduce**
1. npx create-next-app --example with-mobx with-mobx-app
2. `cd with-mobx-app`
2. yarn
3. yarn run dev

**Expected behavior**
Loading localhost:3000 on a browser should render a counter

** Actual behavior** 
The following error is displayed: 

```
Decorating class property failed. Please ensure that transform-class-properties is enabled.
Error: Decorating class property failed. Please ensure that transform-class-properties is enabled.
    at _initializerWarningHelper (/Users/will/code/with-mobx-app/.next/dist/bundles/pages/index.js:338:9)
    at new Store (store.js:9:0)
    at initStore (store.js:25:0)
    at Function.getInitialProps (pages/index.js:9:0)
    at _callee$ (/Users/will/code/with-mobx-app/node_modules/next/dist/lib/utils.js:111:30)
    at tryCatch (/Users/will/code/with-mobx-app/node_modules/regenerator-runtime/runtime.js:62:40)
    at Generator.invoke [as _invoke] (/Users/will/code/with-mobx-app/node_modules/regenerator-runtime/runtime.js:296:22)
    at Generator.prototype.(anonymous function) [as next] (/Users/will/code/with-mobx-app/node_modules/regenerator-runtime/runtime.js:114:21)
    at step (/Users/will/code/with-mobx-app/node_modules/@babel/runtime/helpers/asyncToGenerator.js:12:30)
    at _next (/Users/will/code/with-mobx-app/node_modules/@babel/runtime/helpers/asyncToGenerator.js:27:9)
    at /Users/will/code/with-mobx-app/node_modules/@babel/runtime/helpers/asyncToGenerator.js:34:7
    at new Promise (<anonymous>)
    at new F (/Users/will/code/with-mobx-app/node_modules/core-js/library/modules/_export.js:36:28)
    at /Users/will/code/with-mobx-app/node_modules/@babel/runtime/helpers/asyncToGenerator.js:7:12
    at loadGetInitialProps (/Users/will/code/with-mobx-app/node_modules/next/dist/lib/utils.js:90:31)
    at Function._callee$ (/Users/will/code/with-mobx-app/node_modules/next/dist/lib/app.js:103:55)
```

**System information**
 - OS: macOS
 - Browser Chrome
 - Version of Next.js: 6.0.2

**Comment by willopez** [comment]
fixed in this PR: https://github.com/zeit/next.js/pull/4394 thanks @yhirano55
