### ISSUE TITLE
yarn test on with-apollo-auth example breaks after upgrading to next.js 6.0.

### ISSUE THREAD

**Issue by lasersox** [zeit/next.js#4405]
**Describe the bug**
`yarn test` in the with-apollo-auth example breaks after upgrading to next.js 6.0.

**To Reproduce**
Run: 

```
git clone https://github.com/zeit/next.js.git
cd next.js/examples/with-apollo-auth/
yarn install
yarn upgrade
yarn test
```
I get error:

```
/Users/lasersox/Desktop/next.js/examples/with-apollo-auth/node_modules/ava/lib/cli.js:196
					throw err;
					^
ResolveError: /Users/lasersox/Desktop/next.js/examples/with-apollo-auth/.babelrc: Couldn't find preset "env" relative to directory
    at resolve (/Users/lasersox/Desktop/next.js/examples/with-apollo-auth/node_modules/hullabaloo-config-manager/lib/resolvePluginsAndPresets.js:111:17)
    at resolvePluginsAndPresets (/Users/lasersox/Desktop/next.js/examples/with-apollo-auth/node_modules/hullabaloo-config-manager/lib/resolvePluginsAndPresets.js:125:9)
    at reduceChains (/Users/lasersox/Desktop/next.js/examples/with-apollo-auth/node_modules/hullabaloo-config-manager/lib/reduceChains.js:119:29)
    at new ResolvedConfig (/Users/lasersox/Desktop/next.js/examples/with-apollo-auth/node_modules/hullabaloo-config-manager/lib/ResolvedConfig.js:12:21)
    at collector.fromConfig.then.chains (/Users/lasersox/Desktop/next.js/examples/with-apollo-auth/node_modules/hullabaloo-config-manager/index.js:35:21)
    at <anonymous>
From previous event:
    at Api.run (/Users/lasersox/Desktop/next.js/examples/with-apollo-auth/node_modules/ava/api.js:71:5)
    at Object.exports.run (/Users/lasersox/Desktop/next.js/examples/with-apollo-auth/node_modules/ava/lib/cli.js:187:7)
    at Object.<anonymous> (/Users/lasersox/Desktop/next.js/examples/with-apollo-auth/node_modules/ava/cli.js:22:24)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Function.Module.runMain (module.js:701:10)
    at startup (bootstrap_node.js:193:16)
    at bootstrap_node.js:617:3
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

```

**Expected behavior**
Ideally the tests would pass.

**System information**
 - OS: macOS
 - Version of Next.js: 6.0.3

**Additional context**
I think it's because the .babelrc needs to be updated.  But I can't find the right documentation…

**Comment by lasersox** [comment]
@timneutkens I can help, but I'm not sure where to start. My own projects tests are failing at the moment due to this issue. :(

**Comment by lfades** [comment]
I'll be working on this 💃

**Comment by lfades** [comment]
@lasersox I'm going to update the example but the current error you have it's not going to be fixed, since tests will be dropped.

If you have tests with AVA update to AVA 1.0.0-beta which uses babel 7

**Comment by lasersox** [comment]
Thanks! I migrated to using jest.
