### ISSUE TITLE
update-check module throwing error - [non-breaking]

### ISSUE THREAD

**Issue by razi-rasheed** [zeit/next.js#4412]
update-check module is throwing non-breaking error at the initial stage of 'next' script run. 

**To Reproduce**
run 'npm run dev'

**Expected behavior**
should check for updates among the dependencies

**Screenshots**
$ next
Error checking updates SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at IncomingMessage.response.on (/home/razi/extras/test/node_modules/update-check/index.js:102:29)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)

**System information**
 - OS: Ubuntu 16.04
 - Version of Next.js: 6.0.3

**Additional context**
reaching 'JSON.parse' before the completion of reading the previous stream of data viz., 'rawData'

**Comment by timneutkens** [comment]
@razi-rasheed can you file this on github.com/zeit/update-check?

**Comment by razi-rasheed** [comment]
The same issue has been opened on https://github.com/zeit/update-check. Closing issue.
