### ISSUE TITLE
Migrating to next v6 giving reference error

### ISSUE THREAD

**Issue by dev-drprasad** [zeit/next.js#4423]
**Describe the bug**
migrating from next: "^4.1.3" to next: "^6.0.3" giving reference error. i am not sure whether issue with nextjs or some other library. if i remove `global` prop from `style` tag , error is not coming, but it is breaking styles

**Error**
```
{ ReferenceError: normalizeCSS is not defined
    at _default (/Users/wizard/Workspace/ix-storefront/.next/dist/bundles/pages/BrowsePage.js:5751:10)
    at resolve (/Users/wizard/Workspace/ix-storefront/node_modules/react-dom/cjs/react-dom-server.node.development.js:2102:14)
    at ReactDOMServerRenderer.render (/Users/wizard/Workspace/ix-storefront/node_modules/react-dom/cjs/react-dom-server.node.development.js:2260:22)
    at ReactDOMServerRenderer.read (/Users/wizard/Workspace/ix-storefront/node_modules/react-dom/cjs/react-dom-server.node.development.js:2234:19)
    at renderToString (/Users/wizard/Workspace/ix-storefront/node_modules/react-dom/cjs/react-dom-server.node.development.js:2501:25)
    at renderPage (/Users/wizard/Workspace/ix-storefront/node_modules/next/dist/server/render.js:277:26)
    at Function.getInitialProps (/Users/wizard/Workspace/ix-storefront/.next/dist/bundles/pages/_document.js:228:18)
    at _callee$ (/Users/wizard/Workspace/ix-storefront/node_modules/next/dist/lib/utils.js:111:30)
    at tryCatch (/Users/wizard/Workspace/ix-storefront/node_modules/@babel/runtime/node_modules/regenerator-runtime/runtime.js:62:40)
    at Generator.invoke [as _invoke] (/Users/wizard/Workspace/ix-storefront/node_modules/@babel/runtime/node_modules/regenerator-runtime/runtime.js:296:22)
    at Generator.prototype.(anonymous function) [as next] (/Users/wizard/Workspace/ix-storefront/node_modules/@babel/runtime/node_modules/regenerator-runtime/runtime.js:114:21)
    at step (/Users/wizard/Workspace/ix-storefront/node_modules/@babel/runtime/helpers/asyncToGenerator.js:12:30)
    at _next (/Users/wizard/Workspace/ix-storefront/node_modules/@babel/runtime/helpers/asyncToGenerator.js:27:9)
    at /Users/wizard/Workspace/ix-storefront/node_modules/@babel/runtime/helpers/asyncToGenerator.js:34:7
    at new Promise (<anonymous>)
    at new F (/Users/wizard/Workspace/ix-storefront/node_modules/@babel/runtime/node_modules/core-js/library/modules/_export.js:36:28) sourceMapsApplied: true }
TypeError: Cannot read property 'replace' of undefined
    at MyDocument.render (/Users/wizard/Workspace/ix-storefront/.next/dist/bundles/pages/_document.js:151:19)
    at resolve (/Users/wizard/Workspace/ix-storefront/node_modules/react-dom/cjs/react-dom-server.node.development.js:2149:18)
    at ReactDOMServerRenderer.render (/Users/wizard/Workspace/ix-storefront/node_modules/react-dom/cjs/react-dom-server.node.development.js:2260:22)
    at ReactDOMServerRenderer.read (/Users/wizard/Workspace/ix-storefront/node_modules/react-dom/cjs/react-dom-server.node.development.js:2234:19)
    at renderToStaticMarkup (/Users/wizard/Workspace/ix-storefront/node_modules/react-dom/cjs/react-dom-server.node.development.js:2512:25)
    at _callee3$ (/Users/wizard/Workspace/ix-storefront/node_modules/next/dist/server/render.js:341:100)
    at tryCatch (/Users/wizard/Workspace/ix-storefront/node_modules/@babel/runtime/node_modules/regenerator-runtime/runtime.js:62:40)
    at Generator.invoke [as _invoke] (/Users/wizard/Workspace/ix-storefront/node_modules/@babel/runtime/node_modules/regenerator-runtime/runtime.js:296:22)
    at Generator.prototype.(anonymous function) [as next] (/Users/wizard/Workspace/ix-storefront/node_modules/@babel/runtime/node_modules/regenerator-runtime/runtime.js:114:21)
    at step (/Users/wizard/Workspace/ix-storefront/node_modules/@babel/runtime/helpers/asyncToGenerator.js:12:30)
    at _next (/Users/wizard/Workspace/ix-storefront/node_modules/@babel/runtime/helpers/asyncToGenerator.js:27:9)
    at <anonymous>
5/18/2018, 1:43:06 PM - error: Error in rendering
5/18/2018, 1:43:06 PM - error:  TypeError: Cannot read property 'replace' of undefined
    at MyDocument.render (/Users/wizard/Workspace/ix-storefront/.next/dist/bundles/pages/_document.js:151:19)
    at resolve (/Users/wizard/Workspace/ix-storefront/node_modules/react-dom/cjs/react-dom-server.node.development.js:2149:18)
    at ReactDOMServerRenderer.render (/Users/wizard/Workspace/ix-storefront/node_modules/react-dom/cjs/react-dom-server.node.development.js:2260:22)
    at ReactDOMServerRenderer.read (/Users/wizard/Workspace/ix-storefront/node_modules/react-dom/cjs/react-dom-server.node.development.js:2234:19)
    at renderToStaticMarkup (/Users/wizard/Workspace/ix-storefront/node_modules/react-dom/cjs/react-dom-server.node.development.js:2512:25)
    at _callee3$ (/Users/wizard/Workspace/ix-storefront/node_modules/next/dist/server/render.js:341:100)
    at tryCatch (/Users/wizard/Workspace/ix-storefront/node_modules/@babel/runtime/node_modules/regenerator-runtime/runtime.js:62:40)
    at Generator.invoke [as _invoke] (/Users/wizard/Workspace/ix-storefront/node_modules/@babel/runtime/node_modules/regenerator-runtime/runtime.js:296:22)
    at Generator.prototype.(anonymous function) [as next] (/Users/wizard/Workspace/ix-storefront/node_modules/@babel/runtime/node_modules/regenerator-runtime/runtime.js:114:21)
    at step (/Users/wizard/Workspace/ix-storefront/node_modules/@babel/runtime/helpers/asyncToGenerator.js:12:30)
    at _next (/Users/wizard/Workspace/ix-storefront/node_modules/@babel/runtime/helpers/asyncToGenerator.js:27:9)
    at <anonymous>
```

**System information**
 - OS: macOS High Sierra 10.13.4
 - Version of Next.js: [e.g. 6.0.3]

package.json
```
"devDependencies": {
    "babel-eslint": "^8.0.1",
    "babel-preset-stage-0": "^6.24.1",
    "eslint": "^4.9.0",
    "eslint-config-airbnb": "^16.1.0",
    "eslint-plugin-import": "^2.8.0",
    "eslint-plugin-jsx-a11y": "^6.0.2",
    "eslint-plugin-react": "^7.4.0",
    "husky": "^0.14.3",
    "node": "8.9.4",
    "pm2": "^2.9.1",
    "prop-types": "^15.6.0"
  },
  "dependencies": {
    "babel-plugin-module-resolver": "^3.0.0",
    "babel-preset-stage-0": "^6.24.1",
    "express": "^4.16.2",
    "express-http-proxy": "^1.1.0",
    "express-winston": "^2.5.0",
    "html-to-text": "^3.3.0",
    "isomorphic-fetch": "^2.2.1",
    "next": "^6.0.3",
    "next-routes": "^1.2.0",
    "postcss-cssnext": "^3.0.2",
    "postcss-import": "^11.0.0",
    "postcss-nested": "^3.0.0",
    "react": "^16.2.0",
    "react-amphtml": "^2.2.2",
    "react-dom": "^16.2.0",
    "react-icons": "^2.2.7",
    "redis": "^2.8.0",
    "styled-jsx-plugin-postcss": "^0.1.1",
    "winston": "^2.4.0"
  },
```

.babelrc
```
{
  "presets": [
    "@babel/env",
    [
      "next/babel",
      {
        "styled-jsx": {
          "plugins": [
            "styled-jsx-plugin-postcss"
          ]
        }
      }
    ]
  ],
  "plugins": [
    [
      "module-resolver",
      {
        "root": ["./"],
        "alias": {
          "components": "./components",
          "utils": "./utils",
          "styles": "./styles"
        }
      }
    ]
  ]
}
```

next.config.js
```
const getRoutes = require('./routes');

module.exports = {
  useFileSystemPublicRoutes: false,
  exportPathMap: getRoutes,
  webpack: (oldConfig) => {
    const config = Object.assign({}, oldConfig);
    // disable sourcemaps of webpack
    config.devtool = false;
    config.target = 'node';
    Object.keys(config.module.rules).forEach((rule) => {
      if (Object.prototype.hasOwnProperty.call(config.module.rules, rule) && config.module.rules[rule].loader === 'babel-loader') {
        config.module.rules[rule].options.sourceMaps = false;
      }
    });
    return config;
  },
};
```

styles.js
```
import normalizeCSS from './normalize';
import globalCSS from './global-styles';
import gridCSS from './grid';

export default () => (
  [
    <style jsx global>
      {normalizeCSS}
    </style>,
    <style jsx global>
      {globalCSS}
    </style>,
    <style jsx global>
      {gridCSS}
    </style>,
  ]
);
```
removing `global` prop from above file fixes the issue. but its breaking styles

**Comment by timneutkens** [comment]
I'm not sure how to help without a full reproduction. Please provide a minimal full reproduction. Also I'm pretty sure that this is not supported and has to be a child of a real component:

```
export default () => (
  [
    <style jsx global>
      {normalizeCSS}
    </style>,
    <style jsx global>
      {globalCSS}
    </style>,
    <style jsx global>
      {gridCSS}
    </style>,
  ]
);
```

**Comment by dev-drprasad** [comment]
@timneutkens  i modified code. its looks like

page.js
```
import Styles from '../styles';

const Page = () => {
  return (
    <React.Fragment>
      <style jsx global>{normalizeCSS}</style>
      <Head>
        <title>{title}</title>
      </Head>
      <body>
        <Header topNavigation={topNavigation} />
        <Content isFullWidth={isFullWidth}>
          {children}
        </Content>
        <Footer />
      </body>
    </React.Fragment>
  );
};

export default Page;
```

styles.js
```
import css from 'styled-jsx/css';

export default css`
  html {
    line-height: 1.15;
    -ms-text-size-adjust: 100%;
    -webkit-text-size-adjust: 100%;
  }

  body {
    margin: 0;
  }
`;
```

as i told its working fine with next v4 but not next v6. but removing `global` prop do not raise error. but styles don't work.

**Comment by 6foot7** [comment]
Hi @dev-drprasad, I am experiencing the same, did you find a solution? Thank you.

**Comment by dev-drprasad** [comment]
@6foot7 can you please send your `.babelrc` and `package.json` ?

**Comment by 6foot7** [comment]
thanks for you reply:

.babelrc:

{
  "presets": [
    [
      "next/babel",
      {
        "preset-env": {
          "modules": "commonjs"
        }
      }
    ]
  ],
  "plugins": [
    "inline-react-svg",
    "transform-flow-strip-types",
    [
      "module-resolver",
      {
        "root": [
          "./"
        ]
      }
    ]
  ]
}


package.json:
{
    "name": "next-boilerplate",
    "version": "1.0.0",
    "license": "MIT",
    "scripts": {
        "dev": "node server",
        "test": "NODE_ENV=test jest",
        "build": "next build",
        "start": "NODE_ENV=production node server",
        "precommit": "lint-staged",
        "storybook": "start-storybook -p 6006",
        "build-storybook": "build-storybook"
    },
    "lint-staged": {
        "*.js": [
            "eslint --fix",
            "prettier-eslint --write",
            "git add"
        ]
    },
    "dependencies": {
        "@zeit/next-bundle-analyzer": "^0.1.1",
        "@zeit/next-source-maps": "^0.0.2",
        "axios": "0.18.0",
        "babel-core": "7.0.0-bridge.0",
        "babel-eslint": "8.2.2",
        "babel-jest": "22.4.3",
        "babel-plugin-module-resolver": "3.1.1",
        "babel-runtime": "^6.0.0",
        "compression": "1.7.2",
        "css-loader": "^0.28.11",
        "dotenv": "5.0.1",
        "express": "4.16.3",
        "next": "6.1.1",
        "next-compose-plugins": "^1.0.3",
        "next-optimized-images": "^1.3.0",
        "next-redux-saga": "2.0.1",
        "next-redux-wrapper": "^1.3.4",
        "next-routes": "1.4.2",
        "nprogress": "^0.2.0",
        "prop-types": "15.6.1",
        "react": "^16.4.1",
        "react-dom": "^16.4.1",
        "react-redux": "5.0.7",
        "reactstrap": "^6.1.0",
        "redux": "4.0.0",
        "redux-devtools-extension": "^2.13.5",
        "redux-logger": "^3.0.6",
        "redux-saga": "^0.16.0",
        "svg-sprite-loader": "^3.8.0",
        "universal-cookie-express": "^2.1.0",
        "webpack": "^3.10.0"
    },
    "devDependencies": {
        "@storybook/addons": "^3.3.0",
        "@storybook/addon-actions": "3.4.0",
        "@storybook/addon-links": "3.4.0",
        "@storybook/react": "3.4.0",
        "autoprefixer": "8.2.0",
        "babel-plugin-transform-flow-strip-types": "^6.22.0",
        "babel-plugin-inline-react-svg": "^0.2.0",
        "enzyme": "3.2.0",
        "enzyme-adapter-react-16": "1.1.1",
        "eslint": "4.19.1",
        "eslint-config-airbnb": "^16.1.0",
        "eslint-config-prettier": "^2.9.0",
        "eslint-import-resolver-babel-module": "^4.0.0",
        "eslint-plugin-flowtype": "2.46.1",
        "eslint-plugin-import": "2.11.0",
        "eslint-plugin-jsx-a11y": "^6.0.2",
        "eslint-plugin-react": "7.7.0",
        "flow-bin": "0.69.0",
        "husky": "^0.14.3",
        "jest": "22.0.1",
        "lint-staged": "7.0.4",
        "node-sass": "4.8.3",
        "postcss-loader": "2.1.3",
        "prettier": "1.11.1",
        "prettier-eslint-cli": "4.7.1",
        "react-test-renderer": "16.2.0",
        "sass-loader": "6.0.7",
        "styled-jsx-css-loader": "^0.3.0"
    }
}

Marc Selhorst
Creative Technologist / Web Developer

06-16600289
marc@6foot7.nl <mailto:marc@6foot7.nl>

http://www.6foot7.nl <http://www.6foot7.nl/>
https://www.linkedin.com/in/marcselhorst <https://www.linkedin.com/in/marcselhorst>

**Comment by dev-drprasad** [comment]
can you try by removing following dependcies ??
```
"babel-core": "7.0.0-bridge.0"
"babel-runtime": "^6.0.0"
```

command ```npm uninstall --save babel-core babel-runtime```

**Comment by 6foot7** [comment]
Thank you so much! I got it working!

Op ma 2 jul. 2018 11:30 schreef REDDY PRASAD <notifications@github.com>:
