### ISSUE TITLE
Material UI 1.0.0 Tooltip fails with Typescript / Custom Server

### ISSUE THREAD

**Issue by tashburn** [zeit/next.js#4462]
## Expected Behavior

Tooltip works.

## Current Behavior

When trying to use the Material UI 1.0.0 `Tooltip` with Next and Typescript, and visit `localhost:3000` with a browser, the following error happens in the console:

```
This dependency was not found:

* popper.js in ./node_modules/react-popper/lib/Popper.js

To install it, you can run: npm install --save popper.js
```

And the following error happens in the browser:

```
Error in ./Popper
Module not found: Error: [CaseSensitivePathsPlugin] `/Users/trent/home/projects/Grok/tmp/issue-tooltip/node_modules/react-popper/lib/popper.js` does not match the corresponding path on disk `Popper.js`.
ModuleNotFoundError: Module not found: Error: [CaseSensitivePathsPlugin] `/Users/trent/home/projects/Grok/tmp/issue-tooltip/node_modules/react-popper/lib/popper.js` does not match the corresponding path on disk `Popper.js`.
    at factoryCallback (/Users/trent/home/projects/Grok/tmp/issue-tooltip/node_modules/webpack/lib/Compilation.js:276:40)
    at factory (/Users/trent/home/projects/Grok/tmp/issue-tooltip/node_modules/webpack/lib/NormalModuleFactory.js:235:20)
    at applyPluginsAsyncWaterfall (/Users/trent/home/projects/Grok/tmp/issue-tooltip/node_modules/webpack/lib/NormalModuleFactory.js:70:21)
    at /Users/trent/home/projects/Grok/tmp/issue-tooltip/node_modules/tapable/lib/Tapable.js:265:18
    at that.fileExistsWithCase (/Users/trent/home/projects/Grok/tmp/issue-tooltip/node_modules/case-sensitive-paths-webpack-plugin/index.js:156:15)
    at that.getFilenamesInDir (/Users/trent/home/projects/Grok/tmp/issue-tooltip/node_modules/case-sensitive-paths-webpack-plugin/index.js:97:7)
    at fs.readdir (/Users/trent/home/projects/Grok/tmp/issue-tooltip/node_modules/case-sensitive-paths-webpack-plugin/index.js:63:5)
    at /Users/trent/home/projects/Grok/tmp/issue-tooltip/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:70:14
    at process._tickCallback (internal/process/next_tick.js:112:11)
```

If I try `yarn add popper.js`, the following warning is produced and the errors above remain --

```
warning Pattern ["popper.js@1.14.3"] is trying to unpack in the same destination "/Users/trent/Library/Caches/Yarn/v1/npm-popper.js-1.14.3-1438f98d046acf7b4d78cd502bf418ac64d4f095" as pattern ["popper.js@^1.14.1"]. This could result in non-deterministic behavior, skipping.
```

## Context

This is blocking my project.

## Steps To Reproduce

1. `git clone git@github.com:tashburn/issue-tooltip.git`
2. `cd issue-tooltip`
3. `yarn install`
4. `yarn dev`
5. open `localhost:3000` in browser

## Environment

macOS (latest)
Chrome (latest)
custom server (express)
`typescript@2.8.3`
`next@6.0.3`
`@material-ui/core@1.0.0`

**Comment by timneutkens** [comment]
I don't think this issue is related to Next.js other than that you're using Next.js.

Please file issues with Material UI in their respective repository.

**Comment by tashburn** [comment]
Total understand. I wasn't sure (and am still not sure) about which project should be addressing this issue. The `material-ui` project says this issue isn't theirs either.
