### ISSUE TITLE
All examples failing to build with `Error: Cannot find module './dist/server/build/babel/preset'`

### ISSUE THREAD

**Issue by lukebarton** [zeit/next.js#4468]
# Examples bug report

## Example name
`with-react-helmet`, `using-router`, `basic-css` etc

## Describe the bug
Fails to build with bable error:
```
{ Error: Cannot find module './dist/server/build/babel/preset'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:571:15)
    at Function.Module._load (internal/modules/cjs/loader.js:497:25)
    at Module.require (internal/modules/cjs/loader.js:626:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/a_user/dev/nextbug/next.js/babel.js:1:80)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
    at Function.Module._load (internal/modules/cjs/loader.js:520:3)
    at Module.require (internal/modules/cjs/loader.js:626:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at requireModule (/Users/a_user/dev/nextbug/next.js/examples/with-react-helmet/node_modules/@babel/core/lib/config/files/plugins.js:142:12)
    at loadPreset (/Users/a_user/dev/nextbug/next.js/examples/with-react-helmet/node_modules/@babel/core/lib/config/files/plugins.js:56:15)
    at createDescriptor (/Users/a_user/dev/nextbug/next.js/examples/with-react-helmet/node_modules/@babel/core/lib/config/config-descriptors.js:152:21)
    at /Users/a_user/dev/nextbug/next.js/examples/with-react-helmet/node_modules/@babel/core/lib/config/config-descriptors.js:104:12 code: 'MODULE_NOT_FOUND' }
```

## To Reproduce
Steps to reproduce the behavior, please provide code snippets or a repository:
```
git clone git@github.com:zeit/next.js.git && cd ./next.js/examples/basic-css && yarn install && yarn run build
```
## Expected behavior
Should build without error

## System information
 - OS: `osx`
 - Version of Next.js: `6.0.3`

## Additional context
I think it's something to do with babel dependencies
Probably related to #4467

**Comment by timneutkens** [comment]
If you `git clone` you have to build Next.js (`yarn build` in the main directory) first before executing any of the examples, since the built babel preset is used. This is why none of the instructions for the examples mention cloning the repository 👍 Also cloning the repository for 1 out of 100+ examples takes a lot of time usually, that's why we favor downloading / `npx init` / `yarn create`

**Comment by timneutkens** [comment]
Babel looks recursively up the tree for a `.babelrc`, there is no way to disable this, so we had to add a .babelrc in the examples directory, except that doesn't allow for finding the respective next/babel for the example. So you have to manually build next.js and then the next/babel preset is available.

**Comment by timneutkens** [comment]
This is the babelrc: https://github.com/zeit/next.js/blob/canary/examples/.babelrc

**Comment by lukebarton** [comment]
Ahh, thanks!

**Comment by sydneywu** [comment]
So does it mean that in our own app, we need to include this .babelrc file too?
