### ISSUE TITLE
Building Local Master Clone fails

### ISSUE THREAD

**Issue by FrancosLab** [zeit/next.js#450]
Trying to build a local copy of latest `Master` to `link` into a project.

Asking for the debug/node module. Yet I am completely unaware of the existence of such package.

`npm i` and `yarn install` both produce the same effect

Am I missing a bigger picture?
```
[4/4] 📃  Building fresh packages...
success Saved lockfile.
$ gulp release
module.js:472
    throw err;
    ^

Error: Cannot find module 'debug/node'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/0x4e/Development/OSS/next.js/node_modules/babel-core/lib/transformation/file/logger.js:9:13)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
error Command failed with exit code 1.
```

**Comment by nkzawa** [comment]
It should work. What version of node do you use?

**Comment by FrancosLab** [comment]
Closing this, just realized for some reason, files were referencing and old location.
