### ISSUE TITLE
styled-jsx-scss and jest could not run in Next@6

### ISSUE THREAD

**Issue by blackbing** [zeit/next.js#4501]
# Bug report

## Describe the bug

This is a smallest reproduce example of styled-jsx-scss+jest problem. It is worked on next@5.1.0 In my project, but when upgrading to next@6, it will broke jest test. so I create an example to reproduce this problem.

Here is a repo:
<https://github.com/blackbing/next-with-jest-style-jsx-error>

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:
1. clone this https://github.com/blackbing/next-with-jest-style-jsx-error
2. `yarn test`

## Expected behavior
jest pass

## System information
 - OS: macOS
 - node: 8.11.2(10 could reproduce either)
 - Version of Next.js: 6.0.3

## Additional context

``` sh
$ NODE_ENV=test jest
 FAIL  __tests__/index.test.js
  With Enzyme
    ✕ App shows "Hello world!" (9ms)
  With Snapshot Testing
    ✕ App shows "Hello world!" (10ms)

  ● With Enzyme › App shows "Hello world!"

    ReferenceError: style is not defined

      2 |
      3 | export default () => (
  > 4 |   <div className='hello'>
      5 |     <p>Hello World</p>
      6 |     <style jsx global>{style}</style>
      7 |   </div>

      at Object._default [as type] (pages/index.js:4:3)
      at Object.<anonymous> (__tests__/index.test.js:11:17)

  ● With Snapshot Testing › App shows "Hello world!"

    ReferenceError: style is not defined



      at _default (pages/index.js:21:10)
      at Object.<anonymous> (__tests__/index.test.js:22:48)
```

**Comment by blackbing** [comment]
related to <https://github.com/zeit/next.js/issues/4265>

**Comment by JimLin94** [comment]
This is real concern to me as well!

**Comment by blackbing** [comment]
I can reproduce in Babel7. 
checkout this branch 
https://github.com/blackbing/styled-jsx/tree/upgrade-babel7


and  the snapshot shows the same problem in this case.
https://github.com/blackbing/styled-jsx/blob/upgrade-babel7/test/snapshots/index.js.md#works-with-styled-jsx-styles-and-babel-preset-env
