### ISSUE TITLE
Material-UI Tooltip works with built-in Next server, but not with custom server

### ISSUE THREAD

**Issue by tashburn** [zeit/next.js#4538]
# Bug report

## Describe the bug

There seems to be something about using a custom server with Next that causes a compilation error when using the material-ui `Tooltip`. It works without a custom server.

I've combined these canonical examples --

- https://github.com/zeit/next.js/tree/canary/examples/with-typescript
- https://github.com/zeit/next.js/tree/canary/examples/custom-server-express
- https://github.com/mui-org/material-ui/tree/master/examples/nextjs

-- into the repo https://github.com/tashburn/issue-tooltip

In the repo's `package.json`, there are two scripts --

`yarn dev` (without a custom server) which works fine.
`yarn dev-custom-server` (with a custom server) which fails.

The only difference is using the simple custom server.

This is the error --

```
ModuleNotFoundError: Module not found: Error: [CaseSensitivePathsPlugin] `/Users/trent/home/projects/Grok/tmp/issue-tooltip/node_modules/react-popper/lib/popper.js` does not match the corresponding path on disk `Popper.js`.
    at factoryCallback (/Users/trent/home/projects/Grok/tmp/issue-tooltip/node_modules/webpack/lib/Compilation.js:276:40)
    at factory (/Users/trent/home/projects/Grok/tmp/issue-tooltip/node_modules/webpack/lib/NormalModuleFactory.js:235:20)
    at applyPluginsAsyncWaterfall (/Users/trent/home/projects/Grok/tmp/issue-tooltip/node_modules/webpack/lib/NormalModuleFactory.js:70:21)
    at /Users/trent/home/projects/Grok/tmp/issue-tooltip/node_modules/tapable/lib/Tapable.js:265:18
    at that.fileExistsWithCase (/Users/trent/home/projects/Grok/tmp/issue-tooltip/node_modules/case-sensitive-paths-webpack-plugin/index.js:156:15)
    at that.getFilenamesInDir (/Users/trent/home/projects/Grok/tmp/issue-tooltip/node_modules/case-sensitive-paths-webpack-plugin/index.js:97:7)
    at CaseSensitivePathsPlugin.getFilenamesInDir (/Users/trent/home/projects/Grok/tmp/issue-tooltip/node_modules/case-sensitive-paths-webpack-plugin/index.js:47:5)
    at CaseSensitivePathsPlugin.fileExistsWithCase (/Users/trent/home/projects/Grok/tmp/issue-tooltip/node_modules/case-sensitive-paths-webpack-plugin/index.js:85:8)
    at that.primeCache (/Users/trent/home/projects/Grok/tmp/issue-tooltip/node_modules/case-sensitive-paths-webpack-plugin/index.js:150:14)
    at CaseSensitivePathsPlugin.primeCache (/Users/trent/home/projects/Grok/tmp/issue-tooltip/node_modules/case-sensitive-paths-webpack-plugin/index.js:116:5)
    at NormalModuleFactory.nmf.plugin (/Users/trent/home/projects/Grok/tmp/issue-tooltip/node_modules/case-sensitive-paths-webpack-plugin/index.js:145:12)
    at NormalModuleFactory.applyPluginsAsyncWaterfall (/Users/trent/home/projects/Grok/tmp/issue-tooltip/node_modules/tapable/lib/Tapable.js:272:13)
    at resolver (/Users/trent/home/projects/Grok/tmp/issue-tooltip/node_modules/webpack/lib/NormalModuleFactory.js:69:10)
    at process.nextTick (/Users/trent/home/projects/Grok/tmp/issue-tooltip/node_modules/webpack/lib/NormalModuleFactory.js:194:7)
    at process._tickCallback (internal/process/next_tick.js:112:11)
ModuleNotFoundError: Module not found: Error: [CaseSensitivePathsPlugin] `/Users/trent/home/projects/Grok/tmp/issue-tooltip/node_modules/react-popper/lib/popper.js` does not match the corresponding path on disk `Popper.js`.
    at factoryCallback (/Users/trent/home/projects/Grok/tmp/issue-tooltip/node_modules/webpack/lib/Compilation.js:276:40)
    at factory (/Users/trent/home/projects/Grok/tmp/issue-tooltip/node_modules/webpack/lib/NormalModuleFactory.js:235:20)
    at applyPluginsAsyncWaterfall (/Users/trent/home/projects/Grok/tmp/issue-tooltip/node_modules/webpack/lib/NormalModuleFactory.js:70:21)
    at /Users/trent/home/projects/Grok/tmp/issue-tooltip/node_modules/tapable/lib/Tapable.js:265:18
    at that.fileExistsWithCase (/Users/trent/home/projects/Grok/tmp/issue-tooltip/node_modules/case-sensitive-paths-webpack-plugin/index.js:156:15)
    at that.getFilenamesInDir (/Users/trent/home/projects/Grok/tmp/issue-tooltip/node_modules/case-sensitive-paths-webpack-plugin/index.js:97:7)
    at CaseSensitivePathsPlugin.getFilenamesInDir (/Users/trent/home/projects/Grok/tmp/issue-tooltip/node_modules/case-sensitive-paths-webpack-plugin/index.js:47:5)
    at CaseSensitivePathsPlugin.fileExistsWithCase (/Users/trent/home/projects/Grok/tmp/issue-tooltip/node_modules/case-sensitive-paths-webpack-plugin/index.js:85:8)
    at that.primeCache (/Users/trent/home/projects/Grok/tmp/issue-tooltip/node_modules/case-sensitive-paths-webpack-plugin/index.js:150:14)
    at CaseSensitivePathsPlugin.primeCache (/Users/trent/home/projects/Grok/tmp/issue-tooltip/node_modules/case-sensitive-paths-webpack-plugin/index.js:116:5)
    at NormalModuleFactory.nmf.plugin (/Users/trent/home/projects/Grok/tmp/issue-tooltip/node_modules/case-sensitive-paths-webpack-plugin/index.js:145:12)
    at NormalModuleFactory.applyPluginsAsyncWaterfall (/Users/trent/home/projects/Grok/tmp/issue-tooltip/node_modules/tapable/lib/Tapable.js:272:13)
    at resolver (/Users/trent/home/projects/Grok/tmp/issue-tooltip/node_modules/webpack/lib/NormalModuleFactory.js:69:10)
    at process.nextTick (/Users/trent/home/projects/Grok/tmp/issue-tooltip/node_modules/webpack/lib/NormalModuleFactory.js:194:7)
    at process._tickCallback (internal/process/next_tick.js:112:11)


 ERROR  Failed to compile with 1 errors                                                                    13:45:07

This dependency was not found:

* popper.js in ./node_modules/react-popper/lib/Popper.js

To install it, you can run: npm install --save popper.js
```

## To Reproduce

1. `git clone https://github.com/tashburn/issue-tooltip`
2. `cd issue-tooltip`
3. `yarn install`
4. `yarn run dev` 
5. Go to http://localhost:3000. *It will work.*
6. ^C to stop the server
7. `yarn run dev-custom-server`
8. Go to http://localhost:3000. *It will fail.*

## System information
 - OS: macOS
 - Version of Next.js: 6.0.3
 - Version of Material UI: 1.2.0
 - Version of Typescript: 2.9.1

**Comment by timneutkens** [comment]
It's related to the way typescript compiles modules when booting it up with ts-node.
So it's not a bug in Next.js but something in your configuration or a bug in Typescript. If you copy `server.ts` to `server.js` it works fine for example. I've also tried changing to @babel/node (babel-node) and using the same config that's used to compile the client side code. But that didn't work either. You'll probably have to debug the output of typescript and find where exactly it transforms to the lowercase name. It could also just be that there really is a filename inconsistency in the react-popper package, which would cause issues on nearly every Linux machine. So it might be worth creating an issue on that package. I've ruled out Next.js itself as the cause (yes we do run `CaseSensitivePathsPlugin`, but there are no issues with compilation without the ts-node configuration).

**Comment by tashburn** [comment]
@timneutkens That's some really useful clarity and leads, thanks for taking a look and explaining. I'll try to narrow down what's responsible.

**Comment by tashburn** [comment]
@timneutkens, I removed all the typescript from my repo, making it straight JS. I still get this issue, so it's not typescript. But I found that what triggers it is having `NODE_PATH=.` before `node server.js`.

So in the `package.js` --

```
  "scripts": {
    "dev-works": "node server.js",
    "dev-fails": "NODE_PATH=. node server.js"
  },
```

I'm using `NODE_PATH=.` for absolute-path imports.

I realize this is not a Next issue, but if this latest info sparks any quick thoughts in your intuition, I'd appreciate any clues to help me track this down.

**Comment by timneutkens** [comment]
Maybe it goes wrong here: https://github.com/zeit/next.js/blob/18676e08703a8d6c39049fe15996f3ede23323ae/server/build/webpack.js#L64-L66 then 🤔

**Comment by tashburn** [comment]
Strangely, using `NODE_PATH=$(pwd)` is a workaround.

**Comment by timneutkens** [comment]
https://nodejs.org/api/modules.html#modules_loading_from_the_global_folders

> If the NODE_PATH environment variable is set to a colon-delimited list of absolute paths, then Node.js will search those paths for modules if they are not found elsewhere.

So apparently it's correct behavior, although it breaks the case-sensitive paths webpack plugin 😄
