### ISSUE TITLE
Cannot find module '@babel/core'

### ISSUE THREAD

**Issue by vpicone** [zeit/next.js#4548]
# Bug report

## Describe the bug

Unable to run `next` from a brand new project. The following error comes up:
```
Error: Cannot find module '@babel/core'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:548:15)
    at Function.Module._load (internal/modules/cjs/loader.js:475:25)
    at Module.require (internal/modules/cjs/loader.js:598:17)
    at require (internal/modules/cjs/helpers.js:11:18)
    at Object.<anonymous> (/Users/vincepicone/Programming/Personal/raven-next-test/node_modules/next/dist/server/build/webpack.js:40:13)
    at Module._compile (internal/modules/cjs/loader.js:654:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:665:10)
    at Module.load (internal/modules/cjs/loader.js:566:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:506:12)
    at Function.Module._load (internal/modules/cjs/loader.js:498:3)
    at Module.require (internal/modules/cjs/loader.js:598:17)
    at require (internal/modules/cjs/helpers.js:11:18)
    at Object.<anonymous> (/Users/vincepicone/Programming/Personal/raven-next-test/node_modules/next/dist/server/hot-reloader.js:46:40)
    at Module._compile (internal/modules/cjs/loader.js:654:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:665:10)
    at Module.load (internal/modules/cjs/loader.js:566:32)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! raven-next-test@1.0.0 dev: `next`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the raven-next-test@1.0.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/vincepicone/.npm/_logs/2018-06-06T15_12_39_952Z-debug.log
```

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:
1. Make a new directory
1. Enter the directory and init an npm project
1. `npm install --save next react react-dom`
1. Populate the `./pages/index.js` file with `export default () => <div>Welcome to next.js!</div>;`
1. Add the following scripts to the package.json, then `npm run dev`
```
{
  "scripts": {
    "dev": "next",
    "build": "next build",
    "start": "next start"
  }
}
```

## Expected behavior
Project enters development mode

## System information
 - OS: Mac, node version 9.11.1 npm version 5.6.0
 - Version of Next.js: 
```
"dependencies": {
    "next": "^6.0.3",
    "react": "^16.4.0",
    "react-dom": "^16.4.0"
  }
```

**Comment by vpicone** [comment]
I think this was something weird with npm or yarn or my node version manager. Either way I cleared the npm cache, removed everything and tried again with yarn. It worked fine. Then I tried with npm and it worked fine too. 🤷‍♂️

**Comment by tommypater** [comment]
I confirm, npm, cache and babel sometimes, make delicate situations...
