### ISSUE TITLE
TypeError: Cannot read property '1' of undefined

### ISSUE THREAD

**Issue by YuriBrunetto** [zeit/next.js#4551]
I just updated my project using `next.js` from `v4.2.3` to `v6.0.3` (current stable version). Well, I _**guess**_ the new version broke my `next.config.js` file, here's the error when I run `yarn run dev`:

```bash
Module build failed: TypeError: Cannot read property '1' of undefined
    at Plugin.manipulateOptions (/Users/ezoom-dev/Documents/htdocs/sat7-site/node_modules/babel-plugin-module-resolver/lib/index.js:88:9)
    at normalizeOptions (/Users/ezoom-dev/Documents/htdocs/sat7-site/node_modules/@babel/core/lib/transformation/normalize-opts.js:80:17)
    at runSync (/Users/ezoom-dev/Documents/htdocs/sat7-site/node_modules/@babel/core/lib/transformation/index.js:34:84)
    at runAsync (/Users/ezoom-dev/Documents/htdocs/sat7-site/node_modules/@babel/core/lib/transformation/index.js:25:14)
    at /Users/ezoom-dev/Documents/htdocs/sat7-site/node_modules/@babel/core/lib/transform.js:32:34
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)

 @ multi ./pages/_error.js
```

My `next.config.js` file:
```javascript
const path = require('path')
const glob = require('glob')

module.exports = {
  webpack: (config, { dev }) => {
    config.module.rules.push(
      {
        test: /\.(css|scss)/,
        loader: 'emit-file-loader',
        options: {
          name: 'dist/[path][name].[ext]'
        }
      }
    ,
      {
        test: /\.css$/,
        use: ['babel-loader', 'raw-loader', 'postcss-loader']
      }
    ,
      {
        test: /\.s(a|c)ss$/,
        use: ['babel-loader', 'raw-loader', 'postcss-loader',
          { loader: 'sass-loader',
            options: {
              includePaths: ['styles', 'node_modules']
                .map((d) => path.join(__dirname, d))
                .map((g) => glob.sync(g))
                .reduce((a, c) => a.concat(c), [])
            }
          }
        ]
      }
    )
    return config
  }
}
```

Is this a common error? Can somebody help me? 
Thanks in advance!

**Comment by timneutkens** [comment]
It's probably .babelrc or you need to upgrade specific babel plugins.

**Comment by YuriBrunetto** [comment]
Thank you, @timneutkens! That was it, it's working now 😃
