### ISSUE TITLE
Learn Next.js Styling Components - Global Styles error

### ISSUE THREAD

**Issue by insekticid** [zeit/next.js#4592]
https://nextjs.org/learn/basics/styling-components/global-styles

error:
```
__WEBPACK_IMPORTED_MODULE_3_next_router___default(...) is not a function
TypeError: __WEBPACK_IMPORTED_MODULE_3_next_router___default(...) is not a function
    at Object../pages/markdown.js (pages/markdown.js:5:0)
    at __webpack_require__ (webpack:/webpack/bootstrap 7f440147c0ed2088d83d:21:0)
    at Object.3 (/app/.next/dist/bundles/pages/markdown.js:217:18)
    at __webpack_require__ (webpack:/webpack/bootstrap 7f440147c0ed2088d83d:21:0)
    at /app/.next/dist/bundles/pages/markdown.js:70:18
    at Object.<anonymous> (/app/.next/dist/bundles/pages/markdown.js:73:10)
    at Module._compile (internal/modules/cjs/loader.js:654:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:665:10)
    at Module.load (internal/modules/cjs/loader.js:566:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:506:12)
    at Function.Module._load (internal/modules/cjs/loader.js:498:3)
    at Module.require (internal/modules/cjs/loader.js:598:17)
    at require (internal/modules/cjs/helpers.js:11:18)
    at _callee$ (/app/node_modules/next/dist/server/require.js:87:46)
    at tryCatch (/app/node_modules/regenerator-runtime/runtime.js:62:40)
    at Generator.invoke [as _invoke] (/app/node_modules/regenerator-runtime/runtime.js:296:22)
```
replace `withRouter ` to `{ withRouter }` - line number 2

Chrome 68, docker: node:9-alpine (v9.11.1)

```
import Layout from '../components/MyLayout.js'
import withRouter from 'next/router'
import Markdown from 'react-markdown'

export default withRouter((props) => (
  <Layout>
   <h1>{props.router.query.title}</h1>
   <div className="markdown">
     <Markdown source={`
This is our blog post.
Yes. We can have a [link](/link).
And we can have a title as well.

### This is a title

And here's the content.
     `}/>
   </div>
   <style jsx global>{`
     .markdown {
       font-family: 'Arial';
     }

     .markdown a {
       text-decoration: none;
       color: blue;
     }

     .markdown a:hover {
       opacity: 0.6;
     }

     .markdown h3 {
       margin: 0;
       padding: 0;
       text-transform: uppercase;
     }
  `}</style>
  </Layout>
))
```

**Comment by timneutkens** [comment]
Thanks! Fixed 👍
