### ISSUE TITLE
Using <title> in _document.js's <Head> tag should show a warning to use _app.js instead

### ISSUE THREAD

**Issue by timneutkens** [zeit/next.js#4596]
# Bug report

Based on #3527

## Describe the bug

Currently, users might add `<title>` in `_document.js` which will lead to unexpected results with `next/head` since `_document.js` is only rendered on the initial pre-render. `_app.js` is rendered on the server and client side, and is rendered as a normal React tree, whereas _document.js is rendered as static HTML.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:
1. Copy the default `_document.js` and add `<title>`:
```
// _document is only rendered on the server side and not on the client side
// Event handlers like onClick can't be added to this file

// ./pages/_document.js
import Document, { Head, Main, NextScript } from 'next/document'

export default class MyDocument extends Document {
  static async getInitialProps(ctx) {
    const initialProps = await Document.getInitialProps(ctx)
    return { ...initialProps }
  }

  render() {
    return (
      <html>
        <Head>
          <title>Hello World</title>
        </Head>
        <body className="custom_class">
          <Main />
          <NextScript />
        </body>
      </html>
    )
  }
}
```

## Expected behavior

Above example should show a warning that `<title>` should only be used in _app.js and other pages. This can be done using `err.sh`, create a link like: `https://err.sh/next.js/no-document-title` and create a file in the `errors` directory: `errors/no-document-title.md`

**Comment by remy** [comment]
Question on this issue - is including `<head><title>xyz</title></head>` okay? (note this is the regular `head` element and not the React element.

Can I also ask what's the thinking behind `title` being set in `_app.js` over `_document.js`? It _seems_ (without background) to be more intuitive that I would set the title in the document.

**Comment by timneutkens** [comment]
A title is directly correlated to a page. So it should be set in a page. `<Head>` from `next/document` is a wrapper around the real `<head>` tag, you shouldn't implement it yourself. The reason you should use `next/head` for this is that next/head managed the title and all other head elements.

**Comment by timneutkens** [comment]
@davscro go ahead 👍🙌

**Comment by davscro** [comment]
Ok, thanks. 
Over the weekend, between soccer matches ⚽️🇭🇷, I will take care of this task. 😀

**Comment by davscro** [comment]
Hi @teleginzhenya, feel free to suggest solution.
@timneutkens I did it, but I think this is not a right way to fix it, IMO it should be one-time check probably during the build time, what do u think?

**Comment by rainstormza** [comment]
https://github.com/zeit/next.js/tree/canary/examples/with-styled-components

This example should be fixed?

it use <Head> tag in _document.js

@timneutkens

**Comment by timneutkens** [comment]
Yes, feel free to update it @rainstormza.

I'm going to close this issue as it was fixed in #5160.

**Comment by rainstormza** [comment]
@timneutkens 
How can we inject css-in-js on server side if we can't use` <Head> `tag in _document.js ?

refs: https://github.com/zeit/next.js#custom-document

**Comment by timneutkens** [comment]
You can use the head tag, just not for setting <title> as it leads to unexpected behavior

**Comment by zargold** [comment]
Using react helmet seems to trigger this warning.

**Comment by mattdell** [comment]
What if I purposely want this behavior? How can I stop it from saying...

```
Warning: <title> should not be used in _document.js's <Head>. https://err.sh/next.js/no-document-title
```

**Comment by jrosspaperless** [comment]
My project is experiencing the same warning with `react-helmet-async`. I am going to create a PR to remove the warning for this rendition of Helmet. Please let me know if you think this is an issue. Thank you!

**Comment by itpreneur** [comment]
import Head from 'next/head';

from your pages e.g. index.js etc.

<Head> <title> cool title </title> </Head>

**Comment by Pushplaybang** [comment]
Hi There, I followed the error message, landing up here, moved my Head element, title and description meta tag to _app and received the following:

```
TypeError: Cannot read property '_documentProps' of null
    at Head.render (/Users/paul/repositories/coronasepush-web/.next/server/static/development/pages/_document.js:665:22)
    at processChild (/Users/paul/repositories/coronasepush-web/node_modules/react-dom/cjs/react-dom-server.node.development.js:3134:18)
    at resolve (/Users/paul/repositories/coronasepush-web/node_modules/react-dom/cjs/react-dom-server.node.development.js:2960:5)
    at ReactDOMServerRenderer.render (/Users/paul/repositories/coronasepush-web/node_modules/react-dom/cjs/react-dom-server.node.development.js:3435:22)
    at ReactDOMServerRenderer.read (/Users/paul/repositories/coronasepush-web/node_modules/react-dom/cjs/react-dom-server.node.development.js:3373:29)
    at renderToString (/Users/paul/repositories/coronasepush-web/node_modules/react-dom/cjs/react-dom-server.node.development.js:3988:27)
    at render (/Users/paul/repositories/coronasepush-web/node_modules/next/dist/next-server/server/render.js:83:16)
    at renderPage (/Users/paul/repositories/coronasepush-web/node_modules/next/dist/next-server/server/render.js:406:16)
    at Object.ctx.renderPage (/Users/paul/repositories/coronasepush-web/.next/server/static/development/pages/_document.js:1693:28)
    at Function.getInitialProps (/Users/paul/repositories/coronasepush-web/.next/server/static/development/pages/_document.js:506:19)
    at Function.module.exports../src/pages/_document.js.MyDocument.getInitialProps (/Users/paul/repositories/coronasepush-web/.next/server/static/development/pages/_document.js:1704:85)
    at Object.loadGetInitialProps (/Users/paul/repositories/coronasepush-web/node_modules/next/dist/next-server/lib/utils.js:59:29)
    at Object.renderToHTML (/Users/paul/repositories/coronasepush-web/node_modules/next/dist/next-server/server/render.js:410:36)
[ event ] build page: /next/dist/pages/_error
[ wait ]  compiling ...
[ info ]  bundled successfully, waiting for typecheck results...
[ ready ] compiled successfully - ready on http://localhost:3000
TypeError: Cannot read property '_documentProps' of null
    at Head.render (/Users/paul/repositories/coronasepush-web/.next/server/static/development/pages/_document.js:665:22)
    at processChild (/Users/paul/repositories/coronasepush-web/node_modules/react-dom/cjs/react-dom-server.node.development.js:3134:18)
    at resolve (/Users/paul/repositories/coronasepush-web/node_modules/react-dom/cjs/react-dom-server.node.development.js:2960:5)
    at ReactDOMServerRenderer.render (/Users/paul/repositories/coronasepush-web/node_modules/react-dom/cjs/react-dom-server.node.development.js:3435:22)
    at ReactDOMServerRenderer.read (/Users/paul/repositories/coronasepush-web/node_modules/react-dom/cjs/react-dom-server.node.development.js:3373:29)
    at renderToString (/Users/paul/repositories/coronasepush-web/node_modules/react-dom/cjs/react-dom-server.node.development.js:3988:27)
    at render (/Users/paul/repositories/coronasepush-web/node_modules/next/dist/next-server/server/render.js:83:16)
    at renderPage (/Users/paul/repositories/coronasepush-web/node_modules/next/dist/next-server/server/render.js:406:16)
    at Object.ctx.renderPage (/Users/paul/repositories/coronasepush-web/.next/server/static/development/pages/_document.js:1693:28)
 
```

**Comment by rjerue** [comment]
> Hi There, I followed the error message, landing up here, moved my Head element, title and description meta tag to _app and received the following:
> 
> ```
> TypeError: Cannot read property '_documentProps' of null
>     at Head.render (/Users/paul/repositories/coronasepush-web/.next/server/static/development/pages/_document.js:665:22)
>     at processChild (/Users/paul/repositories/coronasepush-web/node_modules/react-dom/cjs/react-dom-server.node.development.js:3134:18)
>     at resolve (/Users/paul/repositories/coronasepush-web/node_modules/react-dom/cjs/react-dom-server.node.development.js:2960:5)
>     at ReactDOMServerRenderer.render (/Users/paul/repositories/coronasepush-web/node_modules/react-dom/cjs/react-dom-server.node.development.js:3435:22)
>     at ReactDOMServerRenderer.read (/Users/paul/repositories/coronasepush-web/node_modules/react-dom/cjs/react-dom-server.node.development.js:3373:29)
>     at renderToString (/Users/paul/repositories/coronasepush-web/node_modules/react-dom/cjs/react-dom-server.node.development.js:3988:27)
>     at render (/Users/paul/repositories/coronasepush-web/node_modules/next/dist/next-server/server/render.js:83:16)
>     at renderPage (/Users/paul/repositories/coronasepush-web/node_modules/next/dist/next-server/server/render.js:406:16)
>     at Object.ctx.renderPage (/Users/paul/repositories/coronasepush-web/.next/server/static/development/pages/_document.js:1693:28)
>     at Function.getInitialProps (/Users/paul/repositories/coronasepush-web/.next/server/static/development/pages/_document.js:506:19)
>     at Function.module.exports../src/pages/_document.js.MyDocument.getInitialProps (/Users/paul/repositories/coronasepush-web/.next/server/static/development/pages/_document.js:1704:85)
>     at Object.loadGetInitialProps (/Users/paul/repositories/coronasepush-web/node_modules/next/dist/next-server/lib/utils.js:59:29)
>     at Object.renderToHTML (/Users/paul/repositories/coronasepush-web/node_modules/next/dist/next-server/server/render.js:410:36)
> ```

See https://github.com/vercel/next.js/issues/9647#issuecomment-583844001

**Comment by crevulus** [comment]
> import Head from 'next/head';
> 
> from your pages e.g. index.js etc.
> 
> <title> cool title </title>

so then, if I'm understanding right, the current best practice to insert `<Head>` tag with `<title>` tags in **every** page, rather than jut setting it once in _document.js?

**Comment by filipesmedeiros** [comment]
@crevulus Afaik, you can set a "global" title in `_app.tsx` or in individual pages

**Comment by Oosasukel** [comment]
You should import Head from `'next/head'` instead `'next/document'` to put the title

**Comment by barthuijgen** [comment]
I need the title to be part of the page source when using SSG so that SEO/embedding will read it properly. Moving `<title>` and `<meta property="og:title" content="..."/>` to `_app.tsx` makes certain embed tools fail to read it.

It may be a problem when you are using SSR but when you just use the server for development this warning is highly confusing. It should definitely be mutable for projects that only use SSG.

**Comment by phiberber** [comment]
Hey, I'm having some problems related to this issue. When creating a _document file, it prompts the following message:

`warn  - Your custom Document (pages/_document) did not render all the required subcomponent.
Missing component: <Head />
Read how to fix here: https://nextjs.org/docs/messages/missing-document-component`

For some reason, it prompts another warning saying.

`Missing required 'title' element`

And obviously, I can't set the title in the _document. Is someone having the same problem? Didn't think it was enough to create a new issue.

**Comment by nazywamsiepawel** [comment]
Hey did anyone manage to solve this with Next 12? Using 12.0.6 currently.

I have a _document.js but not specifying title/head in there. Using next/head in my pages and all of the tags land in the body not in head. It's a pretty bad result for SEO.

**Comment by balazsorban44** [comment]
If you have issues, I suggest opening a new bug report with a reproduction. :pray:
