### ISSUE TITLE
How to include local package written in typescript

### ISSUE THREAD

**Issue by AleksandarAleksandrov** [zeit/next.js#4621]
I have a shared component library that I have linked to my project.
```json
"dependencies": {
   ...
    "shared-habit": "link:../shared-habit"
  },
```

This package is written in typescript. My project also uses typescript. I don't want to build the `shared-habit` package every time I make a change to it so my project can use it. For that reason I set the `main` property in the `package.json` of the `shared-habit` library like so: `"main": "src/lib/index.js"`

I tried to make webpack compile and use the tsx files in the shared-habit package but wit no success:

*next.config.js*
```js
const withTypescript = require("@zeit/next-typescript");
const ForkTsCheckerWebpackPlugin = require("fork-ts-checker-webpack-plugin");
const withCSS = require("@zeit/next-css");
const withPlugins = require("next-compose-plugins");
const { BundleAnalyzerPlugin } = require("webpack-bundle-analyzer");
const { ANALYZE } = process.env;

const fs = require("fs");
// paths for the tsx files in the linked local package
var includePaths = [
  fs.realpathSync(__dirname + "/node_modules/shared-habit")
];

const NEXT_CONFIG = withTypescript({
  webpack: (config, options) => {
    // Fixes npm packages that depend on `fs` module
    config.node = {
      fs: "empty"
    };

    // Do not run type checking twice:
    if (options.isServer) config.plugins.push(new ForkTsCheckerWebpackPlugin());

    // analyze generated bundle
    if (ANALYZE) {
      config.plugins.push(
        new BundleAnalyzerPlugin({
          analyzerMode: "server",
          analyzerPort: options.isServer ? 8888 : 8889,
          openAnalyzer: true
        })
      );
    }
    
   // push the rules for the shared library
    config.module.rules.push({
      test: /\.(ts|tsx)$/,
      include: includePaths,
      use: options.defaultLoaders.babel
    });

    console.log(config.module.rules);
    return config;
  }
});

const PLUGINS = [
  [
    withCSS,
    {
      cssModules: true,
      cssLoaderOptions: {
        importLoaders: 1,
        localIdentName: "[local]___[hash:base64:5]"
      }
    }
  ]
];
module.exports = withPlugins(PLUGINS, NEXT_CONFIG);

```

I get this error:

```sh
> Using external babel configuration> Location: "C:\pp\habit\web\.babelrc"
[ { test: /\.(js|jsx)$/,    loader: 'hot-self-accept-loader',    include:
     [ 'C:\\pp\\habit\\web\\pages',
       'C:\\pp\\habit\\web\\node_modules\\next\\pages' ],
    options: { extensions: /\.(js|jsx)$/ } },
  { test: /\.(js|jsx)$/,
    include: [ 'C:\\pp\\habit\\web' ],
    exclude: /node_modules/,
    use: { loader: 'babel-loader', options: [Object] } },
  { test: /\.css$/,
    use: [ 'extracted-loader', [Object], [Object] ] },
  { test: /\.(ts|tsx)$/,
    loader: 'hot-self-accept-loader',
    include: [ 'C:\\pp\\habit\\web\\pages' ],
    options: { extensions: /\.(ts|tsx)$/ } },
  { test: /\.(ts|tsx)$/,
    include: [ 'C:\\pp\\habit\\web' ],
    exclude: /node_modules/,
    use: { loader: 'babel-loader', options: [Object] } },
  { test: /\.(ts|tsx)$/,
    include: [ 'C:\\pp\\habit\\shared-habit' ],
    use: { loader: 'babel-loader', options: [Object] } } ]
[ { test: /\.(js|jsx)$/,
    include: [ 'C:\\pp\\habit\\web' ],
    exclude: /node_modules/,
    use: { loader: 'babel-loader', options: [Object] } },
  { test: /\.css$/, use: [ [Object] ] },  { test: /\.(ts|tsx)$/,    include: [ 'C:\\pp\\habit\\web' ],
    exclude: /node_modules/,
    use: { loader: 'babel-loader', options: [Object] } },
  { test: /\.(ts|tsx)$/,
    include: [ 'C:\\pp\\habit\\shared-habit' ],
    use: { loader: 'babel-loader', options: [Object] } } ]
Starting type checking service...
Using 1 worker with 2048MB memory limit
Version: typescript 2.9.1
Time: 2069ms


 ERROR  Failed to compile with 2 errors            12:02:13 AM
 error  in ../shared-habit/src/lib/Sidebar/SidebarElement.tsx

Module build failed: Error: Using `babel-preset-react-app` requires that you specify `NODE_ENV` or `BABEL_ENV` environment variables. Valid values are "development", "test", and "production". Instead, received: undefined.
    at Object.<anonymous> (C:\pp\habit\shared-habit\node_modules\babel-preset-react-app\index.js:51:9)
    at Module._compile (internal/modules/cjs/loader.js:702:30)    at Module._extensions..js (internal/modules/cjs/loader.js:713:10)
    at Object.require.extensions.(anonymous function) [as .js] (C:\pp\habit\web\node_modules\ts-node\src\index.ts:422:14)
    at Module.load (internal/modules/cjs/loader.js:612:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
    at Function.Module._load (internal/modules/cjs/loader.js:543:3)
    at Module.require (internal/modules/cjs/loader.js:650:17)
    at require (internal/modules/cjs/helpers.js:20:18)
PS C:\pp\habit\web> npm run dev
> web@ dev C:\pp\habit\web> nodemon server/index.ts
[nodemon] 1.17.5[nodemon] to restart at any time, enter `rs`[nodemon] watching: server/**/*.ts
[nodemon] starting `ts-node --compilerOptions {"""module""":"""commonjs"""} server/index.ts`> Using external babel configuration> Location: "C:\pp\habit\web\.babelrc"
{ rules:   [ { test: /\.(js|jsx)$/,       loader: 'hot-self-accept-loader',
       include: [Array],
       options: [Object] },
     { test: /\.(js|jsx)$/,
       include: [Array],
       exclude: /node_modules/,
       use: [Object] },
     { test: /\.css$/, use: [Array] },
     { test: /\.(ts|tsx)$/,
       loader: 'hot-self-accept-loader',
       include: [Array],
       options: [Object] },
     { test: /\.(ts|tsx)$/,
       include: [Array],
       exclude: /node_modules/,
       use: [Object] },
     { test: /\.(ts|tsx)$/, include: [Array], use: [Object] }
] }
{ rules:
   [ { test: /\.(js|jsx)$/,
       include: [Array],
       exclude: /node_modules/,
       use: [Object] },
     { test: /\.css$/, use: [Array] },
     { test: /\.(ts|tsx)$/,
       include: [Array],       exclude: /node_modules/,       use: [Object] },
     { test: /\.(ts|tsx)$/, include: [Array], use: [Object] }
] }
Starting type checking service...
Using 1 worker with 2048MB memory limit
ERROR in C:/pp/habit/web/components/AppShell/Header/index.tsx(2,17):
TS2307: Cannot find module './index.css'.
ERROR in C:/pp/habit/web/components/AppShell/index.tsx(4,22):
TS2307: Cannot find module 'react-native'.
ERROR in C:/pp/habit/web/components/AppShell/index.tsx(5,17):
TS2307: Cannot find module './index.css'.
ERROR in C:/pp/habit/web/components/AppShell/Sidebar/index.tsx(2,17):
TS2307: Cannot find module './index.css'.
ERROR in C:/pp/habit/web/components/AppShell/Sidebar/index.tsx(5,21):
TS2307: Cannot find module 'static/icons/browser.svg'.
ERROR in C:/pp/habit/web/pages/_app.tsx(1,17):
TS6133: 'Component' is declared but its value is never read.
ERROR in C:/pp/habit/web/pages/_app.tsx(7,43):
TS2339: Property 'props' does not exist on type 'MyApp'.
ERROR in C:/pp/habit/web/pages/_document.tsx(2,29):
TS2307: Cannot find module 'react-native'.
ERROR in C:/pp/habit/web/pages/_document.tsx(16,18):
TS2339: Property 'jsx' does not exist on type 'DetailedHTMLProps<StyleHTMLAttributes<HTMLStyleElement>, HTMLStyleElement>'.
ERROR in C:/pp/habit/web/pages/index.tsx(41,12):
TS2339: Property 'jsx' does not exist on type 'DetailedHTMLProps<StyleHTMLAttributes<HTMLStyleElement>, HTMLStyleElement>'.
Version: typescript 2.9.1
Time: 2108ms


 ERROR  Failed to compile with 2 errors            12:03:54 AM
 error  in ../shared-habit/src/lib/Sidebar/SidebarElement.tsx

Module build failed: Error: Using `babel-preset-react-app` requires that you specify `NODE_ENV` or `BABEL_ENV` environment variables. Valid values are "development", "test", and "production". Instead, received: undefined.
    at Object.<anonymous> (C:\pp\habit\shared-habit\node_modules\babel-preset-react-app\index.js:51:9)
    at Module._compile (internal/modules/cjs/loader.js:702:30)    at Module._extensions..js (internal/modules/cjs/loader.js:713:10)
    at Object.require.extensions.(anonymous function) [as .js] (C:\pp\habit\web\node_modules\ts-node\src\index.ts:422:14)
    at Module.load (internal/modules/cjs/loader.js:612:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
    at Function.Module._load (internal/modules/cjs/loader.js:543:3)
    at Module.require (internal/modules/cjs/loader.js:650:17)
    at require (internal/modules/cjs/helpers.js:20:18)
PS C:\pp\habit\web> npm run dev
> web@ dev C:\pp\habit\web> nodemon server/index.ts
[nodemon] 1.17.5[nodemon] to restart at any time, enter `rs`[nodemon] watching: server/**/*.ts
[nodemon] starting `ts-node --compilerOptions {"""module""":"""commonjs"""} server/index.ts`> Using external babel configuration> Location: "C:\pp\habit\web\.babelrc"
[ { test: /\.(js|jsx)$/,    loader: 'hot-self-accept-loader',    include:
     [ 'C:\\pp\\habit\\web\\pages',
       'C:\\pp\\habit\\web\\node_modules\\next\\pages' ],
    options: { extensions: /\.(js|jsx)$/ } },
  { test: /\.(js|jsx)$/,
    include: [ 'C:\\pp\\habit\\web' ],
    exclude: /node_modules/,
    use: { loader: 'babel-loader', options: [Object] } },
  { test: /\.css$/,
    use: [ 'extracted-loader', [Object], [Object] ] },
  { test: /\.(ts|tsx)$/,
    loader: 'hot-self-accept-loader',
    include: [ 'C:\\pp\\habit\\web\\pages' ],
    options: { extensions: /\.(ts|tsx)$/ } },
  { test: /\.(ts|tsx)$/,
    include: [ 'C:\\pp\\habit\\web' ],
    exclude: /node_modules/,
    use: { loader: 'babel-loader', options: [Object] } },
  { test: /\.(ts|tsx)$/,
    include: [ 'C:\\pp\\habit\\shared-habit' ],
    use: { loader: 'babel-loader', options: [Object] } } ]
[ { test: /\.(js|jsx)$/,
    include: [ 'C:\\pp\\habit\\web' ],
    exclude: /node_modules/,
    use: { loader: 'babel-loader', options: [Object] } },
  { test: /\.css$/, use: [ [Object] ] },  { test: /\.(ts|tsx)$/,    include: [ 'C:\\pp\\habit\\web' ],
    exclude: /node_modules/,
    use: { loader: 'babel-loader', options: [Object] } },
  { test: /\.(ts|tsx)$/,
    include: [ 'C:\\pp\\habit\\shared-habit' ],
    use: { loader: 'babel-loader', options: [Object] } } ]
Starting type checking service...
Using 1 worker with 2048MB memory limit
ERROR in C:/pp/habit/web/components/AppShell/Header/index.tsx(2,17):
TS2307: Cannot find module './index.css'.
ERROR in C:/pp/habit/web/components/AppShell/index.tsx(4,22):
TS2307: Cannot find module 'react-native'.
ERROR in C:/pp/habit/web/components/AppShell/index.tsx(5,17):
TS2307: Cannot find module './index.css'.
ERROR in C:/pp/habit/web/components/AppShell/Sidebar/index.tsx(2,17):
TS2307: Cannot find module './index.css'.
ERROR in C:/pp/habit/web/components/AppShell/Sidebar/index.tsx(5,21):
TS2307: Cannot find module 'static/icons/browser.svg'.
ERROR in C:/pp/habit/web/pages/_app.tsx(1,17):
TS6133: 'Component' is declared but its value is never read.
ERROR in C:/pp/habit/web/pages/_app.tsx(7,43):
TS2339: Property 'props' does not exist on type 'MyApp'.
ERROR in C:/pp/habit/web/pages/_document.tsx(2,29):
TS2307: Cannot find module 'react-native'.
ERROR in C:/pp/habit/web/pages/_document.tsx(16,18):
TS2339: Property 'jsx' does not exist on type 'DetailedHTMLProps<StyleHTMLAttributes<HTMLStyleElement>, HTMLStyleElement>'.
ERROR in C:/pp/habit/web/pages/index.tsx(41,12):
TS2339: Property 'jsx' does not exist on type 'DetailedHTMLProps<StyleHTMLAttributes<HTMLStyleElement>, HTMLStyleElement>'.
Version: typescript 2.9.1
Time: 2046ms


 ERROR  Failed to compile with 2 errors            12:13:14 AM
 error  in ../shared-habit/src/lib/Sidebar/SidebarElement.tsx

Module build failed: Error: Using `babel-preset-react-app` requires that you specify `NODE_ENV` or `BABEL_ENV` environment variables. Valid values are "development", "test", and "production". Instead, received: undefined.
    at Object.<anonymous> (C:\pp\habit\shared-habit\node_modules\babel-preset-react-app\index.js:51:9)
    at Module._compile (internal/modules/cjs/loader.js:702:30)    at Module._extensions..js (internal/modules/cjs/loader.js:713:10)
    at Object.require.extensions.(anonymous function) [as .js] (C:\pp\habit\web\node_modules\ts-node\src\index.ts:422:14)
    at Module.load (internal/modules/cjs/loader.js:612:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
    at Function.Module._load (internal/modules/cjs/loader.js:543:3)
    at Module.require (internal/modules/cjs/loader.js:650:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at requireModule (C:\pp\habit\web\node_modules\next\node_modules\@babel\core\lib\config\files\plugins.js:142:12)
    at loadPreset (C:\pp\habit\web\node_modules\next\node_modules\@babel\core\lib\config\files\plugins.js:56:15)
    at createDescriptor (C:\pp\habit\web\node_modules\next\node_modules\@babel\core\lib\config\config-descriptors.js:152:21)    at C:\pp\habit\web\node_modules\next\node_modules\@babel\core\lib\config\config-descriptors.js:104:12
    at Array.map (<anonymous>)
    at createDescriptors (C:\pp\habit\web\node_modules\next\node_modules\@babel\core\lib\config\config-descriptors.js:103:27)
    at createPresetDescriptors (C:\pp\habit\web\node_modules\next\node_modules\@babel\core\lib\config\config-descriptors.js:95:10)

 @ ../shared-habit/src/lib/index.js 2:0-69
 @ ./components/AppShell/Sidebar/index.tsx
 @ ./components/AppShell/index.tsx
 @ ./pages/_app.tsx
 @ multi ./pages/_app.tsx

 error  in ../shared-habit/src/lib/Util/HoverableView.js

Module parse failed: Unexpected token (5:22)
You may need an appropriate loader to handle this file type.
|
| export default class HoverableView extends Component {
|   static defaultProps = {
|     hoverStyle: {},
|     onMouseEnterListener: () => {},

 @ ../shared-habit/src/lib/Util/index.js 1:0-58
 @ ../shared-habit/src/lib/index.js
 @ ./components/AppShell/Sidebar/index.tsx
 @ ./components/AppShell/index.tsx
 @ ./pages/_app.tsx
 @ multi ./pages/_app.tsx

(node:2732) DeprecationWarning: Module.chunks: Use Module.forEachChunk/mapChunks/getNumberOfChunks/isInChunk/addChunk/removeChunk instead
```
How can I make this work ?

**Comment by KeitIG** [comment]
Did you manage to find a solution? I have the exact same problem?

**Comment by AleksandarAleksandrov** [comment]
No I did not :(

**Comment by rheaditi** [comment]
Hey @AleksandarAleksandrov & @KeitIG:

I landed here through a google search combining `next.js` & `Property 'props' does not exist on type...`. 
I fixed my particular issue by installing `@types/next` as a dependency. Not sure if this will fix your issue but I hope this helps! 🙂

**Comment by KeitIG** [comment]
I created a repo to show how I did it (does not include server-side transpiration yet) https://github.com/KeitIG/monorepo-typescript-next-the-sane-way

Based on this:

https://github.com/KeitIG/next-plugin-transpile-modules

**Comment by AleksandarAleksandrov** [comment]
@KeitIG Awesome. I'll try it next week when I have the time.
