### ISSUE TITLE
Nextjs compilation fails when importing component with css file imported in it

### ISSUE THREAD

**Issue by codenakama** [zeit/next.js#4637]
I have built a component library and in one of them I am using `react-tippy` as a dependency which itself has a dependency in a css file to style the tooltip component. This works fine after multiple tests in the library docs and using create-react-app. However, when I upgraded the library in our main nextjs project and tried to run in development, it fails with errors below:

```
(function (exports, require, module, __filename, __dirname) { .tippy-touch{cursor:pointer!important}.tippy-notransition{transition:none!important}.tippy-popper{max-width:400px;-webkit-perspective:800px;perspective:800px;z-index:9999;outl
ine:0;transition-timing-function:cubic-bezier(.165,.84,.44,1);pointer-events:none}.tippy-popper.html-template{max-width:96%;max-width:calc(100% - 20px)}.tippy-popper[x-placement^=top] [x-arrow]{border-top:7px solid #333;border-right:7px
solid transparent;border-left:7px solid transparent;bottom:-7px;margin:0 9px}.tippy-popper[x-placement^=top] [x-arrow].arrow-small{border-top:5px solid #333;border-right:5px solid transparent;border-left:5px solid transparent;bottom:-5px
}.tippy-popper[x-placement^=top] [x-arrow].arrow-big{border-top:10px solid #333;border-right:10px solid transparent;border-left:10px solid transparent;bottom:-10px}.tippy-popper[x-placement^=top] [x-circle]{-

SyntaxError: Unexpected token .
    at new Script (vm.js:51:7)
    at createScript (vm.js:136:10)
    at Object.runInThisContext (vm.js:197:10)
    at Module._compile (internal/modules/cjs/loader.js:618:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:665:10)
    at Module.load (internal/modules/cjs/loader.js:566:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:506:12)
    at Function.Module._load (internal/modules/cjs/loader.js:498:3)
    at Module.require (internal/modules/cjs/loader.js:598:17)
    at require (internal/modules/cjs/helpers.js:11:18)
    at Object.<anonymous> (/Users/ricardo/Documents/Projects_COT/RetailReactApplication/node_modules/cot-experience/dist/components/TextInput/TextInput.js:28:1)
    at Module._compile (internal/modules/cjs/loader.js:654:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:665:10)
    at Module.load (internal/modules/cjs/loader.js:566:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:506:12)
    at Function.Module._load (internal/modules/cjs/loader.js:498:3)
```

What can I be doing wrong? I have already added next-css to the next.config.js which looks like this:

```
// next.config.js
const withCSS = require('@zeit/next-css');

const isProduction = process.env.NODE_ENV === 'production';

module.exports = withCSS({
  // We set the asset prefix in production to match the location
  // on the retail.capitalontap.com IIS Website static location
  assetPrefix: isProduction ? '/apps/apply' : '',

  distDir: 'build',
  webpack: config => config,
  webpackDevMiddleware: config => config,
  exportPathMap: () => ({
    '/': { page: '/' },
    '/login': { page: '/login' },
    '/applicationJourney': { page: '/applicationJourney' },
    '/error': { page: '/error' },
  }),
});
```

**Comment by teleginzhenya** [comment]
@codenakama 
Hello! I have checked this and it [works fine](https://i.imgur.com/LLAqhiJ.png). Make sure you did all steps.

1. Install packages
`yarn add react-tippy`
`npm install --save @zeit/next-css` or `yarn add @zeit/next-css`
2. Add [withCSS](https://github.com/zeit/next-plugins/tree/master/packages/next-css#with-css-modules) to your next.config.js.
3. Add CSS import `import "react-tippy/dist/tippy.css"` to appropriate file
4. Add package import `import { Tooltip } from "react-tippy"` to appropriate file
5. **[*]** Also don't forget to add `<link rel="stylesheet" href="/_next/static/style.css" />` to `_document.js`. (https://github.com/zeit/next-plugins/tree/master/packages/next-css#usage)

> The stylesheet is compiled to .next/static/style.css. You have to include it into the page using a custom _document.js. The file will be served from /_next/static/style.css

If you have any questions feel free to ask me
