### ISSUE TITLE
Using @babel/core and babel plugins

### ISSUE THREAD

**Issue by jerptrs** [zeit/next.js#4640]
# Bug report

When installing ``@babel/core`` and such plugins, for example ``@babel/preset-env`` the build will fail.

```npm install next react react-dom --save && npm install @babel/core --save-dev``

package.json start script
```
  "scripts": {
    "next:start": "next",
    "next:build": "next build"
  },
```
Steps to reproduce the behavior, please provide code snippets or a repository:
1. Create a basic index page 
```jsx
'use strict';
import React from 'react';

export default class extends React.Component {
  render() {
    return (
      <div>
        Hello World!
      </div>
    );
  }
}
```
2. Run the script ``npm run next:start``
3. See error
```
Error in ./pages/index.jsx

Module build failed: Error: [BABEL] C:\Users\jerom\Documents\Programming\WebstormProjects\web\pages\index.jsx: .value is not a valid Plugin property
    at Object.keys.forEach.key (C:\Users\jerom\Documents\Programming\WebstormProjects\web\node_modules\@babel\core\lib\config\validation\plugins.js:52:56)
    at Array.forEach (<anonymous>)
    at validatePluginObject (C:\Users\jerom\Documents\Programming\WebstormProjects\web\node_modules\@babel\core\lib\config\validation\plugins.js:50:20)
    at instantiatePlugin (C:\Users\jerom\Documents\Programming\WebstormProjects\web\node_modules\@babel\core\lib\config\full.js:201:55)
    at cachedFunction (C:\Users\jerom\Documents\Programming\WebstormProjects\web\node_modules\@babel\core\lib\config\caching.js:32:19)
    at loadPluginDescriptor (C:\Users\jerom\Documents\Programming\WebstormProjects\web\node_modules\@babel\core\lib\config\full.js:192:10)
    at config.plugins.map.descriptor (C:\Users\jerom\Documents\Programming\WebstormProjects\web\node_modules\@babel\core\lib\config\full.js:68:16)
    at Array.map (<anonymous>)
    at recurseDescriptors (C:\Users\jerom\Documents\Programming\WebstormProjects\web\node_modules\@babel\core\lib\config\full.js:67:38)
    at loadFullConfig (C:\Users\jerom\Documents\Programming\WebstormProjects\web\node_modules\@babel\core\lib\config\full.js:100:6)
    at process.nextTick (C:\Users\jerom\Documents\Programming\WebstormProjects\web\node_modules\@babel\core\lib\transform.js:28:33)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```
## Expected behavior
I expected that the build won't fail.

## System information
 - OS: Windows 10
 - Version of Next.js: 6.0.3

## Additional context

What I wanted to do was to use ``@babel/env`` so I can use ``office-ui-fabric-react`` [see issue here](https://github.com/OfficeDev/office-ui-fabric-react/issues/5236)

**Comment by timneutkens** [comment]
As per https://github.com/zeit/next.js#customizing-babel-config

@babel/preset-env is part of Next.js already. No need to install it. Same with @babel/core.

**Comment by jerptrs** [comment]
Shouldn't the ``babel/preset-env`` enable the es6 features which are not working (see the issue I mentioned)?

**Comment by timneutkens** [comment]
Yeah, we don't run babel on node_modules though.

**Comment by aguidis** [comment]
I just tried to create a simple page but the compilation failed: 

> Module build failed: Error: Cannot find module 'babel-preset-env' from '/Users/admin/Sites/test'
> - Did you mean "@babel/env"?
>     at Function.module.exports [as sync] (/Users/admin/Sites/test/node_modules/@babel/core/node_modules/resolve/lib/sync.js:43:15)

the dependencies look like:

```
"dependencies": {
        "@vx/axis": "^0.0.168",
        "@vx/event": "^0.0.165",
        "@vx/gradient": "^0.0.165",
        "@vx/grid": "^0.0.169",
        "@vx/group": "^0.0.165",
        "@vx/mock-data": "^0.0.165",
        "@vx/pattern": "^0.0.165",
        "@vx/responsive": "^0.0.165",
        "@vx/scale": "^0.0.165",
        "@vx/shape": "^0.0.168",
        "@vx/tooltip": "^0.0.165",
        "d3-array": "^1.2.1",
        "d3-format": "^1.3.0",
        "d3-time-format": "^2.1.1",
        "isomorphic-fetch": "^2.2.1",
        "next": "^6.1.1",
        "react": "^16.4.1",
        "react-dom": "^16.4.1"
    }
```

as @timneutkens said, @babel/preset-env is part of Next.js already so I'm a bit confused

**Comment by calbertts** [comment]
I'm having the same issue by using bpmn-io inside of a NextJS app, any update?

**Comment by balazsorban44** [comment]
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
