### ISSUE TITLE
`Error: Cannot find module 'next.config.js'`

### ISSUE THREAD

**Issue by rike422** [zeit/next.js#468]
When am trying to start custom server and `next.config.js` Its raise an error

```
[11:54:30] _(master)_ > next dev
// console.log(dir) inserted to https://github.com/zeit/next.js/blob/master/server/config.js#L19
dir = /Users/username/dev/js/test-next
// console.log(path) inserted to https://github.com/zeit/next.js/blob/master/server/config.js#L22
path = /Users/username/dev/js/test-next/next.config.js
```

```
[11:56:05] _(master)_ > node server.js
// console.log(dir) inserted to https://github.com/zeit/next.js/blob/master/server/config.js#L19
dir = .
// console.log(path) inserted to https://github.com/zeit/next.js/blob/master/server/config.js#L22
path = next.config.js
module.js:442
    throw err;
    ^
Error: Cannot find module 'next.config.js'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at loadConfig (/Users/akiratakahashi/dev/js/test-next/node_modules/next/dist/server/config.js:45:28)
    at getConfig (/Users/akiratakahashi/dev/js/test-next/node_modules/next/dist/server/config.js:32:20)
    at new Server (/Users/akiratakahashi/dev/js/test-next/node_modules/next/dist/server/index.js:86:40)
    at module.exports (/Users/akiratakahashi/dev/js/test-next/node_modules/next/dist/server/next.js:10:10)
    at Object.<anonymous> (/Users/akiratakahashi/dev/js/test-next/server.js:4:13)
    at Module._compile (module.js:541:32)
```

server.js
```js
const express = require('express')
const next = require('next')
const accepts = require('accepts')
const app = next({ dev: true })
const handle = app.getRequestHandler()

app.prepare()
  .then(() => {
    const server = express()

    server.use((req, res, next) => {
      const accept = accepts(req)
      const type = accept.type(['json', 'html'])
      if (type === 'json') {
        return handle(req, res)
      }
      next()
    })

    server.get('/a', (req, res) => {
      return app.render(req, res, '/b', req.query)
    })

    server.get('*', (req, res) => {
      return handle(req, res)
    })

    server.listen(3000)
  })
```

**Comment by rike422** [comment]
Resolved.
After changing as below, no error occurred.

`const app = next({ dev: true })` and 
 to 
`const app = next({ dev: true, dir: process.cwd() })`
