### ISSUE TITLE
import plugin have error:window is not defined 

### ISSUE THREAD

**Issue by MyGithub-Ljc** [zeit/next.js#4683]
when i import plugin in my next project 
code : import "videojs-resolution-switcher/lib/videojs-resolution-switcher" 
report error : window is not defined. 
how to use it ? 

window is not defined
ReferenceError: window is not defined
    at r (D:\project\team\管理平台\node_modules\react-draggable-tags\lib\bundle.js:20:35413)
    at a (D:\project\team\管理平台\node_modules\react-draggable-tags\lib\bundle.js:20:35501)
    at t.exports (D:\project\team\管理平台\node_modules\react-draggable-tags\lib\bundle.js:20:38921)
    at Object.<anonymous> (D:\project\team\管理平台\node_modules\react-draggable-tags\lib\bundle.js:20:41034)
    at n (D:\project\team\管理平台\node_modules\react-draggable-tags\lib\bundle.js:1:186)
    at Object.module.exports.t.exports.e (D:\project\team\管理平台\node_modules\react-draggable-tags\lib\bundle.js:20:28649)
    at n (D:\project\team\管理平台\node_modules\react-draggable-tags\lib\bundle.js:1:186)
    at module.exports.r (D:\project\team\管理平台\node_modules\react-draggable-tags\lib\bundle.js:1:600)
    at Object.<anonymous> (D:\project\team\管理平台\node_modules\react-draggable-tags\lib\bundle.js:1:610)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)

**Comment by timneutkens** [comment]
It's a client only module. You can't use it while server-side rendering. `window` is not available in Node.js. Try doing a dynamic import inside componentDidMount.
