### ISSUE TITLE
 DOMException: Failed to execute 'querySelector' on 'Document': '

### ISSUE THREAD

**Issue by canotech** [zeit/next.js#4757]
Hi, I have a next.js´s issue, when I deployed my site with npm run build and npm run start into a server, he throw  the next error:

`main.js:1 DOMException: Failed to execute 'querySelector' on 'Document': '0R53QmEJkS' is not a valid selector.
    at I (https://b2cpqa.dentegra.technogi.com.mx/_next/64be391f-e695-423a-b1cf-2bbdea4e4c8b/main.js:1:13155)
    at t.e (https://b2cpqa.dentegra.technogi.com.mx/_next/64be391f-e695-423a-b1cf-2bbdea4e4c8b/main.js:1:71533)
    at ll (https://b2cpqa.dentegra.technogi.com.mx/_next/64be391f-e695-423a-b1cf-2bbdea4e4c8b/main.js:1:732866)
    at ul (https://b2cpqa.dentegra.technogi.com.mx/_next/64be391f-e695-423a-b1cf-2bbdea4e4c8b/main.js:1:729383)
    at al (https://b2cpqa.dentegra.technogi.com.mx/_next/64be391f-e695-423a-b1cf-2bbdea4e4c8b/main.js:1:728864)
    at rl (https://b2cpqa.dentegra.technogi.com.mx/_next/64be391f-e695-423a-b1cf-2bbdea4e4c8b/main.js:1:728690)
    at Xu (https://b2cpqa.dentegra.technogi.com.mx/_next/64be391f-e695-423a-b1cf-2bbdea4e4c8b/main.js:1:728058)
    at Tu (https://b2cpqa.dentegra.technogi.com.mx/_next/64be391f-e695-423a-b1cf-2bbdea4e4c8b/main.js:1:727287)
    at Object.enqueueSetState (https://b2cpqa.dentegra.technogi.com.mx/_next/64be391f-e695-423a-b1cf-2bbdea4e4c8b/main.js:1:702376)
    at n.O.setState (https://b2cpqa.dentegra.technogi.com.mx/_next/64be391f-e695-423a-b1cf-2bbdea4e4c8b/main.js:1:4597)`

But the selector change when I am reload the site.
I am using : 

`"dependencies": {
    "@zeit/next-sass": "0.1.2",
    "axios": "0.18.0",
    "bootstrap": "4.1.0",
    "classnames": "2.2.5",
    "dotenv": "5.0.1",
    "file-loader": "1.1.11",
    "lodash": "^4.17.5",
    "next": "^5.1.0",
    "node-sass": "^4.9.2",
    "react": "^16.3.1",
    "react-dom": "^16.3.1",
    "react-gcaptcha": "^4.2.1",
    "react-icons": "^2.2.7",
    "react-redux": "^5.0.7",
    "react-spinners": "^0.3.2",
    "react-tooltip": "^3.5.0",
    "react-transition-group": "2.3.0",
    "reactstrap": "5.0.0",
    "redux": "^3.7.2",
    "redux-form": "^7.3.0",
    "redux-multi": "^0.1.12",
    "redux-promise": "^0.5.3",
    "shortid": "^2.2.8",
    "url-loader": "1.0.1"
  },

  "devDependencies": {
    "babel-eslint": "^8.2.3",
    "babel-preset-es2015": "^6.24.1",
    "babel-preset-react": "^6.24.1",
    "babel-preset-stage-2": "^6.24.1",
    "eslint": "^4.19.1",
    "eslint-config-airbnb-base": "^12.1.0",
    "eslint-plugin-import": "^2.12.0",
    "eslint-plugin-jsx-a11y": "^6.0.3",
    "eslint-plugin-react": "^7.7.0",
    "eslint-watch": "^3.1.4"
  }`

Do you have anything idea of what is happen?

**Comment by timneutkens** [comment]
Please provide a reproducible example in a GitHub repository. Maybe you're using a dependency that is using `document` or `window` directly, which is not available when server side rendering.
