### ISSUE TITLE
Next.js + material-ui example not working

### ISSUE THREAD

**Issue by ryannealmes** [zeit/next.js#4781]
# Bug report

Next.js + material-ui [example](https://github.com/mui-org/material-ui/tree/master/examples/nextjs) not working

## Describe the bug

When running material-ui with nextjs I get an error on their [example](https://github.com/mui-org/material-ui/tree/master/examples/nextjs) repo.

```
╭─ryanme@GS-M135 ~/sandbox/material-ui/examples/nextjs  ‹master›
╰─$ npm run dev                                                                                                                                                                                         1 ↵

> nextjs@1.0.0 dev /Users/ryanme/sandbox/material-ui/examples/nextjs
> next

internal/modules/cjs/loader.js:550
    throw err;
    ^

Error: Cannot find module 'webpack'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:548:15)
    at Function.Module._load (internal/modules/cjs/loader.js:475:25)
    at Module.require (internal/modules/cjs/loader.js:598:17)
    at require (internal/modules/cjs/helpers.js:11:18)
    at Object.<anonymous> (/Users/ryanme/sandbox/material-ui/next.config.js:1:79)
    at Module._compile (internal/modules/cjs/loader.js:654:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:665:10)
    at Module.load (internal/modules/cjs/loader.js:566:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:506:12)
    at Function.Module._load (internal/modules/cjs/loader.js:498:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! nextjs@1.0.0 dev: `next`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the nextjs@1.0.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/ryanme/.npm/_logs/2018-07-13T18_10_34_539Z-debug.log
```
## To Reproduce

Clone the [repo](https://github.com/mui-org/material-ui/tree/master/examples/nextjs), 
navigate to the example for nextjs
`npm install`, 
`npm run`

## Expected behavior
I expect the server to start running and to be able to see an example of nextjs working with material-ui.

## System information
```
node v9.11.1
npm v6.0.1
 "@material-ui/core": "latest",
    "jss": "latest",
    "next": "latest",
    "prop-types": "latest",
    "react": "latest",
    "react-dom": "latest",
    "react-jss": "latest"
```
## Additional context

There are multiple issues logged in the material-ui repo about this, but they all get closed and the solution is - the problem is on the nextjs side. They need to fix it.

https://github.com/mui-org/material-ui/issues/10439

**Comment by timneutkens** [comment]
Seems like following these steps works fine: https://github.com/mui-org/material-ui/tree/master/examples/nextjs#how-to-use

**Comment by lorensr** [comment]
@ryannealmes did you ever solve? I'm seeing the same issue.

Also, matching issues:

https://github.com/mui-org/material-ui/issues/10439
https://github.com/mui-org/material-ui/issues/11309

**Comment by pvtri96** [comment]
Hi @lorens 
This issue has already solved, I think it was a problem from nextjs side and they fixed it.

**Comment by lorensr** [comment]
I'm using the master version of `material-ui/examples/nextjs`, which uses next `latest`, and I get the same error.

**Comment by ryannealmes** [comment]
I never fixed this :/

**Comment by thundermiracle** [comment]
I faced the same problem.
The solution is simple: adding a next.config.js file to the example folder.
Like the newest [example](https://github.com/mui-org/material-ui/blob/master/examples/nextjs/next.config.js) did.

**Comment by ziedHamdi** [comment]
I'm having the same issue even though I added next.config.js: he styles are displayed correctly until the document loads, then styles disappear

**Comment by Yorkshireman** [comment]
> I faced the same problem.
> The solution is simple: adding a next.config.js file to the example folder.
> Like the newest [example](https://github.com/mui-org/material-ui/blob/master/examples/nextjs/next.config.js) did.
> 
> As next.js is trying to find the nearest next.config.js, so if you didn't add a blank one to the folder, nextjs will use material-ui/next.config.js instead and cause the error.

I have two pages: `pages/signin.js` and `pages/signup.js`. Adding this (almost) blank `next.config.js` file to the root folder fixed the problem for `/signin` but not `/signup`. Any ideas?

**Comment by balazsorban44** [comment]
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
