### ISSUE TITLE
DOMException: Failed to execute 'insertRule' on 'CSSStyleSheet' 

### ISSUE THREAD

**Issue by Vista1nik** [zeit/next.js#4803]
# Bug report
DOMException: Failed to execute 'insertRule' on 'CSSStyleSheet'
## Describe the bug
"An unexpected error has occurred." when using back button or <Link> redirect
In Chrome Dev. console:
```
DOMException: Failed to execute 'insertRule' on 'CSSStyleSheet': Failed to insert the rule.
    at e (http://www.cathub.cc/_next/static/commons/main-5cf3dee45abaed02cb2f.js:1:207014)
    at e (http://www.cathub.cc/_next/static/commons/main-5cf3dee45abaed02cb2f.js:1:207282)
    at http://www.cathub.cc/_next/static/commons/main-5cf3dee45abaed02cb2f.js:1:202047
    at Array.forEach (<anonymous>)
    at e (http://www.cathub.cc/_next/static/commons/main-5cf3dee45abaed02cb2f.js:1:202011)
    at t.e (http://www.cathub.cc/_next/static/commons/main-5cf3dee45abaed02cb2f.js:1:197028)
    at Ka (http://www.cathub.cc/_next/static/commons/main-5cf3dee45abaed02cb2f.js:1:94758)
    at Ya (http://www.cathub.cc/_next/static/commons/main-5cf3dee45abaed02cb2f.js:1:96319)
    at ru (http://www.cathub.cc/_next/static/commons/main-5cf3dee45abaed02cb2f.js:1:105606)
    at nu (http://www.cathub.cc/_next/static/commons/main-5cf3dee45abaed02cb2f.js:1:103500)
Va @ main-5cf3dee45abaed02cb2f.js:1
main-5cf3dee45abaed02cb2f.js:1 Failed to execute 'insertRule' on 'CSSStyleSheet': Failed to insert the rule.
Error: Failed to execute 'insertRule' on 'CSSStyleSheet': Failed to insert the rule.
    at e (http://www.cathub.cc/_next/static/commons/main-5cf3dee45abaed02cb2f.js:1:207014)
    at e (http://www.cathub.cc/_next/static/commons/main-5cf3dee45abaed02cb2f.js:1:207282)
    at http://www.cathub.cc/_next/static/commons/main-5cf3dee45abaed02cb2f.js:1:202047
    at Array.forEach (<anonymous>)
    at e (http://www.cathub.cc/_next/static/commons/main-5cf3dee45abaed02cb2f.js:1:202011)
    at t.e (http://www.cathub.cc/_next/static/commons/main-5cf3dee45abaed02cb2f.js:1:197028)
    at Ka (http://www.cathub.cc/_next/static/commons/main-5cf3dee45abaed02cb2f.js:1:94758)
    at Ya (http://www.cathub.cc/_next/static/commons/main-5cf3dee45abaed02cb2f.js:1:96319)
    at ru (http://www.cathub.cc/_next/static/commons/main-5cf3dee45abaed02cb2f.js:1:105606)
    at nu (http://www.cathub.cc/_next/static/commons/main-5cf3dee45abaed02cb2f.js:1:103500)


    in t
    in div
    in Unknown
    in withRouter(Unknown)
    in t
    in App
```

Site using `Isomorphic-unfetch`

This bug occurs **only in Production Build.**

## To Reproduce

Sorry. Can't provide steps to Reproduce.

Example code of the page:
https://gist.github.com/Vista1nik/dbef2a66deefffc2bfcd10f9cbab27ef#file-somepage-js

## Expected behavior
Redirect to another page.

## Screenshots
![](https://i.imgur.com/e8nzGYH.png)
## System information
 - OS: Windows 10
 - Browser (if applies) Chrome, Edge
 - Version of Next.js: 6.0.3

## Additional context

Page where bug occurs:
http://www.cathub.cc/video?videoid=5b49e3d176020dcd0080f7a9
(on russian language)

Click on Logo or Back button.

Sometimes this bug appears and disappears

Sometimes `next build` Fixes this bug in some places.

Duplicate because I can not access Spectrum Chat.

**Comment by timneutkens** [comment]
```
<style jsx global>{`
         /* Some CSS Here */  
    `}
        </style>
```

I guess it's this.

**Comment by heshamelmasry77** [comment]
@timneutkens   actually this is my problem cause for now. I have a head component  like this and i am using the style jsx global in it to make it as a global between my pages.

but its cause this error. please write a proper solution for the error.



```
import React from 'react';
import NextHead from 'next/head';
import { string } from 'prop-types';

const defaultDescription = '';
const defaultOGURL = '';
const defaultOGImage = '';

const SEOHead = props => (
  <div>
    <NextHead>
      <meta charSet="UTF-8" />
      <title>{props.title || ''}</title>
      <meta
        name="description"
        content={props.description || defaultDescription}
      />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" sizes="192x192" href="/static/touch-icon.png" />
      <link rel="apple-touch-icon" href="/static/touch-icon.png" />
      <link rel="mask-icon" href="/static/favicon-mask.svg" color="#49B882" />
      <link rel="icon" href="/static/favicon.ico" />
      <meta property="og:url" content={props.url || defaultOGURL} />
      <meta property="og:title" content={props.title || ''} />
      <meta
        property="og:description"
        content={props.description || defaultDescription}
      />
      <meta name="twitter:site" content={props.url || defaultOGURL} />
      <meta name="twitter:card" content="summary_large_image" />
      <meta name="twitter:image" content={props.ogImage || defaultOGImage} />
      <meta property="og:image" content={props.ogImage || defaultOGImage} />
      <meta property="og:image:width" content="1200" />
      <meta property="og:image:height" content="630" />
    </NextHead>
    <style jsx global>{`
      @import url('https://fonts.googleapis.com/css?family=Josefin+Sans:400,600,700|Roboto:300,400,500,700,900');
      @import url('https://fonts.googleapis.com/css?family=Dancing+Script:400,700');
body {
  margin: 0;
  padding: 0;
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', 'Roboto', 'Oxygen', 'Ubuntu', 'Cantarell', 'Fira Sans', 'Droid Sans', 'Helvetica Neue', sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}
code {
  font-family: source-code-pro, Menlo, Monaco, Consolas, 'Courier New', monospace;
}
/* CSS Normalize */
article, aside, details, figcaption, figure, footer, header, hgroup, nav, section, summary {
  display: block;
}
audio, canvas, video {
  display: inline-block;
}
audio:not([controls]) {
  display: none;
  height: 0;
}
[hidden] {
  display: none;
}
html {
  font-family: sans-serif;
  -webkit-text-size-adjust: 100%;
  -ms-text-size-adjust: 100%;
}
a:focus {
  outline: 0;
}
a:active, a:hover {
  outline: 0;
}
h1 {
  font-size: 2em;
}
abbr[title] {
  border-bottom: 1px dotted;
}
b, strong {
  font-weight: 700;
}
dfn {
  font-style: italic;
}
mark {
  background: #ff0;
  color: #000;
}
code, kbd, pre, samp {
  font-family: monospace, serif;
  font-size: 1em;
}
pre {
  white-space: pre-wrap;
  word-wrap: break-word;
}
q {
  quotes: \\201c \\201d \\2018 \\2019;
}
small {
  font-size: 80%;
}
sub, sup {
  font-size: 75%;
  line-height: 0;
  position: relative;
  vertical-align: baseline;
}
sup {
  top: -0.5em;
}
sub {
  bottom: -0.25em;
}
img {
  border: 0;
}
svg:not(:root) {
  overflow: hidden;
}
fieldset {
  border: 1px solid silver;
  margin: 0 2px;
  padding: 0.35em 0.625em 0.75em;
}
button, input, select, textarea {
  font-family: inherit;
  font-size: 100%;
  margin: 0;
}
button, input {
  line-height: normal;
}
button, html input[type=button], input[type=reset], input[type=submit] {
  /* 1 */
  -webkit-appearance: button;
  cursor: pointer;
}
button[disabled], input[disabled] {
  cursor: default;
}
input[type='checkbox'], input[type='radio'] {
  box-sizing: border-box;
  padding: 0;
}
input[type='search'] {
  -webkit-appearance: textfield;
  -moz-box-sizing: content-box;
  -webkit-box-sizing: content-box;
  box-sizing: content-box;
}
input[type='search']::-webkit-search-cancel-button, input[type='search']::-webkit-search-decoration {
  -webkit-appearance: none;
}
textarea {
  overflow: auto;
  vertical-align: top;
}
table {
  border-collapse: collapse;
  border-spacing: 0;
}
body, figure {
  margin: 0;
}
legend, button::-moz-focus-inner, input::-moz-focus-inner {
  border: 0;
  padding: 0;
}
* {
  -moz-box-sizing: border-box;
  -webkit-box-sizing: border-box;
  box-sizing: border-box;
}

      body {
        margin: 0;
        padding: 0;
        font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', 'Roboto',
          'Oxygen', 'Ubuntu', 'Cantarell', 'Fira Sans', 'Droid Sans',
          'Helvetica Neue', sans-serif;
        -webkit-font-smoothing: antialiased;
        -moz-osx-font-smoothing: grayscale;
        font-family: 'Roboto', sans-serif;
        font-size: 16px;
      }
      body .SingleDatePicker_picker__portal {
        z-index: 9999;
      }
      body button {
        display: inline-block;
        color: #000;
        margin: 0 5px 0 5px;
        font-weight: 500;
        font-size: 16px;
        text-shadow: none;
        box-shadow: none;
        background: white none;
        -webkit-tap-highlight-color: transparent;
        -moz-tap-highlight-color: transparent;
        -o-tap-highlight-color: transparent;
        tap-highlight-color: transparent;
      }
      body button:focus {
        outline: none;
      }
      body label {
        font-weight: 400;
      }
      body input[type='number'] {
        border: 0;
        outline: 0;
        background: transparent;
        border-bottom: 2px solid #389835;
        width: 111px;
        text-align: center;
      }
      body input[type='number']::-webkit-inner-spin-button,
      body input[type='number']::-webkit-outer-spin-button {
        -webkit-appearance: none;
        -moz-appearance: none;
        appearance: none;
        margin: 0;
      }
      body input[type='tel'] {
        border: 0;
        outline: 0;
        background: transparent;
        border-bottom: 2px solid #389835;
        width: 111px;
        text-align: left;
      }
      body input[type='tel']::-webkit-inner-spin-button,
      body input[type='tel']::-webkit-outer-spin-button {
        -webkit-appearance: none;
        -moz-appearance: none;
        appearance: none;
        margin: 0;
      }
      body input[type='text'] {
        text-align: left;
      }
      body .styled-checkbox {
        position: absolute;
        opacity: 0;
        display: none;
      }
      body .styled-checkbox + label {
        position: relative;
        cursor: pointer;
        padding: 0;
        color: #1d1d1d;
      }
      body .styled-checkbox + label span {
        position: relative;
        top: 2px;
      }
      body .styled-checkbox + label:before {
        content: '';
        margin-right: 10px;
        display: inline-block;
        vertical-align: text-top;
        width: 20px;
        height: 20px;
        background: #403f3f;
        border-radius: 2px;
        border: 2px solid #1d1d1d;
      }
      body .styled-checkbox:hover + label:before {
        border: 2px solid #389835;
      }
      body .styled-checkbox:focus + label:before {
        box-shadow: 0 0 0 3px rgba(0, 0, 0, 0.12);
      }
      body .styled-checkbox:checked + label:before {
        background: #389835;
        border: 2px solid #389835;
      }
      body .styled-checkbox:disabled + label {
        color: #b8b8b8;
        cursor: auto;
      }
      body .styled-checkbox:disabled + label:before {
        box-shadow: none;
        background: #d5d5d5;
      }
      body .styled-checkbox:checked + label:after {
        content: '';
        position: absolute;
        left: 7px;
        top: 11px;
        background: #403f3f;
        width: 2px;
        height: 2px;
        box-shadow: 2px 0 0 #403f3f, 4px 0 0 #403f3f, 4px -2px 0 #403f3f,
          4px -4px 0 #403f3f, 4px -6px 0 #403f3f, 4px -8px 0 #403f3f;
        transform: rotate(45deg);
      }
      body .styled-checkbox:checked + label > span {
        color: #d5d5d5;
      }
      body span.range-icon {
        color: #1d1d1d;
        font-size: 1.7em;
        margin-left: 5px;
        margin-right: 5px;
      }
      body span.check-box {
        margin-right: 10px;
      }
      body .input-range__label--value {
        position: absolute;
        top: -33px;
        right: -19px;
        width: 25px;
        height: 25px;
      }
      body .input-range__label--value:before {
        content: '';
        -webkit-transform: perspective(40px) rotateX(20deg) rotateZ(-45deg);
        transform: perspective(40px) rotateX(20deg) rotateZ(-45deg);
        -webkit-transform-origin: 50% 50%;
        -ms-transform-origin: 50% 50%;
        transform-origin: 50% 50%;
        border-radius: 50% 50% 50% 0;
        padding: 0 3px 3px 0;
        width: 18px;
        height: 18px;
        background: #389835;
        position: absolute;
        left: 12.7px;
        top: 23px;
        margin: -2.2em 0 0 -1.3em;
        -webkit-box-shadow: -1px 1px 4px rgba(0, 0, 0, 0.5);
        box-shadow: -1px 1px 4px rgba(0, 0, 0, 0.5);
      }
      body .input-range__label--value .input-range__label-container {
        font-size: 1em;
        bottom: 14px;
        font-weight: 400;
        color: #fff;
        top: 0;
        left: -6px;
        z-index: 3;
      }
      body .input-range__slider:before {
        content: '';
        width: 23px;
        height: 30px;
        position: absolute;
        left: 10.7px;
        top: 1px;
        background: transparent;
        margin: -2.2em 0 0 -1.3em;
      }
      body .input-range__track--active {
        background: #389835;
      }
      body .input-range__slider {
        background: #389835;
        border: 1px solid #46bd43;
      }
      body .input-range__label--max > span,
      body .input-range__label--min > span {
        font-size: 1em;
      }
      body .rad {
        cursor: pointer;
        user-select: none;
        -webkit-user-select: none;
        -webkit-touch-callout: none;
        display: flex;
        flex-direction: column;
        align-items: center;
      }
      body .rad > input {
        visibility: hidden;
        position: absolute;
      }
      body .rad > svg {
        font-size: 2em;
        color: #403f3f;
      }
      body .rad > span {
        color: #403f3f;
      }
      body .rad:hover > svg {
        color: #403f3f;
      }
      @media (max-width: 768px) {
        body .rad:hover > svg {
          color: #403f3f;
        }
      }
      body .rad:hover > span {
        color: #d5d5d5;
      }
      body .rad > input:checked + svg {
        color: #ed8f1f;
      }
      body .rad > input:checked + svg + span {
        color: #d5d5d5;
      }
    `}</style>
  </div>
);

SEOHead.propTypes = {
  title: string,
  description: string,
  url: string,
  ogImage: string
};

export default SEOHead;

```
