### ISSUE TITLE
How to set token as cookie on express server.js and use it all the next pages and components?

### ISSUE THREAD

**Issue by nagibmahfuj** [zeit/next.js#4807]
Hi, I have a api getting JWT tokens which I want to call on express end and store token as cookie. This cookie I want to use in next pages as well.

Here is my implementation:
**server.js**

```
const express = require('express');
const next = require('next');
const cookieParser = require('cookie-parser');
const axios = require('axios')
const routes = require('./routes')
const variables = require('./common/variables')
const app = next({
	dev: process.env.NODE_ENV !== 'production'
})
const handler = routes.getRequestHandler(app)
app.prepare().then(() => {
	const server = express();
	// need cookieParser middleware before we can do anything with cookies
	server.use(cookieParser());

	server.use(function (req, res, next) {
		var cookie = req.cookies.token;
		if (typeof cookie == 'undefined') {
			axios.post(variables.apiUrls.getToken, {}, {
					headers: {
						'Content-Type': 'application/json'
					}
				}).then( (response) => {
					//console.log(response.data);
					res.cookie('token', response.data.token, { maxAge: 900000, httpOnly: true});
					console.log('cookie created successfully', response.token);
				})
				.catch((error) => {
					console.log(error);
				});
		} else {
			// yes, cookie was already present 
			console.log('cookie exists', cookie);
		}
		next()
	})
	server.use(handler).listen(3000)
})
```

But I am getting this error:
```
Error: Can't set headers after they are sent.
    at validateHeader (http_outgoing.js:491:11)
    at ServerResponse.setHeader (http_outgoing.js:498:3)
    at ServerResponse.header (xxx\node_modules\express\lib\response.js:767:10)
    at ServerResponse.append (xxx\node_modules\express\lib\response.js:728:15)
    at ServerResponse.res.cookie (xxx\node_modules\express\lib\response.js:853:8)
    at axios.post.then (xxx\server.js:47:10)
    at <anonymous>
    at process.tickCallback (internal/process/next_tick.js:1
88:7)
```
Need help!

**Comment by timneutkens** [comment]
It's kind of strange to open an issue when the issue template says to ask questions on https://spectrum.chat/next-js, which you did, and then create an issue here if there's no response within 1 minute 🤔 

Closing as per the issue template.

https://spectrum.chat/?t=4ae62646-529c-4046-a58b-b99d3b0d7cb4
