### ISSUE TITLE
[v2] next init doesn't include _error so next start breaks

### ISSUE THREAD

**Issue by matthewmueller** [zeit/next.js#491]
To repro:

```sh
next init
next start
open http://localhost:3000
```

I'm getting: `Error: Cannot find module /.../.next/dist/pages/_error`

**Comment by matthewmueller** [comment]
doh, it's just `next`.

**Comment by milkyway8** [comment]
Same issue here. Could you be more specific about how do you resolve it.
` npm run dev

> ecommerce-app-in-react@1.0.0 dev C:\Users\Usuario\desktop\frontend_2k17\proyectosBootcamp\aini-s    oul
> next

 DONE  Compiled successfully in 6967ms17:42:40

> Ready on http://localhost:3000
{ Error: Cannot find module C:\Users\Usuario\desktop\frontend_2k17\proyectosBootcamp\aini-soul\.ne    xt\dist\pages\_error
    at _callee$ (C:\Users\Usuario\Desktop\frontend_2k17\proyectosBootcamp\aini-soul\node_modules\n    ext\dist\server\resolve.js:220:19)
    at tryCatch (C:\Users\Usuario\Desktop\frontend_2k17\proyectosBootcamp\aini-soul\node_modules\n    ext\node_modules\regenerator-runtime\runtime.js:65:40)
    at Generator.invoke [as _invoke] (C:\Users\Usuario\Desktop\frontend_2k17\proyectosBootcamp\ain    i-soul\node_modules\next\node_modules\regenerator-runtime\runtime.js:303:22)
    at Generator.prototype.(anonymous function) [as next] (C:\Users\Usuario\Desktop\frontend_2k17\    proyectosBootcamp\aini-soul\node_modules\next\node_modules\regenerator-runtime\runtime.js:117:21)
    at step (C:\Users\Usuario\Desktop\frontend_2k17\proyectosBootcamp\aini-soul\node_modules\next\    node_modules\babel-runtime\helpers\asyncToGenerator.js:17:30)
    at C:\Users\Usuario\Desktop\frontend_2k17\proyectosBootcamp\aini-soul\node_modules\next\node_m    odules\babel-runtime\helpers\asyncToGenerator.js:28:13
    at <anonymous> code: 'ENOENT' }
{ Error: Cannot find module C:\Users\Usuario\desktop\frontend_2k17\proyectosBootcamp\aini-soul\.ne    xt\dist\pages\_error
    at _callee$ (C:\Users\Usuario\Desktop\frontend_2k17\proyectosBootcamp\aini-soul\node_modules\n    ext\dist\server\resolve.js:220:19)
    at tryCatch (C:\Users\Usuario\Desktop\frontend_2k17\proyectosBootcamp\aini-soul\node_modules\n    ext\node_modules\regenerator-runtime\runtime.js:65:40)
    at Generator.invoke [as _invoke] (C:\Users\Usuario\Desktop\frontend_2k17\proyectosBootcamp\ain    i-soul\node_modules\next\node_modules\regenerator-runtime\runtime.js:303:22)
    at Generator.prototype.(anonymous function) [as next] (C:\Users\Usuario\Desktop\frontend_2k17\    proyectosBootcamp\aini-soul\node_modules\next\node_modules\regenerator-runtime\runtime.js:117:21)
    at step (C:\Users\Usuario\Desktop\frontend_2k17\proyectosBootcamp\aini-soul\node_modules\next\    node_modules\babel-runtime\helpers\asyncToGenerator.js:17:30)
    at C:\Users\Usuario\Desktop\frontend_2k17\proyectosBootcamp\aini-soul\node_modules\next\node_m    odules\babel-runtime\helpers\asyncToGenerator.js:28:13
    at <anonymous> code: 'ENOENT' }
{ Error: Cannot find module C:\Users\Usuario\desktop\frontend_2k17\proyectosBootcamp\aini-soul\.ne    xt\dist\pages\_document
    at _callee$ (C:\Users\Usuario\Desktop\frontend_2k17\proyectosBootcamp\aini-soul\node_modules\n    ext\dist\server\resolve.js:220:19)
    at tryCatch (C:\Users\Usuario\Desktop\frontend_2k17\proyectosBootcamp\aini-soul\node_modules\n    ext\node_modules\regenerator-runtime\runtime.js:65:40)
    at Generator.invoke [as _invoke] (C:\Users\Usuario\Desktop\frontend_2k17\proyectosBootcamp\ain    i-soul\node_modules\next\node_modules\regenerator-runtime\runtime.js:303:22)
    at Generator.prototype.(anonymous function) [as next] (C:\Users\Usuario\Desktop\frontend_2k17\    proyectosBootcamp\aini-soul\node_modules\next\node_modules\regenerator-runtime\runtime.js:117:21)
    at step (C:\Users\Usuario\Desktop\frontend_2k17\proyectosBootcamp\aini-soul\node_modules\next\    node_modules\babel-runtime\helpers\asyncToGenerator.js:17:30)
    at C:\Users\Usuario\Desktop\frontend_2k17\proyectosBootcamp\aini-soul\node_modules\next\node_m    odules\babel-runtime\helpers\asyncToGenerator.js:28:13
    at <anonymous> code: 'ENOENT' }
{ Error: Cannot find module C:\Users\Usuario\desktop\frontend_2k17\proyectosBootcamp\aini-soul\.ne    xt\dist\pages\_error
    at _callee$ (C:\Users\Usuario\Desktop\frontend_2k17\proyectosBootcamp\aini-soul\node_modules\n    ext\dist\server\resolve.js:220:19)
    at tryCatch (C:\Users\Usuario\Desktop\frontend_2k17\proyectosBootcamp\aini-soul\node_modules\n    ext\node_modules\regenerator-runtime\runtime.js:65:40)
    at Generator.invoke [as _invoke] (C:\Users\Usuario\Desktop\frontend_2k17\proyectosBootcamp\ain    i-soul\node_modules\next\node_modules\regenerator-runtime\runtime.js:303:22)
    at Generator.prototype.(anonymous function) [as next] (C:\Users\Usuario\Desktop\frontend_2k17\    proyectosBootcamp\aini-soul\node_modules\next\node_modules\regenerator-runtime\runtime.js:117:21)
    at step (C:\Users\Usuario\Desktop\frontend_2k17\proyectosBootcamp\aini-soul\node_modules\next\    node_modules\babel-runtime\helpers\asyncToGenerator.js:17:30)
    at C:\Users\Usuario\Desktop\frontend_2k17\proyectosBootcamp\aini-soul\node_modules\next\node_m    odules\babel-runtime\helpers\asyncToGenerator.js:28:13
    at <anonymous> code: 'ENOENT' }
`

**Comment by wuzhuzhu** [comment]
same issue here.

**Comment by timneutkens** [comment]
This issue is 1,5 year old. Try upgrading to next@canary. The issue on topic is something completely different than the 2 comments. Going to lock the conversation.
