### ISSUE TITLE
with-apollo example failed to compile

### ISSUE THREAD

**Issue by gatezh** [zeit/next.js#4966]
# Examples bug report

## Example name
with-apollo

## Describe the bug
After repository is cloned and example dependencies installed running `yarn dev` returns an error.

## To Reproduce
Steps to reproduce the behavior, please provide code snippets or a repository:
1. Clone the repo
2. Go to `examples/with-apollo`
3. Install dependencies `yarn`
4. Start the example `yarn dev`

## Expected behavior
Project should compile and be accessible on http://localhost:3000

## System information
 - OS: macOS High Sierra 10.13.6
 - Browser chrome 68.0.3440.106
 - Version of Next.js: 6.1.1

## Error message 

```bash
yarn run v1.9.4
$ next

 ERROR  Failed to compile with 1 errors                                                                           10:07:48 AM
 error  in ./pages/_app.js
Module build failed: Error: Cannot find module './dist/build/babel/preset'    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/sergii/Code/GitHub/next.js/babel.js:1:80)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at requireModule (/Users/sergii/Code/GitHub/next.js/examples/with-apollo/node_modules/@babel/core/lib/config/files/plugins.js:142:12)
    at loadPreset (/Users/sergii/Code/GitHub/next.js/examples/with-apollo/node_modules/@babel/core/lib/config/files/plugins.js:56:15)
    at createDescriptor (/Users/sergii/Code/GitHub/next.js/examples/with-apollo/node_modules/@babel/core/lib/config/config-descriptors.js:152:21)
    at /Users/sergii/Code/GitHub/next.js/examples/with-apollo/node_modules/@babel/core/lib/config/config-descriptors.js:104:12

 @ multi ./pages/_app.js

(node:5618) DeprecationWarning: Module.chunks: Use Module.forEachChunk/mapChunks/getNumberOfChunks/isInChunk/addChunk/removeChunk instead
> Ready on http://localhost:3000
```

**Comment by timneutkens** [comment]
If you clone the repo you have to manually build Next.js. Instead use the download zip / create-next-app way of installing.
