### ISSUE TITLE
I'm following the Getting Started guide, and it doesn't work.

### ISSUE THREAD

**Issue by trusktr** [zeit/next.js#5023]
On this page:

![screen shot 2018-08-23 at 7 15 04 pm](https://user-images.githubusercontent.com/297678/44561276-df232700-a708-11e8-9e89-90ddf6b34c2c.png)

I pasted the code, then refreshed `localhost:3000` and I see this:

![screen shot 2018-08-23 at 7 15 37 pm](https://user-images.githubusercontent.com/297678/44561294-ee09d980-a708-11e8-9f1c-29cbea64caaa.png)

Here's the actual text:

```
Error in ./pages/index.js
Module build failed: Error: Plugin/Preset files are not allowed to export objects, only functions. In /Users/trusktr/src/Signafy+mapper-public-website/node_modules/babel-preset-stage-2/lib/index.js
    at createDescriptor (/Users/trusktr/src/Signafy+mapper-public-website/node_modules/@babel/core/lib/config/config-descriptors.js:179:11)
    at /Users/trusktr/src/Signafy+mapper-public-website/node_modules/@babel/core/lib/config/config-descriptors.js:104:12
    at Array.map (<anonymous>)
    at createDescriptors (/Users/trusktr/src/Signafy+mapper-public-website/node_modules/@babel/core/lib/config/config-descriptors.js:103:27)
    at createPresetDescriptors (/Users/trusktr/src/Signafy+mapper-public-website/node_modules/@babel/core/lib/config/config-descriptors.js:95:10)
    at /Users/trusktr/src/Signafy+mapper-public-website/node_modules/@babel/core/lib/config/config-descriptors.js:67:19
    at presets (/Users/trusktr/src/Signafy+mapper-public-website/node_modules/@babel/core/lib/config/config-descriptors.js:57:25)
    at mergeChainOpts (/Users/trusktr/src/Signafy+mapper-public-website/node_modules/@babel/core/lib/config/config-chain.js:298:68)
    at /Users/trusktr/src/Signafy+mapper-public-website/node_modules/@babel/core/lib/config/config-chain.js:251:7
    at buildRootChain (/Users/trusktr/src/Signafy+mapper-public-website/node_modules/@babel/core/lib/config/config-chain.js:85:20)
    at loadPrivatePartialConfig (/Users/trusktr/src/Signafy+mapper-public-website/node_modules/@babel/core/lib/config/partial.js:41:53)
    at Object.loadPartialConfig (/Users/trusktr/src/Signafy+mapper-public-website/node_modules/@babel/core/lib/config/partial.js:66:16)
    at Object.<anonymous> (/Users/trusktr/src/Signafy+mapper-public-website/node_modules/next/node_modules/babel-loader/lib/index.js:82:26)
    at Generator.next (<anonymous>)
    at step (/Users/trusktr/src/Signafy+mapper-public-website/node_modules/next/node_modules/babel-loader/lib/index.js:3:221)
    at _next (/Users/trusktr/src/Signafy+mapper-public-website/node_modules/next/node_modules/babel-loader/lib/index.js:3:409)
```

**Comment by trusktr** [comment]
In the previous step, the 404 worked fine. In this step, I created the `pages/index.js` file with the **_exact_** content (copied/pasted) and it led to this error.

I just installed `next`, `react` and `react-dom` today, based on the tutorial.

```
    "next": "^6.1.1",
    "react": "^16.4.2",
    "react-dom": "^16.4.2",
```

**Comment by trusktr** [comment]
Alright, I removed everything in my repo, and started over, but no luck.

I made an empty `package.json`,

```js
{
  "name": "test",
  "version": "1.0.0",
  "scripts": {
    "start": "next"
  },
  "dependencies": {
  },
  "devDependencies": {
  }
}
```

then I ran `npm install react react-dom next` which changed package.json to

```js
{
  "name": "mapper-public-website",
  "version": "1.0.0",
  "description": "Mapper's public-facing website at mapper.ai",
  "author": "Mapper.ai",
  "private": true,
  "scripts": {
    "start": "next"
  },
  "dependencies": {
    "next": "^6.1.1",
    "react": "^16.4.2",
    "react-dom": "^16.4.2"
  },
  "devDependencies": {}
}
```

Then in `pages/index.js` I have

```js
const Index = () => (
  <div>
    <p>Hello Next.js</p>
  </div>
)

export default Index
```

Then I ran `npm start` and I see this:

![screen shot 2018-08-23 at 9 54 26 pm](https://user-images.githubusercontent.com/297678/44565834-21576300-a71f-11e8-802e-449e71128a5f.png)

I can't get it to work following the simple steps in the Getting Started guide.

**Comment by trusktr** [comment]
Okay, I moved to a new folder, and started even fresher, not git, no anything, no package.json, and I did

```sh
npm install react react-dom next
mkdir pages
touch pages/index.js
# paste example code
./node_modules/.bin/next
```

and it worked.

Does Next.js cache some things? I don't understand why it's not working in my other repo even though I removed node_modules, deleted everything in package.json, reinstalled, and basically did the same thing and get the above error.

**Comment by trusktr** [comment]
Okay, something is seriously messed up.

I literally deleted **everything** in my repo, except for package.json. And removed all dependencies from package.json. Literally.

Then I ran `npm install react react-dom next`, made the `pages/index.hjs` file, and started `next`.

I get literally the same error.

**Comment by trusktr** [comment]
Alright,  took it a step further: I deleted `~/.npm/` and still no luck. I wonder why it works in another folder, but not in my repo.

**Comment by trusktr** [comment]
Oops, I forgot to delete `.babelrc`. That was it.

**Comment by ajsharp** [comment]
I'm having a similar issue. I think the `Error: "Plugin/Preset files are not allowed to export objects, only functions"` is related to the babel 7 upgrade, and specifically something with babel-react-optimize. See here: https://github.com/babel/babel/issues/6808

**Comment by ajsharp** [comment]
The thing that was causing this issue for me was loading a file from another project that was using babel 6.
