### ISSUE TITLE
string template holders in styled jsx not defined in mocha enzyme test after upgrading to nextjs6/babel 7

### ISSUE THREAD

**Issue by Filipvdb321** [zeit/next.js#5078]
# Bug report

## Describe the bug
When I moved to nextjs 6 it moved to babel 7. Although my app is running without problems some of my tests are suddenly failing.

It seems that the template placeholders are causing issues in my tests:
```
import React from 'react';
import { darkGray, grey } from '../styles/colors';

const HelloComponent = () => (
  <div className='hello'>
    <p>Hello World</p>
    <style jsx>{`
      .hello {
        font: 15px Helvetica, Arial, sans-serif;
        background: ${grey};
        padding: 100px;
        text-align: center;
        transition: 100ms ease-in background;
      }
      .hello:hover {
        background: ${darkGray};
      }
    `}</style>
  </div>
);

export default HelloComponent;

```
When I run this test:
```
import React from 'react';
import { expect } from 'chai';
import { shallow } from 'enzyme';
import HelloComponent from './HelloComponent';

describe('<HelloComponent />', () => {
  let wrapper;

  beforeEach(() => {
    wrapper =
      shallow(<HelloComponent />);
  });

  it('has a hello text ', () => {
    expect(wrapper.find('p').text()).to.eql('Hello World');
  });
});
```
It gives this stacktrace:
```
<HelloComponent />
       "before each" hook for "has a hello text ":
     ReferenceError: grey is not defined
      at HelloComponent (components/HelloComponent.js:10:23)
      at Object.type (node_modules/enzyme-adapter-react-16/build/ReactSixteenAdapter.js:388:38)
      at ReactShallowRenderer.render (node_modules/react-test-renderer/cjs/react-test-renderer-shallow.development.js:145:34)
      at /.../enzyme-adapter-react-16/build/ReactSixteenAdapter.js:392:37
      at withSetStateAllowed (node_modules/enzyme-adapter-utils/build/Utils.js:125:16)
      at Object.render (node_modules/enzyme-adapter-react-16/build/ReactSixteenAdapter.js:391:70)
      at new ShallowWrapper (node_modules/enzyme/build/ShallowWrapper.js:119:22)
      at shallow (node_modules/enzyme/build/shallow.js:19:10)
      at Context.<anonymous> (components/HelloComponent.spec.js:11:7)
```
I have a setup-tests.js in which I configure babel like this:
```
require('@babel/register')({
  presets: ['@babel/preset-env', [
    'next/babel',
    {
      'styled-jsx': { optimizeForSpeed: true }
    }
  ], '@babel/preset-stage-0'],
  babelrc: false,
});
```
## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:
1. clone: https://github.com/Filipvdb321/next-basic-css
2. yarn install , yarn test
3. you will see the test failing (if you run the app you see that the styles work)

## Expected behavior
Test to work after upgrade.

**Comment by timneutkens** [comment]
You shouldn't add `'@babel/preset-env'`, instead use:

```
require('@babel/register')({
  presets: [[
    'next/babel',
    {
      'preset-env': {modules: 'commonjs'},
      'styled-jsx': { optimizeForSpeed: true }
    }
  ], '@babel/preset-stage-0'],
  babelrc: false,
});
```

This is probably the reason it broke, as you're first compiling away `import/export` before next/babel is applied. 

Note that the `'preset-env': {modules: 'commonjs'},` is no longer needed when #5081 lands.

**Comment by Filipvdb321** [comment]
Hi Tim, thanks for your help.
I applied the change but still have exactly the same problem: https://github.com/Filipvdb321/next-basic-css/blob/master/__tests__/setup-tests.js

any more ideas?

**Comment by Filipvdb321** [comment]
@timneutkens you had a chance to look at this? You can reproduce the problem with the repository I sent.
