### ISSUE TITLE
scss file problem

### ISSUE THREAD

**Issue by ruoru** [zeit/next.js#5087]
# Question about Next.js

Questions should be posted on https://spectrum.chat/next-js

index.js

```
import './index.scss'
import {} from 'antd';
import Layout from './components/MyLayout.js'
import Link from 'next/link'
import fetch from 'isomorphic-unfetch'
import Markdown from 'react-markdown'

const Index = (props) => {
  return (
    <Layout>
      <h1>Batman TV Shows</h1>
      <Markdown source={`
          This is our blog post.
          Yes. We can have a [link](/link).
          And we can have a title as well.

          ### This is a title

          And here's the content.
        `} />
      <ul>
        {props.shows.map(({ show }) => (
          <li key={show.id}>
            <Link as={`/p/${show.id}`} href={`/post?id=${show.id}`}>
              <a>{show.name}</a>
            </Link>
          </li>
        ))}
      </ul>
    </Layout>
  );
}

Index.getInitialProps = async function () {
  const res = await fetch('https://api.tvmaze.com/search/shows?q=batman')
  const data = await res.json()

  console.log(`Show data fetched. Count: ${data.length}`)

  return {
    shows: data
  }
}

export default Index
```

next.config.js
```
const withSass = require('@zeit/next-sass')
module.exports = withSass();

module.exports = {
  distDir: 'dist',
  exportPathMap: function () {
    return {
      '/': { page: '/' },
      '/about': { page: '/about' },
      '/p/hello-nextjs': { page: '/post', query: { title: "Hello Next.js" } },
      '/p/learn-nextjs': { page: '/post', query: { title: "Learn Next.js is awesome" } },
      '/p/deploy-nextjs': { page: '/post', query: { title: "Deploy apps with Zeit" } }
    }
  }
}
```

error
```
> Failed to build
{ Error: (client) ./pages/index.scss
Module parse failed: Unexpected token (1:6)
You may need an appropriate loader to handle this file type.
| h1, a {
|   font-family: "Arial";
| }
 @ ./pages/index.js 6:0-22
```

**Comment by ruoru** [comment]
anyone help me?

**Comment by Marvin1003** [comment]
module.exports behaves as your default export. In your case the second module.export replaces the first. 
Try this instead:
```
const withSass = require('@zeit/next-sass')

module.exports = withSass({
  distDir: 'dist',
  exportPathMap: function () {
    return {
      '/': { page: '/' },
      '/about': { page: '/about' },
      '/p/hello-nextjs': { page: '/post', query: { title: "Hello Next.js" } },
      '/p/learn-nextjs': { page: '/post', query: { title: "Learn Next.js is awesome" } },
      '/p/deploy-nextjs': { page: '/post', query: { title: "Deploy apps with Zeit" } }
    }
  }
})
```

**Comment by ruoru** [comment]
@Marvin1003 i am try it and throw this error.

```
 ERROR  Failed to compile with 1 errors                                                      10:06:20

This dependency was not found:

* index.scss in ./pages/index.js

To install it, you can run: npm install --save index.scss
ModuleNotFoundError: Module not found: Error: Can't resolve 'index.scss' in '/Users/ruoru/Repositories/nextjs-demo/pages'
    at factoryCallback (/Users/ruoru/Repositories/nextjs-demo/node_modules/webpack/lib/Compilation.js:276:40)
    at factory (/Users/ruoru/Repositories/nextjs-demo/node_modules/webpack/lib/NormalModuleFactory.js:235:20)
    at resolver (/Users/ruoru/Repositories/nextjs-demo/node_modules/webpack/lib/NormalModuleFactory.js:60:20)
    at asyncLib.parallel (/Users/ruoru/Repositories/nextjs-demo/node_modules/webpack/lib/NormalModuleFactory.js:127:20)
```
