### ISSUE TITLE
 Cannot find module 'babel-preset-es2015'

### ISSUE THREAD

**Issue by kishoreramkumar** [zeit/next.js#5096]
# Error

Error in ./pages/index.js
Module build failed: Error: Cannot find module 'babel-preset-es2015' from '/home/innoventes'
    at Function.module.exports [as sync] (/home/innoventes/kishore/ssr/innoventes-website/node_modules/resolve/lib/sync.js:40:15)
    at resolveStandardizedName (/home/innoventes/kishore/ssr/innoventes-website/node_modules/@babel/core/lib/config/files/plugins.js:78:29)
    at resolvePreset (/home/innoventes/kishore/ssr/innoventes-website/node_modules/@babel/core/lib/config/files/plugins.js:31:10)
    at loadPreset (/home/innoventes/kishore/ssr/innoventes-website/node_modules/@babel/core/lib/config/files/plugins.js:50:18)
    at createDescriptor (/home/innoventes/kishore/ssr/innoventes-website/node_modules/@babel/core/lib/config/config-descriptors.js:152:21)
    at /home/innoventes/kishore/ssr/innoventes-website/node_modules/@babel/core/lib/config/config-descriptors.js:104:12
    at Array.map (<anonymous>)
    at createDescriptors (/home/innoventes/kishore/ssr/innoventes-website/node_modules/@babel/core/lib/config/config-descriptors.js:103:27)
    at createPresetDescriptors (/home/innoventes/kishore/ssr/innoventes-website/node_modules/@babel/core/lib/config/config-descriptors.js:95:10)
    at /home/innoventes/kishore/ssr/innoventes-website/node_modules/@babel/core/lib/config/config-descriptors.js:67:19
    at presets (/home/innoventes/kishore/ssr/innoventes-website/node_modules/@babel/core/lib/config/config-descriptors.js:57:25)
    at mergeChainOpts (/home/innoventes/kishore/ssr/innoventes-website/node_modules/@babel/core/lib/config/config-chain.js:298:68)
    at /home/innoventes/kishore/ssr/innoventes-website/node_modules/@babel/core/lib/config/config-chain.js:251:7
    at buildRootChain (/home/innoventes/kishore/ssr/innoventes-website/node_modules/@babel/core/lib/config/config-chain.js:85:20)
    at loadPrivatePartialConfig (/home/innoventes/kishore/ssr/innoventes-website/node_modules/@babel/core/lib/config/partial.js:41:53)
    at Object.loadPartialConfig (/home/innoventes/kishore/ssr/innoventes-website/node_modules/@babel/core/lib/config/partial.js:66:16)

**Comment by popugune** [comment]
presets depricated

**Comment by kishoreramkumar** [comment]
can u explain me what to do?
@popugune

**Comment by popugune** [comment]
@kishoreramkumar use @babel/preset-env

**Comment by kishoreramkumar** [comment]
resolved issue added .babelrc in root directory
`{
    "presets": [
      ["next/babel", {
        "preset-env": {},
        "transform-runtime": {},
        "styled-jsx": {},
        "class-properties": {}
      }]
    ],
    "plugins": []
  }`

it will configure the babel

**Comment by timneutkens** [comment]
Just a note for anyone that comes here, please read this full section: https://github.com/zeit/next.js#customizing-babel-config

You should never manually add `@babel/preset-env`.

**Comment by puneetdevs** [comment]
[](url)

> 

- [``](url)

**Comment by balazsorban44** [comment]
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
