### ISSUE TITLE
withSass not working with nextjs 7

### ISSUE THREAD

**Issue by seb-saletes** [zeit/next.js#5097]
Hi,

I updated to V7 mainly because of this issue: https://github.com/zeit/next.js/issues/4182#issuecomment-418113176. 

Unfortunately I got an error trying to build using a custom next.config.js using withSass.

Looks like extract-text-webpack-plugin is not compatible with webpack 4
https://github.com/webpack-contrib/extract-text-webpack-plugin/issues/701

Any hot tips to make v7 works with Sass ?

```
Error: Chunk.entrypoints: Use Chunks.groupsIterable and filter by instanceof Entrypoint instead
    at Chunk.get (/Users/seb/Work/All-Square/react-app/node_modules/webpack/lib/Chunk.js:824:9)
    at /Users/seb/Work/All-Square/react-app/node_modules/extract-text-webpack-plugin/dist/index.js:176:48
    at Array.forEach (<anonymous>)
    at /Users/seb/Work/All-Square/react-app/node_modules/extract-text-webpack-plugin/dist/index.js:171:18
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/seb/Work/All-Square/react-app/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:12:1)
    at AsyncSeriesHook.lazyCompileHook [as _callAsync] (/Users/seb/Work/All-Square/react-app/node_modules/tapable/lib/Hook.js:35:21)
    at Compilation.seal (/Users/seb/Work/All-Square/react-app/node_modules/webpack/lib/Compilation.js:1213:27)
    at hooks.make.callAsync.err (/Users/seb/Work/All-Square/react-app/node_modules/webpack/lib/Compiler.js:547:17)
    at _done (eval at create (/Users/seb/Work/All-Square/react-app/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:9:1)
    at _err0 (eval at create (/Users/seb/Work/All-Square/react-app/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:20:22)
    at Promise.all.then (/Users/seb/Work/All-Square/react-app/node_modules/webpack/lib/DynamicEntryPlugin.js:73:20)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by seb-saletes** [comment]
My bad forgot to check if withSass canary package exists before posting. Don't have any error using @zeit/next-sass 0.2.1-canary.2

**Comment by timneutkens** [comment]
👍 going to close this

**Comment by skout90** [comment]
@zeit/next-css is the same.
 Don't have any error using `"@zeit/next-css": "^0.2.1-canary.2"`
