### ISSUE TITLE
Use of a decorator on MyDocument (extends Document) causes an error 

### ISSUE THREAD

**Issue by trusktr** [zeit/next.js#5109]
# Bug report

## Describe the bug

Now that I got decorators enabled, I put one of the root `Document` element, and it resulted in

```
TypeError: Cannot read property 'page' of undefined
    at Head.render (/Users/trusktr/src/Signafy+mapper-public-website/node_modules/next/dist/server/document.js:167:32)
    at processChild (/Users/trusktr/src/Signafy+mapper-public-website/node_modules/react-dom/cjs/react-dom-server.node.development.js:2207:18)
    at resolve (/Users/trusktr/src/Signafy+mapper-public-website/node_modules/react-dom/cjs/react-dom-server.node.development.js:2064:5)
    at ReactDOMServerRenderer.render (/Users/trusktr/src/Signafy+mapper-public-website/node_modules/react-dom/cjs/react-dom-server.node.development.js:2383:22)
    at ReactDOMServerRenderer.read (/Users/trusktr/src/Signafy+mapper-public-website/node_modules/react-dom/cjs/react-dom-server.node.development.js:2357:19)
    at renderToStaticMarkup (/Users/trusktr/src/Signafy+mapper-public-website/node_modules/react-dom/cjs/react-dom-server.node.development.js:2740:25)
    at _callee3$ (/Users/trusktr/src/Signafy+mapper-public-website/node_modules/next/dist/server/render.js:338:100)
    at tryCatch (/Users/trusktr/src/Signafy+mapper-public-website/node_modules/regenerator-runtime/runtime.js:62:40)
    at Generator.invoke [as _invoke] (/Users/trusktr/src/Signafy+mapper-public-website/node_modules/regenerator-runtime/runtime.js:296:22)
    at Generator.prototype.(anonymous function) [as next] (/Users/trusktr/src/Signafy+mapper-public-website/node_modules/regenerator-runtime/runtime.js:114:21)
    at step (/Users/trusktr/src/Signafy+mapper-public-website/node_modules/@babel/runtime/helpers/asyncToGenerator.js:12:30)
    at _next (/Users/trusktr/src/Signafy+mapper-public-website/node_modules/@babel/runtime/helpers/asyncToGenerator.js:27:9)
```

## To Reproduce

^

## Expected behavior

Ability to use decorators on Document, where the decorator is a higher-order component that wraps my Document-extending class,

```js
@someDecorator
export default
class MyDocument extends Document { ... }
```

 - Version of Next.js: 6.1.1

**Comment by trusktr** [comment]
In particular, this is what I did to cause the error:

```js
const provideJss = (Doc: typeof Document) => (
  class extends Component {
    sheets = new SheetsRegistry
    render() {
      return (
        <JssProvider registry={this.sheets}>
          <Doc />
        </JssProvider>
      )
    }
  }
)

@provideJss
export default
class MyDoc extends Document { ... }
```

If I comment out the `@provideJss` line, the error is gone.

**Comment by trusktr** [comment]
Basically what I'm trying to do is

```js
@provideJss
@withStyle(style())
export default
class MyDocument extends Document { ... }
```

where `style()` returns a JSS style object, so that I can use JSS on the Document component to define global styles there, so that global styles are colocated with the document element (the colocation is what I'm aiming for).

I thought about just putting the styles on the `_app` component, but it doesn't seem colocating there is the best fit, but it'll work.

**Comment by timneutkens** [comment]
`_document.js` should only be used to change the initial HTML structure and implement css-in-js solutions.

The reason that wrapping breaks everything is that `<Doc />` doesn't get `<Doc {...this.props} />` passed in. Another reason is that you're not propagating `getInitialProps`, you could use `hoist-non-react-statics` for this.

But for what you're doing using _app.js is better.
