### ISSUE TITLE
TypeError: Cannot read property 'res' of undefined 

### ISSUE THREAD

**Issue by rafael096** [zeit/next.js#5151]
# Bug report
TypeError: Cannot read property 'res' of undefined
    at Function.getInitialProps (.../node_modules/next/dist/lib/error.js:63:22)
    at Function.getInitialProps (.../.next/server/bundles/pages/_app.js:321:33)
    at Function._callee$ (.../node_modules/next-redux-wrapper/lib/index.js:195:46)
    at tryCatch (.../node_modules/regenerator-runtime/runtime.js:62:40)
    at Generator.invoke [as _invoke] (.../node_modules/regenerator-runtime/runtime.js:296:22)
    at Generator.prototype.(anonymous function) [as next] (.../node_modules/regenerator-runtime/runtime.js:114:21)
    at step (.../node_modules/next-redux-wrapper/lib/index.js:18:221)
    at _next (.../node_modules/next-redux-wrapper/lib/index.js:18:409)
    at .../node_modules/next-redux-wrapper/lib/index.js:18:477
    at new Promise (.../node_modules/core-js/modules/es6.promise.js:177:7)

hello i'm new in react and ssr and i have this error app is working but is very annoying..I don' t know why and how i can solve it..plz help me..

this is my server.js

const express = require('express');
const next = require('next');
require('dotenv').config();
const port = parseInt(process.env.PORT, 10);
const dev = process.env.NODE_ENV !== 'production';
const app = next({ dev });
const handle = app.getRequestHandler();

app.prepare()
    .then(() => {
        const server = express();
        server.get('/', (req, res) => {
            return app.render(req, res, '/')
        });
        server.get('*', (req, res) => {
            return handle(req, res)
        });
        server.listen(port, (err) => {
            if (err) throw err
            console.log(`> port:${process.env.PORT}`)
        })
    });

**Comment by timneutkens** [comment]
The file you've posted looks correct 🤔 Could you create a minimal github repository and post back here?
