### ISSUE TITLE
[2.0 beta2] watch-pages-plugin is failing

### ISSUE THREAD

**Issue by tleunen** [zeit/next.js#517]
Using the latest 2.0.0 beta 2, I sometimes have this error popping in the console:

```
/node_modules/next/dist/server/build/plugins/watch-pages-plugin.js:54
        (0, _keys2.default)(compiler.fileTimestamps).filter(isPageFile).filter(function (f) {
                                                                        ^
TypeError: Cannot read property 'indexOf' of null
    at /node_modules/next/dist/server/build/plugins/watch-pages-plugin.js:55:44
    at Array.filter (native)
    at Compiler.<anonymous> (/node_modules/next/dist/server/build/plugins/watch-pages-plugin.js:54:73)
    at Compiler.applyPluginsAsync (/node_modules/tapable/lib/Tapable.js:71:13)
    at Watching._go (/node_modules/webpack/lib/Compiler.js:44:16)
    at Watching.invalidate (/node_modules/webpack/lib/Compiler.js:108:8)
    at Watching.<anonymous> (/node_modules/webpack/lib/Compiler.js:93:8)
    at /node_modules/next/dist/server/build/plugins/watch-remove-event-plugin.js:45:22
    at NodeWatchFileSystem.<anonymous> (/node_modules/webpack/lib/node/NodeWatchFileSystem.js:43:3)
    at Watchpack.g (events.js:292:16)
```

**Comment by nkzawa** [comment]
Maybe https://github.com/zeit/next.js/pull/523 will fix the error.
Let us know if you get how to reproduce the problem.
