### ISSUE TITLE
Error: Chunk.entrypoints: Use Chunks.groupsIterable and filter by instanceof Entrypoint instead

### ISSUE THREAD

**Issue by MarcosRenato266** [zeit/next.js#5207]
# Bug report
DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead
Error: Chunk.entrypoints: Use Chunks.groupsIterable and filter by instanceof Entrypoint instead
    at Chunk.get (C:\D.vida Projects\fiduc-dashboard\node_modules\webpack\lib\Chunk.js:824:9)
    at C:\D.vida Projects\fiduc-dashboard\node_modules\extract-text-webpack-plugin\dist\index.js:176:48
    at Array.forEach (<anonymous>)
    at C:\D.vida Projects\fiduc-dashboard\node_modules\extract-text-webpack-plugin\dist\index.js:171:18
    at AsyncSeriesHook.eval [as callAsync] (eval at create (C:\D.vida Projects\fiduc-dashboard\node_modules\tapable\lib\HookCodeFactory.js:32:10), <anonymous>:12:1)
    at AsyncSeriesHook.lazyCompileHook (C:\D.vida Projects\fiduc-dashboard\node_modules\tapable\lib\Hook.js:154:20)
    at Compilation.seal (C:\D.vida Projects\fiduc-dashboard\node_modules\webpack\lib\Compilation.js:1214:27)
    at hooks.make.callAsync.err (C:\D.vida Projects\fiduc-dashboard\node_modules\webpack\lib\Compiler.js:547:17)
    at _done (eval at create (C:\D.vida Projects\fiduc-dashboard\node_modules\tapable\lib\HookCodeFactory.js:32:10), <anonymous>:9:1)
    at _err2 (eval at create (C:\D.vida Projects\fiduc-dashboard\node_modules\tapable\lib\HookCodeFactory.js:32:10), <anonymous>:50:22)
    at Promise.all.then (C:\D.vida Projects\fiduc-dashboard\node_modules\webpack\lib\DynamicEntryPlugin.js:73:20)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
Error: Chunk.entrypoints: Use Chunks.groupsIterable and filter by instanceof Entrypoint instead
    at Chunk.get (C:\D.vida Projects\fiduc-dashboard\node_modules\webpack\lib\Chunk.js:824:9)
    at C:\D.vida Projects\fiduc-dashboard\node_modules\extract-text-webpack-plugin\dist\index.js:176:48
    at Array.forEach (<anonymous>)
    at C:\D.vida Projects\fiduc-dashboard\node_modules\extract-text-webpack-plugin\dist\index.js:171:18
    at AsyncSeriesHook.eval [as callAsync] (eval at create (C:\D.vida Projects\fiduc-dashboard\node_modules\tapable\lib\HookCodeFactory.js:32:10), <anonymous>:12:1)
    at AsyncSeriesHook.lazyCompileHook (C:\D.vida Projects\fiduc-dashboard\node_modules\tapable\lib\Hook.js:154:20)
    at Compilation.seal (C:\D.vida Projects\fiduc-dashboard\node_modules\webpack\lib\Compilation.js:1214:27)
    at hooks.make.callAsync.err (C:\D.vida Projects\fiduc-dashboard\node_modules\webpack\lib\Compiler.js:547:17)
    at _done (eval at create (C:\D.vida Projects\fiduc-dashboard\node_modules\tapable\lib\HookCodeFactory.js:32:10), <anonymous>:9:1)
    at _err2 (eval at create (C:\D.vida Projects\fiduc-dashboard\node_modules\tapable\lib\HookCodeFactory.js:32:10), <anonymous>:50:22)
    at Promise.all.then (C:\D.vida Projects\fiduc-dashboard\node_modules\webpack\lib\DynamicEntryPlugin.js:73:20)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

## Describe the bug
After update next to 7 I got this erro when running *(yarn dev)

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:
Run yarn dev with "next": "7"

## Package
{
  "name": "fiduc-dashboard",
  "version": "0.0.1",
  "repository": "https://github.com/d-vida/fiduc-dashboard",
  "author": "d.vida",
  "private": true,
  "scripts": {
    "dev": "next",
    "build": "next build",
    "start": "next start"
  },
  "dependencies": {
    "@zeit/next-css": "^0.1.4",
    "antd": "^3.3.1",
    "apollo-client": "^2.3.8",
    "apollo-client-preset": "^1.0.8",
    "apollo-link": "^1.2.2",
    "apollo-link-context": "^1.0.8",
    "apollo-link-http": "^1.5.4",
    "apollo-link-ws": "^1.0.8",
    "axios": "^0.18.0",
    "babel-plugin-import": "^1.1.1",
    "chart.js": "^2.7.2",
    "dotenv": "^6.0.0",
    "graphql": "^0.13.2",
    "graphql-tag": "^2.9.2",
    "isomorphic-unfetch": "^2.1.1",
    "js-cookie": "^2.2.0",
    "mini-css-extract-plugin": "^0.4.3",
    "next": "7",
    "prop-types": "^15.6.2",
    "react": "^16.2.0",
    "react-apollo": "^2.1.11",
    "react-chartjs-2": "^2.7.4",
    "react-dom": "^16.2.0",
    "subscriptions-transport-ws": "^0.9.14"
  },
  "devDependencies": {
    "babel-eslint": "^8.2.6",
    "babel-plugin-transform-decorators-legacy": "^1.3.4",
    "eslint": "^5.3.0",
    "eslint-plugin-react": "^7.10.0"
  }
}

**Comment by timneutkens** [comment]
Upgrade `@zeit/next-css`
