### ISSUE TITLE
Example "with-next-sass" fails due to wrong dependency

### ISSUE THREAD

**Issue by needcaffeine** [zeit/next.js#5217]
# Examples bug report

## Example name
with-next-sass

## Describe the bug
`next` fails horribly on _development_.

## To Reproduce
Steps to reproduce the behavior, please provide code snippets or a repository:
1. `yarn install`
2. `yarn dev`
3. See error

## Console output
```
$ next
/Users/vic/Workspace/needcaffeine/next.js/examples/with-next-sass/node_modules/mini-css-extract-plugin/dist/index.js:21
} = _webpack2.default;
    ^
TypeError: Cannot destructure property `createHash` of 'undefined' or 'null'.
    at Object.<anonymous> (/Users/vic/Workspace/needcaffeine/next.js/examples/with-next-sass/node_modules/mini-css-extract-plugin/dist/index.js:21:5)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/vic/Workspace/needcaffeine/next.js/examples/with-next-sass/node_modules/mini-css-extract-plugin/dist/cjs.js:3:18)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
error Command failed with exit code 1.
```

**Comment by JiiB** [comment]
Hey @needcaffeine I had a similar issue two days ago. In the meantime they released a new version for the `@zeit/next-sass` package. Be sure to upgrade to the latest version.

Here is my `package.json`:
```json
{
  "scripts": {
    "dev": "next",
    "build": "next build",
    "start": "next start"
  },
  "dependencies": {
    "@zeit/next-sass": "^1.0.1",
    "next": "^7.0.0",
    "node-sass": "4.9.3",
    "react": "^16.5.2",
    "react-dom": "^16.5.2"
  }
}
```

**Comment by timneutkens** [comment]
Yep should be fixed in latest version of next-css/sass/etc
