### ISSUE TITLE
Not working with next 6 & next 7...

### ISSUE THREAD

**Issue by CYB3RL1F3** [zeit/next.js#5225]
# Bug report
Impossible to load style from node_module react-slick.

## Describe the bug

Receive this message : 
```
Module build failed (from app/node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleParseError: Module parse failed: Unexpected character '' (1:0)
You may need an appropriate loader to handle this file type.
(Source code omitted for this binary file)
```

## To Reproduce
apply next.config.js like following : 

```
module.exports = withCss(withTypescript({
    distDir: '../dist',
}));
```

Also tried : 

```
const wcss = withCss({
    server: true
});

module.exports = withTypescript({
    distDir: '../dist',
    ...wcss
});
```

I tried options like modules, etc...
The CSS file is loaded from a node_module.
Important : we are in a lerna context. The component using the css is in UI and called from main-app. The typescript is configured in UI (that's why there is only distDir in the typescript options).

Steps to reproduce the behavior, please provide code snippets or a repository:
with next 7.0.0 and next-css 1.0.0

## System information
 - Version of Next.js: [e.g. 7.0.0]

**Comment by josephluck** [comment]
As another data point.. I also get a related error for `mini-css-extract-plugin` with Next 7.0.0: 

```
TypeError: Cannot destructure property `createHash` of 'undefined' or 'null'.
    at Object.<anonymous> (/home/joseph/code/fantastec-game/node_modules/mini-css-extract-plugin/dist/index.js:21:5)
```

**Comment by mtree** [comment]
Before you close it and redirect to next-plugins - this is clearly related to next.js webpack configuration. More and more related issues are coming (look -> next-plugins). We clearly need some official statement on node_modules 3rd party component styling. If you don't really see the need of this feature, we clearly need some proper way to ignore any related 3rd party CSS require.

Please, help. :-)

**Comment by needcaffeine** [comment]
I was getting this error yesterday trying to include external scss. This is how I fixed it in my next.config.js:

```const withSass = require('@zeit/next-sass')
module.exports = withSass({
    sassLoaderOptions: {
        includePaths: [
            require('path').resolve(__dirname, 'node_modules')
        ]
    }
})```

**Comment by CYB3RL1F3** [comment]
I tried to use mini-css-extract-plugin and got the following error : 

```
Unexpected token .
/Users/deikean/Server/louvres-hotels/LH.WhiteLabel.App/site/node_modules/slick-carousel/slick/slick.css:2
.slick-slider
^

SyntaxError: Unexpected token .
```

Using that way : 

```
const withPlugins = (nextConfig = {}) => {
    return Object.assign({}, nextConfig, {
        webpack(config, options) {
            if (!config.plugins) config.plugins = [];
            config.plugins.push(
                new MiniCssExtractPlugin({
                    filename: 'style.css',
                    chunkFilename: '[name].css'
                })
            );
            config.module.rules.push({
                test: /\.css$/,
                use: [
                    {
                        loader: MiniCssExtractPlugin.loader,
                        options: {
                            publicPath: './static'
                        }
                    },
                    {
                        loader: 'css-loader',
                        options: {
                            modules: true,
                            sourceMap: true
                        }
                    }
                ]
            });

            if (typeof nextConfig.webpack === 'function') {
                return nextConfig.webpack(config, options);
            }

            return config;
        }
    });
};
```

and of course withPlugins(withTypescript.......)

**Comment by romainquellec** [comment]
similar to https://github.com/zeit/next-plugins/issues/273 & https://github.com/webpack-contrib/mini-css-extract-plugin/issues/282

**Comment by BipinBhandari** [comment]
Did anyone figured out the way?

**Comment by mdo5004** [comment]
I'm seeing this error when trying to use Semantic-UI. Here is a minimal reproduction: https://github.com/mdo5004/next-css-bug-min-repo

**Comment by adamthewan** [comment]
https://github.com/webpack-contrib/mini-css-extract-plugin/issues/69

I fixed it by updating my webpack via `yarn add webpack@latest`

**Comment by solomon18** [comment]
> [webpack-contrib/mini-css-extract-plugin#69](https://github.com/webpack-contrib/mini-css-extract-plugin/issues/69)
> 
> I fixed it by updating my webpack via `yarn add webpack@latest`

Thank you so much :) This worked me.

**Comment by richsilv** [comment]
This is related to the OP's issue, *not* the `Cannot destructure...` issue:

In order to use `next-css` to load a vendor CSS file that somehow includes an image (like Leaflet does, and I believe Slick-Carousel), you also need to have a file-loader for image files otherwise you'll get an `Unexpected character` error.

I thinks [`next-images`](https://github.com/arefaslani/next-images) will do the job, but it's easy enough to include `file-loader` yourself, e.g.:

```js
module.exports = withCSS({
  webpack(config) {
    config.module.rules.push({
      test: /\.(png|svg|jpg|gif)$/,
      use: ["file-loader"]
    });
    return config;
  }
}));
```

**Comment by mdo5004** [comment]
This solution worked for me. It seems like a common issue.

https://github.com/akiran/react-slick/issues/842#issuecomment-385378629

**Comment by ngocketit** [comment]
@mdo5004 I tried the one you mentioned but got another error:
```
:root {
^

SyntaxError: Unexpected token :
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
```

Here is `next.config.js`:
```
const withCSS = require('@zeit/next-css')

module.exports = withCSS({
  webpack: function (config) {
    config.module.rules.push({
      test: /\.(eot|woff|woff2|ttf|svg|png|jpg|gif)$/,
      use: {
        loader: 'url-loader',
        options: {
          limit: 100000,
          name: '[name].[ext]'
        }
      }
    })
    return config
  }
})
```

**Comment by kazumatsudo** [comment]
@ngocketit same issue was occured when I tried to import aws-amplify.
I added following in next.config.js and it worked.

```
if (typeof require !== "undefined") {
    require.extensions[".less"] = () => {};
    require.extensions[".css"] = (file) => {};
}
```

**Comment by ngocketit** [comment]
@kazumatsudo I tried it and that works! Thank you!
