### ISSUE TITLE
i18n error

### ISSUE THREAD

**Issue by markolofsen** [zeit/next.js#5269]
## Example name
i18n error

## Describe the bug
Repo example: https://github.com/markolofsen/nextjs

## To Reproduce
Steps to reproduce the behavior, please provide code snippets or a repository:
1. yarn dev --> http://localhost:3000/about
2. See error: Internal Server Error

## Expected behavior
My variable {t('pureComponent')} in /pages/about.js doesn't work

## System information
 - OS: MacOS
 - Version of Next.js: canary (latest)

## Additional context
```
TypeError: Cannot set property 'toJSON' of undefined
    at I18n.module.exports../i18n.js.i18n.getInitialProps (/Users/mark/Documents/htdocs/nextjs/.next/server/static/development/pages/about.js:143:19)
    at Function._callee$ (/Users/mark/Documents/htdocs/nextjs/.next/server/static/development/pages/about.js:327:91)
    at tryCatch (/Users/mark/Documents/htdocs/nextjs/node_modules/regenerator-runtime/runtime.js:62:40)
    at Generator.invoke [as _invoke] (/Users/mark/Documents/htdocs/nextjs/node_modules/regenerator-runtime/runtime.js:288:22)
    at Generator.prototype.(anonymous function) [as next] (/Users/mark/Documents/htdocs/nextjs/node_modules/regenerator-runtime/runtime.js:114:21)
    at asyncGeneratorStep (/Users/mark/Documents/htdocs/nextjs/.next/server/static/development/pages/about.js:284:103)
    at _next (/Users/mark/Documents/htdocs/nextjs/.next/server/static/development/pages/about.js:286:194)
    at <anonymous>
TypeError: Cannot read property 'sheetsRegistry' of undefined
    at Function.module.exports../pages/_document.js.MyDocument.getInitialProps (/Users/mark/Documents/htdocs/nextjs/.next/server/static/development/pages/_document.js:384:29)
    at _callee$ (/Users/mark/Documents/htdocs/nextjs/node_modules/next/dist/lib/utils.js:135:30)
    at tryCatch (/Users/mark/Documents/htdocs/nextjs/node_modules/regenerator-runtime/runtime.js:62:40)
    at Generator.invoke [as _invoke] (/Users/mark/Documents/htdocs/nextjs/node_modules/regenerator-runtime/runtime.js:288:22)
    at Generator.prototype.(anonymous function) [as next] (/Users/mark/Documents/htdocs/nextjs/node_modules/regenerator-runtime/runtime.js:114:21)
    at asyncGeneratorStep (/Users/mark/Documents/htdocs/nextjs/node_modules/@babel/runtime-corejs2/helpers/asyncToGenerator.js:5:24)
    at _next (/Users/mark/Documents/htdocs/nextjs/node_modules/@babel/runtime-corejs2/helpers/asyncToGenerator.js:27:9)
    at /Users/mark/Documents/htdocs/nextjs/node_modules/@babel/runtime-corejs2/helpers/asyncToGenerator.js:34:7
    at new Promise (<anonymous>)
    at new F (/Users/mark/Documents/htdocs/nextjs/node_modules/core-js/library/modules/_export.js:36:28)
    at /Users/mark/Documents/htdocs/nextjs/node_modules/@babel/runtime-corejs2/helpers/asyncToGenerator.js:23:12
    at loadGetInitialProps (/Users/mark/Documents/htdocs/nextjs/node_modules/next/dist/lib/utils.js:98:31)
    at _callee3$ (/Users/mark/Documents/htdocs/nextjs/node_modules/next/dist/server/render.js:339:51)
    at tryCatch (/Users/mark/Documents/htdocs/nextjs/node_modules/regenerator-runtime/runtime.js:62:40)
    at Generator.invoke [as _invoke] (/Users/mark/Documents/htdocs/nextjs/node_modules/regenerator-runtime/runtime.js:288:22)
    at Generator.prototype.(anonymous function) [as next] (/Users/mark/Documents/htdocs/nextjs/node_modules/regenerator-runtime/runtime.js:114:21)
TypeError: Cannot read property 'sheetsRegistry' of undefined
    at Function.module.exports../pages/_document.js.MyDocument.getInitialProps (/Users/mark/Documents/htdocs/nextjs/.next/server/static/development/pages/_document.js:384:29)
    at _callee$ (/Users/mark/Documents/htdocs/nextjs/node_modules/next/dist/lib/utils.js:135:30)
    at tryCatch (/Users/mark/Documents/htdocs/nextjs/node_modules/regenerator-runtime/runtime.js:62:40)
    at Generator.invoke [as _invoke] (/Users/mark/Documents/htdocs/nextjs/node_modules/regenerator-runtime/runtime.js:288:22)
    at Generator.prototype.(anonymous function) [as next] (/Users/mark/Documents/htdocs/nextjs/node_modules/regenerator-runtime/runtime.js:114:21)
    at asyncGeneratorStep (/Users/mark/Documents/htdocs/nextjs/node_modules/@babel/runtime-corejs2/helpers/asyncToGenerator.js:5:24)
    at _next (/Users/mark/Documents/htdocs/nextjs/node_modules/@babel/runtime-corejs2/helpers/asyncToGenerator.js:27:9)
    at /Users/mark/Documents/htdocs/nextjs/node_modules/@babel/runtime-corejs2/helpers/asyncToGenerator.js:34:7
    at new Promise (<anonymous>)
    at new F (/Users/mark/Documents/htdocs/nextjs/node_modules/core-js/library/modules/_export.js:36:28)
    at /Users/mark/Documents/htdocs/nextjs/node_modules/@babel/runtime-corejs2/helpers/asyncToGenerator.js:23:12
    at loadGetInitialProps (/Users/mark/Documents/htdocs/nextjs/node_modules/next/dist/lib/utils.js:98:31)
    at _callee3$ (/Users/mark/Documents/htdocs/nextjs/node_modules/next/dist/server/render.js:339:51)
    at tryCatch (/Users/mark/Documents/htdocs/nextjs/node_modules/regenerator-runtime/runtime.js:62:40)
    at Generator.invoke [as _invoke] (/Users/mark/Documents/htdocs/nextjs/node_modules/regenerator-runtime/runtime.js:288:22)
    at Generator.prototype.(anonymous function) [as next] (/Users/mark/Documents/htdocs/nextjs/node_modules/regenerator-runtime/runtime.js:114:21)
> Disposing inactive page(s): /about

```

**Comment by stevokk** [comment]
Is this not that maybe the constructor isn't called? I've yet to try and use a class constructor method in Next.js

`TypeError: Cannot read property 'sheetsRegistry' of undefined`

**Comment by markolofsen** [comment]
problem was here
```
  "scripts": {
    "dev": "node server.js",

```
