### ISSUE TITLE
Ant Design example doesn't work

### ISSUE THREAD

**Issue by SebaBoler** [zeit/next.js#5298]
# Bug report
Example Next.js with and doesn't work

npx create-next-app --example with-ant-design with-ant-design-app
cd with-ant-design-app
yarn
yarn dev

Compilation end good but when I trying to open localhost:3000 I get Server internal Error

## Describe the bug

 ERROR  Failed to compile with 1 errors                                                                          13:25:21

 error  in ./pages/index.js

Module build failed (from ./node_modules/next/dist/build/webpack/loaders/next-babel-loader.js):
Error: The 'decorators' plugin requires a 'decoratorsBeforeExport' option, whose value must be a boolean. If you are migrating from Babylon/Babel 6 or want to use the old decorators proposal, you should use the 'decorators-legacy' plugin instead of 'decorators'.
    at validatePlugins (/Users/sebastianpietrzak/Programming/NextJs/with-ant-design-app/node_modules/@babel/parser/lib/index.js:10421:13)
    at getParser (/Users/sebastianpietrzak/Programming/NextJs/with-ant-design-app/node_modules/@babel/parser/lib/index.js:10478:5)
    at parse (/Users/sebastianpietrzak/Programming/NextJs/with-ant-design-app/node_modules/@babel/parser/lib/index.js:10462:12)
    at parser (/Users/sebastianpietrzak/Programming/NextJs/with-ant-design-app/node_modules/@babel/core/lib/transformation/normalize-file.js:170:34)
    at normalizeFile (/Users/sebastianpietrzak/Programming/NextJs/with-ant-design-app/node_modules/@babel/core/lib/transformation/normalize-file.js:138:11)
    at runSync (/Users/sebastianpietrzak/Programming/NextJs/with-ant-design-app/node_modules/@babel/core/lib/transformation/index.js:44:43)
    at runAsync (/Users/sebastianpietrzak/Programming/NextJs/with-ant-design-app/node_modules/@babel/core/lib/transformation/index.js:35:14)
    at process.nextTick (/Users/sebastianpietrzak/Programming/NextJs/with-ant-design-app/node_modules/@babel/core/lib/transform.js:34:34)
    at process._tickCallback (internal/process/next_tick.js:61:11)

 @ multi ./pages/index.js

{ Error: Cannot find module '/Users/sebastianpietrzak/Programming/NextJs/with-ant-design-app/.next/server/static/development/pages/_document'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at _callee3$ (/Users/sebastianpietrzak/Programming/NextJs/with-ant-design-app/node_modules/next/dist/server/render.js:227:17)
    at tryCatch (/Users/sebastianpietrzak/Programming/NextJs/with-ant-design-app/node_modules/regenerator-runtime/runtime.js:62:40)
    at Generator.invoke [as _invoke] (/Users/sebastianpietrzak/Programming/NextJs/with-ant-design-app/node_modules/regenerator-runtime/runtime.js:288:22)
    at Generator.prototype.(anonymous function) [as next] (/Users/sebastianpietrzak/Programming/NextJs/with-ant-design-app/node_modules/regenerator-runtime/runtime.js:114:21)
    at asyncGeneratorStep (/Users/sebastianpietrzak/Programming/NextJs/with-ant-design-app/node_modules/@babel/runtime-corejs2/helpers/asyncToGenerator.js:5:24)
    at _next (/Users/sebastianpietrzak/Programming/NextJs/with-ant-design-app/node_modules/@babel/runtime-corejs2/helpers/asyncToGenerator.js:27:9) code: 'MODULE_NOT_FOUND' }
{ Error: Cannot find module '/Users/sebastianpietrzak/Programming/NextJs/with-ant-design-app/.next/server/static/development/pages/_document'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at _callee3$ (/Users/sebastianpietrzak/Programming/NextJs/with-ant-design-app/node_modules/next/dist/server/render.js:227:17)
    at tryCatch (/Users/sebastianpietrzak/Programming/NextJs/with-ant-design-app/node_modules/regenerator-runtime/runtime.js:62:40)
    at Generator.invoke [as _invoke] (/Users/sebastianpietrzak/Programming/NextJs/with-ant-design-app/node_modules/regenerator-runtime/runtime.js:288:22)
    at Generator.prototype.(anonymous function) [as next] (/Users/sebastianpietrzak/Programming/NextJs/with-ant-design-app/node_modules/regenerator-runtime/runtime.js:114:21)
    at asyncGeneratorStep (/Users/sebastianpietrzak/Programming/NextJs/with-ant-design-app/node_modules/@babel/runtime-corejs2/helpers/asyncToGenerator.js:5:24)
    at _next (/Users/sebastianpietrzak/Programming/NextJs/with-ant-design-app/node_modules/@babel/runtime-corejs2/helpers/asyncToGenerator.js:27:9) code: 'MODULE_NOT_FOUND' }
{ Error: Cannot find module '/Users/sebastianpietrzak/Programming/NextJs/with-ant-design-app/.next/server/static/development/pages/_document'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at _callee3$ (/Users/sebastianpietrzak/Programming/NextJs/with-ant-design-app/node_modules/next/dist/server/render.js:227:17)
    at tryCatch (/Users/sebastianpietrzak/Programming/NextJs/with-ant-design-app/node_modules/regenerator-runtime/runtime.js:62:40)
    at Generator.invoke [as _invoke] (/Users/sebastianpietrzak/Programming/NextJs/with-ant-design-app/node_modules/regenerator-runtime/runtime.js:288:22)
    at Generator.prototype.(anonymous function) [as next] (/Users/sebastianpietrzak/Programming/NextJs/with-ant-design-app/node_modules/regenerator-runtime/runtime.js:114:21)
    at asyncGeneratorStep (/Users/sebastianpietrzak/Programming/NextJs/with-ant-design-app/node_modules/@babel/runtime-corejs2/helpers/asyncToGenerator.js:5:24)
    at _next (/Users/sebastianpietrzak/Programming/NextJs/with-ant-design-app/node_modules/@babel/runtime-corejs2/helpers/asyncToGenerator.js:27:9)
    at process._tickCallback (internal/process/next_tick.js:68:7) code: 'MODULE_NOT_FOUND' }

**Comment by gatezh** [comment]
This issue is already addressed https://github.com/zeit/next.js/pull/5232

**Comment by timneutkens** [comment]
Fixed in #5298

**Comment by timneutkens** [comment]
Thanks @gatezh!
