### ISSUE TITLE
serve.js:32 ... SyntaxError: Unexpected token (

### ISSUE THREAD

**Issue by appernetic** [zeit/next.js#5333]
# Examples bug report
 serve -p 8080
/Users/knud/.npm-packages/lib/node_modules/serve/bin/serve.js:32
const updateCheck = async (isDebugging) => {
                          ^
SyntaxError: Unexpected token (
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:528:28)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.runMain (module.js:590:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
## Example name
https://nextjs.org/learn/excel/static-html-export/export-the-index-page

## Describe the bug
I installed serve and then run the example: cd out followed by serve -p 8080

## To Reproduce
Steps to reproduce the behavior, please provide code snippets or a repository:
1. Go to: https://nextjs.org/learn/excel/static-html-export/export-the-index-page
2. Follow the example..

## Expected behavior
https://nextjs.org/learn/excel/static-html-export/export-the-index-page

## System information
 - OS: macOS High Sierra

 - Version of Next.js: [e.g. 6.0.2]
^6.1.1

**Comment by timneutkens** [comment]
We support Node.js 8+

**Comment by appernetic** [comment]
Ok, I used an old node 6.7. Upgraded to 10.11 and now it works. Closing!
