### ISSUE TITLE
TypeError: Cannot read property 'injection' of undefined

### ISSUE THREAD

**Issue by rafaelfragosom** [zeit/next.js#5366]
# Bug report

## Describe the bug

I'm trying to get react-native-web to work with NextJS but it's not working how the documentation says.

I tried to downgrade my React and React-DOM versions, because of the issue with React 16.5 and React Native Web, but no success.

I'm only filing this issue because I also tried to download the example from your repo and got the same error. So I assume it's not about react-native-web or react anymore, it's about NextJS.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

Clone and run the `with-react-native-web-app` example.

## Expected behavior
It was suppose to work.

## System information
 - OS: macOS 
 - Browser (if applies) [e.g. chrome, safari]
 - Version of Next.js: 7.0.1
 - Node v8.12.0

## Additional context

```
TypeError: Cannot read property 'injection' of undefined
    at Object.<anonymous> (/Users/rafael.fragoso/Development/with-react-native-web-app/node_modules/react-native-web/dist/cjs/exports/createElement/index.js:43:16)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/rafael.fragoso/Development/with-react-native-web-app/node_modules/react-native-web/dist/cjs/exports/View/index.js:15:22)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
TypeError: Cannot read property 'injection' of undefined
    at Object.<anonymous> (/Users/rafael.fragoso/Development/with-react-native-web-app/node_modules/react-native-web/dist/cjs/exports/createElement/index.js:43:16)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/rafael.fragoso/Development/with-react-native-web-app/node_modules/react-native-web/dist/cjs/exports/View/index.js:15:22)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
```

**Comment by rafaelfragosom** [comment]
I'm closing this after. I found out it's nothing related to NextJS.

**Comment by tychovbh** [comment]
@rafaelfragosom i have this error too, what was it related too, and how do you solved it?

**Comment by rafaelfragosom** [comment]
@tychovbh The library I am using was depending on an older version of `react-native-web` which has no support for recent React versions.

Luckly, the library is maintained by my company and I was able to update it's dependencies and make it support recent versions of React and React DOM.
