### ISSUE TITLE
contributing.md out of date

### ISSUE THREAD

**Issue by sheerun** [zeit/next.js#5405]
# Bug report

## Describe the bug

I wanted to contribute something but I have no idea how to develop next.js, contributing.md seems out of date as when I run

```
npm run bootstrap
npm run dev
yarn testonly
```

Then I get lot of errors "SyntaxError: Unexpected identifier" of regeneratorRuntime.

Could you tell how I can properly start developing next.js (both next and next-server) and test it before sending PR?

**Comment by mherodev** [comment]
@timneutkens I am experiencing similar issues. 

```bash
npm i
npm run bootstrap
npm run dev
```

If I run the above steps, I run into the following error:

![image](https://user-images.githubusercontent.com/1099139/46631270-ca092880-cafb-11e8-9645-bdf9841e4bf8.png)

Tests are also failing with `Cannot find module '@babel/core'` (although I had them passing at one point...)

**Comment by mherodev** [comment]
Interesting, I removed `node_modules` and reinstalled, re-boostrapped and re-dev'd, and it all worked.

I am a little confused though, do I `npm link` the `packages/next` directory and then `cd` back to root and `run dev`, or what's the order of operations for locally developing.

**Comment by mherodev** [comment]
That said, I still can't get it to run with a local project. I end up with a series of errors when I hit localhost:3000, e.g.

```
{ Error: Cannot find module 'next-server/dist/lib/utils'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.next-server/dist/lib/utils (/Users/206476943/git/temp/next-test/.next/server/static/development/pages/_app.js:463:18)
    at __webpack_require__ (/Users/206476943/git/temp/next-test/.next/server/static/development/pages/_app.js:23:31)
    at Object.../next.js/packages/next/dist/pages/_app.js (/Users/206476943/git/temp/next-test/.next/server/static/development/pages/_app.js:138:14)
    at __webpack_require__ (/Users/206476943/git/temp/next-test/.next/server/static/development/pages/_app.js:23:31)
    at Object.0 (/Users/206476943/git/temp/next-test/.next/server/static/development/pages/_app.js:330:18)
    at __webpack_require__ (/Users/206476943/git/temp/next-test/.next/server/static/development/pages/_app.js:23:31)
    at /Users/206476943/git/temp/next-test/.next/server/static/development/pages/_app.js:91:18
    at Object.<anonymous> (/Users/206476943/git/temp/next-test/.next/server/static/development/pages/_app.js:94:10)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12) code: 'MODULE_NOT_FOUND' }
{ Error: Cannot find module 'next-server/dist/lib/utils'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
...
```

**Comment by dhleong** [comment]
Getting the same `Cannot find module 'next-server/dist/lib/utils'` error here

**Comment by sheerun** [comment]
ping

**Comment by mherodev** [comment]
Any clarifications around this, @timneutkens? I'm still blocked 😢 

`Error: Cannot find module 'next-server/dist/lib/utils'`

**Comment by mherodev** [comment]
Update:

As you might expect, this error is because `next-server` is not linked, but `next` is.

Here are the missing steps (I'll update the contributing.md):

## Inside `/next.js`

```bash
cd packages/next-server
npm link
cd ../..
npm run dev
```

## Inside `/your-local-next-dependent-project`

```bash
npm link next-server
npm run dev
```

**Comment by mherodev** [comment]
Well, this is odd. I can see changes I make inside `packages/next`, but I can't see any changes made inside `packages/next-server`

e.g. If I add a `console.log` inside `packages/next-server/lib/router/router.js`, I don't see that output anywhere.

Perhaps I need to link `next-server` to `next` inside its package...

**Comment by mherodev** [comment]
That seemed to do it! I'm seeing logs 💃💃💃 

I'll update the contributing.
