### ISSUE TITLE
Upgrade to Next v7 breaks app

### ISSUE THREAD

**Issue by trusktr** [zeit/next.js#5465]
# Bug report

## Describe the bug

I tried to upgrade to Next v7 and now my apps says this:

```
 ERROR  Failed to compile with 1 errors                                                                                                                                   8:05:33 PM

 error  in ./src/pages/_app.jsx

Module build failed (from ../node_modules/next/dist/build/webpack/loaders/next-babel-loader.js):
Error: The 'decorators' plugin requires a 'decoratorsBeforeExport' option, whose value must be a boolean. If you are migrating from Babylon/Babel 6 or want to use the old decorators proposal, you should use the 'decorators-legacy' plugin instead of 'decorators'.
    at validatePlugins (/Users/trusktr/src/spaceship-emporium/node_modules/@babel/parser/lib/index.js:10472:13)
    at getParser (/Users/trusktr/src/spaceship-emporium/node_modules/@babel/parser/lib/index.js:10529:5)
    at parse (/Users/trusktr/src/spaceship-emporium/node_modules/@babel/parser/lib/index.js:10513:12)
    at parser (/Users/trusktr/src/spaceship-emporium/node_modules/@babel/core/lib/transformation/normalize-file.js:170:34)
    at normalizeFile (/Users/trusktr/src/spaceship-emporium/node_modules/@babel/core/lib/transformation/normalize-file.js:138:11)
    at runSync (/Users/trusktr/src/spaceship-emporium/node_modules/@babel/core/lib/transformation/index.js:44:43)
    at runAsync (/Users/trusktr/src/spaceship-emporium/node_modules/@babel/core/lib/transformation/index.js:35:14)
    at process.nextTick (/Users/trusktr/src/spaceship-emporium/node_modules/@babel/core/lib/transform.js:34:34)
    at process._tickCallback (internal/process/next_tick.js:61:11)

 @ multi ./pages/_app.jsx

Client pings, but there's no entry for page: /ships
{ Error: Cannot find module '/Users/trusktr/src/spaceship-emporium/.dist/build-manifest.json'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at _callee3$ (/Users/trusktr/src/spaceship-emporium/node_modules/next/dist/server/render.js:223:42)
    at tryCatch (/Users/trusktr/src/spaceship-emporium/node_modules/@babel/runtime-corejs2/node_modules/regenerator-runtime/runtime.js:62:40)
    at Generator.invoke [as _invoke] (/Users/trusktr/src/spaceship-emporium/node_modules/@babel/runtime-corejs2/node_modules/regenerator-runtime/runtime.js:288:22)
    at Generator.prototype.(anonymous function) [as next] (/Users/trusktr/src/spaceship-emporium/node_modules/@babel/runtime-corejs2/node_modules/regenerator-runtime/runtime.js:114:21)
    at asyncGeneratorStep (/Users/trusktr/src/spaceship-emporium/node_modules/@babel/runtime-corejs2/helpers/asyncToGenerator.js:5:24)
    at _next (/Users/trusktr/src/spaceship-emporium/node_modules/@babel/runtime-corejs2/helpers/asyncToGenerator.js:27:9)
    at process._tickCallback (internal/process/next_tick.js:68:7) code: 'MODULE_NOT_FOUND' }
Client pings, but there's no entry for page: /ships
{ Error: Cannot find module '/Users/trusktr/src/spaceship-emporium/.dist/build-manifest.json'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at _callee3$ (/Users/trusktr/src/spaceship-emporium/node_modules/next/dist/server/render.js:223:42)
    at tryCatch (/Users/trusktr/src/spaceship-emporium/node_modules/@babel/runtime-corejs2/node_modules/regenerator-runtime/runtime.js:62:40)
    at Generator.invoke [as _invoke] (/Users/trusktr/src/spaceship-emporium/node_modules/@babel/runtime-corejs2/node_modules/regenerator-runtime/runtime.js:288:22)
    at Generator.prototype.(anonymous function) [as next] (/Users/trusktr/src/spaceship-emporium/node_modules/@babel/runtime-corejs2/node_modules/regenerator-runtime/runtime.js:114:21)
```

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:
1. `npm i 'next@^7'`
2. restart next.

## Expected behavior

I was hoping it worked

## System information
 - OS: macOS
 - Version of Next.js: 6.1.1 to 7.0.1

## Additional context

Investigating...

**Comment by trusktr** [comment]
I read #5231, and my `babelrc` already looks like it should:

```js
{
	"presets": ["next/babel"],
	"plugins": [
		[
			"@babel/plugin-proposal-decorators",
			{
				"legacy": true,
				"decoratorsBeforeExport": true
			}
		]
	]
}
```

yet I still get that same error.

**Comment by timneutkens** [comment]
There's not really anything we can change in Next.js related to this, so I'm going to close the issue.
