### ISSUE TITLE
first readme example breaks

### ISSUE THREAD

**Issue by davemo** [zeit/next.js#55]
![screen shot 2016-10-25 at 1 20 17 pm](https://cloud.githubusercontent.com/assets/69559/19696612/db0c1f70-9ab5-11e6-9ec5-17d1be62397c.png)

```bash
$ node -v
v7.0.0
$ npm -v
3.10.8
```

```bash
$ tree . -L 2
.
├── package.json
└── pages
    └── index.js
```

```bash
$ cat pages/index.js 
import React from 'react'
export default () => {
  <div>Welcome to next.js!</div>
}
```

```bash
$ cat package.json 
{
  "name": "next-play",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "dependencies": {
    "next": "^1.0.0"
  },
  "devDependencies": {},
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "start": "next"
  },
  "author": "",
  "license": "ISC"
}
```

```bash
$ npm start

> next-play@1.0.0 start /Users/ext.dmosher/code/next-play
> next

> Ready on http://localhost:3000
Warning: Component(...): A valid React element (or null) must be returned. You may have returned undefined, an array or some other invalid object.
{ Invariant Violation: Component(...): A valid React element (or null) must be returned. You may have returned undefined, an array or some other invalid object.
    at invariant (/Users/ext.dmosher/code/next-play/node_modules/fbjs/lib/invariant.js:38:15)
    at ReactCompositeComponentWrapper.mountComponent (/Users/ext.dmosher/code/next-play/node_modules/react/lib/ReactCompositeComponent.js:194:121)
    at Object.mountComponent (/Users/ext.dmosher/code/next-play/node_modules/react/lib/ReactReconciler.js:47:35)
    at ReactCompositeComponentWrapper.performInitialMount (/Users/ext.dmosher/code/next-play/node_modules/react/lib/ReactCompositeComponent.js:370:34)
    at ReactCompositeComponentWrapper.mountComponent (/Users/ext.dmosher/code/next-play/node_modules/react/lib/ReactCompositeComponent.js:257:21)
    at Object.mountComponent (/Users/ext.dmosher/code/next-play/node_modules/react/lib/ReactReconciler.js:47:35)
    at /Users/ext.dmosher/code/next-play/node_modules/react/lib/ReactServerRendering.js:46:36
    at ReactServerRenderingTransaction.perform (/Users/ext.dmosher/code/next-play/node_modules/react/lib/Transaction.js:138:20)
    at renderToStringImpl (/Users/ext.dmosher/code/next-play/node_modules/react/lib/ReactServerRendering.js:44:24)
    at renderToString (/Users/ext.dmosher/code/next-play/node_modules/react/lib/ReactServerRendering.js:74:10) name: 'Invariant Violation', framesToPop: 1 }
```

**Comment by impronunciable** [comment]
@davemo 

`pages/index.js` should be:

```
import React from 'react'
export default () => (
  <div>Welcome to next.js!</div>
)
```

`()` let's you return the expression while `{}` creates the block and not a return

**Comment by davemo** [comment]
@impronunciable ah, thanks, I typed it out instead of copy/pasted and had the wrong parens :(

**Comment by impronunciable** [comment]
@davemo that's how we learn :)
