### ISSUE TITLE
How to deploy NextJs project in production server?

### ISSUE THREAD

**Issue by anehkumar** [zeit/next.js#5512]
Hi, I create my project using NextJs and it was ready for production but I am little confuse how we can host that I  already run following command 

```
npm run build
npm run start
```

Now I am not sure which folder we need to upload to server do we need to upload complete project or only .next folder Can you please help me. How to host NextJs application.

Thanks in advance.

**Comment by MathiasKandelborg** [comment]
[This link might](https://nextjs.org/docs/#production-deployment) prove useful to you.

It's incredibly easy! To start, you'd want node to know that it's running in production. So you run the app in production like this: `NODE_ENV=production npm run start`.

**Comment by timneutkens** [comment]
Please post your question here: https://spectrum.chat/next-js, as per the issue template

**Comment by giriibm** [comment]
Looks like "next export" creates/export static pages on the "out" folder and I want to deploy it to the nginx that's the right way to deploy it in the production server? or  Am I missing anything here?, BTW we are using nodejs/mongodb for api/backend.  I'm don't know why we have "next build" and what is the difference between "next export" and "next build".

**Comment by scurrilus** [comment]
Just add "export" task to your package.json and run "npm run-script prod" or what ever you named it. It generates an "out" folder with all what you need. Just copy the content from the "out" folder to your server.

_package.json_

`"scripts": { `
` "dev": "next",`
`"build": "next build",`
`"start": "next start",`
`"prod": "next export"`
`},`

**Comment by mtaylor567** [comment]
Is next export only way to run a next build on nginx production?

**Comment by rezaHashemi8139** [comment]
Hey
Im quiet new to next.js and im trying to deploy my project to a windows webserver. Ive already installed node and iisnode but i really dont know how to get it work.

**Comment by sarang-naico** [comment]
@rezaHashemi8139 
Were you able to deploy the next js app on iis?

**Comment by iMerica** [comment]
This [official page](https://nextjs.org/docs/#production-deployment) is extremely thin running Next.js in production.

For example: How to enable access logs? Is a frontend web server (nginx) neccessary? Why/Why not? What are the trade offs? What is the reference architecture for running next.js in Kubernetes?

Can someone point me to any literature on these topics?

**Comment by timneutkens** [comment]
https://nextjs.org/docs/deployment#self-hosting

It's just hosting a Node.js application, nothing special needed really.

**Comment by thomasjm** [comment]
@timneutkens the self-hosting docs you linked say that to deploy a hybrid pages Node server to production, you should "Potentially copy the .next, node_modules, and package.json to your server."

What does "potentially" mean here? In particular, what determines when `node_modules` is needed? My `node_modules` is quite large and copying it to the server seems to defeat the purpose Webpack's tree-shaking, so I'm wondering if there's some way around this.

**Comment by timneutkens** [comment]
All node_modules your project depends on need to be installed, including next. Tree shaking is applied on client-side bundling, not server-side. Server-side all node_modules are marked as external.

**Comment by thomasjm** [comment]
Thanks for the quick response! Would the new `serverless` target be a way to get around this and have a smaller version on the server?

**Comment by timneutkens** [comment]
Depends on how you’re deploying, with serverless you have to deploy every page as a separate function (not one single server) otherwise it will negate optimizations from the severless target

**Comment by message** [comment]
Here's how I deployed my Next.JS app, maybe it will help someone.

Here is my bash script that is running in Jenkins
```sh
rm -rf $WORKSPACE/my-nextjs-project
git clone git@gitlab.com:me/my-nextjs-project.git $WORKSPACE/my-nextjs-project

cd $WORKSPACE/my-nextjs-project
git checkout master

yarn install
yarn build

mkdir my-nextjs-project

mv public/ my-nextjs-project/

NEXT_BUILD_ID=$(cat build/BUILD_ID)
LAST_COMMIT=$(git rev-parse HEAD)

echo "{git: ${LAST_COMMIT}, ci: ${BUILD_ID}, next: ${NEXT_BUILD_ID}}" > my-nextjs-project/CI

# trim package.json and leave only things that you need in production
cat package.json | jq '. | {name: .name, private: true, version: .version, scripts: {start: .scripts.start}, dependencies: .dependencies}' > my-nextjs-project/package.json

# I'm using next-compose-plugins, so here we need to dump config. If you have next.config.js as an object then just copy config file 
NEXT_CONFIG=$(node -e 'var configFile = require("./next.config.js"); var config = configFile([], {}); delete config.webpack; console.log(JSON.stringify(config));')
echo "module.exports = ${NEXT_CONFIG}" > my-nextjs-project/next.config.js # result => {distDir: "build", poweredByHeader: false}

mv build my-nextjs-project/

cd my-nextjs-project

yarn install 

cd $WORKSPACE/my-nextjs-project

# dump folder tree structure just for Jenkins console output logs
tree -h -L 1 build/

tar czf $WORKSPACE/my-nextjs-project.tar.gz my-nextjs-project
cd $WORKSPACE

rm -rf $WORKSPACE/my-nextjs-project
```

Upload result to your server (with `scp` for example, add your ssh key to `.ssh/authorized_keys` on server side to bypass password verification), unpack it (e.g.`/var/www/my-nextjs-project`) and run it. You can install your node application as `systemd` service.

Here is my `/etc/systemd/system/nextjs.service`

```
[Unit]
Description=My Next.JS app

[Service]
ExecStart=node ./node_modules/.bin/next start -p 6200
Restart=always
User=www-data
Group=www-data
Environment=PATH=/usr/bin:/usr/local/bin
Environment=NODE_ENV=production
WorkingDirectory=/var/www/my-nextjs-project
StandardOutput=append:/var/log/www/my-nextjs-project/common.log
StandardError=inherit

[Install]
WantedBy=multi-user.target
```

Since it's a service now, you can `sudo systemctl start/stop/restart nextjs`

Much love ❤️

**Comment by deadcoder0904** [comment]
How can I access `.next/server` on Vercel???

I have a `package.json` script like:

```json
{
 "export": "next export",
 "build": "next build && npm run export && npm run build:rss",
 "build:rss": "node ./.next/server/scripts/build-rss.js",
 "start": "next start",
}
```

It has `build:rss` which points to `./.next/server/scripts/build-rss.js` but it cannot find it on Vercel. How do I point it correctly on Vercel? I get the following error & cannot deploy my site:

```bash
> node ./.next/server/scripts/build-rss.js
15:14:05.786 internal/modules/cjs/loader.js:968
15:14:05.786 throw err;
15:14:05.786 ^
15:14:05.786 Error: Cannot find module '/vercel/workpath0/.next/server/scripts/build-rss.js'
15:14:05.786 at Function.Module._resolveFilename (internal/modules/cjs/loader.js:965:15)
15:14:05.786 at Function.Module._load (internal/modules/cjs/loader.js:841:27)
15:14:05.786 at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
15:14:05.786 at internal/main/run_main_module.js:17:47 {
```

**Comment by deadcoder0904** [comment]
The answer is to use `.serverless` instead of `.server` as Vercel has a `.serverless` directory so I'd change my RSS script:

```json
{
 "export": "next export",
 "build": "next build && npm run export && npm run build:rss",
 "build:rss": "node ./.next/serverless/scripts/build-rss.js",
 "start": "next start",
}
```

**Comment by muratx10** [comment]
@message thanx dude! You saved me)

**Comment by balazsorban44** [comment]
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
