### ISSUE TITLE
NextJS is not working with react-spring properly

### ISSUE THREAD

**Issue by iammarkps** [zeit/next.js#5532]
# Bug report

## Describe the bug

When using react-spring its throw this error
```
global.requestAnimationFrame is not a function

TypeError: global.requestAnimationFrame is not a function
    at requestFrame (/Users/iammark/Projects/openhouse/node_modules/react-spring/dist/web.cjs.js:18:17)
    at Controller.start (/Users/iammark/Projects/openhouse/node_modules/react-spring/dist/web.cjs.js:1542:18)
    at Controller.update (/Users/iammark/Projects/openhouse/node_modules/react-spring/dist/web.cjs.js:1530:47)
    at new Controller (/Users/iammark/Projects/openhouse/node_modules/react-spring/dist/web.cjs.js:1335:10)
    at new Parallax (/Users/iammark/Projects/openhouse/node_modules/react-spring/dist/addons.cjs.js:218:25)
    at processChild (/Users/iammark/Projects/openhouse/node_modules/react-dom/cjs/react-dom-server.node.development.js:2435:14)
    at resolve (/Users/iammark/Projects/openhouse/node_modules/react-dom/cjs/react-dom-server.node.development.js:2401:5)
    at ReactDOMServerRenderer.render (/Users/iammark/Projects/openhouse/node_modules/react-dom/cjs/react-dom-server.node.development.js:2728:22)
    at ReactDOMServerRenderer.read (/Users/iammark/Projects/openhouse/node_modules/react-dom/cjs/react-dom-server.node.development.js:2699:25)
    at renderToString (/Users/iammark/Projects/openhouse/node_modules/react-dom/cjs/react-dom-server.node.development.js:3113:25)
    at renderPage (/Users/iammark/Projects/openhouse/node_modules/next/dist/server/render.js:319:26)
    at Function.getInitialProps (/Users/iammark/Projects/openhouse/.next/server/static/development/pages/_document.js:193:18)
    at _callee$ (/Users/iammark/Projects/openhouse/node_modules/next/dist/lib/utils.js:86:30)
    at tryCatch (/Users/iammark/Projects/openhouse/node_modules/regenerator-runtime/runtime.js:62:40)
    at Generator.invoke [as _invoke] (/Users/iammark/Projects/openhouse/node_modules/regenerator-runtime/runtime.js:288:22)
    at Generator.prototype.(anonymous function) [as next] (/Users/iammark/Projects/openhouse/node_modules/regenerator-runtime/runtime.js:114:21)
```

The problem is with NextJS, not react-spring itself because I've tried using react-spring separately.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:
1. Go to 'https://github.com/iammarkps/openhouse' and clone the repo
2. yarn install
3. yarn dev
4. Go to 'http://localhost:3000

## Expected behavior
App render properly

## System information
 - OS: macOS
 - Firefox
 - NextJS 7

Ref: https://github.com/drcmda/react-spring/issues/278

**Comment by zhaiduo** [comment]
You need to check out this: http://www.mariadcampbell.com/2017/09/27/requestanimationframe-and-polyfill-in-react-16/, better use in 16.7.0-alpha :)

**Comment by ritz078** [comment]
I am getting the following error with react-spring 6. Everything works fine with v5.

<img width="1274" alt="screenshot 2018-11-03 at 2 17 49 pm" src="https://user-images.githubusercontent.com/5389035/47950095-a064e500-df73-11e8-8f3e-811313ede1fe.png">

@drcmda

**Comment by drcmda** [comment]
Right, it goes into `items` now, could you fix it?
