### ISSUE TITLE
brace: window is not defined

### ISSUE THREAD

**Issue by markolofsen** [zeit/next.js#5547]
# Bug report
I'm using [React ACE Editor](https://github.com/securingsincity/react-ace) with [brace](https://www.npmjs.com/package/brace) and got en error `window is not defined`

Also i'm doing it with dynamic components, bit problem still save.

## Additional context
```
ReferenceError: window is not defined
    at .../node_modules/brace/index.js:20265:21
    at _acequire (.../node_modules/brace/index.js:88:37)
    at Object.acequire (.../node_modules/brace/index.js:93:26)
    at .../node_modules/brace/index.js:20260:21
    at Object.<anonymous> (.../node_modules/brace/index.js:20270:15)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at Object.brace (.../.next/server/static/development/pages/user_projects_details.js:9932:18)
    at __webpack_require__ (.../.next/server/static/development/pages/user_projects_details.js:29:31)
    at Module../components/AceEditor/Include.js (.../.next/server/0.js:17:63)
    at __webpack_require__ (.../.next/server/static/development/pages/user_projects_details.js:29:31)
    at <anonymous>:null:null
```

**Comment by sergiodxa** [comment]
Brace is running server side but it depends on `window` object which it doesn't exists server side, try using it only in `componentDidMount` so it only runs client side.

**Comment by timneutkens** [comment]
Or use `next/dynamic` with `ssr: false`

**Comment by markolofsen** [comment]
it's look like
`const AceEditor = dynamic(import('./Include'), {ssr: false})`
...but doesn't work. Window error

**Comment by markolofsen** [comment]
@sergiodxa It doesn't matter, because I have to connect **brace** originally in header of my Dynamic include component.

**Comment by markolofsen** [comment]
Example:

**index.js**
```
import React from 'react';
import PropTypes from 'prop-types';

import dynamic from 'next/dynamic'
const AceEditor = dynamic(import('./Include'), {ssr: false})


class AceEditorDynamic extends React.Component {

  componentDidMount() {
    this.props.onRef(this)
  }

  componentWillUnmount() {
    this.props.onRef(undefined)
  }

  getContent = () => {
    return this.refAceEditor.getContent()
  }

  render() {
    const {value, mode} = this.props
    return (
      <div style={{height: '100%',}}>
        <AceEditor onRef={ref => (this.refAceEditor = ref)} value={value} mode={mode} />
      </div>
    )
  }
}

AceEditorDynamic.propTypes = {
  value: PropTypes.string.isRequired,
  mode: PropTypes.string.isRequired,
};

export default AceEditorDynamic

```

**Include.js**
```
import React from 'react';
import PropTypes from 'prop-types';

import brace from 'brace';
import AceEditor from 'react-ace';

import '../../node_modules/brace/mode/python';
import '../../node_modules/brace/theme/monokai';

class AceEditorComponent extends React.Component {

  state = {
    value: ''
  }

  componentDidMount() {
    this.props.onRef(this)

    const {value} = this.props
    this.setState({value})
  }

  componentWillUnmount() {
    this.props.onRef(undefined)
  }

  getContent = () => {
    return this.state.value
  }

  onChange = (value) => {
    this.setState({value})
    // console.log('change',newValue);
  }

  onLoad = () => {}

  render() {

    const {mode} = this.props

    return (
      <AceEditor
    		mode={mode}
    		theme="monokai"
    		name="AceEditor_id"
    		onLoad={this.onLoad}
    		onChange={this.onChange}
    		fontSize={18}
    		showPrintMargin={true}
    		showGutter={true}
    		highlightActiveLine={true}
    		width="100%"
    		height="100%"

    		value={this.state.value}
        editorProps={{$blockScrolling: true}}
    		setOptions={{
    		  enableBasicAutocompletion: false,
    		  enableLiveAutocompletion: true,
    		  enableSnippets: false,
    		  showLineNumbers: true,
    		  tabSize: 2,
    	  }}
      />
    )
  }
}


AceEditorComponent.propTypes = {
  value: PropTypes.string.isRequired,
  mode: PropTypes.string.isRequired,
};

export default AceEditorComponent


```
