### ISSUE TITLE
Error: Cannot resolve dependency MODULE_NOT_FOUND

### ISSUE THREAD

**Issue by rodrigooler** [zeit/next.js#5557]
I was testing the new version and discovered a new bug.
Maybe it's because I'm using `babel-plugin-root-import`

babel:

```json
"babel": {
    "plugins": [
      "babel-plugin-root-import"
    ],
    "presets": [
      "next/babel",
      "@zeit/next-typescript/babel"
    ]
  },
```

Version: 7.0.3-alpha.0

Error:
```sh
$ next build src/
🚨  /Users/rodrigooler/projects/clubinvest-workstation/clubinvest/core/web-frontend/src/pages/2fa.tsx:15:39: Cannot resolve dependency '~/src/atoms/Card' a
t '/Users/rodrigooler/projects/clubinvest-workstation/clubinvest/core/web-frontend/src/pages/~/src/atoms/Card'
    at Resolver.resolve (/Users/rodrigooler/projects/clubinvest-workstation/clubinvest/core/web-frontend/node_modules/parcel/src/Resolver.js:70:17)
{ Error: Cannot resolve dependency '~/src/atoms/Card' at '/Users/rodrigooler/projects/clubinvest-workstation/clubinvest/core/web-frontend/src/pages/~/src/
atoms/Card'
    at Resolver.resolve (/Users/rodrigooler/projects/clubinvest-workstation/clubinvest/core/web-frontend/node_modules/parcel/src/Resolver.js:70:17)
  code: 'MODULE_NOT_FOUND',
  loc: Position { line: 15, column: 39 },
  fileName:
   '/Users/rodrigooler/projects/clubinvest-workstation/clubinvest/core/web-frontend/src/pages/2fa.tsx' }
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
MacBook-Pro-de-Rodrigo:web-frontend rodrigooler$
```

![captura de tela 2018-10-30 as 16 42 11](https://user-images.githubusercontent.com/5496931/47745793-3f7f9900-dc63-11e8-9068-7515ba98dc74.png)

**Comment by timneutkens** [comment]
Sounds like babel-plugin-root-import was not executed, as otherwise the path with `~` would be an absolute file path.

**Comment by rodrigooler** [comment]
@timneutkens yes, thanks.
