### ISSUE TITLE
next export Error: No router instance found

### ISSUE THREAD

**Issue by sumitparakh** [zeit/next.js#5637]
# Bug report

## Describe the bug

When i export my app i get following error:-
**Error: No router instance found.
You should only use "next/router" inside the client side of your app.**

app works perfectly fine with **next build**, **next start** and **next** command  but fails for following export command:-
> **next export -o public**

Here is the output of above command:-

next export -o public
> using build directory: /home/sumit/Documents/projects/opensource/project/.next
  copying "static" directory
  copying "static build" directory
> No "exportPathMap" found in "next.config.js". Generating map from "./pages"
> exporting path: /404
true
> exporting path: /about
true
> exporting path: /chapter_leader
true
> exporting path: /code_schools
true
> exporting path: /faq
true
> exporting path: /get_involved
true
> exporting path: /history
true
Error: No router instance found.
You should only use "next/router" inside the client side of your app.

    at throwIfNoRouter (/home/sumit/Documents/projects/opensource/project/node_modules/next/dist/lib/router/index.js:110:11)
    at Object.get (/home/sumit/Documents/projects/opensource/project/node_modules/next/dist/lib/router/index.js:65:7)
    at OutboundLink_OutboundLink (/home/sumit/Documents/projects/opensource/project/.next/server/static/_DxySqg9SIvl5Y3zScEb6/pages/_app.js:200:85)
    at d (/home/sumit/Documents/projects/opensource/project/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:29:492)
    at za (/home/sumit/Documents/projects/opensource/project/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:31:494)
    at a.render (/home/sumit/Documents/projects/opensource/project/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:36:147)
    at a.read (/home/sumit/Documents/projects/opensource/project/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:35:333)
    at renderToString (/home/sumit/Documents/projects/opensource/project/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:47:6)
    at renderPage (/home/sumit/Documents/projects/opensource/project/node_modules/next/dist/server/render.js:319:26)
    at Function.getInitialProps (/home/sumit/Documents/projects/opensource/project/node_modules/next/dist/server/document.js:65:25)
error Command failed with exit code 1.

## Package information
 - next(7.0.2)
 - react(^16.6.0)

## Additional context
Please let me know if any further details are required to understand this problem.

**Comment by sumitparakh** [comment]
> Can you provide a minimal reproduction in a GitHub repository?

@timneutkens  Please check above referenced pull request.

**Comment by timneutkens** [comment]
I just ran the latest master branch `yarn build` and then `yarn export -o public` and both worked perfectly.
