### ISSUE TITLE
Cannot run any next.js project, issue with tapable/lib/Hook.js?

### ISSUE THREAD

**Issue by garrettmac** [zeit/next.js#5647]
##  Bug report / Describe the bug
I am getting the following error running any nextjs projects (all examples and custom nextjs apps). I believe it has to do with something outside of nextjs projects as I can run the projects when I login as any other user. I only have issues with any project where the project is placed anywhere recursively placed past my  `/Users/myusername/` directory, as it works under any other user or if project is placed here `/Users/nextjs-example`

It doesn't matter if its using the `./node_modules/.bin/next` to build or `node` (eg `node server.js`) I get the same error for every project.

```

/Users/myusername/next.js/examples/custom-server/node_modules/tapable/lib/HookCodeFactory.js:32
				fn = new Function(
				     ^

RangeError: Maximum call stack size exceeded
    at new Function (<anonymous>)
    at AsyncSeriesBailHookCodeFactory.create (/Users/myusername/next.js/examples/custom-server/node_modules/tapable/lib/HookCodeFactory.js:32:10)
    at AsyncSeriesBailHook.compile (/Users/myusername/next.js/examples/custom-server/node_modules/tapable/lib/AsyncSeriesBailHook.js:28:18)
    at AsyncSeriesBailHook._createCall (/Users/myusername/next.js/examples/custom-server/node_modules/tapable/lib/Hook.js:24:15)
    at AsyncSeriesBailHook.lazyCompileHook [as callAsync] (/Users/myusername/next.js/examples/custom-server/node_modules/tapable/lib/Hook.js:153:21)
    at Resolver.doResolve (/Users/myusername/next.js/examples/custom-server/node_modules/enhanced-resolve/lib/Resolver.js:235:16)
    at resolver.getHook.tapAsync (/Users/myusername/next.js/examples/custom-server/node_modules/enhanced-resolve/lib/TryNextPlugin.js:17:13)
    at AsyncSeriesBailHook.eval [as callAsync] (eval at create (/Users/myusername/next.js/examples/custom-server/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:7:1)
    at AsyncSeriesBailHook.lazyCompileHook (/Users/myusername/next.js/examples/custom-server/node_modules/tapable/lib/Hook.js:154:20)
    at Resolver.doResolve (/Users/myusername/next.js/examples/custom-server/node_modules/enhanced-resolve/lib/Resolver.js:235:16)
    at resolver.getHook.tapAsync (/Users/myusername/next.js/examples/custom-server/node_modules/enhanced-resolve/lib/ModuleKindPlugin.js:19:13)
    at _fn41 (eval at create (/Users/myusername/next.js/examples/custom-server/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:385:1)
    at resolver.getHook.tapAsync (/Users/myusername/next.js/examples/custom-server/node_modules/enhanced-resolve/lib/AliasPlugin.js:53:11)
    at _fn40 (eval at create (/Users/myusername/next.js/examples/custom-server/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:376:1)
    at resolver.getHook.tapAsync (/Users/myusername/next.js/examples/custom-server/node_modules/enhanced-resolve/lib/AliasPlugin.js:53:11)
    at _fn39 (eval at create (/Users/myusername/next.js/examples/custom-server/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:367:1)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

## To Reproduce

I have no idea.

## System information
 - OS:   macOS
 - Version of Next.js: 7.0.2
 - Node: v8.10.0
- npm v5.6.0

## Additional context

I thought it could be related to some of my global installed packages and removed any I thought was causing the conflict.

Here are my global npm packages:

```
> npm -g ls --depth=0               

/usr/local/lib
├── alias-quokka-plugin@0.1.0
├── awsmobile-cli@1.0.21
├── UNMET PEER DEPENDENCY babel-eslint@>= 7
├── codecov@3.0.4
├── covermy@0.2.4
├── create-razzle-app@0.8.12
├── create-react-app@1.5.1
├── create-react-native-app@2.0.2
├── cypress@2.1.0
├── devtool@2.3.1
├── diff2html-cli@2.5.4
├── docker-compose@0.4.3
├── esformatter@0.10.0
├── esformatter-jsx@8.0.1
├── UNMET PEER DEPENDENCY eslint@5.8.0
├── eslint-config-airbnb@16.1.0
├── eslint-config-last@0.0.5
├── eslint-config-prettier@2.9.0
├── eslint-plugin-css-modules@2.7.5
├── eslint-plugin-flowtype@2.41.0
├── eslint-plugin-fp@2.3.0
├── eslint-plugin-import@2.8.0
├── eslint-plugin-jest@21.6.1
├── eslint-plugin-jsx-a11y@6.0.3
├── eslint-plugin-prettier@2.4.0
├── eslint-plugin-promise@4.0.1
├── eslint-plugin-react@7.11.1
├── eslint-plugin-standard@4.0.0
├── flow-bin@0.61.0
├── forever@0.15.3
├── gatsby-cli@1.1.52
├── generator-react-server@0.8.1
├── git-change-date@1.0.2
├── gnomon@1.5.0
├── gpg@0.6.0
├── graphcool@0.11.6
├── ios-deploy@1.9.2
├── istanbul@0.4.5
├── jest@22.0.4
├── jest-codemods@0.13.9
├── js-beautify@1.8.6
├── jscodeshift@0.4.0
├── jsdom-quokka-plugin@1.0.9
├── jshint@2.9.5
├── jslint@0.11.0
├── lambda-local@1.4.7
├── lebab@2.7.7
├── lint-github-pr@1.0.1
├── n@2.1.11
├── ngrok@3.0.1
├── node-debug@0.1.0
├── node-es6@0.3.1
├── node-inspector@1.1.2
├── node-nightly@1.7.3
├── node-sass@4.9.0
├── nodemon@1.14.7
├── npm@5.6.0
├── npm-install-peers@1.2.1
├── nvm@0.0.4
├── package-info@3.0.1
├── prettier@1.10.2
├── react-native-cli@2.0.1
├── react-native-debugger@1.1.0
├── react-native-git-upgrade@0.2.7
├── react-native-scripts@1.14.0
├── renamer@0.6.1
├── rnpm@1.9.0
├── sequelize-cli@4.0.0
├── serverless@1.26.1
├── sqlite-json@1.0.1
├── testcafe@0.20.2
├── tinderauth@2.0.3
├── typescript@3.1.3
└── yarn@1.12.3

npm ERR! peer dep missing: eslint@^4.9.0, required by eslint-config-airbnb@16.1.0
npm ERR! peer dep missing: eslint@2.x - 4.x, required by eslint-plugin-import@2.8.0
npm ERR! peer dep missing: eslint@^3 || ^4, required by eslint-plugin-jsx-a11y@6.0.3
npm ERR! peer dep missing: babel-eslint@>= 7, required by eslint-config-last@0.0.5
npm ERR! peer dep missing: eslint@^4.9.0, required by eslint-config-airbnb-base@12.1.0
npm ERR! missing: strip-ansi@^3.0.1, required by cli-columns@3.1.2
npm ERR! missing: safe-buffer@^5.1.2, required by minipass@2.3.3
npm ERR! missing: strip-ansi@^3.0.1, required by gauge@2.7.4
npm ERR! missing: strip-ansi@^3.0.0, required by string-width@1.0.2
npm ERR! missing: strip-ansi@^3.0.0, required by string-width@1.0.2
npm ERR! missing: pacote@^8.1.6, required by libcipm@2.0.0
npm ERR! missing: read-package-json@^2.0.13, required by libcipm@2.0.0
npm ERR! missing: worker-farm@^1.6.0, required by libcipm@2.0.0
npm ERR! missing: lru-cache@^4.1.2, required by npm-registry-fetch@3.1.1
npm ERR! missing: lru-cache@^4.1.2, required by make-fetch-happen@4.0.1
npm ERR! missing: mississippi@^3.0.0, required by make-fetch-happen@4.0.1
npm ERR! missing: ssri@^6.0.0, required by make-fetch-happen@4.0.1
npm ERR! missing: lru-cache@^4.1.2, required by npm-registry-fetch@1.1.0
npm ERR! missing: lru-cache@^4.1.2, required by make-fetch-happen@3.0.0
npm ERR! missing: mississippi@^3.0.0, required by make-fetch-happen@3.0.0
npm ERR! missing: strip-ansi@^3.0.1, required by wrap-ansi@2.1.0
npm ERR! missing: strip-ansi@^3.0.0, required by string-width@1.0.2
npm ERR! missing: readable-stream@^2.1.5, required by stream-iterate@1.2.0
```
Is it some babel issue, what would cause this issue?

**Comment by timneutkens** [comment]
Maybe you're installing `webpack` yourself, but I'm not sure what to do with this issue based on the given description. Do you have a custom next.config.js, package.json dependencies etc? I'm going to close the issue to keep the issue list clear.
