### ISSUE TITLE
Uncaught ReferenceError: dll is not defined

### ISSUE THREAD

**Issue by Jero786** [zeit/next.js#5702]
# Bug report
The error `Uncaught ReferenceError: dll_xxxxxx is not defined` it happens a soon as you create a empty project and open it. Please take a look the [following demo project](https://github.com/Jero786/nextjs-issue-5641).

It does only happening in Chrome! in FF it's works fine.

```
MacOs Sierra: 10.13.6
Chrome Version: 70.0.3538.102
Node: v10.10.0
NPM: v6.4.1
```

- Package dependencies: 
```
 "@zeit/next-sass": "^1.0.2-canary.0",
    "babel-polyfill": "^6.26.0",
    "classnames": "^2.2.6",
    "cross-fetch": "^2.2.2",
    "express": "^4.16.4",
    "fs": "0.0.1-security",
    "immutable": "^3.8.2",
    "lodash": "^4.17.10",
    "next": "^7.0.2-canary.21",
    "next-redux-wrapper": "^2.0.0",
    "node-sass": "4.9.4",
    "prop-types": "^15.6.2",
    "react": "^16.4.2",
    "react-dom": "^16.4.2",
    "react-notification-system": "^0.2.17",
    "react-redux": "^5.0.7",
    "redux": "^4.0.0",
    "redux-devtools-extension": "^2.13.5",
    "redux-immutable": "^4.0.0",
    "redux-thunk": "^2.3.0"
```

my dev dependencies:
```
"devDependencies": {
    "babel-core": "7.0.0-bridge.0",
    "babel-eslint": "^8.2.6",
    "babel-jest": "22.4.3",
    "babel-plugin-module-resolver": "^3.1.1",
    "chai": "^4.1.2",
    "enzyme": "3.2.0",
    "enzyme-adapter-react-16": "1.5.0",
    "eslint": "^4.19.1",
    "eslint-config-airbnb": "^17.0.0",
    "eslint-plugin-import": "^2.13.0",
    "eslint-plugin-jsx-a11y": "^6.1.1",
    "eslint-plugin-react": "^7.10.0",
    "husky": "^0.14.3",
    "jest": "22.0.1",
    "lint-staged": "^7.3.0",
    "prettier-eslint": "^8.8.2",
    "react-addons-test-utils": "15.6.2",
    "react-test-renderer": "16.2.0",
    "sinon": "^6.1.5",
    "superagent": "^4.0.0-beta.5",
    "supertest": "^3.3.0"
  }
```

## Expected behavior
Should not show any message error.

## Screenshots

<img width="887" alt="48650538-5f3ded80-e9d5-11e8-9125-09837a55afe7" src="https://user-images.githubusercontent.com/1815487/48703073-6a5d6d00-ebd1-11e8-94ac-36689b737025.png">

## Additional context

This bug was [closed](https://github.com/zeit/next.js/issues/5641) but it's still there and I change the name of the bug in order to be more searchable.

**Comment by timneutkens** [comment]
Please provide a *full* reproduction. I still can't reproduce.

**Comment by PrimarchAlpharius** [comment]
Can confirm the bug, reverting to v7.0.1 solves the problem for me

**Comment by timneutkens** [comment]
> Please provide a full reproduction. I still can't reproduce.

I keep repeating myself in these issues 😢

It's really hard to look into or fix anything without a full reproduction of this issue.

**Comment by Jero786** [comment]
if I just clone the project that I [sent](https://github.com/Jero786/nextjs-issue-5641), and write `npm install && npm run` and then open a `Chrome` it does happen. Again for me only in chrome. (Version 70.0.3538.102 (Official Build) (64-bit))

**Comment by Jero786** [comment]
> Can confirm the bug, reverting to v7.0.1 solves the problem for me

for me it doesn't work :(

**Comment by timneutkens** [comment]
Just tried the repo, which is a Next.js app with one page, meaning it's the equivalent of our test suites, and had no issue at all. I'm on chrome 70.0.3538.102.

**Comment by davscro** [comment]
...also while I am getting above error in chrome console in the same time I see in node console
```javascript
TypeError: Cannot read property 'finished' of undefined
    at HotReloader._callee2$ (/node_modules/next/dist/server/hot-reloader.js:276:34)
    at tryCatch (/node_modules/@babel/runtime-corejs2/node_modules/regenerator-runtime/runtime.js:62:40)
    at Generator.invoke [as _invoke] (/node_modules/@babel/runtime-corejs2/node_modules/regenerator-runtime/runtime.js:288:22)
    at Generator.prototype.(anonymous function) [as next] (/node_modules/@babel/runtime-corejs2/node_modules/regenerator-runtime/runtime.js:114:21)
    at asyncGeneratorStep (/node_modules/@babel/runtime-corejs2/helpers/asyncToGenerator.js:5:24)
    at _next (/node_modules/@babel/runtime-corejs2/helpers/asyncToGenerator.js:27:9)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:182:7)
```
I am not sure whether this one is connected 🤔

**Comment by djhi** [comment]
I reproduced this issue when trying to install both `react@16.7.0-alpha.2` and `@material-ui/styles@3.0.0-alpha.2` which has a peer dependency on `react@16.7.0-alpha.0`. When removing `@material-ui/styles@3.0.0-alpha.2`, the issue disappeared so I suspected there were multiple versions of react conflicting.

Adding a resolution key in my package.json for `react` and `react-dom` targetting the version I want solved the issue

**Comment by timneutkens** [comment]
So the issue could be `react` being shipped with a dependency you install 🤔

**Comment by davidcraig** [comment]
I am also getting this error today on a fresh NextJS build - it only happens on localhost (does not happen once the project is deployed) - I am developing on a Windows machine at the minute, perhaps issue is an edge case with webpack on windows node?

Console warning is present in firefox and chrome. 

```
external "dll_513dd14659e539e0c36c":1 Uncaught ReferenceError: dll_513dd14659e539e0c36c is not defined
    at Object.dll-reference dll_513dd14659e539e0c36c (external "dll_513dd14659e539e0c36c":1)
    at __webpack_require__ (bootstrap:788)
    at fn (bootstrap:149)
    at Object../node_modules/react/index.js?79ad (index.js from dll-reference dll_513dd14659e539e0c36c:1)
    at __webpack_require__ (bootstrap:788)
    at fn (bootstrap:149)
    at Object../node_modules/next/dist/client/index.js (index.js:35)
    at __webpack_require__ (bootstrap:788)
    at fn (bootstrap:149)
    at Object../node_modules/next/dist/client/next-dev.js (next-dev.js:23)
dll-reference dll_513dd14659e539e0c36c @ external "dll_513dd14659e539e0c36c":1
__webpack_require__ @ bootstrap:788
fn @ bootstrap:149
./node_modules/react/index.js?79ad @ index.js from dll-reference dll_513dd14659e539e0c36c:1
__webpack_require__ @ bootstrap:788
fn @ bootstrap:149
./node_modules/next/dist/client/index.js @ index.js:35
__webpack_require__ @ bootstrap:788
fn @ bootstrap:149
./node_modules/next/dist/client/next-dev.js @ next-dev.js:23
__webpack_require__ @ bootstrap:788
fn @ bootstrap:149
0 @ module.js:22
__webpack_require__ @ bootstrap:788
checkDeferredModules @ bootstrap:45
webpackJsonpCallback @ bootstrap:32
(anonymous) @ main.js?ts=1552845440736:1
```

Package.json deps
```
"dependencies": {
    "@fortawesome/fontawesome-svg-core": "^1.2.15",
    "@fortawesome/free-solid-svg-icons": "^5.7.2",
    "@fortawesome/react-fontawesome": "^0.1.4",
    "@zeit/next-sass": "^1.0.1",
    "bulma": "^0.7.4",
    "next": "^8.0.3",
    "node-sass": "^4.11.0",
    "react": "^16.8.4",
    "react-dom": "^16.8.4"
  },
```

**Comment by matiascaputti** [comment]
Same happening to me, still not fixed on latests versions.

**Comment by roelvan** [comment]
Just had the same error on `"next": "^8.0.4"`.

**Comment by vamshikilari** [comment]
Same issue! Did anyone find a solution?

**Comment by aguilarm** [comment]
Not sure 100% how to repro what I just did to get this error to show up, but stopping my next dev process and re-installing my node dependencies before restarting next resolved for me. Seems like it could be related to not having certain dependencies next needs at runtime, or yanking them out with `npm uninstall` or `yarn remove` while next is still running the dev/webpack process.

I had it happen as a result of a pretty large refactor and haven't been able to repro it however. I imagine most of ya'll could fix this by `rm -rf ./node_modules && npm install` if I'm correct here. Could explain why @davidcraig's case breaks only locally.

**Comment by scottie-schneider** [comment]
Same error with Next.JS Build. @aguilarm 's solution worked, I npm install'd again, restarted server.

**Comment by juliosilvacwb** [comment]
I  stopped my server, running 'npm install' and restart the server, after it the problem disappear.

**Comment by kabyanil** [comment]
I am running nextjs with express as backend. My nextjs runs on localhost:3000 and express runs on localhost:3001. Often times when I change my code, the page doesn't refresh. When I manually refresh, it shows the 404 not found page and **Uncaught ReferenceError: dll is not defined** in the console. I have to manually run **npm run dev** and refresh. This is time-consuming. It would be great if somebody shares a solution.

**Comment by konsumer** [comment]
It was not at all clear to me, from the error message, but in my case I had multiple next apps running in a parent now app, and the issues was `assetPrefix` needs to point to the subdir's location. I tried clearing out things and re-running `npm i`, both at the top-level and in subdirs and it had issues. I ended up finding [#257](https://github.com/zeit/next.js/issues/257) and solved my problem in the sub-app's next.config.js:

```js
module.exports = {
  assetPrefix: '/store/'
}
```

**Comment by IAmNatch** [comment]
In my case, I stopped my server, rm -rf node_modules, npm install, and restarted my server. All was back to normal. 

I believe it was caused when I "npm installed" while running the dev server, as mentioned above.

**Comment by lucasgerard** [comment]
I'm having the same issue, and @aguilarm [solution](https://github.com/zeit/next.js/issues/5702#issuecomment-484256734) to `rm -rf node_modules & yarn install` did not work for me.

Next Version: `9.4`

**Comment by comxd** [comment]
@lucasgerard Use `&&`, not single `&`.

If cleaning the node_module not work and you work at localhost:3000 on multiple projects, you need to clear your browser cache.

A simple way to full clear all caches for a domain/website (Chrome dev tools):

![image](https://user-images.githubusercontent.com/9022239/86066720-4d5a7280-ba73-11ea-9eeb-71994832c989.png)

**Comment by matiascaputti** [comment]
I fixed the problem by forcing service workers to update the site, as they were caching files generating the `dll is not defined` error.

```
if ('serviceWorker' in navigator) {
   window.addEventListener('load', function() {
       navigator.serviceWorker.getRegistrations().then(registrations => {
           for(let registration of registrations) {
               registration.unregister().then(bool => {console.log('unregister: ', bool);});
               }
               window.location.reload();
       });
   });
 }
```

Another approach could be -as @comxd said- unregistering service workers from your browser with the `Unregister service workers` to force them update cached files.

**Comment by DaveKnifeman** [comment]
@comxd Clearing the browser data worked for me! Thanks!

**Comment by lazlojuly** [comment]
I had similar issue and running `rm -rf .next/cache` has resolved it.

**Comment by timneutkens** [comment]
Can you try latest Next.js, the dll plugin was removed

**Comment by KeitelDOG** [comment]
I just experienced it, while setting up Material UI & Co, did not have to delete my Browser Data for localhost

On Chrome Browser:

1. Open "Dev Tools"
2. Select the "Network" tab
3. Check the "Disable Cache"

This will force refresh all the page assets and it should work

**Comment by uqurtosun** [comment]
**Don't use :** npm start
**Do use :** npm run dev

**Comment by balazsorban44** [comment]
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
