### ISSUE TITLE
Build failed on heroku

### ISSUE THREAD

**Issue by sarovin** [zeit/next.js#582]
Hi, i have this error on heroku =>

```
2016-12-31T11:00:51.614558+00:00 app[web.1]: > next build
2016-12-31T11:00:51.614559+00:00 app[web.1]: 
2016-12-31T11:00:59.997024+00:00 heroku[web.1]: State changed from starting to crashed
2016-12-31T11:00:59.985547+00:00 heroku[web.1]: Process exited with status 1
2016-12-31T11:00:59.847766+00:00 app[web.1]: { Error: multi bundles/pages/index.js
2016-12-31T11:00:59.847787+00:00 app[web.1]: Module not found: Error: Can't resolve 'babel-loader' in '/app'
2016-12-31T11:00:59.847788+00:00 app[web.1]: resolve 'babel-loader' in '/app'
2016-12-31T11:00:59.847790+00:00 app[web.1]:   Parsed request is a module
2016-12-31T11:00:59.847790+00:00 app[web.1]:   using description file: /app/package.json (relative path: .)
2016-12-31T11:00:59.847791+00:00 app[web.1]:   after using description file: /app/package.json (relative path: .)
2016-12-31T11:00:59.847792+00:00 app[web.1]:     resolve as module
2016-12-31T11:00:59.847792+00:00 app[web.1]:       looking for modules in /app/node_modules/next/node_modules
2016-12-31T11:00:59.847794+00:00 app[web.1]:         using description file: /app/node_modules/next/package.json (relative path: ./node_modules)
2016-12-31T11:00:59.847794+00:00 app[web.1]:         after using description file: /app/node_modules/next/package.json (relative path: ./node_modules)
2016-12-31T11:00:59.847795+00:00 app[web.1]:           using description file: /app/node_modules/next/package.json (relative path: ./node_modules/babel-loader)
2016-12-31T11:00:59.847796+00:00 app[web.1]:             as directory
2016-12-31T11:00:59.847797+00:00 app[web.1]:               /app/node_modules/next/node_modules/babel-loader doesn't exist
2016-12-31T11:00:59.847797+00:00 app[web.1]:             no extension
2016-12-31T11:00:59.847798+00:00 app[web.1]:               /app/node_modules/next/node_modules/babel-loader doesn't exist
2016-12-31T11:00:59.847799+00:00 app[web.1]:             .js
2016-12-31T11:00:59.847799+00:00 app[web.1]:               /app/node_modules/next/node_modules/babel-loader.js doesn't exist
2016-12-31T11:00:59.847800+00:00 app[web.1]:             .json
2016-12-31T11:00:59.847801+00:00 app[web.1]:               /app/node_modules/next/node_modules/babel-loader.json doesn't exist
2016-12-31T11:00:59.847802+00:00 app[web.1]:       looking for modules in /app/node_modules/next/dist/server/build/loaders
2016-12-31T11:00:59.847803+00:00 app[web.1]:         using description file: /app/node_modules/next/package.json (relative path: ./dist/server/build/loaders)
2016-12-31T11:00:59.847803+00:00 app[web.1]:         after using description file: /app/node_modules/next/package.json (relative path: ./dist/server/build/loaders)
2016-12-31T11:00:59.847804+00:00 app[web.1]:           using description file: /app/node_modules/next/package.json (relative path: ./dist/server/build/loaders/babel-loader)
2016-12-31T11:00:59.847805+00:00 app[web.1]:             as directory
2016-12-31T11:00:59.847806+00:00 app[web.1]:               /app/node_modules/next/dist/server/build/loaders/babel-loader doesn't exist
2016-12-31T11:00:59.847806+00:00 app[web.1]:             no extension
2016-12-31T11:00:59.847807+00:00 app[web.1]:               /app/node_modules/next/dist/server/build/loaders/babel-loader doesn't exist
2016-12-31T11:00:59.847808+00:00 app[web.1]:             .js
2016-12-31T11:00:59.847809+00:00 app[web.1]:               /app/node_modules/next/dist/server/build/loaders/babel-loader.js doesn't exist
2016-12-31T11:00:59.847809+00:00 app[web.1]:             .json
2016-12-31T11:00:59.847810+00:00 app[web.1]:               /app/node_modules/next/dist/server/build/loaders/babel-loader.json doesn't exist
2016-12-31T11:00:59.847811+00:00 app[web.1]: [/app/node_modules/next/node_modules/babel-loader]
2016-12-31T11:00:59.847811+00:00 app[web.1]: [/app/node_modules/next/node_modules/babel-loader]
2016-12-31T11:00:59.847812+00:00 app[web.1]: [/app/node_modules/next/node_modules/babel-loader.js]
2016-12-31T11:00:59.847813+00:00 app[web.1]: [/app/node_modules/next/node_modules/babel-loader.json]
2016-12-31T11:00:59.847813+00:00 app[web.1]: [/app/node_modules/next/dist/server/build/loaders/babel-loader]
2016-12-31T11:00:59.847814+00:00 app[web.1]: [/app/node_modules/next/dist/server/build/loaders/babel-loader]
2016-12-31T11:00:59.847815+00:00 app[web.1]: [/app/node_modules/next/dist/server/build/loaders/babel-loader.js]
2016-12-31T11:00:59.847816+00:00 app[web.1]: [/app/node_modules/next/dist/server/build/loaders/babel-loader.json]
2016-12-31T11:00:59.847816+00:00 app[web.1]:  @ multi bundles/pages/index.js
2016-12-31T11:00:59.847817+00:00 app[web.1]:     at /app/node_modules/next/dist/server/build/index.js:81:21
2016-12-31T11:00:59.847818+00:00 app[web.1]:     at /app/node_modules/webpack/lib/Compiler.js:258:15
2016-12-31T11:00:59.847818+00:00 app[web.1]:     at Compiler.emitRecords (/app/node_modules/webpack/lib/Compiler.js:350:37)
2016-12-31T11:00:59.847819+00:00 app[web.1]:     at /app/node_modules/webpack/lib/Compiler.js:251:12
2016-12-31T11:00:59.847819+00:00 app[web.1]:     at /app/node_modules/webpack/lib/Compiler.js:343:11
2016-12-31T11:00:59.847820+00:00 app[web.1]:     at next (/app/node_modules/tapable/lib/Tapable.js:118:11)
2016-12-31T11:00:59.847820+00:00 app[web.1]:     at Compiler.<anonymous> (/app/node_modules/webpack/lib/performance/SizeLimitsPlugin.js:119:3)
2016-12-31T11:00:59.847821+00:00 app[web.1]:     at Compiler.applyPluginsAsyncSeries1 (/app/node_modules/tapable/lib/Tapable.js:122:13)
2016-12-31T11:00:59.847821+00:00 app[web.1]:     at Compiler.afterEmit (/app/node_modules/webpack/lib/Compiler.js:340:8)
2016-12-31T11:00:59.847822+00:00 app[web.1]:     at Compiler.<anonymous> (/app/node_modules/webpack/lib/Compiler.js:335:14)
2016-12-31T11:00:59.847823+00:00 app[web.1]:   errors: 
2016-12-31T11:00:59.847833+00:00 app[web.1]:    [ 'multi bundles/pages/index.js\nModule not found: Error: Can\'t resolve \'babel-loader\' in \'/app\'\nresolve \'babel-loader\' in \'/app\'\n  Parsed request is a module\n  using description file: /app/package.json (relative path: .)\n  after using description file: /app/package.json (relative path: .)\n    resolve as module\n      looking for modules in /app/node_modules/next/node_modules\n        using description file: /app/node_modules/next/package.json (relative path: ./node_modules)\n        after using description file: /app/node_modules/next/package.json (relative path: ./node_modules)\n          using description file: /app/node_modules/next/package.json (relative path: ./node_modules/babel-loader)\n            as directory\n              /app/node_modules/next/node_modules/babel-loader doesn\'t exist\n            no extension\n              /app/node_modules/next/node_modules/babel-loader doesn\'t exist\n            .js\n              /app/node_modules/next/node_modules/babel-loader.js doesn\'t exist\n            .json\n              /app/node_modules/next/node_modules/babel-loader.json doesn\'t exist\n      looking for modules in /app/node_modules/next/dist/server/build/loaders\n        using description file: /app/node_modules/next/package.json (relative path: ./dist/server/build/loaders)\n        after using description file: /app/node_modules/next/package.json (relative path: ./dist/server/build/loaders)\n          using description file: /app/node_modules/next/package.json (relative path: ./dist/server/build/loaders/babel-loader)\n            as directory\n              /app/node_modules/next/dist/server/build/loaders/babel-loader doesn\'t exist\n            no extension\n              /app/node_modules/next/dist/server/build/loaders/babel-loader doesn\'t exist\n            .js\n              /app/node_modules/next/dist/server/build/loaders/babel-loader.js doesn\'t exist\n            .json\n              /app/node_modules/next/dist/server/build/loaders/babel-loader.json doesn\'t exist\n[/app/node_modules/next/node_modules/babel-loader]\n[/app/node_modules/next/node_modules/babel-loader]\n[/app/node_modules/next/node_modules/babel-loader.js]\n[/app/node_modules/next/node_modules/babel-loader.json]\n[/app/node_modules/next/dist/server/build/loaders/babel-loader]\n[/app/node_modules/next/dist/server/build/loaders/babel-loader]\n[/app/node_modules/next/dist/server/build/loaders/babel-loader.js]\n[/app/node_modules/next/dist/server/build/loaders/babel-loader.json]\n @ multi bundles/pages/index.js',
2016-12-31T11:00:59.847836+00:00 app[web.1]:      'multi bundles/pages/progetto.js\nModule not found: Error: Can\'t resolve \'babel-loader\' in \'/app\'\nresolve \'babel-loader\' in \'/app\'\n  Parsed request is a module\n  using description file: /app/package.json (relative path: .)\n  after using description file: /app/package.json (relative path: .)\n    resolve as module\n      looking for modules in /app/node_modules/next/node_modules\n        using description file: /app/node_modules/next/package.json (relative path: ./node_modules)\n        after using description file: /app/node_modules/next/package.json (relative path: ./node_modules)\n          using description file: /app/node_modules/next/package.json (relative path: ./node_modules/babel-loader)\n            as directory\n              /app/node_modules/next/node_modules/babel-loader doesn\'t exist\n            no extension\n              /app/node_modules/next/node_modules/babel-loader doesn\'t exist\n            .js\n              /app/node_modules/next/node_modules/babel-loader.js doesn\'t exist\n            .json\n              /app/node_modules/next/node_modules/babel-loader.json doesn\'t exist\n      looking for modules in /app/node_modules/next/dist/server/build/loaders\n        using description file: /app/node_modules/next/package.json (relative path: ./dist/server/build/loaders)\n        after using description file: /app/node_modules/next/package.json (relative path: ./dist/server/build/loaders)\n          using description file: /app/node_modules/next/package.json (relative path: ./dist/server/build/loaders/babel-loader)\n            as directory\n              /app/node_modules/next/dist/server/build/loaders/babel-loader doesn\'t exist\n            no extension\n              /app/node_modules/next/dist/server/build/loaders/babel-loader doesn\'t exist\n            .js\n              /app/node_modules/next/dist/server/build/loaders/babel-loader.js doesn\'t exist\n            .json\n              /app/node_modules/next/dist/server/build/loaders/babel-loader.json doesn\'t exist\n[/app/node_modules/next/node_modules/babel-loader]\n[/app/node_modules/next/node_modules/babel-loader]\n[/app/node_modules/next/node_modules/babel-loader.js]\n[/app/node_modules/next/node_modules/babel-loader.json]\n[/app/node_modules/next/dist/server/build/loaders/babel-loader]\n[/app/node_modules/next/dist/server/build/loaders/babel-loader]\n[/app/node_modules/next/dist/server/build/loaders/babel-loader.js]\n[/app/node_modules/next/dist/server/build/loaders/babel-loader.json]\n @ multi bundles/pages/progetto.js',
2016-12-31T11:00:59.847838+00:00 app[web.1]:      'multi bundles/pages/_error.js\nModule not found: Error: Can\'t resolve \'babel-loader\' in \'/app\'\nresolve \'babel-loader\' in \'/app\'\n  Parsed request is a module\n  using description file: /app/package.json (relative path: .)\n  after using description file: /app/package.json (relative path: .)\n    resolve as module\n      looking for modules in /app/node_modules/next/node_modules\n        using description file: /app/node_modules/next/package.json (relative path: ./node_modules)\n        after using description file: /app/node_modules/next/package.json (relative path: ./node_modules)\n          using description file: /app/node_modules/next/package.json (relative path: ./node_modules/babel-loader)\n            as directory\n              /app/node_modules/next/node_modules/babel-loader doesn\'t exist\n            no extension\n              /app/node_modules/next/node_modules/babel-loader doesn\'t exist\n            .js\n              /app/node_modules/next/node_modules/babel-loader.js doesn\'t exist\n            .json\n              /app/node_modules/next/node_modules/babel-loader.json doesn\'t exist\n      looking for modules in /app/node_modules/next/dist/server/build/loaders\n        using description file: /app/node_modules/next/package.json (relative path: ./dist/server/build/loaders)\n        after using description file: /app/node_modules/next/package.json (relative path: ./dist/server/build/loaders)\n          using description file: /app/node_modules/next/package.json (relative path: ./dist/server/build/loaders/babel-loader)\n            as directory\n              /app/node_modules/next/dist/server/build/loaders/babel-loader doesn\'t exist\n            no extension\n              /app/node_modules/next/dist/server/build/loaders/babel-loader doesn\'t exist\n            .js\n              /app/node_modules/next/dist/server/build/loaders/babel-loader.js doesn\'t exist\n            .json\n              /app/node_modules/next/dist/server/build/loaders/babel-loader.json doesn\'t exist\n[/app/node_modules/next/node_modules/babel-loader]\n[/app/node_modules/next/node_modules/babel-loader]\n[/app/node_modules/next/node_modules/babel-loader.js]\n[/app/node_modules/next/node_modules/babel-loader.json]\n[/app/node_modules/next/dist/server/build/loaders/babel-loader]\n[/app/node_modules/next/dist/server/build/loaders/babel-loader]\n[/app/node_modules/next/dist/server/build/loaders/babel-loader.js]\n[/app/node_modules/next/dist/server/build/loaders/babel-loader.json]\n @ multi bundles/pages/_error.js',
2016-12-31T11:00:59.847840+00:00 app[web.1]:      'multi bundles/pages/_error-debug.js\nModule not found: Error: Can\'t resolve \'babel-loader\' in \'/app\'\nresolve \'babel-loader\' in \'/app\'\n  Parsed request is a module\n  using description file: /app/package.json (relative path: .)\n  after using description file: /app/package.json (relative path: .)\n    resolve as module\n      looking for modules in /app/node_modules/next/node_modules\n        using description file: /app/node_modules/next/package.json (relative path: ./node_modules)\n        after using description file: /app/node_modules/next/package.json (relative path: ./node_modules)\n          using description file: /app/node_modules/next/package.json (relative path: ./node_modules/babel-loader)\n            as directory\n              /app/node_modules/next/node_modules/babel-loader doesn\'t exist\n            no extension\n              /app/node_modules/next/node_modules/babel-loader doesn\'t exist\n            .js\n              /app/node_modules/next/node_modules/babel-loader.js doesn\'t exist\n            .json\n              /app/node_modules/next/node_modules/babel-loader.json doesn\'t exist\n      looking for modules in /app/node_modules/next/dist/server/build/loaders\n        using description file: /app/node_modules/next/package.json (relative path: ./dist/server/build/loaders)\n        after using description file: /app/node_modules/next/package.json (relative path: ./dist/server/build/loaders)\n          using description file: /app/node_modules/next/package.json (relative path: ./dist/server/build/loaders/babel-loader)\n            as directory\n              /app/node_modules/next/dist/server/build/loaders/babel-loader doesn\'t exist\n            no extension\n              /app/node_modules/next/dist/server/build/loaders/babel-loader doesn\'t exist\n            .js\n              /app/node_modules/next/dist/server/build/loaders/babel-loader.js doesn\'t exist\n            .json\n              /app/node_modules/next/dist/server/build/loaders/babel-loader.json doesn\'t exist\n[/app/node_modules/next/node_modules/babel-loader]\n[/app/node_modules/next/node_modules/babel-loader]\n[/app/node_modules/next/node_modules/babel-loader.js]\n[/app/node_modules/next/node_modules/babel-loader.json]\n[/app/node_modules/next/dist/server/build/loaders/babel-loader]\n[/app/node_modules/next/dist/server/build/loaders/babel-loader]\n[/app/node_modules/next/dist/server/build/loaders/babel-loader.js]\n[/app/node_modules/next/dist/server/build/loaders/babel-loader.json]\n @ multi bundles/pages/_error-debug.js',
2016-12-31T11:00:59.847842+00:00 app[web.1]:      'multi bundles/pages/_document.js\nModule not found: Error: Can\'t resolve \'babel-loader\' in \'/app\'\nresolve \'babel-loader\' in \'/app\'\n  Parsed request is a module\n  using description file: /app/package.json (relative path: .)\n  after using description file: /app/package.json (relative path: .)\n    resolve as module\n      looking for modules in /app/node_modules/next/node_modules\n        using description file: /app/node_modules/next/package.json (relative path: ./node_modules)\n        after using description file: /app/node_modules/next/package.json (relative path: ./node_modules)\n          using description file: /app/node_modules/next/package.json (relative path: ./node_modules/babel-loader)\n            as directory\n              /app/node_modules/next/node_modules/babel-loader doesn\'t exist\n            no extension\n              /app/node_modules/next/node_modules/babel-loader doesn\'t exist\n            .js\n              /app/node_modules/next/node_modules/babel-loader.js doesn\'t exist\n            .json\n              /app/node_modules/next/node_modules/babel-loader.json doesn\'t exist\n      looking for modules in /app/node_modules/next/dist/server/build/loaders\n        using description file: /app/node_modules/next/package.json (relative path: ./dist/server/build/loaders)\n        after using description file: /app/node_modules/next/package.json (relative path: ./dist/server/build/loaders)\n          using description file: /app/node_modules/next/package.json (relative path: ./dist/server/build/loaders/babel-loader)\n            as directory\n              /app/node_modules/next/dist/server/build/loaders/babel-loader doesn\'t exist\n            no extension\n              /app/node_modules/next/dist/server/build/loaders/babel-loader doesn\'t exist\n            .js\n              /app/node_modules/next/dist/server/build/loaders/babel-loader.js doesn\'t exist\n            .json\n              /app/node_modules/next/dist/server/build/loaders/babel-loader.json doesn\'t exist\n[/app/node_modules/next/node_modules/babel-loader]\n[/app/node_modules/next/node_modules/babel-loader]\n[/app/node_modules/next/node_modules/babel-loader.js]\n[/app/node_modules/next/node_modules/babel-loader.json]\n[/app/node_modules/next/dist/server/build/loaders/babel-loader]\n[/app/node_modules/next/dist/server/build/loaders/babel-loader]\n[/app/node_modules/next/dist/server/build/loaders/babel-loader.js]\n[/app/node_modules/next/dist/server/build/loaders/babel-loader.json]\n @ multi bundles/pages/_document.js' ],
```

My package.json is like this => 

```
{
  "name": "test",
  "version": "0.0.1",
  "private": true,
  "main": "index.js",
  "scripts": {
    "dev": "next",
    "prestart": "next build",
    "start": "next start -p ${PORT}"
  },
  "dependencies": {
    "inline-style-prefixer": "^2.0.5",
    "next": "latest",
    "react": "^15.4.1",
    "react-bootstrap": "^0.30.7",
    "react-dom": "^15.4.1",
    "react-motion": "^0.4.7",
    "react-redux": "^5.0.1",
    "redux": "^3.6.0"
  },
  "devDependencies": {
    "babel-eslint": "^7.0.0",
    "eslint": "^3.7.1",
    "eslint-config-airbnb": "^12.0.0",
    "eslint-plugin-import": "^1.16.0",
    "eslint-plugin-jsx-a11y": "^2.2.3",
    "eslint-plugin-react": "^6.4.0"
  }
}

```

**Comment by jamesmcallister** [comment]
Change `"next": "lastest",` to  `"next": "2.0.0-beta.5",` as the latest `"beta.6"` has a similar problem.

See [https://github.com/zeit/next.js/issues/581](581)

I could be wrong.

**Comment by sarovin** [comment]
Thanks @jamesmcallister

**Comment by arunoda** [comment]
Thanks @jamesmcallister for the reference.
We'll land a new release soon with the fix.

Let's track this via #581
