### ISSUE TITLE
Error: Cannot find module './runtime'

### ISSUE THREAD

**Issue by Enalmada** [zeit/next.js#5868]
When trying to upgrade from 7.0.2 to v7.0.2-canary.42 I can build ok but get the following error when hitting the first page:
```
{ Error: Cannot find module './runtime'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:580:15)
    at Function.Module._load (internal/modules/cjs/loader.js:506:25)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.uqG8 (C:\Users\Adam\code\public\next-reason-boilerplate\.next\server\static\pG0J7KxMZx_VHzleY1EvL\pages\_app.js:1136:18)
    at __webpack_require__ (C:\Users\Adam\code\public\next-reason-boilerplate\.next\server\static\pG0J7KxMZx_VHzleY1EvL\pages\_app.js:23:31)
    at Object.QcLC (C:\Users\Adam\code\public\next-reason-boilerplate\.next\server\static\pG0J7KxMZx_VHzleY1EvL\pages\_app.js:569:18)
    at __webpack_require__ (C:\Users\Adam\code\public\next-reason-boilerplate\.next\server\static\pG0J7KxMZx_VHzleY1EvL\pages\_app.js:23:31)
    at Object.ln6h (C:\Users\Adam\code\public\next-reason-boilerplate\.next\server\static\pG0J7KxMZx_VHzleY1EvL\pages\_app.js:790:18)
    at __webpack_require__ (C:\Users\Adam\code\public\next-reason-boilerplate\.next\server\static\pG0J7KxMZx_VHzleY1EvL\pages\_app.js:23:31)
    at Module.B5Ud (C:\Users\Adam\code\public\next-reason-boilerplate\.next\server\static\pG0J7KxMZx_VHzleY1EvL\pages\_app.js:139:19)
    at __webpack_require__ (C:\Users\Adam\code\public\next-reason-boilerplate\.next\server\static\pG0J7KxMZx_VHzleY1EvL\pages\_app.js:23:31)
    at Object.0 (C:\Users\Adam\code\public\next-reason-boilerplate\.next\server\static\pG0J7KxMZx_VHzleY1EvL\pages\_app.js:106:18)
    at __webpack_require__ (C:\Users\Adam\code\public\next-reason-boilerplate\.next\server\static\pG0J7KxMZx_VHzleY1EvL\pages\_app.js:23:31)
    at C:\Users\Adam\code\public\next-reason-boilerplate\.next\server\static\pG0J7KxMZx_VHzleY1EvL\pages\_app.js:91:18
    at Object.<anonymous> (C:\Users\Adam\code\public\next-reason-boilerplate\.next\server\static\pG0J7KxMZx_VHzleY1EvL\pages\_app.js:94:10) code: 'MODULE_NOT_FOUND' }
```
Error happens in dev and production setting.  Is this a known issue in canary.42 or is there something my codebase might be doing to cause it?  

## System information
 - OS: Windows 10
 - Version of Next.js: v7.0.2-canary.42

UPDATE:
I believe I have traced the problem to module `babel-plugin-react-intl`.  Problem seem to go away when I remove that module and these lines:
https://github.com/zeit/next.js/blob/master/examples/with-react-intl/.babelrc#L5-L18

**Comment by timneutkens** [comment]
Most likely not related to Next.js, we didn't even upgrade Babel in the canary releases as far as I can remember. The integration tests on Next.js are passing between stable and canary (canary has even more tests). It seems like you're importing a `runtime` module that does not exist in your app or something. Maybe it's related to babel caching? Try `rm -rf node_modules/.cache`.

**Comment by Enalmada** [comment]
@timneutkens Thanks for your feedback.  The `with-react-intl` example works in canary so there indeed must be something more going on.  Removing node_modules directory also seems to be required to .cache may indeed factor into this.   When I have more time I will try just clearing the cache rather than whole directory.  Will close ticket since I can live without the `babel-plugin-react-intl` functionality and will reopen if anyone else hits this issue as they upgrade.

**Comment by noiboi** [comment]
Experiencing the same issue, however even deleting ```.babelrc``` and ```babel-plugin-react-intl``` didn't help in my case.

**Comment by seawatts** [comment]
I'm still running into this issue. Cleaning cache and node_modules didn't help

**Comment by balupton** [comment]
@seawatts are you using yarn or npm? I had to switch to yarn for it to work. Also if you are using yarn, try switch to the canary tag for all zeit packages.

**Comment by seawatts** [comment]
Using npm. I haven't tried to upgrade other next dependencies. I just
reverted back to 7 for now

**Comment by NathanielHill** [comment]
FWIW I've also run into this in an unrelated project. I believe it's due to `@babel/plugin-tranform-runtime` injecting that require statement, but then `@babel/runtime` is not handling it. It for sure has something to do with both those modules.

I was trying to transpile some React components using async/await with Babel 7. I ended up removing those two packages completely and requiring `regenerator-runtime/runtime.js` in the main entry point.
