### ISSUE TITLE
Error: Callback was already called. when using `npm run dev` from docker on windows

### ISSUE THREAD

**Issue by d3sandoval** [zeit/next.js#5872]
# Bug report
Whenever running `docker-compose up` on a windows machine whose volumes are mounted, I get this error.
## Describe the bug
I'm not sure if this is a problem with Next since it might be the underlying webpack its using. I recently starting working on a windows machine and found i cannot mount my directory without this issue occuring.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:
1. Create a Dockerfile for next (mine is in /ui):
```
FROM node:10

WORKDIR /usr/ui

COPY package.json .
RUN npm install --quiet

COPY . .

RUN npm run build

CMD npm start
```
2. In docker-compose, refer to that dockerfile and mount the directory
```
version: '3.1'
services:
  ui:
    image: us.gcr.io/anymessage-219921/ui:latest
    build: ./ui
    command: npm run dev
    volumes:
      - ./ui:/usr/ui/
      - /usr/ui/node_modules
    ports:
      - "3000:3000"
    env_file: .env
```
3. Run docker-compose up
```
ui_1          | [9:31:52 PM] Compiling server
ui_1          | [9:31:53 PM] Compiled server in 2s
ui_1          | [9:31:53 PM] Compiling server
ui_1          | /usr/ui/node_modules/neo-async/async.js:14
ui_1          |     throw new Error('Callback was already called.');
ui_1          |     ^
ui_1          |
ui_1          | Error: Callback was already called.
ui_1          |     at throwError (/usr/ui/node_modules/neo-async/async.js:14:11)
ui_1          |     at /usr/ui/node_modules/neo-async/async.js:2813:7
ui_1          |     at process._tickCallback (internal/process/next_tick.js:61:11)
ui_1          | npm ERR! code ELIFECYCLE
ui_1          | npm ERR! errno 1
ui_1          | npm ERR! @anymessage/ui@0.0.1 dev:80: `next -p 80`
ui_1          | npm ERR! Exit status 1
ui_1          | npm ERR!
ui_1          | npm ERR! Failed at the @anymessage/ui@0.0.1 dev:80 script.
ui_1          | npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
ui_1          |
ui_1          | npm ERR! A complete log of this run can be found in:
ui_1          | npm ERR!     /root/.npm/_logs/2018-12-12T21_31_54_001Z-debug.log
anymessage_ui_1 exited with code 1
```

## Expected behavior
available on localhost:3000

## Screenshots
N/A

## System information
 - OS: Windows
 - Browser (if applies) N/A
 - Version of Next.js: 7.0.2

**Comment by timneutkens** [comment]
`#webpack#watchpack#neo-async` sounds like an issue with watchpack (webpack's file watcher) 🤔 I'm pretty sure we can't really do anything with this on the Next.js side.

**Comment by d3sandoval** [comment]
Thanks for pointing me in the right direction @timneutkens I'll cross post in those repos and see if I can get further. For now I'm just running `npm run dev` locally and everything is working just fine.
