### ISSUE TITLE
These dependencies were not found in node_modules:

### ISSUE THREAD

**Issue by SerkanDayicik** [zeit/next.js#589]
im using Beta.7 and 8 try but not fixed me.

* react-hot-loader/patch
* webpack-hot-middleware/client?overlay=false&reload=true
* babel-runtime/helpers/toConsumableArray
* babel-runtime/core-js/get-iterator
* babel-runtime/core-js/object/keys
* react
* react-dom
* babel-runtime/core-js/object/define-property
* react
* babel-runtime/core-js/get-iterator
* babel-runtime/core-js/object/keys
* react-hot-loader
* babel-runtime/core-js/promise
* babel-runtime/helpers/classCallCheck
* babel-runtime/helpers/classCallCheck
* babel-runtime/helpers/createClass
* babel-runtime/helpers/createClass
* babel-runtime/helpers/extends
* babel-runtime/core-js/object/get-prototype-of
* babel-runtime/helpers/possibleConstructorReturn
* babel-runtime/helpers/inherits
* babel-runtime/helpers/slicedToArray
* babel-runtime/core-js/object/entries
* glamor
* babel-runtime/core-js/promise
* babel-runtime/helpers/extends
* babel-runtime/helpers/classCallCheck
* babel-runtime/helpers/createClass
* babel-runtime/helpers/possibleConstructorReturn
* babel-runtime/helpers/inherits
* babel-runtime/core-js/object/get-prototype-of
* babel-runtime/regenerator
* babel-runtime/helpers/asyncToGenerator
* babel-runtime/core-js/set
* babel-runtime/helpers/defineProperty
* babel-runtime/core-js/object/assign

Missed Packages

Win 10
Node v6.9.2
NPM 3.10.9
still using yarn but no luck :(
yarn version v0.18.1

Try next 2.0.0.beta8

**Comment by rauchg** [comment]
Can you supply a github repo / gist with a `package.json` and minimal example that reproduces this?

**Comment by SerkanDayicik** [comment]
i'm using next example project not changing any thing

**Comment by SerkanDayicik** [comment]
im try fresh folder name and fresh install ssr-cache example now server started but if open browser and connect dev server return :
SyntaxError: Unexpected token m in JSON at position 0

this error
SyntaxError: Unexpected token m in JSON at position 0
    at Object.parse (native)
    at _callee$ (C:\Users\BioFr\Desktop\ssr-caching\node_modules\next\dist\server\read-page.js:48:32)
    at tryCatch (C:\Users\BioFr\Desktop\ssr-caching\node_modules\regenerator-runtime\runtime.js:64:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (C:\Users\BioFr\Desktop\ssr-caching\node_modules\regenerator-runtime\runtime.js:355:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (C:\Users\BioFr\Desktop\ssr-caching\node_modules\regenerator-runtime\runtime.js:116:21)
    at step (C:\Users\BioFr\Desktop\ssr-caching\node_modules\babel-runtime\helpers\asyncToGenerator.js:17:30)
    at C:\Users\BioFr\Desktop\ssr-caching\node_modules\babel-runtime\helpers\asyncToGenerator.js:28:13
SyntaxError: Unexpected token m in JSON at position 0
    at Object.parse (native)
    at _callee$ (C:\Users\BioFr\Desktop\ssr-caching\node_modules\next\dist\server\read-page.js:48:32)
    at tryCatch (C:\Users\BioFr\Desktop\ssr-caching\node_modules\regenerator-runtime\runtime.js:64:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (C:\Users\BioFr\Desktop\ssr-caching\node_modules\regenerator-runtime\runtime.js:355:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (C:\Users\BioFr\Desktop\ssr-caching\node_modules\regenerator-runtime\runtime.js:116:21)
    at step (C:\Users\BioFr\Desktop\ssr-caching\node_modules\babel-runtime\helpers\asyncToGenerator.js:17:30)
    at C:\Users\BioFr\Desktop\ssr-caching\node_modules\babel-runtime\helpers\asyncToGenerator.js:28:13
SyntaxError: Unexpected token m in JSON at position 0
    at Object.parse (native)
    at _callee$ (C:\Users\BioFr\Desktop\ssr-caching\node_modules\next\dist\server\read-page.js:48:32)
    at tryCatch (C:\Users\BioFr\Desktop\ssr-caching\node_modules\regenerator-runtime\runtime.js:64:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (C:\Users\BioFr\Desktop\ssr-caching\node_modules\regenerator-runtime\runtime.js:355:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (C:\Users\BioFr\Desktop\ssr-caching\node_modules\regenerator-runtime\runtime.js:116:21)
    at step (C:\Users\BioFr\Desktop\ssr-caching\node_modules\babel-runtime\helpers\asyncToGenerator.js:17:30)
    at C:\Users\BioFr\Desktop\ssr-caching\node_modules\babel-runtime\helpers\asyncToGenerator.js:28:13
(node:4368) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): SyntaxError: Unexpected token m in JSON at position 0
SyntaxError: Unexpected token m in JSON at position 0
    at Object.parse (native)
    at _callee$ (C:\Users\BioFr\Desktop\ssr-caching\node_modules\next\dist\server\read-page.js:48:32)
    at tryCatch (C:\Users\BioFr\Desktop\ssr-caching\node_modules\regenerator-runtime\runtime.js:64:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (C:\Users\BioFr\Desktop\ssr-caching\node_modules\regenerator-runtime\runtime.js:355:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (C:\Users\BioFr\Desktop\ssr-caching\node_modules\regenerator-runtime\runtime.js:116:21)
    at step (C:\Users\BioFr\Desktop\ssr-caching\node_modules\babel-runtime\helpers\asyncToGenerator.js:17:30)
    at C:\Users\BioFr\Desktop\ssr-caching\node_modules\babel-runtime\helpers\asyncToGenerator.js:28:13
SyntaxError: Unexpected token m in JSON at position 0
    at Object.parse (native)
    at _callee$ (C:\Users\BioFr\Desktop\ssr-caching\node_modules\next\dist\server\read-page.js:48:32)
    at tryCatch (C:\Users\BioFr\Desktop\ssr-caching\node_modules\regenerator-runtime\runtime.js:64:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (C:\Users\BioFr\Desktop\ssr-caching\node_modules\regenerator-runtime\runtime.js:355:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (C:\Users\BioFr\Desktop\ssr-caching\node_modules\regenerator-runtime\runtime.js:116:21)
    at step (C:\Users\BioFr\Desktop\ssr-caching\node_modules\babel-runtime\helpers\asyncToGenerator.js:17:30)
    at C:\Users\BioFr\Desktop\ssr-caching\node_modules\babel-runtime\helpers\asyncToGenerator.js:28:13
SyntaxError: Unexpected token m in JSON at position 0
    at Object.parse (native)
    at _callee$ (C:\Users\BioFr\Desktop\ssr-caching\node_modules\next\dist\server\read-page.js:48:32)
    at tryCatch (C:\Users\BioFr\Desktop\ssr-caching\node_modules\regenerator-runtime\runtime.js:64:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (C:\Users\BioFr\Desktop\ssr-caching\node_modules\regenerator-runtime\runtime.js:355:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (C:\Users\BioFr\Desktop\ssr-caching\node_modules\regenerator-runtime\runtime.js:116:21)
    at step (C:\Users\BioFr\Desktop\ssr-caching\node_modules\babel-runtime\helpers\asyncToGenerator.js:17:30)
    at C:\Users\BioFr\Desktop\ssr-caching\node_modules\babel-runtime\helpers\asyncToGenerator.js:28:13
(node:4368) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): SyntaxError: Unexpected token m in JSON at position 0

**Comment by arunoda** [comment]
@SerkanDayicik if you are using yarn try `yarn upgrade` too.

**Comment by ryancole** [comment]
This is happening to me as well, all of a sudden. I reverted back to `beta.6`, etc, because I knew those worked previously but now I'm getting these errors on those versions too.

Here's my repo. It's not prepared as a minimal example, but I do believe you should be able to clone, npm install and then npm start to see the error. Nothing platform specific, afaik.

https://github.com/ryancole/league/tree/nextjs/packages/league-client

**Comment by ryancole** [comment]
I just wanted to note the actual error message that I'm receiving ...

```
 ERROR  Failed to compile with 42 errors

These dependencies were not found in node_modules:

* ./pages/index.js?entry
* ./pages/team/detail.js?entry
* ./pages/team/index.js?entry
* C:\Users\Ryan\Projects\league\packages\league-client\node_modules\next\dist\pages\_error.js?entry
* C:\Users\Ryan\Projects\league\packages\league-client\node_modules\next\dist\pages\_error-debug.js?entry
* C:\Users\Ryan\Projects\league\packages\league-client\node_modules\next\dist\pages\_document.js?entry
* react-hot-loader/patch
* webpack-hot-middleware/client?overlay=false&reload=true
* babel-runtime/helpers/toConsumableArray
* babel-runtime/core-js/get-iterator
* babel-runtime/core-js/object/keys
* react
* react-dom
* babel-runtime/core-js/object/define-property
* babel-runtime/core-js/get-iterator
* babel-runtime/core-js/object/keys
* react
* react-hot-loader
* babel-runtime/core-js/promise
* babel-runtime/helpers/classCallCheck
* babel-runtime/helpers/classCallCheck
* babel-runtime/helpers/createClass
* babel-runtime/helpers/createClass
* babel-runtime/helpers/slicedToArray
* babel-runtime/core-js/object/entries
* glamor
* babel-runtime/helpers/extends
* babel-runtime/core-js/object/get-prototype-of
* babel-runtime/helpers/possibleConstructorReturn
* babel-runtime/helpers/inherits
* babel-runtime/core-js/promise
* babel-runtime/helpers/extends
* babel-runtime/helpers/classCallCheck
* babel-runtime/helpers/createClass
* babel-runtime/helpers/possibleConstructorReturn
* babel-runtime/helpers/inherits
* babel-runtime/core-js/object/get-prototype-of
* babel-runtime/regenerator
* babel-runtime/helpers/asyncToGenerator
* babel-runtime/core-js/set
* babel-runtime/helpers/defineProperty
* babel-runtime/core-js/object/assign

Did you forget to run npm install --save for them?
```

**Comment by arunoda** [comment]
One of the issue is your node_modules directory is not inside the `src`. 
We assumed that. But that's wrong.

I'll work on a fix today.

**Comment by ryancole** [comment]
@arunoda I'm super confused, though. I've had this project structure for a few days now. Everything worked as recently as a day or two ago. I literally changed nothing, except for nuking `node_modules` and re-installing. Does this still jive with your assessment?

**Comment by arunoda** [comment]
@ryancole We changed something :)
I'll work on a fix.

**Comment by ryancole** [comment]
no worries! thanks for your efforts.

**Comment by nkzawa** [comment]
#592 should fix the issue.

**Comment by ryancole** [comment]
@nkzawa It does appear to fix the issue, thanks! On Windows 10, this patch does indeed fix the error reported by OP, on my end.

As noted in #593, though, many of the tests are failing and `npm link` shows an over-all fail.

**Comment by mnpenner** [comment]
Was this fix tagged? What do I have to install to get the fix?
