### ISSUE TITLE
Cannot read property 'replaceState' of undefined

### ISSUE THREAD

**Issue by arherzf8er** [zeit/next.js#5916]
# Bug report

## Describe the bug

Got 502 on my hosted docker app while trying to open a page by a direct link.
Locally got `Warning: window.history is not available.` in the console (server-side).
Dynamic routes are provided by next-routes with pages like `/items/:hash/details`.

```
TypeError: Cannot read property 'replaceState' of undefined
    at process.internalTickCallback (internal/process/next_tick.js:77:7)
    at _next (/usr/src/app/node_modules/@babel/runtime-corejs2/helpers/asyncToGenerator.js:27:9)
    at asyncGeneratorStep (/usr/src/app/node_modules/@babel/runtime-corejs2/helpers/asyncToGenerator.js:5:24)
    at Generator.prototype.(anonymous function) [as next] (/usr/src/app/node_modules/@babel/runtime-corejs2/node_modules/regenerator-runtime/runtime.js:114:21)
    at Generator.invoke [as _invoke] (/usr/src/app/node_modules/@babel/runtime-corejs2/node_modules/regenerator-runtime/runtime.js:288:22)
    at tryCatch (/usr/src/app/node_modules/@babel/runtime-corejs2/node_modules/regenerator-runtime/runtime.js:62:40)
    at _callee3$ (/usr/src/app/node_modules/next/dist/server/render.js:256:22)
    at new Router (/usr/src/app/node_modules/next/dist/lib/router/router.js:136:12)
    at Router.changeState (/usr/src/app/node_modules/next/dist/lib/router/router.js:383:23)
```

## To Reproduce

App crashes only if one attempts to open a page by its direct url.
If one navigates to the page using `Link`, then it acts normal.

## Screenshots

![screenshot from 2018-12-20 11-39-49](https://user-images.githubusercontent.com/29209372/50269509-371c3100-0450-11e9-88b8-c0ade71baad9.png)

## System information
 - OS: Ubuntu 18.04
 - Browser: latest Chrome
 - Version of Next.js: 7.0.2

## Additional context

Also using `next/head` at the page if this might be somehow relevant.

**Comment by arherzf8er** [comment]
Found #2067 but wasn't able to apply it to my situation, the whole thing goes in componentDidMount. 
@jagreene Could you please give some hints on how you managed to solve it?

**Comment by timneutkens** [comment]
Please follow the whole issue template and provide a clear and concise reproduction. It's close to impossible to help with just a stacktrace from your application.

**Comment by timneutkens** [comment]
Like I said before:

> Please provide a clear and concise reproduction. It's close to impossible to help with just a stacktrace from your application.

It's close to impossible to help you based on one screenshot, without providing *any* code from your application to reproduce the issue.

I'm assuming you're doing something wrong with `Router.push()` / `Router.replace()` where you're calling it on the server side instead of on the client side. Maybe you're injecting the router using `withRouter`? Please provide some code as it sounds like we can throw an error on the server side when trying to do what you're doing.
