### ISSUE TITLE
Many tests failing

### ISSUE THREAD

**Issue by ryancole** [zeit/next.js#593]
Just a head up. I've cloned the [current repo](https://github.com/zeit/next.js/commit/f2483cfe1c7d35386fc7e68e1f2e010c48375152) and run `npm install`. A lot of tests fail with the same error ...

```
 FAIL  .\integration.test.js (17.725s)
  ● integration tests › renders a stateless component

    SyntaxError: Unexpected token m in JSON at position 0
        at JSON.parse (<anonymous>)

      at _callee$ (..\dist\server\read-page.js:48:32)
      at tryCatch (..\node_modules\regenerator-runtime\runtime.js:64:40)
      at Generator.invoke [as _invoke] (..\node_modules\regenerator-runtime\runtime.js:355:22)
      at Generator.prototype.(anonymous function) [as next] (..\node_modules\regenerator-runtime\runtime.js:116:21)
      at step (..\node_modules\babel-runtime\helpers\asyncToGenerator.js:17:30)
      at ..\node_modules\babel-runtime\helpers\asyncToGenerator.js:28:13

  ● integration tests › renders a stateful component

    SyntaxError: Unexpected token m in JSON at position 0
        at JSON.parse (<anonymous>)

      at _callee$ (..\dist\server\read-page.js:48:32)
      at tryCatch (..\node_modules\regenerator-runtime\runtime.js:64:40)
      at Generator.invoke [as _invoke] (..\node_modules\regenerator-runtime\runtime.js:355:22)
      at Generator.prototype.(anonymous function) [as next] (..\node_modules\regenerator-runtime\runtime.js:116:21)
      at step (..\node_modules\babel-runtime\helpers\asyncToGenerator.js:17:30)
      at ..\node_modules\babel-runtime\helpers\asyncToGenerator.js:28:13
```

And so on.

**Comment by ryancole** [comment]
I know this is closed, but this seems related to #597.
