### ISSUE TITLE
TypeError deploying to Zeit v2.0 with WithApolloClient _app.js and Emotion 10

### ISSUE THREAD

**Issue by tcerdaITBA** [zeit/next.js#5972]
# Examples bug report

## Example Name
[with-emotion](https://github.com/zeit/next.js/tree/canary/examples/with-emotion)

## Describe the bug
Deploying to Zeit Now 2.0 with custom `_app.js` and Emotion 10 produces an 500 error originated from the following TypeError recovered from the Zeit deployment logs:

```
TypeError: Cannot read property 'registered' of undefined
    at Object.children (/var/task/.next/server/static/RolwaMefjPFTL~9yHWUpF/pages/index.js:6:4638)
    at ReactDOMServerRenderer.render (/var/task/node_modules/react-dom/cjs/react-dom-server.node.development.js:3292:55)
    at ReactDOMServerRenderer.read (/var/task/node_modules/react-dom/cjs/react-dom-server.node.development.js:3059:29)
    at renderToString (/var/task/node_modules/react-dom/cjs/react-dom-server.node.development.js:3526:27)
    at render (/var/task/node_modules/next-server/dist/server/render.js:45:16)
    at renderPage (/var/task/node_modules/next-server/dist/server/render.js:112:16)
    at Function.value (/var/task/.next/server/static/RolwaMefjPFTL~9yHWUpF/pages/_document.js:1:20266)
    at Object.loadGetInitialProps (/var/task/node_modules/next-server/dist/lib/utils.js:44:35)
    at Object.renderToHTML (/var/task/node_modules/next-server/dist/server/render.js:115:36)
    at <anonymous>
```

This only occurs with Zeit Now 2 and when wrapping `_app.js` with the `WithApolloClient` HOC taken from [with-apollo example](https://github.com/zeit/next.js/tree/canary/examples/with-apollo). Either removing Emotion's components or removing the HOC from `_app.js` or deploying to Zeit Now 1 produces a successful deploy.

## To Reproduce
1. `npx create-next-app --example with-emotion with-emotion-app`
2. `cd with-emotion-app`
3. `yarn install apollo-boost react-apollo graphql isomorphic-unfetch`
4. Copy `lib` directory and `pages/_app.js` from [with-apollo example](https://github.com/zeit/next.js/tree/canary/examples/with-apollo)
5. Write `now.json`:
```
{
  "version": 2,
  "builds": [
    { "src": "package.json", "use": "@now/next" }
  ]
}
```
6. Deploy with `now`

## Expected behavior
https://with-emotion-app-annixbe92.now.sh/

## Actual behavior
https://with-emotion-app-a49lrf5ni.now.sh/

## System information
 - OS: macOS
 - Browser: any since the error is originated the server

**Comment by tcerdaITBA** [comment]
Bug seems to be fixed using [next-with-apollo](https://github.com/lfades/next-with-apollo) dependency instead of using the example's Apollo implementation.

**Comment by tcerdaITBA** [comment]
Actually bug it is not fixed; the only difference is that [next-with-apollo](https://github.com/lfades/next-with-apollo) catches the exception in order to prevent throwing and crashing the server, but the error persists.
