### ISSUE TITLE
with-jest-react-testing-library issue with babel: invalid property of "default"

### ISSUE THREAD

**Issue by Skaronator** [zeit/next.js#5980]
# Examples bug report

## Example name
with-jest-react-testing-library

## Describe the bug
I'm unable to run the test without any changes to this example.

```
C:\Users\Skaronator\Documents\GitHub\with-rtl-app>yarn test
yarn run v1.12.3
warning package.json: No license field
$ jest
 FAIL  __tests__/index.test.js
  ● Test suite failed to run

    Plugin 0 specified in "C:\\Users\\Skaronator\\Documents\\GitHub\\with-rtl-app\\node_modules\\next\\babel.js" provided an invalid property of "default" (While processing preset: "C:\\Users\\Skaronator\\Documents\\GitHub\\with-rtl-app\\node_modules\\next\\babel.js")

      at Plugin.init (node_modules/babel-core/lib/transformation/plugin.js:131:13)
      at Function.normalisePlugin (node_modules/babel-core/lib/transformation/file/options/option-manager.js:152:12)
      at node_modules/babel-core/lib/transformation/file/options/option-manager.js:184:30
          at Array.map (<anonymous>)
      at Function.normalisePlugins (node_modules/babel-core/lib/transformation/file/options/option-manager.js:158:20)
      at OptionManager.mergeOptions (node_modules/babel-core/lib/transformation/file/options/option-manager.js:234:36)
      at node_modules/babel-core/lib/transformation/file/options/option-manager.js:265:14
      at node_modules/babel-core/lib/transformation/file/options/option-manager.js:323:22
          at Array.map (<anonymous>)
      at OptionManager.resolvePresets (node_modules/babel-core/lib/transformation/file/options/option-manager.js:275:20)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        1.362s
Ran all test suites.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

## To Reproduce
Steps to reproduce the behavior, please provide code snippets or a repository:
1. `yarn create next-app --example with-jest-react-testing-library with-rtl-app`
2. `cd with-rtl-app`
3. `yarn test`

## Expected behavior
Test should run without any error.

## System information
 - OS: Windows 10
- Node v10.15.0
```
  "dependencies": {
    "next": "^7.0.2",
    "react": "^16.7.0",
    "react-dom": "^16.7.0"
  },
  "devDependencies": {
    "jest": "^23.6.0",
    "react-testing-library": "^5.4.2"
  },
```
## Additional context

/cc: @jeanbauer #5940

**Comment by timneutkens** [comment]
Feel free to create a PR to fix it 💯
