### ISSUE TITLE
Cannot find module './modules/UnimplementedView' 

### ISSUE THREAD

**Issue by steida** [zeit/next.js#5989]
Canary changed strategy to import modules. With 7.0.2, React Native Web works. More info here:
This is cross issue because I don't know where the bug is.

https://github.com/necolas/react-native-web/issues/1220

**Comment by timneutkens** [comment]
I'm not sure what's happening here. You didn't add the `serverless` target right?

**Comment by steida** [comment]
No. I also checked Next.js RNW example with the same result.

**Comment by steida** [comment]
With 8.0.0-canary.4

 ERROR  Failed to compile with 1 errors                                                                  1:11:33 AM

This dependency was not found:

* private-next-pages/_app.tsx in ./node_modules/next/dist/build/webpack/loaders/next-client-pages-loader.js?page=%2
F_app&absolutePagePath=private-next-pages%2F_app.tsx

To install it, you can run: npm install --save private-next-pages/_app.tsx
Server ready at http://localhost:4000/
{ Error: Cannot find module '/Users/steida/dev/este-typescript/.next/build-manifest.json'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:580:15)
    at Function.Module._load (internal/modules/cjs/loader.js:506:25)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.loadComponents (/Users/steida/dev/este-typescript/node_modules/next-server/dist/server/load-component
s.js:13:9)
    at DevServer.renderToHTMLWithComponents (/Users/steida/dev/este-typescript/node_modules/next-server/dist/server
/next-server.js:196:48)
    at DevServer.renderErrorToHTML (/Users/steida/dev/este-typescript/node_modules/next-server/dist/server/next-ser
ver.js:226:21)
    at DevServer.renderErrorToHTML (/Users/steida/dev/este-typescript/node_modules/next/dist/server/next-dev-server
.js:107:26)
    at process._tickCallback (internal/process/next_tick.js:68:7) code: 'MODULE_NOT_FOUND' }

**Comment by timneutkens** [comment]
https://github.com/zeit/next.js/blob/canary/examples/with-react-native-web/next.config.js#L7-L9

It's because that line is not taking into account aliases set by Next.js, could you send a PR?

**Comment by steida** [comment]
I would, but I don't know which aliases are set by Next.js.

**Comment by timneutkens** [comment]
```
    config.resolve.alias = {
      ...(config.resolve.alias || {})
      'react-native$': 'react-native-web'
    }
```

This should do

**Comment by steida** [comment]
I just checked with-react-native-web with 

```js
const withTM = require("next-plugin-transpile-modules");

module.exports = withTM({
  transpileModules: ["react-native-web"],
  webpack: config => {
    // Alias all `react-native` imports to `react-native-web`
    config.resolve.alias = {
      ...(config.resolve.alias || {}),
      "react-native$": "react-native-web"
    };

    return config;
  }
});
```
and 

```
{
  "name": "with-react-native-web",
  "scripts": {
    "dev": "next",
    "build": "next build",
    "start": "next start"
  },
  "dependencies": {
    "next": "8.0.0-canary.6",
    "next-plugin-transpile-modules": "^0.1.3",
    "react": "^16.7.0",
    "react-art": "^16.5.2",
    "react-dom": "^16.7.0",
    "react-native-web": "^0.9.3"
  }
}
```

And still the same error.

**Comment by steida** [comment]
@timneutkens Can you point me to what should I debug, please?

```
{ Error: Cannot find module './modules/UnimplementedView'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:580:15)
    at Function.Module._load (internal/modules/cjs/loader.js:506:25)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object../modules/UnimplementedView (/Users/steida/dev/este-typescript/.next/server/static/development/pages/index.js:2353:18)
    at __webpack_require__ (/Users/steida/dev/este-typescript/.next/server/static/development/pages/index.js:23:31)
    at Object../node_modules/react-native-web/dist/cjs/index.js (/Users/steida/dev/este-typescript/.next/server/static/development/pages/index.js:5003:26)
    at __webpack_require__ (/Users/steida/dev/este-typescript/.next/server/static/development/pages/index.js:23:31)
    at Module../pages/index.tsx (/Users/steida/dev/este-typescript/.next/server/static/development/pages/index.js:5922:70)
    at __webpack_require__ (/Users/steida/dev/este-typescript/.next/server/static/development/pages/index.js:23:31)
    at Object.3 (/Users/steida/dev/este-typescript/.next/server/static/development/pages/index.js:6411:18)
    at __webpack_require__ (/Users/steida/dev/este-typescript/.next/server/static/development/pages/index.js:23:31)
    at /Users/steida/dev/este-typescript/.next/server/static/development/pages/index.js:91:18
    at Object.<anonymous> (/Users/steida/dev/este-typescript/.next/server/static/development/pages/index.js:94:10)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10) code: 'MODULE_NOT_FOUND' }
{ Error: Cannot find module './modules/UnimplementedView'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:580:15)
    at Function.Module._load (internal/modules/cjs/loader.js:506:25)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object../modules/UnimplementedView (/Users/steida/dev/este-typescript/.next/server/static/development/pages/_document.js:840:18)
    at __webpack_require__ (/Users/steida/dev/este-typescript/.next/server/static/development/pages/_document.js:23:31)
    at Object../node_modules/react-native-web/dist/cjs/index.js (/Users/steida/dev/este-typescript/.next/server/static/development/pages/_document.js:2403:26)
    at __webpack_require__ (/Users/steida/dev/este-typescript/.next/server/static/development/pages/_document.js:23:31)
    at Module../pages/_document.tsx (/Users/steida/dev/este-typescript/.next/server/static/development/pages/_document.js:3709:71)
    at __webpack_require__ (/Users/steida/dev/este-typescript/.next/server/static/development/pages/_document.js:23:31)
    at Object.1 (/Users/steida/dev/este-typescript/.next/server/static/development/pages/_document.js:3861:18)
    at __webpack_require__ (/Users/steida/dev/este-typescript/.next/server/static/development/pages/_document.js:23:31)
    at /Users/steida/dev/este-typescript/.next/server/static/development/pages/_document.js:91:18
    at Object.<anonymous> (/Users/steida/dev/este-typescript/.next/server/static/development/pages/_document.js:94:10)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10) code: 'MODULE_NOT_FOUND' }
{ Error: Cannot find module './modules/UnimplementedView'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:580:15)
    at Function.Module._load (internal/modules/cjs/loader.js:506:25)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object../modules/UnimplementedView (/Users/steida/dev/este-typescript/.next/server/static/development/pages/_document.js:840:18)
    at __webpack_require__ (/Users/steida/dev/este-typescript/.next/server/static/development/pages/_document.js:23:31)
    at Object../node_modules/react-native-web/dist/cjs/index.js (/Users/steida/dev/este-typescript/.next/server/static/development/pages/_document.js:2403:26)
    at __webpack_require__ (/Users/steida/dev/este-typescript/.next/server/static/development/pages/_document.js:23:31)
    at Module../pages/_document.tsx (/Users/steida/dev/este-typescript/.next/server/static/development/pages/_document.js:3709:71)
    at __webpack_require__ (/Users/steida/dev/este-typescript/.next/server/static/development/pages/_document.js:23:31)
    at Object.1 (/Users/steida/dev/este-typescript/.next/server/static/development/pages/_document.js:3861:18)
    at __webpack_require__ (/Users/steida/dev/este-typescript/.next/server/static/development/pages/_document.js:23:31)
    at /Users/steida/dev/este-typescript/.next/server/static/development/pages/_document.js:91:18
    at Object.<anonymous> (/Users/steida/dev/este-typescript/.next/server/static/development/pages/_document.js:94:10)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10) code: 'MODULE_NOT_FOUND' }
```

**Comment by steida** [comment]
So I tried Babel instead of Webpack, and it magically not only this issue but also "The default export is not a React Component".

So there is something wrong with Webpack and TM.

https://github.com/necolas/react-native-web/blob/master/docs/guides/getting-started.md#configuring-babel

**Comment by steida** [comment]
OK, fixed with babel.

**Comment by steida** [comment]
I am not sure. It's technically correct, Webpack should work IMHO. What do you think?

**Comment by steida** [comment]
OK. It does not work. I will create a new issue.
