### ISSUE TITLE
IE11 Object doesn't support property or method 'isFinite'

### ISSUE THREAD

**Issue by hect1c** [zeit/next.js#6008]
# Bug report

## Describe the bug

I'm getting an error on IE11 only and getting An unexpected error has occurred page.  I am using next@canary. It works on IE10 or Microsoft Edge, and all other browsers. Just not IE11.

## Expected behavior

The page should load as it does in other browsers. The page loads briefly and gets to a certain point in the script and then breaks.

## Screenshots

![image](https://user-images.githubusercontent.com/1482519/50827980-05292b00-137b-11e9-82f5-2258dbd23f9f.png)

Below is the error I'm getting. 

`
teachonline (6,9944)
TypeError: Object doesn't support property or method 'isFinite'
   {
      [functions]: ,
      __proto__: {
         [functions]: ,
         __proto__: { },
         message: "",
         name: "TypeError"
      },
      description: "Object doesn't support property or method 'isFinite'",
      message: "Object doesn't support property or method 'isFinite'",
      name: "TypeError",
      number: -2146827850,
      stack: "TypeError: Object doesn't support property or method 'isFinite'
   at n (https://www.ef.com/teachonline/_next/static/U3ZfjICZfz4S~3uq8oigf/pages/index.js:31:4986)
   at e (https://www.ef.com/teachonline/_next/static/U3ZfjICZfz4S~3uq8oigf/pages/index.js:8:27396)
   at e (https://www.ef.com/teachonline/_next/static/U3ZfjICZfz4S~3uq8oigf/pages/index.js:8:59688)
   at RNiq (https://www.ef.com/teachonline/_next/static/U3ZfjICZfz4S~3uq8oigf/pages/index.js:8:59577)
   at l (https://www.ef.com/teachonline/_next/static/runtime/webpack-89179faa512dd01fbb62.js:1:515)
   at Anonymous function (https://www.ef.com/teachonline/_next/static/U3ZfjICZfz4S~3uq8oigf/pages/index.js:1:10021)
   at Anonymous function (https://www.ef.com/teachonline/_next/static/runtime/main-5bcfa18a01c22fc9a45e.js:1:7424)
   at value (https://www.ef.com/teachonline/_next/static/runtime/main-5bcfa18a01c22fc9a45e.js:1:7409)
   at W (https://www.ef.com/teachonline/_next/static/runtime/main-5bcfa18a01c22fc9a45e.js:1:9836)
   at Anonymous function (http"
   }

`

## System information
 - OS: Windows
 - Browser (if applies) IE11
 - Version of Next.js: 8.0.0-canary.2

## Additional context

I am getting a Syntax error from a script before this error occurs. I'm still trying to isolate the issue to determine what exactly is causing this issue. I'm assuming it may be an issue with one of my scripts. I was using a package that was using Swiper as an ESM module. https://github.com/nolimits4web/swiper/issues/2282 found this, so I've added swiper as an external dependency which works but the issue still persists. 

Sorry if I have not given enough information, but I am still in the process of debugging. Hoping someone can point me in the right direction to isolate and resolve this. Thanks

**Comment by timneutkens** [comment]
I assume this is because of an external library you're importing from node_modules. We don't transpile node_modules. So you'll have to add a polyfill: https://github.com/zeit/next.js/tree/canary/examples/with-polyfills
