### ISSUE TITLE
How to escape rendering and send response directly from 'getInitialProps'?

### ISSUE THREAD

**Issue by alexey-kuznetsov** [zeit/next.js#6021]
I created page for sitemap. I generate XML in getInitialProps and want to send it directly to response. 
```
 static async getInitialProps({ req, res }) {
 // Some code to generate XML.
      res.header('Content-Type', 'application/xml');
      res.status(200);
      res.send(xml);
}
```
If there are 'render' method in page, I get what returned from 'render' method. Even if render returns null, I get empty page. But if I remove 'render' method entirely, server responds with XML, as expected, but I have the following error in logs:
```
{ TypeError: inst.render is not a function
    at processChild (/app/node_modules/react-dom/cjs/react-dom-server.node.development.js:2527:18)
    at resolve (/app/node_modules/react-dom/cjs/react-dom-server.node.development.js:2384:5)
    at ReactDOMServerRenderer.render (/app/node_modules/react-dom/cjs/react-dom-server.node.development.js:2706:22)
    at ReactDOMServerRenderer.read (/app/node_modules/react-dom/cjs/react-dom-server.node.development.js:2680:23)
    at renderToString (/app/node_modules/react-dom/cjs/react-dom-server.node.development.js:3071:25)
    at renderPage (/app/node_modules/next/dist/server/render.js:275:26)
    at Function.getInitialProps (/app/node_modules/next/dist/server/document.js:67:25)
    at tryCatch (/app/node_modules/regenerator-runtime/runtime.js:62:40)
    at Generator.invoke [as _invoke] (/app/node_modules/regenerator-runtime/runtime.js:296:22)
    at Generator.prototype.(anonymous function) [as next] (/app/node_modules/regenerator-runtime/runtime.js:114:21)
    at step (/app/node_modules/@babel/runtime/helpers/asyncToGenerator.js:12:30)
    at _next (/app/node_modules/@babel/runtime/helpers/asyncToGenerator.js:27:9)
    at /app/node_modules/@babel/runtime/helpers/asyncToGenerator.js:34:7
    at new Promise (<anonymous>)
    at new F (/app/node_modules/core-js/library/modules/_export.js:36:28) sourceMapsApplied: true }
```

So I don't know, how to resolve this problem.

**Comment by timneutkens** [comment]
Please follow the issue template. This is not a clear and concise reproduction, making it really hard to help on your particular issue.
