### ISSUE TITLE
Unable to deploy with-hashed-statics to Zeit.co v2

### ISSUE THREAD

**Issue by Skaronator** [zeit/next.js#6024]
# Examples bug report

## Example name
with-hashed-statics

## Describe the bug
I'm unable to deploy with-hashed-statics to Now v2 with Serverless Next.js (v8.0). It looks like that the build script doesn't have access to the static folder.

## To Reproduce

1. Get the with-hashed-statics example
2. Upgrade to NextJS 8.0 Canary
3. Add `target: 'serverless'` to next.config.js
4. Add `"now-build": "next build"` to scripts in package.json
5. Add a example now.json
6. Deploy via now

```
{
    "version": 2,
    "name": "nextjs",
    "builds": [
        { "src": "package.json", "use": "@now/next" }
    ]
}
```

## Expected behavior
It should deploy without any errors.

## System information
 - Version of Next.js: latest canary v8.0 with Serverless

## Additional context

Deployment Log:
```
2019-01-10T18:50:43.815Z  $ next build
2019-01-10T18:50:45.019Z  ℹ Compiling Client                                         webpackbar 18:50:45
2019-01-10T18:50:53.752Z  ✔ Client: Compiled with some errors in 8.74s               webpackbar 18:50:53
2019-01-10T18:50:53.771Z  ℹ Compiling Server                                         webpackbar 18:50:53
2019-01-10T18:51:04.355Z  ✔ Server: Compiled with some errors in 10.58s              webpackbar 18:51:04
2019-01-10T18:51:04.363Z  ModuleNotFoundError: Module not found: Error: Can't resolve '../static/file.txt' in '/tmp/47c45b47/pages'
                              at factory.create (/tmp/47c45b47/node_modules/webpack/lib/Compilation.js:821:10)
                              at factory (/tmp/47c45b47/node_modules/webpack/lib/NormalModuleFactory.js:397:22)
                              at resolver (/tmp/47c45b47/node_modules/webpack/lib/NormalModuleFactory.js:130:21)
                              at asyncLib.parallel (/tmp/47c45b47/node_modules/webpack/lib/NormalModuleFactory.js:224:22)
                              at /tmp/47c45b47/node_modules/neo-async/async.js:2825:7
                              at /tmp/47c45b47/node_modules/neo-async/async.js:6886:13
                              at normalResolver.resolve (/tmp/47c45b47/node_modules/webpack/lib/NormalModuleFactory.js:214:25)
                              at doResolve (/tmp/47c45b47/node_modules/enhanced-resolve/lib/Resolver.js:184:12)
                              at hook.callAsync (/tmp/47c45b47/node_modules/enhanced-resolve/lib/Resolver.js:238:5)
                              at _fn0 (eval at create (/tmp/47c45b47/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:15:1)
                              at resolver.doResolve (/tmp/47c45b47/node_modules/enhanced-resolve/lib/UnsafeCachePlugin.js:37:5)
                              at hook.callAsync (/tmp/47c45b47/node_modules/enhanced-resolve/lib/Resolver.js:238:5)
                              at _fn0 (eval at create (/tmp/47c45b47/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:15:1)
                              at hook.callAsync (/tmp/47c45b47/node_modules/enhanced-resolve/lib/Resolver.js:238:5)
                              at _fn0 (eval at create (/tmp/47c45b47/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:12:1)
                              at resolver.doResolve (/tmp/47c45b47/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:42:38)
                          resolve '../static/file.txt' in '/tmp/47c45b47/pages'
                            using description file: /tmp/47c45b47/package.json (relative path: ./pages)
                              Field 'browser' doesn't contain a valid alias configuration
                              using description file: /tmp/47c45b47/package.json (relative path: ./static/file.txt)
                                no extension
                                  Field 'browser' doesn't contain a valid alias configuration
                                  /tmp/47c45b47/static/file.txt doesn't exist
                                .wasm
                                  Field 'browser' doesn't contain a valid alias configuration
                                  /tmp/47c45b47/static/file.txt.wasm doesn't exist
                                .mjs
                                  Field 'browser' doesn't contain a valid alias configuration
                                  /tmp/47c45b47/static/file.txt.mjs doesn't exist
                                .js
                                  Field 'browser' doesn't contain a valid alias configuration
                                  /tmp/47c45b47/static/file.txt.js doesn't exist
                                .jsx
                                  Field 'browser' doesn't contain a valid alias configuration
                                  /tmp/47c45b47/static/file.txt.jsx doesn't exist
                                .json
                                  Field 'browser' doesn't contain a valid alias configuration
                                  /tmp/47c45b47/static/file.txt.json doesn't exist
                                as directory
                                  /tmp/47c45b47/static/file.txt doesn't exist
2019-01-10T18:51:04.364Z  ModuleNotFoundError: Module not found: Error: Can't resolve '../static/images/logo.png' in '/tmp/47c45b47/pages'
                              at factory.create (/tmp/47c45b47/node_modules/webpack/lib/Compilation.js:821:10)
                              at factory (/tmp/47c45b47/node_modules/webpack/lib/NormalModuleFactory.js:397:22)
                              at resolver (/tmp/47c45b47/node_modules/webpack/lib/NormalModuleFactory.js:130:21)
                              at asyncLib.parallel (/tmp/47c45b47/node_modules/webpack/lib/NormalModuleFactory.js:224:22)
                              at /tmp/47c45b47/node_modules/neo-async/async.js:2825:7
                              at /tmp/47c45b47/node_modules/neo-async/async.js:6886:13
                              at normalResolver.resolve (/tmp/47c45b47/node_modules/webpack/lib/NormalModuleFactory.js:214:25)
                              at doResolve (/tmp/47c45b47/node_modules/enhanced-resolve/lib/Resolver.js:184:12)
                              at hook.callAsync (/tmp/47c45b47/node_modules/enhanced-resolve/lib/Resolver.js:238:5)
                              at _fn0 (eval at create (/tmp/47c45b47/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:15:1)
                              at resolver.doResolve (/tmp/47c45b47/node_modules/enhanced-resolve/lib/UnsafeCachePlugin.js:37:5)
                              at hook.callAsync (/tmp/47c45b47/node_modules/enhanced-resolve/lib/Resolver.js:238:5)
                              at _fn0 (eval at create (/tmp/47c45b47/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:15:1)
                              at hook.callAsync (/tmp/47c45b47/node_modules/enhanced-resolve/lib/Resolver.js:238:5)
                              at _fn0 (eval at create (/tmp/47c45b47/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:12:1)
                              at resolver.doResolve (/tmp/47c45b47/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:42:38)
                          resolve '../static/images/logo.png' in '/tmp/47c45b47/pages'
                            using description file: /tmp/47c45b47/package.json (relative path: ./pages)
                              Field 'browser' doesn't contain a valid alias configuration
                              using description file: /tmp/47c45b47/package.json (relative path: ./static/images/logo.png)
                                no extension
                                  Field 'browser' doesn't contain a valid alias configuration
                                  /tmp/47c45b47/static/images/logo.png doesn't exist
                                .wasm
                                  Field 'browser' doesn't contain a valid alias configuration
                                  /tmp/47c45b47/static/images/logo.png.wasm doesn't exist
                                .mjs
                                  Field 'browser' doesn't contain a valid alias configuration
                                  /tmp/47c45b47/static/images/logo.png.mjs doesn't exist
                                .js
                                  Field 'browser' doesn't contain a valid alias configuration
                                  /tmp/47c45b47/static/images/logo.png.js doesn't exist
                                .jsx
                                  Field 'browser' doesn't contain a valid alias configuration
                                  /tmp/47c45b47/static/images/logo.png.jsx doesn't exist
                                .json
                                  Field 'browser' doesn't contain a valid alias configuration
                                  /tmp/47c45b47/static/images/logo.png.json doesn't exist
                                as directory
                                  /tmp/47c45b47/static/images/logo.png doesn't exist
2019-01-10T18:51:04.365Z  ModuleNotFoundError: Module not found: Error: Can't resolve '../static/images/logo.svg' in '/tmp/47c45b47/pages'
                              at factory.create (/tmp/47c45b47/node_modules/webpack/lib/Compilation.js:821:10)
                              at factory (/tmp/47c45b47/node_modules/webpack/lib/NormalModuleFactory.js:397:22)
                              at resolver (/tmp/47c45b47/node_modules/webpack/lib/NormalModuleFactory.js:130:21)
                              at asyncLib.parallel (/tmp/47c45b47/node_modules/webpack/lib/NormalModuleFactory.js:224:22)
                              at /tmp/47c45b47/node_modules/neo-async/async.js:2825:7
                              at /tmp/47c45b47/node_modules/neo-async/async.js:6886:13
                              at normalResolver.resolve (/tmp/47c45b47/node_modules/webpack/lib/NormalModuleFactory.js:214:25)
                              at doResolve (/tmp/47c45b47/node_modules/enhanced-resolve/lib/Resolver.js:184:12)
                              at hook.callAsync (/tmp/47c45b47/node_modules/enhanced-resolve/lib/Resolver.js:238:5)
                              at _fn0 (eval at create (/tmp/47c45b47/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:15:1)
                              at resolver.doResolve (/tmp/47c45b47/node_modules/enhanced-resolve/lib/UnsafeCachePlugin.js:37:5)
                              at hook.callAsync (/tmp/47c45b47/node_modules/enhanced-resolve/lib/Resolver.js:238:5)
                              at _fn0 (eval at create (/tmp/47c45b47/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:15:1)
                              at hook.callAsync (/tmp/47c45b47/node_modules/enhanced-resolve/lib/Resolver.js:238:5)
                              at _fn0 (eval at create (/tmp/47c45b47/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:12:1)
                              at resolver.doResolve (/tmp/47c45b47/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:42:38)
                          resolve '../static/images/logo.svg' in '/tmp/47c45b47/pages'
                            using description file: /tmp/47c45b47/package.json (relative path: ./pages)
                              Field 'browser' doesn't contain a valid alias configuration
                              using description file: /tmp/47c45b47/package.json (relative path: ./static/images/logo.svg)
                                no extension
                                  Field 'browser' doesn't contain a valid alias configuration
                                  /tmp/47c45b47/static/images/logo.svg doesn't exist
                                .wasm
                                  Field 'browser' doesn't contain a valid alias configuration
                                  /tmp/47c45b47/static/images/logo.svg.wasm doesn't exist
                                .mjs
                                  Field 'browser' doesn't contain a valid alias configuration
                                  /tmp/47c45b47/static/images/logo.svg.mjs doesn't exist
                                .js
                                  Field 'browser' doesn't contain a valid alias configuration
                                  /tmp/47c45b47/static/images/logo.svg.js doesn't exist
                                .jsx
                                  Field 'browser' doesn't contain a valid alias configuration
                                  /tmp/47c45b47/static/images/logo.svg.jsx doesn't exist
                                .json
                                  Field 'browser' doesn't contain a valid alias configuration
                                  /tmp/47c45b47/static/images/logo.svg.json doesn't exist
                                as directory
                                  /tmp/47c45b47/static/images/logo.svg doesn't exist
                          ModuleNotFoundError: Module not found: Error: Can't resolve '../static/file.txt' in '/tmp/47c45b47/pages'
                              at factory.create (/tmp/47c45b47/node_modules/webpack/lib/Compilation.js:821:10)
                              at factory (/tmp/47c45b47/node_modules/webpack/lib/NormalModuleFactory.js:397:22)
                              at resolver (/tmp/47c45b47/node_modules/webpack/lib/NormalModuleFactory.js:130:21)
                              at asyncLib.parallel (/tmp/47c45b47/node_modules/webpack/lib/NormalModuleFactory.js:224:22)
                              at /tmp/47c45b47/node_modules/neo-async/async.js:2825:7
                              at /tmp/47c45b47/node_modules/neo-async/async.js:6886:13
                              at normalResolver.resolve (/tmp/47c45b47/node_modules/webpack/lib/NormalModuleFactory.js:214:25)
                              at doResolve (/tmp/47c45b47/node_modules/enhanced-resolve/lib/Resolver.js:184:12)
                              at hook.callAsync (/tmp/47c45b47/node_modules/enhanced-resolve/lib/Resolver.js:238:5)
                              at _fn0 (eval at create (/tmp/47c45b47/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:15:1)
                              at resolver.doResolve (/tmp/47c45b47/node_modules/enhanced-resolve/lib/UnsafeCachePlugin.js:37:5)
                              at hook.callAsync (/tmp/47c45b47/node_modules/enhanced-resolve/lib/Resolver.js:238:5)
                              at _fn0 (eval at create (/tmp/47c45b47/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymou
2019-01-10T18:51:04.395Z  error Command failed with exit code 1.
2019-01-10T18:51:04.395Z  info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
2019-01-10T18:51:04.402Z  Error: Exited with 1
                              at ChildProcess.child.on (/tmp/utils/node_modules/@now/build-utils/fs/run-user-scripts.js:11:16)
                              at emitTwo (events.js:126:13)
                              at ChildProcess.emit (events.js:214:7)
                              at maybeClose (internal/child_process.js:925:16)
                              at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
2019-01-10T18:51:04.402Z  patching https://api-bru1.zeit.co/v2/now/deployments/dpl_wgNfHrfRZVV1t2uGnwPEHfKQhqLK/builds/bld_oezuh59eh with {"readyState":"ERROR","errorCode":"BUILD_FAILED_2"}
```

**Comment by Skaronator** [comment]
Here is a Repo for faster reproducing. Just clone it and run `now` to deploy it.

https://github.com/Skaronator/with-hashed-now
