### ISSUE TITLE
Support Yarn PnP

### ISSUE THREAD

**Issue by jacobwgillespie** [zeit/next.js#6049]
# Feature request

It would be nice to have support for Yarn PnP, now that it's officially stable in Yarn 1.12.  Here's some info on enabling it: https://gist.github.com/arcanis/02b49752c385908479734d8027d7a6c7.

Create React App 2.0 supports PnP via [pnp-webpack-plugin](https://github.com/arcanis/pnp-webpack-plugin), so it might be a nice reference for implementation.

**Comment by balupton** [comment]
For those wondering, this is the error:

```
> yarn run now-build
yarn run v1.13.0
$ npm run our:compile:next
npm WARN lifecycle The node binary used for scripts is /var/folders/5j/y0qt_jkd7wz97klgv9f21bl40000gn/T/yarn--1548450415442-0.8949424365687375/node but npm is using /usr/local/Cellar/node/11.7.0/bin/node itself. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.

> jordanbpeterson.community@1.1.0 our:compile:next /Users/balupton/Projects/websites/jordanbpeterson.community
> next build

internal/modules/cjs/loader.js:605
    throw err;
    ^

Error: Cannot find module 'cross-spawn'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:603:15)
    at Function.Module._load (internal/modules/cjs/loader.js:529:25)
    at Module.require (internal/modules/cjs/loader.js:657:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/balupton/Library/Caches/Yarn/v4/npm-next-8.0.0-canary.14-7b358d8359b57274fb28ce0df660956a21b5990f/node_modules/next/dist/bin/next:8:39)
    at Module._compile (internal/modules/cjs/loader.js:721:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:732:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
    at Function.Module._load (internal/modules/cjs/loader.js:552:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! jordanbpeterson.community@1.1.0 our:compile:next: `next build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the jordanbpeterson.community@1.1.0 our:compile:next script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/balupton/.cache/npm/_logs/2019-01-25T21_06_55_878Z-debug.log
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
````

**Comment by balupton** [comment]
Running `yarn --disable-pnp` resolves it.

**Comment by jth0024** [comment]
Just to add some additional info, I created a new project with only NextJS, the PnpWebpackPlugin, and a single page. Like so:
**package.json**
`json
{
  "installConfig": {
    "pnp": true
  },
  "scripts": {
    "dev": "next"
  },
  "dependencies": {
    "next": "8.1.0",
    "react": "16.8.6",
    "react-dom": "16.8.6"
  },
  "devDependencies": {
    "pnp-webpack-plugin": "1.4.3"
  }
}
`
**next.config.js**
`javascript
const PnpWebpackPlugin = require('pnp-webpack-plugin')

module.exports = {
  webpack(config) {
    if (!config.resolve) config.resolve = {}
    if (!config.resolveLoader) config.resolveLoader = {}
    if (!config.resolve.plugins) config.resolve.plugins = []
    if (!config.resolveLoader.plugins) config.resolveLoader.plugins = []

    config.resolve.plugins.push(PnpWebpackPlugin)
    config.resolveLoader.plugins.push(PnpWebpackPlugin.moduleLoader(module))

    // Return the modified config
    return config
  },
}
`

**pages/index.js**
`javascript
export default () => (<div>Hello, World!</div>)
`
I receive this error:

![image](https://user-images.githubusercontent.com/5278555/58559944-238ca780-81f2-11e9-8cc7-beba1c76f195.png)

**Comment by Timer** [comment]
Yarn PnP now works out of the box!

**Comment by Ciantic** [comment]
Is there an example of this? I don't think people get this working because anything non-trivial uses CSS plugin that does not work, see here:

https://github.com/zeit/next-plugins/issues/550

**Comment by balazsorban44** [comment]
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
