### ISSUE TITLE
Frontend and backend result in different cookies

### ISSUE THREAD

**Issue by RuizhenMai** [zeit/next.js#6110]
Using Express and PassportJS

Since getInitialProps will be called by frontend and backend, when I try to do things like
```javascript
index.getInitialProps = async context => {
  const response = await axios.get("/auth/verify"); // check if the user has logged in 
  return { user: response.data};
};
```

```javascript
server.get("/auth/verify", (req, res) => {
  res.json({ user: res.locals.user });
});
```
this will result in different states because when I log in the browser, the browser's cookie is set to be logged but when I refresh, the method called by server, the server will not respond the user I have logged in in the browser. Any help is much appreciated

**Comment by timneutkens** [comment]
Your API should be stateless and use an authentication token instead.

See this example: https://github.com/zeit/next.js/tree/canary/examples/with-cookie-auth

Please follow the issue template in the future.

**Comment by RuizhenMai** [comment]
The example cannot be download: 
```
> Error! Error downloading with-cookie-auth files for with-cookie-auth-app
(node:49133) UnhandledPromiseRejectionWarning: HttpError: {"message":"Not Found","documentation_url":"https://developer.github.com/v3/repos/contents/#get-contents"}
    at response.text.then.message (/usr/local/lib/node_modules/create-next-app/node_modules/@octokit/rest/lib/request/request.js:72:19)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:49133) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:49133) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
