### ISSUE TITLE
8.0.0-canary.14 bug

### ISSUE THREAD

**Issue by steida** [zeit/next.js#6136]
Updated from 8.0.0-canary.10 with this result:

```
ERROR  Failed to compile with 1 errors                                                                 12:55:13 AM

 error  in ./node_modules/next/dist/client/next-dev.js

Module parse failed: Unexpected token (34:6)
You may need an appropriate loader to handle this file type.
|
|
> import('./noop');
| var _window = window,
|     assetPrefix = _window.__NEXT_DATA__.assetPrefix;

 @ multi ./node_modules/next/dist/client/next-dev

{ Error: Cannot find module '/Users/steida/dev/este/.next/build-manifest.json'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.loadComponents (/Users/steida/dev/este/node_modules/next-server/dist/server/load-components.js:13:9)
    at DevServer.renderToHTMLWithComponents (/Users/steida/dev/este/node_modules/next-server/dist/server/next-serve
r.js:194:48)
    at DevServer.renderErrorToHTML (/Users/steida/dev/este/node_modules/next-server/dist/server/next-server.js:224:
21)
    at DevServer.renderErrorToHTML (/Users/steida/dev/este/node_modules/next/dist/server/next-dev-server.js:107:26)
    at process._tickCallback (internal/process/next_tick.js:68:7) code: 'MODULE_NOT_FOUND' }
```

**Comment by timneutkens** [comment]
@steida that's interesting, could you provide a reproduction? Really curious to see what's going on here.

**Comment by timneutkens** [comment]
Possibly related: https://twitter.com/wSokra/status/1087992291548164103

**Comment by steida** [comment]
It really is 😲

I tried suggested fix: Add "acorn": "^6.0.5", (need to purge node_modules then), and it works.

It happens in https://github.com/este/este/tree/e92ebee8ca75967903a74820e1cc504a3afee15a.

So I am closing it. Temp fix is weird but working.

**Comment by steida** [comment]
Related https://github.com/zeit/next.js/issues/6167

**Comment by dimensi** [comment]
i got some problem on "production" version (8.0.0). Can't start develop mode. I update my npm to 6.7.0. Problem not resolve.

**Comment by edwinwong90** [comment]
For my case, I just remove node_modules and package-lock.json and run `npm install` again, Its works. Related #6167
