### ISSUE TITLE
"next": "8.0.0-canary.16" cannot find module '../server/htmlescape'

### ISSUE THREAD

**Issue by steida** [zeit/next.js#6154]
Update from 14 to 16 (with Acorn workarouch, which works for 14)

{ Error: Cannot find module '../server/htmlescape'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.../server/htmlescape (/Users/steida/dev/este/.next/server/static/development/pages/_document.js:103:18)
    at __webpack_require__ (/Users/steida/dev/este/.next/server/static/development/pages/_document.js:23:31)
    at Object../node_modules/next/dist/pages/_document.js (/Users/steida/dev/este/.next/server/static/development/pages/_document.js:1629:20)
    at __webpack_require__ (/Users/steida/dev/este/.next/server/static/development/pages/_document.js:23:31)
    at Object../node_modules/next/document.js (/Users/steida/dev/este/.next/server/static/development/pages/_document.js:2013:18)
    at __webpack_require__ (/Users/steida/dev/este/.next/server/static/development/pages/_document.js:23:31)
    at Module../pages/_document.tsx (/Users/steida/dev/este/.next/server/static/development/pages/_document.js:2835:71)
    at __webpack_require__ (/Users/steida/dev/este/.next/server/static/development/pages/_document.js:23:31)
    at Object.1 (/Users/steida/dev/este/.next/server/static/development/pages/_document.js:2992:18)
    at __webpack_require__ (/Users/steida/dev/este/.next/server/static/development/pages/_document.js:23:31)
    at /Users/steida/dev/este/.next/server/static/development/pages/_document.js:91:18
    at Object.<anonymous> (/Users/steida/dev/este/.next/server/static/development/pages/_document.js:94:10) code: 'MODULE_NOT_FOUND' }

**Comment by petrovichm** [comment]
Having the same issue from `canary` update
