### ISSUE TITLE
with-custom-reverse-proxy  throw er; // Unhandled 'error' event

### ISSUE THREAD

**Issue by jixiaohongdw** [zeit/next.js#6161]
# with-custom-reverse-proxy 
 

when i run yarn && yarn dev there throw an error like this

```bash

[HPM] Proxy created: /api  ->  https://swapi.co/api/
[HPM] Proxy rewrite rule created: "^/api" ~> "/"
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::3000
    at Server.setupListenHandle [as _listen2] (net.js:1360:14)
    at listenInCluster (net.js:1401:12)
    at Server.listen (net.js:1485:7)
    at Function.listen (plugins/next.js/examples/with-custom-reverse-proxy/node_modules/express/lib/application.js:618:24)
    at app.prepare.then (plugins/next.js/examples/with-custom-reverse-proxy/server.js:40:12)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.


```

**Comment by teleginzhenya** [comment]
![image](https://user-images.githubusercontent.com/24455680/51822417-70c14100-2306-11e9-9df9-4bd3079e5895.png)
I have no errors

`Error: listen EADDRINUSE :::3000`
Probably you have something running on 3000 port

**Comment by timneutkens** [comment]
Thanks for checking @teleginzhenya
