### ISSUE TITLE
Antd-design-less example with export with Next > 7.0.2

### ISSUE THREAD

**Issue by revskill10** [zeit/next.js#6181]
# Bug report

## Describe the bug

The bug happens when i export static NextJS app

```
> with-ant-design-less@1.0.0 export /Users/revskill/work/kms/kms-edu/src/with-ant-design-less
> next build && next export


✔ Client
  Compiled successfully in 28.09s

✔ Server
  Compiled successfully in 16.04s

> Using external babel configuration
> Location: "/Users/revskill/work/kms/kms-edu/src/with-ant-design-less/.babelrc"
 ┌ /
 ├ /_app
 ├ /_document
 └ /_error

> using build directory: /Users/revskill/work/kms/kms-edu/src/with-ant-design-less/.next
  copying "static build" directory
  launching 3 threads with concurrency of 10 per thread
/Users/revskill/work/kms/kms-edu/src/with-ant-design-less/node_modules/antd/lib/style/index.less:1
(function (exports, require, module, __filename, __dirname) { @import './themes/default';
                                                              ^

SyntaxError: Invalid or unexpected token
    at new Script (vm.js:84:7)
    at createScript (vm.js:264:10)
    at Object.runInThisContext (vm.js:312:10)
    at Module._compile (internal/modules/cjs/loader.js:696:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:747:10)
    at Module.load (internal/modules/cjs/loader.js:628:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:568:12)
    at Function.Module._load (internal/modules/cjs/loader.js:560:3)
    at Module.require (internal/modules/cjs/loader.js:665:17)
    at require (internal/modules/cjs/helpers.js:20:18)
{}
```

## To Reproduce

Upgrading `antd-less-design` example with following dependencies:

```
{
  "name": "with-ant-design-less",
  "version": "1.0.0",
  "scripts": {
    "dev": "next",
    "build": "next build",
    "start": "next start",
    "export": "next build && next export"
  },
  "dependencies": {
    "@zeit/next-less": "^1.0.1",
    "antd": "3.12.4",
    "less": "^3.9.0",
    "next": "^8.0.0-canary.17",
    "react": "^16.7.0",
    "react-dom": "^16.7.0"
  },
  "license": "ISC",
  "devDependencies": {
    "babel-plugin-import": "^1.11.0"
  }
}
```
next.config.js:

```js
/* eslint-disable */
const withLess = require('@zeit/next-less')


// fix: prevents error when .less files are required by node
if (typeof require !== 'undefined') {
  require.extensions['.less'] = file => {}
}

module.exports = withLess({
  lessLoaderOptions: {
    javascriptEnabled: true,
    modifyVars: {
      "@primary-color": '#1DA57A'
    }
  },
  exportPathMap: async function (defaultPathMap) {
    return {
      '/': { page: '/' },
    }
  }
})

```

## Expected behavior

Exporting should be successfull.

## Screenshots

<img width="738" alt="screen shot 2019-01-31 at 7 27 43 am" src="https://user-images.githubusercontent.com/1390196/52022059-dccfbf00-2529-11e9-91a7-5106b26a8960.png">

## System information
 - OS: MacOS
 - Browser : chrome
 - Version of Next.js: ^8.0.0-canary.17

Updated: The example worked with Next 7.0.2 , but not work with < 7.0.2 or 8.0.x

**Comment by teleginzhenya** [comment]
Hello! Did you see the [example](https://github.com/zeit/next.js/tree/canary/examples/with-ant-design-less)?

**Comment by revskill10** [comment]
@teleginzhenya I tried both ways but it still showed the same error.
Do you have any working repo for me to re-test again ? Thanks you very much.

**Comment by revskill10** [comment]
@teleginzhenya The example worked well with Next 7.0.2.
If you upgrade Next to 8.0.x, the error still happens.

**Comment by afuggini** [comment]
Having the same issue. Here's my `next.config.js`:

```javascript
const withLess = require('@zeit/next-less')
const lessToJS = require('less-vars-to-js')
const fs = require('fs')
const path = require('path')

const themeVariables = lessToJS(
  fs.readFileSync(
    path.resolve(__dirname, './styles/antd/theme.less'),
    'utf8'
  )
)

const config = {
  webpack: (config, { dev, isServer, defaultLoaders }) => {
    // Fixes npm packages that depend on `fs` module
    config.node = { fs: 'empty' }
    return config
  },
  distDir: '../../dist/functions/next',
  cssLoaderOptions: {
    modules: true,
    getLocalIdent: (context, localIdentName, localName) => {
      return localName
    }
  },
  lessLoaderOptions: {
    javascriptEnabled: true,
    modifyVars: themeVariables
  }
}

// fix: prevents error when .less files are required by node
if (typeof require !== 'undefined') {
  require.extensions['.less'] = () => {} // eslint-disable-line
}

module.exports = withLess(config)
```

**Comment by Legym** [comment]
I'm using next 8.0.0.0

in my .babelrc I had to change 

```
{
  "presets": ["next/babel"],
  "plugins": [
    "@babel/plugin-proposal-class-properties",
    ["import", { "libraryName": "antd", "style": true} ],
    ["import", { "libraryName": "antd-mobile", "libraryDirectory": "lib"}, "antd-mobile"],
    ["@babel/plugin-proposal-decorators", { "decoratorsBeforeExport": true }],
  ]
}```

to 

```
{
  "presets": ["next/babel"],
  "plugins": [
    "@babel/plugin-proposal-class-properties",
    ["import", { "libraryName": "antd", "style": "less"} ],
    ["import", { "libraryName": "antd-mobile", "libraryDirectory": "lib"}, "antd-mobile"],
    ["@babel/plugin-proposal-decorators", { "decoratorsBeforeExport": true }],
  ]
}
```

So `["import", { "libraryName": "antd", "style": true} ]` to `["import", { "libraryName": "antd", "style": "less"} ]`

**Comment by Legym** [comment]
My next.config.js

```
/* eslint-disable */
const withLess = require('@zeit/next-less');
const withCSS = require('@zeit/next-css');
const withSass = require('@zeit/next-sass')

// fix: prevents error when .less files are required by node
if (typeof require !== 'undefined') {
  require.extensions['.less'] = (file) => {}
}

module.exports = withCSS(withLess({
  exportPathMap: async function () {
    return {
      '/d': { page: '/d' },
      '/d/about': { page: '/d/about' },
      '/d/cart': { page: '/d/cart' },
      '/d/checkout': { page: '/d/checkout' },
      '/d/contact': { page: '/d/contact' },
      '/d/shop': { page: '/d/shop' },
    }
  },
  cssModules: true,
  lessLoaderOptions: {
     javascriptEnabled: true
  },
},withSass()));
```

**Comment by maotora** [comment]
I'm facing a similar issue with `with-antd` example cannot export but it runs okay with `npm run dev`.

When I run `next build && next export`

```
> next build


✔ Client
  Compiled successfully in 2.49s

✔ Server
  Compiled successfully in 1.84s

> Using external babel configuration
> Location: "/home/niggacode/Projects/Sites/Mwenge/.babelrc"
 ┌ /
 ├ /_app
 ├ /_document
 └ /_error


> with-ant-design@1.0.0 export /home/niggacode/Projects/Sites/Mwenge
> next export

> using build directory: /home/niggacode/Projects/Sites/Mwenge/.next
  copying "static build" directory
  launching 7 threads with concurrency of 10 per thread
/home/niggacode/Projects/Sites/Mwenge/node_modules/antd/lib/style/index.css:7
body {
     ^

SyntaxError: Unexpected token {
    at new Script (vm.js:79:7)
    at createScript (vm.js:251:10)
    at Object.runInThisContext (vm.js:303:10)
    at Module._compile (internal/modules/cjs/loader.js:657:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
{}
```

**Comment by pacoyang** [comment]
Same issue
```js
// fix: prevents error when .less files are required by node
if (typeof require !== 'undefined') {
  require.extensions['.less'] = file => {}
}
```
work will with `next build` but still getting error with `next export`, in version "8.0.x".
downgraded to "7.0.2" solve the problem.

**Comment by thecodeboss** [comment]
This require patch
```js
// fix: prevents error when .less files are required by node
if (typeof require !== 'undefined') {
  require.extensions['.less'] = file => {}
}
```
gets executed on the main `next export` process, but then when it forks to spawn a bunch of workers, they don't have this patch and so they fail once a `.less` file gets required.

I can't think of a workaround to ensure that workers execute that patch code prior to running their main logic.

**Comment by stephankaag** [comment]
Is anyone working on this? Or is the recommended solution to use v7 for the time being?

**Comment by revskill10** [comment]
@thecodeboss That hack/patch 
```js
// fix: prevents error when .less files are required by node
if (typeof require !== 'undefined') {
  require.extensions['.less'] = file => {}
}
```
ruied my common sense. Because i thought just using babel is enough in this case.
And as i know, it's deprecated in latest NodeJS version (`require.extensions` is deprecated)

**Comment by koolamusic** [comment]
What could be the solution to this issue ?

**Comment by Buhaiyang** [comment]
I have resolve this issue by manual import less not use 'babel-plugin-import'

**Comment by koolamusic** [comment]
What would be the alternative to `require.extensions` in Next

**Comment by pierre-b** [comment]
Hi, I'm running next 8.0.3 and still got the bug on export, any update please?

**Comment by bigwisu** [comment]
Next v8.1.0 also fails to export, I also verified that

`// fix: prevents error when .less files are required by node
if (typeof require !== 'undefined') {
  require.extensions['.less'] = file => {}
}`

is in the next.config.js. 

Still, no luck exporting for v8.1.0. It does succeed after downgrading to v7.0.2

**Comment by revskill10** [comment]
This could be resolved (maybe) if nextjs allows babel for server too, not just client.

**Comment by koolamusic** [comment]
No progress yet apparently

**Comment by samuelg123** [comment]
Still waiting

**Comment by pierre-b** [comment]
same here, looking forward upgrading to v8 when it's solved!

**Comment by jimmdd** [comment]
any one tried this plugin? works for me. [next-antd-aza-less](https://github.com/sdli/next-antd-aza-less), article by Steven can be found [here](https://www.yuque.com/steven-kkr5g/aza/ig3x9w):

**Comment by tgdn** [comment]
Fix?

**Comment by pierre-b** [comment]
had to switch to gatsby, sorry guys

**Comment by sanojsilva** [comment]
export still not working :(

**Comment by linhbkhn95** [comment]
same issue :((. who can this resolve? tks all

**Comment by samuelg123** [comment]
any update?

**Comment by aysark** [comment]
I run into other issues if i downgrade to v7.0.2 due to decorators... so there isn't a proper workaround currently :/

**Comment by koolamusic** [comment]
I think this mostly depends on environment and what other packages your app utilizes

**Comment by koolamusic** [comment]
Not sure how odd this may seem, but setting the package versions in `package.json` to use 

```json
"@zeit/next-less": "^1.0.1",
    "antd": "^3.5.4",
    "less": "3.0.4",
    "less-vars-to-js": "1.3.0",
    "next": "latest",
```

has worked for me so far

**Comment by aindong** [comment]
The problem still occurs,

```
> Build error occurred
{ /home/ubuntu/yoyo-website/node_modules/antd/lib/style/index.css:7
body {
     ^

SyntaxError: Unexpected token {
    at new Script (vm.js:80:7)
    at createScript (vm.js:274:10)
    at Object.runInThisContext (vm.js:326:10)
    at Module._compile (internal/modules/cjs/loader.js:664:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18) type: 'SyntaxError' }
Automatically optimizing pages .npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! with-ant-design@1.0.0 build: `next build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the with-ant-design@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ubuntu/.npm/_logs/2020-02-12T09_53_35_004Z-debug.log
```

**Comment by balazsorban44** [comment]
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
