### ISSUE TITLE
Error: Cannot find module 'graphql-tools'

### ISSUE THREAD

**Issue by TheoMer** [zeit/next.js#6209]
# Bug report

## Describe the bug
Heroku attempts to start, after making a deployment, and the following errors are issued.

```
2019-02-05T06:57:03.962782+00:00 app[web.1]: { Error: Cannot find module 'graphql-tools'
2019-02-05T06:57:03.962804+00:00 app[web.1]:     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
2019-02-05T06:57:03.962807+00:00 app[web.1]:     at Function.Module._load (internal/modules/cjs/loader.js:507:25)
2019-02-05T06:57:03.962809+00:00 app[web.1]:     at Module.require (internal/modules/cjs/loader.js:637:17)
2019-02-05T06:57:03.962810+00:00 app[web.1]:     at require (internal/modules/cjs/helpers.js:22:18)
2019-02-05T06:57:03.962813+00:00 app[web.1]:     at Object.<anonymous> (/app/.next/server/static/rtiDEJwC8_JWyySR5n06D/pages/_app.js:1880:18)
2019-02-05T06:57:03.962815+00:00 app[web.1]:     at __webpack_require__ (/app/.next/server/static/rtiDEJwC8_JWyySR5n06D/pages/_app.js:23:31)
2019-02-05T06:57:03.962817+00:00 app[web.1]:     at Object.<anonymous> (/app/.next/server/static/rtiDEJwC8_JWyySR5n06D/pages/_app.js:325:31)
2019-02-05T06:57:03.962819+00:00 app[web.1]:     at __webpack_require__ (/app/.next/server/static/rtiDEJwC8_JWyySR5n06D/pages/_app.js:23:31)
2019-02-05T06:57:03.962821+00:00 app[web.1]:     at Object.<anonymous> (/app/.next/server/static/rtiDEJwC8_JWyySR5n06D/pages/_app.js:1334:18)
2019-02-05T06:57:03.962823+00:00 app[web.1]:     at __webpack_require__ (/app/.next/server/static/rtiDEJwC8_JWyySR5n06D/pages/_app.js:23:31) code: 'MODULE_NOT_FOUND' }
2019-02-05T06:57:03.967744+00:00 app[web.1]: { Error: Cannot find module 'graphql-tools'
2019-02-05T06:57:03.967747+00:00 app[web.1]:     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
2019-02-05T06:57:03.967749+00:00 app[web.1]:     at Function.Module._load (internal/modules/cjs/loader.js:507:25)
2019-02-05T06:57:03.967750+00:00 app[web.1]:     at Module.require (internal/modules/cjs/loader.js:637:17)
2019-02-05T06:57:03.967752+00:00 app[web.1]:     at require (internal/modules/cjs/helpers.js:22:18)
2019-02-05T06:57:03.967754+00:00 app[web.1]:     at Object.<anonymous> (/app/.next/server/static/rtiDEJwC8_JWyySR5n06D/pages/_app.js:1880:18)
2019-02-05T06:57:03.967755+00:00 app[web.1]:     at __webpack_require__ (/app/.next/server/static/rtiDEJwC8_JWyySR5n06D/pages/_app.js:23:31)
2019-02-05T06:57:03.967757+00:00 app[web.1]:     at Object.<anonymous> (/app/.next/server/static/rtiDEJwC8_JWyySR5n06D/pages/_app.js:325:31)
2019-02-05T06:57:03.967759+00:00 app[web.1]:     at __webpack_require__ (/app/.next/server/static/rtiDEJwC8_JWyySR5n06D/pages/_app.js:23:31)
2019-02-05T06:57:03.967760+00:00 app[web.1]:     at Object.<anonymous> (/app/.next/server/static/rtiDEJwC8_JWyySR5n06D/pages/_app.js:1334:18)
2019-02-05T06:57:03.967762+00:00 app[web.1]:     at __webpack_require__ (/app/.next/server/static/rtiDEJwC8_JWyySR5n06D/pages/_app.js:23:31) code: 'MODULE_NOT_FOUND' }
2019-02-05T06:57:03.971424+00:00 app[web.1]: (node:30) UnhandledPromiseRejectionWarning: Error: Cannot find module 'graphql-tools'
2019-02-05T06:57:03.971428+00:00 app[web.1]:     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
2019-02-05T06:57:03.971429+00:00 app[web.1]:     at Function.Module._load (internal/modules/cjs/loader.js:507:25)
2019-02-05T06:57:03.971431+00:00 app[web.1]:     at Module.require (internal/modules/cjs/loader.js:637:17)
2019-02-05T06:57:03.971433+00:00 app[web.1]:     at require (internal/modules/cjs/helpers.js:22:18)
2019-02-05T06:57:03.971434+00:00 app[web.1]:     at Object.<anonymous> (/app/.next/server/static/rtiDEJwC8_JWyySR5n06D/pages/index.js:1880:18)
2019-02-05T06:57:03.971436+00:00 app[web.1]:     at __webpack_require__ (/app/.next/server/static/rtiDEJwC8_JWyySR5n06D/pages/index.js:23:31)
2019-02-05T06:57:03.971437+00:00 app[web.1]:     at Object.<anonymous> (/app/.next/server/static/rtiDEJwC8_JWyySR5n06D/pages/index.js:325:31)
2019-02-05T06:57:03.971439+00:00 app[web.1]:     at __webpack_require__ (/app/.next/server/static/rtiDEJwC8_JWyySR5n06D/pages/index.js:23:31)
2019-02-05T06:57:03.971441+00:00 app[web.1]:     at Object.<anonymous> (/app/.next/server/static/rtiDEJwC8_JWyySR5n06D/pages/index.js:1334:18)
2019-02-05T06:57:03.971443+00:00 app[web.1]:     at __webpack_require__ (/app/.next/server/static/rtiDEJwC8_JWyySR5n06D/pages/index.js:23:31)
2019-02-05T06:57:03.971541+00:00 app[web.1]: (node:30) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
```

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:
1. As per this issue previously being raised: [https://github.com/zeit/next.js/issues/198](https://github.com/zeit/next.js/issues/198)

## Expected behavior
As was the case up until yesterday, I expected the app to run successfuilly in the browser.

## Screenshots
As can be seen from my package.json, the graphql-tool package is specified in devDependencies.

![package-json](https://user-images.githubusercontent.com/15969262/52263339-ca3cf780-2926-11e9-81dc-c58b194ce14f.jpg)

My scripts are specified as follows:

![package-scripts](https://user-images.githubusercontent.com/15969262/52263441-17b96480-2927-11e9-8fd2-adeb478674f7.jpg)

## System information
 - Next 7.0.2
 - Heroku, which installs `...node 10.15.1`

**Comment by timneutkens** [comment]
Looks like the devdependencies weren't installed 🤔

**Comment by TheoMer** [comment]
@timneutkens Could be, although they do state that:

> By default, Heroku will install all dependencies listed in package.json under dependencies and devDependencies.

[https://devcenter.heroku.com/articles/nodejs-support](https://devcenter.heroku.com/articles/nodejs-support)
