### ISSUE TITLE
Can't get index.js to run correctly.

### ISSUE THREAD

**Issue by KhoaComp** [zeit/next.js#6214]
# Question about Next.js
Running through the startup guide, I was up to the "npm run dev" part where I started running into issues. I created a pages directory with an index.js but when trying to compile and run it on localhost:3000, this is the error it gives me. Also I am running Ubuntu 18.04 if that helps.

>  ERROR  Failed to compile with 1 errors                                                                                          17:55:19

 error  in ./pages/index.js

Module parse failed: Unexpected token (1:21)
You may need an appropriate loader to handle this file type.
export default () => <div>Welcome to next.js!</div>
| 
|     (function (Component, route) {

 @ multi ./pages/index.js

{ Error: Cannot find module './pages/index.js'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object../pages/index.js (/home/khoa/node_modules/next/.next/server/static/development/pages/index.js:103:18)
    at __webpack_require__ (/home/khoa/node_modules/next/.next/server/static/development/pages/index.js:23:31)
    at Object.3 (/home/khoa/node_modules/next/.next/server/static/development/pages/index.js:114:18)
    at __webpack_require__ (/home/khoa/node_modules/next/.next/server/static/development/pages/index.js:23:31)
    at /home/khoa/node_modules/next/.next/server/static/development/pages/index.js:91:18
    at Object.<anonymous> (/home/khoa/node_modules/next/.next/server/static/development/pages/index.js:94:10)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17) code: 'MODULE_NOT_FOUND' }
Client pings, but there's no entry for page: /_error
^Cgot signal SIGINT, exiting

**Comment by timneutkens** [comment]
It sounds like you have a `.babelrc` up the directory tree.
