### ISSUE TITLE
running `yarn dev` crashes

### ISSUE THREAD

**Issue by valpinkman** [zeit/next.js#6228]
# Bug report

## Describe the bug

Impossible to start the dev server on next v7+

## To Reproduce

 1. `touch project && cd project`
 2. `yarn init`
 3. `yarn add react react-dom next`
 4. add to `package.json` 
```json
{
  "scripts": {
    "dev": "next"
  }
}
```
 5. create `pages/index.js` with `export default () => <div>Hello</div>`
 6. run `yarn dev`
 7. Error in console

```
Error: custom keyword definition is invalid: data.errors should be boolean
    at Ajv.addKeyword (/Users/valpinkman/Projects/dr0p-blog/knowyourbass/node_modules/ajv/lib/keyword.js:65:13)
    at module.exports (/Users/valpinkman/Projects/dr0p-blog/knowyourbass/node_modules/ajv-errors/index.js:10:7)
    at Object.<anonymous> (/Users/valpinkman/Projects/dr0p-blog/knowyourbass/node_modules/terser-webpack-plugin/node_modules/schema-utils/src/validateOptions.js:22:1)
    at Module._compile (internal/modules/cjs/loader.js:734:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:745:10)
    at Module.load (internal/modules/cjs/loader.js:626:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:566:12)
    at Function.Module._load (internal/modules/cjs/loader.js:558:3)
    at Module.require (internal/modules/cjs/loader.js:663:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/valpinkman/Projects/dr0p-blog/knowyourbass/node_modules/terser-webpack-plugin/node_modules/schema-utils/src/index.js:7:25)
    at Module._compile (internal/modules/cjs/loader.js:734:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:745:10)
    at Module.load (internal/modules/cjs/loader.js:626:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:566:12)
    at Function.Module._load (internal/modules/cjs/loader.js:558:3)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

## Expected behavior
The next dev server should start so I can run my app locally

## System information
 - OS: macOS Mojave 10.14.4 Beta (18E184e)
 - Version of Next.js: v7.0.2
 - Node Version: v11.9.0
 - React Version: v16.8.1

**Comment by WebchemistGenn** [comment]
updated ajv version 6.7.0 -> 6.9.0

yarn add ajv@6.7.0 or npm install ajv@6.7.0
