### ISSUE TITLE
[2.0-beta12] error loading main.js and commons.js

### ISSUE THREAD

**Issue by mattapperson** [zeit/next.js#626]
I have been working to port an existing app to 2.0 (both to test it out and to just casually begin porting to it as it's developed) and noticed the following issue (also replicated on the custom server example).
The page loads via SSR but throws a 500 error when calling the js bundles `http://localhost:3000/_next/commons.js` and `http://localhost:3000/_next/main.js`

This happens when running Node: 6.0.0... I have not tested other node versions
<details>
 <summary>TypeError: Cannot read property 'R_OK' of undefined</summary>
TypeError: Cannot read property 'R_OK' of undefined
    at _callee6$ (/Users/mattapperson/Development/Theocratic/kh-mirror-web/node_modules/next/dist/server/render.js:283:72)
    at tryCatch (/Users/mattapperson/Development/Theocratic/kh-mirror-web/node_modules/regenerator-runtime/runtime.js:64:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Users/mattapperson/Development/Theocratic/kh-mirror-web/node_modules/regenerator-runtime/runtime.js:355:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Users/mattapperson/Development/Theocratic/kh-mirror-web/node_modules/regenerator-runtime/runtime.js:116:21)
    at step (/Users/mattapperson/Development/Theocratic/kh-mirror-web/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at /Users/mattapperson/Development/Theocratic/kh-mirror-web/node_modules/babel-runtime/helpers/asyncToGenerator.js:35:14
    at new Promise (/Users/mattapperson/Development/Theocratic/kh-mirror-web/node_modules/core-js/library/modules/es6.promise.js:191:7)
    at /Users/mattapperson/Development/Theocratic/kh-mirror-web/node_modules/babel-runtime/helpers/asyncToGenerator.js:14:12
    at serveStaticWithGzip (/Users/mattapperson/Development/Theocratic/kh-mirror-web/node_modules/next/dist/server/render.js:313:19)
    at Server._callee5$ (/Users/mattapperson/Development/Theocratic/kh-mirror-web/node_modules/next/dist/server/index.js:222:58)
</details>

**Comment by Chathula** [comment]
here also!
