### ISSUE TITLE
with-inferno example doesn't work with next 8.0.0

### ISSUE THREAD

**Issue by willross** [zeit/next.js#6264]
# Bug report

## Describe the bug

```with-inferno```  example doesn't work with ```next@8.0.0```.
The following error is produced when running ```npm run build```:
```
ModuleNotFoundError: Module not found: Error: Can't resolve 'private-next-pages/about.js' in '/home/user/next-inferno/using-inferno-app'
    at factory.create (/home/user/next-inferno/using-inferno-app/node_modules/webpack/lib/Compilation.js:823:10)
    at factory (/home/user/next-inferno/using-inferno-app/node_modules/webpack/lib/NormalModuleFactory.js:397:22)
    at resolver (/home/user/next-inferno/using-inferno-app/node_modules/webpack/lib/NormalModuleFactory.js:130:21)
    at asyncLib.parallel (/home/user/next-inferno/using-inferno-app/node_modules/webpack/lib/NormalModuleFactory.js:224:22)
    at /home/user/next-inferno/using-inferno-app/node_modules/neo-async/async.js:2825:7
    at /home/user/next-inferno/using-inferno-app/node_modules/neo-async/async.js:6886:13
    at normalResolver.resolve (/home/user/next-inferno/using-inferno-app/node_modules/webpack/lib/NormalModuleFactory.js:214:25)
    at doResolve (/home/user/next-inferno/using-inferno-app/node_modules/enhanced-resolve/lib/Resolver.js:184:12)
    at hook.callAsync (/home/user/next-inferno/using-inferno-app/node_modules/enhanced-resolve/lib/Resolver.js:238:5)
    at _fn0 (eval at create (/home/user/next-inferno/using-inferno-app/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:15:1)
    at resolver.doResolve (/home/user/next-inferno/using-inferno-app/node_modules/enhanced-resolve/lib/UnsafeCachePlugin.js:37:5)
    at hook.callAsync (/home/user/next-inferno/using-inferno-app/node_modules/enhanced-resolve/lib/Resolver.js:238:5)
    at _fn0 (eval at create (/home/user/next-inferno/using-inferno-app/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:15:1)
    at hook.callAsync (/home/user/next-inferno/using-inferno-app/node_modules/enhanced-resolve/lib/Resolver.js:238:5)
    at _fn0 (eval at create (/home/user/next-inferno/using-inferno-app/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:12:1)
    at resolver.doResolve (/home/user/next-inferno/using-inferno-app/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:42:38)
resolve 'private-next-pages/about.js' in '/home/user/next-inferno/using-inferno-app'
  Parsed request is a module
  using description file: /home/user/next-inferno/using-inferno-app/package.json (relative path: .)
    Field 'browser' doesn't contain a valid alias configuration
    resolve as module
      /home/user/next-inferno/node_modules doesn't exist or is not a directory
      /home/user/node_modules doesn't exist or is not a directory
      /home/node_modules doesn't exist or is not a directory
      /node_modules doesn't exist or is not a directory
      looking for modules in /home/user/next-inferno/using-inferno-app/node_modules
        using description file: /home/user/next-inferno/using-inferno-app/package.json (relative path: ./node_modules)
          Field 'browser' doesn't contain a valid alias configuration
      looking for modules in /home/user/node_modules
        No description file found
        Field 'browser' doesn't contain a valid alias configuration
          using description file: /home/user/next-inferno/using-inferno-app/package.json (relative path: ./node_modules/private-next-pages/about.js)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              /home/user/next-inferno/using-inferno-app/node_modules/private-next-pages/about.js doesn't exist
            .wasm
              Field 'browser' doesn't contain a valid alias configuration
              /home/user/next-inferno/using-inferno-app/node_modules/private-next-pages/about.js.wasm doesn't exist
            .mjs
              Field 'browser' doesn't contain a valid alias configuration
        No description file found
        no extension
          Field 'browser' doesn't contain a valid alias configuration
              /home/user/next-inferno/using-inferno-app/node_modules/private-next-pages/about.js.mjs doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
          /home/user/node_modules/private-next-pages/about.js doesn't exist
        .wasm
          Field 'browser' doesn't contain a valid alias configuration
              /home/user/next-inferno/using-inferno-app/node_modules/private-next-pages/about.js.js doesn't exist
            .jsx
              Field 'browser' doesn't contain a valid alias configuration
          /home/user/node_modules/private-next-pages/about.js.wasm doesn't exist
        .mjs
          Field 'browser' doesn't contain a valid alias configuration
              /home/user/next-inferno/using-inferno-app/node_modules/private-next-pages/about.js.jsx doesn't exist
            .json
              Field 'browser' doesn't contain a valid alias configuration
          /home/user/node_modules/private-next-pages/about.js.mjs doesn't exist
        .js
          Field 'browser' doesn't contain a valid alias configuration
              /home/user/next-inferno/using-inferno-app/node_modules/private-next-pages/about.js.json doesn't exist
          /home/user/node_modules/private-next-pages/about.js.js doesn't exist
        .jsx
          Field 'browser' doesn't contain a valid alias configuration
            as directory
              /home/user/next-inferno/using-inferno-app/node_modules/private-next-pages/about.js doesn't exist
          /home/user/node_modules/private-next-pages/about.js.jsx doesn't exist
        .json
          Field 'browser' doesn't contain a valid alias configuration
          /home/user/node_modules/private-next-pages/about.js.json doesn't exist
        as directory
          /home/user/node_modules/private-next-pages/about.js doesn't exist
ModuleNotFoundError: Module not found: Error: Can't resolve 'private-next-pages/index.js' in '/home/user/next-inferno/using-inferno-app'
    at factory.create (/home/user/next-inferno/using-inferno-app/node_modules/webpack/lib/Compilation.js:823:10)
    at factory (/home/user/next-inferno/using-inferno-app/node_modules/webpack/lib/NormalModuleFactory.js:397:22)
    at resolver (/home/user/next-inferno/using-inferno-app/node_modules/webpack/lib/NormalModuleFactory.js:130:21)
    at asyncLib.parallel (/home/user/next-inferno/using-inferno-app/node_modules/webpack/lib/NormalModuleFactory.js:224:22)
    at /home/user/next-inferno/using-inferno-app/node_modules/neo-async/async.js:2825:7
    at /home/user/next-inferno/using-inferno-app/node_modules/neo-async/async.js:6886:13
    at normalResolver.resolve (/home/user/next-inferno/using-inferno-app/node_modules/webpack/lib/NormalModuleFactory.js:214:25)
    at doResolve (/home/user/next-inferno/using-inferno-app/node_modules/enhanced-resolve/lib/Resolver.js:184:12)
    at hook.callAsync (/home/user/next-inferno/using-inferno-app/node_modules/enhanced-resolve/lib/Resolver.js:238:5)
    at _fn0 (eval at create (/home/user/next-inferno/using-inferno-app/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:15:1)
    at resolver.doResolve (/home/user/next-inferno/using-inferno-app/node_modules/enhanced-resolve/lib/UnsafeCachePlugin.js:37:5)
    at hook.callAsync (/home/user/next-inferno/using-inferno-app/node_modules/enhanced-resolve/lib/Resolver.js:238:5)
    at _fn0 (eval at create (/home/user/next-inferno/using-inferno-app/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:15:1)
    at hook.callAsync (/home/user/next-inferno/using-inferno-app/node_modules/enhanced-resolve/lib/Resolver.js:238:5)
    at _fn0 (eval at create (/home/user/next-inferno/using-inferno-app/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:12:1)
    at resolver.doResolve (/home/user/next-inferno/using-inferno-app/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:42:38)
resolve 'private-next-pages/index.js' in '/home/user/next-inferno/using-inferno-app'
  Parsed request is a module
  using description file: /home/user/next-inferno/using-inferno-app/package.json (relative path: .)
    Field 'browser' doesn't contain a valid alias configuration
    resolve as module
      /home/user/next-inferno/node_modules doesn't exist or is not a directory
      /home/user/node_modules doesn't exist or is not a directory
      /home/node_modules doesn't exist or is not a directory
      /node_modules doesn't exist or is not a directory
      looking for modules in /home/user/next-inferno/using-inferno-app/node_modules
        using description file: /home/user/next-inferno/using-inferno-app/package.json (relative path: ./node_modules)
          Field 'browser' doesn't contain a valid alias configuration
      looking for modules in /home/user/node_modules
        No description file found
        Field 'browser' doesn't contain a valid alias configuration
          using description file: /home/user/next-inferno/using-inferno-app/package.json (relative path: ./node_modules/private-next-pages/index.js)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              /home/user/next-inferno/using-inferno-app/node_modules/private-next-pages/index.js doesn't exist
            .wasm
              Field 'browser' doesn't contain a valid alias configuration
              /home/user/next-inferno/using-inferno-app/node_modules/private-next-pages/index.js.wasm doesn't exist
            .mjs
              Field 'browser' doesn't contain a valid alias configuration
        No description file found
        no extension
          Field 'browser' doesn't contain a valid alias configuration
              /home/user/next-inferno/using-inferno-app/node_modules/private-next-pages/index.js.mjs doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
          /home/user/node_modules/private-next-pages/index.js doesn't exist
        .wasm
          Field 'browser' doesn't contain a valid alias configuration
              /home/user/next-inferno/using-inferno-app/node_modules/private-next-pages/index.js.js doesn't exist
            .jsx
              Field 'browser' doesn't contain a valid alias configuration
          /home/user/node_modules/private-next-pages/index.js.wasm doesn't exist
        .mjs
          Field 'browser' doesn't contain a valid alias configuration
              /home/user/next-inferno/using-inferno-app/node_modules/private-next-pages/index.js.jsx doesn't exist
            .json
              Field 'browser' doesn't contain a valid alias configuration
          /home/user/node_modules/private-next-pages/index.js.mjs doesn't exist
        .js
          Field 'browser' doesn't contain a valid alias configuration
              /home/user/next-inferno/using-inferno-app/node_modules/private-next-pages/index.js.json doesn't exist
          /home/user/node_modules/private-next-pages/index.js.js doesn't exist
        .jsx
          Field 'browser' doesn't contain a valid alias configuration
            as directory
              /home/user/next-inferno/using-inferno-app/node_modules/private-next-pages/index.js doesn't exist
          /home/user/node_modules/private-next-pages/index.js.jsx doesn't exist
        .json
          Field 'browser' doesn't contain a valid alias configuration
          /home/user/node_modules/private-next-pages/index.js.json doesn't exist
        as directory
          /home/user/node_modules/private-next-pages/index.js doesn't exist
ModuleNotFoundError: Module not found: Error: Can't resolve 'private-next-pages/about.js' in '/home/user/next-inferno/using-inferno-app'
    at factory.create (/home/user/next-inferno/using-inferno-app/node_modules/webpack/lib/Compilation.js:823:10)
    at factory (/home/user/next-inferno/using-inferno-app/node_modules/webpack/lib/NormalModuleFactory.js:397:22)
    at resolver (/home/user/next-inferno/using-inferno-app/node_modules/webpack/lib/NormalModuleFactory.js:130:21)
    at asyncLib.parallel (/home/user/next-inferno/using-inferno-app/node_modules/webpack/lib/NormalModuleFactory.js:224:22)
    at /home/user/next-inferno/using-inferno-app/node_modules/neo-async/async.js:2825:7
    at /home/user/next-inferno/using-inferno-app/node_modules/neo-async/async.js:6886:13
    at normalResolver.resolve (/home/user/next-inferno/using-inferno-app/node_modules/webpack/lib/NormalModuleFactory.js:214:25)
    at doResolve (/home/user/next-inferno/using-inferno-app/node_modules/enhanced-resolve/lib/Resolver.js:184:12)
    at hook.callAsync (/home/user/next-inferno/using-inferno-app/node_modules/enhanced-resolve/lib/Resolver.js:238:5)
    at _fn0 (eval at create (/home/user/next-inferno/using-inferno-app/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:15:1)
    at resolver.doResolve (/home/user/next-inferno/using-inferno-app/node_modules/enhanced-resolve/lib/UnsafeCachePlugin.js:37:5)
    at hook.callAsync (/home/user/next-inferno/using-inferno-app/node_modules/enhanced-resolve/lib/Resolver.js:238:5)
    at _fn0 (eval at create (/home/user/next-inferno/using-inferno-app/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:15:1)
    at hook.callAsync (/home/user/next-inferno/using-inferno-app/node_modules/enhanced-resolve/lib/Resolver.js:238:5)
    at _fn0 (eval at create (/home/user/next-inferno/using-inferno-app/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:12:1)
    at resolver.doResolve (/home/user/next-inferno/using-inferno-app/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:42:38)
resolve 'private-next-pages/about.js' in '/home/user/next-inferno/using-inferno-app'
  Parsed request is a module
  using description file: /home/user/next-inferno/using-inferno-app/package.json (relative path: .)
    resolve as module
      /home/user/next-inferno/node_modules doesn't exist or is not a directory
      /home/user/node_modules doesn't exist or is not a directory
      /home/node_modules doesn't exist or is not a directory
      /node_modules doesn't exist or is not a directory
      looking for modules in /home/user/node_modules
        No description file found
      looking for modules in /home/user/next-inferno/using-inferno-app/node_modules
        using description file: /home/user/next-inferno/using-inferno-app/package.json (relative path: ./node_modules)
          using description file: /home/user/next-inferno/using-inferno-app/package.json (relative path: ./node_modules/private-next-pages/about.js)
            no extension
              /home/user/next-inferno/using-inferno-app/node_modules/private-next-pages/about.js doesn't exist
            .wasm
              /home/user/next-inferno/using-inferno-app/node_modules/private-next-pages/about.js.wasm doesn't exist
        No description file found
            .js
              /home/user/next-inferno/using-inferno-app/node_modules/private-next-pages/about.js.js doesn't exist
        no extension
          /home/user/node_modules/private-next-pages/about.js doesn't exist
            .mjs
              /home/user/next-inferno/using-inferno-app/node_modules/private-next-pages/about.js.mjs doesn't exist
        .wasm
          /home/user/node_modules/private-next-pages/about.js.wasm doesn't exist
            .jsx
              /home/user/next-inferno/using-inferno-app/node_modules/private-next-pages/about.js.jsx doesn't exist
        .js
          /home/user/node_modules/private-next-pages/about.js.js doesn't exist
            .json
              /home/user/next-inferno/using-inferno-app/node_modules/private-next-pages/about.js.json doesn't exist
        .mjs
          /home/user/node_modules/private-next-pages/about.js.mjs doesn't exist
            as directory
              /home/user/next-inferno/using-inferno-app/node_modules/private-next-pages/about.js doesn't exist
        .jsx
          /home/user/node_modules/private-next-pages/about.js.jsx doesn't exist
        .json
          /home/user/node_modules/private-next-pages/about.js.json doesn't exist
        as directory
          /home/user/node_modules/private-next-pages/about.js doesn't exist
ModuleNotFoundError: Module not found: Error: Can't resolve 'private-next-pages/index.js' in '/home/user/next-inferno/using-inferno-app'
    at factory.create (/home/user/next-inferno/using-inferno-app/node_modules/webpack/lib/Compilation.js:823:10)
    at factory (/home/user/next-inferno/using-inferno-app/node_modules/webpack/lib/NormalModuleFactory.js:397:22)
    at resolver (/home/user/next-inferno/using-inferno-app/node_modules/webpack/lib/NormalModuleFactory.js:130:21)
    at asyncLib.parallel (/home/user/next-inferno/using-inferno-app/node_modules/webpack/lib/NormalModuleFactory.js:224:22)
    at /home/user/next-inferno/using-inferno-app/node_modules/neo-async/async.js:2825:7
    at /home/user/next-inferno/using-inferno-app/node_modules/neo-async/async.js:6886:13
    at normalResolver.resolve (/home/user/next-inferno/using-inferno-app/node_modules/webpack/lib/NormalModuleFactory.js:214:25)
    at doResolve (/home/user/next-inferno/using-inferno-app/node_modules/enhanced-resolve/lib/Resolver.js:184:12)
    at hook.callAsync (/home/user/next-inferno/using-inferno-app/node_modules/enhanced-resolve/lib/Resolver.js:238:5)
    at _fn0 (eval at create (/home/user/next-inferno/using-inferno-app/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:15:1)
    at resolver.doResolve (/home/user/next-inferno/using-inferno-app/node_modules/enhanced-resolve/lib/UnsafeCachePlugin.js:37:5)
    at hook.callAsync (/home/user/next-inferno/using-inferno-app/node_modules/enhanced-resolve/lib/Resolver.js:238:5)
    at _fn0 (eval at create (/home/user/next-inferno/using-inferno-app/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:15:1)
    at hook.callAsync (/home/user/next-inferno/using-inferno-app/node_modules/enhanced-resolve/lib/Resolver.js:238:5)
    at _fn0 (eval at create (/home/user/next-inferno/using-inferno-app/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:12:1)
    at resolver.doResolve (/home/user/next-inferno/using-inferno-app/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:42:38)
resolve 'private-next-pages/index.js' in '/home/user/next-inferno/using-inferno-app'
  Parsed request is a module
  using description file: /home/user/next-inferno/using-inferno-app/package.json (relative path: .)
    resolve as module
      /home/user/next-inferno/node_modules doesn't exist or is not a directory
      /home/user/node_modules doesn't exist or is not a directory
      /home/node_modules doesn't exist or is not a directory
      /node_modules doesn't exist or is not a directory
      looking for modules in /home/user/node_modules
        No description file found
      looking for modules in /home/user/next-inferno/using-inferno-app/node_modules
        using description file: /home/user/next-inferno/using-inferno-app/package.json (relative path: ./node_modules)
          using description file: /home/user/next-inferno/using-inferno-app/package.json (relative path: ./node_modules/private-next-pages/index.js)
            no extension
              /home/user/next-inferno/using-inferno-app/node_modules/private-next-pages/index.js doesn't exist
            .wasm
              /home/user/next-inferno/using-inferno-app/node_modules/private-next-pages/index.js.wasm doesn't exist
        No description file found
            .js
              /home/user/next-inferno/using-inferno-app/node_modules/private-next-pages/index.js.js doesn't exist
        no extension
          /home/user/node_modules/private-next-pages/index.js doesn't exist
            .mjs
              /home/user/next-inferno/using-inferno-app/node_modules/private-next-pages/index.js.mjs doesn't exist
        .wasm
          /home/user/node_modules/private-next-pages/index.js.wasm doesn't exist
            .jsx
              /home/user/next-inferno/using-inferno-app/node_modules/private-next-pages/index.js.jsx doesn't exist
        .js
          /home/user/node_modules/private-next-pages/index.js.js doesn't exist
            .json
              /home/user/next-inferno/using-inferno-app/node_modules/private-next-pages/index.js.json doesn't exist
        .mjs
          /home/user/node_modules/private-next-pages/index.js.mjs doesn't exist
            as directory
              /home/user/next-inferno/using-inferno-app/node_modules/private-next-pages/index.js doesn't exist
        .jsx
          /home/user/node_modules/private-next-pages/index.js.jsx doesn't exist
        .json
          /home/user/node_modules/private-next-pages/index.js.json doesn't exist
        as directory
          /home/user/node_modules/private-next-pages/index.js doesn't exist
> Build error occurred
Error: > Build failed because of webpack errors
    at Object.build [as default] (/home/user/next-inferno/using-inferno-app/node_modules/next/dist/build/index.js:69:15)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
```

## To Reproduce

```npx create-next-app --example using-inferno using-inferno-app && cd using-inferno-app && npm run build```

## Expected behavior

Should build with no errors.

## System information
 - OS: Ubuntu 18.04
 - Version of Next.js: 8.0.0

## Additional context

Works when using ```next@7.0.2```

**Comment by timneutkens** [comment]
Seems like the examples are not taking into account aliases coming from Next.js itself (which Next.js does add), can you create a PR that spreads the aliases from `config` 👍

**Comment by willross** [comment]
@timneutkens Sure. I've tried that and it works, but then I get the ```TypeError: React.createContext is not a function``` error, and I'm still figuring out a good way to polyfill ```createContext``` for ```next``` with ```inferno```. I'll create a PR when I figure it out.

**Comment by timneutkens** [comment]
Awesome thank you @willross 🙏

**Comment by willross** [comment]
Unfortunately, we have decided not to use inferno, and in the foreseeable future I won't have time to investigate this further. Hopefully someone will pick this up!

**Comment by crutchcorn** [comment]
I will be fixing this as part of updating almost all of the examples

**Comment by skdigital** [comment]
any news on this?

**Comment by AndyOGo** [comment]
@timneutkens 
Is this issue closed because it have been fixed or won't be fixed?

I would really like to see support for `inferno` 🙏

**Comment by balazsorban44** [comment]
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
