### ISSUE TITLE
with-nerv example doesn't work on next@7.0.2 and next@8.0.0

### ISSUE THREAD

**Issue by willross** [zeit/next.js#6267]
# Bug report

## Describe the bug

```with-nerv``` example doesn't work on neither ```next@8.0.0``` nor ```next@7.0.2```.

On ```next@8.0.0``` the same error as in [this issue about ```with-inferno``` example](https://github.com/zeit/next.js/issues/6264) is occurring.

On ```next@7.0.2``` the following error is thrown: 

```
var isMacSafari = navigator && navigator.platform && /mac/i.test(navigator.platform) && /^((?!chrome|android).)*safari/i.test(navigator.userAgent);
                  ^

ReferenceError: navigator is not defined
    at Object.<anonymous> (/home/user/next-nerv/using-nerv-app/node_modules/nervjs/dist/index.js:47:19)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/user/next-nerv/using-nerv-app/node_modules/nervjs/index.js:1:80)
    at Module._compile (module.js:653:30)
```

## To Reproduce

```npx create-next-app --example using-nerv using-nerv-app && cd using-nerv-app && npm run build && npm run start```

## Additional context

It appears that this is a SSR issue, but simply aliasing ```react-dom/server``` to ```nerv-server``` did not help.

**Comment by Timer** [comment]
I'll tag this as up for grabs -- feel welcome to fix it! 😄

**Comment by YL2014** [comment]
the same issue on `next@8.0.3`

**Comment by timneutkens** [comment]
@YL2014 as said

> I'll tag this as up for grabs -- feel welcome to fix it! 😄

**Comment by crutchcorn** [comment]
I will be fixing this as part of updating almost all of the examples

**Comment by balazsorban44** [comment]
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
