### ISSUE TITLE
Cannot browse the application

### ISSUE THREAD

**Issue by nodegin** [zeit/next.js#63]
By visiting the index page location at `http://localhost/` the following thrown:

```
> next start

> Ready on http://localhost:3000
{ [Error: Cannot find module /home/ubuntu/workspace/.next/dist/pages/_error] code: 'ENOENT' }
```

Filesystem:
```
- package.json
- node_modules
- pages
    - index.js
```

`index.js`:
```
import React from 'react'

export default () => (
  <div>Welcome to next.js!</div>
)
```

Thanks for help!

**Comment by vdemedes** [comment]
Try running `next` instead of `next start`. `next start` expects that you executed `next build` before.

**Comment by nodegin** [comment]
@vdemedes Oh that was true, thank you

However I face another issue that some dependencies were missing.

```

Module build failed: ReferenceError: Unknown plugin "transform-async-to-generator" specified in "base" at 0, attempted to resolve relative to "/home/ubuntu/workspace/pages"
    at /home/ubuntu/workspace/node_modules/next/node_modules/babel-core/lib/transformation/file/options/option-manager.js:176:17
    at Array.map (native)
    at Function.normalisePlugins (/home/ubuntu/workspace/node_modules/next/node_modules/babel-core/lib/transformation/file/options/option-manager.js:154:20)
    at OptionManager.mergeOptions (/home/ubuntu/workspace/node_modules/next/node_modules/babel-core/lib/transformation/file/options/option-manager.js:228:36)
    at OptionManager.init (/home/ubuntu/workspace/node_modules/next/node_modules/babel-core/lib/transformation/file/options/option-manager.js:373:12)
    at File.initOptions (/home/ubuntu/workspace/node_modules/next/node_modules/babel-core/lib/transformation/file/index.js:221:65)
    at new File (/home/ubuntu/workspace/node_modules/next/node_modules/babel-core/lib/transformation/file/index.js:141:24)
    at Pipeline.transform (/home/ubuntu/workspace/node_modules/next/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at transpile (/home/ubuntu/workspace/node_modules/next/node_modules/babel-loader/index.js:38:20)
    at Object.module.exports (/home/ubuntu/workspace/node_modules/next/node_modules/babel-loader/index.js:131:12)
 @ multi bundles/pages/index.js
> Ready on http://localhost:3000
{ [Error: Cannot find module 'strip-ansi'] code: 'MODULE_NOT_FOUND' }
```

Fixed by running

```
npm i -S babel-plugin-transform-async-to-generator
npm i -S babel-plugin-transform-object-rest-spread
npm i -S babel-plugin-transform-class-properties
npm i -S babel-plugin-transform-runtime
npm i -S strip-ansi
```

Not sure why next didn't include these modules?
