### ISSUE TITLE
[2.0-beta12] Not working 

### ISSUE THREAD

**Issue by mr47** [zeit/next.js#642]
I have a simple project with one page `index.js` using programmatic api (express)
Super simple page: 
```jsx
import React from 'react'
import BaseTemplate from '../components/BaseTemplate'
import MainPage from '../components/MainPage'

export default class extends React.Component {
    static async getInitialProps({ req }) {
        const isServer = !!req;
        return {
            isServer: isServer
        }
    }

    render() {
        return (
            <BaseTemplate>
                <MainPage />
            </BaseTemplate>
        )
    }
}
```

updated to latest version of `next` and always getting error:
```
 SyntaxError: Unexpected token m in JSON at position 0
    at Object.parse (native)
    at _callee$ (E:\projects\mr47\client\node_modules\next\dist\server\read-page.js:51:32)
    at tryCatch (E:\projects\mr47\client\node_modules\regenerator-runtime\runtime.js:64:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (E:\projects\mr47\client\node_modules\regenerator-runtime\runtime.js:355:22)
 at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (E:\projects\mr47\client\node_modules\regenerator-runtime\runtime.js:116:21)
 at step (E:\projects\mr47\client\node_modules\babel-runtime\helpers\asyncToGenerator.js:17:30)
 at E:\projects\mr47\client\node_modules\babel-runtime\helpers\asyncToGenerator.js:28:13
 at propagateAslWrapper (E:\projects\mr47\client\node_modules\async-listener\index.js:421:23)
 at E:\projects\mr47\client\node_modules\async-listener\glue.js:188:31
 at E:\projects\mr47\client\node_modules\async-listener\index.js:458:70
```
most part of error log ase useless but it's seems its connected to https://github.com/zeit/next.js/commit/165924b71b290388fbbacbc2a74cba80e1058133

`JsonPagesPlugin` making some black magic on pages.

Thanks!

**Comment by arunoda** [comment]
Hey, could you wrap this into a small repo and send to me.
Also, tell me your OS and node version.

**Comment by arunoda** [comment]
Actually, we did a fix for windows here: https://github.com/zeit/next.js/pull/611
It's not released yet.

**Comment by mr47** [comment]
@arunoda i'll test master version in few min. Thanks!
