### ISSUE TITLE
Module not found: Can't resolve './dist/server/document' in '/app/node_modules/next'

### ISSUE THREAD

**Issue by foxhound87** [zeit/next.js#6420]
I'm updating from v7 to v8 and I get this error:

```
Failed to compile.

./node_modules/next/document.js
Module not found: Can't resolve './dist/server/document' in '/app/node_modules/next'
{ Error: Cannot find module '/app/.next/server/pages-manifest.json'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:594:15)
    at Function.Module._load (internal/modules/cjs/loader.js:520:25)
    at Module.require (internal/modules/cjs/loader.js:650:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at getPagePath (/app/node_modules/next-server/dist/server/require.js:14:27)
    at Object.requirePage (/app/node_modules/next-server/dist/server/require.js:30:22)
    at Object.loadComponents (/app/node_modules/next-server/dist/server/load-components.js:15:34)
    at DevServer.renderToHTMLWithComponents (/app/node_modules/next-server/dist/server/next-server.js:224:48)
    at DevServer.renderErrorToHTML (/app/node_modules/next-server/dist/server/next-server.js:260:21)
    at DevServer.renderErrorToHTML (/app/node_modules/next/dist/server/next-dev-server.js:111:37)
    at process._tickCallback (internal/process/next_tick.js:68:7) code: 'MODULE_NOT_FOUND' }
(node:98) UnhandledPromiseRejectionWarning: Error: Cannot find module '/app/.next/server/pages-manifest.json'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:594:15)
    at Function.Module._load (internal/modules/cjs/loader.js:520:25)
    at Module.require (internal/modules/cjs/loader.js:650:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at getPagePath (/app/node_modules/next-server/dist/server/require.js:14:27)
    at Object.requirePage (/app/node_modules/next-server/dist/server/require.js:30:22)
    at Object.loadComponents (/app/node_modules/next-server/dist/server/load-components.js:15:34)
    at DevServer.renderToHTMLWithComponents (/app/node_modules/next-server/dist/server/next-server.js:224:48)
    at DevServer.renderErrorToHTML (/app/node_modules/next-server/dist/server/next-server.js:260:21)
    at DevServer.renderErrorToHTML (/app/node_modules/next/dist/server/next-dev-server.js:118:26)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:98) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 8)
```

**Comment by foxhound87** [comment]
Solved, I recreated the docker container, removing `.next` folder.
