### ISSUE TITLE
Get apolloState failed causes no SSR, Apollo Next.js deployed on Now 2.0 

### ISSUE THREAD

**Issue by ducdev** [zeit/next.js#6428]
# Bug report
Get apolloState on server failed causing no SSR
## Describe the bug
I have my apollo next app deployed on now 2.0 serverless.
I also have a back-end apollo server with `/graphql` endpoint deployed on now 2.0 serverless on a sub domain of above client app.
Everything include SSR is OK on local development (port 3000 & 4000). But it has an issue appear in `now logs` of deployed client app, shown below:

```
Error while running `getDataFromTree` { Error: Network error: Unexpected token  in JSON at position 0
                              at new ApolloError (/var/task/page.js:114:2230)
                              at /var/task/page.js:114:28333
                              at /var/task/page.js:114:38087
                              at Array.forEach (<anonymous>)
                              at /var/task/page.js:114:38060
                              at Map.forEach (<anonymous>)
                              at QueryManager.broadcastQueries (/var/task/page.js:114:37943)
                              at /var/task/page.js:114:26821
                              at <anonymous>
                              at process._tickDomainCallback (internal/process/next_tick.js:228:7)
                            graphQLErrors: [],
                            networkError:
                             { ServerParseError: Unexpected token  in JSON at position 0
                              at JSON.parse (<anonymous>)
                              at /var/task/page.js:147:182136
                              at <anonymous>
                              at process._tickDomainCallback (internal/process/next_tick.js:228:7)
                               name: 'ServerParseError',
                               response:
                                Response {
                                  size: 0,
                                  timeout: 0,
                                  [Symbol(Body internals)]: [Object],
                                  [Symbol(Response internals)]: [Object] },
                               statusCode: 404,
                               bodyText: '\u0015M\u0005\u0000�4i���妪�J\t���h\u001dot*\u001c��\u0000N\u0007T�W5�\'�\u0014�\u0013�\u0013�e��Np����\u0002\n��,��\u0013�˲��f�m��Y�<���`1y`ོg>\\?\\=���_j�����\u0012��\u0010�\u001dƾ03��\u000b\u0013P@�\u0019RF٭2��\f�D\b�{%|[8��\u001c\u0005���7r2�\u001c���\u001a\u0018�(�\u0010�:[��Tk�4\u001e���.r��\u0011\u0012����j�4�Z`Bey�NE\u00165�\u001ay��4��\u0015&��c?�;\u001c\u0003���n����#\u0004�\u0007]òx��!\u000b�ꇧ�r\u0007�q��o8JU>�Ĩ��)��?\u001eX��ʇ�a�XV��FY˪��(����*o(�z��˪�NLN=B�eU���\u0015�,�{\\��2�\\gL4v�\u001b\u000e/$��Q�\u001c�e�8i�B�\t2�Np/u��0Q�4/B���\u0016\'\u001aȓ\u001c��3\tq�0d��`\'���8�n�D�,��\u0006\u0016���Q^<\u001c��qߍ\u001e����V�����\u0010;���I;\u001ca�r�:�G+��8�}�\u0012��鏗��\u00117\'����uF�V���\u0000\u0014�ٓ�k\u0016\u001a\u000f�@�h�Q0u�i�5\t�\fg��\u0004�RGp_5�uG7m��[�9��n�y��O�樁8�;����|�Zٶ�)K�8\u001dM�mOK���bٟ�h�s�\u001f���b\u001cK�\u001cZNPa\u001a9�ɲC��j���s\f\u001d(R\u0002pv�����;�dz�\u000e���#X�nWK\u000e�\u0015��\u001e�[\u001a0%��8ru����*@\n6�dI\bA�DeR�EW�&¤��\n\u001c9/`�ʘh<�\u0019�\u0011|\u000e���+���o���q�(�\b\u001d�kKl��\u0002O\u000b\u0006���%8ф�^��\u0002�����4��\u0016��&����\u0017&\u0000�\u0018��Mڠ߶[Ӝ\u0011�\u0017��V�Y��`��\u000b��W�P+c�a���������4�w�\u0001%�&�]�k�\u0010_J5\'\u001cw�,�d�4�Hrf�qls�x\u0015Lu\u0016�57�v[��\u0003\'�b\u001a�M��i\u0002P�\u000b�\f�\u000e}a�Y��\u000b' },
                            message: 'Network error: Unexpected token \u0015 in JSON at position 0',
                            extraInfo: undefined }
```

SSR is not working, but the strange thing is after a short while the client refetch the data on second try flawlessly. It shoudn't work if first try was 404 in result, right ?

**Comment by revskill10** [comment]
Is there any minimal repo for reproduction  ? Without it, there would be not enough context to identify the bugs.

**Comment by timneutkens** [comment]
It sounds like the API you're fetching is returning a malformed response (not JSON)
