### ISSUE TITLE
Module build failed: Error: Couldn't find preset "es2015" relative to directory ".../nextgram/pages"

### ISSUE THREAD

**Issue by gmondragon** [zeit/next.js#643]
Hi. I installed Next.js for the first time to test and when I run "npm run dev" it gives me the following error:

`Module build failed: Error: Couldn't find preset "es2015" relative to directory "/Users/gabriel/Developing/nextgram/pages"
    at /Users/gabriel/Developing/nextgram/node_modules/next/node_modules/babel-core/lib/transformation/file/options/option-manager.js:299:19
    at Array.map (native)
    at OptionManager.resolvePresets (/Users/gabriel/Developing/nextgram/node_modules/next/node_modules/babel-core/lib/transformation/file/options/option-manager.js:270:20)
    at OptionManager.mergePresets (/Users/gabriel/Developing/nextgram/node_modules/next/node_modules/babel-core/lib/transformation/file/options/option-manager.js:259:10)
    at OptionManager.mergeOptions (/Users/gabriel/Developing/nextgram/node_modules/next/node_modules/babel-core/lib/transformation/file/options/option-manager.js:244:14)
    at OptionManager.init (/Users/gabriel/Developing/nextgram/node_modules/next/node_modules/babel-core/lib/transformation/file/options/option-manager.js:374:12)
    at File.initOptions (/Users/gabriel/Developing/nextgram/node_modules/next/node_modules/babel-core/lib/transformation/file/index.js:216:65)
    at new File (/Users/gabriel/Developing/nextgram/node_modules/next/node_modules/babel-core/lib/transformation/file/index.js:139:24)
    at Pipeline.transform (/Users/gabriel/Developing/nextgram/node_modules/next/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at transpile (/Users/gabriel/Developing/nextgram/node_modules/next/node_modules/babel-loader/lib/index.js:41:20)`

I tried the example application "nextgram" and it turns out to give the same error.

Regards.

**Comment by victorkane** [comment]
I still have this problem. What am I doing wrong?

**Comment by gmondragon** [comment]
@victorkane I solved it by updating Nodejs to its latest version. Requires Nodejs v5 up as far as I can tell.

**Comment by victorkane** [comment]
On my Mac, I updated to Node 6.9.3 LTS and get same error

**Comment by hegelstad** [comment]
I still have this problem, none of the above tricks did it. 
Node v6.10.2
NPM v3.10.10
Next ^2.1.0

`Error in /Users/nikolai/github/nextapp/pages/index.js?entry
Module build failed: Error: Couldn't find preset "es2015" relative to directory "/Users/nikolai"
    at /Users/nikolai/github/nextapp/node_modules/babel-core/lib/transformation/file/options/option-manager.js:293:19
    at Array.map (native)
    at OptionManager.resolvePresets (/Users/nikolai/github/nextapp/node_modules/babel-core/lib/transformation/file/options/option-manager.js:275:20)
    at OptionManager.mergePresets (/Users/nikolai/github/nextapp/node_modules/babel-core/lib/transformation/file/options/option-manager.js:264:10)
    at OptionManager.mergeOptions (/Users/nikolai/github/nextapp/node_modules/babel-core/lib/transformation/file/options/option-manager.js:249:14)
    at OptionManager.init (/Users/nikolai/github/nextapp/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
    at File.initOptions (/Users/nikolai/github/nextapp/node_modules/babel-core/lib/transformation/file/index.js:212:65)
    at new File (/Users/nikolai/github/nextapp/node_modules/babel-core/lib/transformation/file/index.js:135:24)
    at Pipeline.transform (/Users/nikolai/github/nextapp/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at transpile (/Users/nikolai/github/nextapp/node_modules/babel-loader/lib/index.js:46:20)`

**Comment by hegelstad** [comment]
Fix: Removed (hidden) .babelrc (global?) file from "/Users/nikolai".

**Comment by Igor912** [comment]
I want to confirm that solution from previous comment works for me. I tried different fixes but issue didn't disappear.  But this one resolved problem. Thanks hegelstad.

> Fix: Removed (hidden) .babelrc (global?) file from "/Users/nikolai".

**Comment by saoirse-zee** [comment]
I had the same problem as @hegelstad and @Ihor912, and removing a `.babelrc` up the tree fixed it for me as well. This seems to be a somewhat common issue. Maybe it would be good to put this in the automated tutorial? I can imagine this issue completely flummoxing folks who are new to babel and/or the command line.

**Comment by zidzid1234** [comment]
I had the same issue...
when you run $ npm run dev, it says running .babelrc from folderXYZ
... from the folder you last ran babel or react!
=> Delete that file! Solved! Thank you
