### ISSUE TITLE
Error with nextjs 8 on Now 2

### ISSUE THREAD

**Issue by majongaagnojam** [zeit/next.js#6432]
# Bug report

**Project link :** https://github.com/majongaagnojam/now-next-redux-i18n

Hello guys,

I try to work with next and redux but I have an error when I deploy on Now 2. **In local, it works perfectly.**

I was in nextjs 7 but when I tried to access to my index page, I had an error message like this  : **"TypeError: n.isMemo is not a function"** on Now logs. 

So I followed instructions noticed here : https://github.com/zeit/next.js/issues/5750#issuecomment-451607604.

But, I encounter an other error when I redeploy and I tried to access again to my index page. 

**From console logs Now :**

```
02/24 10:55 PM (7m)
(output/index)
TypeError: undefined is not a function
    at Array.map (<anonymous>)
    at webpackAsyncContext (/var/task/page.js:33:8062)
    at _callee$ (/var/task/page.js:1:37793)
    at tryCatch (/var/task/page.js:25:48382)
    at Generator.invoke [as _invoke] (/var/task/page.js:25:52240)
    at Generator.prototype.(anonymous function) [as next] (/var/task/page.js:25:49506)
    at asyncGeneratorStep (/var/task/page.js:20:4447)
    at _next (/var/task/page.js:20:4853)
    at /var/task/page.js:20:5003
    at new Promise (<anonymous>)
```

Here are my conf files :

**.nowignore**
```
README.md
.next
```

**now.js**
```
{
  "version": 2,
  "builds": [
    {"src": "package.json", "use": "@now/next"}
  ]
}
```

**next.config.js**
```
const path = require("path");

module.exports = {
  target: 'serverless',
  webpack(config, { isServer }) {
    config.resolve.alias = config.resolve.alias || {};
    config.resolve.alias["@catalogs$"] = path.resolve(
      __dirname,
      isServer ? "./locale/catalogs.server.js" : "./locale/catalogs.client.js"
    );
    return config;
  }
};
```

**package.json**
```
{
  "name": "next-with-lingui",
  "version": "1.0.0",
  "description": "A Next.js project that uses lingui for i18n",
  "main": "index.js",
  "scripts": {
    "dev": "next",
    "build": "next build",
    "start": "next start",
    "lingui:extract": "lingui extract --clean",
    "lingui:compile": "lingui compile"
  },
  "keywords": [],
  "author": "",
  "license": "MIT",
  "dependencies": {
    "@lingui/react": "^2.7.0",
    "next": "^7.0.2",
    "next-redux-wrapper": "^2.0.0",
    "react": "^16.5.2",
    "react-dom": "^16.5.2",
    "react-redux": "^6.0.1",
    "redux": "^4.0.1",
    "redux-logger": "^3.0.6",
    "redux-thunk": "^2.3.0"
  },
  "devDependencies": {
    "@babel/core": "^7.1.2",
    "@lingui/cli": "^2.7.0",
    "@lingui/loader": "^2.7.0",
    "@lingui/macro": "^2.7.0",
    "babel-core": "^7.0.0-bridge.0",
    "babel-plugin-macros": "^2.4.2",
    "raw-loader": "^0.5.1"
  }
}
```
**Again, in nextjs version 7 or 8 when I deploy in local, it works perfectly.**

What did I miss ?  Thanks a lot people for your help !

Cheers !

**Comment by zachdoty** [comment]
> **now.js**
Should this filename be now.json?

**Comment by majongaagnojam** [comment]
I switch the extension but I still have the problem with the same error. 

I share the project : https://github.com/majongaagnojam/now-next-redux-i18n

**Comment by dav-is** [comment]
Seems to be an issue with dynamic importing (closing in favor of https://github.com/webpack/webpack/issues/4292). You can fix it by using regular imports instead.

```js
import NextDocument, { Head, Main, NextScript } from "next/document";
import en from "raw-loader!../locale/en/messages.js";
import fr from "raw-loader!../locale/fr/messages.js";
import es from "raw-loader!../locale/es/messages.js";

const supportedLocale = {en, fr, es};

export default class Document extends NextDocument {
  static async getInitialProps(ctx) {
    const queryLocale = ctx.query.locale;
    const locale = supportedLocale[queryLocale]
      ? queryLocale
      : "en";

    const initialProps = await NextDocument.getInitialProps(ctx);

    return { ...initialProps, linguiCatalog: supportedLocale[locale] };
  }

  render() {
    const { linguiCatalog } = this.props;
    return (
      <html>
        <Head>
          <script dangerouslySetInnerHTML={{ __html: linguiCatalog }} />
        </Head>
        <body>
          <Main />
          <NextScript />
        </body>
      </html>
    );
  }
}
```

**Comment by majongaagnojam** [comment]
It works perfectly on both sides, thanks a lot !!
