### ISSUE TITLE
problems with export

### ISSUE THREAD

**Issue by dcsan** [zeit/next.js#6449]
# Bug report
I'm unable to build or deploy a simple site using the versions below

## Describe the bug
Build step will succeed, deploy will now fail.
I tried to switch to using a static build since serverless build was failing.
static also fails
so back to serverless, now that fails also.

## To Reproduce
yarn run build # succeeds
yarn run export  # fails

## Expected behavior
should be able to deploy a simple starter website

## Screenshots
```
➜  rap git:(master) ✗ yarn run build
yarn run v1.13.0
(node:66685) ExperimentalWarning: The fs.promises API is experimental
$ next build
Creating an optimized production build ...

Compiled successfully.

 ┌ /
 ├ /_app
 ├ /_document
 ├ /_error
 ├ /about
 ├ /quizItem
 ├ /quizList
 └ /quizTop

✨  Done in 6.90s.
➜  rap git:(master) ✗ yarn run export
yarn run v1.13.0
(node:66717) ExperimentalWarning: The fs.promises API is experimental
$ next export
> using build directory: /Users/dc/dev/rikai/rabbit/rap/.next
  copying "static" directory
  copying "static build" directory
  launching 7 threads with concurrency of 10 per thread
{ Error: Cannot find module '/Users/dc/dev/rikai/rabbit/rap/.next/server/static/gTAnjqmstqLGU51V0PSue/pages/_document'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:571:15)
    at Function.Module._load (internal/modules/cjs/loader.js:497:25)
    at Module.require (internal/modules/cjs/loader.js:626:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at loadComponents (/Users/dc/dev/rikai/rabbit/rap/node_modules/next-server/dist/server/load-components.js:16:24)
    at work (/Users/dc/dev/rikai/rabbit/rap/node_modules/next/dist/export/worker.js:36:38) code: 'MODULE_NOT_FOUND' }
{ code: 'MODULE_NOT_FOUND' }
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

![image](https://user-images.githubusercontent.com/514002/53384877-6357af00-39b7-11e9-9f13-a48eca25042d.png)

## System information
 - OS: [e.g. macOS, Windows]
osx

 - Browser (if applies) [e.g. chrome, safari]
 - Version of Next.js: [e.g. 6.0.2]
```
➜  rap git:(master) ✗ now -v
14.0.0
➜  rap git:(master) ✗ npx next -v
Next.js v8.0.3
➜  rap git:(master) ✗ npm -v
6.7.0
➜  rap git:(master) ✗ node -v
v10.1.0

➜  rap git:(master) ✗ cat now.json
{
  "version": 2,
  "builds": [
    {
      "src": "package.json",
      "use": "@now/next"
    }
  ]
}%                                                                                                                                          ➜  rap git:(master) ✗ cat package.json
{
  "name": "rap",
  "version": "1.0.0",
  "description": "hsk app",
  "main": "index.js",
  "scripts": {
    "dev": "next",
    "build": "next build",
    "now-build": "next build",
    "start": "next start",
    "export": "next export"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "next": "^8.0.3",
    "react": "^16.8.3",
    "react-dom": "^16.8.3"
  }
}
➜  rap git:(master) ✗ cat next.config.js
module.exports = {
  target: 'serverless',
  exportPathMap: function () {
    return {
      '/': { page: '/' }
    }
  }
}
```
## Additional context
on trying to deploy with `now` 

```
> Error! 1 build failure occured.
> Error! Check your logs at https://rap-qnuv0jhvl.now.sh/_logs or run `now logs rap-qnuv0jhvl.now.sh`.
```

**Comment by dcsan** [comment]
related
https://github.com/zeit/now-builders/issues/155

**Comment by dav-is** [comment]
@dcsan Try removing `target: 'serverless',` from `next.config.js`

**Comment by dcsan** [comment]
oddly the build now seems to "just work"

previously, I had tried:

  target: 'serverless',

and also

      "use": "@now/next"
      "use": "@now/static-build"


![image](https://user-images.githubusercontent.com/514002/53482214-b2860880-3ab9-11e9-998c-134ede03ca8c.png)
