### ISSUE TITLE
In production: `delete Component.propTypes.someProp` causes `TypeError: Cannot convert undefined or null to object`

### ISSUE THREAD

**Issue by maximilianschmitt** [zeit/next.js#6717]
# Bug report

Take the following component:

```
import PropTypes from "prop-types";

Button.propTypes = {
  color: PropTypes.string,
  somethingElse: PropTypes.object
};

delete Button.propTypes.somethingElse;    // <--- this line is crucial

export default function Button({ color = "white", ...props }) {
  return <button style={{ background: color }} {...props} />;
}
```

When running `next build; next start` and opening the app in the browser, I receive the following error:

```
TypeError: Cannot convert undefined or null to object
    at Module.RNiq (/Users/max/Desktop/next-mini-bug/.next/server/static/X5fiY32Ar2ZJX~NCkJ9C8/pages/index.js:1:1947)
    at t (/Users/max/Desktop/next-mini-bug/.next/server/static/X5fiY32Ar2ZJX~NCkJ9C8/pages/index.js:1:225)
    at Object.0 (/Users/max/Desktop/next-mini-bug/.next/server/static/X5fiY32Ar2ZJX~NCkJ9C8/pages/index.js:1:1098)
    at t (/Users/max/Desktop/next-mini-bug/.next/server/static/X5fiY32Ar2ZJX~NCkJ9C8/pages/index.js:1:225)
    at module.exports.0 (/Users/max/Desktop/next-mini-bug/.next/server/static/X5fiY32Ar2ZJX~NCkJ9C8/pages/index.js:1:1059)
    at Object.<anonymous> (/Users/max/Desktop/next-mini-bug/.next/server/static/X5fiY32Ar2ZJX~NCkJ9C8/pages/index.js:1:1068)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
```

If I `console.log(Button.propTypes)`, I can see that they are `undefined` in production but an object (as expected) in dev-mode.

## To Reproduce

1. Clone https://github.com/maximilianschmitt/nextjs-bug and install deps by running `yarn`
2. Run `yarn build; yarn start`
3. Go to http://localhost:3000
4. See error in console

To get rid of the error, uncomment the following line of code:

https://github.com/maximilianschmitt/nextjs-bug/blob/master/components/Button.js#L8

## Notes

The error does not occur when running in dev-mode so I'm suspecting that this might be a bug in the minifier.

**Comment by timneutkens** [comment]
Proptypes are removed in production as they are type checking only, I'm not sure what you're trying to do exactly but adding/removing proptypes at runtime is probably not the best idea.
