### ISSUE TITLE
Can't start using-preact

### ISSUE THREAD

**Issue by JuanCaicedo** [zeit/next.js#6764]
# Examples bug report

## Example name
`using-preact`

## Describe the bug
Cannot start the app with this error 😅
```

> using-preact@1.0.0 dev /Users/juan/code/personal/using-preact-app
> node server.js

/Users/juan/code/personal/using-preact-app/node_modules/next-server/dist/lib/head-manager-context.js:11
exports.HeadManagerContext = React.createContext(null);
                                   ^

TypeError: React.createContext is not a function
    at Object.<anonymous> (/Users/juan/code/personal/using-preact-app/node_modules/next-server/dist/lib/head-manager-context.js:11:36)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/Users/juan/code/personal/using-preact-app/node_modules/next-server/dist/lib/head.js:8:32)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
npm ERR! code ELIFECYCLE
```

## To Reproduce
```bash
yarn create next-app --example using-preact using-preact-app`
cd using-preact-app 
npm i      
npm run dev
```

## Expected behavior
The app should start successfully

## Screenshots
See stack trace above 😀

## System information
 - OS: macOS 10.14.3
 - Next.js: latest (8.0.3)
 - Node: 8.11.4 and 10.15.0

## Other info
Perhaps related to #5716?

**Comment by breuerfelix** [comment]
same bug here...

i also tried the version specified here: https://github.com/zeit/next-plugins/tree/master/packages/next-preact

**Comment by coltonTB** [comment]
Worth noting - It appears that `preact-compat` does not export the `createContext` API

**Comment by Timer** [comment]
Seems Preact has been updated to support these new features. Please try using the latest version, thanks!
