### ISSUE TITLE
Unexpected token export with Material UI React

### ISSUE THREAD

**Issue by nayan2823** [zeit/next.js#6841]
# Bug report
Hi, When compiling with babel its always giving Unexpected token export error .

error:-
```
/Users/g/Desktop/study/React/node_modules/@material-ui/core/es/colors/green.js:17
export default green;
^^^^^^

SyntaxError: Unexpected token export
    at new Script (vm.js:79:7)
    at createScript (vm.js:251:10)
    at Object.runInThisContext (vm.js:303:10)
    at Module._compile (internal/modules/cjs/loader.js:657:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.@material-ui/core/es/colors/green (/Users/g/Desktop/study/React/.next/server/static/development/pages/index.js:17552:18)
    at __webpack_require__ (/Users/g/Desktop/study/React/.next/server/static/development/pages/index.js:23:31)
    at Module../pages/Styles.js (/Users//Desktop/study/React/.next/server/static/development/pages/index.js:939:91)
    at __webpack_require__ (/Users/g/Desktop/study/React/.next/server/static/development/pages/index.js:23:31)
    at Module../pages/components/ChapterList.jsx (/Users/g/Desktop/study/React/.next/server/static/development/pages/index.js:13696:66)
    at __webpack_require__ (/Users/g/Desktop/study/React/.next/server/static/development/pages/index.js:23:31)

```

Package.json dependencies(I have also tried @material-ui/core stable versions):-

   ```
 "@babel/core": "^7.4.0",
    "@babel/node": "latest",
    "@babel/plugin-proposal-class-properties": "latest",
    "@babel/preset-env": "latest",
    "@babel/preset-react": "^7.0.0",
    "@material-ui/core": "4.0.0-alpha.6",
    "@material-ui/icons": "^3.0.2",
    "babel-core": "7.0.0-bridge.0",
    "babel-loader": "8.0.0-beta.4",
    "babel-preset-stage-0": "^6.24.1",
    "express": "latest",
    "install": "^0.12.2",
    "jquery": "^3.3.1",
    "jss": "latest",
    "next": "^8.0.3",
    "nodemon": "latest",
    "notistack": "^0.5.0",
    "npm": "^6.9.0",
    "react": "^16.8.6",
    "react-dom": "^16.8.6",
    "react-iframe": "^1.5.0",
    "react-jss": "^8.1.0",
    "react-meta-tags": "^0.7.4",
    "react-router-dom": "^4.3.1",
    "react-router-transition": "^1.3.0",
    "react-scripts": "2.1.8",
    "source-map-explorer": "^1.8.0",
    "sprintf-js": "^1.1.2",
    "webpack": "latest",
    "webpack-cli": "latest"

```

.bablrc file content:-
```
{
  "presets": ["next/babel"],
  "plugins": []
}
```

I think there is problem in babel configuration if any one can help.Thanks

**Comment by timneutkens** [comment]
Please provide a full reproduction. You can also check material-ui's repository, it has an example for Next.js.
