### ISSUE TITLE
UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be one of type string, TypedArray, or DataView. Received type number

### ISSUE THREAD

**Issue by StupidSexyJake** [zeit/next.js#6872]
# Bug report

I just upgraded to the latest version of Next and now get the following error message when I run npm run build:

```
Creating an optimized production build ...

> Using external babel configuration
> Location: "/root/AdminPortal/.babelrc"
(node:32114) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be one of type string, TypedArray, or DataView. Received type number
    at Hash.update (internal/crypto/hash.js:58:11)
    at ids.forEach.id (/root/AdminPortal/node_modules/next/dist/build/webpack/plugins/hashed-chunk-ids-plugin.js:24:41)
    at Array.forEach (<anonymous>)
    at compilation.hooks.beforeChunkIds.tap.chunks (/root/AdminPortal/node_modules/next/dist/build/webpack/plugins/hashed-chunk-ids-plugin.js:24:25)
    at SyncHook.eval [as call] (eval at create (/root/AdminPortal/node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:7:1)
    at SyncHook.lazyCompileHook (/root/AdminPortal/node_modules/tapable/lib/Hook.js:154:20)
    at hooks.optimizeTree.callAsync.err (/root/AdminPortal/node_modules/webpack/lib/Compilation.js:1275:30)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/root/AdminPortal/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (/root/AdminPortal/node_modules/tapable/lib/Hook.js:154:20)
    at Compilation.seal (/root/AdminPortal/node_modules/webpack/lib/Compilation.js:1244:27)
(node:32114) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:32114) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

I'm unable to locate the source of the issue as the error message doesn't provide any further details.

This is the contents of the .babelrc file:

```
{
  "presets": ["next/babel"]
}
```

As far as I'm aware I don't have any unhandled promises in my code so I believe this is an issue with Next.js configuration. 

My project is quite large so I haven't included my code, however if there are any specific sections of code you would like me to share then just let me know.

## Expected behavior

No error message, or at least further details about what is causing this issue. This wasn't occurring before I upgraded to the latest version of Next.

## System information
 - OS: Ubuntu 18.04
 - Version of Next.js: 8.0.4

**Comment by StupidSexyJake** [comment]
Nevermind, I found this other issue that addresses the issue - https://github.com/zeit/next.js/issues/6861

Need to delete the .next folder before running npm next build

**Comment by dhffdh** [comment]
Please help, deleting .next foldet not resolve this problem...

**Comment by Timer** [comment]
@dhffdh Please upgrade to Next.js 9 or later -- this has been fixed in newer versions.
