### ISSUE TITLE
`now dev` / now/next compiling files that are not pages

### ISSUE THREAD

**Issue by timneutkens** [zeit/next.js#6934]
```
$ next build
Creating a development build ...

Failed to compile.

./node_modules/next/dist/build/webpack/loaders/next-client-pages-loader.js?page=%2F..%2Fstatic%2Ffavicon.ico&absolutePagePath=static%2Ffavicon.ico
Module not found: Can't resolve 'static/favicon.ico' in '/private/var/folders/ly/4jx0_c9x1271wrwsrvj_cngh0000gn/T/co.zeit.now/dev/workPaths/6tv3965g'

> Build error occurred
Error: > Build failed because of webpack errors
    at Object.build [as default] (/private/var/folders/ly/4jx0_c9x1271wrwsrvj_cngh0000gn/T/co.zeit.now/dev/workPaths/6tv3965g/node_modules/next/dist/build/index.js:190:15)
    at processTicksAndRejections (internal/process/next_tick.js:81:5)
```

**Comment by timneutkens** [comment]
`yarn create next-app`

```
{
    "version": 2,
    "name": "clock",
    "regions": ["iad"],
    "builds": [
        { "src": "package.json", "use": "@now/next@canary" }
    ]
}
```

```
module.exports = {
  target: 'serverless'
}
```

**Comment by dav-is** [comment]
Should be fixed by: https://github.com/zeit/now-builders/pull/369
