### ISSUE TITLE
`now dev` hanging after 2-3 force refreshes

### ISSUE THREAD

**Issue by timneutkens** [zeit/next.js#6936]
```
installing dependencies...
installing to /var/folders/ly/4jx0_c9x1271wrwsrvj_cngh0000gn/T/co.zeit.now/dev/workPaths/4gl123vo
yarn install v1.15.2
warning package.json: No license field
warning create-next-example-app: No license field
[1/4] 🔍  Resolving packages...
success Already up-to-date.
✨  Done in 0.38s.
running user script...
running "yarn run now-build"
yarn run v1.15.2
warning package.json: No license field
$ next build
Creating a development build ...

Compiled with warnings.

./node_modules/next-server/dist/server/require.js
Critical dependency: the request of a dependency is an expression

./node_modules/next-server/dist/server/require.js
Critical dependency: the request of a dependency is an expression

 ┌ /
 ├ /_app
 ├ /_document
 └ /_error

✨  Done in 3.92s.
preparing lambda files...
Creating lambda for page: "index.js"...
Created lambda for page: "index.js"
preparing cache ...
producing cache file manifest ...
```

Another refresh ends in `502: An error occurred with your deployment
Code: NO_STATUS_CODE_FROM_LAMBDA`

**Comment by timneutkens** [comment]
This also happened:
```
Error: pool is draining and cannot accept work
    at Pool.acquire (/snapshot/repo/dist/index.js:1:2067542)
    at NativeProvider.<anonymous> (/snapshot/repo/dist/index.js:1:403338)
    at Generator.next (<anonymous>)
    at /snapshot/repo/dist/index.js:1:400787
    at new Promise (<anonymous>)
    at r (/snapshot/repo/dist/index.js:1:400519)
    at NativeProvider.invoke (/snapshot/repo/dist/index.js:1:403275)
    at /snapshot/repo/dist/index.js:1:1973223
    at Generator.next (<anonymous>)
    at /snapshot/repo/dist/index.js:1:1970989
```

**Comment by dreamsinspace** [comment]
I have these same warnings: 
```
./node_modules/next-server/dist/server/require.js
Critical dependency: the request of a dependency is an expression

./node_modules/next-server/dist/server/require.js
Critical dependency: the request of a dependency is an expression
```

And wondering how I could fix them. Cheers
