### ISSUE TITLE
Cannot read property 'getCompilationErrors' of undefined

### ISSUE THREAD

**Issue by dinfyru** [zeit/next.js#7041]
next js - 8.0.4
fastify - 2.2.0
error when `app.renderToHTML(req.raw, reply.res, pagePath, queryParams)`

```
TypeError: Cannot read property 'getCompilationErrors' of undefined
    at DevServer.getCompilationError (/home/dinfy/Desktop/work/showcase/front-teasers/node_modules/next/dist/server/next-dev-server.js:162:47)
    at DevServer.renderToHTML (/home/dinfy/Desktop/work/showcase/front-teasers/node_modules/next/dist/server/next-dev-server.js:100:43)
```

**Comment by timneutkens** [comment]
You probably forgot to run `prepare`. Please follow the issue template + provide a clear and concise reproduction.

**Comment by dinfyru** [comment]
> You probably forgot to run `prepare`. Please follow the issue template + provide a clear and concise reproduction.

```
app
      .prepare()
      .then(() => {
fastify.get(home.url, (req, reply) => {
          const data = generateData(req, home.name, domainThemes, categoryList);
          return cachedRender(req, reply, `/${home.name}`, data).then(() => {
            reply.sent = true;
          });
        });
})
```

**Comment by dinfyru** [comment]
renderToHTML usage in cachedRender
