### ISSUE TITLE
Cannot read property 'getCompilationErrors' of undefined

### ISSUE THREAD

**Issue by dinfyru** [zeit/next.js#7044]
reproduce https://github.com/dinfyru/nextjs-fastifay-reproduce-rendertohtml

next js - 8.0.4
fastify - 2.2.0
error when `app.renderToHTML(req.raw, reply.res, pagePath, queryParams)`

```
TypeError: Cannot read property 'getCompilationErrors' of undefined
    at DevServer.getCompilationError (/home/dinfy/Desktop/work/showcase/front-teasers/node_modules/next/dist/server/next-dev-server.js:162:47)
    at DevServer.renderToHTML (/home/dinfy/Desktop/work/showcase/front-teasers/node_modules/next/dist/server/next-dev-server.js:100:43)
```

**Comment by dinfyru** [comment]
any ideas?

**Comment by chrishpowell** [comment]
Where is renderToHTML documented?  I see uses of it  but NO documentation.

**Comment by Timer** [comment]
Can you remove the usage of arrow functions and see if that fixes is? We may need to bind to the proper `this` within the `app` instance.

**Comment by timneutkens** [comment]
Closing this as there was no reply.

**Comment by balazsorban44** [comment]
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
