### ISSUE TITLE
Webpack config.externals is undefined in Next 8.1.0?

### ISSUE THREAD

**Issue by aeksco** [zeit/next.js#7068]
# Question about Next.js
I'm not sure if this qualifies as a "bug" per se, as we're engaging with some wild chicanery in our `next.config.js`, but there was a change in `next@8.1.0` that broke our current configuration.

**`next.config.js`** (simplified)
```js
module.exports = withTypescript({
    webpack: (config, options) => {
        const updatedConfig = withSass({
            // SASS options here
        }).webpack(config, options);

        updatedConfig.resolve.symlinks = false;
        updatedConfig.externals = config.externals.map(external => {
            // Some custom dependency resolution here
        });

        // Returns the customized Next.js configuration
        return updatedConfig;
    }
});
```

This causes no problems on `next@8.0.4` - however, after updating to `8.1.0` I started seeing the following error:

```
(node:45880) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'map' of undefined
    at Object.webpack (/Users/aeksco/project/web/next.config.js:43:52)
    at Object.webpack (/Users/aeksco/project/web/node_modules/@zeit/next-typescript/index.js:57:27)
    at Object.getBaseWebpackConfig [as default] (/Users/aeksco/project/web/node_modules/next/dist/build/webpack-config.js:308:32)
    at HotReloader.getWebpackConfig (/Users/aeksco/project/web/node_modules/next/dist/server/hot-reloader.js:162:37)
```

It appears that the Webpack configuration object passed into the `webpack` function does not include an `externals` array, which causes our customized configuration to explode when we try to run `config.externals.map(...)`

I was curious if the missing `config.externals` array is a bug, or if we're doing something that's so completely non-standard that the problem is really with our approach.

Any help or insight is appreciated - thanks!

**Comment by sync** [comment]
experiencing similar issues since 8.1.0

**Comment by sync** [comment]
my problem was located here: https://github.com/martpie/next-transpile-modules/issues/29 and latest version fixes it

**Comment by timneutkens** [comment]
It's not a bug. Not adding the config value makes the plugin not load in webpack, which is better for performance.

**Comment by aeksco** [comment]
@timneutkens Thanks for the reply and the context! I've added the following line to my `next.config.js` file which solves the problem:

```js
config.externals = config.externals || [];
```

Glad to know this is actually a _solution_ to the problem and not just a kludgey band-aid. Thanks again!

**Comment by timneutkens** [comment]
Note that you should actually make the value undefined if you're not adding anything to it.

**Comment by derit** [comment]
same issue with nextjs ^9.1.7

**Comment by Timer** [comment]
@derit as explained in the issue, this is not a bug, but a problem with your custom config.

**Comment by derit** [comment]
@Timer yes, i solved with validate  config external

**Comment by balazsorban44** [comment]
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
