### ISSUE TITLE
Styletron example breaks on SSR

### ISSUE THREAD

**Issue by smoll** [zeit/next.js#7191]
## Describe the bug

`yarn dev` works fine, but `yarn build && yarn start` errors out

## To Reproduce
Steps to reproduce the behavior, please provide code snippets or a repository:
1. clone repo, `cd examples/with-styletron`, `yarn install`
2. `yarn build`
3. `yarn start`
4. Load http://localhost:3000
5. See error in shell:

```
> Ready on http://localhost:3000
TypeError: Cannot read property 'renderStyle' of undefined
    at driver (/Users/s/workspace/next.js/examples/with-styletron/node_modules/styletron-standard/dist/index.js:16:20)
    at Object.StyledElement.React.createElement [as children] (/Users/s/workspace/next.js/examples/with-styletron/node_modules/styletron-react/dist/index.js:284:32)
    at a.render (/Users/s/workspace/next.js/examples/with-styletron/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:44:64)
    at a.read (/Users/s/workspace/next.js/examples/with-styletron/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:41:58)
    at renderToString (/Users/s/workspace/next.js/examples/with-styletron/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:53:83)
    at render (/Users/s/workspace/next.js/examples/with-styletron/node_modules/next-server/dist/server/render.js:86:16)
    at renderPage (/Users/s/workspace/next.js/examples/with-styletron/node_modules/next-server/dist/server/render.js:211:20)
    at Function.getInitialProps (/Users/s/workspace/next.js/examples/with-styletron/.next/server/static/RUt_NNFZYVNClDESx18vF/pages/_document.js:398:18)
    at Object.loadGetInitialProps (/Users/s/workspace/next.js/examples/with-styletron/node_modules/next-server/dist/lib/utils.js:42:35)
    at Object.renderToHTML (/Users/s/workspace/next.js/examples/with-styletron/node_modules/next-server/dist/server/render.js:218:36)
```

## Expected behavior

Page should render properly

## System information
 - OS: macOS
 - Browser (if applies) [e.g. chrome, safari]
 - Version of Next.js: `latest`

**Comment by MarchWorks** [comment]
Maybe duplicate of https://github.com/zeit/next.js/issues/7167

**Comment by smoll** [comment]
@MarchWorks looks like you're right, downgrading to `8.0.3` fixes the example for me. Closing this, thanks!
