### ISSUE TITLE
with-preact does not and will not work with next 8.0.0

### ISSUE THREAD

**Issue by LukasBombach** [zeit/next.js#7231]
# Bug report

## Describe the bug

`Next 8.x` uses `React.Suspense` which is neither implemented in `Preact 8.x` nor in `Preact X`. There are only 3 ways to deal with this:

* `Preact` implements `Lazy / Suspense` 
*  `Next` removes `Suspense` here: [client/index.js](https://github.com/zeit/next.js/blob/19c635175ba7556a222bd46f9a68bfb3beeeb7cd/packages/next/client/index.js#L211) and also gets rid of `react-ssr-prepass` because that is also related to `React.Suspense`
* You'd write a hack in `@zeit/next-preact` shimming `React.Suspense` to something like `props => props.children`

## To Reproduce

To find this bug you need to get rid of another bug first

1. `npx create-next-app --example using-preact using-preact-app && cd using-preact-app`
1. crate a file `noop.js` in the root dir with the contents `module.exports = () => {};`
1. open `server.js` add 
    ```js
    const path = require("path");
    const moduleAlias = require("module-alias");
    moduleAlias.addAlias("react-ssr-prepass", path.resolve(__dirname, "noop.js"));
    ```
    This will bypass `react-ssr-prepass` and reveal the real issue here, that `Preact` does not support `Suspense`
1. `npm run dev`

## Expected behavior

Running 

```console
npx create-next-app --example using-preact using-preact-app && cd using-preact-app && npm dev
``` 
should run Next with Preact without any errors

## Screenshots

This is the Error you'll get:

```
Error: The version of React you are using is lower than the minimum required version needed for Next.js. Please upgrade "react" and "react-dom": "npm install --save react react-dom" https://err.sh/zeit/next.js/invalid-react-version
    at Object.<anonymous> (/Users/lbombach/Arbeit/Spring/Basecamp/Projects/next-super-performance-monorepo/packages/next/node_modules/next/dist/server/next-dev-server.js:24:11)
    at Module._compile (internal/modules/cjs/loader.js:799:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:810:10)
    at Module.load (internal/modules/cjs/loader.js:666:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:606:12)
    at Function.Module._load (internal/modules/cjs/loader.js:598:3)
    at Module.require (internal/modules/cjs/loader.js:705:19)
    at require (internal/modules/cjs/helpers.js:14:16)
    at module.exports (/Users/lbombach/Arbeit/Spring/Basecamp/Projects/next-super-performance-monorepo/packages/next/node_modules/next/dist/server/next.js:5:24)
    at Object.<anonymous> (/Users/lbombach/Arbeit/Spring/Basecamp/Projects/next-super-performance-monorepo/packages/next/server.js:5:13)
```

## System information
 - OS: macOS Mojave 10.14.4
 - Browser (if applies) -> Node.js
 - Version of Next.js: 8.1.0

**Comment by frederikhors** [comment]
Suspense in Preact coming here: https://github.com/developit/preact/pull/1593

**Comment by Timer** [comment]
Closed as this is a upstream issue.
