### ISSUE TITLE
Link next/prefetch TypeError

### ISSUE THREAD

**Issue by intermundos** [zeit/next.js#725]
Hi,

I get following error in console while using Link from next/prefetch. Though, the link is working and goes to other page. 

> Parameter 'url' must be a string, not undefined.

Just installed next and run npm run dev.

**Comment by impronunciable** [comment]
Hi @intermundos can you paste the error information from the devtools/provide more information? thanks

**Comment by intermundos** [comment]
`url.js?d390d15:112Uncaught (in promise) TypeError: Parameter 'url' must be a string, not undefined
    at Url.parse (http://localhost:3000/_next/commons.js:3988:11)
    at urlParse (http://localhost:3000/_next/commons.js:3982:5)
    at getPrefetchUrl (http://localhost:3000/_next/commons.js:11797:34)
    at _callee$ (http://localhost:3000/_next/commons.js:11599:19)
    at tryCatch (http://localhost:3000/_next/commons.js:15901:40)
    at Generator.invoke [as _invoke] (http://localhost:3000/_next/commons.js:16192:22)
    at Generator.prototype.(anonymous function) [as next] (http://localhost:3000/_next/commons.js:15953:21)
    at step (http://localhost:3000/_next/commons.js:2647:30)
    at http://localhost:3000/_next/commons.js:2665:14
    at F (http://localhost:3000/_next/commons.js:1675:28)`

**Comment by intermundos** [comment]
Also, please tell me what information you need and I will gladly provide it.

Thanks.

**Comment by impronunciable** [comment]
@intermundos Tried to reproduce and couldn't. Is it possible to see the code of your page?

**Comment by intermundos** [comment]
This is index page with the link.

```
import React from  'react'
import Link        from 'next/prefetch';

export default class extends React.Component {


	render (){
		return (
			<div>
				<div>Hello world!</div>
				<Link><a href="/home">Home</a></Link>
			</div>
		)
	}
}
```

**Comment by impronunciable** [comment]
Oh, try to move the `href='/home'` to the link:

```
	render (){
		return (
			<div>
				<div>Hello world!</div>
				<Link href="/home"><a>Home</a></Link>
			</div>
		)
	}

```

**Comment by intermundos** [comment]
Oh my eyes. Thanks.

**Comment by impronunciable** [comment]
Glad it worked
