### ISSUE TITLE
Error: Not supported at at loadableGenerated.webpack

### ISSUE THREAD

**Issue by ellioseven** [zeit/next.js#7273]
# Bug report

## Describe the bug

I get a 500 error when a package in `node_modules` attempts to use `next/dynamic`.

I have a package that attempts to use `next/dynamic`: https://github.com/ellioseven/next-dynamic-package

I have a platform that implements the package: https://github.com/ellioseven/next-dynamic-platform

## To Reproduce

```
git clone git@github.com:ellioseven/next-dynamic-platform.git
cd next-dynamic-platform
docker-compose up
```

## Expected behavior

Component will be loaded dynamically on the page.

## System information
 - OS: [e.g. macOS, Windows]
 - Browser (if applies) [e.g. chrome, safari]
 - Version of Next.js: [e.g. 6.0.2]

### Log Output

```
yarn run v1.12.3
warning package.json: No license field
$ rm -rf ./node_modules && yarn install && next build && next start
warning package.json: No license field
warning No license field
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@1.2.9: The platform "linux" is incompatible with this module.
info "fsevents@1.2.9" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
[4/4] Building fresh packages...
Creating an optimized production build ...

Compiled successfully.

 ┌ /
 ├ /_app
 ├ /_document
 └ /_error

> Ready on http://localhost:3000
Error: Not supported
    at Message.loadableGenerated.webpack (/srv/node_modules/@provider/package/lib/Page.js:29:3)
    at load (/srv/node_modules/next-server/dist/lib/loadable.js:34:19)
    at init (/srv/node_modules/next-server/dist/lib/loadable.js:114:19)
    at flushInitializers (/srv/node_modules/next-server/dist/lib/loadable.js:244:23)
    at Promise (/srv/node_modules/next-server/dist/lib/loadable.js:254:9)
    at new Promise (<anonymous>)
    at Function.Loadable.preloadAll (/srv/node_modules/next-server/dist/lib/loadable.js:253:12)
    at Object.renderToHTML (/srv/node_modules/next-server/dist/server/render.js:113:30)
    at Server.renderToHTMLWithComponents (/srv/node_modules/next-server/dist/server/next-server.js:199:25)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

### Notes

- This bug only occurs an initial page load. When I refresh, I get the expect behavior. 
- This bug only occurs when I import from `node_modules`. If I clone the package into a different directory and import that instead, I get the expect behavior.

**Comment by ellioseven** [comment]
This was solved by adding `dynamic-import-node` to babel plugins.
