### ISSUE TITLE
Error: Cannot find module 'webpack'

### ISSUE THREAD

**Issue by mattiasewers** [zeit/next.js#7369]
When starting a new project, with just an index page, with next@canary I get this error:

```
{ Error: Cannot find module 'webpack'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:613:15)
    at Function.Module._load (internal/modules/cjs/loader.js:539:25)
    at Module.require (internal/modules/cjs/loader.js:667:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/test/code/next/node_modules/autodll-webpack-plugin/lib/plugin.js:11:16)
    at Module._compile (internal/modules/cjs/loader.js:738:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:749:10)
    at Module.load (internal/modules/cjs/loader.js:630:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:570:12)
    at Function.Module._load (internal/modules/cjs/loader.js:562:3) code: 'MODULE_NOT_FOUND' }
```

**Comment by timneutkens** [comment]
Please provide a reproduction. And please use the issue template.

**Comment by mattiasewers** [comment]
@timneutkens Like I wrote, just the minimal setup with a index.js file. Then run `next`.

Enviornment:
node: 11.10.0
chrome: 74.0.3729.131 (Official Build) (64-bit)
MacOS 10.14.2

**Comment by mifrej** [comment]
Same with me. Simplest possible setup fails due to lack of webpack. It should be as a dependency of next itself, no?
```package.json
  "dependencies": {
    "next": "^8.1.1-canary.30",
    "react": "^16.8.6",
    "react-dom": "^16.8.6"
  }
```

```terminal
{ Error: Cannot find module 'webpack'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)
    at Function.Module._load (internal/modules/cjs/loader.js:508:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/Users/mfrejnik/www/playground/next-fresh/node_modules/autodll-webpack-plugin/lib/plugin.js:11:16)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3) code: 'MODULE_NOT_FOUND' }
error Command failed with exit code 1.
```
