### ISSUE TITLE
NextJS `now dev` crashes / hangs when `build.env.NODE_ENV` is set to `production` 

### ISSUE THREAD

**Issue by williamli** [zeit/next.js#7439]
# Bug report

## Describe the bug

NextJS `now dev` crashes / hangs when `build.env.NODE_ENV` is set to `production` 

If `now dev --debug` is used:

```
Error: Cannot start server when target is not server. https://err.sh/zeit/next.js/next-start-serverless
    at new Server (/Users/williamli/projects/bbiHQ/ibcol/node_modules/next-server/dist/server/next-server.js:37:19)
    at new DevServer (/Users/williamli/projects/bbiHQ/ibcol/node_modules/next/dist/server/next-dev-server.js:28:9)
    at module.exports (/Users/williamli/projects/bbiHQ/ibcol/node_modules/next/dist/server/next.js:6:16)
    at main (/Users/williamli/Library/Caches/co.zeit.now/dev/builders/node_modules/@now/next/dist/dev-server.js:18:17)
    at Object.<anonymous> (/Users/williamli/Library/Caches/co.zeit.now/dev/builders/node_modules/@now/next/dist/dev-server.js:39:1)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
```

It works fine when deployed to Now.

## To Reproduce

Have the following defined in `now.json`.

```
"build": {
    "env": {
      "NODE_ENV": "production"
    }
  },
```

run `now dev --debug` (or `now dev` to not see debug message)

## Expected behavior
App should run the same in `now dev` as on Now (when deployed)

## System information
> now-cli v 15.3.0
> nextjs v8.1.0

**Comment by williamli** [comment]
related to https://github.com/zeit/now-builders/issues/464

**Comment by lfades** [comment]
Hi @williamli, this is due to the `serverless` target not being supported by `next start` in the latest release, if you switch to `next@canary` it should work, I'm going to close this for now if you keep having the issue feel free to reopen it 🙏

**Comment by timneutkens** [comment]
@lfades how is this related to `next start` though? William is using `now dev` 🤔

**Comment by lfades** [comment]
@timneutkens I tested it in both, when `next start` didn't work either did `now dev`, but `now dev` does run next in development anyway.

**Comment by wilsonpage** [comment]
I'm still not able to get this working (even with latest `next@8.1.1-canary.45`). I'm getting the following exception when running `now dev` with `NODE_ENV=production` in `.env` and `.env.build`.

```
> Building @now/next:app/next.config.js
> [debug] [2019-06-12T07:47:24.384Z] Using `@now/next@0.4.1`
> [debug] [2019-06-12T07:47:24.384Z] Creating build process for app/next.config.js
[@now/next] Downloading user files...
[@now/next] Installing dependencies...
installing to /Users/wilsonpage/Documents/s/songwhip/songwhip-web/next/app
(node:66162) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead
> Using external babel configuration
> Location: "/Users/wilsonpage/Documents/s/songwhip/songwhip-web/next/app/.babelrc"
/Users/wilsonpage/Documents/s/songwhip/songwhip-web/next/app/node_modules/neo-async/async.js:16
    throw new Error('Callback was already called.');
    ^

Error: Callback was already called.
    at throwError (/Users/wilsonpage/Documents/s/songwhip/songwhip-web/next/app/node_modules/neo-async/async.js:16:11)
    at /Users/wilsonpage/Documents/s/songwhip/songwhip-web/next/app/node_modules/neo-async/async.js:2818:7
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

Using `yarn why neo-async` I traced this back to a dependency of `watchpack` which is consumed by `next`. Beyond that I'm stumped!

**Comment by wilsonpage** [comment]
@lfades are you able to give me any pointers?

**Comment by lfades** [comment]
@wilsonpage I tested it again on Windows using Node 8.10.0 and latest canary, setting `NODE_ENV=production` in `.env` and `.env.build`, it worked but is definitely not running in production, just the local development server.
