### ISSUE TITLE
npm run build errors on Ubuntu, works on macOS

### ISSUE THREAD

**Issue by iFokus** [zeit/next.js#7470]
# Bug report
npm run build fails on Ubuntu, but works fine on macOS

## Describe the bug
When building I get the following error. 

```
> Build error occurred
TypeError: Super expression must either be null or a function
    at _inherits (/root/ifokus-web/.next/server/static/p8MNVIJABTYb1hZYybnoB/pages/index.js:289:11)
    at /root/ifokus-web/.next/server/static/p8MNVIJABTYb1hZYybnoB/pages/posts/post.js:376:102
    at Object.7m35 (/root/ifokus-web/.next/server/static/p8MNVIJABTYb1hZYybnoB/pages/posts/post.js:399:2)
    at __webpack_require__ (/root/ifokus-web/.next/server/static/p8MNVIJABTYb1hZYybnoB/pages/posts/post.js:23:31)
    at Object.rjl1 (/root/ifokus-web/.next/server/static/p8MNVIJABTYb1hZYybnoB/pages/posts/post.js:2341:18)
    at __webpack_require__ (/root/ifokus-web/.next/server/static/p8MNVIJABTYb1hZYybnoB/pages/posts/post.js:23:31)
    at Module.Y6X2 (/root/ifokus-web/.next/server/static/p8MNVIJABTYb1hZYybnoB/pages/posts/post.js:1211:26)
    at __webpack_require__ (/root/ifokus-web/.next/server/static/p8MNVIJABTYb1hZYybnoB/pages/posts/post.js:23:31)
    at Object.2 (/root/ifokus-web/.next/server/static/p8MNVIJABTYb1hZYybnoB/pages/posts/post.js:155:18)
    at __webpack_require__ (/root/ifokus-web/.next/server/static/p8MNVIJABTYb1hZYybnoB/pages/posts/post.js:23:31)

```

- I'm using TypeScript. 
- I do have a custom server
- I have not misspelled React.Component or something similar as suggested in other posts abouth this error. 

My .babelrc looks like this

```
{
  "presets": [
    "next/babel",
    "@zeit/next-typescript/babel"
  ],
  "plugins": [
    [
      "@babel/plugin-proposal-decorators",
      {
        "legacy": true
      }
    ],
    [
      "@babel/plugin-proposal-class-properties",
      {
        "loose": true
      }
    ]
  ]
}

```

My next.config.js looks like this:

```
const withTypescript = require('@zeit/next-typescript');
const withCSS = require('@zeit/next-css');

module.exports = withTypescript(withCSS({
    cssLoaderOptions: {
        url: false
    }
}));

```

The page in question that loads some dummy json data in getInitialProps looks like this:

```
import * as React from 'react';
import { WithRouterProps } from 'next-server/router';
import { CommunityContextProps } from '../../contexts/CommunityContext';
import DiscussionResponse from '../../models/DiscussionResponse';

import mockdata from '../../mocks/Post';
import Message from '../../components/posts/Message';
import { NextContext } from 'next';
import HeadTags from '../../components/headtags/HeadTags';

interface Props extends WithRouterProps, CommunityContextProps {
    json: any;
}

class Post extends React.Component<Props> {
    static async getInitialProps(context: NextContext) {
        const {id} = context.query;

        return {
            json: mockdata[`${id}`]
        };
    }

    render() {
        const {json} = this.props;
        const model = DiscussionResponse.fromJson(json);

        const {discussion, messages = [], users = {}} = model;

        if (!discussion) {
            return null;
        }

        return (
            <div>
                <HeadTags title={discussion.title!} description={''}/>

                {messages.map((message, index) => {
                    const user = users[`${message.userId!}`];

                    return (<Message key={message.id!}
                                     index={index}
                                     title={index === 0 ? discussion.title : undefined}
                                     message={message}
                                     user={user}/>);
                })}
            </div>
        );
    }
}

export default Post;

```

## System information

- OS: Ubuntu
- Version of Next.js: 8.1.0

**Comment by lfades** [comment]
@iFokus Can you try `next@canary` and see if the error persists ? you won't need `@zeit/next-typescript` anymore. You can follow this steps for it: https://github.com/zeit/next.js#typescript

**Comment by tfsjohan** [comment]
I did try Canary, but I got too many compile errors to get thru all changes with typings. 

For the time being I've solved by building on my mac and using rsync to copy build files to the server. That works.

**Comment by Timer** [comment]
Closing as this is likely a configuration problem and better suited for our [Spectrum](https://spectrum.chat/next-js).
Please repost there if you still need help getting this to work!
