### ISSUE TITLE
Latest 8.1.1-canary.55 version compatibility issue with next-css plugin

### ISSUE THREAD

**Issue by jishaal** [zeit/next.js#7632]
# Bug report

## Describe the bug

While attempting to run the [with-linaria example](https://github.com/zeit/next.js/tree/canary/examples/with-linaria) which uses the `next-css` plugin, I found the following error gets thrown when using the latest canary build of next.js `8.1.1-canary.55`

```es6
{ Error: Cannot find module 'webpack'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/sandbox/node_modules/extract-css-chunks-webpack-plugin/dist/index.js:11:16)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3) code: 'MODULE_NOT_FOUND' }
```

## To Reproduce

See https://codesandbox.io/s/nextjs-811-canary55-bug-8gtqi

Downgrading the version of next.js to `8.1.1-canary.54` fixes the error

## Expected behavior

There is no error

## System information

- OS: macOS
- Version of Next.js: `8.1.1-canary.55`

**Comment by borisowsky** [comment]
Same issue with next-sass package.

**Comment by MarchWorks** [comment]
I think it's caused here https://github.com/zeit/next.js/pull/7628
Cc @guybedford

**Comment by Timer** [comment]
This will be fixed in the next `canary`. Sorry for the noise!

**Comment by jishaal** [comment]
Thanks team!
