### ISSUE TITLE
Missing Dependency file When using Latest Next and Pkg

### ISSUE THREAD

**Issue by paboulos** [zeit/next.js#7636]
# Bug report
When upgrading from next 6.0.2 and pkg 4.3.1 to next 8.1.0 and pkg 4.4.0 the deployed executable app fails to run on Alpine Linux. 

## Describe the bug
no page opens at URL http://localhost and command line log reports:
[pkg-app-run.txt](https://github.com/paboulos/next-docker-demo/blob/master/pkg-app-run.txt)
> Next is Ready on http://localhost:3000
{ Error: Cannot find module 'core-js/library/fn/object/assign'
1) If you want to compile the package/file into executable, please pay attention to compilation warnings and specify a literal in 'require' call. 2) If you don't want to compile the package/file into executable and want to 'require' it from filesystem (likely plugin), specify an absolute path in 'require' call using process.cwd() or process.execPath.
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:580:15)
    at Function.Module._resolveFilename (pkg/prelude/bootstrap.js:1287:46)
    at Function.Module._load (internal/modules/cjs/loader.js:506:25)
    at Module.require (internal/modules/cjs/loader.js:635:17)
    at Module.require (pkg/prelude/bootstrap.js:1166:31)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.dGr4 (/snapshot/app/.next/server/static/jAyZPI-isdLYWdxnnyu4x/pages/_document.js:1681:18)
    at __webpack_require__ (/snapshot/app/.next/server/static/jAyZPI-isdLYWdxnnyu4x/pages/_document.js:23:31)
    at Object.UXZV (/snapshot/app/.next/server/static/jAyZPI-isdLYWdxnnyu4x/pages/_document.js:696:18)
    at __webpack_require__ (/snapshot/app/.next/server/static/jAyZPI-isdLYWdxnnyu4x/pages/_document.js:23:31) code: [32m'MODULE_NOT_FOUND'[39m, pkg: [33mtrue[39m }
{ Error: Cannot find module 'core-js/lyibrar/fn/object/define-property'
1) If you want to compile the package/file into executable, please pay attention to compilation warnings and specify a literal in 'require' call. 2) If you don't want to compile the package/file into executable and want to 'require' it from filesystem (likely plugin), specify an absolute path in 'require' call using process.cwd() or process.execPath.
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:580:15)
    at Function.Module._resolveFilename (pkg/prelude/bootstrap.js:1287:46)
    at Function.Module._load (internal/modules/cjs/loader.js:506:25)
    at Module.require (internal/modules/cjs/loader.js:635:17)
    at Module.require (pkg/prelude/bootstrap.js:1166:31)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.TUA0 (/snapshot/app/.next/server/static/jAyZPI-isdLYWdxnnyu4x/pages/_error.js:344:18)
    at __webpack_require__ (/snapshot/app/.next/server/static/jAyZPI-isdLYWdxnnyu4x/pages/_error.js:23:31)
    at Object.hfKm (/snapshot/app/.next/server/static/jAyZPI-isdLYWdxnnyu4x/pages/_error.js:438:18)
    at __webpack_require__ (/snapshot/app/.next/server/static/jAyZPI-isdLYWdxnnyu4x/pages/_error.js:23:31) code: [32m'MODULE_NOT_FOUND'[39m, pkg: [33mtrue[39m }
^C

  In debug mode the zeit pkg module shows no presence of files 'core-js/library/fn/object/assign' and 'core-js/lyibrar/fn/object/define-property'. Appears they do not exist in the latest Next 8.1.0 version.  Refer to provide git repo file  	[next810pkg440-debug.txt](https://github.com/paboulos/next-docker-demo/blob/master/next810pkg440-debug.txt) . In the working deployment pkg --debug shows presence in previous 6.0.2 version. Refer to [next602pkg431-debug.txt.](https://github.com/paboulos/next-docker-demo/blob/master/next602pkg431-debug.txt)
## To Reproduce
Build Docker Image and Run Container on Alpine
$ docker build -t nextjs-pkg-docker-alpine .
$ docker run --rm -it -p 80:3000 -e "PORT=3000" -e "API_URL=https://API_URL.com" nextjs-pkg-docker-alpine
Steps to reproduce the behavior, please provide code snippets or a repository:
Repository provide [here](https://github.com/paboulos/next-docker-demo) 
1. Go to URL 'http://localhost'
2. See page error
3. Go to command line see logging error

## Expected behavior
Go to browser URL and view the home page.

## System information

- OS: Alpine
- Browser Any
- Version of Next.js: 8.1.0

**Comment by timneutkens** [comment]
Going to close this as it's quite stale.

**Comment by balazsorban44** [comment]
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
