### ISSUE TITLE
TypeError: _typeof is not a function in _app.js

### ISSUE THREAD

**Issue by gyto** [zeit/next.js#7678]
# Question about Next.js

I was working for a while on the project with next.js, but when time come to deploy live I start getting an odd behavior from the `express`. I am using next.js, express as backend server, and redux with persist to store some of my data when I needed in the client browser.

pages/_app.jsx
```
// @flow
import * as React from 'react';
import App, {Container} from 'next/app';
import { I18nextProvider } from 'react-i18next';
import { Provider } from 'react-redux';
import { PersistGate } from 'redux-persist/integration/react';
import { getPersistor, getStore } from '../store/configureStore';
import i18n from '../utils/i18n';

type Props = {
    Component: Object,
    pageProps: Object
}

export default class MyApp extends App<Props> {
    render() {
        const { Component, pageProps } = this.props;
        return (
            <Container>
                <I18nextProvider i18n={i18n}>
                    <Provider store={getStore()}>
                        <PersistGate
                            loading={null}
                            persistor={getPersistor()}
                        >
                            <Component {...pageProps} />
                        </PersistGate>
                    </Provider>
                </I18nextProvider>
            </Container>
        );
    }
}
```

My store configuration ../store/configureStore.js
```
import { createStore, applyMiddleware } from 'redux';
import reducer from '../reducers';
import { persistStore } from 'redux-persist';
import { composeWithDevTools } from 'redux-devtools-extension';

let _persistor;
let _store;

// export const history = createBrowserHistory();

export const getStore = (props) => {
    if (_store) {
        return _store;
    }
    const initialState = (props) ? {...props} : {};
    _store = createStore(
        reducer,
        initialState,
        composeWithDevTools(applyMiddleware())
    );

    _persistor = persistStore(_store);

    return _store;
};

export const getPersistor = () => {
    return _persistor;
};
```

finally my server.js file
```
const express = require('express');
const next = require('next');
const Router = require('./utils/dynamicRoutes');
const dev = process.env.NODE_ENV !== 'production';
const app = next({ dev });
const handle = Router.getRequestHandler(app);
const port = process.env.PORT || 3000;

const bodyParser = require('body-parser');

app.prepare()
    .then(() => {
        const server = express();
        server.use(bodyParser.json());
        server.use(bodyParser.urlencoded({ extended: true }));

        server.get('*', (req, res) => handle(req, res));

        server.listen(port, (err) => {
            if (err) throw err;
            console.log(`> Ready on http://localhost:${port}`);
        });
    })
    .catch((ex) => {
        console.log(ex);
        console.error(ex.stack);
        process.exit(1);
    });
```

Here is a problem. When I starting the server as `NODE_ENV=production node server.js` I am getting this issue
```
TypeError: _typeof is not a function
    at _interopDefault (/mnt/sdb1/public/with-jest-flow-app/.next/server/static/GxzjAOI9ZeWUXNEi6WAv6/pages/_app.js:237:48)
    at Object._interopDefault (/mnt/sdb1/public/with-jest-flow-app/.next/server/static/GxzjAOI9ZeWUXNEi6WAv6/pages/_app.js:239:15)
    at call (/mnt/sdb1/public/with-jest-flow-app/.next/server/static/GxzjAOI9ZeWUXNEi6WAv6/pages/_app.js:23:31)
    at Object.__webpack_require__ (/mnt/sdb1/public/with-jest-flow-app/.next/server/static/GxzjAOI9ZeWUXNEi6WAv6/pages/_app.js:2422:15)
    at call (/mnt/sdb1/public/with-jest-flow-app/.next/server/static/GxzjAOI9ZeWUXNEi6WAv6/pages/_app.js:23:31)
    at Module.__webpack_require__ (/mnt/sdb1/public/with-jest-flow-app/.next/server/static/GxzjAOI9ZeWUXNEi6WAv6/pages/_app.js:4050:12)
    at call (/mnt/sdb1/public/with-jest-flow-app/.next/server/static/GxzjAOI9ZeWUXNEi6WAv6/pages/_app.js:23:31)
    at Object.__webpack_require__ (/mnt/sdb1/public/with-jest-flow-app/.next/server/static/GxzjAOI9ZeWUXNEi6WAv6/pages/_app.js:137:18)
    at call (/mnt/sdb1/public/with-jest-flow-app/.next/server/static/GxzjAOI9ZeWUXNEi6WAv6/pages/_app.js:23:31)
    at __webpack_require__ (/mnt/sdb1/public/with-jest-flow-app/.next/server/static/GxzjAOI9ZeWUXNEi6WAv6/pages/_app.js:91:18)
```

I am curries if any one were getting this issue before, and it would be great if anyone will help me to solve it

**Comment by Timer** [comment]
Hi! Please post questions like these [on our Spectrum](https://spectrum.chat/next-js) with a full reproduction. Thanks!

**Comment by balazsorban44** [comment]
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
