### ISSUE TITLE
Build failing with ENOMEM error

### ISSUE THREAD

**Issue by cibulka** [zeit/next.js#7703]
# Bug report

At first, I feel that this situation falls somewhere between the bug (unexpected behaviour, unclear documentation) and a question. If you feel it's not really a bug, feel free to close my question and point me to Next.js forums.

Also it is incredibly confusing for me, so apologies for the length of my question. 

TLDR;

- 1.: Are dependencies such as `webpack` really needed in project's package.json?
- 2.: What is average memory consumption of `npm run build`? Can I measure it somehow?
- 3.: Is ENOMEM problem I'm experiencing caused by the lack of memory or is that some sort of problem on my project configuration or on Next.js? 

## Describe the bug

`npm run build` fails on FastComet hosting. I don't have this problem on my local environment.

The tech support seem to suggest, that the error is caused by some sort of dependency problem. They've tried to install the following modules:

- dependencies:
  - "@babel/core": "^7.4.5",
  - "css-loader": "^3.0.0",
  - "extract-loader": "^3.1.0",
  - "extracted-loader": "^1.0.7",
  - "postcss-loader": "^3.0.0",
  - "sass-loader":
  - "webpack": "^4.35.0"
- devDependencies:
  - "@babel/cli": "^7.4.4",
  - "@babel/runtime-corejs2": "^7.4.5",

I've tried various versions of Next 8.1. canary versions with various results. Some versions failed with missing dependency error (such as "webpack not found") even on my local environment, some went through. The most recent version works locally.

I've found some issues (such as https://github.com/zeit/next.js/issues/6353, https://github.com/zeit/next.js/issues/6240, https://github.com/zeit/next.js/issues/7369) and accepted PRs (such as https://github.com/zeit/next.js/pull/7370) in this repo with a bit of unclear guidance. Some issues recommend using Yarn (I can't use that on FastComet hosting), some issues recommend purging cache and `.next` folder (didn't help), some issues recommend not adding webpack to package.json, some issues recommend adding webpack to package.json.

Anyway, here is the exact ENOMEM error I receive after `npm run build`:

```
internal/child_process.js:323
    throw errnoException(err, 'spawn');
    ^

Error: spawn ENOMEM
    at _errnoException (util.js:992:11)
    at ChildProcess.spawn (internal/child_process.js:323:11)
    at exports.spawn (child_process.js:502:9)
    at Object.exports.fork (child_process.js:103:10)
    at fork (/home/cibulkam/nodevenv/cirkonet.cibulka.in/nest-cirkonet-fe/10/lib/node_modules/worker-farm/lib/fork.js:17:36)
    at Farm.startChild (/home/cibulkam/nodevenv/cirkonet.cibulka.in/nest-cirkonet-fe/10/lib/node_modules/worker-farm/lib/farm.js:107:16)
    at Farm.processQueue (/home/cibulkam/nodevenv/cirkonet.cibulka.in/nest-cirkonet-fe/10/lib/node_modules/worker-farm/lib/farm.js:288:10)
    at Farm.receive (/home/cibulkam/nodevenv/cirkonet.cibulka.in/nest-cirkonet-fe/10/lib/node_modules/worker-farm/lib/farm.js:213:8)
    at Farm.<anonymous> (/home/cibulkam/nodevenv/cirkonet.cibulka.in/nest-cirkonet-fe/10/lib/node_modules/worker-farm/lib/farm.js:123:10)
    at emitTwo (events.js:126:13)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! nest@0.3.0 build: `next build src`
npm ERR! Exit status 1

```

## To Reproduce

This is sort of hard to do, as the error does not happen in my local environment and does not happen on Heroku. It does happen, however, on FastComet.

Those are, I think, relevant files:

### Package.json
```
{
  "main": "index.js",
  "scripts": {
    "build": "next build src",
    "dev": "NODE_ENV=development nodemon server.js --watch server.js",
    "export": "NODE_ENV=production next export src --outdir out",
    "lint": "eslint --ext .js --ext .jsx src/ || exit 0",
    "lint-fix": "eslint --fix --ext .js --ext .jsx src/ || exit 0",
    "start": "NODE_ENV=production node server.js",
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "Petr Cibulka <cibulka.me@gmail.com>",
  "license": "UNLICENSED",
  "private": true,
  "dependencies": {
    "@zeit/next-sass": "^1.0.1",
    "body-parser": "^1.19.0",
    "cookie-parser": "^1.4.4",
    "cors": "^2.8.5",
    "express": "^4.16.4",
    "express-bearer-token": "^2.4.0",
    "icomoon-react": "^1.0.0",
    "isomorphic-unfetch": "^3.0.0",
    "moment": "^2.24.0",
    "next": "^v8.1.1-canary.61",
    "next-fonts": "^0.17.0",
    "next-redux-wrapper": "^3.0.0-alpha.2",
    "node-sass": "^4.12.0",
    "nprogress": "^0.2.0",
    "prop-types": "^15.7.2",
    "react": "^16.8.6",
    "react-body-classname": "^1.3.0",
    "react-dom": "^16.8.6",
    "react-expanding-textarea": "^1.0.0",
    "react-google-maps": "^9.4.5",
    "react-html-classname": "^0.1.2",
    "react-i18nify": "^1.11.14",
    "react-images": "^0.5.19",
    "react-linkify": "^1.0.0-alpha",
    "react-player": "^1.11.1",
    "react-redux": "^7.0.3",
    "react-typed": "^1.1.2",
    "redux": "^4.0.1",
    "redux-devtools-extension": "^2.13.8",
    "redux-form": "^8.2.0",
    "redux-thunk": "^2.3.0",
    "svg-sprite-loader": "^4.1.6"
  },
  "devDependencies": {
    "@epegzz/sass-vars-loader": "^4.3.1",
    "babel-eslint": "^10.0.1",
    "eslint": "^5.12.0",
    "eslint-config-airbnb": "^17.1.0",
    "eslint-import-resolver-alias": "^1.1.2",
    "eslint-plugin-import": "^2.14.0",
    "eslint-plugin-jsx-a11y": "^6.1.2",
    "eslint-plugin-react": "^7.13.0",
    "nodemon": "^1.19.0",
    "postcss-cssnext": "^3.1.0"
  }
}
```

### next.config.js
```
const withSass = require('@zeit/next-sass');
module.exports = withSass();
```

## Expected behavior

To make `next run build` working again.

## System information

- OS: OSX in development, Linux version 2.6.32-954.3.5.lve1.4.64.el6.x86_64 in production
- Version of Next.js: v8.1.1-canary.61
- Node: v10.1.0 in development, v10.16.0 in production

---

Thanks in advance!

**Comment by cibulka** [comment]
Also, `npm run build` runs without problems on 2 other shared hostings for me (be it both missing dependencies or ENOMEM). So maybe it is an issue connected more to FastComet or to `nodevenv` (which FastComet, according the error message above, uses)?

**Comment by rbntimes** [comment]
Been having the same issues with fastcomet hosting/next.js

**Comment by timneutkens** [comment]
Sounds like a lack of memory on your hosting provider.

- Webpack shouldn't be installed by the user
- Babel shouldn't be installed by the user


Sounds like you might want to use https://zeit.co to host your project.

**Comment by nicolasflorth** [comment]
@cibulka, @rbntimes Did you find a solution? I have the same problem on FastComet

**Comment by cibulka** [comment]
@nicolasflorth The reasoning behind me trying it out with FastComet etc. back then was to have my traditional PHP back-end (WordPress) and front-end (Next.js) at one place. Ultimately it showed to be way more pain than anything else, so I ended up hosting my Next.js projects on Vercel. 

You can try either [Vercel](https://vercel.com/) or other hostings more suited for React apps (I know about Heroku and Netlify). Good luck!

**Comment by balazsorban44** [comment]
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
