### ISSUE TITLE
publicRuntimeConfig shouldn’t be undefined on build

### ISSUE THREAD

**Issue by tusbar** [zeit/next.js#7713]
# Bug report

## Describe the bug

v8.1.1-canary.62 (or maybe 3aed76fad857b518a31675987e8c79f6f1afccde) (re-)introduces an issue with how I use (and recommend how to use) https://github.com/tusbar/next-runtime-dotenv.

## To Reproduce

This breaks on build as `publicRuntimeConfig` is `undefined` at build time:

```js
const {
  publicRuntimeConfig: {MY_API_URL}
} = getConfig()
```

## Expected behavior

`publicRuntimeConfig` used to be `{}` at build time.

## System information

- OS: macOS
- Version of Next.js: 8.1.1-canary.62

## Additional context

This is not the first time this breaks, maybe it would be nice to add a test. It used to work fine with `8.0.4`, it’s broken in `8.1.0` and used to work fine in canary before `8.1.1-canary.62`. Broken in `9.0` as well.

**Comment by tusbar** [comment]
@timneutkens could we have a consistent behavior for this? Thanks.

**Comment by cbarratt** [comment]
I'm using the built in method of using publicRuntimeConfig and not the above plugin and also receive the same error message on build

**Comment by tusbar** [comment]
@cbarratt the plugin just pre-fills the runtime configuration with environment variables using `dotenv`.

Accessing the configuration is not different [from the doc](https://github.com/zeit/next.js#runtime-configuration).

**Comment by vitorhsb** [comment]
I also received the same error message on build and think I figured it out why. It has to do with [Automatic static optimization](https://nextjs.org/blog/next-9#automatic-static-optimization) introduced in Next 9. 

Following the documentation that states "This determination is made by whether or not the page has blocking data requirements through using getInitialProps." I ended up adding getInitialProps to every page in my application and the error went away. 
Since there was none getInitialProps statement in some pages, during build it would consider this pages as static and does not expose runtime env configuration.

**Comment by egdelwonk** [comment]
I'm seeing the same error on build, but getting notices that Automatic static optimization is opt-out, so not sure if it's related @vitorhsb.

**Comment by ijjk** [comment]
Hi, I'm not able to reproduce this error, could someone who is encountering this issue add a link to a repo or their `next.config.js`? 

On a minimal project `publicRuntimeConfig` and `serverRuntimeConfig` are both being populated during build. We also do have a test for this [here](https://github.com/zeit/next.js/blob/canary/test/integration/export/test/ssr.js#L12)

<img width="952" alt="Screen Shot 2019-07-08 at 1 51 49 PM" src="https://user-images.githubusercontent.com/22380829/60841857-a573d700-a187-11e9-8e50-52808e1d9558.png">

**Comment by timdavish** [comment]
Hey, I am also seeing this error on production builds. Doing the following:
```
import getConfig from 'next/config'
console.log(getConfig())
```
seems to randomly switch between printing the config and `undefined` during the build.

Here is our `next.config.js`:
```
const withCss = require('@zeit/next-css')
const withSass = require('@zeit/next-sass')
const withImages = require('next-images')

const isDev = process.env.NODE_ENV === 'dev'

const withSassConfig = {
  cssModules: true,
  cssLoaderOptions: {
    modules: true,
    importLoaders: 1,
    localIdentName: isDev ? '[name]__[local]--[hash:base64:5]' : '[sha1:hash:hex:4]',
  },
}

const nextConfig = {
  publicRuntimeConfig: {
    // config vars..
  },
}

const config = {
  ...withSassConfig,
  ...nextConfig,
  webpack: webpackConfig => webpackConfig,
}

module.exports = withCss(withSass(withImages(config)))
```

**Comment by ijjk** [comment]
Hi @timdavish, I'm still not able reproduce. It would help a lot if someone could create a minimal repo that shows this occurring 👍 

Tested `next.config.js`:
```js
const withCss = require('@zeit/next-css')
const withSass = require('@zeit/next-sass')
const withImages = require('next-images')

const isDev = process.env.NODE_ENV === 'dev'

const withSassConfig = {
  cssModules: true,
  cssLoaderOptions: {
    modules: true,
    importLoaders: 1,
    localIdentName: isDev ? '[name]__[local]--[hash:base64:5]' : '[sha1:hash:hex:4]',
  },
}

const nextConfig = {
  serverRuntimeConfig: {
    secret: 'pass'
  },
  publicRuntimeConfig: {
    hello: 'world'
  },
}

const config = {
  ...withSassConfig,
  ...nextConfig,
  webpack: webpackConfig => webpackConfig,
}

module.exports = withCss(withSass(withImages(config)))
```

`pages/index.js`
```
import getConfig from 'next/config'

console.log(getConfig())

export default () => <p>Hello world!!</p>
```

<img width="952" alt="Screen Shot 2019-07-08 at 3 57 29 PM" src="https://user-images.githubusercontent.com/22380829/60847910-5767cf00-a199-11e9-8579-428c2ad6b334.png">

**Comment by lglossman** [comment]
@timdavish I have the impression that is some sort of race condition. When I run the build inside a docker container it fails, but when I run on my Mac directly it builds just fine

**Comment by baer** [comment]
I'm running into this problem as well. My project is large so a minimal repro is going to be tricky, but I suspect that this is a race condition so it may not even be possible. Running the same command (`NODE_ENV=production next build`) in two environments gets the same error on different pages in the app.

**Early 2015 Macbook Pro (3.1 GHz Intel Core i7) I get the following:**

```
{ TypeError: Cannot destructure property `publicRuntimeConfig` of 'undefined' or 'null'.
    at Object.tpE7 (/Users/ericbaer/dev/work/lnc/constellation/web/.next/server/static/hAFgtwbpTC55qnszuIR1i/pages/inventory.js:4011:55)
```

**Netlify CI Environment (node10 Docker image)**
```
TypeError: Cannot destructure property `publicRuntimeConfig` of 'undefined' or 'null'.
5:12:27 PM:     at Object.tpE7 (/opt/build/repo/web/.next/server/static/RVuMYAXq8hm_vjh7oqK4-/pages/order-acknowledgment.js:3740:55)
```

 A few notable things about my project:

- My project is large. There are ~90 components exported in the `build.manifest`, static 87Mb output dir.
- My config is unique since I do static export with dynamic routes deployed to a CDN. You can see a description and minimal repo explaining the technique in https://github.com/zeit/next.js/pull/6963

```
/* eslint-env node */

const { set, uniq } = require(`lodash/fp`);
const { BundleAnalyzerPlugin } = require(`webpack-bundle-analyzer`);
const redirects = require(`./redirects`);

const { ANALYZE, API_ROOT } = process.env;

module.exports = {
  // Will be available on both server and client
  publicRuntimeConfig: {
    API_ROOT: API_ROOT || `http://localhost:8000/api/`,
  },
  exportPathMap: function() {
    const staticPages = uniq(redirects.map(redirect => redirect.staticPage));
    const staticExports = staticPages.reduce(
      (memo, page) => set(page, { page }, memo),
      {}
    );

    return {
      "/": { page: `/` },
      "/auth/signed-in": { page: `/auth/signed-in` },
      ...staticExports
    };
  },
  webpack: function(config, options) {
    if (ANALYZE) {
      // eslint-disable-next-line fp/no-mutating-methods
      config.plugins.push(
        new BundleAnalyzerPlugin({
          analyzerMode: `static`,
          openAnalyzer: true
        })
      );
    }

    if (!options.dev) {
      // Sourcemaps are a powerful tool but their default behavior is to upload your entire
      // de-obfuscated source code to the public internet. There are various solutions to this
      // including hosting them on a private server but there is some non-trivial amount of
      // complexity to maintain for the life of the project. This option creates a special sourcemap
      // that, while not particularly useful for stepping through code, does provide file names and
      // line numbers in stack traces. For more information on sourcemaps and how to set them up
      // for production systems, see the Formidable Playbook on the topic.
      // https://github.com/FormidableLabs/formidable-playbook/blob/master/docs/frontend/webpack-source-maps.md
      // eslint-disable-next-line fp/no-mutation
      config.devtool = `nosources-source-map`;

      // Enable sourceMaps in UglifyJs
      for (const plugin of config.plugins) {
        if (plugin[`constructor`][`name`] === `UglifyJsPlugin`) {
          // eslint-disable-next-line fp/no-mutation
          plugin.options.sourceMap = true;
          break;
        }
      }
    }

    return config;
  }
};
```

**Comment by egdelwonk** [comment]
It looks like when the require cache is cleared in `static-checker.js` it is wiping out next/config (which uses the require cache to persist the configuration afaik). I disabled the cache in static-checker and the error no longer appears. 

As far as how to replicate the issue... I'm not entirely sure. It seems like you'd need a decently large number of pages to compile (I have ~30) and see the error. With these changes to static-checker below, the error goes away:

```
import { isPageStatic } from './utils'

export default function worker(
  options: any,
  callback: (err: Error | null, data?: any) => void
) {
  try {
    const { serverBundle, runtimeEnvConfig } = options || ({} as any)
    const result = isPageStatic(serverBundle, runtimeEnvConfig)

    // clear require.cache to prevent running out of memory
    // since the cache is persisted by default
    Object.keys(require.cache).map(modId => {
      if (modId.endsWith("node_modules/next/config.js")) {
        return;
      }
      const mod = require.cache[modId]
      delete require.cache[modId]
      if (mod.parent) {
        const idx = mod.parent.children.indexOf(mod)
        mod.parent.children.splice(idx, 1)
      }
    })

    callback(null, result)
  } catch (error) {
    callback(error)
  }
}
```

cc @ijjk

**Comment by ijjk** [comment]
@egdelwonk thanks for the additional details, this makes more sense. I have submitted a PR addressing the problem [here](https://github.com/zeit/next.js/pull/7822)

**Comment by egdelwonk** [comment]
Looks good, thanks @ijjk.

**Comment by ryandcsg** [comment]
@egdelwonk Where does that code go to? Does one need to get inside node_modules and update code?

**Comment by egdelwonk** [comment]
@ryandcsg looks like @ijjk made a [PR](https://github.com/zeit/next.js/pull/7822) to fix it (slightly different approach, but it should work) and i'd imagine it's coming in the 9.0.1 release. It's on the canary branch, but hasn't made it to a 9.0.x canary release yet.

**Comment by Timer** [comment]
Hey! I'll release a canary now so you can use this fix.

**Comment by isaachinman** [comment]
Can confirm that the canary release fixes the issue. Thanks everyone!

**Comment by jtaox** [comment]
I reproduced this bug on 9.4.2

**Comment by controversial** [comment]
Hey @ijjk - it seems like this bug has returned, as per the 16 upvotes there ^

**Comment by timneutkens** [comment]
No reproduction was given on the new comment so that makes it hard to look into.

**Comment by jtaox** [comment]
@timneutkens [reproduction repo](https://github.com/jtaox/nextjs-runtime-config-undefined-demo), I tried to fix it,  https://github.com/vercel/next.js/pull/15777

**Comment by Multiply** [comment]
I've tried v9.5.2 which should include #15777 and we're still getting `undefined` back from any `getConfig` call it seems.

**Comment by ColeTownsend** [comment]
The sentry example also has this

**Comment by eddiewang** [comment]
having the same error as above, getConfig no longer works for some reason, and is returning undefined, which breaks sentry  configs

**Comment by lukinasargy** [comment]
I am having the same issue on nextjs 9.5.3 publicRuntimeConfig is not returning custom variables, but only NODE_ENV :(

**Comment by kristojorg** [comment]
We are having the same issue that when running in a docker container, the `publicRuntimeConfig` does not appear to be set from runtime env vars. I've confirmed that they are set in the container and available on `process.env` when the app is running, and they are available server side, but not client side. We are not using any static pages, but we are using `getServerSideProps`.

**Comment by csmartinsfct** [comment]
I ran into the same issue and ended up downgrading to v9.0.2 which for now suits my needs.

**Comment by jbcochery** [comment]
I also ran into this issue and in my case it was introduced by [this change](https://github.com/vercel/next.js/pull/10250) in the 9.4.3 release.

Since this change all undefined properties of `publicRuntimeConfig` are removed at build time, and if that happens for all the properties then `publicRuntimeConfig` is seen as `{}` which is in turn [filtered out](https://github.com/vercel/next.js/blob/62b9183e89d8aed5723830b1358c743f90ddfedc/packages/next/export/index.ts#L310).

A workaround can be to add at least one property to `publicRuntimeConfig` that is defined at build time, could be foo:'bar'.

In my case though the real problem was that I was not using `getInitialProps` as documented [here](https://nextjs.org/docs/api-reference/next.config.js/runtime-configuration).

**Comment by kristojorg** [comment]
For anyone else running into this, I ended up building the Next.js app when running my docker container (instead of when building the image) in order to avoid having to use the `publicRuntimeConfig`. I now just use standard build time env vars. It adds startup time, but solves this issue

**Comment by nandorojo** [comment]
I'm running into this issue in my Sentry config in `next@10.0.1`, following the `with-sentry-simple` example mentioned by @ColeTownsend [here](https://github.com/vercel/next.js/issues/7713#issuecomment-682486991).

Looking at the examples repo, it looks like `with-sentry` was updated 7 hours ago. It has a [different config](https://github.com/vercel/next.js/blob/canary/examples/with-sentry/utils/sentry.js) altogether:

```ts
// utils/sentry
import * as Sentry from '@sentry/node'
import { RewriteFrames } from '@sentry/integrations'

export const init = () => {
  if (process.env.NEXT_PUBLIC_SENTRY_DSN) {
    const integrations = []
    if (
      process.env.NEXT_IS_SERVER === 'true' &&
      process.env.NEXT_PUBLIC_SENTRY_SERVER_ROOT_DIR
    ) {
      // For Node.js, rewrite Error.stack to use relative paths, so that source
      // maps starting with ~/_next map to files in Error.stack with path
      // app:///_next
      integrations.push(
        new RewriteFrames({
          iteratee: (frame) => {
            frame.filename = frame.filename.replace(
              process.env.NEXT_PUBLIC_SENTRY_SERVER_ROOT_DIR,
              'app:///'
            )
            frame.filename = frame.filename.replace('.next', '_next')
            return frame
          },
        })
      )
    }

    Sentry.init({
      enabled: process.env.NODE_ENV === 'production',
      integrations,
      dsn: process.env.NEXT_PUBLIC_SENTRY_DSN,
      release: process.env.NEXT_PUBLIC_COMMIT_SHA,
    })
  }
}
```

```tsx
// pages/_app.tsx

import { init } from '../utils/sentry'

init()

export default function App({ Component, pageProps, err }) {
  // Workaround for https://github.com/vercel/next.js/issues/8592
  return <Component {...pageProps} err={err} />
}
```

Changing my `_app.tsx` file to use the new Sentry setup seems to have fixed this for me (given that `getConfig()` returns `undefined` and it's no longer used.)

**Comment by jbox5** [comment]
Was still able to reproduce this on 9.5.5, but thankfully jbcochery's workaround of including an unused property worked for me for now.

**Comment by madeinspace** [comment]
> Was still able to reproduce this on 9.5.5, but thankfully jbcochery's workaround of including an unused property worked for me for now.

where exactly do you include that property? thanks!

**Comment by nickelghost** [comment]
@madeinspace As jbcochery said, the real problem is allowing ASO to run on the pages where you get that error. Adding `export const getServerSideProps = () => {};` to every page where that error occurred worked for me. I think it'd be great if we got a warning or an error if client side config was used on an ASO page, but it's probably something that's difficult to implement.

**Comment by scott-thrillist** [comment]
I'll add to this by saying even though the latest Nextjs docs are using `getStaticProps` as an example, I was only able to access process.env variables in my staging and prod environments using `getServerSideProps`.

**Comment by PsyGik** [comment]
Still getting the error on `"next": "10.2.3"`. My use-case is with Stripe. 

```js
import React, { createContext } from 'react';
import { loadStripe } from '@stripe/stripe-js';
import { Elements } from '@stripe/react-stripe-js';
import getConfig from 'next/config';

const { publicRuntimeConfig } = getConfig();
const StripeContext = createContext(null);
const stripePromise = loadStripe(publicRuntimeConfig.stripeKey); <= Undefined

const StripeProvider = ({ children }) => {
  return (
    <StripeContext.Provider value={{}}>
      <Elements stripe={stripePromise}>{children}</Elements>
    </StripeContext.Provider>
  );
};

export { StripeContext, StripeProvider };

```

```
> next build

info  - Using webpack 4. Reason: custom webpack configuration in next.config.js https://nextjs.org/docs/messages/webpack5
info  - Checking validity of types  
info  - Creating an optimized production build  
info  - Compiled successfully
info  - Collecting page data .{ publicRuntimeConfig: {}, serverRuntimeConfig: {} }
{ publicRuntimeConfig: {}, serverRuntimeConfig: {} }
info  - Collecting page data ..{ publicRuntimeConfig: {}, serverRuntimeConfig: {} }
{ publicRuntimeConfig: {}, serverRuntimeConfig: {} }
info  - Collecting page data  
[==  ] info  - Generating static pages (0/4){ serverRuntimeConfig: {}, publicRuntimeConfig: undefined }

Error occurred prerendering page "/500". Read more: https://nextjs.org/docs/messages/prerender-error
TypeError: Cannot read property 'stripeKey' of undefined
```

**Comment by balazsorban44** [comment]
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
