### ISSUE TITLE
Module not found: Can't resolve 'fs'

### ISSUE THREAD

**Issue by TidyIQ** [zeit/next.js#7755]
# Bug report

## Describe the bug

I'm using the popular [find-up](https://www.npmjs.com/package/find-up) npm package, which has [locate-path](https://www.npmjs.com/package/locate-path) as a dependency. `locate-path` requires `fs` within it's code.

When I attempt to run my app I get the following error message:

```
[ error ] ./node_modules/locate-path/index.js
Module not found: Can't resolve 'fs' in 'C:\...\node_modules\locate-path'
Could not find files for /index in .next/build-manifest.json
Promise { <pending> }
ModuleNotFoundError: Module not found: Error: Can't resolve 'fs' in 'C:\...\node_modules\locate-path'
    at factory.create (C:\...\node_modules\webpack\lib\Compilation.js:823:10)
    at factory (C:\...\node_modules\webpack\lib\NormalModuleFactory.js:397:22)
    at resolver (C:\...\node_modules\webpack\lib\NormalModuleFactory.js:130:21)
    at asyncLib.parallel (C:\...\node_modules\webpack\lib\NormalModuleFactory.js:224:22)
    at C:\...\node_modules\neo-async\async.js:2830:7
    at C:\...\node_modules\neo-async\async.js:6877:13
    at normalResolver.resolve (C:\...\node_modules\webpack\lib\NormalModuleFactory.js:214:25)
    at doResolve (C:\...\node_modules\enhanced-resolve\lib\Resolver.js:184:12)
    at hook.callAsync (C:\...\node_modules\enhanced-resolve\lib\Resolver.js:238:5)
    at _fn0 (eval at create (C:\...\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:15:1)
    at resolver.doResolve (C:\...\node_modules\enhanced-resolve\lib\UnsafeCachePlugin.js:37:5)
    at hook.callAsync (C:\...\node_modules\enhanced-resolve\lib\Resolver.js:238:5)
    at _fn0 (eval at create (C:\...\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:15:1)
    at hook.callAsync (C:\...\node_modules\enhanced-resolve\lib\Resolver.js:238:5)
    at _fn0 (eval at create (C:\...\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:27:1)
    at resolver.doResolve (C:\...\node_modules\enhanced-resolve\lib\DescriptionFilePlugin.js:42:38)
```

I created an [issue in the locate-path repo](https://github.com/sindresorhus/locate-path/issues/5) and they have confirmed the issue is not with them, but likely with webpack. I don't use webpack in my app so the issue must be arising from Next.js's use of webpack.

## To Reproduce

Clone [https://github.com/TidyIQ/nextjs-issue](https://github.com/TidyIQ/nextjs-issue) and run `npm run dev`.

## Expected behavior

No issue

## System information

- OS: Windows 10
- Version of Next.js: 8.1.1-canary.67

**Comment by Timer** [comment]
The provided code is not valid -- this file would never be available on the client side during rendering:

https://github.com/TidyIQ/nextjs-issue/blob/aef67b12d91d299d0978550005a40cbb34f74b71/pages/index.js#L5

Remember, you can only do FS-related operations while _on the server_. This means you cannot use `fs` while rendering.

If you use `fs`, be sure it's only within `getInitialProps`.

You may also need to create a `next.config.js` file with the following content to get the client bundle to build:
```js
module.exports = {
  webpack: config => {
    // Fixes npm packages that depend on `fs` module
    config.node = {
      fs: 'empty'
    }

    return config
  }
}
```

**Comment by bystrovo** [comment]
I have the same problem on my local, practically vanilla install, however in the examples from nextjs this doesn not seem to be a problem
https://github.com/zeit/next.js/tree/5787cbd9de33ea9add7cadeb04689b0d4b02976d/examples/blog-starter

what makes it work there without modifying the config file?

**Comment by timneutkens** [comment]
Only use `fs` in getStaticProps / getServerSideProps as those are eliminated from the browser bundle.

**Comment by qoalu** [comment]
I found out what the problem was. If I import a function that uses `fs`, but do not run/use the function inside getStaticProps, it will end up being included in the browser bundle. Once the function gets referenced inside getStaticProps it will stop appearing in the browser bundle.

I guess there is some hidden logic that removes imports used in getStaticProps but unused in main export. I spent a few hours debugging until I could reproduce, maybe worth having a sidenote somewhere in the docs :)

**Comment by bystrovo** [comment]
I found out what the problem was. If I import a function that uses `fs`, but do not run/use the function inside getStaticProps, it will end up being included in the browser bundle. Once the function gets referenced inside getStaticProps it will stop appearing in the browser bundle.

I guess there is some hidden logic that removes imports used in getStaticProps but unused in main export. I spent a few hours debugging until I could reproduce, maybe worth having a sidenote somewhere in the docs :)

**Comment by tgroutars** [comment]
Isn't the hidden logic just webpack's tree shaking? Makes sense when you think of it, Next doesn't import `getStaticProps` in the browser bundle, so it removes the imported function used in it.

If you don't reference it anywhere, I guess webpack considers you imported it for side effects, so it still includes it in every bundle.

**Comment by timneutkens** [comment]
> Isn't the hidden logic just webpack's tree shaking? Makes sense when you think of it, Next doesn't import `getStaticProps` in the browser bundle, so it removes the imported function used in it.
> 
> If you don't reference it anywhere, I guess webpack considers you imported it for side effects, so it still includes it in every bundle.

No, webpack tree shaking is not sophisticated enough to shake these exports in that way. Tree shaking getStaticProps / getServerSideProps / getStaticPaths is handled by this custom Babel plugin we created: https://github.com/vercel/next.js/blob/canary/packages/next/build/babel/plugins/next-ssg-transform.ts

**Comment by tgroutars** [comment]
Oh thanks for the pointer, looks like I overestimated webpack :)

**Comment by jeremiedubuis** [comment]
> I found out what the problem was. If I import a function that uses `fs`, but do not run/use the function inside getStaticProps, it will end up being included in the browser bundle. Once the function gets referenced inside getStaticProps it will stop appearing in the browser bundle.
> 
> I guess there is some hidden logic that removes imports used in getStaticProps but unused in main export. I spent a few hours debugging until I could reproduce, maybe worth having a sidenote somewhere in the docs :)

It seems another thing to watch out for is the ability to tree shake your imports. If you import a script that itself imports a serverside module it seems your script needs to be tree shakable for webpack to remove the code from client side bundling. this just happened to me with a redis instanciation script, I had to remove variable declarations for redis to not be bundled with the client.

**Comment by aloukissas** [comment]
Any reason this would be happening from _within_ `getServerSideProps`?

**Comment by ig-perez** [comment]
Hi all. Like @aloukissas I have the same issue when using `dotenv` within my `index.js` `getStaticProps()`. It gets solved when adding the `next.config.js` file as shown in @Timer initial comment.

Any clues why is this happening? I'm unsing `Next.js` v.9.4.0

Thanks!

**Comment by deadcoder0904** [comment]
I had this error while using `fast-glob`.

I used [this great tool](https://next-code-elimination.now.sh/) to understand the code that gets bundled in the client-side.

Turned out, I was importing a variable from a file that uses `fast-glob` which internally uses `fs` but I wasn't using the variable anywhere inside `getStaticProps` so the files imports `fast-glob` weren't getting eliminated.

An example:

# mdxUtils.js

```js
import glob from 'fast-glob'
import path from 'path'

export const BLOG_PATH = path.join(process.cwd(), 'posts')
export const blogFilePaths = glob.sync(`${BLOG_PATH}/blog/**/*.mdx`)
```

# index.js

```js
import { BLOG_PATH, blogFilePaths } from './mdxUtils'

export const getStaticProps = () => {
  const posts = blogFilePaths.map((filePath) => {
    ...
  }
  return { props: { posts } }
}
```

As you can see I am not using `BLOG_PATH` anywhere in `index.js` but still importing it. I am only using `blogFilePaths` so it gave me this error.

For more context → https://github.com/vercel/next.js/discussions/17138

**Comment by deadcoder0904** [comment]
@ig-perez As of Next v9.4, they have a built-in way to load environment variables → https://nextjs.org/docs/basic-features/environment-variables

I suggest you read the docs to find the solution :)

**Comment by ig-perez** [comment]
That is awesome, I missed that part in the docs, thanks! I'll update my code 👍🏽

**Comment by stubar** [comment]
I have a generic log fn which is some scenarios on the server I want it to write to disk,  this is what I'm using...

```   
 if (
      typeof window === 'undefined' &&
      serverRuntimeConfig.saveErrorLogToDisk
    ) {
      require('fs')...
```

I seem to recall "typeof window === 'undefined'" is a magic string that causes segments to be omitted from the client bundle

**Comment by iway1** [comment]
While @Timer 's solution works well, it requires you to edit your webpack config like: ```
module.exports = {
  webpack: (config, { isServer }) => {
    // Fixes npm packages that depend on `fs` module
    if (!isServer) {
      config.node = {
        fs: 'empty'
      }
    }

    return config
  }
}
```

This is because you are importing `fs` in the React component. If instead you import `fs` in a different file and do your file reading there you will not have to modify your webpack config at all:

```
//util.js
import * as fs from 'fs';

export function getDirectory() {
    return fs.readdirSync('.');
}
```

```
//component.js
import {getDirectory} from '../util'

export default function Component({directory}) {
    console.log(directory) // Logs cwd
    return (<div></div>)
}
async function getStaticProps() {
    return {props: {directory: getDirectory()}}'
}
```

**Comment by iway1** [comment]
While @Timer 's solution works well, it requires you to edit your webpack config like: 
```js
module.exports = {
  webpack: (config, { isServer }) => {
    // Fixes npm packages that depend on `fs` module
    if (!isServer) {
      config.node = {
        fs: 'empty'
      }
    }

    return config
  }
}
```

This is because you are importing `fs` in the React component. If instead you import `fs` in a different file and do your file reading there you will not have to modify your webpack config at all:

```js
//util.js
import * as fs from 'fs';

export function getDirectory() {
    return fs.readdirSync('.');
}
```

```js
//component.js
import {getDirectory} from '../util'

export default function Component({directory}) {
    console.log(directory) // Logs cwd
    return (<div></div>)
}
async function getStaticProps() {
    return {props: {directory: getDirectory()}}'
}
```

**Comment by indikaimk** [comment]
I had the same issue. The problem turned out to be not referencing the imported variable within `getStaticProps` function. Thanks to @Timer for correctly pointing out.

**Comment by borislemke** [comment]
In my case, it was a separation of FE and BE code. I had used barrel export in some folders, e.g:
```
| src
  | lib
    index.ts
    fe-code.ts
    be-code.ts
```

importing FE code by from the index will give this warning:
```
import FECode from "../lib"
```

need to explicitly import or separate the folders

Option 1, do not use barrel export:
```
import FeCode from "../lib/fe-code.ts"
```

Separate FE and BE code:
```
| src
  | fe-lib
    index.ts
    fe-code.ts
  | be-lib
    index.ts
    be-code.ts

// somewhere
import FECode from "../fe-lib"
```

**Comment by femesq** [comment]
For those trying `webpack 5` on next.js, the fix is different:

```js
module.exports = {
  webpack: (config, { isServer }) => {
    if (!isServer) {
      config.resolve.fallback.fs = false;
    }
    return config;
  },
}
```

Reference: https://webpack.js.org/migrate/5/#clean-up-configuration

**Comment by nicholasengleman** [comment]
The config from @Timer downgrades your Next app to Webpack 4. 

If you want to use Webpack 5, do this:

```
module.exports = {
  future: {
    webpack5: true,
  },
  webpack: (config, { isServer }) => {
    if (!isServer) {
      config.resolve = {
        ...config.resolve,
        fallback: {
          ...config.resolve.fallback,
          fs: false,
        },
      };
    }

    return config;
  },
};```

**Comment by AIEAJN** [comment]
> For those trying `webpack 5` on next.js, the fix is different:
> 
> ```js
> module.exports = {
>   webpack: (config, { isServer }) => {
>     if (!isServer) {
>       config.resolve.fallback.fs = false;
>     }
>     return config;
>   },
> }
> ```
> 
> Reference: https://webpack.js.org/migrate/5/#clean-up-configuration

I tried this method and it didn't work, I have a problem with the pg module for postgresql, when I use it in my code it returns an error for fs, native pg and others. when I use this method I always get the same errors, I use version 5 of webpack

**Comment by deadcoder0904** [comment]
@AIEAJN you're probably exporting the `pg` module or `fs` on the client-side. try pasting your relevant code in https://next-code-elimination.vercel.app/ to see what gets shipped to client.

**Comment by AIEAJN** [comment]
ahhh okk i see now, thanks

**Comment by glantucan** [comment]
I have this same issue (using fs/promises) and applying any of the proposed solutions:
  1. Avoid uncalled functions on the module using fs/promises that was used from `getStaticProperties()`
  2. Adding 
    ```
module.exports = {
  webpack: (config, { isServer }) => {
    if (!isServer) {
      config.resolve.fallback.fs = false;
    }
    return config;
  },
}
```
  to next.config.js

But these are workarounds, right? I men, it's difficult to maintain, as it's difficult to detect that having functions on those modules that are not being called anymore is cause of your problem.

Are there any plans on permanently fix this?

**Comment by TimNZ** [comment]
Setting next.config.js: serverless = 'experimental-serverless-trace' 
solved my problems with static page generation (MDX) using 'fs' module, that was erroring on resolve, and serverless build

**Comment by tettoffensive** [comment]
> For those trying `webpack 5` on next.js, the fix is different:
> 
> ```js
> module.exports = {
>   webpack: (config, { isServer }) => {
>     if (!isServer) {
>       config.resolve.fallback.fs = false;
>     }
>     return config;
>   },
> }
> ```
> 
> Reference: https://webpack.js.org/migrate/5/#clean-up-configuration

How do I tell next.js to use webpack 5. I still get this message `info  - Using webpack 4. Reason: custom webpack configuration in next.config.js https://nextjs.org/docs/messages/webpack5` when I update this section to the above.

**Comment by tkulpa** [comment]
> > For those trying `webpack 5` on next.js, the fix is different:
> > ```js
> > module.exports = {
> >   webpack: (config, { isServer }) => {
> >     if (!isServer) {
> >       config.resolve.fallback.fs = false;
> >     }
> >     return config;
> >   },
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Reference: https://webpack.js.org/migrate/5/#clean-up-configuration
> 
> How do I tell next.js to use webpack 5. I still get this message `info - Using webpack 4. Reason: custom webpack configuration in next.config.js https://nextjs.org/docs/messages/webpack5` when I update this section to the above.

Try this:
```js
module.exports = {
  webpack5: true,
  webpack: (config, { isServer }) => {
    if (!isServer) {
      config.resolve.fallback.fs = false;
    }
    return config;
  },
}
```

**Comment by dankerk** [comment]
When I add the proposed solution for webpack 5 the error disappears, but subsequent errors arise:
`Module not found: Can't resolve 'http2'`
and when I install that the next one appears
`Module not found: Can't resolve 'tls'`
and when I install that the next one appears... etc.

Does anyone have any more/other suggestions? I'm running "next": "^11.1.2",

**Comment by tettoffensive** [comment]
@dankerk I had similar errors because I was using `apollo-server-micro` v2. I just installed them (there ended up being maybe 3 packages and it worked. However, if this is the package your using consider switching to `apollo-server-express` v3: https://github.com/vercel/next.js/pull/30082

**Comment by dankerk** [comment]
@tettoffensive Unfortunately for me the rabbit hole went deeper than 3 packages. I installed like 10 of them then gave up. The trace leads back to the `flamelink` module I'm using.

**Comment by riverscode** [comment]
> When I add the proposed solution for webpack 5 the error disappears, but subsequent errors arise: `Module not found: Can't resolve 'http2'` and when I install that the next one appears `Module not found: Can't resolve 'tls'` and when I install that the next one appears... etc.
> 
> Does anyone have any more/other suggestions? I'm running "next": "^11.1.2",

I have the same proble with "next": "12.0.4",

**Comment by riefer02** [comment]
Why is there no mention of this in the Next.js `getServerSideProps` caveats section?

**Comment by lucasconstantino** [comment]
Keep in mind Next' code elimination only works under `/pages`. If you have, say, a generic `getServerSideProps` elsewhere, it might not work as expected.

**Comment by balazsorban44** [comment]
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
