### ISSUE TITLE
[Next 9.0.0] Error: Cannot find module 

### ISSUE THREAD

**Issue by steida** [zeit/next.js#7801]
Not sure whether it's configuration bug or not. 

```
{ Error: Cannot find module '/Users/steida/dev/nberg/packages/web/.next/server/static/development/pages/_document'
 |     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)
 |     at Function.Module._load (internal/modules/cjs/loader.js:508:25)
 |     at Module.require (internal/modules/cjs/loader.js:637:17)
 |     at require (internal/modules/cjs/helpers.js:22:18)
 |     at Object.loadComponents (/Users/steida/dev/nberg/node_modules/next-server/dist/server/load-components.js:17:25)
 |     at DevServer.findPageComponents (/Users/steida/dev/nberg/node_modules/next-server/dist/server/next-server.js:285:40)
 |     at DevServer.renderErrorToHTML (/Users/steida/dev/nberg/node_modules/next-server/dist/server/next-server.js:349:35)
 |     at DevServer.renderErrorToHTML (/Users/steida/dev/nberg/node_modules/next/dist/server/next-dev-server.js:15:706)
 |     at process._tickCallback (internal/process/next_tick.js:68:7) code: 'MODULE_NOT_FOUND' }
 | { Error: Cannot find module '/Users/steida/dev/nberg/packages/web/.next/server/static/development/pages/_document'
 |     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)
 |     at Function.Module._load (internal/modules/cjs/loader.js:508:25)
 |     at Module.require (internal/modules/cjs/loader.js:637:17)
 |     at require (internal/modules/cjs/helpers.js:22:18)
```

**Comment by Timer** [comment]
This is likely a configuration bug. We have tests covering `_document`!

Please share a full reproduction [on our Spectrum](https://spectrum.chat/next-js) so we may assist you.

**Comment by balazsorban44** [comment]
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
