### ISSUE TITLE
Deployment build freezes on building package from repository dependency

### ISSUE THREAD

**Issue by cereallarceny** [zeit/next.js#7881]
# Bug report

## Describe the bug

I am trying to deploy a Now site running Next.js.  I've done this before and have my aliases totally set up.  Deployment is done through the Github integration by pushing to `master`.  There's a dependency I have in my `package.json` file that's a branch on a public Github repository.  The build logs apparently show that it's stuck on trying to build this library.  In particular, [I'm trying to use Rebass at the update-styled-system branch](https://github.com/rebassjs/rebass/tree/update-styled-system).  Everything installs locally just fine.  I've cleared my `node_modules` folder and removed all package locks (yarn and NPM), as well as push these changes to Now.  No matter what, I have a perfectly fine development environment but do not have the ability to deploy.  The process has been stalled multiple times over multiple builds, sometimes for up to 2 hours.  Here's the task it's getting hung on:

`npm run clean && babel src -d dist && npm run emotion`

This is the `prepare` script located in the Rebass repository.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Clone https://github.com/mnsht/website
2. Try to deploy from the master branch
3. You cannot.

## Expected behavior

I expect the deployment process on Now to properly get the package and build it if necessary.

## Screenshots

<img width="1034" alt="Screen Shot 2019-07-10 at 6 18 31 PM" src="https://user-images.githubusercontent.com/1297930/60989968-350fb600-a33f-11e9-9216-6fbb4f6dcd03.png">
<img width="1036" alt="Screen Shot 2019-07-10 at 6 18 49 PM" src="https://user-images.githubusercontent.com/1297930/60989969-350fb600-a33f-11e9-9e2e-99223944e961.png">

## System information

- OS: macOS 10.14.5
- Browser (if applies): Doesn't apply, but... Brave Browser
- Version of Next.js: 8.1.0

## Additional context

Here's the entire log output:

```
TaskID d9730888-f355-43d7-8467-429c2312465a
@zeit/now-dcs-info: using https://dcs.now.systems as the upstream
running yarn for @now/build-utils@latest...
yarn add v1.16.0
info No lockfile found.
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Saved lockfile.
success Saved 41 new dependencies.
info Direct dependencies
└─ @now/build-utils@0.8.3
info All dependencies
├─ @now/build-utils@0.8.3
├─ async-retry@1.2.3
├─ async-sema@2.1.4
├─ balanced-match@1.0.0
├─ brace-expansion@1.1.11
├─ buffer-crc32@0.2.13
├─ concat-map@0.0.1
├─ core-util-is@1.0.2
├─ cross-spawn@6.0.5
├─ double-ended-queue@2.1.0-0
├─ end-of-stream@1.4.1
├─ from2@2.3.0
├─ fs-extra@7.0.0
├─ fs.realpath@1.0.0
├─ glob@7.1.3
├─ graceful-fs@4.2.0
├─ inflight@1.0.6
├─ inherits@2.0.4
├─ into-stream@5.0.0
├─ isarray@1.0.0
├─ isexe@2.0.0
├─ jsonfile@4.0.0
├─ minimatch@3.0.4
├─ multistream@2.1.1
├─ nice-try@1.0.5
├─ node-fetch@2.2.0
├─ p-is-promise@2.1.0
├─ path-is-absolute@1.0.1
├─ path-key@2.0.1
├─ process-nextick-args@2.0.1
├─ readable-stream@2.3.6
├─ retry@0.12.0
├─ safe-buffer@5.1.2
├─ semver@6.1.1
├─ shebang-command@1.2.0
├─ shebang-regex@1.0.0
├─ string_decoder@1.1.1
├─ universalify@0.1.2
├─ util-deprecate@1.0.2
├─ which@1.3.1
└─ yazl@2.4.3
Done in 1.88s.
running yarn for @now/next...
yarn add v1.16.0
info No lockfile found.
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Saved lockfile.
success Saved 10 new dependencies.
info Direct dependencies
└─ @now/next@0.5.3
info All dependencies
├─ @now/next@0.5.3
├─ @now/node-bridge@1.2.2
├─ fs-extra@7.0.1
├─ get-port@5.0.0
├─ graceful-fs@4.2.0
├─ jsonfile@4.0.0
├─ resolve-from@5.0.0
├─ semver@5.7.0
├─ type-fest@0.3.1
└─ universalify@0.1.2
Done in 0.53s.
running builder.exports.build...
[@now/next] Downloading user files...
missing `engines` in `package.json`, using default range: 8.10.x
MODE: serverless
Your application is being built using `next build`. If you need to define a different build step, please create a `now-build` script in your `package.json` (e.g. `{ "scripts": { "now-build": "npm run prepare && next build" } }`).
installing dependencies...
installing to /tmp/79b55ad5
yarn install v1.16.0
[1/4] Resolving packages...
[2/4] Fetching packages...
info No lockfile found.
warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
[1/4] Resolving packages...
warning gx > gatsby > @babel/polyfill@7.4.4: 🚨 As of Babel 7.4.0, this
package has been deprecated in favor of directly
including core-js/stable (to polyfill ECMAScript
features) and regenerator-runtime/runtime
(needed to use transpiled generator functions):

  > import "core-js/stable";
  > import "regenerator-runtime/runtime";
warning gx > gatsby > @gatsbyjs/relay-compiler > @babel/polyfill@7.4.4: 🚨 As of Babel 7.4.0, this
package has been deprecated in favor of directly
including core-js/stable (to polyfill ECMAScript
features) and regenerator-runtime/runtime
(needed to use transpiled generator functions):

  > import "core-js/stable";
  > import "regenerator-runtime/runtime";
warning gx > gatsby > @reach/router > create-react-context > fbjs > core-js@1.2.7: core-js@<2.6.8 is no longer maintained. Please, upgrade to core-js@3 or at least to actual version of core-js@2.
warning jest > jest-cli > jest-config > jest-environment-jsdom > jsdom > left-pad@1.3.0: use String.prototype.padStart()
[2/4] Fetching packages...
info fsevents@1.2.9: The platform "linux" is incompatible with this module.
info "fsevents@1.2.9" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Saved lockfile.
$ npm run clean && babel src -d dist && npm run emotion
```

**Comment by cereallarceny** [comment]
I finally got the deployment to error out.  Here's a screenshot of that.  No additional logs.

<img width="1061" alt="Screen Shot 2019-07-10 at 6 27 19 PM" src="https://user-images.githubusercontent.com/1297930/60990466-6046d500-a340-11e9-9914-e3e6b9fcaf5f.png">

**Comment by Timer** [comment]
Please upgrade to Next v9 first and see if this is fixed.

**Comment by cereallarceny** [comment]
Upgraded to Next@9.0.0 and deployed, I'm still getting an error although this was at least much quicker to error out (1 minute instead of ~30 minutes):

```
TaskID 252412bb-941b-4783-b776-dfc22470a021
running yarn for @now/build-utils@latest...
yarn add v1.16.0
info No lockfile found.
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Saved lockfile.
success Saved 40 new dependencies.
info Direct dependencies
└─ @now/build-utils@0.8.3
info All dependencies
├─ @now/build-utils@0.8.3
├─ async-retry@1.2.3
├─ async-sema@2.1.4
├─ balanced-match@1.0.0
├─ brace-expansion@1.1.11
├─ buffer-crc32@0.2.13
├─ concat-map@0.0.1
├─ core-util-is@1.0.2
├─ cross-spawn@6.0.5
├─ double-ended-queue@2.1.0-0
├─ end-of-stream@1.4.1
├─ from2@2.3.0
├─ fs-extra@7.0.0
├─ fs.realpath@1.0.0
├─ glob@7.1.3
├─ graceful-fs@4.2.0
├─ inflight@1.0.6
├─ into-stream@5.0.0
├─ isarray@1.0.0
├─ isexe@2.0.0
├─ jsonfile@4.0.0
├─ minimatch@3.0.4
├─ multistream@2.1.1
├─ nice-try@1.0.5
├─ node-fetch@2.2.0
├─ p-is-promise@2.1.0
├─ path-is-absolute@1.0.1
├─ path-key@2.0.1
├─ process-nextick-args@2.0.1
├─ readable-stream@2.3.6
├─ retry@0.12.0
├─ safe-buffer@5.1.2
├─ semver@6.1.1
├─ shebang-command@1.2.0
├─ shebang-regex@1.0.0
├─ string_decoder@1.1.1
├─ universalify@0.1.2
├─ util-deprecate@1.0.2
├─ which@1.3.1
└─ yazl@2.4.3
Done in 0.95s.
running yarn for @now/next...
yarn add v1.16.0
info No lockfile found.
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Saved lockfile.
success Saved 10 new dependencies.
info Direct dependencies
└─ @now/next@0.5.4
info All dependencies
├─ @now/next@0.5.4
├─ @now/node-bridge@1.2.2
├─ fs-extra@7.0.1
├─ get-port@5.0.0
├─ graceful-fs@4.2.0
├─ jsonfile@4.0.0
├─ resolve-from@5.0.0
├─ semver@5.7.0
├─ type-fest@0.3.1
└─ universalify@0.1.2
Done in 0.77s.
running builder.exports.build...
[@now/next] Downloading user files...
missing `engines` in `package.json`, using default range: 8.10.x
MODE: serverless
Your application is being built using `next build`. If you need to define a different build step, please create a `now-build` script in your `package.json` (e.g. `{ "scripts": { "now-build": "npm run prepare && next build" } }`).
installing dependencies...
installing to /tmp/7994e086
yarn install v1.16.0
[1/4] Resolving packages...
[2/4] Fetching packages...
info No lockfile found.
warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
[1/4] Resolving packages...
warning gx > gatsby > @babel/polyfill@7.4.4: 🚨 As of Babel 7.4.0, this
package has been deprecated in favor of directly
including core-js/stable (to polyfill ECMAScript
features) and regenerator-runtime/runtime
(needed to use transpiled generator functions):

  > import "core-js/stable";
  > import "regenerator-runtime/runtime";
warning gx > gatsby > @gatsbyjs/relay-compiler > @babel/polyfill@7.4.4: 🚨 As of Babel 7.4.0, this
package has been deprecated in favor of directly
including core-js/stable (to polyfill ECMAScript
features) and regenerator-runtime/runtime
(needed to use transpiled generator functions):

  > import "core-js/stable";
  > import "regenerator-runtime/runtime";
warning gx > gatsby > @reach/router > create-react-context > fbjs > core-js@1.2.7: core-js@<2.6.8 is no longer maintained. Please, upgrade to core-js@3 or at least to actual version of core-js@2.
warning jest > jest-cli > jest-config > jest-environment-jsdom > jsdom > left-pad@1.3.0: use String.prototype.padStart()
[2/4] Fetching packages...
info fsevents@1.2.9: The platform "linux" is incompatible with this module.
info "fsevents@1.2.9" is an optional dependency and failed compatibility check. Excluding it from installation.
error execa@2.0.3: The engine "node" is incompatible with this module. Expected version "^8.12.0 || >=9.7.0". Got "8.10.0"
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
Error: Exited with 1
    at ChildProcess.child.on (/tmp/4220460c/.build-utils/node_modules/@now/build-utils/dist/fs/run-user-scripts.js:30:24)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
```

This may be unrelated, but I also notice it's not finding my `yarn.lock` file and instead using `package-lock.json`, which is very strange.  I cannot find the latter in my Sources panel, but I can find the former... is there a way I can clear this cache?  Is that necessary?  Would it have any effect on deployment?

Just thinking out loud!  It at least appears the message has no changed because I'm not even getting there - I think?

**Comment by cereallarceny** [comment]
I added a `node` `engines` definition to my `package.json` to get the install to continue, but now I'm back to the same problem as before.  Logs again:

```
TaskID 907a2d2f-1579-4804-b76f-322f40396551
running yarn for @now/build-utils@latest...
yarn add v1.16.0
info No lockfile found.
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Saved lockfile.
success Saved 40 new dependencies.
info Direct dependencies
└─ @now/build-utils@0.8.3
info All dependencies
├─ @now/build-utils@0.8.3
├─ async-retry@1.2.3
├─ async-sema@2.1.4
├─ balanced-match@1.0.0
├─ brace-expansion@1.1.11
├─ buffer-crc32@0.2.13
├─ concat-map@0.0.1
├─ core-util-is@1.0.2
├─ cross-spawn@6.0.5
├─ double-ended-queue@2.1.0-0
├─ end-of-stream@1.4.1
├─ from2@2.3.0
├─ fs-extra@7.0.0
├─ fs.realpath@1.0.0
├─ glob@7.1.3
├─ graceful-fs@4.2.0
├─ inflight@1.0.6
├─ into-stream@5.0.0
├─ isarray@1.0.0
├─ isexe@2.0.0
├─ jsonfile@4.0.0
├─ minimatch@3.0.4
├─ multistream@2.1.1
├─ nice-try@1.0.5
├─ node-fetch@2.2.0
├─ p-is-promise@2.1.0
├─ path-is-absolute@1.0.1
├─ path-key@2.0.1
├─ process-nextick-args@2.0.1
├─ readable-stream@2.3.6
├─ retry@0.12.0
├─ safe-buffer@5.1.2
├─ semver@6.1.1
├─ shebang-command@1.2.0
├─ shebang-regex@1.0.0
├─ string_decoder@1.1.1
├─ universalify@0.1.2
├─ util-deprecate@1.0.2
├─ which@1.3.1
└─ yazl@2.4.3
Done in 1.25s.
running yarn for @now/next...
yarn add v1.16.0
info No lockfile found.
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Saved lockfile.
success Saved 10 new dependencies.
info Direct dependencies
└─ @now/next@0.5.4
info All dependencies
├─ @now/next@0.5.4
├─ @now/node-bridge@1.2.2
├─ fs-extra@7.0.1
├─ get-port@5.0.0
├─ graceful-fs@4.2.0
├─ jsonfile@4.0.0
├─ resolve-from@5.0.0
├─ semver@5.7.0
├─ type-fest@0.3.1
└─ universalify@0.1.2
Done in 0.84s.
running builder.exports.build...
[@now/next] Downloading user files...
Found `engines` in `package.json`, selecting range: 10.x
MODE: serverless
Your application is being built using `next build`. If you need to define a different build step, please create a `now-build` script in your `package.json` (e.g. `{ "scripts": { "now-build": "npm run prepare && next build" } }`).
installing dependencies...
installing to /tmp/769b1400
yarn install v1.16.0
[1/4] Resolving packages...
[2/4] Fetching packages...
info No lockfile found.
warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
[1/4] Resolving packages...
warning gx > gatsby > @babel/polyfill@7.4.4: 🚨 As of Babel 7.4.0, this
package has been deprecated in favor of directly
including core-js/stable (to polyfill ECMAScript
features) and regenerator-runtime/runtime
(needed to use transpiled generator functions):

  > import "core-js/stable";
  > import "regenerator-runtime/runtime";
warning gx > gatsby > @gatsbyjs/relay-compiler > @babel/polyfill@7.4.4: 🚨 As of Babel 7.4.0, this
package has been deprecated in favor of directly
including core-js/stable (to polyfill ECMAScript
features) and regenerator-runtime/runtime
(needed to use transpiled generator functions):

  > import "core-js/stable";
  > import "regenerator-runtime/runtime";
warning gx > gatsby > @reach/router > create-react-context > fbjs > core-js@1.2.7: core-js@<2.6.8 is no longer maintained. Please, upgrade to core-js@3 or at least to actual version of core-js@2.
warning jest > jest-cli > jest-config > jest-environment-jsdom > jsdom > left-pad@1.3.0: use String.prototype.padStart()
[2/4] Fetching packages...
info fsevents@1.2.9: The platform "linux" is incompatible with this module.
info "fsevents@1.2.9" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Saved lockfile.
$ npm run clean && babel src -d dist && npm run emotion
```

**Comment by masives** [comment]
It seems like your node version is to old

```
The engine "node" is incompatible with this module. Expected version "^8.12.0 || >=9.7.0". Got "8.10.0"
error Found incompatible module.
```

To check your node version run `node -v` in your command line

**Comment by cereallarceny** [comment]
If you look at my latest comment, I already bumped the node engine version
in my package.json.  It got me back to the original issue I mentioned.

**Comment by cereallarceny** [comment]
I've updated my deployment to use styled-components according to the latest example in your examples.  I've also removed all image optimization in my `next.config.js` to simplify things as much as possible.  It now only includes the following:

```js
module.exports = {
  target: 'serverless'
};
```

@masives @Timer **Is there anything else I can be trying?  I'm still facing the exact same problem.**

**Comment by Timer** [comment]
Can you please upgrade to the newest Next.js canary and try using the `@now/next` builder?

**Comment by cereallarceny** [comment]
Fixed, actually unrelated... but upgrading to the canary version of `next` helped show another error.  I had my styled-components `_theme.js` file inside the `pages` directory.  I didn't know that wasn't allowed.

Once I moved that, I upgraded my CLI to 1.16 (Now V2), removed the now config file, and added the `next build` script to my `package.json`.  Works like a charm - thanks @Timer.

**Comment by balazsorban44** [comment]
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
