### ISSUE TITLE
Custom pages/_error.js doesn't work for serverless deployment

### ISSUE THREAD

**Issue by wilsonpage** [zeit/next.js#7977]
# Bug report

## Describe the bug

When using `target: 'serverless'` I'm running into an exception in next code that prevents my custom `pages/_error.js` page from rendering:

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

Reduced test-case: https://github.com/wilsonpage/now-test-serverless-custom-error-page

## Expected behavior

When an exception is thrown in a page's `render()` method next should `500` error and render `pages/_error.js`.

## Stack trace

Full stack trace from `now logs` showing the initial error throw, then later a `next` internal error related to `experimentalPrerender`:

```
Error: wat
  at Page (/var/task/page.js:6886:9)
  at c (/var/task/page.js:2542:501)
  at Sa (/var/task/page.js:2545:1)
  at a.module.exports.FDah.a.render (/var/task/page.js:2550:467)
  at a.module.exports.FDah.a.read (/var/task/page.js:2550:58)
  at renderToString (/var/task/page.js:2562:83)
  at render (/var/task/page.js:4592:16)
  at renderPage (/var/task/page.js:4741:20)
  at _callee2$ (/var/task/page.js:5588:24)
  at tryCatch (/var/task/page.js:8175:40)
2019-07-15T15:42:28.270Z 3cdab899-ea89-426f-b13b-4b4571b0ed36    TypeError: Cannot read property 'experimentalPrerender' of undefined
      at renderToHTML (/var/task/page.js:4620:43)
      at <anonymous>
      at process._tickDomainCallback (internal/process/next_tick.js:228:7)
```

## System information

- OS: Deployed via `Now`
- Version of Next.js: 9.0.1

**Comment by wilsonpage** [comment]
Can confirm when downgrading to `next@8.1.0` the bug is not present.

**Comment by balazsorban44** [comment]
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
