### ISSUE TITLE
Unexpected token ( when running npm run dev from quickstart in windows

### ISSUE THREAD

**Issue by charlottetan** [zeit/next.js#8143]
# Unexpected token ( when `npm run dev`

## Getting Started > Setup

https://nextjs.org/learn/basics/getting-started/setup

## Describe the bug

Followed the instructions in Setup and unable to do `npm run dev`.

## To Reproduce

https://nextjs.org/learn/basics/getting-started/setup
Run through steps from above using Windows 10 machine, tried in both cmd and powershell

```
mkdir hello-next
cd hello-next
npm init -y
npm install --save react react-dom next
mkdir pages
```
modified package.json

ran `npm run dev`

## Expected behavior

No errors and http://localhost:3000 running

## System information

- OS: [e.g. Windows10]
- Version of Next.js: 9.0.1, 9.0.2

## Additional context

Output was:

```
node_modules\next\dist\bin\next:4
console.warn(`The module '${dependency}' was not found. Next.js requires that you include it in 'dependencies' of your 'package.json'. To add it, run 'npm install --save ${dependency}'`);}});const defaultCommand='dev';const commands={build:async()=>await Promise.resolve().then(()=>_interopRequireWildcard(require('../cli/next-build'))).then(i=>i.nextBuild),start:async()=>await Promise.resolve().then(()=>_interopRequireWildcard(require('../cli/next-start'))).then(i=>i.nextStart),export:async()=>await Promise.resolve().then(()=>_interopRequireWildcard(require('../cli/next-export'))).then(i=>i.nextExport),dev:async()=>await Promise.resolve().then(()=>_interopRequireWildcard(require('../cli/next-dev'))).then(i=>i.nextDev)};const args=(0,_index.default)({// Types
                                                                                                                        
SyntaxError: Unexpected token (
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! hello-next@1.0.0 dev: `next`
npm ERR! Exit status 1
npm ERR!
```

Seems like code comes from [next.js/packages/next/bin/next.ts](https://github.com/zeit/next.js/blob/master/packages/next/bin/next.ts)

**Comment by charlottetan** [comment]
was running an old version of node. updated node and fine now

**Comment by balazsorban44** [comment]
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
