### ISSUE TITLE
Using preact in serverless mode causes errors when deployed to now.sh

### ISSUE THREAD

**Issue by romellogoodman** [zeit/next.js#8188]
# Bug report

## Describe the bug

I am trying to use preact with next.js with a serverless target. I forked a version of using-preact example and upgraded to use another preact plugin so that I could take advantage of preact X features. The repo can be found [here](https://github.com/zeit/next-plugins/tree/master/packages/next-preact) and when run locally this works like a charm. The issue is that when I deploy the app to now.sh I get the following errors:

```
Unable to import module 'now__launcher': Error
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.cDcd (/var/task/page.js:7333:18)
    at __webpack_require__ (/var/task/page.js:23:31)
    at Object.R+7f (/var/task/page.js:4591:33)
    at __webpack_require__ (/var/task/page.js:23:31)
    at Module.Ct0T (/var/task/page.js:2586:88)
    at __webpack_require__ (/var/task/page.js:23:31)
```

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Clone the repo above
2. Deploy to now.sh
3. Try to load the page

## Expected behavior

I expected that the page to load and for the app to work the same as it does locally.

## System information

- OS: [e.g. macOS, Windows]
- Browser (if applies) [e.g. chrome, safari]
- Version of Next.js: [e.g. 6.0.2]

**Comment by tky5622** [comment]
Is this issue  in progress?

**Comment by Siilwyn** [comment]
More background information can be found here: https://spectrum.chat/next-js/general/using-preact-in-serverless-mode~4975e9ad-4ede-4342-96b9-fc31f25c4bdd

@timneutkens any plans for this on the roadmap?

**Comment by romellogoodman** [comment]
@timneutkens could you possibly provide some insight here?

**Comment by Siilwyn** [comment]
Found a working example by no other than Jason Miller himself (the author of Preact) using preact-compat: https://github.com/developit/nextjs-preact-demo

Tested it with a deploy on Now aswell, and everything works smoothly. Wonder if I can remove the compat dependency and go pure Preact. :thinking:

**Comment by romellogoodman** [comment]
@Siilwyn that example doesnt use serverless mode though. I would really like to use next.js and preact on now serverless

**Comment by Siilwyn** [comment]
I am using serverless mode using that example and it works perfectly. That's what I referred to with:
> Tested it with a deploy on Now aswell, and everything works smoothly.

**Comment by marcelalburg** [comment]
Any new news here ?

**Comment by timneutkens** [comment]
This was solved with the new example: https://github.com/zeit/next.js/tree/canary/examples/using-preact

**Comment by marcelalburg** [comment]
Interesting. Based on the provided example, I cannot see any configuration to use preact. Does it mean, that next discover the existence of preact automatically ?

**Comment by timneutkens** [comment]
It uses npm/yarn resolving to install `preact` into the `react` and `react-dom` package instead: https://github.com/zeit/next.js/blob/canary/examples/using-preact/package.json#L9-L15

**Comment by balazsorban44** [comment]
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
