### ISSUE TITLE
Clickable errors: upgrade next:fork-ts-checker-webpack-plugin to 1.5.0

### ISSUE THREAD

**Issue by prevostc** [zeit/next.js#8229]
# Feature request

I would like to be able to click a Typescript error filename to jump directly to the error position in the file.

Given the page

```

const Index = () => (
  <div>
    <p>Hello Next.ts</p>
  </div>
);
  
const a = 1

// reasign a const, bouuuh
a = 10

export default Index;
```

The console error is

```
[ error ] ERROR in /Users/prevostc/Projects/open-source/hello-next/pages/err-ts.tsx
12:1 Cannot assign to 'a' because it is a constant.
    10 | 
    11 | // reasign a const, bouuuh
  > 12 | a = 10
       | ^
    13 | 
    14 | export default Index;
```

Where it would be much more comfortable with the following syntax

```
[ error ] ERROR in /Users/prevostc/Projects/open-source/hello-next/pages/err-ts.tsx(12,1)
12:1 Cannot assign to 'a' because it is a constant.
    10 | 
    11 | // reasign a const, bouuuh
  > 12 | a = 10
       | ^
    13 | 
    14 | export default Index;
```

## Is your feature request related to a problem? Please describe.

Right now, errors are show in the console like so:
`[ error ] ERROR in <filename>`

IDEs allow you to ctrl+click on filenames to jump directly to the incriminated file. But this syntax just jump to the first line of the file. We can do better. If the error was shown in the console like so:
`[ error ] ERROR in <filename>(<line>,<char>)`

We could click on this and most IDEs will jump directly to the proper line and char of the file.

## Describe the solution you'd like

I went ahead and submitted the appropriate patch to the TS lib that you use: https://github.com/TypeStrong/fork-ts-checker-webpack-plugin/pull/320
This patch just got accepted and is merged in the 1.5.0 version.

## Describe alternatives you've considered

I tried to create a nextjs patch but there is 2 failed tests, and I could not understand how to debug selenium tests. I would be pleased to contribute a proper patch if 

```
diff --git a/packages/next/package.json b/packages/next/package.json
index 82985b8e..f5326ca5 100644
--- a/packages/next/package.json
+++ b/packages/next/package.json
@@ -77,7 +77,7 @@
     "babel-plugin-transform-react-remove-prop-types": "0.4.24",
     "chalk": "2.4.2",
     "find-up": "4.0.0",
-    "fork-ts-checker-webpack-plugin": "1.3.4",
+    "fork-ts-checker-webpack-plugin": "1.5.0",
     "fresh": "0.5.2",
     "launch-editor": "2.2.1",
     "loader-utils": "1.2.3",
```
```
ModuleNotFoundError: Module not found: Error: Can't resolve 'css-framework/framework.css' in '/Users/prevostc/Projects/open-source/next.js/test/integration/config/components'

... some stack trace

  ● Configuration › Configuration › should update css styles using hmr

    [elementByCss(".hello-world")] Error response status: 7, , NoSuchElement - An element could not be located on the page using the given search parameters. Selenium error: no such element: Unable to locate element: {"method":"css selector","selector":".hello-world"}
      (Session info: headless chrome=75.0.3770.142)
      (Driver info: chromedriver=2.46.628411 (3324f4c8be9ff2f70a05a30ebc72ffb013e1a71e),platform=Mac OS X 10.14.5 x86_64)

      at Object.<anonymous>.exports.newError (../node_modules/wd/lib/utils.js:152:13)
      at ../node_modules/wd/lib/callbacks.js:94:19
      at ../node_modules/wd/lib/webdriver.js:194:5
      at Request._callback (../node_modules/wd/lib/http-utils.js:89:7)
      at Request.self.callback (../node_modules/request/request.js:185:22)
      at Request.<anonymous> (../node_modules/request/request.js:1161:10)
      at IncomingMessage.<anonymous> (../node_modules/request/request.js:1083:12)
```

I've considered doing the patch myself, and failed :)

**Comment by Timer** [comment]
Feel free to send a PR upgrading this and we can take a look at the errors, but it'll get upgraded sometime soon with our routine dependency maintenance!

**Comment by NakulTrepp2867** [comment]
same error have to remove plugin

**Comment by balazsorban44** [comment]
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
