### ISSUE TITLE
Server-side error in with-loading example?

### ISSUE THREAD

**Issue by moarwick** [zeit/next.js#827]
The [with-loading](https://github.com/zeit/next.js/tree/master/examples/with-loading) example works well client-side, but on hard refreshing the `/forever` or `/about` routes, it throws `Cannot read property 'Component' of undefined`. `Component` is being imported from `React` in those two pages. Full trace:

```
TypeError: Cannot read property 'Component' of undefined
    at _callee3$ (http://localhost:3000/_next/-/main.js:11570:50)
    at tryCatch (http://localhost:3000/_next/-/commons.js:12871:40)
    at Generator.invoke [as _invoke] (http://localhost:3000/_next/-/commons.js:13162:22)
    at Generator.prototype.(anonymous function) [as next] (http://localhost:3000/_next/-/commons.js:12923:21)
    at step (http://localhost:3000/_next/-/commons.js:3111:30)
    at http://localhost:3000/_next/-/commons.js:3129:14
    at F (http://localhost:3000/_next/-/commons.js:1634:28)
    at http://localhost:3000/_next/-/commons.js:3108:12
    at doRender (http://localhost:3000/_next/-/main.js:11587:18)
    at Object._callee$ (http://localhost:3000/_next/-/main.js:11489:20)
```

**Comment by arunoda** [comment]
### Research Notes:

Returning null (or nothing) from `getInitialProps()` cause this issue.

**Comment by matthewmueller** [comment]
+1 I've run into this before, returning `{}` resolves the issue, but it'd be good to provide that default.
