### ISSUE TITLE
Unknown plugin "transform-async-to-generator"

### ISSUE THREAD

**Issue by gko** [zeit/next.js#84]
Platform: Linux (Arch) x86_64
node: v6.9.1
npm: 3.10.9

pages/index.js:
```javascript
import React from 'react'
export default () => (
  <div>Welcome to next.js!</div>
)
```

when I run `next` I get:
```bash
ERROR in ./pages/index.js
Module build failed: ReferenceError: Unknown plugin "transform-async-to-generator" specified in "base" at 0, attempted to resolve relative to "/home/gk/projects/test/pages"
    at /usr/lib/node_modules/next/node_modules/babel-core/lib/transformation/file/options/option-manager.js:176:17
    at Array.map (native)
    at Function.normalisePlugins (/usr/lib/node_modules/next/node_modules/babel-core/lib/transformation/file/options/option-manager.js:154:20)
    at OptionManager.mergeOptions (/usr/lib/node_modules/next/node_modules/babel-core/lib/transformation/file/options/option-manager.js:228:36)
    at OptionManager.init (/usr/lib/node_modules/next/node_modules/babel-core/lib/transformation/file/options/option-manager.js:373:12)
    at File.initOptions (/usr/lib/node_modules/next/node_modules/babel-core/lib/transformation/file/index.js:221:65)
    at new File (/usr/lib/node_modules/next/node_modules/babel-core/lib/transformation/file/index.js:141:24)
    at Pipeline.transform (/usr/lib/node_modules/next/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at transpile (/usr/lib/node_modules/next/node_modules/babel-loader/index.js:38:20)
    at Object.module.exports (/usr/lib/node_modules/next/node_modules/babel-loader/index.js:131:12)
 @ multi bundles/pages/index.js
```

**Comment by gazaston** [comment]
I had this… node v7 & npm v3 got it running.

**Comment by gko** [comment]
Hm, I looked through package.json of those and there is specific node version req.

**Comment by nkzawa** [comment]
seems the same issue with https://github.com/zeit/next.js/issues/83

**Comment by gko** [comment]
@nkzawa I used npm v3, so the cause not npm specific. Sorry couldn't find that bug cause error message wasn't specified directly in issue.

**Comment by nodegin** [comment]
I had the same problem before, fixed by upgrading to node v7 and reinstall all dependencies.

**Comment by gko** [comment]
@nodegin yes, but since there is no specific engine req in package.json it's a bug.

**Comment by nkzawa** [comment]
I think it's fixed by https://github.com/zeit/next.js/commit/ca161c375f22c71549849595b68f3e43eda94a89
Feel free to reopen if it still occurs.

**Comment by yinsu12311** [comment]
I also had this… node v7.9 & npm v4.2 in mac.
I have another computer , node v6.10.1 npm v3.10.10 in windows, same code ,not have this problem.
how can I solve this problem.
