### ISSUE TITLE
export-namespace-from is not respected

### ISSUE THREAD

**Issue by kuldeepkeshwar** [zeit/next.js#8404]
**Describe the bug**
Seems like `export-namespace-from` is not respected when used with Next.js

```
/sandbox/node_modules/react-dnd/dist/esm/index.js:1
export * from './common';
^^^^^^

SyntaxError: Unexpected token export
    at Module._compile (internal/modules/cjs/loader.js:721:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.react-dnd (/sandbox/.next/server/static/development/pages/index.js:1298:18)
    at __webpack_require__ (/sandbox/.next/server/static/development/pages/index.js:23:31)
    at Module../pages/index.js (/sandbox/.next/server/static/development/pages/index.js:1087:67)
    at __webpack_require__ (/sandbox/.next/server/static/development/pages/index.js:23:31)
    at Object.3 (/sandbox/.next/server/static/development/pages/index.js:1132:18)
    at __webpack_require__ (/sandbox/.next/server/static/development/pages/index.js:23:31)
    at /sandbox/.next/server/static/development/pages/index.js:91:18
    at Object.<anonymous> (/sandbox/.next/server/static/development/pages/index.js:94:10)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
```
**Reproduction**

[Live Reproduction](https://codesandbox.io/s/test-nextjs-and-react-dnd-3wh28)

1. start any project with Next.js
2. install `react-dnd`
3. run the `yarn dev`

**Expected behavior**
It should get complied 

Although, the same works with CRA, [demo](https://codesandbox.io/s/test-react-dnd-ndmhu) here

**Comment by Timer** [comment]
Next.js does not compile `node_modules` -- this package only ships ESM source code. You'll need to customize your webpack configuration to include this package in the compilation pipeline.

See https://github.com/martpie/next-transpile-modules.

**Comment by balazsorban44** [comment]
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
