### ISSUE TITLE
Dev works but build fails with window undefined

### ISSUE THREAD

**Issue by rohan-deshpande** [zeit/next.js#8412]
# Bug report

## Describe the bug

My app will not build and fails with the error that `window` is undefined. A library which I use depends on `window` existing. To safeguard against this, I've got my instantiating code in a conditional `require` within `componentDidMount`, I also load the component asynchronously. Dev mode works fine but `npm run build` throws an error. 

## To Reproduce

Relevant code:

```javascript
  async componentDidMount() {
    // guards against nextjs errors for window being undefined on the server
    if (typeof window === 'undefined') {
      return;
    }

    const { Visualisation } = require('./Visualisation');

    this.visualisation = await new Visualisation(this.canvas).start();

    window.addEventListener('resize', this.handleResize);
  }
```

How the component is included:

```
import { Content, Grid } from '../../../common/components';

import Blurb from './Blurb';
import React from 'react';
import Video from './Video';
import dynamic from 'next/dynamic';

const Canvas = dynamic(import('./Canvas'), { ssr: false });

export default () => (
  <Content className="Hero">
    <Canvas />
    <Grid>
      <Blurb />
      <Video />
    </Grid>
  </Content>
);
```

## Expected behavior

`npm run build` should work the same way that `npm run dev` does and not throw an error

## Screenshots

```
Creating an optimized production build ...

Compiled successfully.

> Build error occurred
ReferenceError: window is not defined
    at Object.<anonymous> (/Users/rohandeshpande/Projects/nebula-web/next/node_modules/three-nebula/build/three-nebula.js:1:194)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:643:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Module.require (internal/modules/cjs/loader.js:683:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.0Fqd (/Users/rohandeshpande/Projects/nebula-web/next/.next/server/static/pf0BOmVPNP14gsZUWnWbb/pages/home/Hero/Canvas/Visualisation.js:274:18)
    at __webpack_require__ (/Users/rohandeshpande/Projects/nebula-web/next/.next/server/static/pf0BOmVPNP14gsZUWnWbb/pages/home/Hero/Canvas/Visualisation.js:23:31)
    at Module.00Zi (/Users/rohandeshpande/Projects/nebula-web/next/.next/server/static/pf0BOmVPNP14gsZUWnWbb/pages/home/Hero/Canvas/Visualisation.js:107:70) {
  type: 'ReferenceError',
  '$error': '$error'
}
```

## System information

- OS: `MacOS Mojave 10.14.5`
- Browser (if applies) [e.g. chrome, safari]: `N/A`
- Version of Next.js: [e.g. 6.0.2]: `@latest`

**Comment by Timer** [comment]
The code you provided does not appear relevant. Please provide a fully reproducible demo for us to look at.

**Comment by rohan-deshpande** [comment]
https://github.com/creativelifeform/nebula-web/tree/feature/nextjs

No errors:

```
cd next 
npm run dev
```

But if you do

```
cd next
npm run build
```

You'll get the error described above

**Comment by ijjk** [comment]
Hi @rohan-deshpande, it looks like it's due to the dependency `three-nubla` requiring `window` be present and is imported at the top level. 

If you remove this import: `import ParticleSystem, { SpriteRenderer } from 'three-nebula';` and change `makeParticleSystem` to 
```js
async makeParticleSystem () {
    const { default: ParticleSystem, SpriteRenderer } = await import('three-nebula')
```
in `./next/pages/home/Hero/Canvas/Visualisation/index.js` it should resolve that issue, but it also looks like you are putting non-pages in the `pages` directory. Any files that aren't meant to be a URL (e.g. `/home`) should be moved to a components or similar folder. 

The following files in the pages directory don't appear to be actual pages:
```
pages/download/constants
pages/download/Form/Spinner
pages/download/Form/Email
pages/home/Hero/Canvas/Visualisation/data
pages/download/Form/Error
pages/editions/Feature
pages/download/Form/PlatformSelect
pages/download/Form
pages/editions/ComingSoon
pages/home/Hero/Canvas/Visualisation
```

If you are still encountering trouble feel free to reply with additional info

**Comment by balazsorban44** [comment]
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
