### ISSUE TITLE
with-react-relay-network-modern throwing error

### ISSUE THREAD

**Issue by juhaelee** [zeit/next.js#8448]
## Describe the bug

When running `yarn dev`, the server spits out the following error:

```
TypeError: Cannot read property 'edges' of undefined
    at BlogPosts (/Users/ju.lee/Projects/testy/.next/server/static/development/pages/index.js:173:47)
    at processChild (/Users/ju.lee/Projects/testy/node_modules/react-dom/cjs/react-dom-server.node.development.js:3090:14)
    at resolve (/Users/ju.lee/Projects/testy/node_modules/react-dom/cjs/react-dom-server.node.development.js:3013:5)
    at ReactDOMServerRenderer.render (/Users/ju.lee/Projects/testy/node_modules/react-dom/cjs/react-dom-server.node.development.js:3436:22)
    at ReactDOMServerRenderer.read (/Users/ju.lee/Projects/testy/node_modules/react-dom/cjs/react-dom-server.node.development.js:3395:29)
    at renderToString (/Users/ju.lee/Projects/testy/node_modules/react-dom/cjs/react-dom-server.node.development.js:3954:27)
    at render (/Users/ju.lee/Projects/testy/node_modules/next-server/dist/server/render.js:80:16)
    at renderPage (/Users/ju.lee/Projects/testy/node_modules/next-server/dist/server/render.js:261:20)
    at /Users/ju.lee/Projects/testy/.next/server/static/development/pages/_document.js:437:17
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/Users/ju.lee/Projects/testy/.next/server/static/development/pages/_document.js:206:24)
    at _next (/Users/ju.lee/Projects/testy/.next/server/static/development/pages/_document.js:228:9)
    at /Users/ju.lee/Projects/testy/.next/server/static/development/pages/_document.js:235:7
    at new Promise (<anonymous>)
    at new F (/Users/ju.lee/Projects/testy/node_modules/core-js/library/modules/_export.js:36:28)
    at /Users/ju.lee/Projects/testy/.next/server/static/development/pages/_document.js:224:12
```

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Follow example from https://github.com/zeit/next.js/tree/canary/examples/with-react-relay-network-modern
2.  Run example and go to http://localhost:3000/
3. refresh website if error doesn't throw initially

## Expected behavior

Expect the example to load the page and work on refresh

## Screenshots

![Screen Shot 2019-08-20 at 10 31 20 AM](https://user-images.githubusercontent.com/606411/63369865-ba6e8900-c335-11e9-9c5d-6471a364ae4c.png)

## System information

- OS: maxOS
- Browser: Chrome Version 75.0.3770.100 (Official Build) (64-bit)
- Version of Next.js: latest (9.0.4)

**Comment by balazsorban44** [comment]
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
