### ISSUE TITLE
SSR in next v9 w/ apollo react hooks does not work

### ISSUE THREAD

**Issue by nephix** [zeit/next.js#8538]
# Bug report

## Describe the bug

When trying to SSR a query via `getDataFromTree()` of a component which contains hooks from `@apollo/react-hooks`, there's an error in the console and the query is executed in the browser instead of being rendered on the server.

I have investigated this quite a bit and found a lot of older tickets which seem to relate to the `useRouter` hook that caused a similar error message:

> Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.
> 
> Check your code at _app.js:15.
>     in MyApp (at withApollo.js:49)
>     in Context.Provider
> Error while running `getDataFromTree` TypeError: Cannot read property 'pathname' of undefined
>     at makePublicRouterInstance (/Users/nephix/Projects/nextjs-graphql/.next/server/static/development/pages/_app.js:748:23)
>     at MyApp.getChildContext (/Users/nephix/Projects/nextjs-graphql/.next/server/static/development/pages/_app.js:879:52)
>     at processChild (/Users/nephix/Projects/nextjs-graphql/node_modules/react-dom/cjs/react-dom-server.node.development.js:3194:31)
>     at resolve (/Users/nephix/Projects/nextjs-graphql/node_modules/react-dom/cjs/react-dom-server.node.development.js:3013:5)
>     at ReactDOMServerRenderer.render (/Users/nephix/Projects/nextjs-graphql/node_modules/react-dom/cjs/react-dom-server.node.development.js:3436:22)
>     at ReactDOMServerRenderer.read (/Users/nephix/Projects/nextjs-graphql/node_modules/react-dom/cjs/react-dom-server.node.development.js:3395:29)
>     at renderToStaticMarkup (/Users/nephix/Projects/nextjs-graphql/node_modules/react-dom/cjs/react-dom-server.node.development.js:3969:27)
>     at process (/Users/nephix/Projects/nextjs-graphql/node_modules/@apollo/react-ssr/lib/react-ssr.cjs.js:38:16)

## To Reproduce

I have created a minimal example, I hope that helps.

```
$ git clone git@github.com:nephix/nextjs-apollo-issue-minimal-example.git
$ cd nextjs-apollo-issue-minimal-example
$ npm i
$ npm run dev
```

Then go to https://localhost:3000

## Expected behavior

Nextjs resolves the query via `getDataFromTree()`

## Screenshots

In the browser you can see that the query is executed after the page has been served:
<img width="1066" alt="Screenshot 2019-08-27 at 20 54 59" src="https://user-images.githubusercontent.com/3169205/63799755-0492d400-c90d-11e9-8080-1d73c89dbd18.png">

## System information

- OS: macOS
- Browser: chrome
- Version of Next.js: 9.0.5

## Additional context

The error message I have pasted seems to occur not all the time, but it definitely seems to be related because I have it pretty consistently in a larger project

**Comment by timneutkens** [comment]
You're rendering `<App>` in getDataFromTree, this should be AppTree as shown here: https://github.com/zeit/next.js/blob/7bd4f4f3bf7696ab0da666105e2220447e1486ef/examples/with-apollo/lib/apollo.js#L60

AppTree has the full Next.js tree with all needed providers. This was recently added.

**Comment by nephix** [comment]
@timneutkens I have already tried `AppTree` from https://github.com/zeit/next.js/blob/7bd4f4f3bf7696ab0da666105e2220447e1486ef/examples/with-apollo-auth/lib/withApollo.js#L30

but ditched it because it was constantly `undefined`

**Comment by HaNdTriX** [comment]
[with-apollo-auth](https://github.com/zeit/next.js/tree/7bd4f4f3bf7696ab0da666105e2220447e1486ef/examples/with-apollo-auth) is a bit outdated you might want to take a look at the [with-apollo](https://github.com/zeit/next.js/tree/7bd4f4f3bf7696ab0da666105e2220447e1486ef/examples/with-apollo) example. 

We`ve changed quite a lot of things there. As soon as I have time I will migrate the latest changes of [with-apollo](https://github.com/zeit/next.js/tree/7bd4f4f3bf7696ab0da666105e2220447e1486ef/examples/with-apollo) to the [with-apollo-auth](https://github.com/zeit/next.js/tree/7bd4f4f3bf7696ab0da666105e2220447e1486ef/examples/with-apollo-auth) example.


Please note that you can only apply the `with-apollo` HOC 

* to an `pages/_App.js`-Component in [with-apollo-auth](https://github.com/zeit/next.js/tree/7bd4f4f3bf7696ab0da666105e2220447e1486ef/examples/with-apollo-auth) or 
* to an `pages/<Component>.js` in [with-apollo](https://github.com/zeit/next.js/tree/7bd4f4f3bf7696ab0da666105e2220447e1486ef/examples/with-apollo).

If you apply the HOC deeper in your Component Tree, `getInitialProps` will be ignored and ssr won't work.

**Comment by nephix** [comment]
Thanks @HaNdTriX will check it out later today

**Comment by julmot** [comment]
Related to #8830

**Comment by balazsorban44** [comment]
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
