### ISSUE TITLE
Cannot continue using AMP while on hybrid-mode (non-amp)

### ISSUE THREAD

**Issue by iliran11** [zeit/next.js#8542]
Hi,
I want to continue using AMP components while not being on AMP valid page.
it speeds up development - for the non-AMP pages i continue using AMP components, but just adding few additional functionalities that requres javascript running on the client side.

the following page, while on non-AMP,  results in below error in client side:

```
import Head from 'next/head';

export const config = {
  hybrid: true
};

export default () => {
  return (
    <div>
      <Head>
        <script async src="https://cdn.ampproject.org/v0.js"></script>
      </Head>
      <p>hi</p>
    </div>
  );
};
```

```
Uncaught (in promise) DOMException: Failed to execute 'define' on 'CustomElementRegistry': the name "amp-img" has already been used with this registry
    at y.Xc.y.define (https://cdn.ampproject.org/v0.js:67:7)
    at y.Xc.y.define (https://cdn.ampproject.org/v0.js:67:7)
    at yj (https://cdn.ampproject.org/v0.js:288:757)
    at kj.Kd (https://cdn.ampproject.org/v0.js:558:23)
    at jj (https://cdn.ampproject.org/v0.js:247:834)
    at fj.zf (https://cdn.ampproject.org/v0.js:251:112)
    at https://cdn.ampproject.org/v0.js:251:319
```

**Comment by c0b41** [comment]
next.js already setup amp script tag for you [see](https://github.com/zeit/next.js/blob/847e892d71a5a20b36afeb40b7871491d5af4977/packages/next/pages/_document.tsx#L388)

**Comment by timneutkens** [comment]
Something like this would work:

```
export default () => {
const isAmp = useAmp()
  return (
    <div>
      {!isAmp && <Head>
        <script async src="https://cdn.ampproject.org/v0.js"></script>
      </Head>}
      <p>hi</p>
    </div>
  );
};
```

**Comment by iliran11** [comment]
@timneutkens 
It doesn't work for the regular page.
Did you actually tried to run it and no error for you?

i'm using the latest next.js. 9.0.5

**Comment by astraube** [comment]
For me the error message has stopped showing up.
The resolution was to use this:
```<link rel="preload" as="script" href="https://cdn.ampproject.org/v0.js">```

**Comment by balazsorban44** [comment]
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
