### ISSUE TITLE
ncc doesn't play well with nextjs builds, or am I doing something wrong?

### ISSUE THREAD

**Issue by armenr** [zeit/next.js#8574]
I've been using zeit's `ncc` to slim down and build our transpiled APIs into tiny, minified, individual scripts that run without any node_modules present on our servers/containers. It's **_absolutely_** fantastic.

I tried to us ncc w/ NextJS, but probably lack the requisite knowledge of understanding how nextJS builds work, and what is built into the output.

My goal: A single, transpiled/built file (or set of files w/ an exposed entrypoint script) that I can run without needing node_modules installed/present on my application servers/containers, which I can simply invoke with a command like:
`"NODE_ENV=production node --require 'dotenv/config' ./dist/index.js"`

We use a custom server with our nextJS app, but it's written in vanilla JS, and doesn't require transpilation, webpack, or babel. 

It does, however, have a handful of dependencies including a redis client and express.

I was thinking that maybe the correct thing to do is use ncc for the server, and `next build` for the client, and then just runn the ncc'ed server file?

If someone could point me in the direction of the best resolution, that would sincerely save me days of failed attempts and wasted hours.

Thank you!! :)

**Comment by timneutkens** [comment]
You'll want to use serverless builds: https://nextjs.org/docs#serverless-deployment

What made you ignore the issue template?

**Comment by armenr** [comment]
@timneutkens - these serverless builds will run on an a bare ec2 or bare docker with nothing but node installed?

**Comment by timneutkens** [comment]
Sure, all Next.js features still work, rendering is just different.

**Comment by armenr** [comment]
Just tested this out:

I get a build - 
```
-rw-r--r-- 1 vagrant vagrant   40 Aug 30 15:06 BUILD_ID
-rw-r--r-- 1 vagrant vagrant 6155 Aug 30 15:06 build-manifest.json
drwxr-xr-x 4 vagrant vagrant 4096 Aug 30 15:05 cache
-rw-r--r-- 1 vagrant vagrant 4586 Aug 30 15:06 react-loadable-manifest.json
-rw-r--r-- 1 vagrant vagrant 3315 Aug 30 15:06 records.json
drwxr-xr-x 3 vagrant vagrant 4096 Aug 30 15:06 serverless
drwxr-xr-x 5 vagrant vagrant 4096 Aug 30 15:06 static
```
So, how would I run this?

**Comment by Timer** [comment]
Did you try `next start`? It should work.

**Comment by armenr** [comment]
@Timer - the goal we're trying to achieve is to have nothing on the server installed other than nodeJS + dotenv installed globally. 

If ncc can bundle everything into a single file, such that you do not need a node_modules folder, or any other dependencies present...why would I have to have nextjs installed in order to run a similarly bundled next app w/ custom server?

The goal for us was to output a nextJS app + custom server to a single, runnable, zero-depenendency file (or set of files) that I can simply invoke from node, like so:

`NODE_PATH=/usr/lib/node_modules NODE_ENV=production node --require 'dotenv/config'`

Would either of you guys @Timer or @timneutkens know if this is doable? :)

**Comment by armenr** [comment]
## Progress update (in case you guys can help me juuuusst a little)

1) build nextJS and ncc build server.js file to ~/dist

    `NODE_ENV=production yarn build && NODE_ENV=production ncc build -s -m server.js -o ~/dist`

2) Copy nextJS build output to where the ncc-built server is  

    `mkdir ~/dist/client && cp -r client/.next to ~/dist/client/.next`

3) Pop into ~/dist and try to run the bad boy!

    ` cd ~/dist && NODE_ENV=production node index.js`

Server comes up, no problem - connects to Redis and to DB as expected.

Try to navigate to application home screen:
```
vagrant@web:~/dist$ NODE_ENV=production node index.js
{
  Server: 'myproj-NEXT-WEB',
  Message: 'Server Online! 🤘🏼🎧',
  Mode: 'production',
  Address: 'http://0.0.0.0:3000'
}
{ RedisConnected: true }
Error: Cannot find module 'core-js/library/fn/object/get-own-property-descriptor'
Require stack:
- /home/vagrant/dist/client/.next/server/static/a9943052f7c187908097f20d48f1616bb8590a58/pages/_document.js
- /home/vagrant/dist/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:772:15)
    at Function.Module._load (internal/modules/cjs/loader.js:677:27)
    at Module.require (internal/modules/cjs/loader.js:830:19)
    at require (internal/modules/cjs/helpers.js:68:18)
    at Object.Z6Kq (/home/vagrant/dist/client/.next/server/static/a9943052f7c187908097f20d48f1616bb8590a58/pages/webpack:/external "core-js/library/fn/object/get-own-property-descriptor":1:1)
    at __webpack_require__ (/home/vagrant/dist/client/.next/server/static/a9943052f7c187908097f20d48f1616bb8590a58/pages/webpack:/webpack/bootstrap:21:1)
    at Object.rx6U (/home/vagrant/dist/client/.next/server/static/a9943052f7c187908097f20d48f1616bb8590a58/pages/webpack:/opt/myproj/src/node_modules/@babel/runtime-corejs2/core-js/object/get-own-property-descriptor.js:1:18)
    at __webpack_require__ (/home/vagrant/dist/client/.next/server/static/a9943052f7c187908097f20d48f1616bb8590a58/pages/webpack:/webpack/bootstrap:21:1)
    at Object.Nx3I (/home/vagrant/dist/client/.next/server/static/a9943052f7c187908097f20d48f1616bb8590a58/pages/_document.js:370:35)
    at __webpack_require__ (/home/vagrant/dist/client/.next/server/static/a9943052f7c187908097f20d48f1616bb8590a58/pages/webpack:/webpack/bootstrap:21:1) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/vagrant/dist/client/.next/server/static/a9943052f7c187908097f20d48f1616bb8590a58/pages/_document.js',
    '/home/vagrant/dist/index.js'
  ]
}
Error: Cannot find module 'core-js/library/fn/object/get-own-property-descriptor'
Require stack:
- /home/vagrant/dist/client/.next/server/static/a9943052f7c187908097f20d48f1616bb8590a58/pages/_document.js
- /home/vagrant/dist/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:772:15)
    at Function.Module._load (internal/modules/cjs/loader.js:677:27)
    at Module.require (internal/modules/cjs/loader.js:830:19)
    at require (internal/modules/cjs/helpers.js:68:18)
    at Object.Z6Kq (/home/vagrant/dist/client/.next/server/static/a9943052f7c187908097f20d48f1616bb8590a58/pages/webpack:/external "core-js/library/fn/object/get-own-property-descriptor":1:1)
    at __webpack_require__ (/home/vagrant/dist/client/.next/server/static/a9943052f7c187908097f20d48f1616bb8590a58/pages/webpack:/webpack/bootstrap:21:1)
    at Object.rx6U (/home/vagrant/dist/client/.next/server/static/a9943052f7c187908097f20d48f1616bb8590a58/pages/webpack:/opt/myproj/src/node_modules/@babel/runtime-corejs2/core-js/object/get-own-property-descriptor.js:1:18)
    at __webpack_require__ (/home/vagrant/dist/client/.next/server/static/a9943052f7c187908097f20d48f1616bb8590a58/pages/webpack:/webpack/bootstrap:21:1)
    at Object.Nx3I (/home/vagrant/dist/client/.next/server/static/a9943052f7c187908097f20d48f1616bb8590a58/pages/_document.js:370:35)
    at __webpack_require__ (/home/vagrant/dist/client/.next/server/static/a9943052f7c187908097f20d48f1616bb8590a58/pages/webpack:/webpack/bootstrap:21:1) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/vagrant/dist/client/.next/server/static/a9943052f7c187908097f20d48f1616bb8590a58/pages/_document.js',
    '/home/vagrant/dist/index.js'
  ]
}
```

### Attempts to solve:

I thought maybe the thing to do is make corejs available in both versions (2 and 3) as dev dependencies, and to also install (explicitly) babel-polyfill

Dev Dependencies are as follows:

```
  "devDependencies": {
    "@babel/polyfill": "^7.4.4",
    "@babel/runtime-corejs2": "^7.5.5",
    "@babel/runtime-corejs3": "^7.5.5",
    "@zeit/next-source-maps": "^0.0.3",
    "babel-cli": "^6.26.0",
    "babel-plugin-root-import": "^6.2.0",
    "babel-plugin-styled-components": "^1.10.6",
    "babel-plugin-syntax-jsx": "^6.18.0",
    "babel-plugin-transform-define": "^1.3.1",
    "babel-preset-env": "^1.7.0",
    "eslint": "^5.16.0",
    "eslint-config-airbnb": "^17.1.0",
    "eslint-config-prettier": "^4.3.0",
    "eslint-plugin-import": "^2.17.3",
    "eslint-plugin-jsx-a11y": "^6.2.1",
    "eslint-plugin-prettier": "^3.1.0",
    "eslint-plugin-react": "^7.13.0",
    "next-build-id": "^3.0.0",
    "next-size": "^2.0.2",
    "nodemon": "^1.19.1",
    "prettier": "^1.17.1"
  },
```

Still won't find that missing module. *Any* help would be much appreciated. Thank you!! :)

**Comment by armenr** [comment]
Any thoughts, feedback, or ideas, guys? I feel like this is a legitimate use-case.

**Comment by eddiewang** [comment]
@armenr having the exact same problem as you. have you been able to figure out why `MODULE_NOT_FOUND` occurs after the server loads?

**Comment by armenr** [comment]
@eddiewang - I can help you. We've got NextJS + ncc fully and completely figured out. If you need help, just holla at me. 

Here's where we are today.

**Comment by barlock** [comment]
I'll probably open a separate issue for this to discuss how to make this approach "supported", but I was able to build a docker image with my app down to about 120mb which is about as small as I think is possible. "Normal" methods keep it around 400. Thought I'd leave this here in case anyone found this through google.

It amounted to 15mb for OS & node deps, 88mb for a "special" node binary, Xmb for your app's code (my simple one was 12).


You first need to set your target to `serverless`:

```js
// next.config.js
module.exports = {
  target: 'serverless',
};
```

Builds of your app will generate "lambdas" for each page. In this case, this probably introduces some duplication of code between pages, but I'll take that tradeoff for faster individual cold-boots.

Now we have to do something weird, we're going to use `ncc` and `pkg` to package 🥁 🥁 the next cli to give us a server, but specifically, only the part that does the serving. Create a new file `next-start.js`:

```js
// next-start.js
const { nextStart } = require('next/dist/cli/next-start');
nextStart(process.env.argv);
```

And we can build it `ncc build -m ./scripts/next-start.js && pkg -t host dist/index.js -o next-start`

☝️ This generates an 88mb binary that will run in base alpine with our generated builds. It is functionally equivalent to running `next start`. 

Now we can package that up in a docker file with a multi-stage build.... and you got yourself a tiny nextjs app in a container.

<details>
<summary>Full Dockerfile</summary>
```dockerfile
# Base ───────────────────────────────────────────────────────────────────────
FROM node:14-alpine as base

WORKDIR /opt/app

ENV PATH /opt/app/node_modules/.bin:$PATH

# Build ──────────────────────────────────────────────────────────────────────
FROM base as build

COPY package.json .
COPY yarn.lock .

RUN true  \
  && yarn install \
  && true

COPY . /opt/app

RUN true  \
  && yarn next build \
  && yarn ncc build -m ./scripts/next-start.js && pkg -t host dist/index.js -o next-start \
  && true

# Service ────────────────────────────────────────────────────────────────────
FROM alpine

WORKDIR /opt/app
ENV NODE_ENV production
ENV PORT 8080

RUN apk update && \
  apk add --no-cache libstdc++ libgcc ca-certificates && \
  rm -rf /var/cache/apk/*

COPY --from=build /opt/app/next.config.js .
COPY --from=build /opt/app/next-start .
COPY --from=build /opt/app/.next .next
COPY --from=build /opt/app/public public

RUN true \
  && addgroup -g 1001 -S nodejs \
  && adduser -S nextjs -u 1001 \
  && true

USER nextjs

CMD [ "./next-start", "-p", "$PORT" ]
```


</details>

**Comment by martaver** [comment]
@barlock in your Dockerfile, how does the 'Service' stage work? You're basing of a plain alpine image, but nowhere can I see that node installed. Did you mean to base the Service stage off `node:14-alpine` too?

**Comment by balazsorban44** [comment]
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
