### ISSUE TITLE
"Invalid Hook Calls" for Redux

### ISSUE THREAD

**Issue by alex067** [zeit/next.js#8930]
# Examples bug report
The bug is for the redux example.

## Example name
 with-redux

## Describe the bug
Installed the example with no other modifications. Ran the build, and we get an invalid Hook call error. 

I have been having this issue on my personal project as well, when trying to implement Redux.

```
Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons: 1. You might have mismatching versions of React and the renderer (such as React DOM) 2. You might be breaking the Rules of Hooks 3. You might have more than one copy of React in the same app See https://fb.me/react-invalid-hook-call for tips about how to debug and fix this problem.

Invariant Violation: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://fb.me/react-invalid-hook-call for tips about how to debug and fix this problem.
    at D:\documents\with-redux-app\node_modules\react\cjs\react.development.js:1607:26
    at resolveDispatcher (D:\documents\with-redux-app\node_modules\react\cjs\react.development.js:1610:5)
    at useMemo (D:\documents\with-redux-app\node_modules\react\cjs\react.development.js:1660:20)
    at Provider (D:\documents\with-redux-app\node_modules\react-redux\lib\components\Provider.js:22:41)
    at processChild (D:\Documents\with-redux-app\node_modules\react-dom\cjs\react-dom-server.node.development.js:3227:14)
    at resolve (D:\Documents\with-redux-app\node_modules\react-dom\cjs\react-dom-server.node.development.js:3147:5)
    at ReactDOMServerRenderer.render (D:\Documents\with-redux-app\node_modules\react-dom\cjs\react-dom-server.node.development.js:3631:22)
    at ReactDOMServerRenderer.read (D:\Documents\with-redux-app\node_modules\react-dom\cjs\react-dom-server.node.development.js:3565:29)
    at renderToString (D:\Documents\with-redux-app\node_modules\react-dom\cjs\react-dom-server.node.development.js:4296:27)
    at render (D:\Documents\with-redux-app\node_modules\next\dist\next-server\server\render.js:81:16)
    at renderPage (D:\Documents\with-redux-app\node_modules\next\dist\next-server\server\render.js:283:20)
    at D:\documents\with-redux-app\.next\server\static\development\pages\_document.js:3582:17
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (D:\documents\with-redux-app\.next\server\static\development\pages\_document.js:206:24)
    at _next (D:\documents\with-redux-app\.next\server\static\development\pages\_document.js:228:9)
    at D:\documents\with-redux-app\.next\server\static\development\pages\_document.js:235:7

```
## To Reproduce

Download the with-redux example and run.

Using npm version 6.4, node version 10.14 and on windows 10, on firefox

## Expected behavior
No error messages.

Windows 10.
NPM 6.4
NODE 10.14
Firefox.
NextJS: latest
.

**Comment by masives** [comment]
I just downloaded this example and ran it on firefox, didn't see this error. Tested on firefox and chrome. Did install with yarn though.

**Comment by alex067** [comment]
I ran the example again and it is working fine now, but whenever I try and implement it in my own project, I get the hooks error.

The repo: https://github.com/kirill-konshin/next-redux-wrapper

The last line from the error states:  at \nextjs-redux-wrapper\.next\server\static\development\pages\_document.js:235:7

**Comment by ijjk** [comment]
Per the above comments it looks like this isn't a bug with the example so I'm going to close this. If you have general questions that aren't bugs with Next.js itself they're better being posted in our [Spectrum Thread](https://spectrum.chat/next-js)

**Comment by balazsorban44** [comment]
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
