### ISSUE TITLE
License Comments in Styled-JSX Cause Errors with AMP Pages

### ISSUE THREAD

**Issue by adonig** [zeit/next.js#8932]
# Bug report

## Describe the bug

License comments in styled-jsx (i.e. `/*! License must not be removed! */`) cause an error with AMP pages.

> { Error: undefined:1:1: selector missing
>     at error (/Users/asd/Projects/next-amp/node_modules/css/lib/parse/index.js:62:15)
>     at rule (/Users/asd/Projects/next-amp/node_modules/css/lib/parse/index.js:555:22)
>     at rules (/Users/asd/Projects/next-amp/node_modules/css/lib/parse/index.js:118:70)
>     at stylesheet (/Users/asd/Projects/next-amp/node_modules/css/lib/parse/index.js:81:21)
>     at Object.module.exports [as parse] (/Users/asd/Projects/next-amp/node_modules/css/lib/parse/index.js:565:20)
>     at SeparateKeyframes.transform (/Users/asd/Projects/next-amp/node_modules/@ampproject/toolbox-optimizer/lib/transformers/SeparateKeyframes.js:71:25)
>     at sequence (/Users/asd/Projects/next-amp/node_modules/@ampproject/toolbox-optimizer/lib/DomTransformer.js:112:26)
>     at process._tickCallback (internal/process/next_tick.js:68:7)
>   reason: 'selector missing',
>   filename: undefined,
>   line: 1,
>   column: 1,
>   source:
>    '{/*! normalize.css v8.0.1 | MIT License | github.com/necolas/normalize.css */}html{line-height:1.15;-webkit-text-size-adjust:100%;}body{margin:0;}main{display:block;}h1{font-size:2em;margin:0.67em 0;}hr{box-sizing:content-box;height:0;overflow:visible;}pre{font-family:monospace,monospace;font-size:1em;}a{background-color:transparent;}abbr[title]{border-bottom:none;-webkit-text-decoration:underline;text-decoration:underline;-webkit-text-decoration:underline dotted;text-decoration:underline dotted;}b,strong{font-weight:bolder;}code,kbd,samp{font-family:monospace,monospace;font-size:1em;}small{font-size:80%;}sub,sup{font-size:75%;line-height:0;position:relative;vertical-align:baseline;}sub{bottom:-0.25em;}sup{top:-0.5em;}img{border-style:none;}button,input,optgroup,select,textarea{font-family:inherit;font-size:100%;line-height:1.15;margin:0;}button,input{overflow:visible;}button,select{text-transform:none;}button,[type="button"],[type="reset"],[type="submit"]{-webkit-appearance:button;}button::-moz-focus-inner,[type="button"]::-moz-focus-inner,[type="reset"]::-moz-focus-inner,[type="submit"]::-moz-focus-inner{border-style:none;padding:0;}button:-moz-focusring,[type="button"]:-moz-focusring,[type="reset"]:-moz-focusring,[type="submit"]:-moz-focusring{outline:1px dotted ButtonText;}fieldset{padding:0.35em 0.75em 0.625em;}legend{box-sizing:border-box;color:inherit;display:table;max-width:100%;padding:0;white-space:normal;}progress{vertical-align:baseline;}textarea{overflow:auto;}[type="checkbox"],[type="radio"]{box-sizing:border-box;padding:0;}[type="number"]::-webkit-inner-spin-button,[type="number"]::-webkit-outer-spin-button{height:auto;}[type="search"]{-webkit-appearance:textfield;outline-offset:-2px;}[type="search"]::-webkit-search-decoration{-webkit-appearance:none;}::-webkit-file-upload-button{-webkit-appearance:button;font:inherit;}details{display:block;}summary{display:list-item;}template{display:none;}[hidden]{display:none;}\n\n' }

Note in source there is a block without a selector around the comment. The block got added by a component of the toolchain (i.e. styled-jsx, amp-toolbox, ...).

## To Reproduce

1. Create a next.js project having an AMP-only pages/index.js and global style setup like here: https://nextjs.org/blog/styling-next-with-styled-jsx
2. Copy normalize.css (or some other css having a license comment) to styles/global.js
3. Watch it crash.

## Expected behavior

The license comment should be rendered within the `amp-custom` style.

## Screenshots

Available upon request. The error output above should be sufficient.

## System information

- OS: macOS
- Browser: Chrome
- Version of Next.js: 9.0.7

## Additional context

This might be a zeit/styled-jsx or an ampproject/amp-toolbox issue.

**Comment by timneutkens** [comment]
Pretty sure this is an amp-optimizer issue, cc @sebastianbenz

**Comment by sebastianbenz** [comment]
Yes. It's been fixed [here](https://github.com/ampproject/amp-toolbox/pull/467). The latest beta `1.1.0-beta.1` includes the fix. Will make a proper release next week.

**Comment by SHREUTH** [comment]
The block got added by a component of the toolchain,,

**Comment by balazsorban44** [comment]
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
