### ISSUE TITLE
TypeError: renderPage is not a function

### ISSUE THREAD

**Issue by napestershine** [zeit/next.js#9052]
I am trying to run `yarn export` but I am getting below error:

```sh
$ yarn export
yarn run v1.19.1
$ next export
> using build directory: /home/rs/next/next-portfolio/.next
  copying "static" directory
  copying "static build" directory
> No "exportPathMap" found in "next.config.js". Generating map from "./pages"
  launching 3 workers
[    ] Exporting (0/8)
Error occurred prerendering /_documet: TypeError: renderPage is not a function
    at /home/rs/next/next-portfolio/.next/server/static/9UZJyMe0CLlRA6QtoEwO7/pages/_document.js:394:17
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/home/rs/next/next-portfolio/.next/server/static/9UZJyMe0CLlRA6QtoEwO7/pages/_document.js:103:24)
    at _next (/home/rs/next/next-portfolio/.next/server/static/9UZJyMe0CLlRA6QtoEwO7/pages/_document.js:125:9)
    at /home/rs/next/next-portfolio/.next/server/static/9UZJyMe0CLlRA6QtoEwO7/pages/_document.js:132:7
    at new Promise (<anonymous>)
    at new F (/home/rs/next/next-portfolio/node_modules/core-js/library/modules/_export.js:36:28)
    at /home/rs/next/next-portfolio/.next/server/static/9UZJyMe0CLlRA6QtoEwO7/pages/_document.js:121:12
    at Function.getInitialProps (/home/rs/next/next-portfolio/.next/server/static/9UZJyMe0CLlRA6QtoEwO7/pages/_document.js:402:7)
    at loadGetInitialProps (/home/rs/next/next-portfolio/.next/server/static/9UZJyMe0CLlRA6QtoEwO7/pages/_document.js:1035:33)
Exporting (8/8)
Error: Export encountered errors
    at _default (/home/rs/next/next-portfolio/node_modules/next/dist/export/index.js:15:734)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

How can I fix this error?

Code: https://github.com/napestershine/next-portfolio/blob/master/pages/_documet.js

**Comment by timneutkens** [comment]
You have a typo in the filename `_documet.js` -> `_document.js`

**Comment by napestershine** [comment]
Thanks

**Comment by haf** [comment]
What about

```

[0] [1] [0] Error occurred prerendering page "/_errors/404" https://err.sh/zeit/next.js/prerender-error: TypeError: ctx.renderPage is not a function
[0] [1] [0]     at Function.getInitialProps (/Users/h/dev/afa/fou/src/Services/fou-web/.next/server/static/HG-xSNCMO-_aovqJNE9wl/pages/_document.js:295:19)
[0] [1] [0]     at Function.getInitialProps (/Users/h/dev/afa/fou/src/Services/fou-web/.next/server/static/HG-xSNCMO-_aovqJNE9wl/pages/_document.js:852:85)
[0] [1] [0]     at loadGetInitialProps (/Users/h/dev/afa/fou/src/Services/fou-web/node_modules/next/dist/next-server/lib/utils.js:59:29)
[0] [1] [0]     at Object.loadGetInitialProps (/Users/h/dev/afa/fou/src/Services/fou-web/node_modules/next/dist/next-server/lib/utils.js:54:34)
[0] [1] [0]     at renderToHTML (/Users/h/dev/afa/fou/src/Services/fou-web/node_modules/next/dist/next-server/server/render.js:237:31)
```

When there's no `_errors` folder in the solution?

**Comment by balazsorban44** [comment]
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
