### ISSUE TITLE
Unable to import TypeScript file from above project root when JavaScript file works correctly.

### ISSUE THREAD

**Issue by thessem** [zeit/next.js#9146]
# Bug report

## Describe the bug

I am attempting to import a Typescript file from above the project root folder. I get the following error

```
Module not found: Can't resolve '../../test' in '<snip>/example/app/pages'
ModuleNotFoundError: Module not found: Error: Can't resolve '../../test' in '<snip>/example/app/pages'
    at <snip>/example/app/node_modules/webpack/lib/Compilation.js:888:10
    at <snip>/example/app/node_modules/webpack/lib/NormalModuleFactory.js:401:22
    at <snip>/example/app/node_modules/webpack/lib/NormalModuleFactory.js:130:21
    at <snip>/example/app/node_modules/webpack/lib/NormalModuleFactory.js:224:22
    at <snip>/example/app/node_modules/neo-async/async.js:2830:7
    at <snip>/example/app/node_modules/neo-async/async.js:6877:13
    at <snip>/example/app/node_modules/webpack/lib/NormalModuleFactory.js:214:25
    at <snip>/example/app/node_modules/enhanced-resolve/lib/Resolver.js:213:14
    at <snip>/example/app/node_modules/enhanced-resolve/lib/Resolver.js:285:5
    at eval (eval at create (<snip>/example/app/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
    at <snip>/example/app/node_modules/enhanced-resolve/lib/UnsafeCachePlugin.js:44:7
    at <snip>/example/app/node_modules/enhanced-resolve/lib/Resolver.js:285:5
    at eval (eval at create (<snip>/example/app/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
    at <snip>/example/app/node_modules/enhanced-resolve/lib/Resolver.js:285:5
    at eval (eval at create (<snip>/example/app/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:27:1)
    at <snip>/example/app/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:67:43
```

## To Reproduce

1. `mkdir example`
2. `npx create-next-app`. Call the app `app`. This creates a directory app, and creates a Next.js app with the following `package.json`
```
{
  "name": "app",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start"
  },
  "dependencies": {
    "next": "9.1.1",
    "react": "16.10.2",
    "react-dom": "16.10.2"
  }
}
```
3. Create file called `example/test.ts`, inside put `export const foo = { bar: 'baz' };`
4. You should have the directory structure:
```
example
├── app
│   ├── components
│   │   └── nav.js
│   ├── package.json
│   ├── pages
│   │   └── index.js
│   ├── public
│   │   └── favicon.ico
│   └── yarn.lock
└── test.ts
```
5. Edit `example/app/pages/index.js` to include `import { foo } from '../../test';` and then reference `{foo.bar}` in the component somewhere.
6. Run `yarn dev` and navigate to `http://localhost:3000/`

## Expected behavior

I expect the page to render properly. Changing the extension of `example/test.ts` to `example/test.js` causes the page to render correctly with no errors. This is what I would expect

## System information

- OS: macOS v10.14.2
- Browser: Firefox 69.0.3
- Version of Next.js: 9.1.1

**Comment by thessem** [comment]
Renaming `index.js` to `index.tsx` causes a `tsconfig.json` to be created, and this works correctly. I have minimized my replication example too far obviously. Closing.

**Comment by balazsorban44** [comment]
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
