### ISSUE TITLE
Serverless builds + CDN support don't appear to mix

### ISSUE THREAD

**Issue by armenr** [zeit/next.js#9233]
# Bug report

## Describe the bug

When passing `target: serverless`, it appears as though `assetPrefix` breaks the serverless target it.

## To Reproduce

To reproduce, this NextConfig file should be used:

```
const nextBuildId = require('next-build-id');
const composeWithPlugins = require('next-compose-plugins');
const withSourceMaps = require('@zeit/next-source-maps')({ devtool: 'hidden-source-map' });

const cloudFront = 'https://REDACTED.cloudfront.net';
const isCloud = process.env.TARGET === 'aws';

if (isCloud) console.log({ Msg: 'Static assets are serving from CDN' });

const nextConfig = {
  target: 'serverless',
  assetPrefix: isCloud ? cloudFront : '',
  generateBuildId: () => nextBuildId({ dir: __dirname, describe: true }),
};

module.exports = composeWithPlugins(
  [
    withSourceMaps({
      webpack(config) {
        return config;
      },
    }),
  ],
  nextConfig,
);
```

This error gets thrown on the ec2 side:
```
3|myProj-NEXT-WEB  | 2019-10-29T09:53:19: { Msg: 'Static assets are serving from CDN' }
3|myProj-NEXT-WEB  | 2019-10-29T09:53:19: { Msg: 'Static assets are serving from CDN' }
3|myProj-NEXT-WEB  | 2019-10-29T09:53:20: Error: Cannot find module '/opt/myProj/builds/myProj-renderer-universal/.next/server/pages-manifest.json'
3|myProj-NEXT-WEB  | 2019-10-29T09:53:20: Require stack:
3|myProj-NEXT-WEB  | 2019-10-29T09:53:20: - /opt/myProj/builds/myProj-renderer-universal/index.js
3|myProj-NEXT-WEB  | 2019-10-29T09:53:20:     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:794:15)
3|myProj-NEXT-WEB  | 2019-10-29T09:53:20:     at Module.Hook._require.Module.require (/usr/local/lib/npm/lib/node_modules/pm2/node_modules/require-in-the-middle/index.js:51:29)
3|myProj-NEXT-WEB  | 2019-10-29T09:53:20:     at require (internal/modules/cjs/helpers.js:74:18)
3|myProj-NEXT-WEB  | 2019-10-29T09:53:20:     at Server.getDynamicRoutes (/opt/myProj/builds/Users/armenr/Desktop/myProj-new/myProj-tessitura/deploy_applications/src/node_modules/next/dist/next-server/server/next-server.js:271:26)
3|myProj-NEXT-WEB  | 2019-10-29T09:53:20:     at Server.generateRoutes (/opt/myProj/builds/myProj-renderer-universal/index.js:371200:39)
3|myProj-NEXT-WEB  | 2019-10-29T09:53:20:     at new Server (/opt/myProj/builds/myProj-renderer-universal/index.js:371085:29)
3|myProj-NEXT-WEB  | 2019-10-29T09:53:20:     at createServer (/opt/myProj/builds/Users/armenr/Desktop/myProj-new/myProj-tessitura/deploy_applications/src/node_modules/next/dist/server/next.js:2:126)
3|myProj-NEXT-WEB  | 2019-10-29T09:53:20:     at Object.<anonymous> (/opt/myProj/builds/server.js:109:1)
3|myProj-NEXT-WEB  | 2019-10-29T09:53:20:     at __webpack_require__ (/webpack/bootstrap:19:1)
3|myProj-NEXT-WEB  | 2019-10-29T09:53:20:     at Object.<anonymous> (/opt/myProj/builds/myProj-renderer-universal/index.js:253977:1) {
3|myProj-NEXT-WEB  | 2019-10-29T09:53:20:   code: 'MODULE_NOT_FOUND',
3|myProj-NEXT-WEB  | 2019-10-29T09:53:20:   requireStack: [ '/opt/myProj/builds/myProj-renderer-universal/index.js' ]
3|myProj-NEXT-WEB  | 2019-10-29T09:53:20: }
PM2              | App [myProj-NEXT-WEB:3] exited with code [0] via signal [SIGINT]
PM2              | App [myProj-NEXT-WEB:3] starting in -fork mode-
PM2              | App [myProj-NEXT-WEB:3] online
```

## Expected behavior
I was hoping to deploy serverless builds where static content can be served via CDN.

## Additional context

We use a custom server.js file.
We first build the serverless targetted NextJS app.
Then we build the server file with NCC and create a zero dependency package which includes the serverless nextJS app + the ncc-compiled server file, and ship them to our ec2 hosts.

Without `assetPrefix`, this strategy works without any issue.
When introducing the `assetPrefix` option, NextJS appears to look for the standard `server` directory for the build...which we do not have, since we're building serverless :)

**Comment by timneutkens** [comment]
It sounds like you probably want to use https://zeit.co to deploy your Next.js app based on the issues you've posted before and this issue.

**Comment by armenr** [comment]
@timneutkens - Thanks for the speedy reply!

I've got everything working as desired without needing to utilize zeit (although we do love zeit).

Am I to understand that we can't use `assetPrefix` with serverless targets -- as in this is expected/by design?

Or is this a bug, but the suggested remedy for now is to use zeit?

**Comment by timneutkens** [comment]
I'm saying it's unlikely this is an issue with `assetPrefix` and that based on the issues you've been having so far it probably would have probably made more sense to use ZEIT Now

**Comment by armenr** [comment]
Got it. Unfortunately, there are aspects of the pricing and the way networking is set up with ZEIT Now which precludes us from adopting it at our current stage.

Is there any help I can get for this issue, or a better way to investigate?

We build with serverless target.

This is our Next config.

```
const nextBuildId = require('next-build-id');

const isCloud = process.env.TARGET === 'aws';
const cloudFront = 'https://REDACTED.cloudfront.net';

if (isCloud) console.log({ Msg: 'Static assets are serving from CDN' });

module.exports = {
  target: 'serverless',
  assetPrefix: isCloud ? cloudFront : '',
  generateBuildId: () => nextBuildId({ dir: __dirname, describe: true }),
};

```

We do `next build` with this config.

We then ncc build this file, and output to our our `dist` folder:

```
const path = require('path');
require('dotenv').config({ path: path.join(__dirname, '.env') });
require('./server.js');
```

We grab the build from `.next` and copy it into `dist`
We even copy the next.config.js file into `dist` (just to be sure)

We then upload the `./next/static` directory to our CDN.

We deploy our `dist` folder to our servers, and start the app with:
`"start": "NODE_ENV=production TARGET=aws node ./dist/index.js"`

The app correctly logs this, when we run it:

```
3|MYAPP-NEX | 2019-10-29T13:05:51: { Msg: 'Static assets are serving from CDN' }
3|MYAPP-NEX | 2019-10-29T13:05:51: {
3|MYAPP-NEX | 2019-10-29T13:05:51:   Server: 'MYAPP-NEXT-WEB',
3|MYAPP-NEX | 2019-10-29T13:05:51:   Message: 'Server Online! 🤘🏼🎧',
3|MYAPP-NEX | 2019-10-29T13:05:51:   Mode: 'production',
3|MYAPP-NEX | 2019-10-29T13:05:51:   Address: 'http://0.0.0.0:3000',
3|MYAPP-NEX | 2019-10-29T13:05:51:   Sessions: 'dev-redis.MYAPP.me:6379',
3|MYAPP-NEX | 2019-10-29T13:05:51:   DeploymentContext: 'aws'
3|MYAPP-NEX | 2019-10-29T13:05:51: }
3|MYAPP-NEX | 2019-10-29T13:05:51: { RedisConnected: true }
```

We can verify that our CDN and the location where we upload our static folder work because we were using `assetPrefix` prior to using `target: serverless` and everything worked perfectly.

We've made no changes there.

Any thoughts/help would be appreciated, again.

Thank you!

**Comment by balazsorban44** [comment]
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
