### ISSUE TITLE
Unable to start Next 9.1.2 

### ISSUE THREAD

**Issue by aliogaili** [zeit/next.js#9269]
Starting a new project with NextJS 9.1.2 results in the following error:

```
SyntaxError: Invalid regular expression: /(?<!node_modules.*)[\\/]node_modules[\\/](react|react-dom|scheduler|prop-types|use-subscription)[\\/]/: Invalid group
    at getBaseWebpackConfig (/test_project/node_modules/next/dist/build/webpack-config.js:15:205)
    at HotReloader.getWebpackConfig (/test_project/node_modules/next/dist/server/hot-reloader.js:14:1337)
    at <anonymous>
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! test_project@1.0.0 dev: `next`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the test_project@1.0.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/x/.npm/_logs/2019-10-31T14_21_09_130Z-debug.log
```

Reverting back to 9.1.1 solves the issue.

**Comment by Timer** [comment]
What's your Node version? I suspect you're not on a new enough Node 8.

**Comment by aliogaili** [comment]
Node version is v8.9.4

**Comment by Timer** [comment]
Can you please upgrade to 8.10 or newer?

**Comment by aliogaili** [comment]
Updating to 8.10 fixes the issue, thanks @Timer.

**Comment by balazsorban44** [comment]
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
