### ISSUE TITLE
Module resolution algorithm differs from CRA's

### ISSUE THREAD

**Issue by hugmanrique** [zeit/next.js#9353]
# Bug report

## Describe the bug

I'm trying to `import` a `file:` dependency from a Next.js page. The package I'm trying to import is called `@core/components` and has the following `package.json` and `dist/index.js` files (reduced to minimal repro case):

```js
// package.json
{
  "name": "@core/components",
  "version": "1.0.0",
  "main": "dist/index.js",
  "scripts": {
    "build": "NODE_ENV=production rollup -c"
  },
  "peerDependencies": {
    "react": "^16.9.0",
    "react-dom": "^16.9.0"
  },
  "devDependencies": {
    // Important: doesn't contain `react` nor `react-dom`. See (2) below
  }
}
```

```js
// dist/index.js
var React = require('react'); // -> fails

exports.Container = /* React component */;
```

My Next.js app has the following files:

```js
// package.json
{
  "name": "next-app",
  "version": "1.0.0",
  "scripts": {
    "dev": "next",
  },
  "dependencies": {
    "next": "^9.1.3",
    "react": "^16.11.0",
    "react-dom": "^16.11.0"
  },
  "devDependencies": {
    "@core/components": "file:../react-components" // points to `@core/components` root dir
  }
}
```

```js
// pages/index.js
import React from 'react'; // works
import { Container } from '@core/components'; // -> fails

// ...
```

When running `npm run dev`, I'm getting the following error:

```
Error: Cannot find module 'react'
Require stack:
- /[redacted]/React-Components/dist/index.js
- /[redacted]/Dir/Site/.next/server/static/development/pages/_app.js
- /[redacted]/Dir/Site/node_modules/next/dist/next-server/server/load-components
- /[redacted]/Dir/Site/node_modules/next/dist/next-server/server/api-utils.js
- /[redacted]/Dir/Site/node_modules/next/dist/next-server/server/next-server.js
- /[redacted]/Dir/Site/node_modules/next/dist/server/next.js
- /[redacted]/Dir/Site/node_modules/next/dist/server/lib/start-server.js
- /[redacted]/Dir/Site/node_modules/next/dist/cli/next-dev.js
- /[redacted]/Dir/Site/node_modules/next/dist/bin/next
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:623:15)
    at Function.Module._load (internal/modules/cjs/loader.js:527:27)
    at Module.require (internal/modules/cjs/loader.js:681:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.<anonymous> (/[redacted]/React-Components/dist/index.js:7:13)
    at Module._compile (internal/modules/cjs/loader.js:774:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:785:10)
    at Module.load (internal/modules/cjs/loader.js:641:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Module.require (internal/modules/cjs/loader.js:681:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.@core/components/dist/index.js (/[redacted]/Dir/Site/.next/server/
    at __webpack_require__ (/[redacted]/Dir/Site/.next/server/static/development
    at Module../components/Navbar/index.js (/[redacted]/Dir/Site/.next/server/st
    at __webpack_require__ (/[redacted]/Hocus/Marketing/.next/server/static/development
    at Module../pages/_app.js (/[redacted]/Hocus/Marketing/.next/server/static/developm
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/[redacted]/React-Components/dist/index.js',
    '/[redacted]/Dir/Site/.next/server/static/development/pages/_app.js',
    '/mnt/d/Users/Hugo/Desktop/Coding/SalsaDev/Hocus/Marketing/node_modules/next/dist/next-server/server/load-compone
    '/[redacted]/Dir/Site/node_modules/next/dist/next-server/server/api-utils.js
    '/[redacted]/Dir/Site/node_modules/next/dist/next-server/server/next-server.
    '/[redacted]/Dir/Site/node_modules/next/dist/server/next.js',
    '/[redacted]/Dir/Site/node_modules/next/dist/server/lib/start-server.js',
    '/[redacted]/Dir/Site/node_modules/next/dist/cli/next-dev.js',
    '/[redacted]/Dir/Site/node_modules/next/dist/bin/next'
  ]
}
```

To clarify, `@core/components` is stored in `/[redacted]/React-Components`, and the Next.js app is in `/[redacted]/Dir/Site`.

I have a CRA project that also imports `@core/components` using the same file import (`file:../React-Components`). (2) I recently had to remove `react` and `react-dom` from the `devDependencies` of `@core/components` because CRA was importing two different React modules causing the infamous [Invalid Hook Call warning](https://reactjs.org/warnings/invalid-hook-call-warning.html). As noted, package libraries (as `@core/components`) should only list react in their `peerDependencies` and let the app packages (either CRA, Next, whatever else-based) install their prefered version by adding them to their `dependencies`.

The CRA app can now import `@core/components` with no warnings, meaning the `react` require inside `dist/index.js` resolved to the CRA installed version on `/[redacted]/Dir/CRASite/node_modules`.

However, Next.js is attempting to load `react` for `@core/components` from `/[redacted]/React-Components/node_modules`, which fails because I intentionally didn't install `react` in `@core/components`.

Here's everything I've tried so far:

- Add a `react` webpack resolve alias pointing to `/[redacted]/Dir/CRASite/node_modules/react` (via `next.config.js`), got same error.
- Add the [`PnpWebpackPlugin`](https://github.com/arcanis/pnp-webpack-plugin), got same error. I thought this would fix it since it's the only different thing I can see between CRA's [webpack resolve config](https://github.com/facebook/create-react-app/blob/master/packages/react-scripts/config/webpack.config.js#L293) and Next.js'. Note I'm using npm, not yarn.
- Disable webpack [symlink resolution](https://webpack.js.org/configuration/resolve/#resolvesymlinks) (via `next.config.js`), got same error.

I'm using `file:` deps (via `npm link`) for easier development (manually installing and updating `@core/components` in every app is not an option). I'm open to other options that still let me keep a different git repo for each app (no lerna/similar tools).

I believe keeping Next.js' webpack resolve algorithm the same as CRA's would yield a better developer experience and would make life easier for those migrating from CRA to Next.

## To Reproduce

1. Run `next dev` on `/[redacted]/Dir/Site/`

## Expected behavior

Next resolves `react` on `@core/components/dist/index.js` correctly (i.e. resolves to `/[redacted]/Dir/Site/node_modules/react`). This should work as a fallback to maintain node resolution (and avoid breaking other Next apps).

## System information

- OS: Windows 10 (Ubuntu WSL)
- Browser: doesn't apply
- Next.js: `9.1.3` (webpack `4.39.0`)
- npm: `6.9.0`
- Node: `12.4.0`

**Comment by jeremy-coleman** [comment]
Tsconfig paths webpack plugin or babel plugin module resolver will help you

**Comment by timneutkens** [comment]
This is related to #706 as Next.js won't touch node_modules. So it's following the standard Node.js resolve algorithm, nothing special there. Let's track it in #706 still.

**Comment by hugmanrique** [comment]
This doesn't have much in common with #706, my lib is already transpiled. I will try Jeremy's suggestion.

**Comment by timneutkens** [comment]
@hugmanrique 

> as Next.js won't touch node_modules. So it's following the standard Node.js resolve algorithm, nothing special there

This probably causes React to be resolved from the react-components dir.

**Comment by hugmanrique** [comment]
Ah, I see. The solution would then be to pass the React-Components lib through babel via that new `transpileModules` option.

Thanks! 😀

**Comment by timneutkens** [comment]
Exactly! 🚀

**Comment by balazsorban44** [comment]
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
