### ISSUE TITLE
please add es6 imports / express / modular absolute import boilerplate example

### ISSUE THREAD

**Issue by bionicles** [zeit/next.js#9487]
# Feature request

## Is your feature request related to a problem? Please describe.
have struggled to get simple es6 modular imports with absolute paths ... just a terrible problem because it seems like such a basic thing which should just work, ex 

## Describe the solution you'd like

I just want to make docker-compose run a docker containerized Next, Express, Apollo-Server, Google signin, redis backend, where line 1 of my server.js actually works: 
`import { resolvers } from "graphql" ` 

where graphql is a directory at src/graphql

## Describe alternatives you've considered

going back to react, throwing my monitor, tried babelrc, babel.config.js, jsconfig.json, nothing works

## Additional context

```
server_1  | yarn run v1.19.1
server_1  | $ ls -la && node --experimental-modules --es-module-specifier-resolution=node src/server.mjs
server_1  | total 328
server_1  | drwxrwxr-x    5 node     node          4096 Nov 21 20:15 .
server_1  | drwxr-xr-x    1 root     root          4096 Nov 21 20:17 ..
server_1  | -rw-rw-r--    1 node     node           303 Nov 21 20:14 .babelrc
server_1  | -rw-rw-r--    1 node     node            32 Nov 21 16:14 .dockerignore
server_1  | -rw-rw-r--    1 node     node           277 Nov 21 16:52 .gitignore
server_1  | drwxr-xr-x    3 root     root          4096 Nov 21 19:30 .next
server_1  | -rw-rw-r--    1 node     node           119 Nov 21 19:52 Dockerfile
server_1  | -rw-rw-r--    1 node     node           357 Nov 21 19:08 Dockerfile.multistage
server_1  | -rw-rw-r--    1 node     node          1723 Nov 21 16:14 README.md
server_1  | -rw-rw-r--    1 node     node            91 Nov 21 20:15 babel.config.js
server_1  | -rw-rw-r--    1 node     node            74 Nov 21 20:09 jsconfig.json
server_1  | -rw-rw-r--    1 node     node           577 Nov 21 20:07 next.config.js
server_1  | drwxr-xr-x  523 root     root         20480 Nov 21 18:54 node_modules
server_1  | -rw-rw-r--    1 node     node           548 Nov 21 20:17 package.json
server_1  | drwxrwxr-x    4 node     node          4096 Nov 21 19:53 src
server_1  | -rw-rw-r--    1 node     node        257405 Nov 21 20:17 yarn.lock
server_1  | (node:27) ExperimentalWarning: The ESM module loader is experimental.
server_1  | internal/modules/esm/default_resolve.js:84
server_1  |   let url = moduleWrapResolve(specifier, parentURL);
server_1  |             ^
server_1  | 
server_1  | Error: Cannot find package 'graphql' imported from /app/src/server.mjs
server_1  |     at Loader.resolve [as _resolve] (internal/modules/esm/default_resolve.js:84:13)
server_1  |     at Loader.resolve (internal/modules/esm/loader.js:74:33)
server_1  |     at Loader.getModuleJob (internal/modules/esm/loader.js:148:40)
server_1  |     at ModuleWrap.<anonymous> (internal/modules/esm/module_job.js:41:40)
server_1  |     at link (internal/modules/esm/module_job.js:40:36) {
server_1  |   code: 'ERR_MODULE_NOT_FOUND'
```

**Comment by timneutkens** [comment]
Looks like this is unrelated to Next.js, you're creating a custom server outside of Next.js that you're trying to use imports in. We recommend that you use [API routes](https://nextjs.org/docs#api-routes) instead.

**Comment by bionicles** [comment]
@timneutkens ok, but i don't see how a custom server equates to zero issue, 

do you think it's fair to make Next.js customers re-invent this stuff over and over? 

there are so many examples, this seems like a pretty common one, somebody wants to make a graphql server side rendering with the most common server (express) most common graphql (apollo) and "modern" es6 syntax, without relative imports, shrug 

anyway, I added `"start": "babel-watch src/server.js",` and everything works and still get ~100 lighthouse score with plain create-react-app. thanks for taking the time to read this, but I do think it's an easy example to add once you figure it out, and would potentially stop people from deleting their "create-next-app" as i did

jsconfig.json: 
```
{
  "compilerOptions": {
    "baseUrl": "src"
  },
  "include": ["src"]
}
```

```
{
  "presets": ["@babel/preset-env"],
  "plugins": [
    ["@babel/plugin-transform-runtime"],
    [
      "module-resolver",
      {
        "extensions": [".mjs", ".js", ".jsx"],
        "root": ["./src"],
        "alias": {
          "root": ".",
          "src": "/src"
        }
      }
    ]
  ]
}
```

babel.config.js
```
module.exports = {
  presets: [["@babel/preset-env", { targets: { node: "current" } }]]
};
```

**Comment by balazsorban44** [comment]
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
