### ISSUE TITLE
[Windows] npm scripts failing

### ISSUE THREAD

**Issue by aurelienbobenrieth** [zeit/next.js#9521]
# Bug report

## Describe the bug

It seems I can not use Next.js ^9.1.0 no matter what I try (manual setup or the npx command line) I am not able to either npm run dev/build/start. 

It fails with this error : 
```
internal/modules/cjs/loader.js:797
    throw err;
    ^

Error: Cannot find module 'C:\Users\aurel\Documents\next\dist\bin\next'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:794:15)
    at Function.Module._load (internal/modules/cjs/loader.js:687:27)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1025:10)
    at internal/main/run_main_module.js:17:11 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
```

The weird thing is that the "cannot find module" path is not my project path at all, it is something like the second or third parent and I cannot seem to understand why my npm scripts is trying to look for next in that directory.

Also everything is working great so far with Next 8 but I do not know why I am not able to use the latest version, any requirements I am missing ?

## To Reproduce

Try the npx command line provided in the git repo.

## Expected behavior

`npm run dev` should not crash and launch my hello world app.

## System information

- OS: W10
- Version of Next.js: ^9.1.0
- Version of node : 12.13.0
- Version of npm : 6.12.0

**Comment by Timer** [comment]
You might have `next` installed globally -- please uninstall that then see if it works in your project.

**Comment by aurelienbobenrieth** [comment]
Thank your for your reply. 

Though of that too, I even removed the whole npm and npm-cache folder in my appdata/roaming without any success.

**Comment by Timer** [comment]
Try running both of these commands in your command prompt, followed by trying the `npm run dev` command again:
```powershell
  reg delete "HKCU\Software\Microsoft\Command Processor" /v AutoRun /f

  reg delete "HKLM\Software\Microsoft\Command Processor" /v AutoRun /f
```

Be sure to copy the command from **start to end**, not omitting the `AutoRun` part.

**Comment by Timer** [comment]
You may need to run it in an **administrator** command prompt shell.

**Comment by aurelienbobenrieth** [comment]
Both commande lines returned : 
`ERROR: The system was unable to find the specified registry key or value.`

**Comment by Timer** [comment]
Interesting -- you haven't tried to adjust the default folder your command prompt opens to, have you?

Can you please provide me a few more reproduction steps?

Does the `npx create-next-app test-app` command complete successfully for you?
If you run `cd test-app` followed by `npm run dev`, can you please paste the exact error you see?

**Comment by aurelienbobenrieth** [comment]
Thank you for your help though, I really appreciate. 

When executed with administrator rights, my cmd opens in `C:\XINDOWS\system32`
The command complete successfully. 

The exact error is :
```
internal/modules/cjs/loader.js:957
    throw err;
    ^

Error: Cannot find module 'C:\Users\aurel\Documents\next\dist\bin\next'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:954:17)
    at Function.Module._load (internal/modules/cjs/loader.js:847:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:67:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! test-app@0.1.0 dev: `next dev`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the test-app@0.1.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\aurel\AppData\Roaming\npm-cache\_logs\2019-11-25T21_37_45_452Z-debug.log
```

**Really interesting thing** : 
If i install everything outside of my `C:\Users\aurel\Documents` directory, let's say `C:\Users\aurel\Desktop` everything works fine and I can access localhost as it is expected. 🤔 

Any idea what could possibly cause trouble ?

**Comment by Timer** [comment]
I'm not really sure what the problem is here. 😞 

Normally issues like these are solved with the above to regex commands, but I'm at a loss on how to debug further.

**Comment by aurelienbobenrieth** [comment]
At least now that I know that I can make it work if I init it somewhere else I am not completly stuck so I guess it is not an urgent issue.
However I am really keen to learn where the trouble comes from. 

I'll make sure to post it here if I manage to sort it out !

**Comment by aurelienbobenrieth** [comment]
GOTCHA ! 🎉
Ladies and gentleman the trouble comes from a kinda stupid thing (which seems pretty logic actually but that occured for the first time to me). 

At the root level of my `/Documents` directory I have a folder called `00 - Personnal & Pro files`... 
**SPOILER ALERT** : The `&` is totally breaking the path resolution and removing it from my folder name resolved the issue.

It seems like when the path encounters an `&` it stops going further and tries to fetch `/node_modules `from there.

I am not sure if it is related to you or some other external packages and if you can implement some fixes. For the moment I removed the `&` as it is not mandatory at all to me. 

Still pretty weird I never had this issue with any other node project.

**Comment by balazsorban44** [comment]
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
