### ISSUE TITLE
500 Error For /api Route When Not Using API Routes System 

### ISSUE THREAD

**Issue by derekdowling** [zeit/next.js#9529]
# Bug report

## Describe the bug

Next encounters an unhandled error when handling `/api` in local and production using Next 9 Routing. We are not using the API Routes feature.

## To Reproduce

Create a Next app with a `/[foo]` page using Next 9 Routing.

1. Go to '/api'
2. Get a full unhandled 500 ISE.

## Expected behavior

`/api` is routed to `/[foo]`.

## Screenshots

<img width="407" alt="Screen Shot 2019-11-25 at 9 24 00 PM" src="https://user-images.githubusercontent.com/613964/69601738-0fbbd580-0fca-11ea-8bf0-1d8662ed0924.png">

## System information

- Version of Next.js: 9.1.4

## Additional context

```
TypeError: Cannot call a class as a function
    at _classCallCheck (<project>/.next/server/static/dev/pages/[foo].js:10781:11)
    at ChannelPage (<project>/.next/server/static/dev/pages/[foo].js:12805:46)
    at Object.apiResolver (<project>/node_modules/next/dist/next-server/server/api-utils.js:39:9)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Server.handleApiRequest (<project>/node_modules/next/dist/next-server/server/next-server.js:356:9)
    at async Object.fn (<project>/node_modules/next/dist/next-server/server/next-server.js:283:21)
    at async Router.execute (<project>/node_modules/next/dist/next-server/server/router.js:25:32)
    at async Server.run (<project>/node_modules/next/dist/next-server/server/next-server.js:406:29)
```

**Comment by Timer** [comment]
We've fixed the API route matching criteria in newer Next.js versions. Please let us know if you can still reproduce this.

**Comment by balazsorban44** [comment]
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
