### ISSUE TITLE
Next 9 Routing: Requested and resolved page mismatch

### ISSUE THREAD

**Issue by derekdowling** [zeit/next.js#9536]
# Bug report

## Describe the bug

We encountered an [error](https://github.com/zeit/next.js/blob/2ba352da39ee00b6595aecdc9ffb2f103e803a85/packages/next/next-server/server/normalize-page-path.ts#L14) that isn't especially actionable as a consumer. It would be helpful to either provide more context in the error so it's easier to understand what went wrong, or make the error explain more what we need to do to solve the problem.

It appears to have happened when trying to route `/.` with Next 9 routing in SSR, though I cannot seem to reproduce it. We have a corresponding `/index` page as well as a `/[foo]` page if that's of any help.

I'll try to collect more information if it happens again, but I thought it'd be good to know about since it is puzzling.

## Expected behavior

Not sure to be honest.

## System information

- Version of Next.js: 9.1.4

## Additional context

Log Dump

```
Handling request for /.

Error: Requested and resolved page mismatch
at Object.normalizePagePath (<project>/node_modules/next/dist/next-server/server/normalize-page-path.js:16:15)
at getPagePath (<project>/node_modules/next/dist/next-server/server/require.js:22:38)
at Object.requirePage (<project>/node_modules/next/dist/next-server/server/require.js:43:22)
at Object.loadComponents (<project>/node_modules/next/dist/next-server/server/load-components.js:24:36)
at Server.findPageComponents (<project>/node_modules/next/dist/next-server/server/next-server.js:457:40)
at Server.renderToHTML (<project>/node_modules/next/dist/next-server/server/next-server.js:553:21)
at Server.render (<project>/node_modules/next/dist/next-server/server/next-server.js:433:33)
at Object.fn (<project>/node_modules/next/dist/next-server/server/next-server.js:311:32)
at runMicrotasks (<anonymous>)
at processTicksAndRejections (internal/process/task_queues.js:93:5)
at async Router.execute (<project>/node_modules/next/dist/next-server/server/router.js:25:32)
at async Server.run (<project>/node_modules/next/dist/next-server/server/next-server.js:406:29)
```

**Comment by timneutkens** [comment]
This issue is not actionable without a reproduction.

**Comment by mengxuhui** [comment]
I hava this quesion 
Error: Requested and resolved page mismatch at Object.normalizePagePath

**Comment by mengxuhui** [comment]
how to fix

**Comment by timneutkens** [comment]
@mengxuhui As said
> This issue is not actionable without a reproduction

**Comment by mengxuhui** [comment]
Recently frequent

**Comment by timneutkens** [comment]
@mengxuhui as said in my previous message we need a full reproduction to investigate 🙏

**Comment by derekdowling** [comment]
@timneutkens I am still having issues getting the error to throw even with `NODE_ENV=production` in local development. As best I can tell this happens when people are looking for vulnerabilities:

Request paths that have caused this:
```
/foo/./WEB-INF/web.xml
/admin/./WEB-INF/web.xml
/streamerhouse/../WEB-INF/web.xml
```

**Comment by mengxuhui** [comment]
> @mengxuhui as said in my previous message we need a full reproduction to investigate 🙏

Error: Requested and resolved page mismatch at Object.normalizePagePath (/search/odin/ocm/nodeapp/sgkf-portal/run/node_modules/next-server/dist/server/normalize-page-path.js:16:15) at getPagePath (/search/odin/ocm/nodeapp/sgkf-portal/run/node_modules/next-server/dist/server/require.js:16:38) at Object.requirePage (/search/odin/ocm/nodeapp/sgkf-portal/run/node_modules/next-server/dist/server/require.js:30:22) at Object.loadComponents (/search/odin/ocm/nodeapp/sgkf-portal/run/node_modules/next-server/dist/server/load-components.js:15:34) at Server.renderToHTMLWithComponents (/search/odin/ocm/nodeapp/sgkf-portal/run/node_modules/next-server/dist/server/next-server.js:224:48) at Server.renderToHTML (/search/odin/ocm/nodeapp/sgkf-portal/run/node_modules/next-server/dist/server/next-server.js:236:37) at Server.render (/search/odin/ocm/nodeapp/sgkf-portal/run/node_modules/next-server/dist/server/next-server.js:192:33) at Object.fn (/search/odin/ocm/nodeapp/sgkf-portal/run/node_modules/next-server/dist/server/next-server.js:150:36) at /search/odin/ocm/nodeapp/sgkf-portal/run/node_modules/next-server/dist/server/router.js:23:36 at Server.run (/search/odin/ocm/nodeapp/sgkf-portal/run/node_modules/next-server/dist/server/next-server.js:161:23)

thanks a lot

**Comment by timneutkens** [comment]
@mengxuhui that is not a reproduction. That is an error you're getting in your particular app and is not actionable for us.

@derekdowling that is expected as we block any path mismatches to ensure people don't traverse up the directory tree etc.

**Comment by derekdowling** [comment]
@timneutkens should this be an error then? Our team has a policy of alerting when our server encounters any unhandled error which causes this to be really noisy because our service is constantly being scanned for issues.

**Comment by timneutkens** [comment]
This one isn't unhandled though right? It just renders the 404 page afaik?

**Comment by mengxuhui** [comment]
I just don't know the specific reason, so I can ask for help. Errors caught by exceptions

**Comment by mengxuhui** [comment]
@timneutkens

**Comment by timneutkens** [comment]
We can't investigate without a clear and concise reproduction.

**Comment by aviaryan** [comment]
I also got this error on my production server but I have no idea why it happened. I am the only one who knows that the website exists and I don't recall visiting it at that time. Was it some kind of bot? I will report with a proper issue if I can replicate it. Until then, here's the trace.

```sh
2020-01-12T15:19:36.914133386Z app[web.1]: Error: Requested and resolved page mismatch
2020-01-12T15:19:36.914504843Z app[web.1]:     at Object.normalizePagePath (/app/node_modules/next/dist/next-server/server/normalize-page-path.js:16:15)
2020-01-12T15:19:36.924627903Z app[web.1]:     at getPagePath (/app/node_modules/next/dist/next-server/server/require.js:22:38)
2020-01-12T15:19:36.924659614Z app[web.1]:     at Object.requirePage (/app/node_modules/next/dist/next-server/server/require.js:43:22)
2020-01-12T15:19:36.924664520Z app[web.1]:     at Object.loadComponents (/app/node_modules/next/dist/next-server/server/load-components.js:25:36)
2020-01-12T15:19:36.924668209Z app[web.1]:     at Server.findPageComponents (/app/node_modules/next/dist/next-server/server/next-server.js:508:40)
2020-01-12T15:19:36.924671607Z app[web.1]:     at Server.renderToHTML (/app/node_modules/next/dist/next-server/server/next-server.js:602:21)
2020-01-12T15:19:36.924675098Z app[web.1]:     at Server.render (/app/node_modules/next/dist/next-server/server/next-server.js:489:33)
2020-01-12T15:19:36.924678423Z app[web.1]:     at Object.fn (/app/node_modules/next/dist/next-server/server/next-server.js:348:28)
2020-01-12T15:19:36.924681792Z app[web.1]:     at processTicksAndRejections (internal/process/task_queues.js:97:5)
2020-01-12T15:19:36.924685053Z app[web.1]:     at async Router.execute (/app/node_modules/next/dist/next-server/server/router.js:42:32)
```

**Comment by timneutkens** [comment]
Posting a stacktrace is really not helpful. 

As said

> We can't investigate without a clear and concise reproduction.

**Comment by Kcin1993** [comment]
I run into this issue. In my situation, I use the AWS ELB to host the next app.

It seems to be the ELB is too small then causes this issue. When I change the t2 Nano → t2 Micro, the deployment is successful.

**Comment by Kcin1993** [comment]
I use AWS ELB and meet this issue also. 
After changing the ELB from Nano to Micro. This issue is solved.

**Comment by flizana** [comment]
I am having the same issue. Getting this error when trying to redirect from my / route to /en/ page. I am using a custom node.js server to redirect requests based on user location to the respective language page (/en/, /es/, etc).

    // server.js

    server.get('/', indexCtrl.redirectLang)
    server.get('*', (req, res) => { return handle(req, res) })


    // indexCtrl.redirectLang

    ...
    return res.redirect('/en/')
    ...

I have a `/[lang]/index` page. The odd thing is I am getting this error only in production, in development it works fine.

**Comment by ijjk** [comment]
Hi @flizana, the mentioned error message has been updated in the latest canary of Next.js (`9.2.2-canary.21`), specifically [this PR](https://github.com/zeit/next.js/pull/10431) which should give more clarity for what is causing it to show

**Comment by xiaohuazheng** [comment]
Error: Requested and resolved page mismatch
at Object.normalizePagePath (<project>/node_modules/next/dist/next-server/server/normalize-page-path.js:16:15)

code:
```
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const path_1 = require("path");
function normalizePagePath(page) {
    // If the page is `/` we need to append `/index`, otherwise the returned directory root will be bundles instead of pages
    if (page === '/') {
        page = '/index';
    }
    // Resolve on anything that doesn't start with `/`
    if (page[0] !== '/') {
        page = `/${page}`;
    }
    // Throw when using ../ etc in the pathname
    const resolvedPage = path_1.posix.normalize(page);
    if (page !== resolvedPage) {
        throw new Error('Requested and resolved page mismatch');
    }
    return page;
}
exports.normalizePagePath = normalizePagePath;
```

you can try check your render pagePath.

**Comment by phoenixbeats01** [comment]
I encountered this problem too. I don't knwo what caused it but restarting my next dev server fixed it

**Comment by balazsorban44** [comment]
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
