### ISSUE TITLE
Error: Requested and resolved page mismatch at Object.normalizePagePath 

### ISSUE THREAD

**Issue by mengxuhui** [zeit/next.js#9549]
Error: Requested and resolved page mismatch at Object.normalizePagePath (/search/odin/ocm/nodeapp/sgkf-portal/run/node_modules/next-server/dist/server/normalize-page-path.js:16:15) at getPagePath (/search/odin/ocm/nodeapp/sgkf-portal/run/node_modules/next-server/dist/server/require.js:16:38) at Object.requirePage (/search/odin/ocm/nodeapp/sgkf-portal/run/node_modules/next-server/dist/server/require.js:30:22) at Object.loadComponents (/search/odin/ocm/nodeapp/sgkf-portal/run/node_modules/next-server/dist/server/load-components.js:15:34) at Server.renderToHTMLWithComponents (/search/odin/ocm/nodeapp/sgkf-portal/run/node_modules/next-server/dist/server/next-server.js:224:48) at Server.renderToHTML (/search/odin/ocm/nodeapp/sgkf-portal/run/node_modules/next-server/dist/server/next-server.js:236:37) at Server.render (/search/odin/ocm/nodeapp/sgkf-portal/run/node_modules/next-server/dist/server/next-server.js:192:33) at Object.fn (/search/odin/ocm/nodeapp/sgkf-portal/run/node_modules/next-server/dist/server/next-server.js:150:36) at /search/odin/ocm/nodeapp/sgkf-portal/run/node_modules/next-server/dist/server/router.js:23:36 at Server.run (/search/odin/ocm/nodeapp/sgkf-portal/run/node_modules/next-server/dist/server/next-server.js:161:23)

**Comment by timneutkens** [comment]
Please follow the issue template and provide a clear and concise reproduction.

**Comment by ad5jo** [comment]
Error: Requested and resolved page mismatch
    at normalizePagePath (/Users/dxd8q2m/Documents/containers/node/node1/jan27next/node_modules/next/dist/next-server/server/normalize-page-path.js:16:15)
    at Object.ensurePage (/Users/dxd8q2m/Documents/containers/node/node1/jan27next/node_modules/next/dist/server/on-demand-entry-handler.js:14:417)
I just used the create-next-app(the next version is 9.2. npm run dev and opened the localhost 3000. My setup is Macbook pro 2018, Mojave 10.14.6. Using the Chrome browser. I control+c to stop then npm run dev again and it didn't happen again.

**Comment by xiaohuazheng** [comment]
> Error: Requested and resolved page mismatch
> at normalizePagePath (/Users/dxd8q2m/Documents/containers/node/node1/jan27next/node_modules/next/dist/next-server/server/normalize-page-path.js:16:15)
> at Object.ensurePage (/Users/dxd8q2m/Documents/containers/node/node1/jan27next/node_modules/next/dist/server/on-demand-entry-handler.js:14:417)
> I just used the create-next-app(the next version is 9.2. npm run dev and opened the localhost 3000. My setup is Macbook pro 2018, Mojave 10.14.6. Using the Chrome browser. I control+c to stop then npm run dev again and it didn't happen again.

set render page path like "//", it happend. Surprise.

**Comment by xiaohuazheng** [comment]
try to check your render page path and ensure it is correct.

**Comment by reza-baiat** [comment]
I had a problem. I had a variable `value = '/some/value'` and then it was splitted by '/'. so I had extra [empty string] at the begining of the array. So I have used `value.split('/').splice(1)`

**Comment by balazsorban44** [comment]
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
