### ISSUE TITLE
Deploy/Build failing on NOW 

### ISSUE THREAD

**Issue by samuelcastro** [zeit/next.js#9564]
# Bug report

## Describe the bug

I have a build process that runs ESLint + Prettier before the in my `prebuild` package.json script, locally is working just fine, however when trying to publish it on `now` I'm getting this issue:
```
Error: ENOENT: no such file or directory, open '/zeit/3c79346f/.gitignore'
error Command failed with exit code 1.
```

The problems is due this script:
`"eslint:fix": "npx eslint --fix \"./**/*.{ts,tsx,js}\" --ignore-path .gitignore"`

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Create a simple project with ESLint
2. Add a script to lint it ignoring files on .gitignore
3. `yarn build`
4. Try to deploy with `now`

## Expected behavior

Build and deploy on `now` as expected.

## Current behaviour

```
 Error! Build failed
> Error! Check your logs at https://my-project-6zv95x4mt.now.sh/_logs or run `now logs https://schooling-6zv95x4mt.now.sh`
```

## System information

- OS: macOS
- Version of Next.js: 9.1.4

## Additional context

Remote logs:

```

Installing build runtime...
--
12:04:01 PM | Build runtime installed: 527.255ms
12:04:02 PM | Looking up build cache...
12:04:02 PM | Installing dependencies...
12:04:03 PM | yarn install v1.17.3
12:04:03 PM | [1/4] Resolving packages...
12:04:03 PM | [2/4] Fetching packages...
12:04:12 PM | info fsevents@1.2.9: The platform "linux" is incompatible with this module.
12:04:12 PM | info "fsevents@1.2.9" is an optional dependency and failed compatibility check. Excluding it from installation.
12:04:12 PM | [3/4] Linking dependencies...
12:04:12 PM | warning "@apollo/react-hooks > @apollo/react-common@3.1.3" has unmet peer dependency "apollo-utilities@^1.3.2".
12:04:12 PM | warning " > next-apollo@3.1.10" has incorrect peer dependency "@apollo/react-hooks@^3.0.1".
12:04:12 PM | warning " > next-apollo@3.1.10" has incorrect peer dependency "@apollo/react-ssr@^3.0.1".
12:04:12 PM | warning " > next-apollo@3.1.10" has unmet peer dependency "apollo-boost@^0.4.4".
12:04:12 PM | warning " > @typescript-eslint/eslint-plugin@2.9.0" has unmet peer dependency "@typescript-eslint/parser@^2.0.0".
12:04:12 PM | warning "eslint-config-airbnb-typescript > eslint-config-airbnb@18.0.1" has incorrect peer dependency "eslint-plugin-react-hooks@^1.7.0".
12:04:16 PM | [4/4] Building fresh packages...
12:04:16 PM | $ yarn build
12:04:17 PM | yarn run v1.17.3
12:04:17 PM | $ yarn format && npx tsc
12:04:17 PM | $ yarn tsclint && yarn eslint:fix && yarn prettier:write
12:04:17 PM | $ npx tsc --noEmit --skipLibCheck
12:04:20 PM | $ npx eslint --fix "./**/*.{ts,tsx,js}" --ignore-path ./.gitignore
12:04:20 PM | Cannot read .eslintignore file: /zeit/3c79346f/.gitignore
12:04:20 PM | Error: ENOENT: no such file or directory, open '/zeit/3c79346f/.gitignore'
12:04:20 PM | error Command failed with exit code 1.
12:04:20 PM | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
12:04:20 PM | error Command failed with exit code 1.
12:04:20 PM | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
12:04:20 PM | error Command failed with exit code 1.
12:04:20 PM | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
12:04:20 PM | error Command failed with exit code 1.
12:04:20 PM | info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
12:04:20 PM | Error: Exited with 1
12:04:20 PM | at ChildProcess.child.on (/zeit/dab4fdc98982bbe7/.build-utils/.builder/node_modules/@now/next/dist/index.js:46827:24)
12:04:20 PM | at emitTwo (events.js:126:13)
12:04:20 PM | at ChildProcess.emit (events.js:214:7)
12:04:20 PM | at maybeClose (internal/child_process.js:925:16)
12:04:20 PM | at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
12:04:20 PM | worker exited with code 20 and signal null
12:04:23 PM | done


```

**Comment by paulogdm** [comment]
Now doesn't upload files prefixed with `.`. Therefore, we recommend that you either remove that script from your build script or use `.eslintignore`: https://eslint.org/docs/user-guide/configuring#eslintignore

**Comment by samuelcastro** [comment]
Ok thanks @paulogdm, getting another issue now though:

```
error Command failed with exit code 1.
--
04:19:03 PM | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
04:19:03 PM | error Command failed with exit code 1.
04:19:03 PM | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
04:19:03 PM | Error: Exited with 1
04:19:03 PM | at ChildProcess.child.on (/zeit/dab4fdc98982bbe7/.build-utils/.builder/node_modules/@now/next/dist/index.js:46827:24)
04:19:03 PM | at emitTwo (events.js:126:13)
04:19:03 PM | at ChildProcess.emit (events.js:214:7)
04:19:03 PM | at maybeClose (internal/child_process.js:925:16)
04:19:03 PM | at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
04:19:03 PM | worker exited with code 20 and signal null
04:19:06 PM | done
```

**Comment by samuelcastro** [comment]
Ok the issue is that my `prebuild` script uses `tsc` to validate the code linting, which shouldn't be at a build stage, closing this, it's not a bug.

**Comment by balazsorban44** [comment]
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
