### ISSUE TITLE
Circular structure in "getInitialProps" even though I remove circular part

### ISSUE THREAD

**Issue by umutozdemir97** [zeit/next.js#9566]
# Bug report

## Bug description

I try to use `RootStore` pattern with Mobx. But `RootStore` holds references to child stores, child stores hold references to `RootStore`. An object with circular dependency emerges. I understand and try to remove the circular problem. I remove references from child stores to `RootStore`. So there will be no serialization problems. 

```js
removeCircularity(mobxStore);

    console.log(JSON.stringify(mobxStore, null, 2));

    return {
      pageConfig,
      token,
      user: userData,
      apiBase: this.apiBase,
      initialMobxStore: mobxStore,
      ...appProps,
    };
```

And here's how I remove and add `RootStore` reference to object:

```js
export function removeCircularity(rootStore) {
  for (const [key, value] of Object.entries(rootStore)) {
    value.rootStore = undefined;
  }

  return rootStore;
}

export function addCircularity(rootStore) {
  if (!rootStore) {
    return undefined;
  }

  for (const [key, value] of Object.entries(rootStore)) {
    value.rootStore = rootStore;
  }

  return rootStore;
}
```

Then I add `RootStore` reference back to it in `constructor` method: 

```js
constructor(props) {
    super(props);

    setGlobalApiBase(props.apiBase);

    const isServer = typeof window === 'undefined';

    this.mobxStore = isServer
      ? addCircularity(props.initialMobxStore)
      : initializeStore(props.initialMobxStore);

    setUniversalProperty('store', this.mobxStore);
  }
```

But, even though, this `console.log(JSON.stringify(mobxStore, null, 2));` line works perfectly after I remove circularity, next.js still throws this error: 

```
Error: Circular structure in "getInitialProps" result of page "/_error". https://err.sh/zeit/next.js/circular-structure
    at Function.getInlineScriptSource (/home/umut/Desktop/kutuphanesi2/.next/server/static/development/pages/_document.js:9247:15)
    at NextScript.render (/home/umut/Desktop/kutuphanesi2/.next/server/static/development/pages/_document.js:9327:28)
    at processChild (/home/umut/Desktop/kutuphanesi2/node_modules/react-dom/cjs/react-dom-server.node.development.js:3295:18)
    at resolve (/home/umut/Desktop/kutuphanesi2/node_modules/react-dom/cjs/react-dom-server.node.development.js:3126:5)
    at ReactDOMServerRenderer.render (/home/umut/Desktop/kutuphanesi2/node_modules/react-dom/cjs/react-dom-server.node.development.js:3600:22)
    at ReactDOMServerRenderer.read (/home/umut/Desktop/kutuphanesi2/node_modules/react-dom/cjs/react-dom-server.node.development.js:3538:29)
    at Object.renderToStaticMarkup (/home/umut/Desktop/kutuphanesi2/node_modules/react-dom/cjs/react-dom-server.node.development.js:4263:27)
    at renderDocument (/home/umut/Desktop/kutuphanesi2/node_modules/next/dist/next-server/server/render.js:90:18)
    at Object.renderToHTML (/home/umut/Desktop/kutuphanesi2/node_modules/next/dist/next-server/server/render.js:332:16)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

This error is seen at backend and at frontend. 

## Expected behavior

I expect and see that the value is actually serializable before sent through result of `getInitialProps`. So no serializability problems should arise. 

- OS: [e.g. Linux]
- Node: v10.16.0
- Version of Next.js: 9.1.2

**Comment by timneutkens** [comment]
It would help to provide a full reproduction. However I doubt it's related to Next.js, we just `JSON.stringify` here: https://github.com/zeit/next.js/blob/canary/packages/next/pages/_document.tsx#L640-L651

**Comment by umutozdemir97** [comment]
I solved it this way and I have no idea what this additional `stringify` function is doing:

```js
    return {
      pageConfig,
      token,
      user: userData,
      apiBase: this.apiBase,
      initialMobxStore: JSON.stringify(stringify(mobxStore)),
      ...appProps,
    };
  }
```
Here's the `stringify` function I found on one of our old codebases, I have no idea of its origin but it works, interesting:

```js
import { toJS } from 'mobx';

/* eslint-disable no-param-reassign */
const Stringify = (obj) => Object.entries(obj).reduce((prev, [key, value]) => {
  if (value && typeof value === 'object') {
    if (Array.isArray(value)) {
      prev[key] = value;
    } else if (value.constructor && value.constructor.name === 'Store') {
      return prev;
    } else {
      prev[key] = Stringify(toJS(value));
    }
  } else {
    prev[key] = toJS(value);
  }

  return prev;
}, {});
/* eslint-enable no-param-reassign */

export default Stringify;
```

Trick is this: `JSON.stringify(stringify(mobxStore))`

**Comment by balazsorban44** [comment]
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
