### ISSUE TITLE
Please update the styled components example, the latest version crashes.

### ISSUE THREAD

**Issue by sarmad1995** [zeit/next.js#9582]
`Error: No valid exports main found`

`at Object.styled-components (/Users/sarmadshah/Desktop/with-styled-components-app/.next/server/static/development/pages/_document.js:1669:18) {
  code: 'MODULE_NOT_FOUND'`

It breaks even when we don't use styled component, only when we import it.

**Comment by JoviDeCroock** [comment]
What version of styled-components are you using?

**Comment by jamesmosier** [comment]
I pulled down the `with-styled-components` example with no issues using the latest versions of styled-components (`4.4.1`) and babel-plugin-styled-components (`1.10.6`) that were downloaded upon running `yarn create next-app --example with-styled-components with-styled-components-app`.

I'd also be interested to know which versions appear to be not working as expected.

**Comment by pkrawc** [comment]
I've recreated the error. My error is slightly different but I think still related to `styled-components`

Git Repo: https://github.com/pkrawc/nextjs-styled-components-error

Error
```bash
[ error ] Error: Package exports for '/Users/patrick/Development/avail/calculator/node_modules/merge-anything' do not define a '.' subpath
    at applyExports (internal/modules/cjs/loader.js:485:15)
    at resolveExports (internal/modules/cjs/loader.js:508:12)
    at Function.Module._findPath (internal/modules/cjs/loader.js:577:20)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:879:27)
    at Function.Module._load (internal/modules/cjs/loader.js:785:27)
    at Module.require (internal/modules/cjs/loader.js:956:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/Users/patrick/Development/avail/calculator/node_modules/styled-components/dist/styled-components.cjs.js:17:29)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1103:10)
    at Module.load (internal/modules/cjs/loader.js:914:32)
    at Function.Module._load (internal/modules/cjs/loader.js:822:14)
    at Module.require (internal/modules/cjs/loader.js:956:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.styled-components (/Users/patrick/Development/avail/calculator/.next/server/static/development/pages/_document.js:1703:18)
    at __webpack_require__ (/Users/patrick/Development/avail/calculator/.next/server/static/development/pages/_document.js:23:31) {
  code: 'MODULE_NOT_FOUND'
}
```

**Comment by pkrawc** [comment]
Running MacOS 10.15.1 if that makes a difference.

**Comment by pkrawc** [comment]
This is an issue with `merge-anything` or how next is using it.

Downgrading to `merge-anything@2.4.2` fixes the issue for me.

**Comment by jamesmosier** [comment]
I received a bit different of an error running your code sample, which lead me to changing [the return in `getInitialProps`](https://github.com/pkrawc/nextjs-styled-components-error/blob/e3fad1e6a65a76a3ef95b309d1bd993f0927a8af/pages/_document.js#L14-L20) to the following:

```js
return {
  ...initialProps,
  styles: (
    <>
      {initialProps.styles}
      {sheet.getStyleElement()}
    </>
  )
}
```

where `styles:` is not an object and instead a React element.

I took this from the [with-styled-components](https://github.com/zeit/next.js/blob/0e1f2f36a32ce7b1869238313b55dcdd4bbbf446/examples/with-styled-components/pages/_document.js#L18-L23) example.

After making this change, I was able to run your code without error.

**Comment by sarmad1995** [comment]
I am using the latest version of next and styled components, I am also getting the issue of `MODULE NOT FOUND`.

**Comment by timneutkens** [comment]
I'm wonder why you ignored the issue template.

Issue template:

https://github.com/zeit/next.js/issues/new/choose

<img width="818" alt="Screen Shot 2019-12-02 at 13 34 48" src="https://user-images.githubusercontent.com/6324199/69959946-8ac04700-1508-11ea-9424-32e50e7467b4.png">

Choose one of them:

<img width="725" alt="Screen Shot 2019-12-02 at 13 35 15" src="https://user-images.githubusercontent.com/6324199/69959981-9c095380-1508-11ea-9b31-9cc9463fe89e.png">

https://github.com/zeit/next.js/issues/new?template=3.Example_Bug_report.md

Fill out the details:

- Title
- Example name
- Describe the bug
- To reproduce
	- Provide a **full** reproduction.

---

This **tremendously** helps with being able to look into your issue and being able to actually reproduce the issue you're running into.

**Comment by GuidovdRiet** [comment]
Running into the issue.

[Styled components example](https://github.com/zeit/next.js/tree/canary/examples/with-styled-components) doesn't work with the current dependencies.

**Comment by bmamouri** [comment]
I can confirm that I have the same issue. But it only exists on Node 13. I had no problem running it on Node 11. No idea what causes it. But there is a related issue from 2016 in styled-components: https://github.com/styled-components/styled-components/issues/115

**Comment by bmamouri** [comment]
Downgrading to Node@10 solved the issue for me!

**Comment by pkrawc** [comment]
> I received a bit different of an error running your code sample, which lead me to changing [the return in `getInitialProps`](https://github.com/pkrawc/nextjs-styled-components-error/blob/e3fad1e6a65a76a3ef95b309d1bd993f0927a8af/pages/_document.js#L14-L20) to the following:
> 
> ```js
> return {
>   ...initialProps,
>   styles: (
>     <>
>       {initialProps.styles}
>       {sheet.getStyleElement()}
>     </>
>   )
> }
> ```
> 
> where `styles:` is not an object and instead a React element.
> 
> I took this from the [with-styled-components](https://github.com/zeit/next.js/blob/0e1f2f36a32ce7b1869238313b55dcdd4bbbf446/examples/with-styled-components/pages/_document.js#L18-L23) example.
> 
> After making this change, I was able to run your code without error.

You're correct, my bad. I was messing around with things. The error is still there for me on node@13. @jamesmosier

**Comment by bmamouri** [comment]
I am also receiving this warning:

```
(node:96843) Warning: require() of ES modules is not supported.
require() of /REDACTED/node_modules/merge-anything/dist/index.cjs.js from /REDACTED/node_modules/styled-components/dist/styled-components.cjs.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename index.cjs.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /REDACTED/node_modules/merge-anything/package.json.
```

**Comment by timneutkens** [comment]
Believe this was unrelated to Next.js and has been solved.

**Comment by balazsorban44** [comment]
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
