### ISSUE TITLE
'MODULE_NOT_FOUND'

### ISSUE THREAD

**Issue by jp-2513** [zeit/next.js#9624]
I have an error running app.js can anybody help me ?

var Carro = /** @class */ (function () {
    function Carro() {
        this.modelo = 
        this.NumeroDePortas = 0
        this.velocidade = 0
    }
    Carro.prototype.acelerar = function () {
        this.velocidade = this.velocidade + 10;
    };
    Carro.prototype.parar = function () {
        this.velocidade = 0;
    };
    Carro.prototype.velocidadeAtual = function () {
        return this.velocidade;
    };
    return Carro;
}());
var carroA = new Carro();
console.log(carroA);

PS C:\cursos\angular\typescript> node app.js
internal/modules/cjs/loader.js:797
    throw err;
    ^

Error: Cannot find module 'C:\cursos\angular\typescript\app.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:794:15)
    at Function.Module._load (internal/modules/cjs/loader.js:687:27)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1025:10)
    at internal/main/run_main_module.js:17:11 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

**Comment by kachkaev** [comment]
Hi @jp-2513. Seems like your question is not related to Next.js, so it's unlikely that someone will be able to help you here. Try asking your question on StackOverflow by providing reproduction steps in the highest possible detail. Alternatively, you can discuss the problem offline with your peers.

**Comment by balazsorban44** [comment]
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
