### ISSUE TITLE
running `next({dev: true}).prepare()` whilst testing results in an error

### ISSUE THREAD

**Issue by luujam2** [zeit/next.js#9636]
# Bug report

## Describe the bug

Running `next({dev: true}).prepare()` whilst testing results in an error. These tests were previously working prior to `v8.1.1-canary.1`

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

see repo: https://github.com/luujam2/next-test
1. run `npm install`
2. run `npm test`

## Expected behavior

Test should pass but instead an error occurs:

```
at Object.importAutoDllPlugin (node_modules/next/dist/build/webpack/plugins/dll-import.js:12:64)
  at webpackConfig.plugins.dev (node_modules/next/dist/build/webpack-config.js:264:56)
  at Object.getBaseWebpackConfig [as default] (node_modules/next/dist/build/webpack-config.js:283:15)
  at HotReloader.getWebpackConfig (node_modules/next/dist/server/hot-reloader.js:162:37)
```

## System information

- OS: macOs
- Version of Next.js: 9.1.4

## Additional context

The unit tests we write spins up an express server and the next app handles most of the requests. we're using `supertest` to go to certain urls and assert specific response statuses

**Comment by timneutkens** [comment]
It's probably best to mirror our test setup and boot up Next.js through the cli.

**Comment by balazsorban44** [comment]
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
