### ISSUE TITLE
Problem loading postcss example

### ISSUE THREAD

**Issue by rickyrauch** [zeit/next.js#964]
Hello,

I'm trying to run the postcss example and after running I'm getting this error: 

```Module build failed: TypeError: unknown: Duplicate declaration "_JSXStyle"
  1 | import _JSXStyle from "styled-jsx/style";
  2 | import React from "react";
> 3 | import _JSXStyle from "styled-jsx/style";
    |        ^
  4 | export default (function (props) {
  5 |   return React.createElement(
  6 |     "div",
    at File.buildCodeFrameError (/Users/ricardorauch/Sites/example.com/node_modules/babel-core/lib/transformation/file/index.js:431:15)
    at Scope.checkBlockScopedCollisions (/Users/ricardorauch/Sites/example.com/node_modules/babel-traverse/lib/scope/index.js:402:27)
    at Scope.registerBinding (/Users/ricardorauch/Sites/example.com/node_modules/babel-traverse/lib/scope/index.js:596:16)
    at Scope.registerDeclaration (/Users/ricardorauch/Sites/example.com/node_modules/babel-traverse/lib/scope/index.js:520:14)
    at Object.Declaration (/Users/ricardorauch/Sites/example.com/node_modules/babel-traverse/lib/scope/index.js:176:36)
    at NodePath._call (/Users/ricardorauch/Sites/example.com/node_modules/babel-traverse/lib/path/context.js:76:18)
    at NodePath.call (/Users/ricardorauch/Sites/example.com/node_modules/babel-traverse/lib/path/context.js:48:17)
    at NodePath.visit (/Users/ricardorauch/Sites/example.com/node_modules/babel-traverse```

Thanks!

**Comment by OlegLustenko** [comment]
I'd removed jsx tag from <style jsx> ... </style> and this issue was fixed as temporary solution.
You can figure out will it work for you.

**Comment by arunoda** [comment]
@OlegLustenko then it's not styled-jsx. It's a generic `<style/>` tag.

**Comment by OlegLustenko** [comment]
Yes Arunoda, you are right

**Comment by sarukuku** [comment]
What's the plan here with this?

**Comment by timneutkens** [comment]
https://github.com/giuseppeg/styled-jsx-postcss/issues/10
