### ISSUE TITLE
api-routes-micro example fails with error

### ISSUE THREAD

**Issue by stephen-dahl** [zeit/next.js#9643]
# Bug report

## Describe the bug

following this example fails with error `TypeError: resolver is not a function`
https://github.com/zeit/next.js/blob/master/examples/api-routes-micro/pages/api/posts.js

## To Reproduce

copy posts.js into pages/api
run next
visit pages/api/posts
see error in console

## Expected behavior

should return 200

## System information

- OS: Windows 10
- Browser (if applies) [e.g. chrome, safari]
- Version of Next.js: 9.1.4
## Additional context

**Comment by jamesmosier** [comment]
I wasn't able to reproduce on Windows 10 or Mac OS 10.15.1. 

I followed these steps:

1. `yarn create next-app --example api-routes-micro api-routes-micro-app`
2. `cd api-routes-micro-app`
3. `yarn dev`
4. Navigate to `http://localhost:3000/api/posts`
5. 200 response with JSON returned

Are these the same steps as you performed? I ask just to ensure I am trying to reproduce correctly. I see you said "copy posts.js into pages/api" so I wasn't sure if you had another project you had copied that file into.

**Comment by stephen-dahl** [comment]
No those are not the steps, as stated above:

1. copy posts.js into pages/api
2. run next
3. visit pages/api/posts
4. see error in console

**Comment by stephen-dahl** [comment]
pulbic/api/test.js
```
import micro from 'micro';

const posts = [
	{
		title: 'Next.js is awesome',
	},
	{
		title: 'API support is really great',
	},
];

export default micro((req, res) => {
	res.status(200).json(posts);
});
```

error
```
TypeError: resolver is not a function
    at Object.apiResolver (C:\Users\steph\PhpstormProjects\auth-proxy\node_modules\next\dist\next-server\server\api-utils.js:39:9)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async DevServer.handleApiRequest (C:\Users\steph\PhpstormProjects\auth-proxy\node_modules\next\dist\next-server\server\next-server.js:356:9)
    at async Object.fn (C:\Users\steph\PhpstormProjects\auth-proxy\node_modules\next\dist\next-server\server\next-server.js:283:21)
    at async Router.execute (C:\Users\steph\PhpstormProjects\auth-proxy\node_modules\next\dist\next-server\server\router.js:25:32)
    at async DevServer.run (C:\Users\steph\PhpstormProjects\auth-proxy\node_modules\next\dist\next-server\server\next-server.js:406:29)
```

**Comment by timneutkens** [comment]
Maybe you didn’t install micro@canary

**Comment by stephen-dahl** [comment]
I have 9.3.4 installed. does it have to be the canary?

**Comment by stephen-dahl** [comment]
Yep, installed canary and it works. why has that canary not been released since Jul 22, I think the poor birds have had all the time then needed to to squawk warning...

**Comment by spmsupun** [comment]
Why it doesn't show the actual error instead of these?

**Comment by balazsorban44** [comment]
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
