### ISSUE TITLE
"Cannot read property 'match' of undefined" when i run "next export'

### ISSUE THREAD

**Issue by flakesrc** [zeit/next.js#9674]
# Bug report

## Describe the bug

I have an error when I try to export as a static site, which is as follows:

```
σ (Server) page will be server rendered (i.e. getInitialProps)
* (Static File) page was prerendered as static HTML

> using build directory: /mnt/sdb2/Development/projects/webstation/webstation-client/.next
   copying "static build" directory
   launching 11 workers
TypeError: Cannot read property 'match' of undefined
     at /mnt/sdb2/Development/projects/webstation/webstation-client/node_modules/next/dist/export/index.js:11:35
     at Array.filter (<anonymous>)
     at _default (/mnt/sdb2/Development/projects/webstation/webstation-client/node_modules/next/dist/export/index.js:10:362)
     at processTicksAndRejections (internal / process / task_queues.js: 93: 5)
```
## To Reproduce

i just run the export command, like this:
`"export": "next build; next export"`

## Expected behavior

I would expect the site to export correctly after the "build" command

## System information

- Arch Linux / 5.4.2-arch1-1 
- "next": "9.1.4"
- node: v13.2.0 also v10.17.0

## Additional context

the `next.config.js` file:

```const httpPublic = require("./services/httpPublic");
const withCSS = require("@zeit/next-css");

const nextSettings = {
	exportPathMap: async () => {
		const postList = await httpPublic.getAllPosts();
		const pages = postList.reduce((pages, post) => {
			return {
				...pages,
				[post.meta.slug]: {
					page: "/[slug]",
					query: { slug: post.meta.slug },
				},
			};
		});
		return {
			"/": { page: "/" },
			...pages,
		};
	},
};

module.exports = withCSS(nextSettings);
```
Source Code: https://github.com/flakesrc/blog-client

**Comment by jamesmosier** [comment]
Does this also fail if you format the npm script like: `"export": "next build && next export"`?

**Comment by flakesrc** [comment]
> Does this also fail if you format the npm script like: `"export": "next build && next export"`?

sim

**Comment by jamesmosier** [comment]
I think one issue might be that you need to change [this line](https://github.com/flakesrc/blog-client/blob/ddd0e1c11120e371f187bd44a01fb97b918c37dc/next.config.js#L15) to be `}, {});` so that your `reduce` function returns an object.

**Comment by flakesrc** [comment]
> I think one issue might be that you need to change [this line](https://github.com/flakesrc/blog-client/blob/ddd0e1c11120e371f187bd44a01fb97b918c37dc/next.config.js#L15) to be `}, {});` so that your `reduce` function returns an object.
> 
> And then additionally [this line](https://github.com/flakesrc/blog-client/blob/ddd0e1c11120e371f187bd44a01fb97b918c37dc/next.config.js#L10) should be `` [`/${post.meta.slug}`]: { `` which is similar to the [with-static-export example](https://github.com/zeit/next.js/blob/8a370d1fff36051eca940c12be7df1485c6c5d58/examples/with-static-export/next.config.js#L15) formatting for dynamic paths.

add `{}` works.

**Comment by balazsorban44** [comment]
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
