### ISSUE TITLE
Browser back gives error--- TypeError: Cannot read property 'split' of undefined

### ISSUE THREAD

**Issue by amrit-sahoo** [zeit/next.js#9698]
### Description
My issue is similar to this..
https://github.com/zeit/next.js/issues/5604
I am using a custom server but I am not using any custom route handling. Even if remove the custom server and only run next i get this error while navigating back using browser back button.
As mentioned in https://github.com/zeit/next.js/blob/canary/errors/popstate-state-empty.md
I am not manipulating window.history in any place. Still I am getting this error.
I am using next/router <Link> for routing.

### Screenshot of error
<img width="1280" alt="Screenshot 2019-12-02 at 2 53 15 PM" src="https://user-images.githubusercontent.com/31152533/70593295-7d8b1280-1c02-11ea-9917-36deeb1efd5f.png">

This is the _app.js code

```import React from 'react';
import App from 'next/app';
import Router from 'next/router';
import Head from 'next/head';
import withRedux from 'withRedux';
import { Provider } from 'redux-bundler-react';
import { ThemeProvider } from 'emotion-theming';
import { Global } from '@emotion/core';
import themeOne from 'ui-web/theme';
import { getCookie } from 'modules/authentication';
import configureStore from '../../src/store';
import { persist, cacheVersions } from '../../src/common';
import { appWithTranslation } from '../../i18n';
const makeStore = initialState => configureStore(initialState);
class MyApp extends App {
  static async getInitialProps(props) {
    const { Component, ctx, router } = props;
    if (ctx.isServer && ctx.req.headers.cookie) {
      const token = getCookie('authToken', ctx.req);
      ctx.store.doSetAuthToken(token);
    }
    const pageProps = Component.getInitialProps
      ? await Component.getInitialProps(ctx, router.pathname)
      : {};
    return { pageProps };
  }
  render() {
    const { Component, store, pageProps } = this.props;
    return (
      <Provider store={store}>
        <ThemeProvider theme={themeOne}>
          <Head>
            <title>Learny</title>
            <link
              href='https://fonts.googleapis.com/css?family=Open+Sans:300,400,600&display=swap'
              rel='stylesheet'
            />
          </Head>
          <Global
            styles={theme => ({
              body: {
                margin: 0,
                overflowX: 'hidden',
                backgroundColor: theme.colors.background,
                a: {
                  textDecoration: 'none',
                },
              },
            })}
          />
          <Component {...pageProps} />
        </ThemeProvider>
      </Provider>
    );
  }
}
export default withRedux(makeStore, { debug: false, persist, cacheVersions })(
  appWithTranslation(MyApp)
);
```

### Routing code sample
```
const ProductCard: React.FC<Props> = (props: Props) => {
  const { product } = props;
  return(
    <Link href={`/learn/[productSeo]`} as={`/learn/${product.seoTitle}`}>
        <Box
          width='productCardW'
          bg='surface'
          sx={{
            boxShadow: 'default',
            cursor: 'pointer',
            position: 'relative',
            ':hover': {
              boxShadow: 'card.hover',
            },
          }}
        >
    </Link>
 );
}

const ProductList: React.FC<Props> = (props: Props) => {
  const { products, title, productType } = props;

  return (
    <>
      <Box height='productCardHEIGHT'>
        <AutoSizer>
          {({ height, width }) => (
            <Swiper
              ref={swiperRef}
              listHeight={height}
              totalLength={products.length}
              slideWidthSize={ITEM_SIZE}
              listLayout='horizontal'
              listWidth={width}
              renderData={products}
              renderItem={({ data, style }): JSX.Element => (
                <Box
                  style={{
                    ...style,
                    paddingTop: GUTTER_SIZE,
                  }}
                >
                  <ProductCard product={data} />
                </Box>
              )}
            />
          )}
        </AutoSizer>
      </Box>
    </>
  );
};
```

**Comment by Timer** [comment]
Could you please provide a full (minimal) code repository that reproduces this? Otherwise we won't be able to fix!

**Comment by amrit-sahoo** [comment]
@Timer  Thanks for your quick response.
Will send soon. Since I am working on a private repo I cant share the full repo. Will create a repo with sample code and add here.

**Comment by jasonbarry** [comment]
I've found this in my logs too – here's the minified code where it barfs:

```
"... value: function(e) {
if (!this.asPath) return!1;
var t = this.asPath.split("#"),
r = a(t,2),
n = r[0],
o = r[1],
i = e.split("#"), // e is undefined
s = a(i,2),
u = s[0],
c = s[1];
return!(!c||n!==u||o!==c)||n===u&&o!==c}},
{ key:"scrollToHash" ... 
```

**Comment by chirag04** [comment]
@jasonbarry were you able to resolve this? we are seeing the exact same error in our error reporting tool but cannot reproduce.

**Comment by kochis** [comment]
We are seeing this too, but only for production builds (does not seem to happen in development).

**Comment by kochis** [comment]
I still haven't been able to figure out to reproduce this outside of our app, but it's basically this line: https://github.com/zeit/next.js/blob/32ec4f691393038e69cd3f2e59c462879b83078d/packages/next/next-server/lib/router/router.ts#L549

`as` seems to be undefined in that case.

**Comment by kochis** [comment]
Ok, seems to be some 3rd party script on the site that was doing some wacky stuff the window history.

**Comment by Ace0611** [comment]
I am not able to solve it. 
Few observations.
Its splitting wrt '#' and '#' isnt present in the URL. So basically you are getting only one array element after splitting(Line 549 in kochis comment). So for other array element, i.e: newHash, its coming as undefined. Thats why we are getting that error. But if you append '#' at the end of your URL, It will work. Although its just a hack. I am waiting for actual solution.

> I still haven't been able to figure out to reproduce this outside of our app, but it's basically this line:
> 
> https://github.com/zeit/next.js/blob/32ec4f691393038e69cd3f2e59c462879b83078d/packages/next/next-server/lib/router/router.ts#L549
> 
> `as` seems to be undefined in that case.

I am not able to solve it. 
Few observations though.
Its splitting wrt '#' and '#' isn't present in the URL. So basically you are getting only one array element after splitting. So for other array element, i.e: newHash, its coming as undefined. Thats why we are getting that error. But if you append '#' at the end of your URL, It will work. Although its just a hack. I am waiting for actual solution.

**Comment by sea129** [comment]
> Ok, seems to be some 3rd party script on the site that was doing some wacky stuff the window history.

exactly, especially modules handle callback urls, they use window history to remove callback params in the url

**Comment by amrit-sahoo** [comment]
I checked and found out that one of a third-party library I had used was manipulating window history

**Comment by pmjhonwang** [comment]
```
TypeError: Cannot read property 'split' of undefined
  at onlyAHashChange(./node_modules/next/dist/next-server/lib/router/router.js:345:44)
  at ? (./node_modules/next/dist/next-server/lib/router/router.js:164:37)
  at new Promise(<anonymous>)
  at new F(./node_modules/core-js/library/modules/_export.js:36:1)
  at change(./node_modules/next/dist/next-server/lib/router/router.js:141:16)
  at replace(./node_modules/next/dist/next-server/lib/router/router.js:138:21)
  at Router.onPopState(./node_modules/next/dist/next-server/lib/router/router.js:49:18)
```
![image](https://user-images.githubusercontent.com/1998455/88366972-303c6980-cdbd-11ea-89bc-2e3891c48afe.png)

![image](https://user-images.githubusercontent.com/1998455/88366991-3c282b80-cdbd-11ea-93ea-b42c9b1c7813.png)

**Comment by jonasgroendahl** [comment]
i have a similiar thing using the `msal-browser`library for AzureAD auth, anyone know how to resolve this? working fine in dev environment

**Comment by ammarbrohi** [comment]
For anyone encountering this, it's likely cause by use of `ref={}`
Like in this case `ref={swiperRef}`

I just found it after hours of trial and error.

**Comment by balazsorban44** [comment]
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
