### ISSUE TITLE
next-server/server/api-utils (`.json()`) rejects with a boolean response

### ISSUE THREAD

**Issue by Timer** [zeit/next.js#9757]
```
UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_ARG_TYPE]: The "string" argument must be one of type string, Buffer, or ArrayBuffer. Received type boolean
    at Function.byteLength (buffer.js:705:11)
    at sendData (/Users/joe/Documents/Development/Work/invokestatic/social-poster/node_modules/next/dist/next-server/server/api-utils.js:185:44)
    at ServerResponse.res.send (/Users/joe/Documents/Development/Work/invokestatic/social-poster/node_modules/next/dist/next-server/server/api-utils.js:36:28)
    at sendJson (/Users/joe/Documents/Development/Work/invokestatic/social-poster/node_modules/next/dist/next-server/server/api-utils.js:198:9)
    at ServerResponse.res.json (/Users/joe/Documents/Development/Work/invokestatic/social-poster/node_modules/next/dist/next-server/server/api-utils.js:37:28)
    at module.exports../pages/api/logins/new.ts.__webpack_exports__.default (/Users/joe/Documents/Development/Work/invokestatic/social-poster/.next/server/static/development/pages/api/logins/new.js:324:12)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

This should return a proper 500 instead of unhandled rejection, or stringify as JSON correctly (latter preferred).

**Comment by balazsorban44** [comment]
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
