### ISSUE TITLE
Auth0 example builds with errors when target: serverless

### ISSUE THREAD

**Issue by hipstersmoothie** [zeit/next.js#9831]
# Examples bug report

## Example name

auth0

## Describe the bug

builds with errors

## To Reproduce

1. `npx create-next-app --example auth0 auth0`
2. Change target to serverless
3. `yarn build`

## Expected behavior

Should build with no errors

## Screenshots

```
Creating an optimized production build  

Compiled with warnings.

/Users/alisowski/Documents/kikbak-2/node_modules/got/source/request-as-event-emitter.js
Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

/Users/alisowski/Documents/kikbak-2/node_modules/next/dist/next-server/server/load-components.js
Critical dependency: the request of a dependency is an expression

/Users/alisowski/Documents/kikbak-2/node_modules/next/dist/next-server/server/load-components.js
Critical dependency: the request of a dependency is an expression

/Users/alisowski/Documents/kikbak-2/node_modules/next/dist/next-server/server/load-components.js
Critical dependency: the request of a dependency is an expression

/Users/alisowski/Documents/kikbak-2/node_modules/next/dist/next-server/server/load-components.js
Critical dependency: the request of a dependency is an expression

/Users/alisowski/Documents/kikbak-2/node_modules/next/dist/next-server/server/require.js
Critical dependency: the request of a dependency is an expression

/Users/alisowski/Documents/kikbak-2/node_modules/next/dist/next-server/server/require.js
Critical dependency: the request of a dependency is an expression

/Users/alisowski/Documents/kikbak-2/node_modules/encoding/lib/iconv-loader.js
Critical dependency: the request of a dependency is an expression

/Users/alisowski/Documents/kikbak-2/node_modules/keyv/src/index.js
Critical dependency: the request of a dependency is an expression

> Build error occurred
{ Error: The cookieSecret setting is empty or null
    at new CookieSessionStoreSettings (/Users/alisowski/Documents/kikbak-2/packages/test/.next/serverless/pages/advanced/ssr-profile.js:22328:19)
    at Object.createInstance [as default] (/Users/alisowski/Documents/kikbak-2/packages/test/.next/serverless/pages/advanced/ssr-profile.js:7667:29)
    at initAuth0 (/Users/alisowski/Documents/kikbak-2/packages/test/.next/serverless/pages/advanced/ssr-profile.js:21557:47)
    at Object.2NqA (/Users/alisowski/Documents/kikbak-2/packages/test/.next/serverless/pages/advanced/ssr-profile.js:2846:127)
    at __webpack_require__ (/Users/alisowski/Documents/kikbak-2/packages/test/.next/serverless/pages/advanced/ssr-profile.js:23:31)
    at Module.qWSV (/Users/alisowski/Documents/kikbak-2/packages/test/.next/serverless/pages/advanced/ssr-profile.js:36832:13)
    at __webpack_require__ (/Users/alisowski/Documents/kikbak-2/packages/test/.next/serverless/pages/advanced/ssr-profile.js:23:31)
    at module.exports.+3SS.strict (/Users/alisowski/Documents/kikbak-2/packages/test/.next/serverless/pages/advanced/ssr-profile.js:91:18)
    at Object.<anonymous> (/Users/alisowski/Documents/kikbak-2/packages/test/.next/serverless/pages/advanced/ssr-profile.js:94:10)
```

## System information

- OS: macOS
- Version of Next.js: 9.1.6

**Comment by galesky** [comment]
Hey there!

This is actually a problem with your .env file, you must have not defined the `SESSION_COOKIE_SECRET`

As it says in the [README](https://github.com/zeit/next.js/tree/canary/examples/auth0#local-development), the steps ou should have taken are:

1. npx create-next-app --example auth0 auth0
2. Change target to serverless
3. Create `.env` file from `.env.template` and set the variables
4. yarn build
**This way it should succeed.**

I'm taking a look right now at the code that actually handles the `initAuth0`. It seems that we have 2 options:
1. We could update the error message as a whole in https://github.com/auth0/nextjs-auth0/blob/master/src/session/cookie-store/settings.ts so that it is more descriptive, the issue would be that to really be 100% helpful we would need to actuallly reference the `.env` implementation that is used on the `examples/auth0`

2. We could handle this error scenario on the `examples/auth0` project itself, so we can show a really specifc and helpful error message, the drawback would be that we would need to duplicate some of the code that alcready exists in the `next-js/auth0` package.

Any thoughts ? @timneutkens

**Comment by hipstersmoothie** [comment]
I actually had an env file at some point but that is not what I was pointing out. The compiled-with warnings part is what went wrong. but this might not be an auth0 example issue.

**Comment by galesky** [comment]
Oh got it now!

This is related to : https://github.com/webpack/webpack/issues/196

tl:dr -> Webpack has issues budling dinamic 'require' statements. 
Although it says "Critical dependency" it is just a warning and means that as _webpack_ cant resolve those dependencies ahead of time correctly so it will assume it needs everything;

I'll take a look at those specific files to see if there is an easy fix (such as defining `DefinePlugin` or something like it)

**Comment by balazsorban44** [comment]
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
