### ISSUE TITLE
Error: Cannot find module '../cli/next-start' when installing node_modules in a Dockerfile

### ISSUE THREAD

**Issue by objmj-itminds** [zeit/next.js#9863]
# Bug report

I can't run my next project in production on Azure. Any insight would be helpful as I am working night/day on this somewhat critical issue.

The error I'm getting is this:
```bash
(node:67) UnhandledPromiseRejectionWarning: Error: Cannot find module '../cli/next-start'
 Require stack:
 - /home/site/wwwroot/node_modules/.bin/next
```

I Have setup my pipelines to build on BitBucket and publish it to Azure. But something seems to go missing underways.
I publish via Bitbucket Pipes wherein I bundle the entire app into a single zip file. 
If I take this zip file and look in the .bin/next file I have this 

```bash
#!/usr/bin/env node
"use strict";var _index=_interopRequireDefault(require("next/dist/compiled/arg/index.js"));function _interopRequireDefault(obj){return obj&&obj.__esModule?obj:{default:obj};}function _getRequireWildcardCache(){if(typeof WeakMap!=="function")return null;var cache=new WeakMap();_getRequireWildcardCache=function(){return cache;};return cache;}function _interopRequireWildcard(obj){if(obj&&obj.__esModule){return obj;}if(obj===null||typeof obj!=="object"&&typeof obj!=="function"){return{default:obj};}var cache=_getRequireWildcardCache();if(cache&&cache.has(obj)){return cache.get(obj);}var newObj={};var hasPropertyDescriptor=Object.defineProperty&&Object.getOwnPropertyDescriptor;for(var key in obj){if(Object.prototype.hasOwnProperty.call(obj,key)){var desc=hasPropertyDescriptor?Object.getOwnPropertyDescriptor(obj,key):null;if(desc&&(desc.get||desc.set)){Object.defineProperty(newObj,key,desc);}else{newObj[key]=obj[key];}}}newObj.default=obj;if(cache){cache.set(obj,newObj);}return newObj;}['react','react-dom'].forEach(dependency=>{try{// When 'npm link' is used it checks the clone location. Not the project.
require.resolve(dependency);}catch(err){// tslint:disable-next-line
console.warn(`The module '${dependency}' was not found. Next.js requires that you include it in 'dependencies' of your 'package.json'. To add it, run 'npm install --save ${dependency}'`);}});const defaultCommand='dev';const commands={build:async()=>await Promise.resolve().then(()=>_interopRequireWildcard(require('../cli/next-build'))).then(i=>i.nextBuild),start:async()=>await Promise.resolve().then(()=>_interopRequireWildcard(require('../cli/next-start'))).then(i=>i.nextStart),export:async()=>await Promise.resolve().then(()=>_interopRequireWildcard(require('../cli/next-export'))).then(i=>i.nextExport),dev:async()=>await Promise.resolve().then(()=>_interopRequireWildcard(require('../cli/next-dev'))).then(i=>i.nextDev),telemetry:async()=>await Promise.resolve().then(()=>_interopRequireWildcard(require('../cli/next-telemetry'))).then(i=>i.nextTelemetry)};const args=(0,_index.default)({// Types
'--version':Boolean,'--help':Boolean,'--inspect':Boolean,// Aliases
'-v':'--version','-h':'--help'},{permissive:true});// Version is inlined into the file using taskr build pipeline
if(args['--version']){// tslint:disable-next-line
console.log(`Next.js v${"9.1.6"}`);process.exit(0);}// Check if we are running `next <subcommand>` or `next`
const foundCommand=Boolean(commands[args._[0]]);// Makes sure the `next <subcommand> --help` case is covered
// This help message is only showed for `next --help`
if(!foundCommand&&args['--help']){// tslint:disable-next-line
console.log(`
    Usage
      $ next <command>

    Available commands
      ${Object.keys(commands).join(', ')}

    Options
      --version, -v   Version number
      --inspect       Enable the Node.js inspector
      --help, -h      Displays this message

    For more information run a command with the --help flag
      $ next build --help
  `);process.exit(0);}const command=foundCommand?args._[0]:defaultCommand;const forwardedArgs=foundCommand?args._.slice(1):args._;if(args['--inspect'])throw new Error(`Use env variable NODE_OPTIONS instead: NODE_OPTIONS="--inspect" next ${command}`);// Make sure the `next <subcommand> --help` case is covered
if(args['--help']){forwardedArgs.push('--help');}const defaultEnv=command==='dev'?'development':'production';process.env.NODE_ENV=process.env.NODE_ENV||defaultEnv;// this needs to come after we set the correct NODE_ENV or
// else it might cause SSR to break
const React=require('react');if(typeof React.Suspense==='undefined'){throw new Error(`The version of React you are using is lower than the minimum required version needed for Next.js. Please upgrade "react" and "react-dom": "npm install --save react react-dom" https://err.sh/zeit/next.js/invalid-react-version`);}commands[command]().then(exec=>exec(forwardedArgs));if(command==='dev'){const{CONFIG_FILE}=require('../next-server/lib/constants');const{watchFile}=require('fs');watchFile(`${process.cwd()}/${CONFIG_FILE}`,(cur,prev)=>{if(cur.size>0||prev.size>0){// tslint:disable-next-line
console.log(`\n> Found a change in ${CONFIG_FILE}. Restart the server to see the changes in effect.`);}});}
``` 
Which does not compare to whats on my local machine 
``` bash
#!/bin/sh
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")

case `uname` in
    *CYGWIN*) basedir=`cygpath -w "$basedir"`;;
esac

if [ -x "$basedir/node" ]; then
  "$basedir/node"  "$basedir/../next/dist/bin/next" "$@"
  ret=$?
else 
  node  "$basedir/../next/dist/bin/next" "$@"
  ret=$?
fi
exit $ret
```  

So it would appear to be some sort of misinstallation issue

## Logs Where the error occours 
```bash
2019-12-28T19:24:03.473844165Z Running #!/bin/sh
2019-12-28T19:24:03.473874765Z 
2019-12-28T19:24:03.473880765Z # Enter the source directory to make sure the script runs where the user expects
2019-12-28T19:24:03.473885665Z cd "/home/site/wwwroot"
2019-12-28T19:24:03.473890465Z 
2019-12-28T19:24:03.473894665Z export NODE_PATH=$(npm root --quiet -g):$NODE_PATH
2019-12-28T19:24:03.473899065Z if [ -z "$PORT" ]; then
2019-12-28T19:24:03.473903365Z 		export PORT=8080
2019-12-28T19:24:03.473907965Z fi
2019-12-28T19:24:03.473911965Z 
2019-12-28T19:24:03.473916065Z npm start
2019-12-28T19:24:05.610633815Z 
2019-12-28T19:24:05.610662115Z > user-client@2.0.0 start /home/site/wwwroot
2019-12-28T19:24:05.610668115Z > next start
2019-12-28T19:24:05.610672415Z 
2019-12-28T19:24:05.803182399Z (node:67) UnhandledPromiseRejectionWarning: Error: Cannot find module '../cli/next-start'
2019-12-28T19:24:05.803214599Z Require stack:
2019-12-28T19:24:05.803220899Z - /home/site/wwwroot/node_modules/.bin/next
2019-12-28T19:24:05.803225399Z     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:794:15)
2019-12-28T19:24:05.803229799Z     at Function.Module._load (internal/modules/cjs/loader.js:687:27)
2019-12-28T19:24:05.803234199Z     at Module.require (internal/modules/cjs/loader.js:849:19)
2019-12-28T19:24:05.803247099Z     at require (internal/modules/cjs/helpers.js:74:18)
2019-12-28T19:24:05.803251999Z     at /home/site/wwwroot/node_modules/.bin/next:4:431
2019-12-28T19:24:05.803256299Z     at async Object.start (/home/site/wwwroot/node_modules/.bin/next:4:374)
2019-12-28T19:24:05.803555900Z (node:67) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
2019-12-28T19:24:05.803633800Z (node:67) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

## Steps to reproduce
I am able to replicate these steps with a simple Dockerfile
```Dockerfile
FROM node:12-slim
WORKDIR /install
COPY package.json .
COPY package-lock.json .

RUN npm ci

CMD ["cat", "/install/node_modules/.bin/next"]
```
And this here will create what appears to be the wrong .bin/next file.

## My dependency versions
```
"next": "^9.1.6",
"react": "16.12.0",
"react-dom": "16.12.0",
```

**Comment by objmj-itminds** [comment]
Might be related to#7288 I will try a canary version now to see.

**Comment by timneutkens** [comment]
Please follow the issue template.

https://github.com/zeit/next.js/issues/new/choose

https://github.com/zeit/next.js/issues/new?template=8.Question_about_next.md

```
# Question about Next.js

GitHub Issues are reserved for Bug reports and Feature requests. The best place to get your question answered is to post it on https://spectrum.chat/next-js.
```

**Comment by balazsorban44** [comment]
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
