### ISSUE TITLE
Cannot read property 'replace' of undefined

### ISSUE THREAD

**Issue by sedubois** [zeit/next.js#990]
I tried to upgrade from next@2.0.0-beta.20 but something changed in the beta.21 specifically, I get the stack trace below when running `yarn dev`. Here is my app: https://github.com/relatenow/relate

<details>
TypeError: Cannot read property 'replace' of undefined
    at toRoute (/Users/sdubois/Documents/relate/node_modules/next/dist/lib/router/router.js:618:14)
    at new Router (/Users/sdubois/Documents/relate/node_modules/next/dist/lib/router/router.js:85:19)
    at renderPage (/Users/sdubois/Documents/relate/node_modules/next/dist/server/render.js:143:25)
    at /Users/sdubois/Documents/relate/node_modules/next/dist/server/document.js:56:22
    at renderStatic (/Users/sdubois/Documents/relate/node_modules/glamor/lib/server.js:18:14)
    at Function.getInitialProps (/Users/sdubois/Documents/relate/node_modules/next/dist/server/document.js:55:45)
    at _callee$ (/Users/sdubois/Documents/relate/node_modules/next/dist/lib/utils.js:36:30)
    at tryCatch (/Users/sdubois/Documents/relate/node_modules/regenerator-runtime/runtime.js:64:40)
    at Generator.invoke [as _invoke] (/Users/sdubois/Documents/relate/node_modules/regenerator-runtime/runtime.js:355:22)
    at Generator.prototype.(anonymous function) [as next] (/Users/sdubois/Documents/relate/node_modules/regenerator-runtime/runtime.js:116:21)
(node:4021) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 3): TypeError: Cannot read property 'replace' of undefined
</details>

**Comment by timneutkens** [comment]
Can you upgrade to `beta.23` and check if it's functioning there?

**Comment by sedubois** [comment]
@timneutkens Sorry I forgot to precise that: no it doesn't work either. Then I backtracked in previous betas to pinpoint that the issue appeared in beta.21.

**Comment by arunoda** [comment]
@sedubois here's the problem: https://github.com/relatenow/relate/blob/master/server.js#L62
For the third argument of `handle` you need to pass either nothing or a parsed url object.

**Comment by arunoda** [comment]
@timneutkens shall we throw an detailed error if we didn't get a parsedUrl but something else for the third argument of `handle`.

**Comment by timneutkens** [comment]
@arunoda we should actually handle that case right, I mean, parse it ourselves if it's not a valid object. We actually already do that here https://github.com/zeit/next.js/blob/master/server/index.js#L37 but not well enough I guess. I'll fix it 👍

**Comment by sedubois** [comment]
Thanks, that was the issue.

**Comment by arunoda** [comment]
@timneutkens This is a common problem. (I got that too)
In this case, if we didn't get a proper parsedUrl object, we need should throw an error with a good error message.
