### ISSUE TITLE
Module not found: Can't resolve 'fs'

### ISSUE THREAD

**Issue by Lebed-kun** [zeit/next.js#9976]
# Bug report

## Describe the bug

I can't realise how I got this bug. Earlier all routes was proceed as expected.

```
./node_modules/destroy/index.js
Module not found: Can't resolve 'fs' in 'D:\Docs\projects\chi_imageboard\web-frontend\node_modules\destroy'
Could not find files for /boards in .next/build-manifest.json
ModuleNotFoundError: Module not found: Error: Can't resolve 'fs' in 'D:\Docs\projects\chi_imageboard\web-frontend\node_modules\destroy'
    at D:\Docs\projects\chi_imageboard\web-frontend\node_modules\webpack\lib\Compilation.js:925:10
    at D:\Docs\projects\chi_imageboard\web-frontend\node_modules\webpack\lib\NormalModuleFactory.js:401:22
    at D:\Docs\projects\chi_imageboard\web-frontend\node_modules\webpack\lib\NormalModuleFactory.js:130:21
    at D:\Docs\projects\chi_imageboard\web-frontend\node_modules\webpack\lib\NormalModuleFactory.js:224:22
    at D:\Docs\projects\chi_imageboard\web-frontend\node_modules\neo-async\async.js:2830:7
    at D:\Docs\projects\chi_imageboard\web-frontend\node_modules\neo-async\async.js:6877:13
    at D:\Docs\projects\chi_imageboard\web-frontend\node_modules\webpack\lib\NormalModuleFactory.js:214:25
    at D:\Docs\projects\chi_imageboard\web-frontend\node_modules\enhanced-resolve\lib\Resolver.js:213:14
    at D:\Docs\projects\chi_imageboard\web-frontend\node_modules\enhanced-resolve\lib\Resolver.js:285:5
    at eval (eval at create (D:\Docs\projects\chi_imageboard\web-frontend\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:15:1)
    at D:\Docs\projects\chi_imageboard\web-frontend\node_modules\enhanced-resolve\lib\UnsafeCachePlugin.js:44:7
    at D:\Docs\projects\chi_imageboard\web-frontend\node_modules\enhanced-resolve\lib\Resolver.js:285:5
    at eval (eval at create (D:\Docs\projects\chi_imageboard\web-frontend\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:15:1)
    at D:\Docs\projects\chi_imageboard\web-frontend\node_modules\enhanced-resolve\lib\Resolver.js:285:5
    at eval (eval at create (D:\Docs\projects\chi_imageboard\web-frontend\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:27:1)
    at D:\Docs\projects\chi_imageboard\web-frontend\node_modules\enhanced-resolve\lib\DescriptionFilePlugin.js:67:43
ModuleNotFoundError: Module not found: Error: Can't resolve 'fs' in 'D:\Docs\projects\chi_imageboard\web-frontend\node_modules\destroy'
    at D:\Docs\projects\chi_imageboard\web-frontend\node_modules\webpack\lib\Compilation.js:925:10
    at D:\Docs\projects\chi_imageboard\web-frontend\node_modules\webpack\lib\NormalModuleFactory.js:401:22
    at D:\Docs\projects\chi_imageboard\web-frontend\node_modules\webpack\lib\NormalModuleFactory.js:130:21
    at D:\Docs\projects\chi_imageboard\web-frontend\node_modules\webpack\lib\NormalModuleFactory.js:224:22
    at D:\Docs\projects\chi_imageboard\web-frontend\node_modules\neo-async\async.js:2830:7
    at D:\Docs\projects\chi_imageboard\web-frontend\node_modules\neo-async\async.js:6877:13
    at D:\Docs\projects\chi_imageboard\web-frontend\node_modules\webpack\lib\NormalModuleFactory.js:214:25
    at D:\Docs\projects\chi_imageboard\web-frontend\node_modules\enhanced-resolve\lib\Resolver.js:213:14
    at D:\Docs\projects\chi_imageboard\web-frontend\node_modules\enhanced-resolve\lib\Resolver.js:285:5
    at eval (eval at create (D:\Docs\projects\chi_imageboard\web-frontend\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:15:1)
    at D:\Docs\projects\chi_imageboard\web-frontend\node_modules\enhanced-resolve\lib\UnsafeCachePlugin.js:44:7
    at D:\Docs\projects\chi_imageboard\web-frontend\node_modules\enhanced-resolve\lib\Resolver.js:285:5
    at eval (eval at create (D:\Docs\projects\chi_imageboard\web-frontend\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:15:1)
    at D:\Docs\projects\chi_imageboard\web-frontend\node_modules\enhanced-resolve\lib\Resolver.js:285:5
    at eval (eval at create (D:\Docs\projects\chi_imageboard\web-frontend\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:27:1)
    at D:\Docs\projects\chi_imageboard\web-frontend\node_modules\enhanced-resolve\lib\DescriptionFilePlugin.js:67:43
ModuleNotFoundError: Module not found: Error: Can't resolve 'fs' in 'D:\Docs\projects\chi_imageboard\web-frontend\node_modules\destroy'
    at D:\Docs\projects\chi_imageboard\web-frontend\node_modules\webpack\lib\Compilation.js:925:10
    at D:\Docs\projects\chi_imageboard\web-frontend\node_modules\webpack\lib\NormalModuleFactory.js:401:22
    at D:\Docs\projects\chi_imageboard\web-frontend\node_modules\webpack\lib\NormalModuleFactory.js:130:21
    at D:\Docs\projects\chi_imageboard\web-frontend\node_modules\webpack\lib\NormalModuleFactory.js:224:22
    at D:\Docs\projects\chi_imageboard\web-frontend\node_modules\neo-async\async.js:2830:7
    at D:\Docs\projects\chi_imageboard\web-frontend\node_modules\neo-async\async.js:6877:13
    at D:\Docs\projects\chi_imageboard\web-frontend\node_modules\webpack\lib\NormalModuleFactory.js:214:25
    at D:\Docs\projects\chi_imageboard\web-frontend\node_modules\enhanced-resolve\lib\Resolver.js:213:14
    at D:\Docs\projects\chi_imageboard\web-frontend\node_modules\enhanced-resolve\lib\Resolver.js:285:5
    at eval (eval at create (D:\Docs\projects\chi_imageboard\web-frontend\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:15:1)
    at D:\Docs\projects\chi_imageboard\web-frontend\node_modules\enhanced-resolve\lib\UnsafeCachePlugin.js:44:7
    at D:\Docs\projects\chi_imageboard\web-frontend\node_modules\enhanced-resolve\lib\Resolver.js:285:5
    at eval (eval at create (D:\Docs\projects\chi_imageboard\web-frontend\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:15:1)
    at D:\Docs\projects\chi_imageboard\web-frontend\node_modules\enhanced-resolve\lib\Resolver.js:285:5
    at eval (eval at create (D:\Docs\projects\chi_imageboard\web-frontend\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:27:1)
    at D:\Docs\projects\chi_imageboard\web-frontend\node_modules\enhanced-resolve\lib\DescriptionFilePlugin.js:67:43
```

## To Reproduce

1. Run `npm run dev` in console;
2. Go to '/boards/b/' route in browser;
3. See the error;

Repo of website application: [https://github.com/Lebed-kun/imageboard/tree/master/web-frontend](url)

## Expected behavior

Get rendered HTML page by "/boards/:abbr" route with ant styles etc.

## Screenshots

![Screenshot_96](https://user-images.githubusercontent.com/7430231/71895294-1f524080-316a-11ea-8585-981502361912.png)

## System information

- OS: Windows 10 x64
- Browser: Opera 65.0.3467.78
- Version of Next.js: 9.1.7

**Comment by Lebed-kun** [comment]
I added this code to `next.config.js` to exclude node modules from client build:
```
if (!isServer) {
config.node = {
fs : 'empty',
net :'empty',
express: "empty'
}
}
```

But then I got this warning:

```
./node_modules/express/lib/view.js
Critical dependency: the request of a dependency is an expression
```

And the error `TypeError: Cannot read property 'prototype' of undefined`:
![Screenshot_97](https://user-images.githubusercontent.com/7430231/71897944-7871a280-3171-11ea-9a5a-c1b820fd7336.png)

**Comment by timneutkens** [comment]
https://github.com/Lebed-kun/imageboard/blob/master/web-frontend/pages/boards.js#L16

You imported router from express instead of `next/router`. `import Router from 'next/router'`

**Comment by Lebed-kun** [comment]
Thank you :3

**Comment by balazsorban44** [comment]
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
