### ISSUE TITLE
Can't get with-apollo to work with SSR on another GraphQL endpoint

### ISSUE THREAD

**Issue by nicholasalanbrown** [zeit/next.js#9995]
# Examples bug report

## Example name

Provide the example name
`with-apollo`

## Describe the bug

I can run the `with-apollo` example successfully locally but as soon as I try to change the `uri` in `apollo.js`, I can only get client-side queries to work. I am able to `curl` the same GraphQL` endpoint and fetch data with no problem. The error I get is:

```
Error while running `getDataFromTree` { Error: Network error: Unexpected token < in JSON at position 0
    at new ApolloError (/Users/nicholasbrown/Source/with-apollo-app/node_modules/apollo-client/bundle.umd.js:92:26)
    at /Users/nicholasbrown/Source/with-apollo-app/node_modules/apollo-client/bundle.umd.js:1587:34
    at /Users/nicholasbrown/Source/with-apollo-app/node_modules/apollo-client/bundle.umd.js:2007:15
    at Set.forEach (<anonymous>)
    at /Users/nicholasbrown/Source/with-apollo-app/node_modules/apollo-client/bundle.umd.js:2005:26
    at Map.forEach (<anonymous>)
    at QueryManager.broadcastQueries (/Users/nicholasbrown/Source/with-apollo-app/node_modules/apollo-client/bundle.umd.js:2003:20)
    at /Users/nicholasbrown/Source/with-apollo-app/node_modules/apollo-client/bundle.umd.js:1482:29
    at process._tickCallback (internal/process/next_tick.js:68:7)
  graphQLErrors: [],
  networkError:
   { ServerParseError: Unexpected token < in JSON at position 0
       at JSON.parse (<anonymous>)
       at /Users/nicholasbrown/Source/with-apollo-app/node_modules/apollo-link-http-common/lib/index.js:35:25
       at process._tickCallback (internal/process/next_tick.js:68:7)
     name: 'ServerParseError',
     response:
      Response {
        size: 0,
        timeout: 0,
        [Symbol(Body internals)]: [Object],
        [Symbol(Response internals)]: [Object] },
     statusCode: 404,
     bodyText:
      '<!DOCTYPE html>\n<html lang="en">\n<head>\n<meta charset="utf-8">\n<title>Error</title>\n</head>\n<body>\n<pre>Cannot POST /graphql</pre>\n</body>\n</html>\n' },
  message: 'Network error: Unexpected token < in JSON at position 0',
  extraInfo: undefined }
```

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Clone the `with-apollo` example
2. Change the `uri` in `apollo.js` to another GraphQL endpoint (mine is also not hosted at the same origin)
3. Update the client-side queries to successfully fetch client-side data
4. Probably see the same error in SSR?

## Expected behavior

I should be able to use the example with minimal changes for any other GraphQL endpoint (mine is running with `@nestjs/graphql`

## System information

- OS: macOS
- Browser Chrome
- Version of Next.js: `latest`

## Additional context

It seems to be trying to `POST` to `/graphql` (on the same server?) even though all I've done is change the `uri` defined in `apollo.js`

**Comment by rafaelalmeidatk** [comment]
The example is fine, the issue seems to be with your server that isn't handing the request correctly:
```
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <title>Error</title>
  </head>
  <body>
    <pre>Cannot POST /graphql</pre>
  </body>
</html>

```

**Comment by balazsorban44** [comment]
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
